### ISSUE TITLE
Small visual glitch at top of photo view

### ISSUE THREAD

**Issue by oatberry** [ccrama/Slide#1000]
[There's a thin black bar](http://i.imgur.com/mC9SmPi.jpg) between the top of the app and the status bar in a photo view. @ccrama can replicate.

**Comment by ccrama** [comment]
Woo issue 1000! You officially broke Slide!

**Comment by oatberry** [comment]
\o/ can I have a refund?

**Comment by ccrama** [comment]
If anything you owe me for breaking slide! 

Just kidding! I'll fix the bug for you instead, fair trade?

**Comment by oatberry** [comment]
It's a deal.

**Comment by Alexendoo** [comment]
On a similar vein, video view has a similar thing going on, looks like the background being created isn't large enough

![image](https://cloud.githubusercontent.com/assets/1830331/13096920/f441a9d6-d514-11e5-849f-f36b349b25bf.png)

**Comment by ccrama** [comment]
Every activity that extends FullScreenActivity will have this bug

**Comment by ccrama** [comment]
Fixed with my last commit
