### ISSUE TITLE
Seems to crash when opening a album w/ Vertical album settings

### ISSUE THREAD

**Issue by brentgsw** [ccrama/Slide#1002]
I deselected "horizontal album", and was getting crashes when trying to access albums via the picture preview. Switching back to horizontal settings, stopped the crashes.

**Comment by ccrama** [comment]
I cannot reproduce this, but it might have been a bug that was fixed with my latest commits and push to the Play Store

**Comment by brentgsw** [comment]
Hmm, maybe it was an old version or just some specific albums. Anyways, seems to be working now.
