### ISSUE TITLE
Alternate spoiler style not supported

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#1004]
A lot of subreddits implement spoilers like this `[spoiler text](/spoiler)`. Can you please implement that spoiler style? Here's a post where some people are using that style. https://reddit.com/r/modhelp/comments/15m7j4/how_do_you_implement_spoiler_tags_in_your/

**Comment by ccrama** [comment]
It would be close to impossible to implement, as you cannot rely on the css tags to exist on every subreddit or be the same on every subreddit. Sorry!

**Comment by kufii** [comment]
OK, but it's extremely common. I'd say around 60% of subreddits use that spoiler style... You really can rely on spoilers being in the style you implemented and the style I just outlined

**Comment by kufii** [comment]
Sorry, didn't notice that markdown formatted my post

The style is

    [Spoiler text](/spoiler)

Again it's super common and I would argue that you can't consider your app to have the spoilers feature if you haven't implemented this style

**Comment by l3d00m** [comment]
Do you have a few example subreddits where this is implemented? I only saw /s or #s so far

**Comment by kufii** [comment]
/r/iama, /r/askreddit, /r/startrek

**Comment by Deadleg** [comment]
Might not be too hard, just need to check if `href==/spoiler || /s || /sp`.

**Comment by Alexendoo** [comment]
Some subreddits also use #sp

**Comment by alexoj** [comment]
Please also add /n

**Comment by ccrama** [comment]
These should all be supported now. If you find any more, feel free to re-open
