### ISSUE TITLE
Slide reloads frontpage when entering Settings and exiting

### ISSUE THREAD

**Issue by anonymous-user** [ccrama/Slide#1007]
If I open a subreddit, enter Settings, then exit, Slide will load the frontpage instead of the subreddit I was reading.

**Comment by Alexendoo** [comment]
What versions of Slide/Android are you running?

**Comment by ccrama** [comment]
Yes that is expected behavior. It has to restart the activity is order to apply the new settings

**Comment by l3d00m** [comment]
@ccrama It opens the front page instead of the sub he was browsing.

**Comment by Alexendoo** [comment]
After a little testing, it appears this happens when subreddit tabs are disabled

**Comment by anonymous-user** [comment]
Would it be possible to reload the activity and then reload the subreddit you were viewing too?

**Comment by Alexendoo** [comment]
It should be loading from the subreddit you were last on, and it does provided you have subreddit tabs enabled. With it disabled is a bug

**Comment by anonymous-user** [comment]
Yes I do have subreddit tabs disabled.

**Comment by ccrama** [comment]
Oh, that's the issue then. I don't and it all seemed to work fine for me haha. Will look into it!

**Comment by ccrama** [comment]
Fixed!
