### ISSUE TITLE
Option to disable image previews on text posts

### ISSUE THREAD

**Issue by anonymous-user** [ccrama/Slide#1008]
If a text post includes an image link, Slide will show a preview at the top in comment view. I have a request that clicking the image should open it. Currently I have to click the image link within the post.

**Comment by Alexendoo** [comment]
That seems a little out of place to me within the current way things are done, the image preview in all cases currently takes you to the target of the post. For example if it's an album it takes you to the album, an article will take you to an article, etc. 

In my opinion it would be a bit counterintuitive to have an exception for self posts for this UI pattern

**Comment by ccrama** [comment]
Yeah that was why I didn't make it clickable.  Usually the content is a link and not an image, and I have no way to tell what link that would be.

**Comment by anonymous-user** [comment]
Would it be possible to have an option to disable that preview then? It just seems strange to have on self posts.

**Comment by SZE2** [comment]
I feel that it should be an option to turn it off, as many times the linked image is only tangentially related to the self post content.

Maybe rename the issue?

Thanks!

**Comment by ccrama** [comment]
Done, now in Settings > Comment settings

**Comment by UnicodeAlt255** [comment]
@ccrama does this setting still exist?
