### ISSUE TITLE
Well I was late to the 1,000 party. Here's some cake!

### ISSUE THREAD

**Issue by hary585** [ccrama/Slide#1010]
─────────────────────█
─────────────────────██
────────────────────██░█
──────────────────███▒░█
──────────────────█▒▒░█
────────────────────█
──────────────────████
─────────────────████░█
──────────────────█░░░█
──────────────────██░██
──────────███████▓███░█▓▓███
───────███▒▒▒▒▒▒▒▒██░████▒▒█████
──────███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒███
─────██░██████████▒▒▒▒▒▒▒▒▒█████░██
─────█░░░░░█░░░░░███████████░░░░░░█
─────██░░░███░░░░█░░░░█░░░░░██░░░██
──────█░░██▒██░░███░░███░░░████░░█
───────█░█▒▒▒█░██▒█░██▒██░░██▒█░█
────────██▒▒▒▒█▒▒▒▒██▒▒▒▒██▒▒▒▒█
───██████░███████▒▒▒▒▒▒▒▒▒▒▒██▒███████
─████▓▓██░░░░████████████████████▓▓▓▓██
███▓▓▓██████░░░░░░░░░░░░░░░░░░░████▓▓▓██
──███▓▓▓▓▓██████░░░░░░░░░░░░██████▓▓▓███
────████▓▓▓▓▓▓▓██████████████▓▓▓▓▓▓███
─────█████████▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓████
────────███████████████████████

**Comment by xnaas** [comment]
Not an issue.

**Comment by hary585** [comment]
Still an issue
