### ISSUE TITLE
Submit button disappears while editing a long comment

### ISSUE THREAD

**Issue by daniele-salvagni** [ccrama/Slide#1011]
The `Submit` button disappears when the length of the comment being edited reaches the full height of the screen. I added a couple of screenshots showing the issue:

![Screenshot 1](http://i.imgur.com/q6u5pPu.png)

![Screenshot 2](http://i.imgur.com/vFQ8XSy.png)

**Comment by ccrama** [comment]
You can actually scroll up on it

**Comment by ccrama** [comment]
Fixed!
