### ISSUE TITLE
Rotating screen vertically while watching a video refreshes subreddit

### ISSUE THREAD

**Issue by miStank** [ccrama/Slide#1013]
If screen is rotated vertically while watching a video,after leaving said video the posts are refreshed. 

To replicate from portrait mode:
  1. Scroll down the subreddit
  2. Open video
  3. Rotate screen horizontally then vertically
  4. Leave video

To replicate from landscape:
  1. Scroll down
  2. Open video
  3. Rotate vertically 
  4. Leave video

**Comment by Alexendoo** [comment]
What versions of slide/android are you running?

**Comment by miStank** [comment]
V4.5.1

**Comment by ccrama** [comment]
This isn't an issue with v4.6
