### ISSUE TITLE
Some images not showing up full size in comments of posts

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#1014]
There are some images that are not showing up full size, and are instead showing up in thumbnail mode. I don't remember ever having seen this happen until today.

Here's an example post:
https://reddit.com/r/pcgaming/comments/45z9y1/update_hi_im_the_guy_who_posted_about_being_vac/

**Comment by kufii** [comment]
Sorry wrong linkhttps://reddit.com/r/meirl/comments/45y549/meirl/

**Comment by Alexendoo** [comment]
If the images are low resolution they won't be given a large image preview, that image is only 80px high so I doubt it passes the bar

**Comment by kufii** [comment]
It's a short image but its long enough that I wouldn't call it low resolution, it would look perfectly fine full size

**Comment by ccrama** [comment]
The issue is when I request the bitmap size, it doesn't exist yet and returns 0, and then the height gets set to 0. Fixing right now!

**Comment by ccrama** [comment]
Fixe!
