### ISSUE TITLE
Duplicate posts shown All

### ISSUE THREAD

**Issue by tehbra1n** [ccrama/Slide#1016]
Slide version: 4.6.0-83-e62230c
Android version:6.0.1 Feb security patch

I'm often seeing duplicate posts when browsing All.  Sometimes with only one post separating them.  Some times a sequence of posts are repeated with a few other posts between them.  This is sorting by Hot.  Nexus 6p/7 (2013)/9 all on same Android and slide version.

![screenshot_20160217-174546](https://cloud.githubusercontent.com/assets/17303996/13128154/ce99366c-d5a1-11e5-9fb0-f0ed72b6077a.png)

**Comment by stokholm** [comment]
This happens in frontpage for me also. I don't browse single subs very often, so can't rule out it happens in those too.

**Comment by ccrama** [comment]
It happens in every subreddit after loading more. It's an issue with the Reddit API, and the fix for it is quite resource intensive unfortunately (cross checking the name against all other submissions loaded). Will be looking into it though!

**Comment by ccrama** [comment]
Should be fixed now
