### ISSUE TITLE
Vertical Album Crashes With Some  (#1002)

### ISSUE THREAD

**Issue by colewinfield** [ccrama/Slide#1018]
Slide version: 4.6.0-87-6ecbafd (latest version)
Android version: 6.0.1

Here's an exampl  that crashes the client with vertical album enabled:

https://reddit.com/r/DumpsterDiving/comments/46bqo3/good_stuff/

It was reported under issue #1002, but it looks closed prematurely, because it happens with the latest edition.

**Comment by colewinfield** [comment]
I think it might have something to do with the album containg text captions.

**Comment by l3d00m** [comment]
That should be fixed with the integration of the new imgur api. That will be merged when we get back a reply from the imgur team.

**Comment by colewinfield** [comment]
All right, thanks for the heads-up. You guys are doing an excellent job with the development of this app!

**Comment by l3d00m** [comment]
Thanks for the nice words!

**Comment by ccrama** [comment]
Has been fixed!
