### ISSUE TITLE
Weird voting behavior

### ISSUE THREAD

**Issue by anandroiduser** [ccrama/Slide#1019]
- [x] If you vote on a post, scroll it out of the view, the scroll back to it, the post card doesn't show the vote.
 - [x] If you vote on a post and click on it, the comments view doesn't show the vote.
 - [x] If you vote on a post in the comments view and go back, the post card doesn't show the vote.

Slide version: 4.6
Android version: 6.0.1

**Comment by willborum** [comment]
I can reproduce this. This has always been the case for me.

**Comment by ccrama** [comment]
Done, done, and done
