### ISSUE TITLE
Tall images display in low resolution

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#1023]
Here's an example post:

https://reddit.com/r/Frisson/comments/46dj2h/image_start/

**Comment by Chromelon** [comment]
Could possibly be fixed with [DeepZoom](https://www.youtube.com/watch?v=yIMltNEAKZY) implementation?

**Comment by ccrama** [comment]
Slide already has subsampling tile image views (exactly what Ion's "DeepZoom" is), Ion's implementation would act the same as the current method. It's limited by resolution, not how far you can zoom

**Comment by ccrama** [comment]
Fixed with my last commit
