### ISSUE TITLE
Directly viewing a subreddit has a different overflow menu

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1024]
Built on f7fa0e02452c6e1ae34be13248dde610d353c09c

Normal:
![image](https://cloud.githubusercontent.com/assets/1830331/13144937/6c168d7e-d645-11e5-971d-d7204b55da3f.png)

Direct:
![image](https://cloud.githubusercontent.com/assets/1830331/13144949/7e98be5e-d645-11e5-9bcc-9f10aeae2df2.png)

Related: #903

**Comment by ccrama** [comment]
That's on purpose. If the user has swipe from anywhere enabled, they can't open the sidebar from the single sub view

**Comment by Alexendoo** [comment]
Would be good to keep it consistent by adding it to the normal view also, as well as adding the missing ones to directly view. Having a more visible way to access the sidebar would be a good addition despite it not being strictly required as sliding from the right is a hidden action, sometimes forgotten about/ignored or not known in the first place

**Comment by ccrama** [comment]
Now it matches more (except cache comments has been replaced with sidebar)

**Comment by Alexendoo** [comment]
The sidebar option only shows up when directly viewing, should also show on normal subreddits

**Comment by ccrama** [comment]
It wouldn't work with frontpage and all and I can't remove it at runtime, unfortunately

**Comment by Alexendoo** [comment]
Close enough with 7492b5cdb19ff9af8f6864ae5e1569717b0059ad
