### ISSUE TITLE
Refreshing subreddits alters the order significantly

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1025]
Slide version: f7fa0e02452c6e1ae34be13248dde610d353c09c
Android version: 5.1.1

In settings > reorder subreddits hitting the refresh/sync button returns subreddits in quite a strange order, not an issue for me as I just immediately sort alphabetically anyway, but for others who have done fine control over their order this could be quite frustrating.

Perhaps compute the diff of the old/new subreddits and remove missing ones, prepend new ones to the end of the list?

**Comment by ccrama** [comment]
Fixed with my last commit
