### ISSUE TITLE
Could you make "Hide all NSFW photos" a per-user setting?

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#1026]
So I could enable it on one account and not the other for reasons

**Comment by Alexendoo** [comment]
It is a per user setting, I'm not sure if the current way it works in settings reflects that and we'll look into it, but it's a convenience method to alter your (per account) media settings on https://www.reddit.com/prefs, so if it isn't able to be changed per account within the app for now, you can change it on the website

**Comment by Alexendoo** [comment]
To add to that a bit, the reddit API decides if the thumbnails are hidden rather than Slide itself—by not including them in the responses, which is determined by the reddit preferences and the subreddits media settings if the default option is on

**Comment by kufii** [comment]
OK well in that case, when I switch the setting in slide it switches it on all accounts

**Comment by kufii** [comment]
Also, just checked. I do have the Reddit pref to show nsfw thumbnails, but they aren't showing I'm slide. Is it possible it's using the prefs from the first account even if I'm logged in to the second?

**Comment by Alexendoo** [comment]
Hmm it looks like it might be hiding the thumbnails despite them being included in the response if that setting is enabled locally, we'll look at it for sure see if we can't simplify it, currently there are quite a few edge cases to deal with relating to how reddit preferences affect things

**Comment by SZE2** [comment]
Slightly off topic, but you add a setting to block all NSFW posts completely?

**Comment by Alexendoo** [comment]
merge into #1128
