### ISSUE TITLE
unable to save posts or comments

### ISSUE THREAD

**Issue by kuojo** [ccrama/Slide#1029]
Slide version: v4.6.0
Android version:6
I am unable to save posts or comments. If I enter the post and save it from there the post will save but I am still unable to save comments and have not found a workaround yet.

**Comment by Plastix** [comment]
I can save posts from the action bar in the post view. If you long press a comment and click the action button you can save a post from there.

**Comment by Alexendoo** [comment]
Not being able to save in the main view is a known bug - #828 

What exactly is happening for comments? Does it change from "Save" to "Unsave" for example

**Comment by ccrama** [comment]
Has all been fixed!
