### ISSUE TITLE
DeepZoom for images

### ISSUE THREAD

**Issue by Chromelon** [ccrama/Slide#1030]
Slide version: v4.6
Android version: 5.1.1, LG UX 4.0 (LG V10 version, not G4)

When opening large images with lots of detail, such as [this comic](https://www.reddit.com/r/polandball/comments/3nkhm3/the_greatest_enemy/), lots of detail is lost because of the inability to zoom past a point. Sync for Reddit has implemented an open source library called "Deep Zoom" (I'm sure you've heard of it), as demonstrated in [this video](
https://www.youtube.com/watch?v=yIMltNEAKZY). I think Slide could benefit a great deal from having this library.

**Comment by ccrama** [comment]
There's not actually a library for it, I'd have to code it all myself (which is why it hasn't been implemented yet)

**Comment by Chromelon** [comment]
There is a library here:
https://github.com/davemorrissey/subsampling-scale-image-view
