### ISSUE TITLE
Add link source to action bar 

### ISSUE THREAD

**Issue by schmidtc89** [ccrama/Slide#1033]
Slide version: 4.6
Android version: 5.1.1

Would it be possible to show the link source of the post on the action bar next to the name of the subreddit? Such as Funny (Imgur), News (CNN), Videos (Youtube).

**Comment by ccrama** [comment]
Done!

**Comment by schmidtc89** [comment]
Awesome thank you!

**Comment by schmidtc89** [comment]
Looks like this was removed from the release? @ccrama
