### ISSUE TITLE
Add an indication that tables/code blocks are scrollable

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1037]
Currently (1da95b632517092d670fb03b5c2ad7a612b8b2c6), there are some places that have rather wide tables such as [/r/bestof](https://reddit.com/r/bestof)'s rules, and it's not immediatly clear that it's possible to scroll these, perhaps a subtle background change or the scrollbar always being visible

**Comment by ccrama** [comment]
Now it has a scrollbar always present
