### ISSUE TITLE
Shadowbox crash

### ISSUE THREAD

**Issue by Plastix** [ccrama/Slide#1038]
Slide version: **4.6.0-93-f7fa0e0**
Android version: **6.0.1**
While scrolling through a subreddit in shadowbox mode, Slide crashes occasionally. 

This post is crashing: https://www.reddit.com/r/pics/comments/46ml9y/tadpoles_swimming_under_lily_pads/

**Comment by gnadenlos** [comment]
I experienced the same problem - especially in image-heavy subreddits the app crashes within a few minutes every time I give it a try. 

Slide version: 4.6.0-93-f7fa0e0
Android version: 6.0.1
Device: Nexus 6P

**Comment by ccrama** [comment]
I believe this has been fixed already
