### ISSUE TITLE
New toolbar covers content at the top of the page

### ISSUE THREAD

**Issue by yasmara** [ccrama/Slide#1044]
Slide version: 4.6.1
Android version: 6.0.1

**Comment by ccrama** [comment]
Cannot reproduce. What screen are you on?

**Comment by yasmara** [comment]
Holy balls that was fast.

I'm on a Nexus 9 just scrolling sideways through my subreddits. I can attach a screenshot if you would like

**Comment by ccrama** [comment]
Haha I just opened my PC and saw it pop up. It's supposed to scroll down over the content when you switch pages if that's what you're referring to

**Comment by yasmara** [comment]
No there are posts I can just see peeking down from behind it that I cannot scroll up to

**Comment by ccrama** [comment]
Oops, is this in tablet UI mode? I totally forgot about that

**Comment by yasmara** [comment]
Yes

**Comment by yasmara** [comment]
Http://I.imgur.com/y1G86Zu

**Comment by ccrama** [comment]
Whoops. Will fix

**Comment by yasmara** [comment]
Thanks!
