### ISSUE TITLE
Option for partially transparent nav bar similar to the one on Google photos or Google now

### ISSUE THREAD

**Issue by yasmara** [ccrama/Slide#1045]

**Comment by ccrama** [comment]
Now nav bar is transparent!

**Comment by Alexendoo** [comment]
False alarm

**Comment by ccrama** [comment]
It's still the same as #34

**Comment by Alexendoo** [comment]
The status bar is the one on top, the nav bar is the bottom. Status would be rather odd IMO except for instance if there was going to be immersive mode in shadowbox/media views

**Comment by Nxt3** [comment]
Either way, this is so very impossible to implement. I spent hours on it and gave up.

**Comment by ccrama** [comment]
I don't think this will end up being implemented, but there is now an option for immersive mode which offers a similar experience
