### ISSUE TITLE
Navigation Between Parent Comments Broken in Latest Update

### ISSUE THREAD

**Issue by lunamoon151** [ccrama/Slide#1048]
Slide version: Slide v4.6.1-5-237f416
Android version: 5.0.1

Bug report: Navigating between parent comments worked great up till the last update where the page would detect and scroll to the last comment of the previous parent comment instead. 

Feature optimization request #1: Also, it would be great if you could make the parent comment navigation arrows located at the bottom of the screen bigger as I seem to be selecting the comment right under the buttons rather frequently right now. 

Feature optimization request #2: Finally, it would be great if while navigating through the parent comments, the screen could immediately transition to the next comment instead of scrolling past all comments. 

Thank you for making this app! It's by far my favorite reddit app, and the fact that you're still improving on it just makes it all the more awesome

**Comment by Alexendoo** [comment]
May I ask you to clarify what exactly is the bug here - what is happening that shouldn't be or vice versa?

For the not animating scrolling suggestion I agree, it's far too laggy on my phone (Nexus 4) so imagine it will be similar for others

**Comment by ccrama** [comment]
@Alexendoo  the adapter position is adding 1 for the submission, but not 2 for the spacer. When you go to the next parent comment, it actually goes to the one above it. I've fixed that issue with my last commit!

**Comment by Alexendoo** [comment]
Ah okay, I'm built off that commit which would explain why I couldn't figure it out

**Comment by ccrama** [comment]
I fixed it already
