### ISSUE TITLE
Can't collapse comment with a table in it, by pressing inside the table

### ISSUE THREAD

**Issue by stokholm** [ccrama/Slide#1049]
Slide version: 4.6.1-8
Android version: 6.0.1

You can't collapse a comment that has got a table in it by pressing inside the table.

Like this comment for example: https://www.reddit.com/r/androidapps/comments/46xg80/which_are_your_most_used_daily_apps_not_your/d08siij

Pressing the text in the right column does nothing, while pressing the text above the table collapses the comment as it's supposed to.

**Comment by ccrama** [comment]
Fixed!

**Comment by ccrama** [comment]
Nevermind, not fixed

**Comment by ccrama** [comment]
Finally got this one fixed!
