### ISSUE TITLE
Can't scroll tables inside comments

### ISSUE THREAD

**Issue by stokholm** [ccrama/Slide#1050]
Slide version: 4.6.1-8
Android version: 6.0.1

When a comment has a table in it that's too wide to fit the screen, you can't scroll it horizontically. There's a scrollbar at the bottom, but there's nothing you can do to interact with it.

An example is the table inside this comment: https://www.reddit.com/r/androidapps/comments/46xg80/which_are_your_most_used_daily_apps_not_your/d08siij

![table scrolling](https://cloud.githubusercontent.com/assets/1306752/13218717/afc72438-d96b-11e5-81ab-3ada0e08ef41.png)

**Comment by Alexendoo** [comment]
Do you have Swipe away from anywhere enabled? (settings, general)

**Comment by stokholm** [comment]
Yep, disabling that does work arround the issue.

**Comment by Alexendoo** [comment]
Okay, yeah that's a temporary workaround you can use. For this thread merging with #987
