### ISSUE TITLE
Adding subreddit like Relay for Reddit without loggin in

### ISSUE THREAD

**Issue by slio** [ccrama/Slide#1054]
Slide version: 4.6.1-3-56162c1
Android version: 4.4 CM 11S

I like the way how relay let's me add the subreddit without logging in and can be used as a drop down to switch between the subreddits I want to frequently visit.
Currently it is not showing me(or I am unable to find it) the way to add my own subreddit's instead of the default one's provided.

**Comment by ccrama** [comment]
Done with 5.1.4
