### ISSUE TITLE
Tapping any comment after submitting one asks to discard last comment

### ISSUE THREAD

**Issue by Jammintk** [ccrama/Slide#1055]
Slide version: 4.6.0-93-f7fa0e0
Android version: 6.0.1 (CyanogenMod 13.0-20160217-NIGHTLY-victara)
Device: Moto X 2014 (Victara)

Basically what is said in the title. After posting a comment on any post, tapping on any comment brings up the "Discard Comment?" Dialogue box as if I had tried to discard a comment currently being written. Leaving the post and re-entering solves the problem until I post a new comment.

**Comment by ccrama** [comment]
That has been fixed in an update released yesterday
