### ISSUE TITLE
Constant random crashes since 4.6.1 update

### ISSUE THREAD

**Issue by yasmara** [ccrama/Slide#1056]
Slide version: 4.6.1.8
Android version: 6.0.1 (Nexus 9) & 6.0 (Moto X Style)

Slide seems to constantly crash just scrolling through comments or posts and opening posts / images. Sometimes the crashes cause the whole device to lock up for a few moments.

**Comment by ccrama** [comment]
Not noticing any crashes (and very small amount of reported crashes). Do you have an example of a specific post that causes issues?

**Comment by yasmara** [comment]
Usually after 2 or 3 attempts at opening a post it will work fine. I'm not noticing any patterns or specific posts that are causing it. I have reported at at least 5 of the crashes

**Comment by ccrama** [comment]
Could you possibly join us on IRC? The link is in the readme :)

**Comment by ccrama** [comment]
Fixed with my last update
