### ISSUE TITLE
When using the mod tools to flair a post, the flairs given are userflairs targeting the logged in account, not link flairs

### ISSUE THREAD

**Issue by TJFadness** [ccrama/Slide#1057]
Slide version: 4.3.1-8-1e642fd
Android version: 5.1

As you can see in the image below, it's listing not only userflairs (On /r/Firefox we allow users to declair which fork/other browser they use), but _my_ userflairs (you can see the third option reads as "Dev on Windows 10" - that's because I've selected the third flair template myself and set that as the custom text. It would normally read "Developer edition".)

So instead of link flairs, it shows userflairs for the currently logged in user. I haven't tested what happens if you try to set them.

It should show the link flairs "Help" and "Solved"

![vn6obev](https://cloud.githubusercontent.com/assets/4923974/13238372/aeaa88fa-d98f-11e5-9000-a9aaf9a02500.png)

**Comment by ccrama** [comment]
Fixed in the mod tools rewrite for v5!
