### ISSUE TITLE
multireddits do not respect sorting order changes

### ISSUE THREAD

**Issue by Aragonii** [ccrama/Slide#1059]
Slide version: 4.6.1-8-1e642fd
Android version: 6.0.1

There is a selector to choose the sort order of articles in multireddits. When I choose ANY of the options from the list of possible sorting methods the list of articles/links reloads in the default sort order. None of the options alter the order in which the articles are presented.

As a user I hope the ability to select a sort order for multireddits is an intended feature and that the bug lies within the application of the sort order. I much prefer that to the idea that the button to choose sort order appearing in multireddits is the bug and only default sorting of multireddits is intended.

**Comment by ccrama** [comment]
Actually, multi sorting is broken through the API I'm using, and I'm working on a fix. It is supposed to work, though! Merging with #300
