### ISSUE TITLE
"Author profile" and "Go to subreddit" doesn't work

### ISSUE THREAD

**Issue by karlding** [ccrama/Slide#106]
The 3-dot Action button doesn't seem to work on the subreddit view (frontpage, /r/all, /r/gaming, etc.).

## Steps to Reproduce
1. Open Slide. Go to any subreddit (frontpage is fine as well)
2. Click the 3-dot Action overflow button
3. Click **Author profile**
4. Click **Go to subreddit**

### Expected Results
The user is brought to the author's profile or subreddit.

### Actual Result
Nothing happens.

![Author Profile from subreddit view](http://giant.gfycat.com/UnfortunateMelodicArcticseal.gif)

Now, if I [open up the post](http://giant.gfycat.com/InnocentSpicyKid.gif), and do the same steps from within the submission, a modal popup shows up with the options to visit the OP's profile, the subreddit it was posted on, and to share the post.

**Comment by ccrama** [comment]
Has been removed, and replaced with a new menu in the latest builds (same menu from inside the post)!

Changed somewhere around this commit 4a11cea2144a2e016eb28503aaa0cb31337ef935

**Comment by karlding** [comment]
Haha, nice ninja commit :+1:
