### ISSUE TITLE
Gifs not saving after updating to latest version

### ISSUE THREAD

**Issue by Botcher23** [ccrama/Slide#1062]
Slide version:4.6.1
Android version:6.0.1

**Comment by ccrama** [comment]
I haven't changed any code. Do you have a link to a specific gif?

**Comment by bantar** [comment]
I don't think this is related to a GIF.  I've tried saving numerous posts since the update.  I see the following behavior:

1) Dialog Box text changes from "Save Post" to "Post Saved"
2) A temporary bottom slider pops up and says "Submission unsaved"
3) If you exit the post ..., then open it again, the dialog box correctly says "Save Post" as the post really was not saved.

Using a different reddit app, I can save a post and then return to my saved items in Slide and see the new ones appearing, so this is unrelated to my account as best I can tell.

**Comment by ccrama** [comment]
It is actually saved, the dialog just doesn't update when you open the post as the dataset hasn't changed, and it sees that it was not saved at the time the data was loaded. @bantar

**Comment by l3d00m** [comment]
@ccrama Saving doesn't work for some users (#828), it's not just the dialog.

**Comment by bantar** [comment]
@ccrama It is definitely NOT saved.   It fails to save everytime.  If I close and use another app, select save on a post, exit that app, return to Slide and hit saved, I see the saved post.   Further, if I save via Slide and then go to the other app, it too has no record of a new item being saved.  Slide is NOT saving right now (for me).

**Comment by Botcher23** [comment]
Hey,  sorry it took so long to respond. It's not any specific gif,  it's every one I've tried since updating. Images save fine,  but when saving a gif,  it just says "gif downloaded" but said gif isn't actually downloaded as it doesn't appear anywhere on the device.  

I'm not sure if it's all gifs,  as it's entirely possible the fifteen  or so gifs I've tried could be bugged,  but I haven't found one that worked yet. I can verify that it works fine in other apps and worked fine in slide before I updated.

**Comment by Nxt3** [comment]
Example: the image in this post will not be saved to anywhere on the device https://reddit.com/r/androidcirclejerk/comments/48kq79/when_someone_calls_my_nexus_a_galaxy/d0kmn52?context=3

Probably because it is gifv

**Comment by Botcher23** [comment]
Even regular  gifs aren't saving. Unless Slide converts them all automatically? I recall was able to save  gifs and gifv links before and getting both .gif and .mp4 files. Glad I'm not the only one having this issue, even if I've replicated it on two devices.

**Comment by Botcher23** [comment]
Solved! Seems the option to set the save location for gifs fixed this issue on both of my devices. No idea what was causing it,  but I'm glad it's solved.
