### ISSUE TITLE
Random crash when Slide isn't even running

### ISSUE THREAD

**Issue by LordManhattan** [ccrama/Slide#1063]
Slide version: 4.6.1-19-83564e7
Android version: 5.1.1

Slide just crashed on me, even though it wasn't even running. 

- Screenshot: http://i.imgur.com/ccFLeJ5.jpg
- Screenshot: http://i.imgur.com/cjSaUNB.jpg

Logcat:
`02-23 15:59:11.291 E/AndroidRuntime(19288): Process: me.ccrama.redditslide, PID: 19288`

`02-23 15:59:11.291 E/AndroidRuntime(19288): at me.ccrama.redditslide.Reddit$2$1.run(Reddit.java:411)`

**Comment by ccrama** [comment]
DId you report the crash? Those two lines are not really hepful unfortunately :(

**Comment by LordManhattan** [comment]
You mean by tapping that report button? Does that actually help!? :O

**Comment by ccrama** [comment]
Yeah, that gives me the full stacktrace and where the crash is occuring so I can fix it :P

**Comment by LordManhattan** [comment]
Haha! I had no idea. I have tapped it a bunch of times, just in case someone gets it, that being Google or the dev, but sadly, I didn't tap it this time. I'll be sure to do it whenever it crashes from now on though :-P

**Comment by ccrama** [comment]
Thank you! And yeah, it goes straight to me

**Comment by ccrama** [comment]
Should not be an issue anymore
