### ISSUE TITLE
Hide post button removes wrong post.

### ISSUE THREAD

**Issue by aaronpoweruser** [ccrama/Slide#1065]
Slide version: 4.6.1
Android version: 6.0.1

In the submission list and the hide post button is enabled. Pressing the hide post button removes the wrong post (1 post above).

**Comment by rebeleagle** [comment]
Actually, the correct post is removed from the data layer, but the incorrect one from the ui layer. If you scroll down and then back up, the correct post is hidden, and the incorrectly removed one reappears.

**Comment by ccrama** [comment]
Fixed!
