### ISSUE TITLE
Crashes when trying to open a saved Post 

### ISSUE THREAD

**Issue by brentgsw** [ccrama/Slide#1066]
Slide version: 4.6.1-19-83564e7
Android version: 6.0.1

When trying to open a saved post slide crashes. If i just click on a preview for an image, the built in image viewer will open fine, but you can't open the actual post. Sent a couple crash logs for this a few minutes ago.

**Comment by bantar** [comment]
As a test, I went thru many of my saved posts and only 1 crashed on me.   Then, when trying to recreate it, the crashing post worked.  I can no longer recreate this myself, but did send the crash log for the one that did fail.

**Comment by brentgsw** [comment]
Strange, I was able to reproduce consistently. However I just got an update form the playstore and now I can't reproduce, so i guess this can be closed.

**Comment by ccrama** [comment]
That has been fixed in the last update I released
