### ISSUE TITLE
Display rotation loses place for certain posts

### ISSUE THREAD

**Issue by bantar** [ccrama/Slide#1067]
Slide version:  v4.6.1-15-b8baab8-dirty
Android version:  5.0

In most cases, I can view a video, gif or article and can rotate the screen without any problem. However, I've found a few posts that cause my main view position to be lost. For instance, after scrolling down 100+ posts, view, rotate and return to the main post list to find myself at the top of the list as if the app just started. This is pretty annoying as I need find my position again.

This post consistently fails: https://reddit.com/r/OSHA/comments/475vrz/luckily_these_workers_were_wearing_their_harnesses/

Steps: 1) Click on image, 2) Gif starts playing, 3) rotate screen (V->H), 4) Rotate back, 5) Hit back button. Not sure if it matters, bit I am not waiting on the video to finish playing.

Using the latest version.

**Comment by bantar** [comment]
OK, here's another post that loses it's position every time I view it.   Subreddit /r/gifs  Sort order:  New   
https://www.reddit.com/r/gifs/comments/47cita/rocknroll/

Steps to recreate:
Scroll to item (in this case, it was > 100 posts down as GIF was showing 1 day ago)
View item in Vertical mode (note viewing via Click on picture - see NOTEs)
Rotate item to Horizontal
Return to Vertical mode (at this point the view behind the overlay has already shifted to the beginning of the list)
Back button to exit confirms that list position has reset.

NOTE:  This same GIF can be played in Vertical mode time after time with no changes in the results.  It only loses position when the video is rotated.   

NOTE:  I also confirmed that you only need to rotate (V->H).  If I hit back at this point, without returning to V mode, the position is already lost.

NOTE:  It does not matter if one clicks on the comments, then the GIF or hit the GIF directly.  In either case, once you return to the main screen, the view has been reset to the newest item.

**Comment by ccrama** [comment]
I think this has been fixed for the next update, need to confirm though. I can't reproduce the issue in the current dev version

**Comment by bantar** [comment]
I'll let you know if I see it again after the update.    It was hard to find examples even when I knew what to look for, yet it happens enough to spot it in a few days if it remains.  Thanks.

**Comment by ccrama** [comment]
Alright. If you run into it again, feel free to re-open it
