### ISSUE TITLE
Wiki hyperlink problems & crashes

### ISSUE THREAD

**Issue by SZE2** [ccrama/Slide#1073]
- [x] Long pressing a wiki link in the submission view to open externally will still open internally.
- [x] Trying to externally open a hyperlink within the wiki well cause a crash.
- [x] Trying to open that hyperlink internally does nothing (maybe after the page finishes loading things change?)
- [x] Loading symbol never seems to finish loading.

Screencaps: https://vid.me/iWjk

Link that I start from in the video: https://reddit.com/r/HFY/comments/47cpc2/ocjverse_the_lost_minstrel_12/

**Comment by ccrama** [comment]
Should all be fixed now
