### ISSUE TITLE
Cached Data doesn't get deleted 

### ISSUE THREAD

**Issue by DavidWalter** [ccrama/Slide#1075]
Slide version: 4.1.6-25-a6cb3ac
Android version: 5.0.2
Device: Huawei Honor 7 PLK-L01

After 3 days of fairly intensive use i had 0.95GB Data for slide. Since you can't move the App to SD in Android 5 this is way too much.

**Comment by ccrama** [comment]
Dang, gifs don't auto delete. Will add a memory management screen soon!

**Comment by aaronpoweruser** [comment]
https://github.com/JakeWharton/DiskLruCache

**Comment by ccrama** [comment]
Fixed, now it's limited to 50mb. Might implement something with a DiskCache later on, but for now clearing the cache directory at 50mb is safe enough for me.

**Comment by DavidWalter** [comment]
Thanks very much for fixing! And keep up the great work, slide is slowly but steady becoming the best Reddit app on Android. :)

**Comment by ccrama** [comment]
Thank you :D
