### ISSUE TITLE
After a few scrolls down the page I get a "No more posts'. 

### ISSUE THREAD

**Issue by Lochstock** [ccrama/Slide#1076]
Slide version:4.6.1-25 a6cb38c
Android version: 5.1.1

**Comment by ccrama** [comment]
That means whatever sorting mode you're on, there are no more posts

**Comment by Lochstock** [comment]
I have it set to 100 under Reddit preferences, but I've found it won't do
nearly that much. Seems most prevalent when I'm switching from mobile data
to wifi.
