### ISSUE TITLE
Opening a post from list view brings me to a different post?

### ISSUE THREAD

**Issue by SZE2** [ccrama/Slide#1078]
Post 1: https://reddit.com/r/Cooking/comments/46ifii/i_walked_into_the_kitchen_and_found_my_boyfriend/

Opens to: https://reddit.com/r/Cooking/comments/478a9w/i_just_made_puff_pastry_from_scratch_it_was_a_ton/

Screencaps: https://vid.me/s8Ar

**Comment by SZE2** [comment]
Happens for many posts over a few minutes, clearing cache fixed it

**Comment by ccrama** [comment]
Merging with #1072

**Comment by ccrama** [comment]
Is this fixed now?

**Comment by SZE2** [comment]
It is for me

**Comment by ccrama** [comment]
Great!

**Comment by SZE2** [comment]
Having occasional issues with this again on the latest play version (4.6.2/7) I'll try clearing cache and resort back if it crops up again.
