### ISSUE TITLE
App bar reportedly doesn't function in kitkat

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1079]
https://www.reddit.com/r/slideforreddit/comments/479gun/bug_topbar_not_clickable_on_kitkat/
https://www.reddit.com/r/slideforreddit/comments/47iclr/unable_to_interact_with_the_entire_orange_space/

I cannot verify this myself as I don't have a kitkat device, but 3 people have reported it so it's pretty sure

**Comment by ccrama** [comment]
I don't have a KitKat device either. If anyone has a KK device, please go to Developer Settings > Show Layout Bounds > Slide, and take a screenshot please. That would be super helpful!

**Comment by hary585** [comment]
I will. I promise.

**Comment by Alexendoo** [comment]
Video https://vid.me/IxcA

![media-20160226](https://cloud.githubusercontent.com/assets/1830331/13340124/b3b74caa-dc25-11e5-9fad-d55d696a1c14.png)

**Comment by ccrama** [comment]
Fixed

**Comment by Alexendoo** [comment]
Fixed for:
- [x] Subreddit view, normal
- [ ] Subreddit view, direct
- [ ] Submission view
- [ ] Profiles
- [ ] Inbox/messages
- [ ] Multireddits

**Comment by ccrama** [comment]
All fixed
