### ISSUE TITLE
Slide constantly crashing when sliding between posts

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#1080]
Slide version: 4.6.1-25
Android version: 6.0.1

I don't know why it's happening all of a sudden, slide has been pretty stable for me lately, but this morning, it's crashing about every 20 seconds. I reported a few of them, it generally happens when sliding between comment threads

**Comment by ccrama** [comment]
Sounds like your phone is running out of RAM. What device are you on?

**Comment by kufii** [comment]
Nexus 6P,  the problem doesn't seem to be happening anymore

**Comment by kufii** [comment]
Disregard, started happening again the second I replied to this

**Comment by ccrama** [comment]
Is this happening anymore with v4.6.2?

**Comment by kufii** [comment]
Occasionally, but not nearly as often

**Comment by ccrama** [comment]
I am not getting any reports of this in v4.6.2, can you make sure to report it if it happens?

**Comment by kufii** [comment]
I have reported all my crashes, there should be a couple from me. It might not be the exact same crash but it is happening when I slide through posts

**Comment by kufii** [comment]
Just reported another one, it seems to usually happen when sliding to a new page of posts

**Comment by ccrama** [comment]
Should now be fixed
