### ISSUE TITLE
Gild button not working

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#1082]
I'm trying to gild a comment and it isn't working

**Comment by l3d00m** [comment]
Gilding comments is not possible because reddit has to allow it for each app, which they sadly haven't for us iirc. This is why it just opens the comment in browser, so you can gild it there.

**Comment by kufii** [comment]
Oh, well it's failing to open the comment in browser then, it's just opening it in slide

**Comment by l3d00m** [comment]
WHich version are you using @kufii?

**Comment by KonradIT** [comment]
Yes, this happens when Slide is setup to open every reddit.com/* link, as a temporary solution go to settings, apps, Slide for Reddit and clear default links.

**Comment by kufii** [comment]
Yep that fixes it for now @KonradIT

**Comment by ccrama** [comment]
Fixed, now it opens in the in-app browser!
