### ISSUE TITLE
Collections in sidebar don't update color properly

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1084]
Slide version: v4.6.1-25-a6cb3ac
Android version: v6.0.1

Despite showing a different color in the sidebar, the correct color is shown everywhere else. I tried deleting it and readding it, but the problem persisted. The below screenshots display the issue with the "android wear+moto360" collection.

![screenshot_20160226-110701](https://cloud.githubusercontent.com/assets/2940826/13357618/3f139d46-dc79-11e5-9c1c-915189ffd112.png)
![screenshot_20160226-110708](https://cloud.githubusercontent.com/assets/2940826/13357621/4293efb6-dc79-11e5-8535-a5153da03309.png)
![screenshot_20160226-110714](https://cloud.githubusercontent.com/assets/2940826/13357632/46fc7c80-dc79-11e5-82db-aa4441d69885.png)

**Comment by ccrama** [comment]
Fixed!
