### ISSUE TITLE
Offline mode Loading animation

### ISSUE THREAD

**Issue by prashantkhurana** [ccrama/Slide#1085]
Slide version:4.6.1-25-a6cb3ac
Android version:6.0.1

There is a loading animation when in offline mode and it obscures the view. 
http://i.imgur.com/XAvsYfD.png

**Comment by ccrama** [comment]
Fixed! Thanks for the report

**Comment by prashantkhurana** [comment]
That was fast :+1:

**Comment by ccrama** [comment]
Haha I just finished fixing it when you posted

**Comment by prashantkhurana** [comment]
Talk about coincidence :)
