### ISSUE TITLE
Don't resize, and by extension reflow, a comment when it's selected

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#1086]

**Comment by ccrama** [comment]
It's not resized, the addition of the [Child Number] tag pushes it around.

**Comment by Alexendoo** [comment]
When you select a comment it takes on the full width available rather than being dictated by comment depth, that is the resize

**Comment by ccrama** [comment]
Oh, I'm wont persueing that. It has to be that width for the editor buttons to fit correctly. Sorry guys
