### ISSUE TITLE
Maintain Go to subreddit height with few items left

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1089]
Currently the drawer shrinks in height to match, by giving the list a minimum height, the drawer wouldn't move around when searching for something and for instance making a spelling mistake, there would just be a blank space.

In a picture:

![screenshot_2016-02-27-00-55-16](https://cloud.githubusercontent.com/assets/1830331/13369485/72872502-dced-11e5-992f-b4226701130f.png)

**Comment by ccrama** [comment]
Fixed!
