### ISSUE TITLE
Reorder subreddits not working

### ISSUE THREAD

**Issue by derioz** [ccrama/Slide#1090]
Slide version: 4.6.1-25
Android version: 5.1.1 S6 edge

**Comment by Alexendoo** [comment]
@derioz Can you elaborate: What's not happening exactly and what are you trying?

**Comment by derioz** [comment]
The side bar subs are not rearranged in the order I set it to in the settings.

 The tabs get rearranged though.

**Comment by Alexendoo** [comment]
In Settings → General, do you have Alphabetical sidebar enabled?

**Comment by ccrama** [comment]
Not applicable anymore, the setting is gone for the next udpate
