### ISSUE TITLE
Reordering subreddits behaves erratically

### ISSUE THREAD

**Issue by wtok** [ccrama/Slide#1094]
Slide version: 4.6.1-25-a6cb3ac
Android version: 5.1.1, CyanogenMod 12.1

When I tap a subreddit and select "Move to top" it sends a subreddit adjacent to the one I select, but not the one I select. For example I just now tried to send `linux` to the top, but it sent `linux_gaming` to the top instead, which was just below `linux`.

Alphabetical sidebar is disabled.

Somehow, the subreddits also seem to get duplicated. After re-syncing subreddits and hitting the alphabetical sort button, I've somehow ended up with three entries for `lisp`, and two for `linux_gaming`. These duplicate entries also appear in the top-bar subreddit slider thingo, and behave normally as tabs for their given subreddits.

Screenshots:
https://i.imgur.com/HDO06KU.png
https://i.imgur.com/EsDKzlp.png
https://i.imgur.com/wvlrwph.png

If you need more info, I'm happy to help.

**Comment by ccrama** [comment]
Those issues have been fixed for the next update. Thank you for the detailed report!
