### ISSUE TITLE
Switch wikis over to the new app bar hiding style

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1097]
Slide version: c354535c5f43a20669d8a682448f8bc3b2c7bcaf

Currently they're on the one that pushes content around

**Comment by ccrama** [comment]
Not really possible as the main views hook into RecyclerView scrolling, and wiki use a ScrollView

**Comment by ccrama** [comment]
Going to close this as it's working fine the way it is, and is not really possible to change it because it listens for a RecyclerView scroll for the main view scrolling, and the RecyclerView is not used for wiki pages
