### ISSUE TITLE
Posts are frequently repeated

### ISSUE THREAD

**Issue by Aerosteed** [ccrama/Slide#1098]
Slide version: 4.6.1-25-a6cb3ac
Android version: 6.0.1

I often find posts duplicated in the stream. They seem to be from the same sub, poster, etc. The only difference appears to be the number of comments. See the screenshot.

![screenshot_20160228-081229](https://cloud.githubusercontent.com/assets/17532872/13381465/b764fa6c-de11-11e5-94d5-f1d1024d6059.png)

**Comment by ccrama** [comment]
Fixed in the v4.6.2 update released earlier today
