### ISSUE TITLE
Thumbnails fail on small cards

### ISSUE THREAD

**Issue by joytrekker** [ccrama/Slide#1099]
Slide version: v4.6.2
Android version: Marshmallow 

Only the first few thumbnails load when using the small card view. The rest of the thumbnails show the default placeholder image. If you scroll up and down the place holder images are incorrectly replaced by the few thumbs that loaded at the beginning. 
http://i.imgur.com/720DKJQ.png

**Comment by ccrama** [comment]
Fixed on my next commit
