### ISSUE TITLE
Can't change layout of frontpage

### ISSUE THREAD

**Issue by Tunous** [ccrama/Slide#110]
Editing it from settings doesn't do anything and when trying to press on "i in circle" button nothing happens.

**Comment by ccrama** [comment]
That is on purpose. All and frontpage take the default from settings. Ill think about re-adding it in the future, though.

**Comment by l3d00m** [comment]
Duplicate of #110?

**Comment by ccrama** [comment]
Closing. Duplicate of #95

**Comment by Tunous** [comment]
I don't think it's duplicate.
> All and frontpage take the default from settings. Ill think about re-adding it in the future, though.

This is the issue. Changing default setting doesn't do anything. I have set default layout to small card but frontpage still displays using list.

**Comment by l3d00m** [comment]
You probably set it before the update. Have you tried clearing app data?

**Comment by Tunous** [comment]
Yes that was it. Thanks.
