### ISSUE TITLE
Incorrect thumbnails in latest version

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#1100]
Slide version: 4.6.2-5
Android version: 6.0.1

In the latest version, the thumbnails in the list of posts are often wrong. It looks like it uses some incorrect cached thumbnail. I didn't notice it before this update

**Comment by kufii** [comment]
Here's an example, it's repeating the cached chameleon thumbnail

http://imgur.com/ve2PlWm

**Comment by Alexendoo** [comment]
#1099 - There is an updated alpha APK on its way out currently containing the fix for this
