### ISSUE TITLE
Imgur only plays first 15 seconds on internal viewer

### ISSUE THREAD

**Issue by amweiss** [ccrama/Slide#1103]
Slide version: 4.6.1-25-a6cb3ac
Android version: 6.0.1

http://i.imgur.com/3kC7fOV.gifv
seen at
https://reddit.com/r/GifRecipes/comments/484d2j/kung_pao_chicken/

Only plays the first 15 seconds while using the internal viewers.

**Comment by amweiss** [comment]
Still present in 4.6.2-11-0184efb

**Comment by ccrama** [comment]
That cannot be fixed until Imgur grants Slide API access, it's a limitation with the current API I'm using

**Comment by FabianHoltkoetter** [comment]
How do the other reddit apps handle this?

**Comment by Alexendoo** [comment]
They use the old imgur API from what I've seen, Slide could also do this but there is a version 3 imgur API out that we're looking at but it has its issues, namely rate limiting.

The reason the gifs are cutoff is they're run through gfycat which recently imposed the restriction (it wasn't supposed to be able to have ≥15s in the first place)

**Comment by ccrama** [comment]
Fixed!
