### ISSUE TITLE
List mode seems to get the text reduced and crammed in more than cards

### ISSUE THREAD

**Issue by brentgsw** [ccrama/Slide#1108]
Slide version:4.6.2
Android version:6.0.1

https://imgur.com/a/Hf80e 

See the screenshots in the link above. 

Seems the action bar line getageta reduced in size in list mode giving it a much more crammed feeling. Not sure if that's intentional or not, but think it would be better if it could be similar to the card mode.

**Comment by ccrama** [comment]
That is on purpose as it makes the list view smaller

**Comment by brentgsw** [comment]
It's just my opinion, but was discussing this w/ Alexendoo, and think it's a bit too cramped. I think the less space list takes compared to cards by default is sufficient. 

I don't think trying to reduce the view is adding enough benefit for how it makes it look. In reality, you may get what, maybe 2 extra posts to a screen in thubmnail, and maybe 1 w/ big picture?

Just sharing my thoughts as a big fan of list views over cards.

**Comment by ccrama** [comment]
Thank you for the feedback. I fixed the padding and made only the buttons a tad smaller

**Comment by brentgsw** [comment]
You the man!

**Comment by ccrama** [comment]
Thanks :D
