### ISSUE TITLE
Drawer subreddit and FAB issue

### ISSUE THREAD

**Issue by xshane** [ccrama/Slide#1109]
Slide version: 4.6.2-11-0184efb
Android version: 5.1.1

Opening a subreddit from the drawer doesn't update the 3 dot button options. Still shows frontpage buttons. 

http://imgur.com/a/8vamo

Also the FAB disappears in the 3rd image (opening subreddit from post) while it's there in the first image (opening from drawer)

**Comment by Alexendoo** [comment]
Thanks for the report, the first is #1024 and the second #979
