### ISSUE TITLE
Comments & submissions keep on reloading when I change orientation

### ISSUE THREAD

**Issue by KaliK0t** [ccrama/Slide#111]
Turning it over to Landscape mode has to reload the comments and then it does it again for portrait mode when i turn it back

**Comment by Alexendoo** [comment]
Happens for submissions also

**Comment by ccrama** [comment]
Not really a way around this. The view is re-created and so are all the sub-views and data.

**Comment by Alexendoo** [comment]
No way at all? You may be sick of hearing the phrase but all the other apps do not suffer from this. Completely losing your place due to an accidental rotation is incredibly frustrating.
