### ISSUE TITLE
Reorder subreddit "move to top"

### ISSUE THREAD

**Issue by xshane** [ccrama/Slide#1111]
Slide version: 4.6.2-11-0184efb 
Android version: 5.1.1 

http://imgur.com/hIDfuiL

In the Reorder Subreddits settings page, using the "move to top" option duplicates a subreddit instead of moving it and this can be repeatedly done. Deleting any duplicate also deletes the original subreddit from the list.

**Comment by ccrama** [comment]
I fixed this for 4.6.2 and can no longer reproduce the issue

**Comment by ccrama** [comment]
I fixed it for long press but not the single tap menu. Fixed with my last commit!
