### ISSUE TITLE
Big pictures stay cropped

### ISSUE THREAD

**Issue by gloryian** [ccrama/Slide#1112]
Slide version: 4.6.2
Android version: 4.4.2

Some pictures are cropped even though the "crop big picture" toggle in Post Layout is off. 
The issue is resolved after clearing data, but returns after adding an account.

**Comment by ccrama** [comment]
Only the first inflated images do this. After scrolling down it will fix itself. This is because I don't know the image height at the time the cards are being inflated so I assume a cropped size

**Comment by ccrama** [comment]
Fixed

**Comment by kufii** [comment]
Was the recent alpha release supposed to have this fix?
