### ISSUE TITLE
Slide goes back to start of frontpage after prolonged use

### ISSUE THREAD

**Issue by gloryian** [ccrama/Slide#1113]
Slide version: 4.6.2
Android version: 4.4.2

The app goes back to the start of frontpage after I use it for a while. It usually happens when I click on a post with an imgur gallery and then click the back button to return to the app.

**Comment by bantar** [comment]
I think this is the same as #1067 which is now being reported as fixed in next release.

**Comment by Alexendoo** [comment]
If this pops up again, please repopen but it sounds like it was that indeed
