### ISSUE TITLE
Open externally by domain

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1116]
For an example see RiF, but it's a pretty nice addition, for instance if somebody has an app for one of the streamables that handles it better, or wants to use opengur etc. they would head to link handling and type the domain in

**Comment by SZE2** [comment]
This would be great, as Imgur is still pretty slow on Slide vs. Opengur. Maybe see if you can implement their way of getting gifs? It's on github under opengur

**Comment by Alexendoo** [comment]
Would also resolve #190

**Comment by ccrama** [comment]
Added in in v4.7.4!
