### ISSUE TITLE
Update vote count when voting 

### ISSUE THREAD

**Issue by Tunous** [ccrama/Slide#112]
In addition to changing color it would feel much more responsible if votes counter also updated. 

Example: 

1. Before voting: `9 points`
2. After upvoting: `10 points` in orange color 
3. After downvoting `8 points` in blue color
4. After resetting vote `9 points`

**Comment by ccrama** [comment]
Cool idea!

**Comment by l3d00m** [comment]
implemented with 6ec1ab6!
