### ISSUE TITLE
Swap out "Toggle dark theme" for a generic theme changer

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1121]
Now that we've another theme, it might be best to allow more than just quick switching between dark/light

**Comment by oatberry** [comment]
This would make it easier to switch to, say, an amoled theme, which I prefer over the regular dark theme.

**Comment by alexsmithfanning** [comment]
Or you could replace the text that says "Toggle dark theme" with something more neutral like "Cycle themes".

**Comment by ccrama** [comment]
Done in latest commit, now it shows a dialog and lets you choose any of the 4 themes
