### ISSUE TITLE
Shadowbox Doesn't show some imgur links

### ISSUE THREAD

**Issue by brentgsw** [ccrama/Slide#1124]
Slide version: 4.6.2
Android version: 6.0.1

 shadowbox mode won't show images if the post is marked as NSFW and is a "imgur.com" link, it seems to show nsfw posts if it's "i.imgur.com" fine.

**Comment by ccrama** [comment]
Fixed, now it uses a new MediaFragment instead of separate image and gif fragments (supports Imgur links)
