### ISSUE TITLE
Settings rework

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1128]
The product of a decent amount of discussion but by no means complete, anybody with opinions please weigh in

#### Layout

Should match the look of the stock settings app - https://i.imgur.com/KZB2Jpl.png

- [x] Allow setting descriptions, replacing any strings that currently contain newlines (\n)
- [x] Not every setting requires an icon, though for some currently it helps, but with the less ambiguous descriptions this should be less of an issue
- [x] The Post layout page uses the wrong sectioning type
- [x] Pages without any sectioning has the wrong background colour
- [x] There are no item separators
- [ ] Main theme, Post layout and Donate have the wrong transitions

#### Usability

- [x] Rename/describe settings as needed, with the new description area in mind. Some settings currently are not very clear in their actions
- [x] Some settings consist of multiple checkboxes, when they should be radio buttons or dropdowns - for instance the FAB settings, custom tabs/webview/disabled internal browser
- [ ] Some settings are unclear due to lack of description or by being unclear about what would happen on toggle
 - If a setting is an **alternative** then the default position should be off and the overriding option shown, eg “Use webview” replacing “Use chrome custom tabs”, “Monochrome comment depth indicators” replacing colourful, etc.
 - If switching the feature off removes it with no alternative, default on is fine. e.g. disabling confirm exit dialog turns off the confirm exit dialog, which is perfectly expected.
- [ ] Grey out settings that aren't available to use, preferably with a small toast/flash that will appear to explain why they're disabled on press - e.g you need to sign in
- [ ] Merge reorder subreddits and subreddit themes - makes more sense for the user as both are lists of subreddits, and the reorder screen already shows the colour of each, just got to go about getting the functionality of both into one place nicely
- [x] Remove the FAB section, have it as a dropdown select in layout, unless it is planned to see a large amount of function adding, it doesn't currently require its own section
- [x] Replace the CSV nature of filters with individual entries, automatically add another blank field underneath as more are added, makes it far easier to view or delete entries and would go a long way to avoid things like #1169 

#### Change to defaults

Whilst the changes are happening, it's the perfect time to make any changes to defaults, these are going to possibly be a lot more subject to debate than the other points, but here are my opening suggestions that I think are reasonable:

- [x] Notification time → 6/12h, for most waking up every 1h is a little overkill for reddit, majority of users are lurkers
- [ ] Swap the meaning of "Swap tap and long press..." over, I think the actions under the current default long press are accessed more than hiding posts are, but can't be sure. Either way it balances out time to action

#### reddit.com preferences interaction

It's rather irritating, but the [preferences](https://www.reddit.com/prefs) users set have an affect on the data reddit apps receive

- [x] Make these settings per user account (See the discussion in #1026)
- [x] Add a dropdown for the users thumbnail preferences
- [ ] Add an option for compressed link display, though the only affect this has on slide is disabling thumbnails as far as I'm aware, so a disclaimer would have to be added when enabling it that it doesn't change the layout of Slide (though perhaps it could in the future? ie hide empty thumbnail box)
- [ ] Potentially warn the user if their reddit settings are causing thumbnails to not show on first log in

#### Removal of certain settings

This one is another that might cause a bit of stir, but some settings are relatively unnecessary or simply too niche, that their removal would benefit the settings/app as a whole by keeping it more simple, as most users won't really go into depth in the settings much it's important to keep it nice and usable

- General
 - [x] Enter animation - far too subtle an effect to need an animation
 - [x] Alphabetical sidebar - very niche, more confusion than it's worth for most
 - [x] Hide header on drawer - The header is now required for multi-account to function
- Link handling
 - [x] Horizontal album style - Remove from settings and use a button/toggle within the album itself
- Theme
 - [x] Use solid Imageviewer background - Rather quite niche, possibly decrease the transparency on the album view a little, it feels a little too transparent to me but that's rather subjective
- Comments
 - [x] Click user names to view profile - make it not clickable and get rid of this setting

**Comment by ccrama** [comment]
Pretty much all done with my last 9 commits! Took a ton of work but looking/working much nicer. Still extracting strings and moving some stuff around, though

**Comment by Alexendoo** [comment]
This issue № has overstayed its welcome I think, reopened a couple of the small remaining bits as #1369 and #1370
