### ISSUE TITLE
Double tap and drag zoom not working as intended

### ISSUE THREAD

**Issue by augenleet** [ccrama/Slide#113]
When trying to use the double tap zoom where you hold on the second tap and move up and down to zoom manually, the picture already zooms in or out by itself on the second tap as if you would just do a regular double tap for zooming.

**Comment by ccrama** [comment]
Works fine for me

**Comment by l3d00m** [comment]
Works fine for me too.

**Comment by Alexendoo** [comment]
Confirmed on my end, there's a stark difference if you're used to that method but you may not notice it otherwise

**Comment by augenleet** [comment]
Here's a video to demonstrate it:
https://www.youtube.com/watch?v=nZQDbnuSMgQ

The double tap shouldn't do anything as long as don't lift your finger again. See Google Photos app for reference.

**Comment by ccrama** [comment]
I still don't see the issue. That all appears to be working how I wanted it to. Could you describe the issue further? Sounds more like an "enhancement" instead of "bug"

**Comment by Alexendoo** [comment]
It's overriding expected behaviour, which is a UX no-no, open an image in a browser or another app and use the single finger zoom, it's the same across all of them

**Comment by augenleet** [comment]
@ccrama When the user wants to do the "one finger tap&drag zoom", the "double tap zoom" is applied (accidentally?), which is an unexpected behaviour. Do you notice the difference to other apps that make use of the tap&drag zoom?

**Comment by ccrama** [comment]
Ah, so it's zooming in and also taking the drag to zoom at the same time?

**Comment by augenleet** [comment]
Yes, that's it.

**Comment by ccrama** [comment]
Ah. ok ill look into it!

**Comment by Alexendoo** [comment]
Fixed with d04f085de21db2cd18d6b0b572f75ffb6862e75b
