### ISSUE TITLE
Bring back option to hide ALL NSFW posts

### ISSUE THREAD

**Issue by SZE2** [ccrama/Slide#1130]
Slide version:4.6.2-18-
Android version:6.0

I remember there used to be a setting to hide ALL nsfw posts, not just thumbnails. can that please be brought back?

**Comment by SZE2** [comment]
[Request]

**Comment by ccrama** [comment]
Go to Reddit Settings and check "Make reddit safe(r) for work"

**Comment by SZE2** [comment]
Only hides thumnails.

**Comment by ccrama** [comment]
Oh, I thought it hid posts too. Whoops

**Comment by Alexendoo** [comment]
Makes sense to stick this in the filters section

**Comment by ccrama** [comment]
Now it uses Reddit's set preference (and will hide all NSFW posts if set)
