### ISSUE TITLE
Feature request: When I share any url from any app, Slide should be able to catch it.

### ISSUE THREAD

**Issue by bagarwa** [ccrama/Slide#1132]
Slide version: 4.6.2
Android version: 6.0.1

For example, I found out a cool new app sale in play store. I tap the share button on that app's play store page. (It shares a url like http://play.google......) Slide should be present in the list of apps who receive this broadcast. So that I can create a new post with this url and submit it to a subreddit.

**Comment by ccrama** [comment]
Done! You can now share links or images to Slide from the share screen

**Comment by bagarwa** [comment]
GitHub doesn't have an upvote or thanks button! Thank you ccrama. That was probably the fastest response I've ever seen from any dev.

**Comment by ccrama** [comment]
:D you're welcome!
