### ISSUE TITLE
Bug: "Toggle dark theme" toggles between light and dark themes, ignoring the original theme I started from.

### ISSUE THREAD

**Issue by bagarwa** [ccrama/Slide#1134]
Slide version: 4.6.2
Android version: 6.0.1

I originally have Amoled black base theme. When I tap the "Toggle dark theme" in the menu, it switches to light theme. When I tap the "Toggle dark theme" again, it switches to dark theme. Not the original Amoled black theme i started from, but the dark theme. The toggle option only toggles between those two themes (light and dark) then on. To switch to black theme, I have to go to settings again.

IMO, it should switch between original theme and light theme.

**Comment by Alexendoo** [comment]
Wasn't a bug per say that was the intended behaviour, but as of 4039cf0edc5a84c58ba7f7d2b0b5be99ef154921 is no longer an issue, now provides a generic switcher for all four themes
