### ISSUE TITLE
Cache Saved Posts

### ISSUE THREAD

**Issue by prashantkhurana** [ccrama/Slide#1135]
Can we have the option to cache saved posts?

**Comment by ccrama** [comment]
What do you mean by "cache"?

**Comment by prashantkhurana** [comment]
Sorry, I meant offline mode for saved posts.

**Comment by ccrama** [comment]
Unfortunately this is much harder than I expected (and there is no profile screen in offline mode). Don't think this will be possible, sorry

**Comment by okungnyo** [comment]
Why not leave the issue open until it becomes possible one day then?? :/

**Comment by ccrama** [comment]
Because I will not be doing this most likely
