### ISSUE TITLE
Can't open some imgur links

### ISSUE THREAD

**Issue by tomatpinne** [ccrama/Slide#1136]
Slide version: 4.6.1
Android version: 5.0.2

Sometimes imgur links wont open in the built im viewer. For example this one: http://m.imgur.com/yafKFN8?r

**Comment by ccrama** [comment]
Can you link me to that post please?

**Comment by tomatpinne** [comment]
Here comes the reddit post. In addition the thumbnail is not visible.

https://www.reddit.com/r/comics/comments/48lzu6/i_meant_no_disrespect/
Den 2 mar 2016 22:44 skrev "ccrama" <notifications@github.com>:

**Comment by ccrama** [comment]
Works fine for me (has a thumbnail and the image loads). The issue might be Imgur rate limiting you, each IP address only has 500 Imgur api calls per day afaik. Another thing to check is reddit.com/prefs and enable thumbnails on all subreddits (that might fix the issue!)

**Comment by ccrama** [comment]
Should not be an issue anymore
