### ISSUE TITLE
Login to imgur account for uploads

### ISSUE THREAD

**Issue by bagarwa** [ccrama/Slide#1137]
Right now, if we make a new image post, Slide uploads the image to imgur as a guest / anonymous. User can't keep track of images uploaded that way. 

Instead, if Slide integrates imgur, just like it has synccit integration, users will be able to link their imgur account to Slide and when they make any image post, the image will get uploaded to a "Slide for Reddit" album in their own imgur account. The user will be able to go to imgur on desktop or in imgur app on their phone to see all images they've uploaded in that way.

**Comment by bagarwa** [comment]
"Not pursuing" means suggestion is declined?? :(

**Comment by Alexendoo** [comment]
It's not currently planned for inclusion, though that can always change. It does seem a little out of scope for a reddit app

**Comment by bagarwa** [comment]
Well, Slide for reddit already uploads images to imgur. Instead of doing it as guest, using the user's account would make it more organized. Unless that login thing makes stuff severely complicated in background.

**Comment by l3d00m** [comment]
It does make stuff a lot more complicated. It is too niche to get implemented.

**Comment by ccrama** [comment]
I agree with @Alexendoo  that it's a little out of the scope for a Reddit app, so probably will not be implementing this. You do have the option to share to Slide for instant posting from the Imgur app, though!

**Comment by okungnyo** [comment]
I think a fair compromise would be to have a little message in Slide, something like:

Your picture will be uploaded to Imgur anonymously, and you will not be able to delete it. Please use the official Imgur app and create an Imgur account if you would like to retain that control.

After all, in this privacy-conscious world, uploading a pic publicly and then never being able to delete it is a pretty big deal.
