### ISSUE TITLE
Imgur improvement

### ISSUE THREAD

**Issue by tomatpinne** [ccrama/Slide#1139]
As of now the imgur text is overlapping the figure. This means if there is a long text accompaning a picture the figure is not visible at all. Also the text size doesn't seem to follow the text size preferneces. In addition an album button would be nice to skip swiping through all the pictures to see the final one.

**Comment by Alexendoo** [comment]
What are you referring to by 'imgur text' exactly?

**Comment by ccrama** [comment]
Now there's a button to view the text in a popup instead of the old view!
