### ISSUE TITLE
Actionbar toggle chevron isn't centered horizontally

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#1149]
Slide version: 4.6.2-94-7d2688a
This is especially visible in card mode.

**Comment by Nxt3** [comment]
@The0x539 has this been fixed yet? It appears centered to me.

**Comment by The0x539** [comment]
![](https://i.imgur.com/IN80uLD.png)

Nope

**Comment by Nxt3** [comment]
I'm not sure I understand where you expect it to be.

**Comment by Controless** [comment]
I'm guessing exactly between the right edge of the thumbnail and the right card edge.

**Comment by Nxt3** [comment]
That's an easy fix--but I'm pretty sure the current look is intentional.

**Comment by ccrama** [comment]
It is intentional

**Comment by The0x539** [comment]
Looks a bit weird as a whole.

**Comment by Nxt3** [comment]
I think it looks normal. It would be weird if it were any higher up in the card.

**Comment by l3d00m** [comment]
I prefer how it is at the moment as well, it looks more like it is belonging to the expandable bottom. Having it centered would look weird.

**Comment by The0x539** [comment]
Centered horizontally would make it not look like it's part of the bottom?

**Comment by The0x539** [comment]
Also, the whitespace above it is a bit awkward.

**Comment by Nxt3** [comment]
@The0x539 I don't think it would. If it were further up--it would be odd that it then expands a menu so far down from it.

**Comment by The0x539** [comment]
At the very least more to the left, up is another issue.

**Comment by ccrama** [comment]
Fixed! Now it's centered horizontally between the side and the thumbnail
