### ISSUE TITLE
Actionbar toggle chevron should be placed at vertical center of thumbnail, not of post

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#1150]
Slide version: 4.6.2-94-7d2688a

**Comment by The0x539** [comment]
http://i.imgur.com/S7HjZXJ.jpg

**Comment by raazman** [comment]
Instead of that, why not expand upon long press? Just like comments, it should be an option to toggle on or off. Basically have the same behavior as tapping on comments.

**Comment by Alexendoo** [comment]
Because posts already have an action on both long and short press

**Comment by ccrama** [comment]
Fixed, now it's at the bottom
