### ISSUE TITLE
Number lists are not rendered properly in comments

### ISSUE THREAD

**Issue by anonymous-user** [ccrama/Slide#1152]
Here is an example comment:

http://www.reddit.com/r/androidapps/comments/493zn1/how_can_i_try_life_without_an_app_drawer/d0p3kf6

And here is what it looks like in Slide:

http://i.imgur.com/FVq1Gf9.png

The numbers are missing and all the items are connected like a run-on sentence.

**Comment by ccrama** [comment]
Has been fixed
