### ISSUE TITLE
Slide is lagging after updating Play Services to 8.7.03 and switching Launcher to Nova

### ISSUE THREAD

**Issue by gofirst2220** [ccrama/Slide#1153]
Slide version: 4.6.2 (March 5th)
Android version: 5.1.1
Play Services: 8.7.03
Device: AT&T Samsung Galaxy S6 (SM-G920A)

When I tried to use Slide, it lags so much after I updated Play Services to 8.7.03 and switched to Nova launcher. I get like 10 errors in last week or so.

**Comment by raazman** [comment]
I highly doubt Nova Launcher has anything to do with it. I use Nova and Slide runs perfectly.
