### ISSUE TITLE
Toggle to always show action bar does not work

### ISSUE THREAD

**Issue by joytrekker** [ccrama/Slide#1155]
After setting the action bar to open with long press the arrow button it is permanently hidden. The toggle to always show the action bar has no effect.

Slide version: v4.6.2-106-43ba053
Android version: Marshmallow

**Comment by oatberry** [comment]
I told @ccrama about this a few minutes ago, he should be pushing a fix soon.

**Comment by ccrama** [comment]
Yeah fixed, thanks
