### ISSUE TITLE
Battery Life Issue

### ISSUE THREAD

**Issue by Chromelon** [ccrama/Slide#1158]
Slide version: v4.6.2 (v4.7 RC) (3/6)
Android version: LG UX 4.0 (LG V10) 5.1.1

Battery life is very poor, with 25% battery usage (50% combined with screen and other things) over an hour. Normally get 5 hours or more of SOT so there's something strange about this.

**Comment by ccrama** [comment]
We worked it out in chat, but it appeared to be an issue with limited connectivity and the OS blaming Slide for battery used accessing the network
