### ISSUE TITLE
It crashed so many times in last week

### ISSUE THREAD

**Issue by gofirst2220** [ccrama/Slide#1159]
Slide version: Slide v4.6.2-110-25097c0
Android version: 5.1.1

It crashed on front-page, other subreddits randomly for 12 times in last week. Now Android offers me to uninstall.

**Comment by ccrama** [comment]
Doesn't help at all without either a crash report or some other info

**Comment by gofirst2220** [comment]
Where would I find the crash log?

**Comment by ccrama** [comment]
You click the "Report" button when it crashes.

**Comment by gofirst2220** [comment]
It crashes without report button. I guess after certain amount of crashes, it disables the report button and offers me to uninstall instead

**Comment by ccrama** [comment]
That's not how Android works, and Android doesn't offer an option to uninstall. What ROM are you on?

**Comment by ccrama** [comment]
We worked it out in chat
