### ISSUE TITLE
Spoiler tags aren't displayed correctly in newest update

### ISSUE THREAD

**Issue by gofirst2220** [ccrama/Slide#1160]
Slide version: 4.6.2 (4.7 RC)
Android version: 5.1.1
In the newest update, the spoiler tags are next to Spoiler links instead of on its own like the website does

**Comment by ccrama** [comment]
Slide has always done this, you click the "spoiler" link to show the spoiler

**Comment by gofirst2220** [comment]
Well, on reddit, you hover over the spoiler box to reveal the spoiler, why not tap on the box to do same thing?

**Comment by ccrama** [comment]
Not possible, sorry
