### ISSUE TITLE
Gray out read posts' text less subtly

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#1162]
MAYBE don't fade out bigpics either, doesn't look too good.

**Comment by Alexendoo** [comment]
Agreed with the bigpics thing, maybe instead of changing opacity change the colour to something else? like purple links on web, could use accent colour maybe?

**Comment by bantar** [comment]
I agree with this request.  I'm using the light theme and I can barely tell the difference between a read post and an unread one now.  In the previous release, it was very easy to see the difference.

**Comment by ccrama** [comment]
@bantar  he was actually suggesting the opposite, that I make it less subtle

**Comment by Alexendoo** [comment]
@ccrama "less subtly"

**Comment by ccrama** [comment]
Done
