### ISSUE TITLE
Tables and code tags can't be scrolled 

### ISSUE THREAD

**Issue by armandojrod** [ccrama/Slide#1164]
Slide version: 4.7.0 with swipe away from anywhere enabled, it works when that setting is disabled. 
Android version: 6.0.1

Self explanatory, here is an example of a table 

https://reddit.com/r/Android/comments/49k0wi/android_distribution_updated_for_march_2016/d0sdhuc?context=3

**Comment by Alexendoo** [comment]
Merge into #987
