### ISSUE TITLE
All subreddits are completely blank

### ISSUE THREAD

**Issue by simico** [ccrama/Slide#1169]
Slide version:
Android version:Marshmallow
![screenshot_20160309-101523](https://cloud.githubusercontent.com/assets/17746558/13639737/1fa4a7aa-e5e0-11e5-8ed3-b2ba4c342fd9.png)

**Comment by ccrama** [comment]
What are your filter settings? You may have filtered all content out

**Comment by simico** [comment]
I removed everything from the filters.  This just happened with the last release.
On Mar 9, 2016 1:27 PM, ccrama <notifications@github.com> wrote:What are your filter settings? You may have filtered all content out

**Comment by ccrama** [comment]
Content filters too?

**Comment by simico** [comment]
Only NSFW.  I just removed even that and it's still all blank
On Mar 9, 2016 1:29 PM, ccrama <notifications@github.com> wrote:Content filters too?

**Comment by ccrama** [comment]
What's your default sorting mode? And is it just on the frontpage? Also please screenshot your Settings > Filters and the content filter dialog as well, thank you!

**Comment by simico** [comment]
Default sort is Hot and this is happening on every single tab: front page/all/subreddits

**Comment by ccrama** [comment]
Can you provide the screenshots please. Also try changing networks, make sure Slide isn't in offline mode, and are you on any VPN?

**Comment by simico** [comment]
On Mar 9, 2016 1:45 PM, ccrama <notifications@github.com> wrote:Can you provide the screenshots please. Also try changing networks, make sure Slide isn't in offline mode, and are you on any VPN?

**Comment by simico** [comment]
Not on VPN and have been moving between cell and wifi all day.  Happens regardles.  Also not on Offline mode


![screenshot_20160309-133949](https://cloud.githubusercontent.com/assets/17746558/13647118/94a5767c-e600-11e5-9bbf-d3abdc21dd59.png)
![screenshot_20160309-133932](https://cloud.githubusercontent.com/assets/17746558/13647134/9e416bf0-e600-11e5-9637-6344c4f5e2a2.png)

**Comment by ccrama** [comment]
Ah, you have a space or an enter in the domain field :)

**Comment by simico** [comment]
Haha.  Thanks so much.  I love this app!
On Mar 9, 2016 2:13 PM, ccrama <notifications@github.com> wrote:Ah, you have a space or an enter in the domain field :)
