### ISSUE TITLE
Bug in settings

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#117]
When changing the base theme for Slide in the settings, pressing the back button does nothing.

**Comment by Alexendoo** [comment]
Works fine on my end

**Comment by alexsmithfanning** [comment]
I can't seem to reproduce this. I'll keep trying though.

**Comment by ccrama** [comment]
The arrow at the top or the physical back button?

**Comment by alexsmithfanning** [comment]
The arrow at the top.

**Comment by Revel1020** [comment]
Can confirm, I have the same issue. I posted it in on Google+ and Github a few hours ago.

**Comment by ccrama** [comment]
Ah arrow at the top is an easy fix. Thought you meant any back arrow

**Comment by ccrama** [comment]
Done with 742e7d71f85425ee89831bbaf5449ec92ebf8e5b
