### ISSUE TITLE
Multireddits laggy when using big pic

### ISSUE THREAD

**Issue by Deadleg** [ccrama/Slide#1174]
Slide version: 4.7
Android version: 5.0
Phone: LG G3

Performance on frontpage/individual subreddits is really good, but on multireddits scrolling through submissions is noticeably laggy. No so much choppy like its loading things, but the fps is low.

Changing images to cropped fixes it.

**Comment by ccrama** [comment]
Comments are extremely laggy as well, it's taking upwards of 40ms to inflate the comment views. It appears to coincide with this error

```W/ResourceType: Invalid package identifier when getting bag for resource number 0x00000e02```

**Comment by ccrama** [comment]
Should all be fixed with v4.7.3!
