### ISSUE TITLE
I can't submit crash reports

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#1175]
When Slide crashes and the report dialog comes up, Slide restarts too fast for me to be able to fill out the crash info.

**Comment by ccrama** [comment]
Handled by the OS, can't do anything about this (I don't tell slide to restart, the OS tries to resume) :(

**Comment by l3d00m** [comment]
Having the same problem with the newest update. Wasn't happening before.

**Comment by ccrama** [comment]
I really have 0 control over it
