### ISSUE TITLE
List of issues (Back buttons, unresponsive buttons)

### ISSUE THREAD

**Issue by Revel1020** [ccrama/Slide#118]
1. ~~Top 'Back' button in 'Default Theme' in Settings is not working.~~
2. 'OK' and 'Reset' buttons in 'Default Theme Settings' overlap the colors.
3. Tapping on 'Pro' or 'App Info' in Settings does nothing.
4. ~~Top Back button in the Settings menu is not working.~~
5. In the sidebar, when tapping the 'Saved' star or the 'Upvoted' arrow, nothing happens.

**Comment by ccrama** [comment]
1, 4 fixed with 742e7d71f85425ee89831bbaf5449ec92ebf8e5b

**Comment by ccrama** [comment]
2 fixed with 6c82a077c1ab6963926ab15edcf56597bc3dea74

3 fixed with add1272ebca1d270cf7a5f40680fbf2fd7836cc8

5 will be milestoned

**Comment by Alexendoo** [comment]
5 added as #199
