### ISSUE TITLE
Some way of differentiating between link types in comments

### ISSUE THREAD

**Issue by yasmara** [ccrama/Slide#1180]
EG: A little YouTube icon next to links that open a YouTube video, or an imgur icon for imgur links, etc.

**Comment by tasmo** [comment]
... or a simple full URL below would be fine.

**Comment by Alexendoo** [comment]
@tasmo If you long press a link it will display the URL

**Comment by ccrama** [comment]
Yeah long press was the solution to this. An image would be nice, but would cause major lag on some link heavy threads

**Comment by SZE2** [comment]
Please let the long press show a full link, this is useful where the domain does not tell you what type of content it is...

Example screenshot of a problematic link: http://i.imgur.com/6yIFDKV.png  

Thanks!

**Comment by ccrama** [comment]
How do you imagine it being shown? Not much I can do if it's a super long link

**Comment by SZE2** [comment]
Maybe add a second line that shows the end if the link, and cutoff the middle?

Take this one for example: "https://www.eff.org/deeplinks/2016/03/tell-congress-its-time-move-fastr"

Would show like this:
https://www.eff.org/deeplinks...
congress-its-time-move-fastr

And this would also let you see if a long link is directly to content, as you would see a trailing ".jpg" etc.

**Comment by ccrama** [comment]
Added an option where you can show the content type after the link like www.google.com (link) or imgur.com/blah.jpg (image), but it also works if the link has text like "this is an image (image)"!
