### ISSUE TITLE
New Feature: Multiple Account Support

### ISSUE THREAD

**Issue by Revel1020** [ccrama/Slide#119]
As the title says, Add multiple account support for people that have multiple reddit accounts.

**Comment by ccrama** [comment]
Going to take a lot of backend changes. In planning, though!

**Comment by Alexendoo** [comment]
Added in 8d40811cae29eb63465aac4842c73fee6d554f9a

**Comment by Revel1020** [comment]
You added the ability to change accounts but not add any new ones.
