### ISSUE TITLE
Android N bugs with links and splitscreen

### ISSUE THREAD

**Issue by cscorvax** [ccrama/Slide#1191]
Slide version: 4.7.3
Android version: N preview v1

I know it's a first beta of a new version of Android and therefore problems will occur, but I found a couple bugs that should be addressed before N is released, if they're not problems with N its self.

The more major of the two is that any links in comments or sidebars that lead to other posts or subreddits don't work. Link posts that lead to such addresses still work, and all links to lead to pages outside of Reddit work fine. For example, in /r/Android, the sidebar link to /r/AndroidQuestions doesn't work, but the link to their IRC channel works fine.

The other bug is that when running Slide in splitscreen, multi-column becomes enabled, regardless of if it's disabled for portrait mode. Also, when entering split screen, Slide restarts, but goes back to the previously open subreddit. Of course, fixing this will mean implementing proper splitscreen support, which will have to be tested in an emulator if you don't have a Nexus phone.

I'm new to Github, so I wasn't sure if I was supposed to write this as separate posts. Sorry if that's the case.

**Comment by ccrama** [comment]
Has this changed at all with the N Preview v2?

**Comment by ccrama** [comment]
I have had multiple reports opening subs now works, closing now. If any of these issues creep back up, feel free to re-open!
