### ISSUE TITLE
Huge lag in specific thread

### ISSUE THREAD

**Issue by silverAndroid** [ccrama/Slide#1195]
Version: 4.7.4
Android OS: 6.0.1

I noticed this morning that this specific thread caused a huge amount of lag...https://www.reddit.com/r/nottheonion/comments/4aaafj/reagan_airport_says_1_person_filed_6500_noise/

Seems to happen when opened from the front page or r/nottheonion

**Comment by bantar** [comment]
When I click on this thread, I see a blank preview image.  I'm able to click on the article.   @silverAndroid when you say lag, can you describe what this means?    The comments take long to load?   The comments lag when scrolling?   The linked article is slow to load?    Other than the blank preview image, it loads up just fine for me.

**Comment by ccrama** [comment]
Fixed! I broke it with afbaa3eaa5c8162b88bb3a9a0950083a11502146 by setting the image scale type to NONE, which loaded the whole 3000x4000 image into the view instead of subscaling it.
