### ISSUE TITLE
Reply deletes text if you scroll up or down in the thread

### ISSUE THREAD

**Issue by bantar** [ccrama/Slide#1197]
Slide version: 4.7.3
Android version: 5.0

While this is 100% a bug, please consider this a potential solution / enhancement at the bottom as well.

Pick any subreddit and a thread that has, let's say 50+ replies in it.   Scroll towards the middle of the replies and pick any message.    Long press and then click on Reply.   The reply dialog appears.  Type in some text (or a novel like I did).   Then, decide you want to review the comments a bit more before saving the reply.   Scroll up and down and notice that your reply is deleted.

Here is what I think is happening.   I believe that the app is dynamically loading replies as you scroll to not eat up all the memory.  Once you scroll to a position where the reply-to comment is unloaded, you lose your reply. 

NOTE:  If you reply to the OP, the behavior is different.  In this case, it always remembers the reply and never deletes it regardless of the paging that occurs.  No matter how much you scroll, it maintains your reply.   This is great.

However, the same lost reply occurs if you reply to the OP, then scroll left or right to the next message.  Go one left or one right and it stays put.   Go 2+ messages over and the reply is forever lost.

This is pure conjecture:   I would imagine the the reply is also lost if I'm typing it, then get interrupted, then let the phone timeout and sleep.  Later the phone decides to close the background app.  Start it up again to find your reply gone.  

ENHANCEMENT:   Consider storing the reply in a system buffer that autosaves if I scroll away or if the phone goes to sleep.   If my reply is ever lost, I simply reply again and get back my text.   Even better, when I restart slide, it might ask if I want to continue my reply and put me back in the editor.  Or let me get back to this position without having to search for the reply position.   Imagine that I was in the middle of a 2000 comment thread adding my insignificant comment to this jumble.   It might be hard to find my place again by eyeballing it.

**Comment by ccrama** [comment]
Has been fixed! Now it stores the text and re-opens the reply area when you scroll up to it. Also saves state through reloads as well
