### ISSUE TITLE
Unable to report bugs because slide reopens itself over the bug report form before you can hit send

### ISSUE THREAD

**Issue by yasmara** [ccrama/Slide#1199]
Slide version: 4.7.3
Android version: 6.0.1

**Comment by bantar** [comment]
Yes, I've seen this as well and in my last crash report, I documented this failure in the notes.   The app crashes, asks you to report it (report dialog loads) and before you have a chance (in other words, immediately), it crashes again.   Thus the initial crash report reason is lost.

**Comment by ccrama** [comment]
Slide is not on the Play Store currently, it's not possible to report
