### ISSUE TITLE
Can't scroll code in comments

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1201]
Slide version: 4.7
Android version: 6.0.1

For example, in a post like this https://reddit.com/r/tasker/comments/41uy6j/make_a_random_variable_more_random/cz5ez0o?context=3, you can't scroll horizontally to view the code

**Comment by bantar** [comment]
I've just loaded that thread.  I'm able to scroll left and right, however, it's not clear from the UI that I'm looking at a code block.  To me it looks like other inline text, except for the fixed font.

**Comment by Nxt3** [comment]
Mine shows a scrollbar, but I can't scroll.

**Comment by Alexendoo** [comment]
Same as #987
