### ISSUE TITLE
Really slow performance

### ISSUE THREAD

**Issue by Fnarley** [ccrama/Slide#1202]
Slide version: 4.7.4
Android version: 6.0.1

It takes a really long time to load posts and then when posts load takes a long time to load images using the internal viewer and comments in the thread. I'm talking several minutes waiting for comments and images to load. I can do the same actions in a different app like sync in much less time. Has been happening since around 4.7.2, have tried clearing app data, reinstall, reboot phone log out/in of app nothing seems to speed it up.

**Comment by ccrama** [comment]
That has been fixed in my comment_swipe_layout branch
