### ISSUE TITLE
Webview cannot scroll horizontally with swipe from anywhere enabled

### ISSUE THREAD

**Issue by realvz** [ccrama/Slide#1203]
Slide version:4.7.3
Android version:5.1.1

When using internal browser some websites are cut off. There is no option to scroll left or right.

**Comment by Alexendoo** [comment]
What sites? It doesn't sound like a Slide issue as that is pretty much handled by the webview or custom tabs

**Comment by realvz** [comment]
On my galaxy tab s2 8.0 I can't scroll left or right in internal Web browser,  it works fine when I use custom chrome tabs but I'd like to use internal browser because it's supports slide to go back to reddit. 
Here's a screenshot.  Screen rotation doesn't matter. 
http://imgur.com/6lebJa4

**Comment by Alexendoo** [comment]
Related #987, webview shouldn't get swipe from anywhere applied

**Comment by realvz** [comment]
On AMRC in iOS, there's a lock on the internal browser screen that will disable left swipe back to app and apply left swipe to current web screen. Something like that will be helpful.

If swipe from anywhere is disabled on webview, then what advantage would it provide over using custom chrome tab?

**Comment by Alexendoo** [comment]
You would presumably still be able to swipe from the edge, additionally history is shared with your chrome profile when using custom tabs, with this it wouldn't be stored anywhere.

**Comment by ccrama** [comment]
Fixed, now you can drag from the very edge to exit but not from the middle!
