### ISSUE TITLE
Floating Action Button hide viewed posts bug

### ISSUE THREAD

**Issue by realvz** [ccrama/Slide#1204]
Slide version:4.7.3
Android version:5.1.1

Pressing Action Button on frontpage hides all posts and doesn't retrieve any new posts.
However, if you scroll down where the app retrieves more pages and then press the Action Button it hides viewed posts and keeps new posts.

I don't have the same problem with Relay for Reddit.

Maybe this is just how Reddit behaves, in which case it would be helpful to hide the action button for the first page or make load other pages and then hide viewed posts on the first page.

https://youtu.be/u5KeImtWl1U

**Comment by Alexendoo** [comment]
Is this still occurring @realvz?

**Comment by realvz** [comment]
In my quick tests it's not happening anymore. I'd like a say or two more to test it throughly.

**Comment by realvz** [comment]
I think this is resolved in the current version. Can be closed.
