### ISSUE TITLE
Performance on this post is terrible

### ISSUE THREAD

**Issue by abraham** [ccrama/Slide#1209]
Slide version: 4.7.4
Android version: 6.0.1

Opening the image lightbox will cause zooming to take multiple seconds. Viewing the post makes it so thats crolling or even  trying to return to the stream takes several seconds.

> Sutra Baths Cave 
https://reddit.com/r/sanfrancisco/comments/4b44es/sutra_baths_cave/

**Comment by ccrama** [comment]
That is a massive photo, performance issues are expected

**Comment by Alexendoo** [comment]
Merge into #1195 

It's not expected performance issues, it's far more than that and hasn't always been around
