### ISSUE TITLE
Some YouTube links not opening in YouTube app

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#1215]
https://reddit.com/r/videos/comments/4b9im9/h3h3_the_leafy_rant/d177g72?context=3

For me it just opens in the chrome custom tab instead of the YouTube app

**Comment by ccrama** [comment]
It's a youtube.co.uk link, I was only checking for youtube.com. For a temp workaround, add youtube.co.uk to the list of domains to always open externally in Settings > Link Handling > Open Externally!

**Comment by ccrama** [comment]
Fixed for the next update
