### ISSUE TITLE
some "post hidden forever" will show up again

### ISSUE THREAD

**Issue by SZE2** [ccrama/Slide#1216]
I'm not sure exactly what triggers it, but I see these posts that I hid "forever" show up again on the 2nd or 3rd page of my front-page feed hours later

It may be that I hid them in their respective subreddits, and they show up in the front-page again or vice versa.

They appear in the list greyed out indicating that Slide knows that they are already read, it just "forgot" that they should be hidden.

**Comment by ccrama** [comment]
Hiding forever goes through the Reddit API, it's not hidden locally through Slide. Seems to be an API issue rather than a Slide issue

**Comment by ccrama** [comment]
Since it's an API issue, gonna mark as fixed on Slide's end
