### ISSUE TITLE
Tap on an opened image to enter immersive mode?

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#1218]
Tapping on the background, as opposed to on the image itself, would go back just like a swipe or a press of the back button. Not sure about this, but it'd be nice, especially with images with an aspect ratio matching that of the device.

**Comment by ccrama** [comment]
It's a good idea, but tapping is a UX gesture that closes the view. I think we're too far in dev to be changing a standard actions, unfortunately. 

Also, it's not really possible to tell if a user tapped on the image or the background as the whole view is the image view
