### ISSUE TITLE
Thumbnails not showing in list view

### ISSUE THREAD

**Issue by SZE2** [ccrama/Slide#1224]
Screencaps: www.vid.me/qhJn

Android 6.0

If you need more info, ask here and I'll try to help.

**Comment by ccrama** [comment]
It's working for me. Are you sure you weren't on offline mode?

**Comment by SZE2** [comment]
Yup. When I press where the thumbnail would be, the image will usually load.

**Comment by SZE2** [comment]
Clearing cache did not help

**Comment by SZE2** [comment]
Changing picture mode to big picture and back to thumbnail fixed it for now.

**Comment by ccrama** [comment]
I can't reproduce it so I'll see if anyone else can

**Comment by ccrama** [comment]
Believe it's been fixed for the next v5 alpha

**Comment by SZE2** [comment]
This happens for me together with #1198
