### ISSUE TITLE
Synccit integration doesn't always work

### ISSUE THREAD

**Issue by gyeben** [ccrama/Slide#1225]
Slide version: 4.7.5
Android version: 5.0.1

After entering my Synccit username and authentication code and pressing the save button Slide tells me that it could not authenticate. If I press the save button for the second time, it tells me that Synccit is active on my device and it actually works. But then sooner or later it stops working and I couldn't figure it out why.

**Comment by ccrama** [comment]
It only syncs when you exit the app for data saving purposes

**Comment by ccrama** [comment]
If closing did not sync correctly, feel free to re-open this issue.
