### ISSUE TITLE
Issue opening images

### ISSUE THREAD

**Issue by Chromelon** [ccrama/Slide#1226]
Slide version: 4.7.5
Android version: 5.1.1 LG UX 4.0
When I open some images, Slide doesn't attempt to open them at all, and I can't click on the download/share/open externally button in the image view.

**Comment by ccrama** [comment]
Has already been fixed for v5

**Comment by Chromelon** [comment]
Oh, good! When is the ETA for v5? Is there an alpha apk?

**Comment by ccrama** [comment]
Alpha is being pushed in about 5 minutes ;)
