### ISSUE TITLE
Long press to show action bar still shows just the downvote button.

### ISSUE THREAD

**Issue by onespaceman** [ccrama/Slide#1229]
Slide version: Slide v4.7.5-77-c39502e
Android version: 6.0.1

https://goo.gl/photos/o1qaf98uakB6eni16

**Comment by ccrama** [comment]
Just pushed a fix a second ago! Thanks for the report

**Comment by onespaceman** [comment]
Jeeze, that was fast. Not that I'm complaining.

**Comment by ccrama** [comment]
Haha I just saw the reports a few mins ago, was just one line of code messing up :)
