### ISSUE TITLE
while writing a comment, reloading (pulling down) will lose it

### ISSUE THREAD

**Issue by sreich** [ccrama/Slide#1232]
Slide version:4.7.5-79-a0afb34
Android version:6.0.1

-write a reply to a thread or other comment
- don't hit submit yet. just pull down (accidentally) on the view to get it to reload
- you can't access the comment anymore, the edit box is hidden...but navigating elsewhere prompts to discard

so, it's still there..just the view doesn't show it anymore

**Comment by ccrama** [comment]
I could make it prompt

**Comment by sreich** [comment]
Sounds good! Just make sure if you hit yes then the state is fully cleared (and doesn't re prompt or whatever)

**Comment by bantar** [comment]
This is largely a duplicate of #1197.    However, it does show another use case of that problem.

**Comment by ccrama** [comment]
Fixed!
