### ISSUE TITLE
switching between apps often makes slide reload

### ISSUE THREAD

**Issue by sreich** [ccrama/Slide#1233]
Slide version:4.7.5-79-a0afb34
Android version:6.0.1

- enter slide for the first time..initial splash/startup
- contents are now loaded
- multitask, by going in a browser, or a few other apps
- navigate back to slide
- slide once again starts reloading

this is especially horrible on mobile, as it means each time you do this it eats more and more of your data (on project fi, so that's money).

device is nexus 6p. it isn't being killed by oom killer either.

**Comment by ccrama** [comment]
If slide restarts, that means it's base data was ram cleared and I have to recreate it. Not much I can do, unfortunately

**Comment by ccrama** [comment]
Not really fixable, sorry
