### ISSUE TITLE
load more threads before we hit the end of the list

### ISSUE THREAD

**Issue by sreich** [ccrama/Slide#1234]
Slide version:4.7.5-79-a0afb34
Android version:6.0.1

right now what happens is, the view loads up and gets populated, you scroll down to the end of the list (easiest to see on a slow connection, but even on a fast one it's pretty noticeable).

when you hit the end of what's available, *then* it loads the rest of the contents.

i don't know if this is possible, or if it is how difficult it will be, but it would be nice to begin loading more threads before you reach the end. that way it's "infinitely scrollable", and means i don't have to wait a few seconds each time i hit the end of the loaded list.

**Comment by ccrama** [comment]
It starts loading 3 posts from the bottom so if you scroll past those too quickly, you see the loading circle. I don't really know if there's a better way to do it, but possibly could move it to 5?

**Comment by sreich** [comment]
That sounds better, yes. Although it might need to be more than that.

 How many does it load when you get near the bottom? It looks like it loads a full page.. But maybe that's necessary due to the api. 

Keep in mind this is usually for slow connections, one should be able to slowly scroll and read each one and hopefully never see the background loading of each comment.

**Comment by ccrama** [comment]
It loads 50 each time, the number being loaded makes no real speed difference. I don't want to do it too much, though, for data conscious people like myself

**Comment by ccrama** [comment]
Done, now it loads up 5 higher than before (I was wrong, it was 0 before not 3)
