### ISSUE TITLE
Add loading bar to all images (possible images loading issue)

### ISSUE THREAD

**Issue by Chromelon** [ccrama/Slide#1235]
Slide: v5 alpha
Android: 5.1.1 LG UX 4.0

Not all images have loading bars at the top, and images take fairly long to load for me so I can't tell if they're loading or not

Possible images not loading bug?

**Comment by ccrama** [comment]
All of them do, which views don't?

**Comment by Chromelon** [comment]
Alright, so I think my issue is that occasionally for me, images just aren't loading, even on 5 bars of LTE

**Comment by ccrama** [comment]
Do you have a link to an example?

**Comment by Chromelon** [comment]
Yeah, it just seems to be with my phone. Close when you want.

**Comment by ccrama** [comment]
Sorry :(, let me know if you figure out why
