### ISSUE TITLE
post image not displaying full size

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#1240]
Here's the link:
https://reddit.com/r/iamverysmart/comments/4bl0il/someone_call_nasa/

I remember you saying something about small images not displaying full size, but this image would look totally fine full size, so I think it should

**Comment by ccrama** [comment]
That's on purpose, the height is too low to show and look decent

**Comment by kufii** [comment]
if you tap on the image to display it full size, it looks totally fine

**Comment by ccrama** [comment]
On my device it's really tiny (less than 1/8th the screen). Might look okay on some devices, but not on the majority of them
