### ISSUE TITLE
Up comment navigation arrow inconsistent

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#1241]
the down arrow works fine, but the up arrow often jumps to the wrong place and stops working entirely

**Comment by joytrekker** [comment]
yeah it needs some work #1148

**Comment by jeefo519** [comment]
The down arrow seems to not jump to the correct position if you have collapsed some comments in one of the parent comment sections lower below.

**Comment by Alexendoo** [comment]
Covered by #1148 and #1258
