### ISSUE TITLE
Request: Different way to display Imgur image descriptions

### ISSUE THREAD

**Issue by jhtervay** [ccrama/Slide#1242]
Slide version: v4.7.5
Android version: v6.0.1

Currently, when viewing an image within an Imgur album, you can view the image description by pressing a "TT" looking icon towards the top of the album viewer. Doing so will create a small popup window giving the description.

The issue with this implementation is that - not only does it take focus away from the image - but it covers the image itself.

The image viewer has lots of free space available (or least it does on a 1440x2560 screen - unable to confirm on smaller res screens) that could be utilized for image descriptions. Perhaps a box below or above the image that holds the description could be implemented.

Unfortunately I am not experienced enough with Android to make this change myself.

Images of current view:
http://i.imgur.com/lCarsmf.jpg
http://i.imgur.com/uokPNLD.jpg

**Comment by Alexendoo** [comment]
Seems like it would require a lot of boundary checking and whatnot, personally I just use the vertical album view as it has the descriptions/titles there already on account of being scrollable

**Comment by ccrama** [comment]
Merged with #1310
