### ISSUE TITLE
Slide force closing when picking save location

### ISSUE THREAD

**Issue by Chromelon** [ccrama/Slide#1245]
Slide version: v5 release candidate (4.7.5-79-a0afb34)
Android version: 5.1.1 LG UX 4.0

When I try to download https://reddit.com/r/GamePhysics/comments/4bsj4q/gtav_trials_fusion_physics/ and I haven't set up my download location, slide FCs.

**Comment by ccrama** [comment]
Does slide have storage perms?

**Comment by ccrama** [comment]
Didn't mean to close :P

**Comment by Chromelon** [comment]
I didn't restrict it from having those permissions, not on MM so I can't do that natively.

**Comment by Chromelon** [comment]
Seems to be just that image. Set up storage location on another image and it worked. Strange.

**Comment by ccrama** [comment]
That's cause it's a gif

**Comment by Chromelon** [comment]
Actually, it's when it tries to set for save location

**Comment by Chromelon** [comment]
GIF* and yeah

**Comment by ccrama** [comment]
Fixed, thanks for the report!
