### ISSUE TITLE
Non-locked post not showing upvote/downvote on front-page

### ISSUE THREAD

**Issue by Chromelon** [ccrama/Slide#1247]
Slide version: v5 RC (4.7.5-96)
Android version: 5.1.1

https://reddit.com/r/Blep/comments/4bs5dv/devious_blep/ this post didn't have upvote or downvote buttons on front-page but when I opened it, it had the buttons

**Comment by Plastix** [comment]
I think I experienced this bug as well. Is this what is happening for you?
![screenshot_20160325-224243](https://cloud.githubusercontent.com/assets/1526881/14057615/ad56ac9e-f2db-11e5-9fdd-572b9ff0e84a.png)

**Comment by Chromelon** [comment]
Yes

**Comment by ccrama** [comment]
Fixed!
