### ISSUE TITLE
Chrome Custom Tabs not working 

### ISSUE THREAD

**Issue by jliu168** [ccrama/Slide#1250]
Slide version: 5.0
Android version: 6.0.1

As the title suggests, the option to use Chrome Custom Tabs as a link handler simply does not work in my case. Having the option set opens links up in my default external browser.

**Comment by ccrama** [comment]
That's actually a limitation with Chrome Customtabs. You have to clear the defaults for your default browser, open with Chrome Customtabs, and then you can set your default browser again. I don't know why Google implemented it like that

**Comment by jliu168** [comment]
Oof, that's kinda strange. Thanks for replying! Excellent work on the new update.

**Comment by Alexendoo** [comment]
It's not a limitation of custom tabs as it's not even handled by custom tabs it's done by android, it works fine on lollipop at least since we did 4a793aa8cf2156b4d803d80da9dc5688f6601301

**Comment by ccrama** [comment]
Assuming this is fixed
