### ISSUE TITLE
Toolbar actions not centered vertically

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1251]
Slide version: 4.7.0-204-303d181 (latest built from source)
Android version: v6.0.1

The toolbar icons/text is not centered vertically on larger displays; they are slightly off-center on my Nexus 6P--but are majorly off center when on my Pixel C.

I don't think this is XML-layout related--but rather the code you used to calculate header height? I'm not 100% on that though. The offcenter-ness has been this way for a few builds now.

[See my screenshots here](http://imgur.com/a/mK9SY)

**Comment by ccrama** [comment]
Should be fixed now!

**Comment by Nxt3** [comment]
Which commit fixed this? I can't tell lol. Was it the minHeight on the toolbars?
