### ISSUE TITLE
Post hiding in background

### ISSUE THREAD

**Issue by 2fst4u** [ccrama/Slide#1254]
Slide version: 5
Android version: 6.0.1

Occasionally a post gets "stuck" in the background of my front-page feed and it can bee seen in the gaps between cards.

**Comment by Alexendoo** [comment]
Can you get a screenshot of this @2fst4u?

**Comment by nbn22385** [comment]
http://imgur.com/lnPoHlA
http://imgur.com/aGh2hJV

The hidden post will peek through the gap between the first 2 posts.

**Comment by ccrama** [comment]
Should be fixed now
