### ISSUE TITLE
Comment navigation arrow issues

### ISSUE THREAD

**Issue by yasmara** [ccrama/Slide#1258]
Slide version: 5.0.1
Android version: 6.0.1 Nexus 9

- [x] After collapsing a comment thread (or just part of one) the arrows navigate to the second comment of each thread instead.
- [x] Sometimes navigating back up jumps to the last comment of the thread above, although I can't always reproduce this one.

**Comment by SZE2** [comment]
Also, sometimes they don't work entirely.

Here is a screencap: www.vid.me/5Pud

This is with the "fold actual parent comment" setting enabled.

**Comment by ccrama** [comment]
All fixed now
