### ISSUE TITLE
This image doesn't display properly

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1261]
Slide version: 4.7.0-210
Android version: v6.0.1

[The image found in this post](https://www.reddit.com/r/OSHA/comments/4c2305/the_only_other_way_to_exit_this_section_of_the/) doesn't display properly. On desktop, the correct image is displayed.

In Slide: http://i.imgur.com/WYVH6WB.png

On Desktop: http://i.imgur.com/N76Kufg.png

**Comment by Alexendoo** [comment]
Usually the thumbnail source via reddit is used as an image because it's full resolution, however seems it's not the case here? Strange, perhaps we've made an incorrect assumption or reddit grabbed something different as the preview image in this case

https://i.redditmedia.com/fBkOk6LRjE1EbR2--pk0tYyfojz4LR15ew3gamV9w9Q.jpg?s=8eb8bff789bb80eae89fd59c2b14780a

**Comment by Nxt3** [comment]
Yeah, the link in Slide to the content differs from on the desktop

**Comment by ccrama** [comment]
I think that's a reddit bug, I've been noticing it in the last few days but this was not the case for the last 3 months of using that API

**Comment by Nxt3** [comment]
I wouldn't be surprised. This is the only time I've ever encountered this issue.

**Comment by Alexendoo** [comment]
Will keep this open for now, if it crops up again it would indicate we should rely less on reddit's thumbnail generation

**Comment by Nxt3** [comment]
Now that you say that, I noticed I've run into a similar issue happening when in comments.

https://reddit.com/r/CringeAnarchy/comments/4bqahv/um_excuse_me/

I have "Crop image in comments" enabled, but this post doesn't do that. It still shows the full image. I've run into this issue two or three times. This is the only example I could find off the top of my head. 

Not sure if that issue is related to this one.

**Comment by Nxt3** [comment]
https://reddit.com/r/BlackPeopleTwitter/comments/4cmmvr/sorry_sir_just_feeling_a_little_krabby_today/

Happened again

**Comment by ccrama** [comment]
Is this still an issue? Haven't come across it in quite a while

**Comment by Nxt3** [comment]
[The link above your comment](https://github.com/ccrama/Slide/issues/1261#issuecomment-203771073) loads fine; the one in the OP doesn't still. I don't think this is a Slide problem; if it happens again, I'll reopen this issue.
