### ISSUE TITLE
[UI] Elements all over settings overlap

### ISSUE THREAD

**Issue by elmkzgirxp** [ccrama/Slide#1264]
![screenshot_20160328-004044](https://cloud.githubusercontent.com/assets/12324510/14066573/f9de6066-f47f-11e5-8917-62996c963ce6.png)
![screenshot_20160328-003928](https://cloud.githubusercontent.com/assets/12324510/14066574/f9e55646-f47f-11e5-83b5-5a74b4964d4b.png)
![screenshot_20160328-003857](https://cloud.githubusercontent.com/assets/12324510/14066575/f9e8fa76-f47f-11e5-8958-0fc4ae789507.png)
![screenshot_20160328-003845](https://cloud.githubusercontent.com/assets/12324510/14066576/fa06d582-f47f-11e5-8695-5346949f0547.png)
![screenshot_20160328-003724](https://cloud.githubusercontent.com/assets/12324510/14066585/524dd3b2-f480-11e5-98fa-02b397fdfb18.png)

Slide version: 5.0.1
Android version: 6.0.1
Resolution: 480×854
Density: 240dpi

**Comment by Chromelon** [comment]
How big is your screen, physically?

**Comment by nbn22385** [comment]
Also happens for me on some elements:

Settings > General > Main Theme (Only tint outside the subreddit)
Settings > Comments (Navigate comments using volume buttons)
Settings > Reddit Preferences (I am over 18 and want to see NSFW content)

Nexus 5 (Android 6.0.1), Slide 5.0.3

**Comment by ccrama** [comment]
Should be fixed now!
