### ISSUE TITLE
Scrolling/zooming is off in webviews

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1265]
Slide version: 64da4a45edb9930bc0519de09c03a4c717881284
Android version: 5.1.1

https://www.reddit.com/r/slideforreddit/comments/4c42s8/request_zooming_in_the_internal_browser/

Essentially, you can't zoom and horizontal scrolling does seem a little strange. I went all the way back to 4.5.1 in hopes I could find a bisect but could not. Perhaps it's always been an issue and we just never noticed

**Comment by ccrama** [comment]
Should be fixed now!
