### ISSUE TITLE
When a comment consists only of a link, tapping anywhere on the comment will open that link

### ISSUE THREAD

**Issue by ledoge** [ccrama/Slide#1266]
[Example](https://www.reddit.com/r/AskReddit/comments/4c2g1b/reddit_what_is_the_worst_movie_scene_of_all_time/d1ehf9g)
Tap anywhere on the lower half of the comment and the link will open.

Slide version: 5.0.1
Android version: 5.1.1

**Comment by Alexendoo** [comment]
Merge into #907
