### ISSUE TITLE
Allow users to delete subreddits from a multireddit without using the FAB

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1268]
The same as how you can with reorder subreddits, minus the reordering

Would solve a couple issues, firstly that the + FAB is not the first thing you'd think of to use if you wish to remove content. It also would allow you to get rid of subreddits that you aren't subscribed to, as currently you cannot untick them

**Comment by ccrama** [comment]
Done, now tapping on it will ask to remove it
