### ISSUE TITLE
Post links in /r/live cause Slide to freeze

### ISSUE THREAD

**Issue by JustinTrouble** [ccrama/Slide#1270]
Slide version: 5.0.1
Android version: 6.0.1 (Android security patch level: 1 March 2016)

In Slide, I can browse posts and comments in /r/live, but if I click on any of the post's links, it causes Slide to freeze.

**Comment by Alexendoo** [comment]
When you try to open the live threads themselves? Strange it should just open externally

**Comment by ccrama** [comment]
Yeah live links open externally by default. Mind linking us to it?

**Comment by JustinTrouble** [comment]
I've cleared the app data, and still have the problem.

Clicking on any **image thumbnail** (the grey globe) of any of the posts in /r/live in the screenshot below causes Slide to freeze (but as you say it should open the live page externally).

Clicking on any post title brings up the comments as normal, and is working fine. Clicking on the link in here will also cause Slide to freee.

![screenshot_20160329-182525](https://cloud.githubusercontent.com/assets/16081842/14117289/eaa10e16-f5db-11e5-97a0-ea1ea7e0ab0e.png)

**Comment by ccrama** [comment]
It's not possible to open live links in Slide, it will open a menu that lets you select an app to open with, and Slide is specifically taken out of that list. It might be what you have it set to auto-open with (chrome or another Reddit app) that's lagging

**Comment by ccrama** [comment]
Closing, not possible to open these links

**Comment by JustinTrouble** [comment]
I have attached a logcat taken when trying to open a /r/live link.
I wondered if you might like to take a look. The log repeats endlessly with the same entries over and over:
ActivityManager: START u0 {act=android.intent.action.VIEW dat=https://www.reddit.com/... flg=0x80000 cmp=me.ccrama.redditslide/.Activities.OpenContent (has extras)} from uid 10084 on display 0
(Activity.java:6251): https://www.reddit.com/live/wpytzw1guzg2/
(OpenRedditLink.java:28): Link is https://www.reddit.com/live/wpytzw1guzg2/

[Log_2016-04-11_16-13-50.txt](https://github.com/ccrama/Slide/files/213273/Log_2016-04-11_16-13-50.txt)

**Comment by l3d00m** [comment]
Do you have installed the debug version as well?

**Comment by JustinTrouble** [comment]
I only have the alpha version installed.

**Comment by ccrama** [comment]
Ah, clear slide defaults and try again. You might have set live links to open with slide before it checked, and therefore you get stuck in a loop. For future/current users this is not an issue

**Comment by JustinTrouble** [comment]
App info -> Open by default -> Clear defaults doesn't fix the problem.

I discovered that the problem is with App info -> Open by default -> Open supported links.
It was set to "Open in this app". I've changed it to "Ask every time" and now I'm correctly asked which app to open these links.

The official Reddit app opens /r/live links, https://www.reddit.com/account-activity, and https://www.reddit.com/gold/about in a Chrome Custom Tab.

Please can Slide do this too, to create a better in-app experience? At the moment it's confusing as to what links can be safely opened in Slide, and which can't, especially when Slide is offered as a option when asked what app to open with.
Before looking in to this, as a user I would have assumed Slide could handle all Reddit links (whether it opens them in the app, or in a Chrome Custom Tab/internal/external browser (as defined in link handling setting)).

When trying to open these links (rightly or wrongly) in Slide, it presumably causes Slide to get stuck in a loop (as demonstrated in the logcat above), which still shouldn't happen.

**Comment by JustinTrouble** [comment]
Please also see: https://plus.google.com/115646860973681860104/posts/ce57Q9Fk8Cb

**Comment by ccrama** [comment]
This is because you set slide as the default before the check for domain type was added. In the future you can't open the link with Slide and there really isn't a way I can fix it retroactively (was added in 4.7 I think)

**Comment by Alexendoo** [comment]
With the addition of external domain filters it doesn't make sense to open them externally by default using a separate method, having them open in a browser will fix this and make somewhat more sense, which I'll look into.

**Comment by ccrama** [comment]
Should now work fully, tested on my devices. It will open live links as an embed if possible and in web otherwise

**Comment by JustinTrouble** [comment]
Thanks so much for this. It's much improved, should provide a more consistent experience, and it's really fast opening these links!

Did you see my comment on the G+ post? I said that I found a problem (I have 5.1.6 alpha)...

Clicking on a /r/live link in Slide doesn't work. Here's what I see:
![screenshot_20160413-084156](https://cloud.githubusercontent.com/assets/16081842/14555116/92f85c68-02e8-11e6-9730-c941992a0838.png)
Curiously it works fine if clicking a /r/live link from outside Slide - it's opens in Slide and works.

**Comment by Alexendoo** [comment]
That one's fixed for the next release
