### ISSUE TITLE
frontpage empty when hiding read posts after reading for a long time

### ISSUE THREAD

**Issue by perler** [ccrama/Slide#1271]
Slide version: latest
Android version: 6.0

This may be related to https://github.com/ccrama/Slide/issues/1095 but I think it happend before 4.6. 

Do this:

1. enable "mark read when scrolling"
2. start slide
3. read the frontpage for at least 3 reload cycles, maybe more
4. exit slide
5. start slide again
6. press FAB to hide read

quite often now the reload sign is circling and that's it. sometimes one single post can be seen, that's it.

**Comment by ccrama** [comment]
Should no longer be an issue, feel free to re-open if you get this after v5.3
