### ISSUE TITLE
Share image shares Reddit thumbnail

### ISSUE THREAD

**Issue by scottder** [ccrama/Slide#1272]
Slide version: 5.0.1
Android version: 6.0.1

I was attempting to share an imgur image and it gave the Reddit thumbnail instead.

**Comment by Alexendoo** [comment]
Do you have a link to the post @scottder?

**Comment by scottder** [comment]
This is the one I tried. I was attempting to send to a friend using Trillian and his time no URL was passed at all.

https://reddit.com/r/funny/comments/4c9xat/nooooo_hold_on_my_friend/

**Comment by bantar** [comment]
I've reproduced this bug on Android 5.0 with Galaxy S5.   Same link, clicked on ..., then Share Post, selected Textra (SMS) and it pastes the following text:  "Nooooo, hold on my friend http://imgur.com/BxQSK2W"

**Comment by Alexendoo** [comment]
Is that not the expected outcome @bantar? A thumbnail URL would look something like https://b.thumbs.redditmedia.com/WasXrIELpYYI67e-dmFpG75n-vAzhocCBCKsTtgzjqQ.jpg

**Comment by bantar** [comment]
Well, I just compared this with Now for Reddit behavior.   There, this same link provides two share options:  Link or Comments.   If it shares the link, then it is indeed correct.   If I were intending to share the thread (comments), then it should be different.   I was confusing this distinction as the OPs  problem.   

If it's link vs thumbnail, then indeed I'm seeing correct behavior.

**Comment by Alexendoo** [comment]
Yeah that's expected, if you wish to share the comments choose the 'share comments' option, 'share post' is a bit ambiguous there so perhaps it would be good to use 'share link' instead as well

**Comment by bantar** [comment]
Well, honestly, I wasn't reading the words.  I just scanned the icons and found the typical share icon.   Now that I've gone back and actually read the words, I now see the share comments!   DOH!

**Comment by horrorslice** [comment]
Slide v 5.0.1
Android 6.0.1

I haven't been able to share any images directly with the built in IMG viewer. I just get the error "cannot attach media".

**Comment by ccrama** [comment]
Fixed!
