### ISSUE TITLE
Clicking on pictures does not open some pictures

### ISSUE THREAD

**Issue by bantar** [ccrama/Slide#1276]
Slide version: 5.0
Android version: 5.0

I'm not sure if this is expected behavior or a bug.   Since 5.0, I've noticed that often I see a picture, but I can't click on the picture to open it.   I think the pattern here is that the initial thread post is text that contains one or more links within.   It appears that Slide grabs the first link and uses it for a picture to display.   This is a nice feature.   Clicking on said picture will not open it though.  You must find the link in the text and click on it instead.

Here's a few examples:
https://www.reddit.com/r/MechanicAdvice/comments/4ccygn/does_this_seem_like_a_needless_upsell/

and 

https://www.reddit.com/r/MechanicAdvice/comments/4ccxbs/what_happened_to_my_paint/

**Comment by The0x539** [comment]
As I understand it it's intended behavior, if, as described, slightly problematic.

**Comment by Nxt3** [comment]
Pretty sure this is intended.

**Comment by ccrama** [comment]
That is intended. You can disable this behavior in Settings > Comments
