### ISSUE TITLE
Use suggested comment sort on posts that have it

### ISSUE THREAD

**Issue by pghant** [ccrama/Slide#1278]
This is an enhancement request. Default sort by Best is good. But some threads will have suggested comment sort. For example,

https://reddit.com/r/Android/comments/4c9p1n/moronic_monday_mar_28_2016_your_weekly_questions/

This thread has a suggested sort of New. Slide should have an option to use suggested comment sort for posts that have it. 

Slide version: 5.0.1 
Android version: 6.0.1

**Comment by ccrama** [comment]
Done! Only works for submissions opened through a general listing, though, not direct links (would require a double load on direct links, unfortunately).
