### ISSUE TITLE
Use new less sensitive swipe-away system with opened images and albums

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#1283]
If it isn't already used. Can't quite tell, but I _think_ it isn't.

**Comment by ccrama** [comment]
Not really applicable to this view as it's not a ViewPager view. I think the current implementation works fine on Images and Gifs as they are

**Comment by Alexendoo** [comment]
Images and gifs are fine, but vertical albums would benefit from it

**Comment by benjamindean** [comment]
The problem occurs, basically, on every activity where vertical layout **and** swipe available at the same time.

**Comment by ccrama** [comment]
Now it uses the new view for albums! Not going to do for images though, would be complicated with zooming in and such
