### ISSUE TITLE
Imgur gallery issues

### ISSUE THREAD

**Issue by scottder** [ccrama/Slide#1288]
Slide version: 5.0.2
Android version: 6.0.1

Issues albums not showing though they are available on ingur

Her is one that failed for me.
Https://reddit.com/r/DIY/comments/4cilw7/another_redditor_posted_a_tv_stand_he_built_using/

**Comment by bantar** [comment]
Here are two more failing examples:

https://www.reddit.com/r/funny/comments/4cmy9y/well_shit/
https://www.reddit.com/r/aww/comments/4ckrax/over_the_past_5_years_my_dog_has_put_up_with_a_lot/

Both of these open fine in other apps, but in slide say:  "Album not found  An error occurred when loading this album. ..."

**Comment by ccrama** [comment]
The Imgur API removed the /2/ endpoint and most apps are affected. Will have to rewrite albums to use v3 which is freemium and rate limited, unfortunately :(

**Comment by ccrama** [comment]
Fixed now, moved to v3
