### ISSUE TITLE
Possible to open a sidebar on the frontpage

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1291]
Slide version: 5.0.2

You can swipe from the right edge like you are going to open a sidebar while on the frontpage--and you'll get a sidebar for a subreddit (in my case, it's /r/android; I'm only subscribed to /r/android, /r/androidcirclejerk, and /r/fiftyfifty). If I swipe away from the frontpage and then come back, this issue disappears.

Pressing the sidebar overflow menu action doesn't open the sidebar though.

**Comment by yashghelani** [comment]
Exact same issue with me. It's /r/android in my case too, but I'm not subscribed to it.

**Comment by ccrama** [comment]
Fixed!

**Comment by yashghelani** [comment]
Thanks!
