### ISSUE TITLE
additional comments won't load

### ISSUE THREAD

**Issue by gofirst2220** [ccrama/Slide#1294]
Slide version: 5.0.3
Android version: 5.1.1

Like the title states, the additional comments in subthreads within posts won't load in latest version of Slide. It just shows the "loading comments" then hides. This happened on North Korean Prisoner AMA and all other posts in all subreddits and the frontpage.

**Comment by alexsmithfanning** [comment]
Happens to me too.

**Comment by gofirst2220** [comment]
That's odd, it also affects Relay too. I guessing API is skewed for now.

**Comment by ccrama** [comment]
I'm not noticing this, so must be an API issue

**Comment by Nxt3** [comment]
It's definitely an API issue; I had this problem all the time in Sync.
