### ISSUE TITLE
Issue with Imgur albums. 

### ISSUE THREAD

**Issue by Lochstock** [ccrama/Slide#1295]
Slide version:5.0.1
Android version:5.1.1
I can't seem to load any Imgur albums, I've tried restarting the app but nothing seems to work. Thanks.

**Comment by Nxt3** [comment]
Already been fixed. Also, #1288

**Comment by joytrekker** [comment]
Not fixed as far as I can tell. v5.0.3 The album view opens but fails to display any images.

**Comment by joytrekker** [comment]
So it seems this is a problem with imgur there is an outage with their api and some keys are not working. Updates here http://status.imgur.com/

**Comment by Nxt3** [comment]
Yeah--so this issue can be closed as it isn't something Slide can fix.
