### ISSUE TITLE
Imgur images opening in image viewer and browser

### ISSUE THREAD

**Issue by Chromelon** [ccrama/Slide#1296]
Slide version: 5.0.3
Android version: 5.1.1

Example: me irl 
https://reddit.com/r/me_irl/comments/4cp75p/me_irl/

**Comment by Chromelon** [comment]
Not all images, but a fair amount are doing this.

**Comment by Chromelon** [comment]
i.imgur.com links load fine, regular imgur links don't.

**Comment by ccrama** [comment]
It's because the Imgur API is down. Will fix itself when they fix it
