### ISSUE TITLE
New posts not loading

### ISSUE THREAD

**Issue by kelvinalfaro** [ccrama/Slide#13]
Scroll far down enough and new lost do not load. Happens on all ,frontpage,  and any other sub.

**Comment by ccrama** [comment]
Fixed with 79659d1

**Comment by Alexendoo** [comment]
It seems that in any sub eventually scrolling will hit a wall where posts cease to load (even without finishing a sub as per #43).

**Comment by ccrama** [comment]
Fixed with 85fb67c73a8fb0d4d3aea2da27ddc44867924ca4 for good this time!
