### ISSUE TITLE
Refresh even if no settings are changed 

### ISSUE THREAD

**Issue by jonasborggren** [ccrama/Slide#1300]
Slide version: 5.0.3
Android version: 6.0.1

Not really a bug but would help a lot if you would only refresh if the result of the settings activity was that anything has changed.

**Comment by ccrama** [comment]
There are actually 14 settings activities, it would be a pain to keep track of all of them so I call it every time

**Comment by Nxt3** [comment]
ccrama, where does the refresh of the MainActivity occur? I could implement something that fixes this.

**Comment by l3d00m** [comment]
@n3xt MainActivity.java Line around 170-180. I'm on mobile right now so I can't link :(

**Comment by Nxt3** [comment]
Thank you. :D

**Comment by Nxt3** [comment]
Yep--this will be difficult to implement given how it's already coded up...
