### ISSUE TITLE
Fix padding for username chips

### ISSUE THREAD

**Issue by angrybacon** [ccrama/Slide#1303]
Slide version: 5.0.3
Android version: 5.1.1

Purely cosmetic change. 

Not too sure what is used to display usernames (let's say chips). They don't look vertically centered (not only the purple and orange ones).  

![screenshot_2016-03-31-20-05-34](https://cloud.githubusercontent.com/assets/5608624/14215092/23e45806-f841-11e5-97f6-13a0ced433dc.png)

**Comment by Nxt3** [comment]
Have you by chance altered your DPI?

**Comment by angrybacon** [comment]
@Nxt3 Here is the unaltered 480 DPI. 

![screenshot_2016-04-01-19-55-28](https://cloud.githubusercontent.com/assets/5608624/14215592/35e7fd7a-f844-11e5-8a99-a7145a97fc77.png)

**Comment by Nxt3** [comment]
It's something device related. If I load it up on a 6P in the Android Studio Design view--the test looks centered perfectly. I'll investigate further.

**Comment by angrybacon** [comment]
Let me know if I can be of further help. :)

**Comment by Nxt3** [comment]
So, I actually have this same thing happen on my 6P--however, I'm running a nonstandard DPI. If it's stock DPI--it looks centered to me; this issue doesn't happen on my Pixel C. All in all, I'd say it's just a DPI thing--and the stock DPI is just weird enough on your device to have this arise.

I looked at the layout xmls for the chips, and there isn't anything wacky or off that would have it be a few pixels lower than it should. I doubt there is anything we can do about it. :( I'm sorry.

**Comment by ccrama** [comment]
The chips are all done through spannables, nothing in XML @Nxt3 . That allows us to have the appearance of having multiple views in a line but actually doing it all with one TextView.

The height of the view is the height of the font, so if your font is differing between devices, that can alter the positioning

**Comment by angrybacon** [comment]
Not fixable I guess then. Thanks for your time anyway.:) 

I'm using a One Plus One for anyone encountering the same issue.

**Comment by Nxt3** [comment]
Ah, gotcha. I figured it had to do with the chip background not centering in the view or something. Nevermind. :P
