### ISSUE TITLE
"Share image" shares empty files

### ISSUE THREAD

**Issue by abraham** [ccrama/Slide#1306]
Slide version: v5.0.3
Android version: v6.0.1

From an image lightbox select the share icon and then "share image"
![screenshot_20160402-160943](https://cloud.githubusercontent.com/assets/3341/14229067/c296b0e0-f8ee-11e5-8421-1f669b1c9ef3.png)
Select an app to share the image to
![screenshot_20160402-160955](https://cloud.githubusercontent.com/assets/3341/14229068/c76db2f8-f8ee-11e5-9a8b-2f7d683740cd.png)
App fails to recieve a valid image
![screenshot_20160402-161020](https://cloud.githubusercontent.com/assets/3341/14229070/cbcde9da-f8ee-11e5-9035-93225427bdfc.png)

**Comment by ccrama** [comment]
Fixed!
