### ISSUE TITLE
Main thread issues

### ISSUE THREAD

**Issue by jonasborggren** [ccrama/Slide#1309]
Slide version: 5.0.3
Android version: 6.0.1

When scrolling and the next page is loading the UI is stuttering a lot which indicates that the response to item object operations are happening on the main/ui thread. Consider using any type of background thread handling for this. Everything up to adding items to the adapter and notifying it can be handled in another thread. 

Tip: Using AsyncTask is easy and would be a decent solution for this.

**Comment by ccrama** [comment]
That actually all happens on an async task, and you cannot initialize RecyclerView holders from a background thread (notifyDataSetInserted needs to run on the main thread). The lag is actually caused by re-positioning the top bar at the same time as swiping

**Comment by ccrama** [comment]
Moved some more stuff back into doInBackground, not much else I can do though
