### ISSUE TITLE
Collapsed comment uncollapses itself but not its children after scrolling away

### ISSUE THREAD

**Issue by whitfieldc** [ccrama/Slide#1311]
Slide version: 5.0.3
Android version: 5.1.1

When I tap on a comment to collapse it, its content and all its children collapse as expected. Only the parent comment's username is visible.

However, when I scroll away from the comment and then return to it, the full text of the parent comment is visible again.The children are still hidden. Tapping the comment again returns it to a completely uncollapsed state, with child comments visible

**Comment by ccrama** [comment]
Has already been fixed for the next release, thanks for the report!
