### ISSUE TITLE
Random crash reproducible with certain posts

### ISSUE THREAD

**Issue by gferon** [ccrama/Slide#1312]
Slide version: 5.0.3
Android version: 6.0.1

Slide crashes when scrolling on any subreddit, especially when going fast, but also sometimes on a specific post. It basically renders the app unusable for me. I don't know if this might be device specific as it mentions a limitation of my phone's model GPU (OnePlus One).

Here is a logcat extract I could get from the issue, I can get more info if needed.

`04-04 23:36:45.543 14442 14442 E libEGL  : call to OpenGL ES API with no current context (logged once per thread)
04-04 23:36:46.284   776 30711 D NetlinkSocketObserver: NeighborEvent{elapsedMs=135993636, fe80::5e49:79ff:fedd:ae70, [5C4979DDAE70], RTM_NEWNEIGH, NUD_STALE}
04-04 23:36:47.666 14442 14483 W OpenGLRenderer: Layer exceeds max. dimensions supported by the GPU (1032x5687, max=4096x4096)
04-04 23:36:47.666 14442 14483 D OpenGLRenderer: Current memory usage / total memory usage (bytes):
04-04 23:36:47.666 14442 14483 D OpenGLRenderer:   TextureCache         10867572 / 75497472
04-04 23:36:47.666 14442 14483 D OpenGLRenderer:   LayerCache           28966912 / 50331648 (numLayers = 6)
04-04 23:36:47.666 14442 14483 D OpenGLRenderer:     Layer size 1088x1216; isTextureLayer()=0; texid=37 fbo=9; refs=2
04-04 23:36:47.666 14442 14483 D OpenGLRenderer:     Layer size 1088x2112; isTextureLayer()=0; texid=39 fbo=0; refs=1
04-04 23:36:47.666 14442 14483 D OpenGLRenderer:     Layer size 1088x1408; isTextureLayer()=0; texid=44 fbo=10; refs=1
04-04 23:36:47.666 14442 14483 D OpenGLRenderer:     Layer size 1088x704; isTextureLayer()=0; texid=27 fbo=0; refs=1
04-04 23:36:47.666 14442 14483 D OpenGLRenderer:     Layer size 1088x384; isTextureLayer()=0; texid=17 fbo=0; refs=1
04-04 23:36:47.666 14442 14483 D OpenGLRenderer:     Layer size 1088x1088; isTextureLayer()=0; texid=23 fbo=0; refs=1
04-04 23:36:47.666 14442 14483 D OpenGLRenderer:     Layer size 1088x704; isTextureLayer()=0; texid=31 fbo=0; refs=1
04-04 23:36:47.666 14442 14483 D OpenGLRenderer:     Layer size 1088x1664; isTextureLayer()=0; texid=12 fbo=0; refs=1
04-04 23:36:47.666 14442 14483 D OpenGLRenderer:   Layers total   40386560 (numLayers = 8)
04-04 23:36:47.666 14442 14483 D OpenGLRenderer:   RenderBufferCache           0 /  8388608
04-04 23:36:47.666 14442 14483 D OpenGLRenderer:   GradientCache               0 /  1048576
04-04 23:36:47.666 14442 14483 D OpenGLRenderer:   PathCache                3700 / 33554432
04-04 23:36:47.666 14442 14483 D OpenGLRenderer:   TessellationCache       14880 /  1048576
04-04 23:36:47.666 14442 14483 D OpenGLRenderer:   TextDropShadowCache         0 /  6291456
04-04 23:36:47.666 14442 14483 D OpenGLRenderer:   PatchCache                  0 /   131072
04-04 23:36:47.666 14442 14483 D OpenGLRenderer:   FontRenderer 0 A8 
04-04 23:36:47.675 14442 14442 D AndroidRuntime: Shutting down VM
04-04 23:36:47.694 14442 14442 E AndroidRuntime: FATAL EXCEPTION: main
04-04 23:36:47.694 14442 14442 E AndroidRuntime: Process: me.ccrama.redditslide, PID: 14442
04-04 23:36:47.694 14442 14442 E AndroidRuntime: Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
04-04 23:36:47.694 14442 14442 E AndroidRuntime: java.lang.IllegalStateException: Unable to create layer for CardView
04-04 23:36:47.694 14442 14442 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
04-04 23:36:47.694 14442 14442 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:323)
04-04 23:36:47.694 14442 14442 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:135)
04-04 23:36:47.694 14442 14442 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
04-04 23:36:47.694 14442 14442 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-04 23:36:47.694 14442 14442 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-04 23:36:47.694 14442 14442 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-04 23:36:47.696   776  3665 W ActivityManager:   Force finishing activity me.ccrama.redditslide/.Activities.MainActivity
`

**Comment by ccrama** [comment]
Has already been fixed for the next update coming out tonight. Was because some images were too tall for Android to render.

 Thank you for the report!

**Comment by gferon** [comment]
Nice! Sorry for the double report then, will update ASAP.
