### ISSUE TITLE
Comment sort selection not being respected when opening full thread

### ISSUE THREAD

**Issue by YusefOuda** [ccrama/Slide#1313]
Slide version: 5.0.3
Android version: 6.0.1
Device: Nexus 6

Repro steps:

1. Make a comment in any post, any subreddit
2. Select a comment sort different than the default (I chose to sort comments by New)
3. Select your profile, go to Overview, then click on the comment.
4. Click Load Full Thread
5. Comments are sorted by default value, but "New" will still show up as selected in the menu

**Comment by ccrama** [comment]
The menu selection doesn't save across states, it is only for that once instance of the comment view. This is expected behavior (unless I'm misunderstanding you)

**Comment by YusefOuda** [comment]
https://vid.me/uLkM.
Here is a quick video outlining the issue. Notice how all posts will open with the New sort, except if I do the Load Full Thread flow. I have to open up the menu and select New again for it to be sorted correctly

**Comment by ccrama** [comment]
Ah gothca. I made it an option in Settings > General now to set the default sorting
