### ISSUE TITLE
Multi-column has three different margin sizes

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#1317]
Slide version: 5.0.4
Android version: 6.0.1

https://i.imgur.com/dDWtf4M.png

Also present in landscape.

**Comment by Nxt3** [comment]
I'm certain that this is intended. Google Plus does the same thing.

**Comment by ccrama** [comment]
It's actually a bug, the card views all have 4dp padding but together, they have 8 between them

**Comment by Nxt3** [comment]
Even on a tablet? On my Pixel C, it looks fine.
