### ISSUE TITLE
Upvote and downvote animation are really choppy

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#1318]
Slide version: Latest alpha
Android version: Marshmallow 6.0.1
Phone: Moto G 2015

The title.

**Comment by ccrama** [comment]
Already fixed!

**Comment by alexsmithfanning** [comment]
Oops! Sorry about that. I'm in a little bit of a hurry but wanted to report it before I forgot.

**Comment by ccrama** [comment]
No worries, always feel free to report!

**Comment by ccrama** [comment]
Whoops

**Comment by alexsmithfanning** [comment]
At least I'm not alone in messing it up this time :D
