### ISSUE TITLE
Shadowbox : 2nd next image opens in internal browser after swiping to next image

### ISSUE THREAD

**Issue by Pastignon** [ccrama/Slide#1320]
Slide version: 5.0.4
Android version: 6.0.1

Sometimes sliding to the next image in shadowbox opens the second next image in the internal browser a brief moment later. User then has to slide back to return the the desired "next image".
!
[Gif of the problem](https://cloud.githubusercontent.com/assets/18305688/14314458/8b6c1586-fbf7-11e5-9503-85b698ae4e8a.gif)

**Comment by ccrama** [comment]
Fixed, thanks!
