### ISSUE TITLE
Shadowbox : weird behaviour after resuming shadowbox in the middle of a list

### ISSUE THREAD

**Issue by Pastignon** [ccrama/Slide#1321]
Slide version: 5.0.4
Android version: 6.0.1

Resuming shadowbox in the middle of a list makes Slide act weirdly. Typically, Slide will open the desired image, then swiping to the next (or previous) image will not complete, then Slide will forcefuly reset to an earlier post, then open random posts.

Acts consistently this way after resuming shadowbox in the middle of a list more than once.

[The bug in action](https://cloud.githubusercontent.com/assets/18305688/14314604/7e9caf40-fbf8-11e5-8b90-7f1f6e95745d.gif)

Breakdown of the example :

→ Slide opens the post in the middle of the list (Valley in Greece)
→ Slide is unable to swipe to the next image
→ Slide force resets on an earlier post (the Advice Mallard)
→ Slide acts super weirdly
→ Slide opens a random post (Pokemon diapers)

**Comment by ccrama** [comment]
Fixed, thanks
