### ISSUE TITLE
Shadowbox crashes when starting on image posts

### ISSUE THREAD

**Issue by Pastignon** [ccrama/Slide#1322]
Slide version: 5.0.4 Alpha 3
Android version: 6.0.1

Shadowbox instantly crashes, 100% of the time when opening shadowbox on image posts.
[Gif](https://cloud.githubusercontent.com/assets/18305688/14346115/faaf9ee0-fcb0-11e5-933f-fc9fad3bf7a8.gif)

Shadowbox doesn't crash when started on selftext posts.
[Gif](https://cloud.githubusercontent.com/assets/18305688/14346124/056123b8-fcb1-11e5-81fd-594d6fd89a12.gif)

*Note : the crash example is showing shadowbox inside multireddits. However, Slides crashes on standard subreddits all the same.

**Comment by ccrama** [comment]
Cannot reproduce. Did you report the crash?

**Comment by Pastignon** [comment]
Done now !

**Comment by Alexendoo** [comment]
Likely related to #1320

**Comment by ccrama** [comment]
Has been fixed, thanks. Actually wasn't related @Alexendoo
