### ISSUE TITLE
Don't show a 1 on submissions that have been gilded once

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#1327]

**Comment by ccrama** [comment]
I think it's better to show that as it might be confusing to users who don't know that no "1" means it was only gilded once.

**Comment by The0x539** [comment]
Reddit dot com disagrees...?

**Comment by The0x539** [comment]
![](http://i.imgur.com/McPOKLQ.jpg)

Sure about this?

**Comment by The0x539** [comment]
Why close it?

**Comment by ccrama** [comment]
Cause it's fixed now
