### ISSUE TITLE
Image download/share button blend in with white on images

### ISSUE THREAD

**Issue by zachhile** [ccrama/Slide#1328]
Slide version: 5.0.4-17-8221590
Android version: 6.0 on X1575

The download / options buttons on imgur viewer blend in with images that contain white backgrounds. Maybe some shading or outlines for those?

[Example](http://i.imgur.com/l7AhCaV.jpg)

**Comment by ccrama** [comment]
Now it's an off gray, which shows up on both light and dark

**Comment by zachhile** [comment]
My mood 😎

**Comment by zachhile** [comment]
*dood
