### ISSUE TITLE
Suboptimal network request order

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1329]
Slide version: 5.1.0
Android version: 5.1.1

The majority of these should be able to be deferred until well after the page has loaded, the duplicate `/api/v1/me` requests might be a JRAW limitation but it seems strange it's required to be sent four times within such a small amount of time. 

```ruby
   POST /api/v1/access_token                # JRAW bug
     ← 401 application/json 14B 159ms
   POST /api/v1/access_token
     ← 200 application/json 209B 185ms
   GET /api/v1/me
     ← 200 application/json 253B 151ms
   GET /api/v1/me
     ← 200 application/json 253B 164ms
   GET /subreddits/mine/moderator?limit=100
     ← 200 application/json 1.08kB 192ms
   GET /prefs/friends?limit=100
     ← 200 application/json 274B 173ms
   GET /api/multi/mine?expand_srs=true
     ← 200 application/json 586B 203ms
   GET /r/slideforreddit/hot?limit=2
     ← 200 application/json 1.66kB 258ms
   GET /api/v1/me
     ← 200 application/json 253B 395ms
   GET /api/v1/me
     ← 200 application/json 253B 162ms
>> GET /hot?limit=50                        # Request that allows page load
     ← 200 application/json 36.3kB 1.26s
```

**Comment by ccrama** [comment]
Turns out I swapped the logic in authenticating, and told it to double auth starting up and to never auth after that if it expires. Will fix asap!

**Comment by ccrama** [comment]
Just did a lot of work on that with my last few commits, look better now?

**Comment by Alexendoo** [comment]
Looks to the same to me on e8f9d020e21cab6db0bb42d748507dde7a2c92e9

**Comment by Alexendoo** [comment]
Major stuff is out of the way, remaining are probably mainly JRAW things
- [ ] Double auth
- [ ] Bearer token isn't currently cached for logged out users
- [ ] Still a render blocking /me request
- [ ] Said /me request still triggers when logged out, it shouldn't
- [ ] It also tries to grab friends when logged out, this isn't blocking so not too much of an issue, but it does cause a redirect 

Pretty great progress much smoother when logged in now, not nearly as noticeable, however it seems that the failed /me request sometimes takes a long time to receive when not logged in, this might give a user a bad first impression so I'll tag medium for now

**Comment by l3d00m** [comment]
JRAW does a /me call as well [here](https://github.com/thatJavaNerd/JRAW/blob/master/src/main/java/net/dean/jraw/RedditClient.java#L109). That line gets called in our project [here](https://github.com/ccrama/Slide/blob/master/app/src/main/java/me/ccrama/redditslide/Authentication.java#L118)  and [here](https://github.com/ccrama/Slide/blob/master/app/src/main/java/me/ccrama/redditslide/Authentication.java#L220). Means it get first called be JRAW and after that by us. Means we could reduce another request here too.

**Comment by Alexendoo** [comment]
It appears that navigating between subreddits has a fair amount more requests than it should. This is navigating **from** /r/answers **to** /r/youshouldknow. The submissions were already loaded earlier so the first four requests shouldn't exist.

Currently 12 seemingly blocking requests when there should ideally be 1 (the submission data itself) with the single flairselector and about requests deferred to the background
```ruby
# <unused>
GET https://oauth.reddit.com/r/answers/hot?obey_over18=true&limit=25
     ← 200 application/json 7.19kB 357ms
POST https://oauth.reddit.com/r/answers/api/flairselector
     ← 200 application/json 107B 159ms
POST https://oauth.reddit.com/r/answers/api/flairselector
     ← 200 application/json 107B 193ms
POST https://oauth.reddit.com/r/answers/api/flairselector
     ← 200 application/json 107B 169ms
# </unused>
POST https://oauth.reddit.com/r/youshouldknow/api/flairselector
     ← 200 application/json 107B 224ms
POST https://oauth.reddit.com/r/youshouldknow/api/flairselector
     ← 200 application/json 107B 166ms
POST https://oauth.reddit.com/r/youshouldknow/api/flairselector
     ← 200 application/json 107B 173ms
GET https://oauth.reddit.com/r/youshouldknow/hot?obey_over18=true&limit=25
     ← 200 application/json 15.21kB 478ms
GET https://oauth.reddit.com/r/youshouldknow/about
     ← 200 application/json 2.34kB 236ms
POST https://oauth.reddit.com/r/youshouldknow/api/flairselector
     ← 200 application/json 107B 176ms
POST https://oauth.reddit.com/r/youshouldknow/api/flairselector
     ← 200 application/json 107B 170ms
POST https://oauth.reddit.com/r/youshouldknow/api/flairselector
     ← 200 application/json 107B 166ms
# Submissions begin to load
```

**Comment by ccrama** [comment]
Should all be fixed now! Can you confirm?

**Comment by ccrama** [comment]
Did some testing and all seems good. Feel free to re-open if another issue comes up
