### ISSUE TITLE
Vertical scrolling is a struggle because of a "Swipe away"

### ISSUE THREAD

**Issue by benjamindean** [ccrama/Slide#1335]
Slide version: 5.1.1
Android version: 6.0.1

For example, vertical scrolling in Settings activity feels almost impossible because of horizontal scrolling which takes you back all the time. The same goes for vertically aligned albums. I remember there was a "Swipe away" option some time ago. Is it turned on by default now?

**Comment by Alexendoo** [comment]
Related #1283

**Comment by The0x539** [comment]
Arguably a duplicate of #957...?

**Comment by benjamindean** [comment]
@The0x539 Yep, but this one was closed 12 days ago. Looks like it was fixed for some of the views, but not all of them.

**Comment by ccrama** [comment]
Done now!
