### ISSUE TITLE
Allow viewing NSFW subreddits despite logged in status/user preference

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1336]
Related to #576

Discovered that this is possible by our good friend undocumented API features, `https://oauth.reddit.com/r/subreddit/hot?limit=50&obey_over18=false`. This would also allow users to opt into NSFW content in any context without having an account if desired.

If a user directly visits a sub it's pretty clear they want to access that content, however it might be best to display a prompt to ask first as reddit does

![image](https://cloud.githubusercontent.com/assets/1830331/14382913/64411aae-fd89-11e5-875b-ddd517a161ee.png)

**Comment by ccrama** [comment]
Done, now the popup says "Continue" if you would like to continue
