### ISSUE TITLE
Selfposts do not have a full sized content tag

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1338]
Slide version: e8f9d020e21cab6db0bb42d748507dde7a2c92e9
Android version: 5.1.1

![image](https://cloud.githubusercontent.com/assets/1830331/14384742/8b49a264-fd94-11e5-8b0c-eae465425d89.png)

**Comment by ccrama** [comment]
Added back in

**Comment by Alexendoo** [comment]
It's there but quite right currently - one line and no bottom padding, can set the domain as self.announcement for example like reddit does so it displays fully

![image](https://cloud.githubusercontent.com/assets/1830331/14407157/c632d094-feb6-11e5-9a0b-242c93913fbe.png)

**Comment by ccrama** [comment]
Fixed
