### ISSUE TITLE
Use flat text & icon buttons for sidebar options

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1339]
Would greatly improve usability as there's currently 4 functions in a small area with unclear function.

Using the text + icons like it was a fair while ago would be a better choice IMO, as well I prefer it cosmetically, drawers should be flat I believe, the current buttons are raised elements

![image](https://cloud.githubusercontent.com/assets/1830331/14384844/3cd6a91e-fd95-11e5-93c4-0ef68d9fb3df.png)

**Comment by Nxt3** [comment]
If you long press--it tells you what each does. The text was too long to fit them all in the sidebar; I can't imagine wanting four buttons (vertically) using up all that space.

**Comment by Alexendoo** [comment]
It does, but that's not an action the majority of users will try, there's no getting around the initial "what do these mystery icons" do without adding a proper label if they're to be understood and used—users largely ignore things they don't the function of

**Comment by Nxt3** [comment]
Well, I could redo this. How would you prefer it look? Four buttons top to bottom in a column? Or what

**Comment by Alexendoo** [comment]
Just had basically how it used to be in mind:

https://cloud.githubusercontent.com/assets/6278400/11152247/1adbc8b0-89f7-11e5-9c54-5a727c982fee.png (found in an old issue)

**Comment by Nxt3** [comment]
Alrighty. I'll whip this up later. :)

**Comment by Alexendoo** [comment]
Nice work @Nxt3
