### ISSUE TITLE
"Moderation" does not show up in drawer

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#1341]
The "Moderation" does not always show up in drawer. That is caused because [this](https://github.com/ccrama/Slide/blob/master/app/src/main/java/me/ccrama/redditslide/Activities/MainActivity.java#L1317) is called before Slide finished authentication and sets the correct value ([here](https://github.com/ccrama/Slide/blob/46ac9f4a669ed826b1c25bf2218b5fe462ca49ea/app/src/main/java/me/ccrama/redditslide/Authentication.java#L223-L223)).

Slide version: v5.1.0
Android version: v5.0.1

**Comment by Alexendoo** [comment]
Related to #1329 a little, it seems like a value that could well be cached and updated in the background after a delay for the next launch, since it's not going to change very frequently if at all for the majority of users

**Comment by ccrama** [comment]
Fixed!
