### ISSUE TITLE
Edit text in SettingsExternalBrowser activity allows spaces

### ISSUE THREAD

**Issue by Soberat** [ccrama/Slide#1342]
Slide version: Latest debug
Android version: 6.0.1 April patch

This causes it to add a space after entering a dot, which makes the app think it's another link.

**Comment by Soberat** [comment]
Also happens in SettingsFilter for domains.

**Comment by Alexendoo** [comment]
What're the ramifications of this? I don't think users would expect to be able to enter a domain with a space in

**Comment by Soberat** [comment]
As I said earlier, entering a dot (well, required for a domain) will add a space, treating the second part as an another domain to filter.

**Comment by Alexendoo** [comment]
Ah, I get you, that's a keyboard specific thing but it *should* no longer do that as of 232acec4be519bf6aa85a9c7a732280aa0ae7acf
