### ISSUE TITLE
Search bar for settings

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1347]
Is it admitting defeat if your settings require a search bar? Maybe, but it'd still be pretty useful

Essentially the same as how the stock settings app has would be great.

![image](https://cloud.githubusercontent.com/assets/1830331/14400686/081767ae-fdf4-11e5-822e-6e3dd563da14.png)

**Comment by Nxt3** [comment]
I'm gonna be honest: the settings aspect of this app blows. But that's okay! I don't really think it needs a search button--i think it needs better organization. It needs headings for categorizing the settings. For example, in "Comments" it should have a heading for "Collapsing" or something, considering  there are multiple settings for collapsing. I don't know. But search for Slide settings? You guys are better than that lol. (However, I agree with you partially). I'd like to hear @ccrama thoughts before doing anything. Depending on what he says,  I'd be more than happy to implement the solution.

**Comment by ccrama** [comment]
I don't quite think we need a search bar per se, but if you have ideas for better organization I'm all for that! If you want to toy around with some swapping and reorganization, I'd be willing to check it out :)

**Comment by Nxt3** [comment]
Can do! I'll mess around with it

**Comment by Nxt3** [comment]
@Alexendoo What are your thoughts on the more organized settings? Can I close this? :P

**Comment by Alexendoo** [comment]
It's improved, certainly, but there's still a few issues including some that can't be solved. Namely there are just so many options, personally I would use a search bar if the categorisation was perfect as it's still quicker/easier than to read through a bunch.

For the organisation specifically though I'd say #846 still applies (What is General, what is other? Why are there so many behavioural options in appearance? etc) if you were interested in continuing the work on settings

**Comment by Nxt3** [comment]
I see what you mean. Yeah--this would be difficult to categorize. Hm... You have any idea where you would put stuff? I get the "appearance" settings having behavioral logic (for example, in Comments); but where would you put the other behavioral settings? It makes sense to put all settings regarding comments in a Comments section

**Comment by Nxt3** [comment]
@Alexendoo If you could give me a mockup or something of what you had in mind, I will implement it.

**Comment by Alexendoo** [comment]
Closed by #2733
