### ISSUE TITLE
Various submission/comment actions have no touch effects

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#135]
For a post the author and view subreddit buttons are at fault (/u/... and /r/...) but the save, gild & share work fine. Whereas with comment viewing the user still doesn't work, and neither does share. But gild still functions.

**Comment by ccrama** [comment]
Those buttons are the touch targets, not the view around it. Gotta fix that!

**Comment by Alexendoo** [comment]
Also found a few more: The share and save icons that appear under a directly viewed image

**Comment by ccrama** [comment]
Everything that has text that needs to be set (usernames, subreddits, save/unsave) will be broken

**Comment by ccrama** [comment]
Done eceb88c6358db444f71e53834b92d527c09a363b
