### ISSUE TITLE
Unable to unhide hidden posts

### ISSUE THREAD

**Issue by matty1086** [ccrama/Slide#1351]
Slide version: 5.1.2
Android version: N Preview - Nexus 6P

I'm unable to unhide posts that have been hidden on my account. Repro steps as follows:

Go into user account --> Hidden
Long press or tap menu on a hidden post
Menu comes up with "Hide Post". This should say unhide if the post is already hidden
Tapping "Hide Post" removes said post from the list making me think it's been unhidden.
Refresh hidden list and same post reappears at top of the list.

**Comment by ccrama** [comment]
Fixed, thanks!
