### ISSUE TITLE
reddituploads.com images open in app and browser

### ISSUE THREAD

**Issue by matty1086** [ccrama/Slide#1352]
Slide version: 5.1.2
Android version: N Preview - Nexus 6P

I believe this is the new domain that reddit has with their app for image uploads, but images that are hosted on i.reddituploads.com open in both the in app viewer as well as the browser.
I have my browser set to use the internal browser.

Example post:
https://www.reddit.com/r/softwaregore/comments/4e1hvk/i_had_a_feeling_google_play_services_was_draining/

Tap the image
The image opens in the in app viewer as expected
The image also attempts to open in the internal browser, however the page is returned as "unauthorized"

**Comment by ccrama** [comment]
Has been fixed for the next alpha, thanks!
