### ISSUE TITLE
Changelog buttons shouldn't scroll with the changelog itself

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1353]
Currently they're on the same level as the changelog, meaning you can't press OK straight away if you aren't interested, and that the scrollbar intersects the button which looks a little strange.

![image](https://cloud.githubusercontent.com/assets/1830331/14406491/dbfc44a2-fea0-11e5-94e1-40588049cd49.png)

**Comment by ccrama** [comment]
Done!
