### ISSUE TITLE
Use "view day", "view array", and "view module" icons for album view mode buttons

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#1355]
I remember seeing one or two people confused about "the shadowbox button being in the album view", and using the first two would arguably be a bit more consistent within albums. I also feel like the "grid" icon is more suited for representing a grid of cells, like in a spreadsheet, as opposed to a grid of things separated by spacing.

**Comment by Alexendoo** [comment]
![ic_view_day_black_48dp_2x](https://cloud.githubusercontent.com/assets/1830331/14407284/62b228b8-feba-11e5-9dd6-7eaffd135990.png) ![ic_view_array_black_48dp_2x](https://cloud.githubusercontent.com/assets/1830331/14407286/6cf3ca02-feba-11e5-8334-3c5d083887a8.png) ![ic_view_module_black_48dp_2x](https://cloud.githubusercontent.com/assets/1830331/14407288/760c8624-feba-11e5-8587-2c9adca8f99c.png)

**Comment by ccrama** [comment]
Done
