### ISSUE TITLE
Shadowbox starts playing audio of next post 

### ISSUE THREAD

**Issue by goodpricefriedrice** [ccrama/Slide#1363]
Video showing the problem (turn the sound up, sorry old phone doesnt have the best camera): https://onedrive.live.com/redir?resid=ED3E99BC7F8F45FF!657811&authkey=!ADCkhMeNdqSV_og&ithint=video%2cmp4

Not sure if it only affects streamable or others as well. A pause button in shadowbox would be nice too if possible. 

Slide version: 5.1.3
Android version: 6.0.1

**Comment by ccrama** [comment]
Fixed, now it plays when you go to it and pauses when you leave it!

**Comment by goodpricefriedrice** [comment]
Awesome! :D Thanks!
