### ISSUE TITLE
Disable (grey out) items in the settings that aren't available

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1369]
Only a couple left I could find:

- [ ] Reddit preferences itself, the category disappears when logged out
- [ ] **Reddit prefs → Hide all NSFW photos:** This is force enabled when "I am over 18..." is disabled, it can only be disabled again when you re-enable over18
- [ ] **General → Notifications:** disappears when logged out

**Comment by Nxt3** [comment]
Are you saying you want the settings for Notifications to be grayed out as opposed to it disappearing when a user is logged out?

**Comment by l3d00m** [comment]
correct @Nxt3

**Comment by Nxt3** [comment]
I can do zat

**Comment by l3d00m** [comment]
zat would be great :+1:
