### ISSUE TITLE
Prompt the user if their reddit preferences interfere with thumbnails/previews

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1370]
Snackbar or something similar, could do it on start for users with compressed link display/set to fully disabled, and possibly if they visit a subreddit that has media disabled it could also prompt if they're on default?

Latter not so important but the former but overall it'd be quite useful for some, as reddit disabling thumbnails in apps because of your web preferences is just bizarre

**Comment by ccrama** [comment]
Turns out a lot of users do this on purpose (blocks out spoilers or other special sub-related things), so instead of having a popup with it telling the user they should change it, there is some text at the top of the Reddit prefs page which explains what the thumbnail settings do
