### ISSUE TITLE
Different icon for Debug builds

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1372]
I took the current icon and tinted it "blueish/purple"; I couldn't figure out how to edit gradle to allow for a different icon per build type.

Maybe someone else could figure it out. :P

[Icons for each screen size are here](https://www.dropbox.com/sh/k7lrha62jblbtj7/AADdWhpxSsxwndZKb-LUL_OMa?dl=0)

**Comment by The0x539** [comment]
But icon recoloring is coming eventually...

**Comment by Nxt3** [comment]
It is?

**Comment by The0x539** [comment]
At least that's what @ccrama had me thinking a fair while ago.

**Comment by Nxt3** [comment]
¯\_(ツ)_/¯

**Comment by The0x539** [comment]
People with more authority can correct me if I'm wrong, but as such I don't think this is happening.

**Comment by Nxt3** [comment]
Booooooooo. I actually think I know how to do it now. Not going to waste my time if @ccrama says tinting is coming.

**Comment by Alexendoo** [comment]
It's very easy to do as a build step, adding tinting after the fact is not easy to do. If tinting did get added it's trivial to undo also (it actually wouldn't even matter, it just would change the default colour). You are missing the 512×512 image though from res/drawable

**Comment by Nxt3** [comment]
@Alexendoo you wanna take a stab at it? I tried making a /debug/res/ folder and changing the sources for debug builds but I couldn't quite figure it out. :\ I'll add the 512x512 in a bit

**Comment by Nxt3** [comment]
Since icon tinting is supposed to happen at some point, I'm just going to close this.

**Comment by Alexendoo** [comment]
I'm not sure on the progress of that and it seems kinds bloaty to me, but I'd be happy to add this if you get that 512 one uploaded somewhere since it's purely a build step. No overhead anywhere else

**Comment by Nxt3** [comment]
It was uploaded :P

**Comment by Alexendoo** [comment]
Ah never re-checked, will look into it momentarily
