### ISSUE TITLE
Unsupported markdown in post/comment previews

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1373]
Currently unsupported that I could find:

- [ ] Superscript
- [ ] Strikethrough
- [ ] Tables

**Comment by ccrama** [comment]
None of those are really possible for me to do, unless we heavily modify the library I'm  using to parse it

**Comment by ccrama** [comment]
Moved to a new library, should fix these now!

**Comment by okungnyo** [comment]
Wow, what new library?

**Comment by ccrama** [comment]
[Commonmark](https://github.com/atlassian/commonmark-java)
