### ISSUE TITLE
Play Store links open in browser

### ISSUE THREAD

**Issue by LordManhattan** [ccrama/Slide#1375]
Slide version: 5.1.3
Android version: 6.0.1
Device: Galaxy S7 Edge

So I've noticed some very annoying behavior on my new S7 Edge. Whenever I hit a post that links to the Play Store, or a comment with a Play Store link, it'll open a Chrome Custom Tab instead of the Play Store, and then open the Play Store link in that tab. If I then hit "open in browser", it'll open the link in the browser. 

The only "solution" is to set the app to open links externally in the browser. That'll kick it into the Play Store directly without any trouble. The issue with that is that every other non-image/video link also opens externally now, which isn't a what I really want.

**Comment by Chromelon** [comment]
Intended behavior. Go into force external browser and enter play.google.co

**Comment by LordManhattan** [comment]
Yup, that does indeed solve the issue. Case closed, lock it down boys!
