### ISSUE TITLE
Option to load imgur albums in internal browser

### ISSUE THREAD

**Issue by TheZoq2** [ccrama/Slide#1378]
Slide version: 5.1.3
Android version: 5.1.1

In the app options, there is a setting to use the internal image view for albums which doesnt support things like image descriptions. Disabling the internal view causes the images to opne in an external browser but I would prefer it to load the album on the imgur site inside the internal browser.

**Comment by The0x539** [comment]
What do you mean it doesn't support image descriptions?

**Comment by TheZoq2** [comment]
It seems like I didn't look propperly before reporting this issue. I tested a few albums just now and it looks like it takes me to the imgur page itself. 

What I was talking about is that sometimes when I clicked on an album before, it would give me an interface where only the images were shown and you could slide between them. But i never saw any descriptions in that mode.

**Comment by ccrama** [comment]
Tap the T button, that shows the title and description. And there is already an option in Settings > Link Handling

**Comment by ccrama** [comment]
Done, now in overflow menu
