### ISSUE TITLE
Long Press Post Presents Edit Button

### ISSUE THREAD

**Issue by ainen** [ccrama/Slide#1379]
Slide version: 5.1.4
Android version: 6.0.1

When "Long press for actionbar" is set for the Actionbar mode, long pressing a post while in the comment view changes the Actionbar to an edit button that can be tapped but does nothing. While testing in other modes, normal behavior seems to be bringing up the bottom sheet.

![screenshot_20160411-103512](https://cloud.githubusercontent.com/assets/1300058/14430907/4e140cce-ffd1-11e5-8a2f-2321affc3e24.png)
![screenshot_20160411-103517](https://cloud.githubusercontent.com/assets/1300058/14430910/5002eb7c-ffd1-11e5-9b8e-4e12766b0c8a.png)

**Comment by ccrama** [comment]
Fixed, good find! Thanks
