### ISSUE TITLE
Changing base theme from 'AMOLED with contrast' to any other theme also changes accent color to blue

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1381]
Slide version: 5.1.4
Android version: 6.0.1

**Comment by ccrama** [comment]
What page are you changing it from?

**Comment by Controless** [comment]
Sorry, I don't understand what you're asking. The accent bar actually changes to blue if you change the theme from 'AMOLED with contrast' to any other theme.

**Comment by ccrama** [comment]
Did you change it in Settings > Theme, the tutorial, 3 dot menu > theme color, or single subreddit > 3 dot menu > theme color

**Comment by Controless** [comment]
Ah, Settings > Main theme

**Comment by Alexendoo** [comment]
Seems switching to light chooses grey, too

**Comment by ccrama** [comment]
Whoops

**Comment by ccrama** [comment]
Fixed now
