### ISSUE TITLE
Option to change selftext font

### ISSUE THREAD

**Issue by matthieugrieger** [ccrama/Slide#1382]
Slide version: 5.1.4
Android version: 6.0

I noticed a minor inconsistency in the font settings. It is possible to change the font style/size for post titles and comments, but it is not possible to change it for selftext. For example, if both the post title and comment fonts are changed to Roboto Slab, the selftext looks out of place. Maybe the selftext could inherit the font settings from comments?

**Comment by ccrama** [comment]
The selftext is the same font and font size as comments are

**Comment by matthieugrieger** [comment]
Yes, I am.

Screenshot:
https://i.imgur.com/43Qi8Iz.png

I changed the comment font to Roboto Slab, and the font for the selftext was not updated. I closed the app and restarted it.

**Comment by ccrama** [comment]
That's actually a bug, good find! Has been fixed

**Comment by matthieugrieger** [comment]
Awesome, thanks!
