### ISSUE TITLE
Better Offline Support

### ISSUE THREAD

**Issue by KonradIT** [ccrama/Slide#1386]
Slide version: 5.1.4
Android version: Android N

>I like how the app 'Reddit offline' does it, it puts a symbol next to each post meaning it cached the self text and the comments, but does not cache imgur images. Also the app does not seem to do it automatically. Do you thing it would be possible to have a full offline mode and maybe even a automated mode where for instance at 5AM if there is WiFi downloads 50 posts of /r/askreddit

>>Caching comments is the only way to do it, but it gets overwritten if you reload the subreddit at a later time (you can only have one session of a subreddit saved at a time).
>>>Reddit offline has this useful panel where you can manage what's offline and what's not synced, the vertical lines represent a post each, my limit is 20 posts per sub, the ones in white are synced but not read like ask Reddit, which only has 1 grey which means only 1 post is read. All other sub's are not cached expect for TIFU, which I haven't read anything. You can re download using the download Button and delete the sub reddit content specifically. That would be great for slide. And of course backing up the sub from the 3dot menu. *You mentioned that every refresh of the sub deletes the content, perhaps you could add an if that checks if there are new post and mark the new posts as NOT BACKED UP and the posts which are already backed up with an arrow icon or something.*
[screenshot](http://i.imgur.com/QOVSWR3.png)

Conversation pulled from reddit messages

**Comment by ccrama** [comment]
Done with my new_offline_model branch (coming soon to the app!)
