### ISSUE TITLE
Issue when reopening the app and very quickly clicking Multireddits/Moderation in the sidebar

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1388]
Slide version: 5.1.5
Android version: 6.0.1

When reopening the app and very quickly clicking Multireddits in the sidebar, it brings up this dialog: http://i.imgur.com/qbRkMik.jpg (even if you already have some Multireddits). Pretty minor issue, but I ran into it and I'm sure others will too as well.

Similarly, quickly clicking Moderation after reopening the app only shows the Mod Mail Unread and Mod Mail, the rest are missing (and Slide crashes a few seconds later).

**Comment by l3d00m** [comment]
This is because multireddits and moderated subreddits are loaded after the other content is loaded (up to 5 seconds after start). This could be fixed by storing moderated subs and multireddits into storage. I'll look into the latter.

**Comment by Alexendoo** [comment]
@l3d00m sounds good to me, I've noticed you can't do moderator actions when clicking a link outside the app to a post, for example https://reddit.com/r/slideforreddit/comments/4edqd6/v515_pushed_to_alpha_rc/

That would catch that issue too

**Comment by ccrama** [comment]
Now it will only allow a click after multis have been synced
