### ISSUE TITLE
Weird space above the content in the Moderation pages when scrolling down to hide action bar, and then swiping right/left [video] + other Moderation issues

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1389]
Slide version: 5.1.5
Android version: 6.0.1

- [x] Here's the video: https://streamable.com/9kxe

It works fine with Multireddits and should work the same for Moderation as well.

- [x]  Also, this should be changed as well to match the others: http://imgur.com/a/hSIpU
- [x] Modqueue should come before /r/mod Unmoderated because it is way more important and moderators view that page more often that Unmoderated.
- [x] Remove the '/r/mod' before Unmoderated. It's redundant and wastes space (it shows as Unmoderated on the reddit sidebar as well, not /r/mod Unmoderated).

**Comment by ccrama** [comment]
All fixed, thanks!

**Comment by Controless** [comment]
Amazing! Thank you.
