### ISSUE TITLE
Comment links open in external browser instead of inline browser

### ISSUE THREAD

**Issue by KaliK0t** [ccrama/Slide#139]
Welp

**Comment by Alexendoo** [comment]
Which links exactly? Links in comments open fine for me

**Comment by KaliK0t** [comment]
Twitter is one. I dont quite remember the rest.

**Comment by l3d00m** [comment]
Can reproduce. This is probably because twitter is the default app for opening www.twitter.com links.

**Comment by ccrama** [comment]
Yep. Chrome customtabs will open an app if you have it set to instead of with the browser.
