### ISSUE TITLE
If you downvote a post with 0 points, it displays -1. It should still display 0.

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1392]
Slide version: 5.1.5
Android version: 6.0.1

I tested it out multiple times, I think this is a bug.

**Comment by Nxt3** [comment]
Why? This isn't actually a bug--as it's coded in there to display -1 :P

Why shouldn't it be -1 though? I can fix it

**Comment by Controless** [comment]
Oh. Well, on reddit the minimum score for a post is 0. There are no negatives, so -1 makes no sense at all. It should still stay at 0, like how the desktop reddit and other reddit apps implement this.

**Comment by Nxt3** [comment]
Give me a few and I'll have this patched up

**Comment by Controless** [comment]
Cool, thanks! :)
