### ISSUE TITLE
Editing buttons should have less size and more contrast

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#1396]
...I think? Feels like it, especially on a dark background as far as the contrast goes.

**Comment by Nxt3** [comment]
I think it's fine. It wouldn't be hard to make them smaller though.

**Comment by ccrama** [comment]
Smaller also means harder to click, though

**Comment by The0x539** [comment]
Yeah, sure. The contrast ought to change, though. It's a bit weird.

**Comment by Nxt3** [comment]
What's wrong with the contrast? I'm looking at it now with the black theme and everything is perfectly visible.

**Comment by The0x539** [comment]
Not the black base theme, but rather dark main colors when replying to a comment.

**Comment by Nxt3** [comment]
Could you send me a screenshot? Maybe I'm seeing this wrong--but I have absolutely no issue with contrast :P

**Comment by The0x539** [comment]
![](https://i.imgur.com/9tGT8Gg.png)

**Comment by Nxt3** [comment]
Ah--I don't use brown anywhere lol. That would be why. I'll see what I can do for this. If you were using the "dark" base theme then this wouldn't be an issue--its the combination of a dark subreddit theme and a light app theme. The tint is probably based on the base theme--where it needs to be based on the subreddit theme (I think)

**Comment by The0x539** [comment]
I still think it should be the solidly opaque color like everything else
near it. And why should the base theme affect the color of buttons not on a
background color?

**Comment by Alexendoo** [comment]
Could just make them white, that's the thing only we tested for compatibility with all the main colours

**Comment by The0x539** [comment]
Exactly, and either white or black for replying to posts depending on base
theme.

**Comment by Nxt3** [comment]
I was stating how its done. If it was based on the subreddit color, this wouldn't be an issue. Making them white is what I was going to do
