### ISSUE TITLE
Searching for certain phrases in "SubredditSearch" doesn't yield results

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1397]
When on the "Discover" activity, and you go to search for subreddits based on keyboard, certain phrases yield no results even though there should be.

Example:
- Search for "toomeirl" (/r/toomeirlformeirl doesn't show)
- Search for "toomeirlformeirl" doesn't yield anything either

**Comment by ccrama** [comment]
It uses the default search from Reddit, I really have no control over what it returns

https://www.reddit.com/subreddits/search?q=toomeirl returns nothing too

**Comment by Nxt3** [comment]
Searching for toomeirlformeirl" actually flashes the list and then you have a list of nothing. That's definitely a bug with something on Slide's end.

Where are the searches being processed? I couldn't find anything about where the query is handled.

**Comment by ccrama** [comment]
The SubredditListView fragment. But it's not getting any data from the Reddit API for the first search you linked me to

**Comment by Nxt3** [comment]
Yeah, I see that it isn't. If I go on desktop and do a search without the url you gave me, I can find subreddits for "toomeirl". Weird.

https://www.reddit.com/search?q=toomeirl

**Comment by ccrama** [comment]
The items on the top of that in browser are not accessible with the API, unfortunately. The only way to search for subs is /subreddits/search?q=blah

**Comment by Nxt3** [comment]
Ah, gotcha.

Well, https://www.reddit.com/subreddits/search?q=toomeirlformeirl returns results on desktop--but on Slide I get nothing.

**Comment by ccrama** [comment]
Found and fixed, it was loading even more right after the first load, and therefore was overwriting it with nothing (also why some results were so strange)
