### ISSUE TITLE
Refactor layout parameters that constrict RTL layouts

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1399]
i.e. `paddingLeft` would become `paddingStart`; `paddingRight` would become `paddingEnd`

Shouldn't be too much work thanks to AS.

**Comment by l3d00m** [comment]
I think we have to leave paddingLeft there as well for older android versions

**Comment by Nxt3** [comment]
As far as I know, RTL layouts are supported in 4.2+. Slide's min SDK is 4.2+

**Comment by l3d00m** [comment]
Yes, you're completely right. My fault

**Comment by Nxt3** [comment]
No worries. :) I'll probably do this later this week.

**Comment by Nxt3** [comment]
Fixed by #1415
