### ISSUE TITLE
Clicking on a subreddit link before the comments finished loading crashes slide

### ISSUE THREAD

**Issue by KaliK0t** [ccrama/Slide#140]
Welp

**Comment by ccrama** [comment]
What do you mean a "subreddit link"?

**Comment by ccrama** [comment]
Sorry, didnt mean to close.

**Comment by KaliK0t** [comment]
If a subreddit is linked in the OP it crashes on click before comments are
loaded

**Comment by ccrama** [comment]
Cannot reproduce

**Comment by KaliK0t** [comment]
I encountered it with the reddit CEO ama post yesterday. He linked
r/alienblue (i know...) and it crashed when i clicked

**Comment by Alexendoo** [comment]
Appears to have been #240

**Comment by Alexendoo** [comment]
Closing as the other issue has more information
