### ISSUE TITLE
Gfycat links no longer show as large thumbnails

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1401]
With the ContentType refactor, Gfycat links no longer appear as large thumbnails anywhere. Not sure if this was intended.

**Comment by ccrama** [comment]
It actually isn't because of the refactor, it's because gfycat links usually have low quality thumbnails and therefore show in a small view

**Comment by Nxt3** [comment]
Why did they show before?

**Comment by ccrama** [comment]
They didn't, I havent had one show for me

**Comment by Nxt3** [comment]
I used to have them show for me. Is this something you'd be okay with me changing? Or would you like to keep it like it is?

**Comment by ccrama** [comment]
You can change it if you'd like

**Comment by ccrama** [comment]
Now all media types are full images always
