### ISSUE TITLE
Can't open certain embedded media

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1402]
Sharevid:
https://reddit.com/r/HiTMAN/comments/4egl8n/well_that_bug_is_op/

Giphy:
https://reddit.com/r/CODZombies/comments/4eh9up/everybody_in_this_sub_right_now/

It states its Embedded, but when you click on it, a white page opens and you can't do anything but swipe back to the post.

**Comment by ccrama** [comment]
Fixed now! Thanks
