### ISSUE TITLE
Comment collapse stutter after refreshing + other weird behaviour [video]

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1403]
Slide version: 5.1.6
Android version: 6.0.1

Minor bug. This annoying stutter occurs every time you tried to replicate this. https://streamable.com/5b0c

**Comment by ccrama** [comment]
Can't reproduce

**Comment by Controless** [comment]
I just reproduced it again. You basically:

1) Open up a large thread

2) Collapse the first comment

3) Refresh

4) Collapse the first comment again

And you'll notice the stutter then.

**Comment by ccrama** [comment]
Still not doing it for me :(

**Comment by Controless** [comment]
Hmm, weird. Can anyone else try to reproduce this?

**Comment by Alexendoo** [comment]
Yeah it happens on my end, Android 5.1.1, Slide 35582365a3b1e99e620f73810479cc20e86f95af

**Comment by Controless** [comment]
ccrama, alexendoo, this issue also seems directly related to this post on google+: https://plus.google.com/115646860973681860104/posts/givFKN8WUDm

One of the same outcomes.

**Comment by ccrama** [comment]
Maybe it's related to screen size? What are you both running

**Comment by Controless** [comment]
I'm on my S6.

**Comment by Alexendoo** [comment]
Nexus 4

**Comment by ccrama** [comment]
Fixed, thanks for the report!
