### ISSUE TITLE
Unable to select/open url that starts with a capital

### ISSUE THREAD

**Issue by TheWorstNL** [ccrama/Slide#1405]
Slide version: 5.1.6 
Android version: 6.0.1 

This comment: https://reddit.com/r/gaybros/comments/4eb0e6/todays_monday_show_me_your_me_411/d1yjiqm?context=3

Pressing the url only highlights the comment and completely ignores the url.

**Comment by TheWorstNL** [comment]
And comment links are not opened by Slide?

**Comment by Alexendoo** [comment]
Which comment links are you having issues with?

And that's annoying the web _is_ case sensitive so it's technically invalid so chrome doesn't want to try and open it, will see what I can do

**Comment by TheWorstNL** [comment]
If I press the Reddit link mentioned above in Chrome on mobile Slide doesn't launch but Chrome opens the link instead.

**Comment by Alexendoo** [comment]
How did you open this page? If you're on chrome dev at least, I don't know about stable/beta, links you tap in other apps open in a custom tab by default which doesn't send an intent out to other apps when navigating pages

**Comment by TheWorstNL** [comment]
Chrome stable and a normal tab. Maybe I'm remembering wrong but I thought Reddit is Fun did open those links.

**Comment by Alexendoo** [comment]
:boom: Should be fixed with b4ef1bf4b617432b2f6031dac85b5e023f4beb4f, if you come across any place that has an issue still please let us know

Thanks!
