### ISSUE TITLE
Hard coded strings

### ISSUE THREAD

**Issue by Soberat** [ccrama/Slide#1406]
Slide version: https://github.com/ccrama/Slide/commit/0e4f78e12fe49fa08a63646cc9378597fd08cb68
Android version:6.0.1

- Profile.java
 - [x] "Redditor for x"
 - [x] "Tag user"
 - [x] "User tagged as"
 - [x] Tagging dialog - "Remove tag", "Set tag",

- InboxAdapter.java
 - [x] All the tabs: Inbox, Unread, Messages, Sent, Mentions
 - [x] Longpress options: Mark read, Mark Unread, Copy Text, Message Copied (toast), View full thread

- Discover.java
 - [x] Tabs: Popular, Trending
 - [x] Default text in search: Search term or topic
 - [x] Activity title

- SettingsGeneral.java
 - [x] "Not set yet" for saving location
 - [x] "Images will be saved to " toast

- SettingsFont.java
 - [x] Font sizes, for both comment font and title font (not types of fonts)

- Other:
 - [x] menu_subreddit_overview.xml
 - [ ] btn_sumbit probably should be swapped with editor_sumbit, otherwise it's just bare "Sumbit"

**Comment by Nxt3** [comment]
We really need to reorganize the entire `strings.xml` file.

**Comment by l3d00m** [comment]
Why do you think so @Nxt3?

**Comment by Nxt3** [comment]
Look in the strings file. Some are organized, some aren't. Just need to move stuff around, that's all. Readability

**Comment by Alexendoo** [comment]
@Soberat / @l3d00m would "Redditor for %s" where %s is a locally translatable time work, or would we need to have things like "Redditor for %1$s %2$s" where the unit of time and number can be moved around

**Comment by l3d00m** [comment]
I think the first one should be enough @Alexendoo, at least in German.

**Comment by Soberat** [comment]
@Alexendoo It's probably gonna be 1st one for most languages, so I'm with it.

**Comment by Alexendoo** [comment]
Got a few of them, what's wrong with menu_subreddit_overview.xml?

**Comment by Soberat** [comment]
It's just a little thing, I think a bare "Sumbit" is out of place in overflow menu. But you know, that's up to you ;)

**Comment by Gawdl3y** [comment]
CommentsPage.java also has hard-coded strings for the comment discard dialog.

**Comment by ccrama** [comment]
Did a lot of lint cleanup, think we can close it now :)
