### ISSUE TITLE
Reply input field doesn't use wubreddit's accent color and instead uses global accent

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#1408]
![](https://i.imgur.com/9tGT8Gg.png)

/r/grilledcheese has its accent color set to orange for me.

**Comment by ccrama** [comment]
That bar isn't even colored for me?

**Comment by The0x539** [comment]
Is your accent color the whitish gray?

**Comment by ccrama** [comment]
No, it's blue. Only the cursor is colored for me

**Comment by The0x539** [comment]
Even when selected? Odd. Base theme?

**Comment by ccrama** [comment]
Base theme is dark blue

**Comment by The0x539** [comment]
Try the others?

**Comment by ccrama** [comment]
Nope, even on light it's just the cursor. What are your view mode settings and how did you get to that post?

**Comment by The0x539** [comment]
View mode? And I go to the subreddit via navdrawer and then open the post.

**Comment by ccrama** [comment]
Like comment pane, no sub tabs, etc. Might also be a marshmallow thing

**Comment by The0x539** [comment]
Single sub. And yeah, I'm on Marshmallow. I do like it being colored, though.

**Comment by ccrama** [comment]
Huh, this is what I see (and have always seen)

![image](https://cloud.githubusercontent.com/assets/3819844/14506202/36fc1ca4-0182-11e6-80a8-bfde674f4cbd.png)

**Comment by Nxt3** [comment]
It's definitely a Marshmallow thing. I can confirm the save behavior. I'm pretty sure it's because it's using the app's accent color to color it--you don't actually define anything in the code, the EditText field just does that automatically. It should be possible to change it, though: http://stackoverflow.com/questions/26574328/changing-edittext-bottom-line-color-with-appcompat-v7

**Comment by The0x539** [comment]
If it's getting overridden, what are we overriding it to? White, black, or
wubreddit accent?

**Comment by Nxt3** [comment]
We're not overriding it. That's why it's taking the global accent color--because it changes the app's accent color. Marshmallow apparently colors it without doing anything other than using `EditText`

**Comment by The0x539** [comment]
I'm saying when this gets closed.

**Comment by ccrama** [comment]
Just updated to marshmallow a minute ago and I can reproduce now! I'll look at that link later tonight @NXT3
