### ISSUE TITLE
App crashes after clicking on the empty links in the sidebar of /r/Tagpro

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1409]
Slide version: 5.1.6
Android version: 6.0.1

Slide marks them as spoilers for some reason, but they aren't actually. They are apparently tooltips for images on that sub. From their stylesheet: "You can also add a tooltip to your image! A tooltip looks like this: `[](#default "sample tooltip")`"

The ones from /r/Tagpro:

`[](#default "Artwork by Pigoon")`
`[](#default "Artwork by pigeoni")`
`[](#default "Artwork by Pigoon")`
`[](#default "Artwork by pigeoni")`
`[](#default "Artwork by pigeoni")`
`[](#default "Artwork by pigeoni")`

**Comment by Nxt3** [comment]
I can't get it to crash--tapping on it does nothing.

**Comment by ccrama** [comment]
Has been fixed with my last few commits
