### ISSUE TITLE
App crashes when clicking long subreddit link

### ISSUE THREAD

**Issue by goodpricefriedrice** [ccrama/Slide#1411]
Clicking the link to the subreddit shown in this screenshot (http://i.imgur.com/OXvPPTW.png) causes a 'Unfortunately slide has stopped' crash

The subreddit in question: https://www.reddit.com/r/ccKufiPrFaShleWoli0

The app may be crashing because of the part after the subreddit name

/r/ccKufiPrFaShleWoli0**: ccKufiPrFaShleWoliGtMuFogenasmwt1_ThnmmeOPmamaniauThphtemualRehok_thCaUrpnThlazzpiawkydiPeBrBrHetaMr**

Slide version: 5.1.3
Android version: 6.0.1

**Comment by Nxt3** [comment]
Can't replicate this because the sub in question is private. Do other imgur links in that sub cause Slide to crash?

**Comment by goodpricefriedrice** [comment]
Oh sorry i realise my wording was poor. I dont mean clicking the imgur link causes a crash. I meant clicking the link to the subreddit IN the screenshot causes a crash.

**Comment by Nxt3** [comment]
Ohhhh. I just realized what it was you're trying to show us. :P 

www.reddit.com/r/ccKufiPrFaShleWoli0: ccKufiPrFaShleWoliGtMuFogenasmwt1_ThnmmeOPmamaniauThphtemualRehok_thCaUrpnThlazzpiawkydiPeBrBrHetaMr

crashes the app??

Wtf kina sub is that? lol

**Comment by goodpricefriedrice** [comment]
Bingo!

It's a subreddit created after reddit latest april fool gag (Robin). The name of the 'Chat' got bigger as more people joined. Largest room ended up with 5000 people and this is a subreddit for them :)

Heres a video of the issue (as its easier to show than describe): https://onedrive.live.com/redir?resid=ED3E99BC7F8F45FF!657838&authkey=!ADc5PN09DwCqHiA&ithint=video%2cmp4

**Comment by ccrama** [comment]
I think it's already been fixed, why we can't reproduce @Nxt3

**Comment by ccrama** [comment]
I don't think the link is the issue, as it opens just fine. Whatever happens after that is crashing it, but I can't reproduce because I don't have access to the sub

**Comment by goodpricefriedrice** [comment]
Very odd, ive asked the mods to add you to the sub. However this is probably a very low priority request (so totally fine if you completely ignore it)

**Comment by fimion** [comment]
Hey, I'm /u/fimion@gmail one of the admins of that subreddit. Let me help you troubleshoot this issue.

**Comment by fimion** [comment]
Okay, I have installed slide and cannot reproduce this issue. Let me check with the other mods really quick and I'll get you access.

**Comment by goodpricefriedrice** [comment]
Rebooted and reinstalled the app. Now its working fine! 

Sorry for the trouble and thanks fimion
