### ISSUE TITLE
Error when uploading photos

### ISSUE THREAD

**Issue by goodpricefriedrice** [ccrama/Slide#1412]
http://i.imgur.com/tqKT8YD.png

Tried it several times, no success. Taking a screenshot of the photo and uploading that **does** work however. 

That screenshot was from trying to add an image to a comment, this is the error from adding it as a new post: http://i.imgur.com/KOMI9iX.png

I get the same error regardless of the photo being on the SD card or on the internal memory. 

Slide version: 5.1.3
Android version: 6.0.1

**Comment by ccrama** [comment]
The image was probably too large for Imgur to upload through the API. Not much I can do to fix that, unfortunately

**Comment by Alexendoo** [comment]
Can you share the photo you were trying to upload @goodpricefriedrice?

**Comment by goodpricefriedrice** [comment]
Literally any image my camera has taken. My phone is an S7 Edge. Heres an example (I tried lots of photos, not a single one uploaded). 

Theyre not even that big. 3-4mb ish This one is 3.01mb for example: https://onedrive.live.com/redir?resid=ED3E99BC7F8F45FF!657849&authkey=!ABRL2lCwJYYjJHE&v=3&ithint=photo%2cjpg

**Comment by ccrama** [comment]
I think 2 mb is the max the api allows if I'm not mistaken

**Comment by goodpricefriedrice** [comment]
Ah that makes sense, i just tried some other reddit apps, they all failed too.  

Maybe instead of having the user wait a couple minutes as it tries to upload, then showing an error that says something about storage being accessible, implement something that quickly checks the size of the image before uploading to see if its above 2mb and then deliver an error notifying the user of that. 

Just a suggestion!

Thanks again!

**Comment by ccrama** [comment]
Now it checks the file size and gives an error if it's too large. Thank you!
