### ISSUE TITLE
Can't share image directly from i.reddituploads.com links

### ISSUE THREAD

**Issue by andrew-kennedy** [ccrama/Slide#1417]
Slide version: 5.1.6
Android version: N

If I try to share the link, works fine with images at this domain. If I try to share the image itself, nothing happens. Still works fine for both sharing options for imgur.

http://i.imgur.com/GOtKCgr.png

**Comment by andrew-kennedy** [comment]
Whoops, meant i.redditmedia.com

**Comment by ccrama** [comment]
Fixed, now it will always be the content URL

**Comment by andrew-kennedy** [comment]
aww that's too bad, sharing the image itself was a nice touch sometimes. What was the cause of the bug?

**Comment by ccrama** [comment]
No you can still share the image. Now it shares the content URL instead of the loaded url when sharing the URL @andrew-kennedy
