### ISSUE TITLE
Start shadowbox from the image you are currently watching

### ISSUE THREAD

**Issue by TheWorstNL** [ccrama/Slide#1425]
Slide version:5.1.6 
Android version:6.0.1 

If you are scrolling through a subreddit and after a while you press the shadowbox, the gallery should start at the post you are currently watching instead of the beginning.

**Comment by goodpricefriedrice** [comment]
Its sorta there are the moment. Sometimes clicking the shadowbox button takes you to the post 1 just before the one you were looking at. But sometimes takes you back to the 1st post of the sub.

**Comment by TheWorstNL** [comment]
I've never seen it work before until now. But like you say: it's pretty
random. Starting one post before it's not that big of a deal but starting
at #1. And it crashes after 50 posts but that bug is already filed.

**Comment by ccrama** [comment]
It starts at the first visible post, which may be the one above the one you're looking at.

**Comment by Alexendoo** [comment]
Could it use the second visible post? On average that should be more centralised as the app bar can frequently cover the first visible post completely (you need to scroll up slightly to get the shadowbox icon)

**Comment by TheWorstNL** [comment]
I think I can pinpoint the problem. Shadowbox works correctly on the frontpage and /r/all but when I use it on a subreddit I'm not subscribed to it always starts at the first post until you open the shadowbox for the second time then it shows the post you're looking at.

**Comment by ccrama** [comment]
It's working fine for me in every subreddit, that doesn't sound like the same issue

**Comment by ccrama** [comment]
Ah gotcha, you meant viewing a single subreddit not in the main view. Has been fixed, also made it load the first totally visible item instead of just the first partly visible item!
