### ISSUE TITLE
Italic comment text still cut off

### ISSUE THREAD

**Issue by andrew-kennedy** [ccrama/Slide#1426]
Slide version: 5.1.6
Android version: N

Occurs on a Nexus 6P

http://i.imgur.com/dQuwUz2.png

**Comment by ccrama** [comment]
Can you link me to that comment?

**Comment by Controless** [comment]
@ccrama https://www.reddit.com/r/woahdude/comments/4elz80/neighbors_left_their_sprinklers_on_overnight_it/d21kg46

**Comment by ccrama** [comment]
Fixed for real this time
