### ISSUE TITLE
YouTube Plugin

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide#1428]
Would it be possible to create a second "plugin" app that has only one activity, the YouTube view, which would open and show as a video popup over slide (like images and gifs)? 

It would be closed source and not break any licenses, and would behave identically to having it natively in app. It would be opened just like how the YouTube app opens, without any of the extra stuff the official app loads.

**Comment by SolarAquarion** [comment]
Sounds interesting

**Comment by septemus** [comment]
You could look at NewPipe (https://github.com/theScrabi/NewPipe) for a reference, maybe.

**Comment by ccrama** [comment]
Done with my latest commit!

App can be found here https://play.google.com/store/apps/details?id=ccrama.me.slideyoutubeplugin
