### ISSUE TITLE
Multi Column value not working in Landscape mode

### ISSUE THREAD

**Issue by realvz** [ccrama/Slide#1429]
Slide version:5.1.6
Android version: Android N Pixel C

Slide is detecting landscape mode and rotating properly but not enabling multi column. This is happening randomly on my Pixel C and I cannot figure out why it works sometimes and stops working. I've tried killing the app but it didn't make any difference. 

If I enable dual columns in portrait mode then I will get 2 columns in the landscape mode as well,  but the landscape column value is ignored and it just takes whatever the value or # of columns is for portrait mode and shows that many columns even though the rest of the app is behaving just as it should in landscape mode. 

So far I have not been able to reproduce this on 5.1.1 Galaxy Tab.

**Comment by Nxt3** [comment]
I had this issue weeks ago on my Pixel C. Try uninstalling the pro add-on and reinstalling. That's what fixed it for me. Wipe data for Slide also (make sure you backup before).

**Comment by realvz** [comment]
Here's a video of the issue. 

https://vid.me/o4aj


I don't have any issues with it not working since I prefer the single column look anyway,  but I just wanted to file a bug so it can be looked at.

**Comment by Nxt3** [comment]
Ah, I see. This is more than likely Android N related. I don't think anyone of the devs is using N, so it's unlikely this will be fixed soon.

**Comment by realvz** [comment]
By the way the easiest fix for this issue is rebooting the device,  I tried deleting data and clearing cache,  but it's not worth the pain.  If you don't have a recent backup then you'd have to spend longer configuring it.

**Comment by ccrama** [comment]
Since rebooting fixes it, it's a device issue and most likely not slide at fault. Will close this, if it comes back after the full N release, we might have to re-investigate
