### ISSUE TITLE
Horizontal scroll in sidebar unable to scroll left

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1432]
Reproduce:

1. Go to /r/bestof
3. Pull out the sidebar.
4. Scroll down a bit until you see the block of text that allows you to scroll horizontally
5. Scroll horizontally
6. You'll be unable to scroll left once you've scrolled right; instead, you'll close the drawer

**Comment by ccrama** [comment]
Not happening to me, it works as intended (as of my last commit)

**Comment by Nxt3** [comment]
Yep, you fixed it.
