### ISSUE TITLE
Image galleries opened in Slide's shadowbox are missing captions

### ISSUE THREAD

**Issue by rmenessec** [ccrama/Slide#1435]
Slide version: 5.1.3
Android version: Nexus 10, Google stock 5.1.1 image (LMY49H); Nexus 6 Google stock 6.0.1 image (MMB29X)

Doesn't seem to be limited to specific galleries. Between this, #1334, and some single images just failing to load, switching off all internal image opening for now.

**Comment by ccrama** [comment]
I think you are confusing shadowbox with the album view. Shadowbox is the pro feature from the top while the gallery view is when you open an album, and you can view those captions by clicking the T button in the toolbar.

**Comment by rmenessec** [comment]
Whoops. You can close this. Sorry!

**Comment by ccrama** [comment]
No worries!
