### ISSUE TITLE
Default layout card padding

### ISSUE THREAD

**Issue by karlding** [ccrama/Slide#144]
When you untick all the boxes in **Settings > Default Layout** (see screenshot 1), the padding for the bottom of  the cards is missing (see screenshot 2).

### Settings
All options are unticked
![Screenshot of Settings](http://i.imgur.com/2zx9860.png)

### Cards
Padding on the bottom of the card is inconsistent with the padding on the top, left and right.

![Screenshot of Cards](http://i.imgur.com/c7gx1Ih.png)

**Comment by ccrama** [comment]
That has been completely re-written with lots more features (and padding fixed) in the 4.1.1 alpha update!
