### ISSUE TITLE
Subreddit thumbnail settings not honored

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1445]
I have mine set to "per sub reedit settings". Go to /r/fiftyfifty or /r/meirl and you can see thumbnails

**Comment by ccrama** [comment]
There isn't a way to not honor it, if you figured out a way to do so let me know because I've been relying on the Reddit settings to do that for me

**Comment by Nxt3** [comment]
It was honored before the either the content type refactor, or when you made all thumbnails show despite quality

**Comment by ccrama** [comment]
If reddit returns a preview, the subreddit wanted that image to show. I have it set to per sub and am getting no thumbnails

**Comment by Nxt3** [comment]
What happens when you go to /r/meirl? In my Reddit prefs, I have everything checked (in Slide)

**Comment by ccrama** [comment]
All thumbnails for me

**Comment by Nxt3** [comment]
As in, you can't see any of the images before you click on them?

**Comment by ccrama** [comment]
Yes, it shows the globe icon, there are 2 posts without the globe icon, though.

**Comment by Nxt3** [comment]
I have more than that; two are globes (an album and a gfycat). All images are shown with large previews. I assure you it wasn't like this before one of those two commits. :|

**Comment by Nxt3** [comment]
I just changed this setting to "Never show" and I still have thumbnails showing (seem to be from /r/androidcirclejerk) for some reason.

**Comment by ccrama** [comment]
Fixed, now if it's off it will never show
