### ISSUE TITLE
Add ability to remove specific/all subreddit suggestions from the sidebar

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1447]
Slide version: 5.1.7
Android version: 6.0.1

I have numerous misspelled subreddit suggestions and it would be helpful if there was a way to get rid of them individually or all together. 

Suggestions: 

- Long press a subreddit suggestion to bring up a dialog asking to delete it.
- "Clear all stored suggestions" setting in History settings.

**Comment by ccrama** [comment]
Now you can go to Settings > History and mange your history there!
