### ISSUE TITLE
Add option to align post titles to the top

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1448]
Slide version: 5.1.7
Android version: 6.0.1

Just like how there's an option for the thumbnail to the either aligned top or centered, there should also be an option to align the post titles to the top as well.

Same suggestion here with more reasoning: https://redd.it/4dwmuc (he actually meant align post titles to top, not thumbnails)

A few other major reddit apps allow this or do this by default, including Sync, RiF, and possibly others.

**Comment by Nxt3** [comment]
I'm not sure I follow on this. He posted the screenshot between Sync and Slide--but they look identical.

**Comment by ccrama** [comment]
Slide centers the text while Sync doesn't. I have pushed this with my last commit, we'll see if it looks better

**Comment by Nxt3** [comment]
Ah, I see it now--he meant vertically. I was thinking horizontally.

**Comment by Controless** [comment]
@ccrama, in your latest commit, did you make aligning top default, or added an option for it?

**Comment by ccrama** [comment]
Default, I hate adding options for stuff :P
