### ISSUE TITLE
Crash when opening posts BOTH archived AND pinned

### ISSUE THREAD

**Issue by jglass071** [ccrama/Slide#1450]
Slide version: 5.2.0 Beta
Android version: 6.0 - Moto G 2015 1/8GB

* only tested this on one post in r/tifu. It was archived AND pinned and the app doesn't crash on posts just pinned.

**Comment by ccrama** [comment]
Did you report the crash? Not seeing any reports in the console.

**Comment by jglass071** [comment]
Do you mean the error that says "slide has stopped"? If so, just did that (because I can recreate the issue so easily)

**Comment by ccrama** [comment]
Still have no reports, are you sure you're up to date?

**Comment by jglass071** [comment]
No updates for slide in google play.

**Comment by ccrama** [comment]
What is your version number in Settings > About?

**Comment by Soberat** [comment]
Slide version: https://github.com/ccrama/Slide/commit/0c33dc017271862d5c8aae5fb6b91e918bebb6e5 
Android version: 6.0.1



Crash log: http://pastebin.com/raw/e3tmr1uQ

**Comment by ccrama** [comment]
That's actually totally unrelated to the post being locked or archived, haha. Seems to only be that post too

**Comment by ccrama** [comment]
Fixed!

**Comment by jglass071** [comment]
Ah, ok. Thanks anyway
