### ISSUE TITLE
Donation activity bugs

### ISSUE THREAD

**Issue by Soberat** [ccrama/Slide#1451]
Slide version: https://github.com/ccrama/Slide/commit/0c33dc017271862d5c8aae5fb6b91e918bebb6e5
Android version: 6.0.1

- [x] <strike>Title bar isn't colored with the set theme, it's always green </strike>
- [ ] Navigation bar isn't colored with the setting, always black
- [x] Initial numbers are different than the ones after changing the amount
- [ ] Noticable flickering between $9 and $10

**Comment by Controless** [comment]
In addition, the donation activity is not swipable.

**Comment by Nxt3** [comment]
Pretty sure it's green intentionally. (Green == money)

**Comment by ccrama** [comment]
Green is intentional, and swipe to exit is disabled intentionally

**Comment by okungnyo** [comment]
LOL at that stutter between $9 and $10.

Like the app having a seizure.

Reminds me of a GIF where something similar happens, but I don't remember anything else about it.
