### ISSUE TITLE
Crash with a specific subreddit link

### ISSUE THREAD

**Issue by Soberat** [ccrama/Slide#1452]
Slide version: https://github.com/ccrama/Slide/commit/0c33dc017271862d5c8aae5fb6b91e918bebb6e5
Android version: 6.0.1

Haven't seen this one yet. <strike>Happens with /r/orlybooks.</strike>
Happens when "t.co" is added to domains to be opened externally. Would probably happen with any combination possible with reddit.com.
Log: http://pastebin.com/raw/94HgRiJK

**Comment by ccrama** [comment]
Can you link me to the thread?

**Comment by Soberat** [comment]
Sure thing: https://www.reddit.com/r/ProgrammerHumor/comments/4ey3mb/rorlybooks_is_now_a_thing/

I tested it and it also happens elsewhere, including comments.

**Comment by ccrama** [comment]
No crash for me. Do you have those links set to open externally?

**Comment by Soberat** [comment]
Nope, only Twitter and Google Play on the list.

**Comment by ccrama** [comment]
The crash is occurring while sharing a link or opening externally, are you on an N preview or something?

**Comment by Soberat** [comment]
Removed all the links and it's actually "t.co" (shorted twitter links) that causes it. Huh.

**Comment by ccrama** [comment]
reddi  t.co  m/r/orlybooks . Interesting!

**Comment by Alexendoo** [comment]
Should we have stricter checks? ie check it matches a domain level fully (reddit.com matches www.reddit.com but not notactuallyreddit.com)

**Comment by ccrama** [comment]
Stricter controls added, now it parses the URL and gets the host!
