### ISSUE TITLE
Comment navigation stops working after 2-3 comments

### ISSUE THREAD

**Issue by Soberat** [ccrama/Slide#1453]
Slide version: https://github.com/ccrama/Slide/commit/0c33dc017271862d5c8aae5fb6b91e918bebb6e5
Android version: 6.0.1

This happens for both navigation arrows as well as volume button navigation. It will work normally once the title bar covers some of comment text.

Video demonstrating it: https://drive.google.com/file/d/0BwivIOVNk_Kjcll4THRYdWRnZlU/view

**Comment by ccrama** [comment]
Should be fixed now
