### ISSUE TITLE
Use gradual acceleration when scrolling to top, or just do it instantly if too far down

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#1454]
Android version: 6.0.1
Slide version: 5.2.1

**Comment by Nxt3** [comment]
This was something I tried to implement, (pressing the tab scrolls back to the top if you're far down), but its more complicated than I was let on to think. We need to keep a count of items we've scrolled by. If that number reaches a threshold, then the scroll to top behavior needs to be changed. A faster way to do this is to use the overflow menu and refresh

**Comment by TheWorstNL** [comment]
You should be able to solve it 'quite easily' by sliding out the posts you view currently and slide the top posts back in. Instead of sliding past all posts. 

I'm not sure but I think Reddit is Fun does it like this.

**Comment by Nxt3** [comment]
I don't think it's that easy. There is already a method for determining how many posts we've scrolled past--but it's in a different part of the app. I don't understand the code enough to adapt it for the main view.

**Comment by ccrama** [comment]
Done. Now if you're too far down, it just goes straight to the top (more than 8 posts)
