### ISSUE TITLE
Layout irregularities

### ISSUE THREAD

**Issue by TheWorstNL** [ccrama/Slide#1455]
Slide version: 5.2.1
Android version: 6.0.1

Since the apparent lack of major bugs, here some minor irregularities:

- [x] When pressing 'Load full thread', after viewing a single comment, the margin on top of the LayoutContainer isn't removed. (https://gfycat.com/WebbedCircularBetafish)

- [x] When pressing 'Load full thread' usually a single comment has too much margin. Selecting the comment removes this. 

Album with examples: https://imgur.com/a/yzpbx

- [x] In 'Your profile', when you unhide an item, it slides out of view (good behavior). When you unsave an item, it stays in the list.

- [x] When you view a post and scroll down, return to the subreddit and view another post, the view doesn't always reset back to top. Cannot replicatie it on a regular basis, it happens on and off.

**Comment by ccrama** [comment]
Should be fixed!

**Comment by Nxt3** [comment]
Not fixed :(  now the toolbar covers up the post title

**Comment by Controless** [comment]
In addition, this overlap between the comment bar and nav bar occurs if you scroll all the way down.

![screenshot_20160429-180725](https://cloud.githubusercontent.com/assets/13410769/14932973/60071526-0e35-11e6-8b59-82cf6a562f2f.png)

**Comment by ccrama** [comment]
Nothing I can do about that @Controless, sorry. And @Nxt3  did your PR fix it?

**Comment by Nxt3** [comment]
I don't know about the comment nav. I don't use that. I doubt it did anything though.

**Comment by Nxt3** [comment]
My PR fixed the topbar not disappearing when tapping "Load full thread"

**Comment by ccrama** [comment]
I'll close it then. The bottom nav thing isn't really fixable, just have to scroll up a little

**Comment by okungnyo** [comment]
Couldn't you attach a blank bar at the end of comments that only appears if the user has bottom nav bar turned on?

**Comment by ccrama** [comment]
Still wouldn't move the comments up if they open the menu, which is the issue here

**Comment by okungnyo** [comment]
Don't give up, I'm sure a solution will drop out of the sky, like it always does.

I've been here too long to believe otherwise.

**Comment by ccrama** [comment]
Well it would require that I scroll the view up every time you open a menu which looks bad IMO
