### ISSUE TITLE
UI freezing and app not responding issues

### ISSUE THREAD

**Issue by abraham** [ccrama/Slide#1456]
Slide version: 5.2.1
Android version: 6.0.1

Starting within the last week I've been been having a lot of issues with the UI feezing and getting the "app not responding" pop-up. I've noticed the issues popping up mostly in three common places.

 - opening image lightbox. The loading animation across the top doesn't doesn't start..
 - opening a post view before comments load. The loading circle appears but isn't animated.
 - scrolling new image posts into view and thumbnails are trying to load.

I've submitted several stack traces so the Play Store dev console should have further details.

![screenshot_20160417-125011](https://cloud.githubusercontent.com/assets/3341/14588915/41adc17c-049b-11e6-9277-5daefb69cc15.png)

**Comment by ccrama** [comment]
Are you on a Nexus 6P? Every ANR I've received is on a 6P, so I'm thinking it might be a device only issue. Thank you for the report!

**Comment by abraham** [comment]
Yes. 6p.

**Comment by ccrama** [comment]
That's interesting. I wonder if someone with a 6P could debug it (I'm 99% sure it's a device issue as I have no reports from any other device)

**Comment by abraham** [comment]
There was a monthly security update within the last week I think.

**Comment by ccrama** [comment]
My Priv has the May security update and is not getting this issue, so may or may not have been related to that update. Did you get this issue before the update?

**Comment by Nxt3** [comment]
I have a 6P; however, I'm also not running into this issue. :(

**Comment by abraham** [comment]
Can't say if it's related to the Nexus update. I'm pretty sure it hit my phone within the last week. And within the last week is when I noticed the performance issues.

**Comment by 2fst4u** [comment]
I'm getting the same problem on Nexus 5 for what it's worth

**Comment by ccrama** [comment]
If any of you have root access, please try this!

Go to Root > Data > Data > me.ccrama.redditslide > SharedPreferences, delte Cache.xml

Does this solve the issue?

**Comment by ccrama** [comment]
Fixed, turns out the SharedPreference for "SEEN" was getting extremely large and causing Android to run out of space. Has been fixed, now it uses a SQLite database to store seen posts!
