### ISSUE TITLE
Flair-type text, especially reddit gold, doesn't look properly centered

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#1463]
<githubroot>Slide version: 5.2.2
Android version: 6.0.1
Also, the once-gilded rounded rectangle ought to have a 1:1 aspect ratio, if not be circular. Not sure if this counts as a separate issue.</githubroot>

**Comment by Nxt3** [comment]
I'm largely certain this is an issue with custom DPI. If you pull up Android Studio and look at the design generated, it's perfectly center.

**Comment by Nxt3** [comment]
How it looks on a Nexus 6P in Android Studio:

<img width="79" alt="screen shot 2016-04-18 at 2 47 37 pm" src="https://cloud.githubusercontent.com/assets/2940826/14615616/80f74978-0574-11e6-9926-16df30929191.png">

**Comment by The0x539** [comment]
440 DPI when stock is 480. Maaan, is there anything I can do to help
resolve it if even possible?

**Comment by Nxt3** [comment]
Nope. It happens to me too. There isn't anything we can do. Its an Android issue.

**Comment by Nxt3** [comment]
And it's our fault for using nonstandard DPI

**Comment by The0x539** [comment]
😞😟😕

**Comment by ccrama** [comment]
To be fair, it's off on my phone with a standard DPI

**Comment by The0x539** [comment]
But it's in my device's stock ROM!

**Comment by ccrama** [comment]
I'm agreeing with you

**Comment by The0x539** [comment]
I'm replying to @NXT3

**Comment by Alexendoo** [comment]
For just 1×gild, 00261e516a84d673132ad1a331d0df62b18b02f9 fixes the large disparity. Seeing anything beyond that?

**Comment by The0x539** [comment]
![](http://i.imgur.com/ZWSaCAY.jpg)

Just a small bit off.
