### ISSUE TITLE
PTR offset is wrong when in landscape

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1465]
Edit: Actually, its not. It seems like if you go into landscape, then swipe between tabs, Slide creates the activity oddly. I will post a video soon.

Edit: [Dropbox link to video of issue](https://www.dropbox.com/s/zklz9mw68itm991/2016_04_18_12_03_54.mp4?dl=0)

**Comment by ccrama** [comment]
Seems to be fixed with that commit!
