### ISSUE TITLE
Crash when loading specific gif

### ISSUE THREAD

**Issue by TheWorstNL** [ccrama/Slide#1467]
Slide version: 5.2.2
Android version: 6.0.1 

When trying to open the image in this comment Slide will crash with a NullPointerException: https://reddit.com/r/CrappyDesign/comments/4fcwr9/sword_fighting_encouraged/d284q4o?context=3

Stack trace submitted.

**Comment by ccrama** [comment]
That isn't a gif, are you sure that's the right link?

**Comment by ccrama** [comment]
Ah gotcha. The Gfycat API is currently down and why it's crashing

**Comment by ccrama** [comment]
Should be fixed now
