### ISSUE TITLE
App unresponsive when loading an image 

### ISSUE THREAD

**Issue by TheWorstNL** [ccrama/Slide#1468]
Slide version:5.2.2 
Android version:6.0.1 

When the app is (trying)  loading an image in the viewer the app is unresponsive. You are unable to back out when it's taking too long.

**Comment by ccrama** [comment]
Do you have an example link?

**Comment by TheWorstNL** [comment]
It's hard for me to reproduce today but yesterday evening I got it all over the place. The actual loading of the image can be cancelled but I think it's before, when the initial call is made.

**Comment by Alexendoo** [comment]
Perhaps resolved by f3ef761b766d21bbe99c472f7fe2bb4d838fbb4d?

**Comment by ccrama** [comment]
It's actually the same issue as #1456, has been fixed!
