### ISSUE TITLE
Frontpage 'subreddit' theme dialog shouldn't say /r/frontpage

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#1470]
Visit /r/frontpage in a desktop browser, why don't ya?

**Comment by Nxt3** [comment]
Where? I can fix this--I just don't understand what you mean 📦

**Comment by The0x539** [comment]
https://i.imgur.com/UJjiG18.png

**Comment by Nxt3** [comment]
Unrelated--go to www.reddit.com/r/frontpage on a desktop--whew lad.
