### ISSUE TITLE
Light themed cards need better text contrast

### ISSUE THREAD

**Issue by abraham** [ccrama/Slide#1474]
Slide version: 5.2.2
Android version: 6.0.1

I used the built in subreddit theme color sync feature.  Some of the themes need dark text for better contrast.

![screenshot_20160419-172259](https://cloud.githubusercontent.com/assets/3341/14657450/99789c74-0653-11e6-8fac-48dd4006e638.png)

**Comment by ccrama** [comment]
Every color automatically uses light text for consistency, might need to go through and delete some of the base colors that don't have enough contrast. Also, mind hopping on the Slide IRC for a second? The link is in the readme!

**Comment by ccrama** [comment]
Removed some more of the lighter colors!
