### ISSUE TITLE
Posts are not posting from right account. Strange.

### ISSUE THREAD

**Issue by derioz** [ccrama/Slide#1476]
Slide version: 5.2.2
Android version: 6.0.1

Video:
https://vid.me/Gxr8

**Comment by ccrama** [comment]
Can you let me know if 5.2.5 fixes this please?

**Comment by derioz** [comment]
No :(

**Comment by ccrama** [comment]
Does resetting app data fix it?

**Comment by derioz** [comment]
Blah. I'll do that later lol. I'll get back to you

**Comment by ccrama** [comment]
Fixed! The issue is you will have to do one wave of removing accounts (on the next alpha), but after that it should work properly :)

**Comment by ccrama** [comment]
I'll leave it open in case it isn't

**Comment by derioz** [comment]
Close it. That fixed it. Sorry.

**Comment by ccrama** [comment]
Sweet! Thanks
