### ISSUE TITLE
State select menu appears when disabling wifi

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1484]
Slide version: 5.2.5
Android version: 6.0.1

The menu is of no use when clicked on, as can be seen in the video: https://streamable.com/q83j

**Comment by ccrama** [comment]
That seems like the intended behavior, no?

**Comment by Controless** [comment]
I don't think so. Should the other icons at the top (sort, refresh, search) disappear as well? Also, the sidebar doesn't seem to change as well, it's still normal.

And clicking on the states overflow menu doesn't show the cached states, as you can see in the video.

**Comment by ccrama** [comment]
Well they should change if you click "Go into offline mode", but since you denied it this is the next best option

**Comment by ccrama** [comment]
Removed it anyway for now
