### ISSUE TITLE
Resuming the app with the icon returns to frontpage 

### ISSUE THREAD

**Issue by TheWorstNL** [ccrama/Slide#1486]
Slide version: 5.2.5
Android version: 6.0.1 

When I'm browsing and press the home button and launch the app with the icon, the app resets back to the frontpage instead of resuming. 

It isn't a crash because using the overview button I can resume the app.

**Comment by ccrama** [comment]
Make sure to replace your homescreen icon after you've updated to v5.1

**Comment by TheWorstNL** [comment]
Replaced icon just in case but issue remains. It also occurs when I relaunch from the app drawer.

**Comment by ccrama** [comment]
Can't reproduce. What launcher?

**Comment by TheWorstNL** [comment]
Google Now Launcher

https://play.google.com/store/apps/details?id=com.google.android.launcher

**Comment by ccrama** [comment]
Fixed
