### ISSUE TITLE
Bold italic text still cut off

### ISSUE THREAD

**Issue by andrew-kennedy** [ccrama/Slide#1487]
Slide version: 5.2.5
Android version: N Preview 2
Still getting the same slightly truncated comment text, this time with bold and italic text. 
Comment permalink: [here](https://reddit.com/r/SandersForPresident/comments/4fld7d/before_tonight_we_needed_56_of_remaining/d2a0neh?context=3)

**Comment by ccrama** [comment]
That comment thread got deleted

**Comment by ccrama** [comment]
Grr, fixed for real this time again
