### ISSUE TITLE
Keyboard covers text when submitting a new post. Can't scroll without closing keyboard.

### ISSUE THREAD

**Issue by nakamin** [ccrama/Slide#1495]
Slide version: 5.2.5
Android version: 6.0 MM

When submitting a post, the keyboard covers what I'm typing so that I can't see what I'm typing. Scrolling is impossible and it's also extremely difficult to move the caret if it's below the keyboard.
Screenshots:

<img src="https://cloud.githubusercontent.com/assets/17557668/14688908/df605d48-0712-11e6-9b2a-fb449b51d207.png" width="300">

Switched to Google keyboard, but no difference:

<img src="https://cloud.githubusercontent.com/assets/17557668/14688913/e58721e8-0712-11e6-9557-23697edb0608.png" width="300">

**Comment by ccrama** [comment]
Has been fixed, thanks!

**Comment by nakamin** [comment]
Damn that was fast! :smile:

**Comment by ccrama** [comment]
Haha I just fixed it like 10 mins ago
