### ISSUE TITLE
Archived/locked posts in the Upvoted/Downvoted sections don't have the respective orange/blue colored scores

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1500]
Slide version: 5.2.6
Android version: 6.0.1

The score should be colored blue in the downvoted section and orange in the upvoted section.

Example:
http://i.imgur.com/OOJHLXx.png
http://i.imgur.com/d1gDAxe.png

That's an archived post, but the same issue occurs with locked posts as well.

**Comment by ccrama** [comment]
Fixed! Good find
