### ISSUE TITLE
Both Slide and Slide (debug) are restarted when pushing a debug build from AS

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1502]
I actually commented out the lines in the Manifest for the receiver AND commented out the code inside `onReceive()` in `CheckInstall.java` and this is still happening.

**Comment by ccrama** [comment]
Fixed, was a missing (). The reason commenting it out didn't work is the original slide instance was still looking for the install

**Comment by Nxt3** [comment]
Thank you thank you thank you thank you

**Comment by Nxt3** [comment]
This is still occurring. :|

**Comment by ccrama** [comment]
It hasn't been pushed to prod yet

**Comment by Nxt3** [comment]
Oh I didn't

**Comment by ccrama** [comment]
If you don't have the play store slide installed, how is it opening it?

**Comment by Nxt3** [comment]
I have two builds on my tablet/phone. I use the "Dev Debug noGplay" for testing and changing stuff. For day to day use, I run a "Dev Release w/ Gplay". While I'm testing stuff with the Dev Debug build--each time I run it on either device, both apps are restarted. This essentially causes the debug build to show up--then the Release build restarts over the Debug version--meaning I have to back out every time I push a change to switch back to the correct version.

**Comment by Alexendoo** [comment]
It's still happening on latest play store release + latest git debug, how's this even happening anyway, doesn't that mean it's running in the background or something?

**Comment by Nxt3** [comment]
@Alexendoo Look at the `CheckInstall` class. It has a receiver that checks a package change, I think.

**Comment by Nxt3** [comment]
We just need a way to look at the app name instead of only the package name.

**Comment by Alexendoo** [comment]
It didn't evaluate false because the debug package name is me.ccrama.redditslide.debug, and cAT is me.ccrama.redditslide.test
