### ISSUE TITLE
Embedded YouTube videos open internally (no Slide Video plugin)

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1504]
If I open a YouTube video--it doesn't open to the YouTube app and instead handles it in the app despite me not having the Slide Video plugin.

[Here is a video of the issue](https://www.dropbox.com/s/5zzt1j3f1qzwdnj/2016_04_20_22_15_21.mp4?dl=0).

If this is intended behavior--I don't understand why; if the user wants internal video--they download the plugin; otherwise, it needs to default to opening the YouTube app.

On version 5.2.2-18, I don't have the plugin installed and all of the YouTube posts are labeled as "YouTube" and they open in the YouTube app. On 5.2.2-126 (debug), the content tags are incorrect (labelled "Embedded" and some "External") and open in the "internal" player.

**Comment by ccrama** [comment]
It opens as streamable content, this is on purpose because all streamable content links open this way. You can add it to open external if you want it to open externally

**Comment by Nxt3** [comment]
Where? I have it set up in Link handling and it still won't open in YouTube

**Comment by ccrama** [comment]
Does the domain match exactly?

**Comment by Nxt3** [comment]
I have: "youtube.co", "youtube.com", and "youtu.be". Nearly everything on /r/youtubehaiku is "youtube.com" or "youtu.be" and it won't open in the YouTube app.

**Comment by ccrama** [comment]
Can't reproduce. Uninstalled the plugin and added to open externally, and it opens externally for every youtube link

**Comment by Nxt3** [comment]
I don't know if it matters--but it would appear it's "youtube.com" links that aren't working as intended. "youtu.be" seems to work correctly. I definitely have my settings correct.

![screenshot_20160420-223601](https://cloud.githubusercontent.com/assets/2940826/14696370/75e6120a-0748-11e6-8ee1-7b8b648fe263.png)

**Comment by ccrama** [comment]
Fixed, was a missing parenthesis!

**Comment by Nxt3** [comment]
ayylmao; thanks :)
