### ISSUE TITLE
Crash on clicking spoiler text 

### ISSUE THREAD

**Issue by TheWorstNL** [ccrama/Slide#1509]
Slide version: 5.2.6
Android version: 6.0.1 

When clicking on this spoiler text: https://reddit.com/r/thenetherlands/comments/4fmlr1/nederland_gestegen_naar_plaats_2_op_world_press/d2an0d1?context=3

Index Out of Bounds Exception. Report sent.

**Comment by ccrama** [comment]
Fixed, good find!
