### ISSUE TITLE
Search results/Profile page top margin is too little

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1510]
Slide version: 5.2.6
Android version: 6.0.1

http://i.imgur.com/muLPHbD.png

**Comment by Nxt3** [comment]
This is the same spacing when you're viewing your profile. Do you think that's too close also?

**Comment by Controless** [comment]
Oh I didn't even realize the profile page margin was the same as well. Yes, I think that's too little as well. It should at least be the same as the margins on the normal subreddit listing pages.

**Comment by Nxt3** [comment]
fixing it now

**Comment by Controless** [comment]
Great, thanks!
