### ISSUE TITLE
Code format doesn't display properly

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1514]
Slide version: 5.2.6
Android version: 6.0.1

Take a look at this thread for example:
https://reddit.com/r/ProgrammerHumor/comments/4ftgm3/trying_to_explain_code_quality_to_execs/

This issue is persistent across all comments in code format (I think). There shouldn't be such a huge gap between the tagline and the actual comment.

**Comment by ccrama** [comment]
This also only occurs if it's just a code tag. This does not occur if there is text above it

**Comment by ccrama** [comment]
Fixed!
