### ISSUE TITLE
Add post editing to overview menus

### ISSUE THREAD

**Issue by ente3000** [ccrama/Slide#1519]
http://imgur.com/BHeZR9t

**Comment by Alexendoo** [comment]
Change flair is in the moderator actions button, adding edit/delete would make the menu excessively large in my opinion, it's already pretty full. It would also bring it out of line with other submissions

**Comment by ente3000** [comment]
In some subreddits you can change your flair even if you're not a mod. That's what I'm talking about.

**Comment by Alexendoo** [comment]
Ah right, in that case would be good to add into the edit menu if it's not available currently

**Comment by Nxt3** [comment]
It's now in the sidebar for a subreddit. Can we close this? @ente3000

**Comment by Controless** [comment]
@Nxt3 I think @ente3000 meant link flair, not user flair.

**Comment by Nxt3** [comment]
Oops :p

**Comment by okungnyo** [comment]
Yes, in some subreddits, the mods require you to tag your submission ([discussion], [news], [fan art], [video], you get the idea), or they will remove it.

**Comment by ente3000** [comment]
@okungnyo @Controless Exactly.

**Comment by ccrama** [comment]
Done!
