### ISSUE TITLE
Comment score doesn't update instantaneously when upvoting/downvoting a comment, going to another post, and then un-upvoting/downvoting that same comment [Video]

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1525]
Slide version: 5.3.1
Android version: 6.0.1

https://streamable.com/5pyl

**Comment by ccrama** [comment]
Fixed, good find!

**Comment by Controless** [comment]
@ccrama, almost the same behavior can be noticed when you upvote a post, refresh, and then un-upvote it. The points do not update instantaneously. However, it works perfectly fine for downvoting.
