### ISSUE TITLE
Rapidly tapping a comment results in a container much larger than the comment itself

### ISSUE THREAD

**Issue by matthieugrieger** [ccrama/Slide#1531]
Slide version: v5.3.1
Android version: v6.0.0

Hi there!

I found a fairly minor bug. If you rapidly tap a comment (my long press and tap actions are switched) it sometimes results in an expanded comment container that is roughly twice the required size.

Screenshot: http://i.imgur.com/UoSUTdD.png

Obviously this isn't a very major bug and probably doesn't even show up for most people. I have a strange habit of tapping comments while reading them. :)

**Comment by Controless** [comment]
Similar to issue #1481.

**Comment by ccrama** [comment]
It's actually the same issue. Merging with #1481 
Thanks for the report @matthieugrieger !

**Comment by matthieugrieger** [comment]
Oops! I guess I didn't skim the issues as carefully as I thought.

Thanks, and sorry about the duplicate!
