### ISSUE TITLE
Support for comment faces.

### ISSUE THREAD

**Issue by beepFTW** [ccrama/Slide#1532]
Slide version: 5.3.1
Android version: 6.0.1

Purely cosmetic, an example of this can be seen in this [thread](https://www.reddit.com/r/manga/comments/4g2iah/new_comment_faces/).

When viewed on Slide, all we see is an underlined period. Although we get an idea of what it is at least by long pressing it.

**Comment by ccrama** [comment]
Unless these are added to the PonyMotes app (which is very possible), it would be very difficult to implement this. Feel free to request it at /r/ponymotes!

**Comment by ccrama** [comment]
Going to close this as it needs to be done through PonyMotes and not Slide

**Comment by okungnyo** [comment]
Kinda related.

So I just Googled PonyMotes, and apparently it's an app that allows mobile users to view these 'comment faces' things that some Subreddits use?

But I remember you telling me that it was a custom CSS thing, so it wouldn't be possible for Slide to support them??

**Comment by Alexendoo** [comment]
It's an app that allows users to view specific ones that are supported, a general solution that worked everywhere would require parsing CSS and most likely spritesheets too, which is pretty heavy.

The ponymotes app stores a bunch of images offline, and maps certain links to them, rather than having to download + parse things

**Comment by okungnyo** [comment]
So would it be possible in the far future for @ccrama to do the same for Slide? Like make a plug-in for Slide that does the same thing as PonyMotes, except he wouldn't have to be reliant on PonyMotes.

Like set up a subreddit like /r/SlideCommentFaces where people can request which subreddits should be added. And if the sub has more than 10,000+ subscribers or something like that, then it will be added.

**Comment by Alexendoo** [comment]
Technically possible, but it would require a lot of infrastructure to do well so it's pretty infeasible. Cost would far outweigh the gain

**Comment by ccrama** [comment]
Well I was more hoping they could add it into ponymotes, I really don't know how it works or how I could implement it myself @okungnyo
