### ISSUE TITLE
Add app analytics

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1534]
**Default on (opt out):**
Google Analytics would be ideal + include it only with withGPlay, don't enable dispatching for non-gplay devices (not having google play services on android is essentially an analytics opt out), this is the default so it's easy to do. F-Droid users tend to be privacy conscious, they'd not be touched at all by the analytics.

It would allow us to more accurately determine which things are used the most by users, whilst listening to users who submit feedback and opinions of contributors is no doubt useful, it's a very biased demographic to use to draw conclusions for the whole app as far as usage is concerned.

We could tweak wording/ reposition settings & features that are being used far less than expected, as well as optimise for the most common user actions, among plenty of other things

**Comment by captainepoch** [comment]
What about devices with MicroG? Are you able to distinguish bethween a GPlay-device and a MicroG-device?
