### ISSUE TITLE
Premium features in fdroid

### ISSUE THREAD

**Issue by mcanders** [ccrama/Slide#1535]
First, thank you so much for adding your app to fdroid.  I'm loving it so far!  I want to support your app by purchasing "slide for reddit pro" (and get all of the features)  but as I don't have google play services and the google play store installed on my phone I have no way of purchasing it.  It would be nice if there was an alternative way to pay (paypal, bitcoin, etc).  You could possibly generate product codes, which Slide could then use to enable the features.  This would require compiling a binary with all of the features, but with the premium features locked until a valid product code is entered.

However there could be a few blockers for this:
1) I'm not sure what fdroid's policy on paid features are.  This could break some of their rules
2) I don't know your code base so I have no clue if the premium features are open source.  If they are not open source this will probably earn you a "red flag" on your fdroid page. 
3) The implementation I mentioned above might be more work than it is worth.  I can't imagine you will get much profit from this.  There aren't that many fdroid users in the first place and the subset willing to pay for features will be even smaller.

**Comment by legogo29** [comment]
There has been commented it this reddit thread:
https://www.reddit.com/r/slideforreddit/comments/4g8fyp/slide_now_available_on_fdroid/d2fpy9r

> And pro is just an unlock key, it has no code so probably not. If you purchase it on the Play Store you can take advantage of the feature, though. I'll look around for alternatives to purchasing on the play store for those who are 100% no Google play :)

**Comment by The0x539** [comment]
Those not opposed to the usage altogether of F-Droid can, if I'm remembering how app purchasing works, purchase the unlock key on the website and use Raccoon on a proper computer to download the pro APK, should they wish to access the features in the (currently) only legitimate method.

**Comment by ccrama** [comment]
This issue was much more complicated than I had anticipated. As a workaround, I have made all pro features free on F-Droid for the next update

**Comment by The0x539** [comment]
Well that's pro-consumer as all hell

**Comment by mcanders** [comment]
Agreed.  I vote you add a "donate" button so people can compensate you for your work if they feel the need.  I would definitely make use of it.
