### ISSUE TITLE
This selftext has an incorrect content tag

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1545]
Slide version: 5.2.2-227

Only post I've seen like this so far.

https://www.reddit.com/r/slideforreddit/comments/4fhhv1/how_do_i_hide_nsfw_images_but_not_the_posts/

![screenshot_20160425-002323](https://cloud.githubusercontent.com/assets/2940826/14773778/4b8b36c0-0a7c-11e6-9503-f8bb551cfe27.png)

**Comment by okungnyo** [comment]
I see a [SOLVED] tag on both?

**Comment by Controless** [comment]
He's talking about "Link" when it's actually a self post.

**Comment by Alexendoo** [comment]
Strange. Not occurring on latest though for me, how about you @Nxt3?

**Comment by Nxt3** [comment]
Just made a build and it's still happening for me. Do you use the "Smaller content tags" by chance?

**Comment by Alexendoo** [comment]
I don't

**Comment by Nxt3** [comment]
See if that triggers the issue.

**Comment by Alexendoo** [comment]
Nope, no issue on latest git for me still

**Comment by ccrama** [comment]
@Nxt3 unless both of your builds have the new code, installing one still triggers the old app

**Comment by Nxt3** [comment]
@ccrama What do you mean? If I'm using the app with the latest code--how does that affect the other app in this case?

**Comment by ccrama** [comment]
@Nxt3 ignore me, I thought this was a thread about slide opening up when installing

**Comment by ccrama** [comment]
Fixed! It was a mixture of having it selftext and the NSFW tag

**Comment by Nxt3** [comment]
Yep--I was _just_ about to say that. It seemed to disappear if I enabled "Hide Lead Image on Selftext posts"
