### ISSUE TITLE
Suggestion to sibling comment navigation

### ISSUE THREAD

**Issue by SaladMandrake** [ccrama/Slide#1546]
Slide version: 5.3.2.2
Android version: 5.0

This topic suggests a way to navigate between same level replies belonging to a parent comment.

Alternative A:
Add up and down arrow ('^' 'v') to long press menu of individual comments, for navigating to previous/next comments of the same level (sibling comments?).

Long press on up arrow to go to first sibling of same level, long press on down arrow to go to last sibling of same level. If already at first sibling comment, long press up arrow brings user to previous level (example: lvl 3-> lvl 2).

Alternately, long pressing on up arrow of any comment simply brings user to previous level (example: lvl 3 -> lvl 2).

Alternative B:
Yet another alternative option is to put it in the new compass menu. Add a new Sibling navigation type. Comment navigation now have 4 arrow buttons, up down left right, plus the compass in the middle. Comment levels start at level 1, in a comment thread, pressing right increases comment level by 1, this makes up and down arrow to jump between comments of that comment level.

Press left to decrease comment level by 1. Long press left to reset comment level to 1.

Pressing up/down on first/last comment of a comment level make it jump to previous/next comment thread, if exist, and reset comment level to 1.

**Comment by ccrama** [comment]
I like the idea A, but I just realized there might be an issue with doing this at all. I don't really know what level the user is currently looking at, and it might have bad behavior if it goes to one higher or lower. What if long press moved to a second-level comment, as that is usually the next thread of replies anyway

**Comment by Alexendoo** [comment]
Would mean possibly ditching the long press to go to top. If you were going to add a long press option for the down arrow I think it'd be good to have it return to the place you were before long pressing to go to the top, which I think was discussed somewhere in another issue # but can't find it

**Comment by ccrama** [comment]
Oh didn't even know that was a thing. Hmm

**Comment by ArthurHeng** [comment]
for Idea A, the navigation buttons are on the individual comment itself, so if you long press on a level 2 comment to access the menu, you can be sure that you are supposed to navigate among level 2 comments.
http://i.imgur.com/czuLIHh.jpg

**Comment by ccrama** [comment]
Done, now if you select a comment and then use the down arrows to navigate, it will go to the next comment with that comment's depth
