### ISSUE TITLE
Automatically remove YouTube from the force-external-browser list when Slide detects that the Video Plugin has been installed

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#1547]

**Comment by ccrama** [comment]
I agree on removing the prefs, because if they remove it it will suggest downloading again or opening externally.

**Comment by ccrama** [comment]
After giving it some thought, I think it might be better to not do this because the user doesn't expect it to be removed from the link handling settings (in case they uninstall it). What are your thoughts @okungnyo

**Comment by okungnyo** [comment]
Then maybe have the links greyed out instead of removed?

And when the user taps on the greyed out links, have a little toast message that explains that because the video plug-in is installed, the greyed-out-links are being overriden.

**Comment by ccrama** [comment]
Now they are hidden if the video plugin is installed
