### ISSUE TITLE
Apply focus on latest read post when go back out to post listing feature to Multireddit as well

### ISSUE THREAD

**Issue by ArthurHeng** [ccrama/Slide#1548]
Apply "focus on latest read post when go back out to post listing“ feature to Multireddit as well.

When we are reading post #100, make Slide focus on post #100 when we go back out to the post listing, a la BaconReader/Opengur. Slide already has this feature, just apply the same to Multireddit.

https://www.reddit.com/r/slideforreddit/comments/4c92j8/improvement_scroll_to_the_last_post_we_read_when/

"1. In post listing, I click into post #1 to read it.
2. While reading post #1, I swipe to the next few posts, swipe swipe swipe again to post #100.
3. I press back to go back to post listing.
4. Slide currently brings me back to my original spot, which is post #1, but I want it to scroll down to post #100 for me."

**Comment by ccrama** [comment]
Fixed, thanks for the report!

**Comment by ArthurHeng** [comment]
No, thank YOU! =)
