### ISSUE TITLE
Invisible flairs

### ISSUE THREAD

**Issue by ente3000** [ccrama/Slide#1549]
Screenshots: https://imgur.com/1WeW4ka & https://imgur.com/Eqtj3H5
Subreddit: nomansskythegame

**Comment by Alexendoo** [comment]
Seems they don't display because it's just a class without a name, include the class also perhaps?

**Comment by ccrama** [comment]
Both of those links are broken

**Comment by ccrama** [comment]
Ah, those are because the flairs are empty. It's not a bug, just how Reddit is

**Comment by ente3000** [comment]
The flairs don't have a name, only an image. Don't know why the links are broken tho.

**Comment by l3d00m** [comment]
Correct, the images are in that subreddit's css, it's not possible to get them unfortunely.

**Comment by ente3000** [comment]
Updated screenshots: http://imgur.com/NI4m1Mc & http://imgur.com/rfvEEUI

**Comment by ccrama** [comment]
Still isn't possible, though. If you go to the nomansskythegame 's subreddit on your browser, none of the flairs have text at all, so Slide cannot make up text to show there. 

I just put the CSS class name in there if the text is blank, but nothing else I can show, unfortunately

**Comment by ente3000** [comment]
@ccrama I guess we'll just see if that helps.

**Comment by ente3000** [comment]
@ccrama I guess we'll just see if that helps.

**Comment by ccrama** [comment]
Yeah hopefully, other than that there is no other solution
