### ISSUE TITLE
Rate snackbar should be in main view rather than settings

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1550]
With a pretty high number (10, 20 or something), in the main view users are just browsing content, they can take a side action with no real consequence.

However in settings there's usually a clear goal, taking another action is not typically desired and so suggestions to do so are seen as a distraction. (Less conversions + more likely to annoy)

**Comment by l3d00m** [comment]
Done in f62d6ab9cf794ddacef6fe358b608e99232d808b
