### ISSUE TITLE
Custom Comment Depth Indicator Colors

### ISSUE THREAD

**Issue by ArthurHeng** [ccrama/Slide#1553]
A new interface in settings to allow users to customize their own comment depth indicator colors.

Users can choose color combinations from minimum 1 to a reasonable maximum colors and the colors would repeat. Choosing 1 color means only 1 single color as depth indicator. If user choose 3 colors (red green blue) the depth indicator would look like rgbrgbrgbrgb...

This way users can pick their own color combination that they are familiar with and easier to know which comment depth/level they are in.

**Comment by ccrama** [comment]
That would be quite complicated, and there's already the option to make it monochrome or color. Sorry, don't think it's possible
