### ISSUE TITLE
Cannot load more comments of large threads

### ISSUE THREAD

**Issue by ArthurHeng** [ccrama/Slide#1560]
Slide version:5.3.2.4
Android version:5.0

http://sendvid.com/mp021s65

Kindly see video thanks. Seems to happen to posts with huge amounts of comments. 500+ comments works while 5000+ does not.

**Comment by Nxt3** [comment]
This is a bug with Reddit. This has been brought up multiple times.

I've had this happen to me when I used to use Sync; and I've heard it happens in a few other apps. There isn't anything Slide can do, unfortunately.

**Comment by ArthurHeng** [comment]
Ah ok then. It keeps happening here and there, so frustrating to see comments tries to load then disappears.

**Comment by ccrama** [comment]
Yeah really nothing I can do about it, unfortunately
