### ISSUE TITLE
Relocate spinny loading icon as to not block post titles while loading

### ISSUE THREAD

**Issue by ArthurHeng** [ccrama/Slide#1561]
http://i.imgur.com/dqAIXk8.jpg
http://i.imgur.com/ixRDYMT.jpg

Would be nice to move it a little lower so it doesn't block the title while the post is loading, like Bacon or Sync. It might just be a low priority cosmetics change, but since it appears everytime a post loads, if I read 1000 posts, I have to look at it 1000 times. It drives me absolute bonkers. I already requested it twice, Ccrama told me the concern about breaking pull down to load code. I understand, I just post it here for record and hopefully one day you guys will get to it.

**Comment by Nxt3** [comment]
I'm not sure I understand what it is you mean. In your screenshot (first one), the progressbar is below the card.

**Comment by ArthurHeng** [comment]
The two screenshots are from Bacon and Sync. If Slide move the spinny icon lower, like Bacon/Sync, it won't block the title/photo thumbnail while the post is loading.

**Comment by Nxt3** [comment]
where do you see this progressbar in Slide? I'm not even sure I've encountered this.

**Comment by ArthurHeng** [comment]
https://imgur.com/gallery/VbRnv

Screenshots from Slide

**Comment by Nxt3** [comment]
Ah, I see what you mean. I'll see what I can do; shouldn't actually be that difficult. However, personally, I don't see the big deal.

**Comment by ccrama** [comment]
I think it would look strange below the image, as it's not in the same place every time and the pull to refresh would be quite awkward

**Comment by ArthurHeng** [comment]
Perhaps make it separate? Pull down to refresh still uses the same icon and spins at that same spot, but when the post is initially loading, use the simpler spinny icon for loading more comments, and place it below.

Just a suggestion. ;-)

**Comment by Nxt3** [comment]
^That's what I was thinking.

**Comment by ArthurHeng** [comment]
My suggestion follows the official Google apps, such as Keep and Gmail, its proper Material.

Gmail pull down to refresh, the pulled down circle spins:
http://i.imgur.com/wUxUD0G.jpg

Gmail when content is loading, shows a different spinny:
http://i.imgur.com/Djf6MKU.jpg

**Comment by ArthurHeng** [comment]
Anyway, its your app so I respect your decision. =) Thanks for the discussion.

**Comment by ccrama** [comment]
Yeah I like that idea. I'll do that for the next update!

**Comment by ccrama** [comment]
Done, now it's a horizontal bar!

**Comment by ArthurHeng** [comment]
Thank you so much ccrama =)
