### ISSUE TITLE
[Request] Alphabetize the multireddit sidebar subreddit list

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1563]
Slide version: 5.3.2.4
Android version: 6.0.1

**Comment by ccrama** [comment]
It's in the order Reddit returns it, presumably on purpose out of order

**Comment by Controless** [comment]
So is there no way to alphabetize it? I have a multireddit with 40-50 subs (and I'm sure other users have large multis as well) and it's rather time consuming trying to locate a specific subreddit from the sidebar.

**Comment by ccrama** [comment]
It is possible but I wonder why Reddit returns in this order

**Comment by Controless** [comment]
Yeah same, I don't understand as well. It's so random and odd.

**Comment by ccrama** [comment]
Maybe addition time?

**Comment by Controless** [comment]
Doesn't seem to be the case. I added a subreddit to my android multi and it appeared near the bottom of the list (not *at* the bottom though).

**Comment by ccrama** [comment]
No idea either, but done
