### ISSUE TITLE
Scrollbars constantly resize

### ISSUE THREAD

**Issue by Gawdl3y** [ccrama/Slide#1569]
Slide version: 5.3.3-alpha
Android version: N Preview 2

The scrollbar in the comments page wildly fluctuates in size based on the size of the comments currently on the screen. This can be fixed on RecyclerView layout managers by calling `setSmoothScrollbarEnabled(false)`. This issue appears throughout the app (submission list, profile comments, inbox, etc), not just the comments. Any time you have entries in a ListView/RecyclerView that aren't constant size, the smooth scrollbar should be disabled.

**Comment by Gawdl3y** [comment]
Just a heads-up: disabling the smooth scrollbar does come with the downside of making the scrollbar.. well, not smooth. The scrollbar will simply jump to the next position with no animation. This is definitely preferable to a scrollbar that doesn't reliably indicate your position at all due to constant resizing, however.

**Comment by Nxt3** [comment]
Let me see how it looks first. I'm testing the changes on the Comments page first. Give me a few.

**Comment by Gawdl3y** [comment]
[The docs describe it better than I do.](http://developer.android.com/reference/android/support/v7/widget/LinearLayoutManager.html#setSmoothScrollbarEnabled(boolean))

**Comment by Nxt3** [comment]
I know--I'm actually just having difficulty disabling it. I'm setting `mLayoutManager.setSmoothScrollbarEnabled(false);` then calling `recyclerView.setLayoutManager(mLayoutManager);`. The change isn't present though. Working on it.

**Comment by ccrama** [comment]
I think it's set in the layout XML @Nxt3 , might have to disable it there and enable it programatically

**Comment by Nxt3** [comment]
only thing that relates to the scrollbars in the XML is `android:scrollbars="vertical"`. I'll try removing that--but I don't think it matters.

**Comment by ccrama** [comment]
Yes, that's it

**Comment by Nxt3** [comment]
Then nothing changed :|

**Comment by ccrama** [comment]
Instead, do rv.getLayoutManager().setSmooth...., that might work

**Comment by Nxt3** [comment]
It won't let me lol

**Comment by ccrama** [comment]
It might have to be cast to a LinearLayoutManager

**Comment by Gawdl3y** [comment]
You guys should consider using [Gitter](https://gitter.im/) or [Slack](https://slack.com/) for real-time chat. Would probably be much easier for you (fully real-time, push notifications, and all that good stuff), and won't send loads of emails. :P

**Comment by Nxt3** [comment]
I'm just not on the IRC chat right now ;)

**Comment by Alexendoo** [comment]
@Gawdl3y We chat in [#slide on Snoonet](https://kiwiirc.com/client/irc.snoonet.org/#slide) if you wished to drop by ever

**Comment by Nxt3** [comment]
I give up with this. I tried everything I could think of. I almost think we should just remove the scrollbars all together--seeing as how often the height changes.

**Comment by Controless** [comment]
I don't mind it that much honestly, a lot of other apps experience this issue as well (like IRCCloud). It's certainly better than nothing.

**Comment by Nxt3** [comment]
I'm actually working to integrate [this MaterialScrollbar library](https://github.com/krimin-killr21/MaterialScrollBar) with Slide. It doesn't quite fix this issue, but it at least makes the scrollbar more useful--while adding some better looks to the app and keeping functionality the same.

**Comment by Gawdl3y** [comment]
@Nxt3 How's that going?

**Comment by Nxt3** [comment]
Not too well. [See this issue](https://github.com/krimin-killr21/MaterialScrollBar/issues/41). Maybe you could help me?

**Comment by okungnyo** [comment]
I don't know, can he?

**Comment by dulleh** [comment]
@Nxt3 do you have a branch set up for the MaterialScrollbar changes?

**Comment by Nxt3** [comment]
@dulleh Nope. I could never get it working so I trashed the work. It wasn't much code at all; there is something going on with our RecyclerView that messes with that Library, but I never *really* tried to figure it out.

**Comment by ccrama** [comment]
So, should this be closed? I don't really see any alternative short of removing the scrollbar all together

**Comment by Nxt3** [comment]
Yeah. This isn't going to be possible with a RecylerView. Of all the libraries I could find to achieve this--none of them worked. I'm sure there is a way to fix it, but all things considered--this is out of our control.
