### ISSUE TITLE
Comments stop loading when the Reddit connection is lost

### ISSUE THREAD

**Issue by Gawdl3y** [ccrama/Slide#1570]
Slide version: 5.3.3-alpha
Android version: N Preview 2

When the connection to Reddit is lost, or the auth needs to be renewed, or whatever the circumstance may be, comments cannot be loaded. You have to attempt to perform an action on a post (vote, save, etc) to get the pop-up asking if you'd like to retry, then open the comments. This is especially inconvenient in the comment pane layout, since you have to perform an action on a post, confirm the retry dialog, load a different post's comments, then go back to the comments you originally wanted to view in order to load them.

**Comment by ccrama** [comment]
When it pops up saying would you like to try again, that does a re-auth if successful.

**Comment by ccrama** [comment]
Wrong button

**Comment by Gawdl3y** [comment]
It does successfully re-auth. The problem is that attempting to view comments doesn't trigger that dialog - the comments just stay loading/blank forever, until you attempt to perform an action on a post to trigger that dialog. You can try to open as many comments as you want, and they'll all have the issue until you do something to trigger the dialog.

**Comment by ccrama** [comment]
Now it will catch the exception in the comment area and give you options to reconnect or retry loading more comments!
