### ISSUE TITLE
Allow swiping away rate and changelog snackbars

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#1576]

**Comment by ccrama** [comment]
No, it's stuck on purpose

**Comment by ccrama** [comment]
Well, the rate one should be swiped away, but the issue is it needs a CoordinatorLayout to enable swiping, which isn't really possible with Slide's UI

**Comment by ccrama** [comment]
Now you can swipe away

**Comment by okungnyo** [comment]
This thread makes you look like a rambling mad scientist...

**Comment by Controless** [comment]
@ccrama The rate snackbar isn't swipable for me on 7e9aba609115a39a644ecb197515fbc902199c78.
