### ISSUE TITLE
/r/meirl has no thumbnails

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1577]
Go to /r/meirl. There are no thumbnails displayed.

I have my Reddit prefs set to "Per Subreddit Settings" for thumbnails.

![screenshot_20160426-100702](https://cloud.githubusercontent.com/assets/2940826/14821008/0783a04a-0b97-11e6-926f-b145b037923d.png)

**Comment by Alexendoo** [comment]
They aren't shown because you use per subreddit settings, and they're set not to show on meirl

**Comment by ccrama** [comment]
It should show globes though @Alexendoo

**Comment by ccrama** [comment]
Fixed though
