### ISSUE TITLE
Checkboxes to add Subreddit to Multireddits in Subreddit sidebar

### ISSUE THREAD

**Issue by ArthurHeng** [ccrama/Slide#1579]
In Subreddit sidebar (http://i.imgur.com/hNqNdYP.jpg), under subscribe checkbox also list our existing Multireddits plus checkboxes to quickly add the subreddit to a Multireddit, like RES. http://i.imgur.com/xbthVoA.png

**Comment by ccrama** [comment]
That would overpopulate the sidebar and it really isn't a high-enough used action to do this. Slide makes it pretty simple in the multireddit creation screen to add it in, though :)
