### ISSUE TITLE
Subreddits not being updated on menu

### ISSUE THREAD

**Issue by kennedy5387** [ccrama/Slide#1581]
Slide version:Slide v5.3.3-alpha.2-1-7da9363
Android version: 6.0.1

My subreddits are nlr updating. I double checked to make sure I subscribed to them via desktop. I subscribed a few weeks ago but they aren't reflected in my side bar with my subreddits options.

**Comment by Nxt3** [comment]
Did you do Settings > Reorder Subreddits > Refresh?

**Comment by ccrama** [comment]
I'm 99% sure this was the issue. If you run into it again let me know!

**Comment by kennedy5387** [comment]
That was it! Thank you. Sorry I didn't realize that setting was there
