### ISSUE TITLE
[Request] Apply same FAB behavior from posts/comments to the "Reorder subreddits" and "Subreddit themes & layouts" page

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1587]
Slide version: 5.3.3-alpha.3
Android version: 6.0.1

**Comment by Alexendoo** [comment]
What differs exactly?

**Comment by Controless** [comment]
Hard to explain but if you scroll down and then up without releasing your fingers the fab doesnt pop up. It only appears if you start scrolling up.

**Comment by Nxt3** [comment]
This isn't happening to me. Scrolling down hides the FAB--and then w/o releasing my finger--scrolling up reveals the FAB again.

**Comment by ccrama** [comment]
Done
