### ISSUE TITLE
doesn't connect under Tor

### ISSUE THREAD

**Issue by moshpirit** [ccrama/Slide#1588]
I have a rooted Android 5.1.1 with Orbot so I can torify everything, including Slide (F-droid version) but most of the times it gives me an error saying that it can't connect to Reddit. I think it's the same it happens with Red Reader Beta (but not with Diode, I always can use Diode).

**Comment by ccrama** [comment]
Probably because redreader and Slide have to use oauth2 while diode hasn't been updated in a long time and probably uses some deprecated authentication

**Comment by moshpirit** [comment]
I don't know, maybe. But I'd like to have a solution and keep using Slide under Tor.

**Comment by Nxt3** [comment]
Not really something Slide can fix. I mean, I guess it _could_ be fixed--but that would require weakening the security. You'd be the only person to say you've had issues; this isn't surprising, as it's so incredibly niche. You're going to have this issue with probably any of the current Reddit apps.

**Comment by ccrama** [comment]
Well actually I can't use http, https is the only way to access the new api. Do you possibly have https disabled with TOR?

**Comment by moshpirit** [comment]
No, the Tor project is always encouraging us to use HTTPS. I checked Orbot settings and I think it's always under HTPPS if it's possible this option.

**Comment by Alexendoo** [comment]
Save for some things that get redirected such as the inbox, diode does its authentication over HTTP using cookies

**Comment by Alexendoo** [comment]
@moshpirit Do you have access to logcat? I'd be interested to see why it's failing exactly

**Comment by moshpirit** [comment]
OK, I found this using aLogcat ROOT (F-droid):

`E/AndroidRuntime( 6732): Process: me.ccrama.redditslide, PID: 6732`
`E/AndroidRuntime (6732): at me.ccrama.redditslide.CommentCacheASync.do.InBackground(CommentCacheSync.java:252)`  
`E/AndroidRuntime (6732): at me.ccrama.redditslide.CommentCacheASync.do.InBackground(CommentCacheSync.java:38)`

After this 3 other lines saying `W/PackageManager(25405): Failure retrieving resources for me.ccrama.redditslide: Resource ID #0x0`

I dunno if it helps (I'm not a developer). I think it's easier for you to understand it if you just try Slide with Orbot on your phone and torifying Slide.

**Comment by ccrama** [comment]
Is this still an issue? Has been a few months and haven't gotten any other reports of this

**Comment by ccrama** [comment]
Closing for now, if this issue returns please feel free to re-open!

**Comment by moshpirit** [comment]
Still happening on Android 6.0.1. Just came here to add [some info](https://github.com/QuantumBadger/RedReader/issues/290#issuecomment-238091174)

**Comment by ccrama** [comment]
Thanks for the link @moshpirit . Unfortunately that still leaves the fact there is no way to fix it, unless we show a capatcha every few minutes, and develop some method to do this for the minority of users who are trying to use this on the TOR network

**Comment by l3d00m** [comment]
Well, it actually sounds like Cloudflare / reddit is looking into it: https://www.reddit.com/r/bugs/comments/4wre66/cloudflare_blocks_reddit_api_requests_from_tor/d69vlz2

**Comment by ccrama** [comment]
@moshpirit I believe this is fixed now, can you confirm?

**Comment by moshpirit** [comment]
I think you can close the issue for now. If Slide fails, we cam always reopen it. I also shared the RedReader post on Reddit in order to get more people using Reddit under TOR :)

**Comment by ccrama** [comment]
Glad to hear that! Let me know if anything changes :)
