### ISSUE TITLE
When viewing a subreddit directly, the information and sort buttons do not function

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#16]
The sort button does nothing whereas the information button :information_source: does open a view, but with no visible items. However it is possible to open view sidebar/wiki/edit card by tapping in the blank area.

![nexus-1444324508](https://cloud.githubusercontent.com/assets/1830331/10373989/875f33bc-6de8-11e5-8e5c-bae3a62cdcf4.png)
![nexus-1444324511](https://cloud.githubusercontent.com/assets/1830331/10373988/875eda98-6de8-11e5-93f2-e9381686da7d.png)

**Comment by ccrama** [comment]
Very strange. Will fix this asap!

**Comment by ccrama** [comment]
Fixed with d267a5fdfbe7ea603986c8f56b22a779709d9b60!
