### ISSUE TITLE
Lack of comments in the source code

### ISSUE THREAD

**Issue by piyush-rvc** [ccrama/Slide#1603]
I am from R.V. College of Engineering from India. We have been asked by our instructor to contribute to OSS. Reddit quite popular among the students and an open source Android Client, that is awesome. I proposed Slide among my batch-mates, approx 24 people are willing to contribute to it. But preliminary look at the code shows a lack of proper documentation. It would greatly help in ramp up process if you could add documentation. Thanks!!

**Comment by piyush-rvc** [comment]
We have to do this for next two semester (June onwards)

@Nxt3 @ccrama can we have some time-line for this so we can let our instructor know about the project we would we working on. Thanks!!

**Comment by Alexendoo** [comment]
24 people sounds a little intense, what exactly would be happening @piyush-rvc?

**Comment by okungnyo** [comment]
My eyes widened reading this as well. Twenty four people, wow!

**Comment by piyush-rvc** [comment]
@Alexendoo @okungnyo 
Ours is a batch of 120 people. We have credits for internship done after 6th semester, which is evaluated in 7th semester. We will be enrolling in 5th sem this June. Our instructor has given us the option to work on OSS during two semesters and have the credit for internship. But we will have to let him know about the project we will be working on, and the id we will be using to make pull requests.

**Comment by Nxt3** [comment]
@piyush-rvc Here's the deal. I've only been contributing for a few months now. The lack of documentation sucks--but once you dive in and start working with it--stuff starts to make sense.

Ccrama started Slide while he was teaching himself Android. He realized that he should have commented code earlier on--but it just wasn't a high priority. I try to comment changes I make--sometimes I don't.

I could only Javadoc so much before I'd have to start asking someone more familiar with the code for what to write. This is one of those jobs that nobody wants to do--and I don't blame them--it's boring. There isn't a timeline, unfortunately.

Having said that, I agree that 24 people sounds intense.

**Comment by ccrama** [comment]
@nxt3 @piyush-rvc that sounds like a great opportunity! Do you have any ideas on what you'd like to contribute to Slide? 

And yeah documentation currently isn't great but I'm planning on doing some more soon, are there any classes or things you'd like to see information and comments on to start with? I'm  usually on IRC in the afternoons US Central Time if you would like to hop on and we could chat!

**Comment by piyush-rvc** [comment]
@ccrama I would like to add comment collapse feature like that of official reddit app for android, to begin with, then later, google anyalitics and other bug fixes/Feature requests that would come along the way.

Classes related to comments would be a good start for documentation. Also some documentation about how they are organized at module level.

Which channel on IRC? will be busy with end sems for a couple of weeks. We can chat after that.

**Comment by l3d00m** [comment]
@piyush-rvc [#Slide on snoonet](https://kiwiirc.com/client/irc.snoonet.org/#slide), feel free to join it!

**Comment by Nxt3** [comment]
@piyush-rvc Slide already has the ability to collapse comments.

**Comment by l3d00m** [comment]
@piyush-rvc (Un)fortunaley there is already an option for that :p Settings > Comments > Collapse fully

**Comment by ccrama** [comment]
@piyush-rvc sounds good! I'm about to head into exams the next few weeks as well and would have more free time to discuss with you afterwards. Feel free to join the irc channel mentioned by @l3d00m when you are avaliable

**Comment by bantar** [comment]
@piyush-rvc, one of the ways that you might contribute is to perform this documentation yourself.   As you are going thru the code, if there is a complex piece that is not easily understood, take the time to understand it, then when you have it figured out, go ahead and document it.   While studying any one piece of code well enough to document it, you might find a bug or weak spot and then contribute even further.   In a sense, your learning will be akin to a Code Review.   Any structured walk thru the code will find bugs.  Code contributions will be greatest from those that understand the subject matter quite well.  

I'd go further and say, don't expect to contribute features right away.  Learn the base first and make a difference.   If you try to do the opposite, you'll only slow down ccrama as he'll be cleaning up from your mistakes.   This wouldn't be a positive contribution.   I know it doesn't seem like the most exciting path, but learning technology is fun and it will go faster than you think.

**Comment by ccrama** [comment]
Going to merge with #755 , we can move the conversation there, too!
