### ISSUE TITLE
Swiping to next post in comment view causes a 'Flash'

### ISSUE THREAD

**Issue by goodpricefriedrice** [ccrama/Slide#1604]
Screen flashes once as its loading every post. 

Tried restarting device (havent tried a reinstall)

Slide version: 5.3.3-alpha.4
Android version: 6.0.1

Edit: should add this only started in the previous version (alpha 3?). Possibly earlier, but thats when i first noticed it.

**Comment by Nxt3** [comment]
Was able to reproduce

**Comment by ccrama** [comment]
Fixed, thanks for the report!
