### ISSUE TITLE
When downloading media, add an option to "Create New Folder" when selecting default directory

### ISSUE THREAD

**Issue by hary585** [ccrama/Slide#1606]
Slide version: Latest Play Store (Slide v5.3.3-alpha.4)
Android version: Android N Developer Preview 2

Just a feature that I think would be useful, if Slide can do this w/o root (I don't see why it couldn't), it'd be a helpful addition so I don't have to save Slide content into my default Downloads folder,

**Comment by l3d00m** [comment]
It isn't currently possible with the library. There is an issue for that though (https://github.com/afollestad/material-dialogs/issues/872).

**Comment by Alexendoo** [comment]
Would it be possible to use the system file picker? Or does that not work for sticking files places at a later date

**Comment by ccrama** [comment]
Done! Now there is a create button on the folder selection dialog
