### ISSUE TITLE
Add a line above the "Load x more" comments option

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1614]
Slide version: 5.3.3-alpha.4
Android version: 6.0.1

![20160428_184131](https://cloud.githubusercontent.com/assets/13410769/14906530/fb5a0152-0d70-11e6-97f0-b3f5e13c3f2a.jpg)

**Comment by ccrama** [comment]
Fixed both, good finds!

**Comment by okungnyo** [comment]
> Also, the "load x more"'s left margin doesn't line up with the comment's left margin.

What does this mean?

**Comment by Alexendoo** [comment]
@okungnyo Look at the left margin on the /u/makegr666 comment and Load 42 more, they're unequal
