### ISSUE TITLE
Title cut off of random post in /r/all

### ISSUE THREAD

**Issue by thebeardedchild** [ccrama/Slide#1618]
![screenshot_20160428-210616](https://cloud.githubusercontent.com/assets/7232861/14908153/02f17e42-0d88-11e6-9383-d37d6c064a69.png)
Slide version: 5.3.3-alpha.4
Android version: 6.0

I just came across a random post with the title cut off. When I entered the comments the full title appeared, but when scrolling through all links/posts it was cut.

**Comment by Nxt3** [comment]
Link to the post?

**Comment by thebeardedchild** [comment]
https://reddit.com/r/sports/comments/4gvxl3/someone_stole_a_14foot_royals_player_off_a/

**Comment by Nxt3** [comment]
May I ask what device you have?

**Comment by thebeardedchild** [comment]
Yeah! I was using a Moto X Pure 2015. So I don't think screen size caused it.. In fact I just browsed back to /r/sports and the issue didn't happen again. Maybe it was just a fluke while I was scrolling deep into /r/all... In which case sorry for the false alarm!!

**Comment by Nxt3** [comment]
Did you by chance change orientations at some point before stumbling upon that post? If you can't remember, try doing that. Start in portrait--go to landscape--then back again and see if the issue reoccurs.

**Comment by thebeardedchild** [comment]
I normally have it locked to portrait, but I just tried it out on sports and on all (scrolling back through to find it) and couldn't reproduce..

**Comment by Nxt3** [comment]
Hm. I'm going to close this issue--but if it happens again, make another issue or feel free to reopen this one. If I notice this happening, I'll do the same. :)

**Comment by thebeardedchild** [comment]
Good call! Yeah I shoulda known it was most likely a flukey thing. Thanks!

**Comment by Nxt3** [comment]
It might not be :P We will see. Nobody has reported that issue in quite some time so it's slightly surprising to see it pop up again. Who knows.

**Comment by Alexendoo** [comment]
I don't imagine it's a coincidence the text cuts of where the URL preview ends

**Comment by Nxt3** [comment]
This is still happening randomly in 5.4.

https://www.reddit.com/r/slideforreddit/comments/4u0kd1/found_another_one_of_those_cutoff_titles/

**Comment by ccrama** [comment]
This has been reported in other apps (even other Reddit apps), so I think this is not a Slide issue but rather an Android issue

**Comment by ccrama** [comment]
There were some underlying changes to the API in v24, along with an update to all the support libraries. Has anyone seen this in v5.4.3?

**Comment by ccrama** [comment]
Going to assume this is now fixed

**Comment by Nxt3** [comment]
Had this just happen in Nougat.

**Comment by Nxt3** [comment]
Not sure if there is much to do.

**Comment by ccrama** [comment]
There is really nothing we can do. It affects other apps as well, hopefully a future update to the RecyclerView fixes this. Don't know if we should keep it open

**Comment by Nxt3** [comment]
I'll just close it. Nothing you can do
