### ISSUE TITLE
Multiple posts can be opened if tapped in rapid succession

### ISSUE THREAD

**Issue by mastercoms** [ccrama/Slide#1621]
Tap a post and then tap another one (it is easier if you have two fingers ready). They will both open.

Slide should disallow any other posts to open when a post is being loaded.

**Comment by Nxt3** [comment]
Additionally, you can tap the same post twice quickly and it will open the same post twice.

**Comment by ccrama** [comment]
It really isn't possible to fix this, the onClickListener will always fire every time you click it

**Comment by Nxt3** [comment]
I think I can fix it. I'll get around to it later today.

**Comment by The0x539** [comment]
I've seen Mailbox fix it.

**Comment by Nxt3** [comment]
And now I have fixed it! Witness me!

**Comment by ccrama** [comment]
Praise be!
