### ISSUE TITLE
"Choose a time frame" option doesn't work properly for some subreddits [Video]

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1629]
Slide version: 5.3.3-alpha.5
Android version: 6.0.1

Video of the issue in action: https://streamable.com/ds6k

It doesn't work for /r/AndroidGaming for example and possibly other subs as well.

**Comment by okungnyo** [comment]
I would love if search in general was overhauled.

One thing (the only thing maybe) I like about the official Reddit app is searching. It looks and works exactly like searching on reddit.com.

**Comment by ccrama** [comment]
It does work, except there are no results avaliable and slide doesn't reset the view to remove the other items

**Comment by ccrama** [comment]
Fixed!
