### ISSUE TITLE
Search results page margins are different than those of the subreddit post listings page

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1630]
Slide version: 5.3.3-alpha.5
Android version: 6.0.1

Search results page: http://i.imgur.com/Hkh6rWL.jpg
Subreddit post listing page: http://i.imgur.com/egw7pJi.jpg

As you can see, the top margin for the search results page is larger than the one in the subreddit post listing page and the side margins of the search results page are smaller than the ones in the subreddit post listing page.

**Comment by Controless** [comment]
Issue still exists: http://i.imgur.com/VkZptEa.jpg

**Comment by Alexendoo** [comment]
Got it again, accidentally undid it in one of the other commits
