### ISSUE TITLE
Deleting a post returns you to your phone's home screen (+ other weird behavior) [Video]

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1633]
Slide version: 5.3.3-alpha.5
Android version: 6.0.1

https://streamable.com/gkyp

Another related issue: Deleting a post from a subreddit with only that post returns you to the first subreddit in the sidebar. It should return you to the subreddit in which you deleted the post from. Video: https://streamable.com/20z7.

I replicated both these issues numerous times and they had the same outcomes each and every time.

**Comment by ccrama** [comment]
Both are because of comment pane mode, I'll look into it

**Comment by ccrama** [comment]
Fixed, now it just shows [DELETED] like comments until you exit.
