### ISSUE TITLE
Left margin of the self-post text is not equal to the post title/info line left margin

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1634]
Slide version: 5.3.3-alpha.5
Android version: 6.0.1

http://i.imgur.com/Os4PHSw.jpg

Not sure if this is intentional or not, but it does look rather odd.

**Comment by okungnyo** [comment]
Maybe it helps at-a-glance readability?

**Comment by ccrama** [comment]
I fixed it a few commits ago, thanks!
