### ISSUE TITLE
Post redirection when attempting to go to subreddit [Video]

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1635]
Slide version: 5.3.3-alpha.5
Android version: 6.0.1

Video: https://streamable.com/kg6f

As you can see, clicking on a post, swiping back (comment pane mode), typing in a subreddit and pressing the keyboard Enter key redirects me to the recently opened post.

**Comment by ccrama** [comment]
Is agario the next sub in the list? I cannot reproduce this

**Comment by ccrama** [comment]
Oh the issue was clicking the search icon. Has been fixed!
