### ISSUE TITLE
Comment pane mode swiping bug [Video]

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1636]
Slide version: 5.3.3-alpha.5
Android version: 6.0.1

Video of bug in action: https://streamable.com/08yd

You are able to swipe to the comments from anywhere if you open up a subreddit from the sidebar. Ccrama confirmed that this was a glitch a few weeks ago.

**Comment by ccrama** [comment]
Fixed!

**Comment by ccrama** [comment]
Actually not really possible to fix this, I don't consider it a bug though. It works differently than the main activity because you can swipe to close it

**Comment by Alexendoo** [comment]
It's an inconsistency at least, if it's not possible to fix there perhaps enable swiping between them like that in the main view?

**Comment by Controless** [comment]
I was just about to ask that. It would be pretty awesome if that was added, I use this "glitch" a lot to my benefit.
