### ISSUE TITLE
UI unresponsive when downloading images

### ISSUE THREAD

**Issue by dulleh** [ccrama/Slide#1639]
Slide version:5.3.2.4
Android version:6.0.1 (nexus 5x)

Clicking the download button when viewing an image makes the app unresponsive for a moment or two - try swiping the image away immediately after pressing download or even just hitting the overflow button a bunch so that mutliple bottomsheets open up once it's done hanging.

Doesn't occur with gifs.

I could try fix this myself if pointed towards the onClick response of the download button.

**Comment by Alexendoo** [comment]
Listeners are:
https://github.com/ccrama/Slide/blob/master/app/src/main/java/me/ccrama/redditslide/Activities/MediaView.java#L137
https://github.com/ccrama/Slide/blob/master/app/src/main/java/me/ccrama/redditslide/Activities/MediaView.java#L362

**Comment by ccrama** [comment]
Fixed, made it run async now.
