### ISSUE TITLE
Just updated to 5.3.3, crash when I open comments.

### ISSUE THREAD

**Issue by krompus** [ccrama/Slide#1644]
Slide version: 5.3.3
Android version: 4.4.4

I get the "Slide has stopped" message when I open comments, or when I start to type in the "Go to subreddit" bar.

Shall I clear the app data and/or reinstall? I'd rather not wipe all of my settings if possible.

**Comment by ccrama** [comment]
Been fixed, was a KitKat bug with accent colors

**Comment by krompus** [comment]
Sweet! Thanks for fixing the "You" bar colour selection for Kitkat, by the way! :)

Looking forward to digging into the new features!

**Comment by ccrama** [comment]
You're welcome :)
