### ISSUE TITLE
Margin error on User Overview page

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1646]
Slide version: 5.3.3
Android version: 6.0.1

![screenshot_20160501-162013](https://cloud.githubusercontent.com/assets/13410769/14944964/21cc345a-0fb9-11e6-9e9f-f155fe4af249.png)

**Comment by Alexendoo** [comment]
Thanks, got it fixed, there was a bit of code that altered margins in profiles that was throwing me right off,  missed it the first time round
