### ISSUE TITLE
Comments since last visit count displays a '-' instead of a '+'

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1647]
Slide version: 5.3.3
Android version: 6.0.1

This post has 248 comments and the comments since last visit count is displayed as -6. It should be +6 since the comments count was 254 when going into the thread. Also, the count doesn't clear when clicking and going back. It's still displayed on the post listings page.

![screenshot_20160501-162951](https://cloud.githubusercontent.com/assets/13410769/14944993/3165012a-0fba-11e6-84e8-fc1974b0fd80.png)

**Comment by ccrama** [comment]
That means comments were removed, not a bug
