### ISSUE TITLE
Content type is not shown on this specific post

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1648]
Slide version: 5.3.3
Android version: 6.0.1

There is no 'self.leagueoflegends' displayed after the username. Perhaps is a margin/padding issue? [Post link](https://www.reddit.com/r/leagueoflegends/comments/4hca3h/janna_cosplay/)
![screenshot_20160501-165230](https://cloud.githubusercontent.com/assets/13410769/14945078/58c7a9f4-0fbd-11e6-8671-bbffef85960f.png)
![screenshot_20160501-165346](https://cloud.githubusercontent.com/assets/13410769/14945079/5dac4196-0fbd-11e6-9c0a-311d704957dd.png)

**Comment by ccrama** [comment]
I think that was just because the text was cut off and didn't wrap. I cannot reproduce but if you run into it again let me know!
