### ISSUE TITLE
Subreddit theme primary colour cannot be changed

### ISSUE THREAD

**Issue by krompus** [ccrama/Slide#1649]
I just updated to the latest version  5.3.3, android 4.4.4, and now the  subreddit theme primary colour cannot be changed. Changing the accent colour works, though.

**Comment by ccrama** [comment]
How are you setting it? Works fine for me

**Comment by krompus** [comment]
In the subreddit, top right, Subreddit Theme, Primary Color, Save. The colour applies, and hen reloads with the colour that was applied before.

I also tried through Settings, Subreddit Themes, same deal.

**Comment by ccrama** [comment]
That shouldn't happen still, I can't reproduce and haven't gotten any other reports of this. Do you mind resetting app data and let me know if that fixes it for you? Thanks!

**Comment by ccrama** [comment]
Are you clicking "Save"?

**Comment by krompus** [comment]
Yep. The first time I change it from default, it works, the second time, when it reloads, it stays with what I had assigned before.

**Comment by ccrama** [comment]
Cannot reproduce on any of my devices and haven't gotten any reports of this. Has to be something else going on

**Comment by krompus** [comment]
Strange. I guess I'll update to the new version when it's available, and if the issue persists, reset app data, and see if that fixes it.

**Comment by ccrama** [comment]
Closing for now, if this pops back up let me know and feel free to re-open!

**Comment by krompus** [comment]
Oh wait! I just tested some more, and it only happens when I try to set the primary colour to #000 black, from another colour (Black is my main colour).

I can switch reliably between other primary colours.

I switched my app-wide primary colour, and I could switch to Black, but I couldn't switch back to my primary colour.

SO!

That means that you cannot customise the subreddit colour to be the default colour, hahaha.

See if you can reproduce this?

**Comment by ccrama** [comment]
Oh yeah that is the issue! I told it not to change if you have the same main color, will fix

**Comment by krompus** [comment]
Noice.

**Comment by ccrama** [comment]
Fixed!
