### ISSUE TITLE
Add public multireddits to profile view

### ISSUE THREAD

**Issue by mjwhitta** [ccrama/Slide#1650]
It would be really cool if we could view a user's [public multis](https://github.com/thatJavaNerd/JRAW/blob/master/src/main/java/net/dean/jraw/managers/MultiRedditManager.java#L280). I feel this would fit well as a new tab to the right of "Gilded" when viewing a user's profile.

**Comment by okungnyo** [comment]
Why does the dev of JRAW do all this but stops short of actually making a Reddit app?

**Comment by l3d00m** [comment]
Because it's the sense of a **library**. It's so much more effort to make an actual app, see Slide as an example.

**Comment by okungnyo** [comment]
What other apps beslide Slide use this?

**Comment by Alexendoo** [comment]
Boost uses it, and I think @fbis251 has an app that does

**Comment by The0x539** [comment]
Making an app almost always requires a UI, and a lot of work goes into Slide's UI

**Comment by mjwhitta** [comment]
I actually may have thought of a better way to do this. I'm working on using `setOnLongClickListener()` with the "Multireddits" button in the drawer to prompt for a username. I've essentially copied code from the "Go to profile" button. My hope was to reuse the `MultiredditOverview` such that an optional username could be passed. `MultiredditOverview` would then check if a username is provided, and if so, it would load that user's public multis. If not, it would load the logged in user's multis. I hope that make sense. I have a quick question though @ccrama. What's the procedure on adding to `strings.xml`. Should I just use Google Translate for the other languages? Or is adding it to the default `strings.xml` fine? I've never worked with multiple languages in Android apps before.

**Comment by ccrama** [comment]
That sounds very cool @mjwhitta ! And just put them in strings.xml, we have crowd-sourced translations on Crowdin that will take care of the translations :)
