### ISSUE TITLE
Crash on selecting Reorder Subreddits from menu.

### ISSUE THREAD

**Issue by krompus** [ccrama/Slide#1651]
Android 4.4.4
Slide 5.3.3

**Comment by Controless** [comment]
Not occuring for me, perhaps it's a KitKat issue.

**Comment by krompus** [comment]
It worked before the latest updates. I couldn't say which, as it's been a week or two since I last reordered my subs.  Have you changed that part recently?

**Comment by Controless** [comment]
I'm not one of the code guys so I wouldn't know :s

**Comment by krompus** [comment]
Ahaha! You must be the PR, then! :D

**Comment by Alexendoo** [comment]
What device do you use @krompus?

**Comment by krompus** [comment]
Galaxy S3 with Cyanogenmod forever. :P

**Comment by ccrama** [comment]
Fixed!

**Comment by krompus** [comment]
Awesome! Thanks!
