### ISSUE TITLE
Could Slide make use of bottom navigation bars?

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#1654]
https://www.google.com/design/spec/components/bottom-navigation.html

Just thought I'd put it out there.

**Comment by Alexendoo** [comment]
Discover could, almost, we'd have to come up with some icons for it

**Comment by ccrama** [comment]
I don't think so, there is nothing as top-level as the subreddits are so it wouldn't be applicable 

As the spec states,

> Bottom navigation provides quick navigation between top-level views of an app.

**Comment by Alexendoo** [comment]
Ah yeah that, oh and it says don't do it if there are two, and not to slide between them so that's sorta us blown out the water

**Comment by ccrama** [comment]
Yeah, will close because we don't have enough options for a bottom bar
