### ISSUE TITLE
NSFW subs won't load (no age gateway) after logging out of an account

### ISSUE THREAD

**Issue by radagastly** [ccrama/Slide#1657]
Slide version: 5.3.3
Android version: 6.0.1

If you are initially not signed in (browsing as Guest) going to a NSFW sub will present you with the "mature content" warning and ask you if you want to continue. 

If you sign in to an account, and then sign out of it by browsing as Guest again, going to a NSFW sub will just load and present you with an empty page afterwards.

**Comment by ccrama** [comment]
Good find, have fixed!
