### ISSUE TITLE
Multireddits as collections bugs/suggestions

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1658]
Slide version: 5.3.4
Android version: 6.0.1
- [x] Accent color cannot be changed for multireddits when added as collections (EDIT: in 'Comment pane' or 'No subreddit tabs' mode)
- [x] Change all instances of /r/sub+sub+sub to /m/multi. Examples: http://imgur.com/a/pYDL1
- [x] Remove the /r/ before /m/. Examples: http://imgur.com/a/iwcRK
- [ ] 'Always show big pictures in this subreddit' option doesn't work
- [ ] 'Always show selftext previews in this subreddit' option doesn't work
  Suggestions:
- [x] Disable 'Submit' from the 3 dot menu, since it's not clear what subreddit you're posting to in the multireddit
- [ ] Add a right sidebar displaying the subreddits in the multireddit (exactly how it's implemented on multireddits page) (Duplicate of #1542)
- [x] In a /m/: the accent color for the "tabs" view mode for the selected tab is correct; however, the FAB ignores the accent color of the multi.

**Comment by Nxt3** [comment]
"Accent color cannot be changed for multireddits when added as collections" needs reproduction. I can change the accent colors for all of my multis with no problem.

**Comment by Controless** [comment]
Here's a video of the bug in action: https://streamable.com/vsgw

**Comment by Nxt3** [comment]
It only happens if you have View mode set to "No subreddit tabs" or "Comment pane".

**Comment by Controless** [comment]
Oh yeah, that could be it. I have it set to Comment pane mode.

**Comment by Controless** [comment]
I think @Nxt3 checked "Remove the /r/ before /m/." already but the issue still persists for the second image in this album:Remove the /r/ before /m/.

**Comment by Nxt3** [comment]
I marked it as done. I didn't realize that was an album. Will fix it later.

**Comment by Tensounder54** [comment]
This issue has been resolved and needs to be closed.
