### ISSUE TITLE
Tapping the image on a self-post won't open the comments

### ISSUE THREAD

**Issue by Canaaduh** [ccrama/Slide#1667]
Slide version: 5.3.4
Android version: 6.0.1
For example the selftext post about the next optional sub navigation on r/slideforreddit won't open the comments if the user touches the image. The only way to open the comments is to touch the title or the bottom bar. Touching the image will grey the post out but not open it.

**Comment by ccrama** [comment]
Fixed! It was preforming a fake click which was being checked for repetition (Slide will only let you open posts or content once every 700 ms), and was always being denied because it was the same ms of the original click
