### ISSUE TITLE
Layout when logged in

### ISSUE THREAD

**Issue by spezzino** [ccrama/Slide#1669]
Slide version: 5.3.4
Android version: 6.0.1

I have a strange problem. When loggin in with my username, I see [this layout](http://i.imgur.com/PHbXJUH.jpg)

But when using the app with guest mode, I see [this layout](http://i.imgur.com/XsByto0.jpg).
I dont know why I cant see image preview when logged in. Settings where left untpuched after app installation

**Comment by ccrama** [comment]
It's based on your Reddit account settings, if you have thumbnails always shown when logged in, you will see all of them. There really isn't a way around this in the API, unfortunately
