### ISSUE TITLE
Change global subreddit colour theme

### ISSUE THREAD

**Issue by nakamin** [ccrama/Slide#1673]
Slide version: 5.3.4
Android version: 6.0 Marshmallow

This is a feature request.
I want to be able to change the theme for all subreddits at once, not just for separate subreddits. Also would be nice to change the colour of the main slide out menu.

**Comment by Alexendoo** [comment]
Unless you've specifically styled a subreddit they all take on the settings In Settings → Main theme, as does the app drawer - the header takes on the primary colour, the body takes on the Base theme. Is there something extra on top of this you were wanting to be able to theme in particular?

**Comment by nakamin** [comment]
Yep I'm stupid thanks. Closing the issue.
