### ISSUE TITLE
Allow swiping away from anywhere on leftmost tabs of profile, messages, and moderation

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#1674]

**Comment by ccrama** [comment]
This adds another layer of complication to the views and I personally don't think that is needed, the user can always assume swiping won't close unless it's directly on the left side of the activity

**Comment by The0x539** [comment]
Can they, though? There aren't that many other places where it doesn't, only paginated albums come to mind.

**Comment by ccrama** [comment]
Yes, it acts the same way for every other paging view except for comments (for obvious reasons). Swiping back is not a top level action for any of the views except comments, so the way it's implemented now is the easiest to understand and most consistent with the non paginating views

**Comment by okungnyo** [comment]
I think it would be great to have swipe to close for everything.

**Comment by ccrama** [comment]
You can already swipe to close from anything @okungnyo , @The0x539  was requesting having swiping on the leftmost page always force close it like comments do, in addition to the current swipe to exit

**Comment by okungnyo** [comment]
I don't understand.

**Comment by ccrama** [comment]
You can already swipe to exit any view in Slide @okungnyo

**Comment by okungnyo** [comment]
No, I understood that part (I guess I never tried to swipe away from everything because Relay taught me not to).

I mean I don't understand "having swiping on the leftmost page always force close it like comments do".

**Comment by ccrama** [comment]
Ah, you can swipe from anywhere in the comment page to exit

**Comment by okungnyo** [comment]
I don't understand how they are two different things...??
