### ISSUE TITLE
Slide crashes on LG V10

### ISSUE THREAD

**Issue by Dezknight** [ccrama/Slide#1675]
Slide version: 5.3.4
Android version: 6.0

App started crashing after logging in and continues to do so with normal use.

**Comment by ccrama** [comment]
Do you have any specifics as to what causes the crash? There is not much info here to work with at all

**Comment by Dezknight** [comment]
When in settings under reorder subreddits it crashed after deleting a couple of subreddits. After that it crashes after browsing every few minutes.

**Comment by ccrama** [comment]
Does resetting app data fix it, and have you reported this crash?

**Comment by Dezknight** [comment]
How do I reset the app data? And Yes I did.

**Comment by ccrama** [comment]
Settings > Applications > Slide > Data > Clear

**Comment by Dezknight** [comment]
Alright no crashes so far now.

**Comment by ccrama** [comment]
If it happens again let me know, don't see any reports from LG v10's this version, though
