### ISSUE TITLE
When you press the Submit button from /r/all, /r/frontpage, /r/friends, /r/mod, or other special subs, the 'Subreddit' edittext should be cleared

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1676]
Slide version: 5.3.4
Android version: 6.0.1

It doesn't make any sense to submit to the /r/all, /r/frontpage, etc subreddits anyway since you can't even submit to those. I noticed that when you try to submit to a multireddit collection, the edittext is automatically cleared and doesn't display the multireddit name. The same functionality would be preferred for these special subreddits.

**Comment by ccrama** [comment]
Done!
