### ISSUE TITLE
Unusual "null" text appears when clicking on the "Title" edittext 

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1685]
Slide version:  a738202d652d4df3969d1b72960c971921d7176b
Android version: 6.0.1

I'm not really sure what that is supposed to be but it looks like a bug. It occurs everytime you click the title edittext on the "Selftext", "Image", and "Link" submit options. http://i.imgur.com/ShX9P5a.jpg

**Comment by ccrama** [comment]
I cannot reproduce. What are the exact steps to get it to occur?

**Comment by Controless** [comment]
As I see what the issue is. The null is shown because there is no "Submission text" entered for that subreddit (it's a subreddit setting). Ideally, it should be empty rather than displaying 'null'.

**Comment by ccrama** [comment]
OH gotcha. I'll look into it

**Comment by ccrama** [comment]
Fixed!
