### ISSUE TITLE
"Suggest title" button text should be bolded/white to match the other button styles

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1686]
Slide version: 8d8d330ee4bf1e54e72a25671c4b709c9a8a12c6
Android version: 6.0.1

http://imgur.com/a/OqvbI

You can see how the 'Suggest title' button looks different than the other buttons. It would better if it was bolded and made white like the others to match the same style.

**Comment by ccrama** [comment]
Done!

**Comment by Controless** [comment]
Oops I sent a pull request haha. I'll close that.
