### ISSUE TITLE
Phone back button/softkey issues

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1689]
Slide version: 8d8d330ee4bf1e54e72a25671c4b709c9a8a12c6
Android version: 6.0.1

The back button doesn't close these two dialogs:
- [x] The user not found: http://i.imgur.com/8faoUxh.jpg
- [x] The subreddit theme customizer: http://i.imgur.com/AgN0QmR.jpg

Other issue:
- [x] Pressing the back button on 'Backup successful!" screen removes the 'Close' button and you can't do anything to get out of that page unless you force close the app. The successful backup popup should close when the back button is pressed, the Close button shouldn't only disappear. Video: https://streamable.com/aa3i

**Comment by ccrama** [comment]
First two are on purpose

**Comment by ccrama** [comment]
Fixed the third
