### ISSUE TITLE
Gifs not loading

### ISSUE THREAD

**Issue by Pastignon** [ccrama/Slide#1696]
Slide version: 5.3.4
Android version: 6.0.1

Gifs are no longer loading (be it shadowbox, multireddits, frontpage...).

**Comment by ccrama** [comment]
If this is a recent thing, it is probably because an API is out and not a Slide issue

**Comment by Pastignon** [comment]
Roger ! Yes totally recent, been like this for the last 24 hours or so.

**Comment by ccrama** [comment]
Yeah nothing I can really do about it, check your network settings and try clearing out some data if possible

**Comment by ccrama** [comment]
Sounds like a network issue, if you find anything else out or it continues to happen, feel free to re-open!
