### ISSUE TITLE
Offline mode for no reason 

### ISSUE THREAD

**Issue by sutiive** [ccrama/Slide#1697]
Slide version: 5.3.4
Android version: 6.0.1

I seem to be ending off in offline mode without being able to return online without a reboot (from what I can tell). Everything else seems to be working fine - I can search the Web, do a speed test and also use reddit sync and relay fine. Love your app and will be buying the pro version soon but this is quite an annoying issue. Hope you can fix. Let me know if you require any additional info. 

Thanks.

**Comment by ccrama** [comment]
What happens if you click "Enter online mode" from the sidebar? Slide only goes offline if the network is off or you force it to go into offline mode

**Comment by ccrama** [comment]
Assuming this is not happening anymore. If you have more details or it happens again, let me know
