### ISSUE TITLE
Attempting to donate causes a crash

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#17]
The app appears to crash twice, first showing a glimpse of the previous screen then crashing to launcher.

logcat:
https://gist.github.com/Alexendoo/7c749eb62b906cfb4230

**Comment by ccrama** [comment]
That is because the app is not published yet. If you attempt to donate on a non-published version of the app, it will crash.

When I get it published, could you let me know if it still crashes? If so, there might be a deeper problem.

Thanks!
