### ISSUE TITLE
[Crashing Bug] Some Gfycat links crash entire phone OS.

### ISSUE THREAD

**Issue by GreenFlash5** [ccrama/Slide#1700]
Slide version: 5.3.4
Android version: 6.0.1

Not sure if this has been posted before.

I have a Moto E 2nd gen. Like I Said, not all, but some gifs tend to crash the phone, causing a reboot, I'm guessing its because the size of the gif?

Just to check if it was the power of my phone or OS, I downloaded "reddit is fun " and relay for reddit and both played the gifs smoothly. So my phone can handle them.

Love the app, but this is really starting to get annoying, I don't know when I'm going to press a gfycat gif that will cause a reboot.

**Comment by ccrama** [comment]
Nothing in the code can really force a reboot, sounds like a major bug in your ROM rather than an issue in Slide

**Comment by ccrama** [comment]
Closing because it's a device only bug. If anyone else has this or there is another pattern, feel free to re-open!
