### ISSUE TITLE
Permanently hiding posts now leaves gaps in post list

### ISSUE THREAD

**Issue by craftyguy** [ccrama/Slide#1702]
See screenshot below

Slide version: 5.3.4
Android version: 6.0.1

![screenshot_20160506-080113](https://cloud.githubusercontent.com/assets/1474209/15076905/d9710928-1360-11e6-8379-222b30ddaf95.png)

**Comment by ccrama** [comment]
Should be fixed now, moved to a new ItemAnimator

**Comment by craftyguy** [comment]
Actually, it doesn't look like it is fixed on 5.3.8

![screenshot_20160523-191219](https://cloud.githubusercontent.com/assets/1474209/15490133/7eda35ee-211a-11e6-8a00-644ff19b9a25.png)
