### ISSUE TITLE
Crashes when viewing picture

### ISSUE THREAD

**Issue by KonradIT** [ccrama/Slide#1704]
Slide version: 5.3.6Alpha2
Android version: Android N

Crash log:

https://gist.github.com/KonradIT/2d27fdc9d4ec9866c06bfbf9ea0bd31a

**Comment by ccrama** [comment]
That is 3 days worth of crash logs, which one is the one for the image? Thanks for the report!

**Comment by ccrama** [comment]
Found it, fixed!
