### ISSUE TITLE
Option for much more compact widget layout

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#1705]
Slide version: 5.3.6-alpha.2
Android version: 6.0.1

Maybe hide everything but title, make thumbnail smaller, and reduce margins?

**Comment by ccrama** [comment]
Done! Now there's a compact option in the creation screen

**Comment by The0x539** [comment]
What's it look like, since an update including it hasn't come out to my knowledge?

**Comment by ccrama** [comment]
Here it is http://imgur.com/ACu02xx

**Comment by The0x539** [comment]
Awesome.
