### ISSUE TITLE
Slide removes submissions from "Upvoted" menu when when unsaving it.

### ISSUE THREAD

**Issue by ente3000** [ccrama/Slide#1706]
This doesn't happen when un-upvoting (?) a submission from the "Saved" menu BTW.
Video: https://youtu.be/8MQUz1p6Djs

Slide version: 5.3.6-alpha.2
Android version: CyanogenOS 12.1.1 based on Android 5.1.1

**Comment by ente3000** [comment]
Just realized I put two "when" in the title ._.

**Comment by okungnyo** [comment]
._.

**Comment by Controless** [comment]
You can edit titles ya know.

**Comment by ente3000** [comment]
@Controless I'm on mobile ._.

**Comment by Controless** [comment]
Pretty sure to can use the wed version of github on your phone. At the bottom, click "Desktop version".

**Comment by ente3000** [comment]
@Controless I'm using an app called "OctoDroid"

**Comment by Controless** [comment]
Oh lol. Yeah, all the github apps are terrible in my opinion. I just use the web version on my phone browser.

**Comment by ente3000** [comment]
@Controless Sure, in functionality the website is way better, but in design... ;)

**Comment by The0x539** [comment]
@Controless The web version is *exactly* on par with the mobile apps in my experience.

**Comment by ccrama** [comment]
Fixed! Good find
