### ISSUE TITLE
Slide crashing on every NSFW picture

### ISSUE THREAD

**Issue by Canaaduh** [ccrama/Slide#1715]
Slide version:5.3.6 alpha 
Android version:6.0.1
Every NSFW picture currently crashes the app. The only fix is to disable the NSFW red preview and allow NSFW pictures to show.

**Comment by Soberat** [comment]
Slide version: https://github.com/ccrama/Slide/commit/0dfdc29fbf10039e1d5939ad1023bce14a23a34a
Android version: 6.0.1 May patch

Same here, log:
http://pastebin.com/CGW0nApt

**Comment by l3d00m** [comment]
Which alpha version are you on (Settings > About)? It should be fixed with the alpha.3

**Comment by Canaaduh** [comment]
Ah okay, thanks for the info.
