### ISSUE TITLE
(request) link to multireddit

### ISSUE THREAD

**Issue by notSokratis** [ccrama/Slide#1717]
Slide version: 5.3.4
Android version: 5.1.1

I'd like to see reddit.com/r/jokes+funny (displays jokes and funny subreddits) inside the app when I click it.

**Comment by ccrama** [comment]
Slide does this already, what happens when you try to open that?

**Comment by notSokratis** [comment]
It asks a browser to open it

**Comment by Controless** [comment]
@ccrama He means links like https://reddit.com/r/jokes+funny. They're not exactly multireddits but just 2 subreddits joined together. He wants them to open in the app, displaying both jokes+funny posts together, just like how the web version does it.

**Comment by ccrama** [comment]
If I open that link with Slide, it opens the subreddit jokes+funny, is that the intended behavior?

**Comment by Controless** [comment]
Yeah, it actually does open it with slide. My bad, didn't test it out first. Maybe there's something wrong with his app defaults or something, but it is definitely working.

**Comment by notSokratis** [comment]
Not working here, I'll uninstall to see what happens

**Comment by Controless** [comment]
Did it work?

**Comment by notSokratis** [comment]
Just reinstalled and now it's opening in Slide...weird...

**Comment by Controless** [comment]
Awesome :P You probably messed with the link settings or something, no idea haha. Glad it's working though!

**Comment by ccrama** [comment]
Glad to hear it!
