### ISSUE TITLE
Blank space appears in comments with code only content.

### ISSUE THREAD

**Issue by piyush-rvc** [ccrama/Slide#1719]
Slide version:5.3.4
Android version:5.1.1

Initial two lines are blank if the comment contains only code.

**Comment by ccrama** [comment]
Thanks for the report! Duplicate of #1514

**Comment by piyush-rvc** [comment]
@ccrama  I would like to fix it, where should I look into. It seems processing for comment containing code happens some where in addition to commentAdapter, which is causing the issue. Thanks!!

**Comment by piyush-rvc** [comment]
@ccrama  also, why is comment display as firstTextView and CommentOverflow? IMO, using only CommentOverflow would do the job.

**Comment by ccrama** [comment]
@piyush-rvc  thank you! And it's like that because we don't have to re-inflate a new first textview every time the view is displayed, which makes it much faster. The CommentOverflow is only touched when needed, which makes scrolling much faster
