### ISSUE TITLE
Some Gyfcat Links Not Playing

### ISSUE THREAD

**Issue by ainen** [ccrama/Slide#1721]
Slide version: 5.3.6-alpha.4
Android version: 6.0.1

Some Gyfcat links will open fine while others do not. I have attached a video that shows this behavior.

[https://www.youtube.com/watch?v=OBRb9WcUSM4](https://www.youtube.com/watch?v=OBRb9WcUSM4)

**Comment by ccrama** [comment]
Interesting, seems to only be giant.gfycat links as those can get up to 25 or 50mb each, and are too big for the buffer to handle. I'll look into it!

**Comment by ccrama** [comment]
Fixed! Great find
