### ISSUE TITLE
swipe up in gallery to get to comments

### ISSUE THREAD

**Issue by boyblunder** [ccrama/Slide#1735]
Slide version: 5.3.6.1
Android version: 6.0.1

this is a feature request, to be able to swipe up from an image/GIF/etc to access the comments. the current implementation is to swipe from the left, then click the text to go into the comments. implementing this would save a step.

Relay for Reddit has a "message icon" that you can tap within a gallery to access comments, and I think that having this would be more in-line with Slide's gui-awesomeness of swiping everywhere to get to where you need to be.

**Comment by The0x539** [comment]
I'm not *personally* sure this works well with the current UI paradigm, opened content isn't associated much with where it was opened.

**Comment by Nxt3** [comment]
How would this work if you have vertical albums enabled?

**Comment by ccrama** [comment]
Ah true, would not be possible then, unfortunately

**Comment by ccrama** [comment]
I think that is closeable now, the vertical album issue is pretty significant

**Comment by okungnyo** [comment]
Maybe when Force Touch becomes available.
