### ISSUE TITLE
Scrolling down page marks unread posts as read

### ISSUE THREAD

**Issue by danwic** [ccrama/Slide#1736]
Slide version: v5.3.6
Android version: 6.0

**Comment by danwic** [comment]
If you scroll past an unread post and then come back to it, the title is grayed out.

**Comment by ccrama** [comment]
Turn off scroll to mark read in Settings > History

**Comment by danwic** [comment]
Ah damn. I'm dumb after all. Thank you for the quick response and keep up the good work!

**Comment by ccrama** [comment]
Haha no worries. Thank you!
