### ISSUE TITLE
right swipe shows subreddit sidebar info of next subreddit from subscription list

### ISSUE THREAD

**Issue by slio** [ccrama/Slide#1738]
Slide version: 5.3.6.1
Android version: CM 11S

1. Go to a subreddit from your list.
- swipe right for sidebar, it will load correctly with sidebar subreddit information.
- click on any post
-- swipe right again for sidebar, it will show correct subreddit name but information will be of next subreddit from your subscription list.

2. While testing above issue it made me realise sidebar on /r/android is closing itself not waiting fore to hit back or click anywhere on screen.

**Comment by ccrama** [comment]
Fixed! Good find :)
