### ISSUE TITLE
Load more posts sometimes doesn't work

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#1741]
When there's more than about 5,000 more posts to be loaded, the 'load more posts' button does nothing.

**Comment by ccrama** [comment]
That's a Reddit API limitation, not much I can do about it

**Comment by alexsmithfanning** [comment]
Hmm. Could you load 100 at a time?

**Comment by ccrama** [comment]
It preloads images, so that would take a ton of user data, so probably not, sorry
