### ISSUE TITLE
Please Remove "get pro" plemp from f-droid version

### ISSUE THREAD

**Issue by theScrabi** [ccrama/Slide#1744]
Hallo,

I want to like your app, but I hate that every second option you click on makes the "get the pro version" pop up. NO I'm not getting the pro version, I don't use google anyway. So I'm not able to even get it. I know why you would do that, but could you please consider an f-droid version where you remove that since there are more users like me out there. You could also consider a market model like the [Conversations](https://github.com/siacs/Conversations) app. If you do than I would also consider spending something ;)

rgds Schabi

**Comment by ccrama** [comment]
Good ideas, merging with #1535 !
