### ISSUE TITLE
"Popular" in Discover doesn't show more than 25 results

### ISSUE THREAD

**Issue by Soberat** [ccrama/Slide#1745]
Slide version: https://github.com/ccrama/Slide/commit/163f486abdf429b57f20f15d34332e135e41762a
Android version: 6.0.1

Shows an endless spinner.

Also, a small thing I was thinking about, but not sure if it's possible - filter the trending and popular results using the subreddit filters, ex. I have the_donald in filters, so it should be filtered out of trending/popular.

**Comment by ccrama** [comment]
Good find! Fixed. And also did the filtering as well!
