### ISSUE TITLE
Weird settings transparency bug

### ISSUE THREAD

**Issue by Soberat** [ccrama/Slide#1754]
Slide version: https://github.com/ccrama/Slide/commit/f138c7812d6575ba9fb17849ed0622a6082b1abc also happening on regular builds/GP
Android version: 6.0.1

I think it will be the best to show it in a video, happens only with Backup activity. Look at the bottom part when backup activity is opened:
https://drive.google.com/file/d/0BwivIOVNk_KjRDg0c1ZNMmpqVW8/view?usp=sharing

**Comment by ccrama** [comment]
Fixed, good find!
