### ISSUE TITLE
Inform about quarantined subreddits

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#1755]
When you try to view quarantined subreddits through the API, you get a 403 error. Currently Slide displays a generic Not Found error if a 403 error occurs. 
If you opted in to view a quarantined subreddit on the website, you can view it through the api as well (You have to do that for each quarantined sub).
 
We should display a message that informs the user about that, with a link to the subreddit that opens external. 

[Source for the API related stuff](https://www.reddit.com/r/redditdev/comments/3fx3gt/quarantined_content_will_be_unavailable_through/) 

[The request in our subreddit](https://www.reddit.com/r/slideforreddit/comments/4j3s18/view_quarantined_subs/)

**Comment by ccrama** [comment]
> subreddits will only be available to authenticated users who have opted-in to view that content on reddit.com.

Unfortunately, that means they have to opt in on the website and then return to Slide and can view it. This cannot be done in app AFAIK

**Comment by l3d00m** [comment]
Yeah, my request was to show a message with a link that opens external :p

**Comment by ccrama** [comment]
How do I know if the 403 was because of quarantine and not removal?

**Comment by l3d00m** [comment]
Jraw has a method for that: https://github.com/thatJavaNerd/JRAW/commit/311e4fa66a56c20c8a045b632db8f12f0f4a95a7

**Comment by ccrama** [comment]
That's after a successful request, though, when the user has already accepted

**Comment by l3d00m** [comment]
Well, I've missed that. I don't think theres a way to distinguish between private and quarantined then.

**Comment by ccrama** [comment]
Yeah, there isn't unfortunately. I think this is closeable now
