### ISSUE TITLE
Subreddit could not be found

### ISSUE THREAD

**Issue by CallanIwan** [ccrama/Slide#1756]
Slide version: 5.3.6.1
Android version: 6.0.1

I get the subreddit could not be found upon starting slide, browsing to random subreddit. Exiting through home button. When returning to the app I get the subreddit not found. Closing the app and starting it again fixes it. Happend multiple times.

**Comment by ccrama** [comment]
This is related to other connection issues, which should be alleviated with the next update. If the Reddit API could not be reached or your network was not active, it could also cause this issue and it is not related to Slide if so.
