### ISSUE TITLE
Duplicate posts

### ISSUE THREAD

**Issue by andrewbitting** [ccrama/Slide#1757]
Slide version: 5.3.6.1
Android version: 6.0.1

Slide sometimes shows duplicate posts fixed by scrolling them in and out of view or refreshing.  I think it has something to do with hiding other posts.

**Comment by ccrama** [comment]
Should be fixed in the next update

**Comment by andrewbitting** [comment]
If you meant 5.3.8, it rid not fix it

**Comment by ccrama** [comment]
I cannot reproduce then, can you give more details on how this occurs

**Comment by andrewbitting** [comment]
The only way for it to happen is to just browse and hide posts.  Really
that's the only thing I think that triggers it, sometimes it happens,
sometimes it doesn't. It's not like every time I hide a post a duplication
occurs, it's just completely random.

**Comment by ccrama** [comment]
Is there a correlation between getting close to the bottom of the loaded posts (while it loads more) and hiding?

**Comment by andrewbitting** [comment]
No, not that I can tell.  I wish I could help more, but I honestly can't
find any cause other than hiding.  Oh, and it's fixed by just scrolling
past the duplicates then back up.
On May 19, 2016 11:15 PM, "ccrama" <notifications@github.com> wrote:

Is there a correlation between getting close to the bottom of the loaded
posts (while it loads more) and hiding?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/ccrama/Slide/issues/1757#issuecomment-220507516>
