### ISSUE TITLE
When commenting, instead of displaying the users comment, it duplicates the top comment

### ISSUE THREAD

**Issue by goodpricefriedrice** [ccrama/Slide#1759]
As described by /u/All_for_anonymous here https://www.reddit.com/r/slideforreddit/comments/4j426y/since_536_when_i_reply_to_a_comment_it_creates_a/

The users comment is still posted, but they dont see theirs, instead the top comment gets shown again. 

Slide version: Been occurring for a while now (the fact that its been occurring for so long made me assume it was on my end, but the above reddit post confirmed its not just me)
Android version: 6.0.1

**Comment by ccrama** [comment]
Have never seen this and cannot reproduce, what are the steps for reproduction? I reply to about 100 messages a week and hasn't happened to me

**Comment by goodpricefriedrice** [comment]
Video showing the issue: https://onedrive.live.com/redir?resid=ED3E99BC7F8F45FF!660595&authkey=!AH-mCG1eRg5FzXw&ithint=video%2cmp4

**Comment by ccrama** [comment]
This happens when the comment below is collapsed

**Comment by ccrama** [comment]
Fixed!
