### ISSUE TITLE
Extra, automatic swipe occurs when swiping away from image in comments

### ISSUE THREAD

**Issue by thebeardedchild** [ccrama/Slide#1760]
Slide version: 5.3.7
Android version: 6.0

When viewing a thread's comments, then opening an image in someone's comment, then swiping away from that image, an additional swipe immediately occurs that takes me back to the subreddit I was viewing (exits the comments page inadvertently).

Here's a gfycat showing this if it helps: https://gfycat.com/LeanInconsequentialEeve

**Comment by ccrama** [comment]
Has been fixed, please update to the latest version!

**Comment by thebeardedchild** [comment]
That fixed it! However I just noticed a related issue when viewing a multireddit. When viewing the multi, then viewing an image, swiping back will take me back to the Reddit front-page. 

So it's the same problem, just in a different place I guess..
