### ISSUE TITLE
Sort base themes by darkness

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#1763]
Light
Sepia
Dark blue
Dark gray
AMOLED with contrast
AMOLED black

**Comment by Controless** [comment]
I'd like to add on to this instead of creating a new github issue: Sort the 'Content to hide on /r/subreddit' based on types. For example, instead of the current order, it should be something like this or something similar:

Images
Albums
GIFs
Videos
Links
Selftext
NSFW content

**Comment by ccrama** [comment]
I did @The0x539 's

**Comment by ccrama** [comment]
Closing, @Controless if you feel it's important enough, feel free to make another issue!
