### ISSUE TITLE
In multireddit, swipe away from image swipes back to Frontpage

### ISSUE THREAD

**Issue by thebeardedchild** [ccrama/Slide#1765]
Slide version: 5.3.7
Android version: 6.0

Hey there, I just posted [this issue](https://github.com/ccrama/Slide/issues/1760) yesterday, and it was promptly fixed! Although I just noticed a similar issue. When browsing a Multireddit, then viewing an image, swiping out of that image will swipe me back to the Reddit frontpage (then entering the multi again will reload everything back to the beginning).

I uploaded [another gfy](https://gfycat.com/ScaredDeadlyAngora) for you in case it helps! Thanks you guys!

**Comment by ccrama** [comment]
Fixed, thanks for the report!

**Comment by thebeardedchild** [comment]
@ccrama This bug seems to persist in the new 5.3.8 update

**Comment by ccrama** [comment]
Fixed for real this time
