### ISSUE TITLE
Crash when clicking Manage offline content > Autocache time

### ISSUE THREAD

**Issue by krompus** [ccrama/Slide#1766]
Slide version: v5.3.7
Android version: 4.4.4

**Comment by ccrama** [comment]
I'm not getting a crash. Please report it through the crash dialog on your device.

**Comment by krompus** [comment]
I did so two hours ago. :)

**Comment by ccrama** [comment]
I'll fix it from there then, thanks

**Comment by ccrama** [comment]
Actually what theme are you on? The theme you have selected could not be found

**Comment by krompus** [comment]
Theme? Which theme? You mean for Android? I use [JellyRevenge](https://f-droid.org/wiki/page/com.jelly.theme.revenge), available on FDroid. It's the best Holo theme in my opinion (poo Material Design, I like my #000, dammit!)

In Slide, I switch between `AMOLED black` and `AMOLED with contrast`.

**Comment by ccrama** [comment]
Ah I meant the Slide theme. What accent color?

**Comment by krompus** [comment]
Ah. The accent colour I am using is [#00B8D4.](https://lut.im/urk0xA50yG/3wEtP7h08iipwRQo.png)

**Comment by ccrama** [comment]
Has nothing to do with that, the crash was because it couldn't load the theme and didn't know what color to make it. 99% sure it's related to KitKat

**Comment by krompus** [comment]
Ah, alright. I'll fiddle with it and try resetting theme preferences, etc.

You mention KitKat being the culprit quite often. Do you not like KitKat or perhaps you find it buggy? Maybe Slide is not optimised for it?

**Comment by ccrama** [comment]
No, KitKat is missing tons of libraries and resources avaliable in Lollipop, and some API features do not work in KitKat. It is only used by less than 7% of my users, and not my top priority

**Comment by krompus** [comment]
Ah, gotcha. I was going to say, KitKat is used by [~30% of users](https://developer.android.com/about/dashboards/index.html), but I guess you can see the percentages for people who use Slide specifically.

I'm pretty sure I can load Lollipop onto my trusty Galaxy S3; I'll look into it, and try to stop bothering you with Kitkat troubles. :)

**Comment by alexsmithfanning** [comment]
They have CyanogenMod 13 Nightlies for most of the S3 variants.

[Here's the international model.](http://download.cyanogenmod.org/?device=i9300)

**Comment by krompus** [comment]
Hahaha, I stupidly forgot my TWRP password, so until I figure out how to get around that, I've locked myself out of flashing :P

**Comment by alexsmithfanning** [comment]
You could use Flashify to overwrite the current version of TWRP you have and the password would be deleted. I think.

**Comment by krompus** [comment]
Oh, neat! Thanks for the tip; I'll look into it!

**Comment by alexsmithfanning** [comment]
Or you could flash a regular CyanogenMod recovery with Flashify and it would definitely work since that recovery doesn't support a password.

**Comment by krompus** [comment]
Sweet. I've only ever flashed once, and that was from stock, and I wiped everything when I did. I'm pretty nervous about losing all of my data. Are there any good guides on how to do this without exploding my phone?

I have Titanium Backup, but I'm not sure what to keep and what to trash; I'd rather not preserve old crap I don't need anymore. The interface is also a little...ehhh.

If you'd like, we could take this conversation to IRC; it's offtopic, and I'm sure `ccrama` would rather not get pinged for no reason. :)

I'm `krompus` on Freenode.

**Comment by alexsmithfanning** [comment]
Just message me on Hangouts. You know my email.

**Comment by krompus** [comment]
Yay! I just upgraded to CyanogenMod 12.1, Android Version 5.1.1, and so I won't be bothering you with any KitKat bugs anymore! :)

**Comment by ccrama** [comment]
Sounds good! And now it won't theme on KitKat
