### ISSUE TITLE
Option to swipe left to return to the comment section when subreddit tabs are turned off

### ISSUE THREAD

**Issue by cyalins** [ccrama/Slide#1769]
Slide version: 5.3.7
Android version: 6.0.1

**Comment by ccrama** [comment]
This is what the comment pane layout does

**Comment by cyalins** [comment]
The comment pane layout doesn't seem to let you swipe back into the comments, though. You can return to the comments by tapping the post again, but not by swiping left.

**Comment by ccrama** [comment]
Oh, that is on purpose. If you havent opened any comments, there is nothing to swipe to
