### ISSUE TITLE
Add +FAB to Subreddit Theme Settings

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#177]
![79668d34-6f71-11e5-9e2a-ed925006b7dd](https://cloud.githubusercontent.com/assets/7350294/10595774/e4c671a2-76a1-11e5-8b51-5824dfe9b83c.png)
Image taken from #36, the original per-subreddit dialog thing thing.

**Comment by The0x539** [comment]
@ccrama where was that FAB-to-toolbar morph library you were mentioning back when we were working on what the post looked like in the comments screen? It could be useful here.

**Comment by ccrama** [comment]
Fab would not work here, as it takes the dataset from the subs you have changed colors for already.

**Comment by The0x539** [comment]
...but this is for adding to the dataset
