### ISSUE TITLE
Weird bug when clearing out read posts

### ISSUE THREAD

**Issue by Chromelon** [ccrama/Slide#1770]
I used slide 5.3.7, Android 6.0.1

![Here's the issue](https://goo.gl/photos/x5RPEkfiomAPpHDe8)

**Comment by Chromelon** [comment]
Sorry, image link was wrong. 

https://photos.google.com/photo/AF1QipNpxvVBpV54BxkQ4q0Qv617ZwqC2vnmlPMnwE_C

**Comment by ccrama** [comment]
Link doesn't work

**Comment by Chromelon** [comment]
http://i.imgur.com/ATs3MDP.png

Ugh. Uploading photos is apparently not my thing today.

**Comment by ccrama** [comment]
How can I reproduce this?

**Comment by Chromelon** [comment]
I'm not sure. It seems to happen at random, but it usually happens when I
am at the bottom of a list and hold the clear button. I'll give you an
update of what happened exactly if I can reproduce again.

**Comment by ccrama** [comment]
Should be fixed now, moved to a new ItemAnimator
