### ISSUE TITLE
Can we please have commas for large numbers on Subscriber counts and in link/comment karma?

### ISSUE THREAD

**Issue by miladmaz12** [ccrama/Slide#1771]
This is not an issue just a minor adjustment.

**Comment by Nxt3** [comment]
It's reported how Reddit reports it.

**Comment by miladmaz12** [comment]
So there isn't a way to make this happen?

**Comment by Nxt3** [comment]
I could see about it. Just so used to it not having commas. It's how all Reddit clients report it to my knowledge.

**Comment by Controless** [comment]
Reddit is Fun uses commas btw.

**Comment by ccrama** [comment]
The issue with this is in Europe, it's a period and not a comma. Probably won't be doing this because of that

**Comment by miladmaz12** [comment]
But I am in the United States and I'm talking about [this](https://imgur.com/SgAuY15)

**Comment by ccrama** [comment]
Yes, but that would not work for Europeans

**Comment by miladmaz12** [comment]
Oh I see. Alright, I'm going to close this, if it's ok with you.

**Comment by ccrama** [comment]
Yeah it's ok, good suggestion though!

**Comment by Nxt3** [comment]
I'm pretty sure we could do this by using `Locale.toString()`; it takes in the default Locale (so if you were European, it would presumably show periods). 

The issue I have with this is I don't care for commas showing up for the score. :|

**Comment by Controless** [comment]
Yeah, it wouldn't look good on the score but it would greatly help for the subscriber number in the sidebar (hard to differentiate 800000 and 8000000 at the first glance).

**Comment by okungnyo** [comment]
Couldn't the region be detected and if it is Europe, then use dots instead of commas?

**Comment by ccrama** [comment]
If there was a way to region detect, yes, but there isn't really

**Comment by okungnyo** [comment]
That's too bad. And having a setting toggle for something so little as this would be way too much, I assume.

**Comment by Nxt3** [comment]
@ccrama You could use `Locale.toString()` like I said :P It does exactly that.

**Comment by ccrama** [comment]
@Nxt3 exactly, but you need to know the current locale first, which is the issue

**Comment by Nxt3** [comment]
@ccrama `Locale.toString(Locale.getDefault(), "%d", score)` will do that. The default Locale is constructed statically at runtime for Slide's process from the device's system settings. If the user is using a European locale on their device--then they'll get the "." instead of ",".

**Comment by ccrama** [comment]
Ah didn't know that! Might look into it again then

**Comment by ccrama** [comment]
It's done for subscriber counts, will *possibly* be done for other numbers in the future with @csdodd's PRs
