### ISSUE TITLE
Somehow manage frontpage subscriptions via "manage subreddits"

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#1773]

**Comment by ccrama** [comment]
Done, now you have the option to remove or remove/unsubscribe, and add or add/subscribe!

**Comment by okungnyo** [comment]
Wait, this wasn't possible until now??

That's like a photo app not having the ability to delete photo tags!

**Comment by l3d00m** [comment]
So, not really important?

**Comment by ccrama** [comment]
@okungnyo  you could do it one at a time, but not a bunch at once
