### ISSUE TITLE
Comments with only code cannot fully collapse if the setting is enabled

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1774]
Slide version: 5.3.7
Android version:6.0.1

**Comment by Nxt3** [comment]
You can collapse them, but you can't press on the body to do so; you'll have to press more towards the username/info line of the comment. Pretty sure this is a duplicate of #1049

**Comment by ccrama** [comment]
Fixed!

**Comment by JStav** [comment]
I just faced this issue on this thread: [https://www.reddit.com/r/softwaregore/comments/4kmwcs/im_just_casually_browsing_the_web_using_internet/](url). 

The first reply to the top comment has a  pre tag with a code tag and tapping the comment after the code doesn't let me collapse it. Tapping the comment before the code works just fine.

**Comment by ccrama** [comment]
That's a separate issue already on the bug tracker. Thanks for reporting it, though!

**Comment by JStav** [comment]
Oh perfect, I must have missed it. Thanks!
