### ISSUE TITLE
Images fail to load in shadow box

### ISSUE THREAD

**Issue by Kruger2147** [ccrama/Slide#1776]
Slide version: 5.3.8
Android version: 6.0 Nexus 6

50% of images and gifs fail to load properly in shadow box mode. I usually have to swipe it closed and reopen several times before it works, or I give up and move on.

Sources include imgur, gfycat, Instagram and Tumblr

**Comment by ccrama** [comment]
Does it show a loading bar? And if you could find a pattern to the images, that would be great

**Comment by Kruger2147** [comment]
Sometimes the loading bar starts to load then gives up, other times no losing bar shows up at all. I'll try and find a pattern.

**Comment by ccrama** [comment]
Should be fixed now, replaced all the code with the same code that runs in the usual Image/Gif view!

**Comment by Kruger2147** [comment]
That seems to have fixed it. Thanks for the quick turn around!

**Comment by ccrama** [comment]
Glad to hear it! You're welcome
