### ISSUE TITLE
Duplicate posts

### ISSUE THREAD

**Issue by andrewbitting** [ccrama/Slide#1777]
Slide version: 5.3.8
Android version: 6.0.1

Still has duplicate post issues, not fixed in latest update

**Comment by andrewbitting** [comment]
Oh, and it happens due to hiding posts

**Comment by ccrama** [comment]
This is in response to your other thread, but if hiding was the only issue, I just put in an extra check to force it to redraw from the dataset, because the actual posts weren't duplicated, just the post content was read from the wrong place
