### ISSUE TITLE
N-style full width list view

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1780]
Someone on the subreddit was saying they'd like to see the full-width style list view. I would add a bit of spacing between the items though.

[See what I'm talking about here](http://i.imgur.com/JbnX82t.jpg).

What are the thoughts on this? I could do it if you decided you liked it, @ccrama.

**Comment by okungnyo** [comment]
That looks insanely good.

Is it a mock up or a real app?

**Comment by l3d00m** [comment]
Looks like a screenshot from the material design specifications.

**Comment by Nxt3** [comment]
@l3d00m is correct. From their specs. Whether or not I will implement this is up to ccrama. :P

**Comment by Nxt3** [comment]
I wasn't going to make it an option--this was going to replace the current style of list view. Thoughts? I could do it as an option if you wanted.

**Comment by ccrama** [comment]
I'd have to see what it looks like first. I personally like the current list view but that could change

**Comment by Nxt3** [comment]
Alright, I'll work on it and post back here once I have it styled. :)

**Comment by Nxt3** [comment]
Here's what I got. The downside is that is the thumbnails larger--we need vector images of the "hide", "nsfw", and "web" drawables. Not sure how to go about that.

I think if we make this the default new list view--we should make the thumbails for the normal card views use the wider styled thumbail--I think it looks better and less "boring". Don't be a square.

![screenshot_20160521-153822](https://cloud.githubusercontent.com/assets/2940826/15450469/3dec65fe-1f6a-11e6-8e9a-074941f1c0f7.png)

**Comment by lbds137** [comment]
Ooh, I like this a lot! Reminds me of why I liked Relay's list view - this is quite similar I think, and that's a good thing.

**Comment by ccrama** [comment]
Looks awesome, done with your last PR @Nxt3
