### ISSUE TITLE
When you switch from account A to account B and comment, it displays the name as account A, but upon refresh corrects itself [video]

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1782]
Slide version: 5.3.8.1
Android version: 6.0.1

It also comments on what your old account commented previously, but upon refresh fixes itself.

https://streamable.com/97rn

**Comment by ccrama** [comment]
Renove your accounts and re add them, was a bug in a previous version of Slide while adding an account

**Comment by Controless** [comment]
Unfortunately the same issue still persists after doing so.

**Comment by ccrama** [comment]
I switch between accounts a lot and haven't gotten run into this. Do you have any specific way to reproduce it

**Comment by Controless** [comment]
Not sure if it helps, but I just comment with account A, switch to account B, and then comment on the same thread and it shows account A's name until I refresh. Maybe someone else can try reproducing this so I know that it's happening with other users as well.

**Comment by ccrama** [comment]
Actually that has nothing to do with accounts, it's just duplicating the first comment every time you comment

**Comment by Controless** [comment]
Great! I'll close this issue then.
