### ISSUE TITLE
Moderator related bugs/suggestions

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1783]
Slide version: 5.3.8.1
Android version: 6.0.1

## Feature Request

- [x] Add ability to spam posts/comments (_[JRAW Support](https://github.com/ccrama/JRAW/blob/master/src/main/java/net/dean/jraw/managers/ModerationManager.java#L197)_)

- [x] Add ability to distinguish posts (_Not yet supported by JRAW_)

- [x] Add ability to lock posts (_Not yet supported by JRAW_)

- [x] Add ability to set posts to "Contest mode" (_Not yet supported by JRAW_)

- [x] Add ability to ban users

## Enhancement

- [x] When removing a comment/post, don't actually remove any info, just add "Removed by (moderator name)" in at the end of the info line. Currently when you remove a comment/post, all the info is deleted and there is no way "Reapprove it". Reddit is fun does this (http://i.imgur.com/2a31Voq.png, http://i.imgur.com/pdcU2Ts.png) and it helps us mods out very much. This way, we can review comments/posts deleted by other mods and reapprove them if we have to. It also shows who remove the comment/post, which is again very useful for mods who moderate large subreddits.

- [x] Maybe give an option to remove the "Are you sure" pop-ups for Removing/Approving posts/comments? As a default mod, I have to sift through dozens of posts daily and this pop-up wastes a lot of my time (and I'm sure it does for other mods as well) and it would be great it was optional somehow. It really would make a difference.

## Strings

- [x] Position approve/remove for posts/comments consecutively (having items inbetween them seems a bit odd)

- [x] Remove the "comment" ending off of "Approve comment", "Distinguish comment", and "Sticky comment". We mods already know that we're performing comment moderator actions so this is redundant. On posts, it already is like this (approve, remove, pin). Also, it doesn't display "Remove comment", only "Remove" so that's the way I propose they should all be.

- [x] Rename "Pin" to "Sticky" (for posts). It already uses the word "Sticky" for comments so consistency would be great.

## Bug

- [ ] When you remove an approved post, it still shows the tag "Approved by (username)" next to the title.

**Comment by ccrama** [comment]
Now it'll show "Removed by ___" or "Approved by ___" for comments/posts that have been removed or approved!

**Comment by ccrama** [comment]
Removed "Are you sure?" dialogs from all the buttons

**Comment by ccrama** [comment]
Added spam support

**Comment by ccrama** [comment]
Added distinguish (it actually was already in JRAW)

**Comment by ccrama** [comment]
Added contest mode and locked to the JRAW api and to Slide. Closing now! If you have any other suggestions, feel free to make a new issue

**Comment by Nxt3** [comment]
You closed https://github.com/ccrama/Slide/issues/2021?

**Comment by ccrama** [comment]
Just a note, contest mode status is NOT available through the API, once it is we can add that in

**Comment by Nxt3** [comment]
Gotcha.
