### ISSUE TITLE
This link opens as an image, not a GIF

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1784]
Slide version: 5.3.8.1
Android version: 6.0.1

https://reddit.com/r/funny/comments/4kdbp7/cya/
https://i.imgur.com/CQglbo4.jpg

**Comment by ccrama** [comment]
That means the Imgur website is not returning animated or gif as the content type in the header, so it's probably a bug on their end

**Comment by ccrama** [comment]
It is a bug with the website, it's returning content-type of text-html, instead of image-gif or animated. Closing now
