### ISSUE TITLE
Tapping on subreddit name at top of application no longer scrolls to the top

### ISSUE THREAD

**Issue by craftyguy** [ccrama/Slide#1785]
Slide version:Slide v5.3.8
Android version: Android 6.0.1 / CyanogenMod 13

Starting with the update to 5.3.8, when scrolled down in a view (e.g. front-page or a subreddit), if you tap on the name of the view at the top of Slide, nothing happens. Previous versions of Slide would cause the view to scroll back to the top.

**Comment by Controless** [comment]
You can still tap to the right of the name (empty space) and it will scroll to the top.

**Comment by craftyguy** [comment]
That doesn't seem to do anything for me. The space next to the name will either switch me to the next tab or do nothing. I've attached a screenshot, its possible I broke something or set myself up for this when I was configuring slide's layout a few weeks ago when I first installed it

![screenshot_20160521-095808](https://cloud.githubusercontent.com/assets/1474209/15449715/d0d865e6-1f3a-11e6-9f61-b87ac22033ae.png)

**Comment by Controless** [comment]
Ah, this seems like a bug. Tapping the name to scroll to the top works fine with no subreddit tabs and comment pane mode, but doesn't work in the subreddit tabs mode.

**Comment by craftyguy** [comment]
Cool, yea I prefer this layout :P

Let me know if you need any more info to troubleshoot it. It's a regression, it was working fine in the previous release of Slide, so hopefully that helps narrow down the cause!

**Comment by Controless** [comment]
Sure thing, I'm not the dev though, just a normal user like you :P

**Comment by Nxt3** [comment]
This happens to me every now and then. Restarting the app fixes it. Definitely a bug.

**Comment by ccrama** [comment]
Fixed in my last commit!

**Comment by craftyguy** [comment]
Awesome, looking forward to the update!
