### ISSUE TITLE
Posts not marked as read on initial load via Synccit

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1787]
When opening up Slide, if there were posts that had been read (and marked as read via Synccit), those posts will still show up as unread _until_ you do a manual refresh--in which you can then see the posts being marked accordingly.

[Here is a video of the issue](https://www.dropbox.com/s/jg6szk24h2et67j/2016_05_22_13_28_29.mp4?dl=0_)

**Comment by ccrama** [comment]
Really not a solution unless we wait to display posts for after Synccit is done syncing

**Comment by ccrama** [comment]
Actually just added an updateViews method to the SubmissionDisplay interface, and that will notifyItemRangeChanged(0, dataSet.size())
