### ISSUE TITLE
Some posts aren't loading until a manual refresh

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1788]
I'm sub'd to /r/fiftyfifty, /r/android, and /r/ajc. Those are the only three subs that show up on my frontpage.

Upon opening Slide, the frontpage doesn't appear to have some /r/fiftyfifty posts and is missing some posts from the other two subs. If I refresh, suddenly, these posts appear.

I posted a video for #1787 that shows this issue also. Notice that after manually refreshing, an /r/fiftyfifty posts shows up at the very top that wasn't there until the refresh.

**Comment by ccrama** [comment]
Sounds like an API issue, not a Slide issue. The content only loads after authenticating, so Reddit might not be returning the correct frontpage posts

**Comment by Nxt3** [comment]
I dunno. It hasn't ever done this until now. I'll see if it keeps happening.

**Comment by ccrama** [comment]
Have you run into it any more?

**Comment by Nxt3** [comment]
Nope. If I do, I'll reopen. You're probably right in that it was Reddit's fault.

**Comment by Nxt3** [comment]
and I'm now running a build that was built just a few minutes ago and I've already run into this issue. Just to clarify--this was happening before you introduced the `updateViews()`.

**Comment by ccrama** [comment]
Yeah but I haven't ever seen this or gotten other reports of it. Really do suspect it's an API issue, Slide is not hiding anything on purpose, just isn't being given the data

**Comment by Nxt3** [comment]
You use Synccit full time? Maybe it's because of Synccit you haven't gotten any reports of it. I would imagine next to nobody uses that.

**Comment by ccrama** [comment]
Have been all day with no issues

**Comment by Nxt3** [comment]
I'm not so sure. I'm leaning towards that--but my tablet is running an older build and I've never experienced this issue. :| I'll close it in hopes that others have the issue too. Maybe I'm just "lucky".
