### ISSUE TITLE
Link from this post is treated as YT content

### ISSUE THREAD

**Issue by Soberat** [ccrama/Slide#1791]
Slide version: too lazy to check, still probably related to Video Plugin
Android version: 6.0.1

https://www.reddit.com/r/wheredidthesodago/comments/35pwwk/why_cant_i_kitchen/

I checked it with similar links opened in the plugin (streamable, vid.me) and it didn't behave it like that.

**Comment by ccrama** [comment]
Fixed, now it does a hard check for youtube as the domain instead of .contains()
