### ISSUE TITLE
updateViews() causes graphical glitches

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1795]
https://www.dropbox.com/s/iqxhdqtoy71tq4x/2016_05_24_00_16_21.mp4?dl=0

Random thumbnails flash over posts and titles length sometime changes. (I'm not talking about the extra list flash that happens after a refresh). I'm not sure if this is something you can fix.

If this isn't something you can fix, I say revert the updateViews() commit--and make it so that if the user has Synccit installed, maybe loading a sub should take a little longer to account for Synccit's syncing.

**Comment by ccrama** [comment]
I have it enabled and have no graphical glitches

**Comment by Nxt3** [comment]
Use List mode too. Maybe that's it.

**Comment by ccrama** [comment]
I do

**Comment by Nxt3** [comment]
Let me install a new build and see if that fixes it. I've also noticed that thumbnails are showing up in the incorrect posts (for example, an /r/5050 post will have a thumbnail from an /r/android post on my frontpage).

**Comment by Nxt3** [comment]
http://imgur.com/a/w2ASl

Notice the "PSA: Motorola . . ." has that thumbnail and so does the "Google's use of the Java API . . .". IN addition to that, the /r/fiftyfifty post has an /r/android thumbnail from a post not in the screenshots ("AmpMe" post on /r/android).

**Comment by ccrama** [comment]
Doesn't look like that for me :(, don't really know what's going on with your device

**Comment by Nxt3** [comment]
Do this: Make a new multi in Slide. Only put /r/androidcirclejerk and /r/fiftyfifty in that multi. I can recreate it super easy. I think it has to do with NSFW thumbnails.

**Comment by ccrama** [comment]
Sorry to say I still can't reproduce with that multireddit, everything looks fine. Same post settings, reddit settings, and subreddits

**Comment by Nxt3** [comment]
What are your Reddit thumbnail settings?

**Comment by ccrama** [comment]
Always show and hide NSFW thumbnails

**Comment by Nxt3** [comment]
If it's set to Per Subreddit Settings this happens. Wasn't able to replicate it with your settings.

**Comment by ccrama** [comment]
It wasn't ocurring with Per Subreddit so I changed it to always because I assumed that's what you were using

**Comment by Nxt3** [comment]
I think that's another bug; if I have "Always Show thumbnail" and "Hide NSFW", I still see NSFW thumbnails. I'll see if I can't narrow this bug down further.

**Comment by ccrama** [comment]
If you force visit an NSFW sub (or multi), it will always show NSFW thumbs despite your setting. And please let me know if you do!

**Comment by Nxt3** [comment]
Then when would it hide?

**Comment by ccrama** [comment]
No, it would show if you force visit a NSFW multi

**Comment by Nxt3** [comment]
Okay it's definitely Synccit. I wiped all data from Slide and only setup my Synccit account, and made a /r/fiftyfifty+/r/ajc multi. It only happens when you have _View Mode_ set to **List** and _Picture Mode_ set to **Thumbnail**; I tried all other combos of view picture mode and it only happens there.

**Comment by Nxt3** [comment]
Correction: It happens with any _View Mode_, but if _Picture Mode_ is set to **Thumbnail**, I have this issue.

**Comment by ccrama** [comment]
Found and fixed, thanks!

**Comment by Nxt3** [comment]
You da best :)
