### ISSUE TITLE
Download bar in offline mode

### ISSUE THREAD

**Issue by Zykino** [ccrama/Slide#1796]
When I read a post (and it's comments list) on a cached version there is a yellow bar on the bottom of the top "menu" which is animated.
It's really annoying to read a long article with that bar moving all the time like if it try to download the last comment version. Since I'm in offline mode the "download" takes forever.
If it was at the bottom of the view it would be less annoying but removing it completely is preferable.

Slide version: 5.3.8
Android version: 5.1.1

**Comment by ccrama** [comment]
It wasn't actually trying to download, I only told it to hide the bar after it does (which it never does in offline mode). Has been fixed for the next update, though!
