### ISSUE TITLE
The Road Ahead

### ISSUE THREAD

**Issue by piyush-rvc** [ccrama/Slide#1800]
With the launch of the official Reddit App, what are the plans for the future for Slide? What philosophy would drive the development forward?

**Comment by The0x539** [comment]
Is this a question that would also apply to any other app? If so, the official app is nowhere _near_ being an end-all reddit client.

**Comment by ccrama** [comment]
I don't think there is much left for us to do. I think Android Wear and Chromecast support would be cool, but Slide's current feature set blows other apps and the official app out of the water

**Comment by Nxt3** [comment]
Just polish and bug fixing bbyyy.

**Comment by piyush-rvc** [comment]
@ccrama what about refactoring? Many classes have public members, and they are changed in different files, which makes it difficult to understand the code flow.

**Comment by l3d00m** [comment]
@piyush-rvc Code optimization would be great, yes. We can also look into using RXJava instead of AsyncTasks in the future.

**Comment by slamanna212** [comment]
@ccrama I would love chromecast support! right now i cast my whole screen but having actual support in the app would be light years better

**Comment by ccrama** [comment]
@slamanna212 after looking into it, we probably won't be doing this. It requires our own webserver to host the website version that is displayed on the chromecast, and it has a lot more going into it than I expected

**Comment by slamanna212** [comment]
@ccrama Oh wow, i didnt realize it was that involved . Casting screen will work!

**Comment by ccrama** [comment]
I think this issue is now closeable, Slide has a pretty huge feature set now, and any new feature implementations will use the new Github Projects system
