### ISSUE TITLE
Larger line height for comments and selftexts

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1802]
Increase the line height to improve readability when viewing comments or selftexts. This will space out each line a little more. Nothing too much.

**Comment by ccrama** [comment]
Why should we deviate by the standard set by the Android TextView?

**Comment by Nxt3** [comment]
I dunno. Better readability? I have to agree that a block of text looks slightly jumbled so close together. I wouldn't even increase it that much. It's easy to do: `android:lineSpacingMultiplier="1.2"` in the `TextView`s.

**Comment by ccrama** [comment]
Made it 1.1x bigger, 1.2 was a bit much

**Comment by Nxt3** [comment]
I was guessing. 1.1 was perfect.

**Comment by Alexendoo** [comment]
Yeah looks a lot nicer
