### ISSUE TITLE
Comment from different accounts w/o changing account.

### ISSUE THREAD

**Issue by QuickBASIC** [ccrama/Slide#1803]
Slide version:Slide v5.3.8
Android version: 6.0

I just came over to Slide and rbb had this feature.

It would be nice if there was a drop down that listed all accounts when you comment, so you can select which to comment from. (Sometimes it's more appropriate to reply from a particular Reddit account, but you don't want to switch accounts and try to find the post again.)

**Comment by ccrama** [comment]
Thanks for the suggestion, same as #521

**Comment by QuickBASIC** [comment]
Sorry about that. I missed it when I checked for other issues. Thank you.
