### ISSUE TITLE
Can't swipe back into comment section after swiping out of it

### ISSUE THREAD

**Issue by cyalins** [ccrama/Slide#1809]
Slide version: 5.3.1.9
Android version: 6.0.1
I'm using the comment pane view mode, and it lets me tap on a post to return to where I was in it, but not swipe back into it.
I'm using a stock Nexus 5 on Marshmallow; could be a device specific bug?

**Comment by ccrama** [comment]
That is on purpose, only tapping will allow you to re-enter a post. This is because if you have not opened any comments, there is nothing to slide back into (and why other apps with similar interfaces do not allow you to swipe back in either)

**Comment by cyalins** [comment]
Okay, so just to clarify, I'm doing this:
1. Tap on a post to open it.
2. Swipe right to exit the comments.
3. Trying to swipe left to return to the loaded comments, but it's not letting me slide back into them.
4. Tap the post instead, to return to the loaded comments.

I think Relay allows for this, and I think it'd be a cool improvement, if possible
Thanks!

**Comment by ccrama** [comment]
Yes and tried on relay, and it's limited as well. This is on purpose in both apps
