### ISSUE TITLE
Cannot expand textless comments with comment actions swapped

### ISSUE THREAD

**Issue by Soberat** [ccrama/Slide#1810]
Slide version: https://github.com/ccrama/Slide/commit/917810cd184ec67bb4bb4106d9b82edd45c79984
Android version: 6.0.1

Noticed it in this thread:
https://www.reddit.com/r/Tinder/comments/4l9ecj/what_can_i_say_i_dont_travel_much/d3li9p2

When the comment body has only a reddit formating sign (>.# etc.) it results in an empty comment, which cannot be expanded if "Swap comment actions" is enabled.

**Comment by l3d00m** [comment]
As a workaround, try to tap in the upper right corner, next to the username.

**Comment by ccrama** [comment]
Fixed for next version!
