### ISSUE TITLE
Sorting by "Top > X" fails to work consistantly

### ISSUE THREAD

**Issue by IronPiston** [ccrama/Slide#1815]
Slide version: 5.3.1.9
Android version: 6.0.1

When sorting by top, the page reloads but fails to take into account the input. If you are previously on new and go to top, the menu displays selecting top but the content is new. Controversial, rising, hot, and new all appear to function correctly. On occasion, top will work, but it is very inconsistent.

**Comment by l3d00m** [comment]
Sorry, I cannot reproduce it. I've tried the comments of a few frontpage posts and I had no problem with it.  
Even if I manage to tap while it's still loading another sorting type, it works without problems,

**Comment by ccrama** [comment]
I cannot either

**Comment by ccrama** [comment]
Was an issue with caps, has been fixed!
