### ISSUE TITLE
Subreddit sidebar links not working

### ISSUE THREAD

**Issue by browncapades** [ccrama/Slide#1816]
Slide version:
Android version:

On the dota2 subreddit the links don't work. They work in other Reddit apps so I know it's possible.

**Comment by ccrama** [comment]
Which subreddit sidebar doesn't work?

**Comment by browncapades** [comment]
The dota2 subreddit. Like it will pull out but the links won't take me
anywhere. For example more upcoming games goes nowhere.

**Comment by ccrama** [comment]
None of the dota2 links actually go anywhere, they just alter the CSS of the website version of the subreddit

**Comment by browncapades** [comment]
I'm not sure what that means. But basically I'm a regular user who clicks
on the links in the other Reddit apps and it takes me to the desired
location. The link in particular being the "more upcoming" one. When I
click on it in slide it goes nowhere. When I click on it in Reddit is fun
or relay for Reddit pro it works. Not sure what or why. Is there a possible
fix?

**Comment by ccrama** [comment]
I really don't know where relay is going to, the "Upcoming Matches" link is an html identifier, and isn't even clickable on Relay

**Comment by browncapades** [comment]
Relay pro? I'm literally clicking it in relay right now and it's taking me
to the gosugamers site. I don't understand how it couldn't be working for
you...

**Comment by ccrama** [comment]
Which link are you clicking on? The "Upcoming Matches" link is not even clickable on Relay

**Comment by browncapades** [comment]
No the link is more upcoming. Like the quotes I had a few emails back.
"More upcoming"

**Comment by ccrama** [comment]
Ah alright. It was because there was a double # identifier in the URL. That should be the only one with an issue, though, the rest of the links work just fine

**Comment by browncapades** [comment]
Soooo is it gonna be fixed or something or is it just kind of there and
that's how it just how it is?

**Comment by ccrama** [comment]
Its an easy fix, only affected that one link though and is unrelated to other links or the sidebar

**Comment by browncapades** [comment]
Oh okay cool so I look forward to the fix. Thanks for the help. Sorry if I
came across in any kind of way it was just a really confusing thing to try
to convey for some reason.
