### ISSUE TITLE
Swiping to exit gif doesn't stop the gif from being downloaded

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1817]
Slide version: 5.3.9.2
Android version: 6.0.1

From the network speed indicators on my status bar, I noticed that swiping to exit a gif doesn't stop the gif from being downloaded (continues to download even after swiping). You can reproduce it by viewing large gifs (10mb+) and then swiping away or exiting.

**Comment by ccrama** [comment]
Should be fixed now

**Comment by Controless** [comment]
Great, thanks!
