### ISSUE TITLE
Use new F-Droid badge

### ISSUE THREAD

**Issue by mvdan** [ccrama/Slide#1818]
See https://f-droid.org/posts/get-it-on-f-droid-badges/.

**Comment by Alexendoo** [comment]
They've included a large amount of whitespace around it in the image itself, that's pretty irritating

**Comment by mvdan** [comment]
Perhaps @relan knows more about this.

**Comment by mvdan** [comment]
Opened an issue on our side about this: https://gitlab.com/fdroid/artwork/issues/2

**Comment by mvdan** [comment]
We closed the issue without changing the padding, see the thread for details.

**Comment by anowlcalledjosh** [comment]
Summary of that thread: the Google Play badge (the new one) has the same amount of padding as the new F-Droid badge, so having both next to each other will look better. I've submitted a PR to update them both.
