### ISSUE TITLE
List mode + Multicolumn == overlapping cards

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1819]
When using the List mode and multicolumn, the posts overlap one another.

I know why this happens--it's because of the `android:layout_marginEnd="-4dp"` that is set in `submission_list.xml`'s `CardView`.

The reason I set the margin is `-4dp` is because of an issue that is caused by some random `4dp` end margin from somewhere in the main view (see below screenshot). I've tried setting negative margins on the `RecyclerView` in `fragment_verticalcontent.xml` and adjusting everything I could think of in that file. I have no idea where this extra `4dp` is coming from, and I couldn't figure it out a week or so ago either. :|

<img width="1280" alt="screenshot_20160529-191518" src="https://cloud.githubusercontent.com/assets/2940826/15636581/e4c34d62-25d1-11e6-831d-4a7ac48780ef.png">

**Comment by Nxt3** [comment]
This commit 3393dcd5f77863e219734f4380632a549daee4ca is a work around. Instead of trying to remove the random `4dp` when in List view mode--just embrace it and remove the end margin from the `CardView` and add back the `4dp` start margin to the view for a consistent look. Not happy about this, but it works for now; at least it isn't overlapping anymore.

![screenshot_20160529-195124](https://cloud.githubusercontent.com/assets/2940826/15636743/dce9280a-25d6-11e6-9256-fc29cada64fa.png)

**Comment by ccrama** [comment]
I mean that doesn't look bad, what is the downside to this method?

**Comment by Nxt3** [comment]
Nothing I guess. It's just hacky and would have been easier to figure out how to remove that random 4dp.

**Comment by Nxt3** [comment]
Maybe one day.

**Comment by Nxt3** [comment]
Actually, an issue with my workaround is that it doesn't work when changing orientations. If I open the app in landscape, it will open and look fine with 2 columns. If I stay on the current sub and rotate to Portrait--the margins on the left and right I added per the work around stay there until I go to a few subs over.

How could I handle the orientation change @ccrama?

**Comment by ccrama** [comment]
@Nxt3 that is quite complicated. Why not just add spacing between the list cards with the LayoutManager and then keep the negative margin the same on the cards?

**Comment by Nxt3** [comment]
You mean in the middle when in split view? That would be the best--but I didn't know how to do that. If you did that, it would need to be `Reddit.dpToPxHorizontal(4);`.

**Comment by ccrama** [comment]
Looked into it and doesn't seem possible, actually. What if we just made the margins on the list -2 and -2, and then just had a little edge padding when you're in portrait?

**Comment by Nxt3** [comment]
Then the cards wouldn't be full width. I think we just need to find where that 4dp is coming from. If you don't have any idea, then I'll keep trying to find it. Whatever it is, isn't in a layout file.

**Comment by ccrama** [comment]
I'm fairly certain it's the fragment_verticalcontent.xml on the GeneralSwipeRefreshLayout

**Comment by Nxt3** [comment]
Setting a margin at the end of any size doesn't affect it though

**Comment by ccrama** [comment]
What happens without that margin?

**Comment by Nxt3** [comment]
And I'm pretty sure I fixed it. When I was trying to fix the margin, I was changing the values in the XML--but once they were set programatically, my XML changes were overridden with the coded ones--meaning--I never saw any changes. Now that I'm only testing stuff in the XML--I'm seeing the changes; so, I've fixed it. :) Thank you!

**Comment by Nxt3** [comment]
Well now there isn't a scrollbar when in list mode; setting the end margin to -4dp programmatically pushes the scrollbar off screen. -_- separate issue.

**Comment by Nxt3** [comment]
Wow. Turns out the scrollbars were creating the offset the entire time. I've fixed both of these.
