### ISSUE TITLE
Subreddit Card Color not Working

### ISSUE THREAD

**Issue by fangorntheent** [ccrama/Slide#182]
Subreddit Card Color not working in any form on latest Play Store update.

**Comment by fangorntheent** [comment]
![screenshot_2015-10-19-23-41-13](https://cloud.githubusercontent.com/assets/7517882/10597286/3573c2e4-76bb-11e5-9320-7e5ab3ac6264.png)
![screenshot_2015-10-19-23-40-58](https://cloud.githubusercontent.com/assets/7517882/10597287/3573de46-76bb-11e5-915b-b0ee3125230d.png)
Front page is to show that /r/gifs won't color. /r/gifs is to show that it is colored.

**Comment by ccrama** [comment]
Fixed! 25af00527dccc2b05e269d8e47b161d99cc031df
