### ISSUE TITLE
Autocache only one version

### ISSUE THREAD

**Issue by Zykino** [ccrama/Slide#1821]
When the autocache function want to download a new version and there is already one autocached nothing happend.
I didn't watched it live but at least there is the download notification but the subreddits I wanted stay in the list in form "SubReddit (1d Comments)". But there is only one entry for this subreddit in the list.

I want either:
* to keep the last 7 day.
* or only the last version of the subreddit.

Slide version: 5.3.8
Android version: 5.1.1

**Comment by ccrama** [comment]
That is on purpose, the point of offline is you can store copies of the subreddit well into the future if you'd like

**Comment by Zykino** [comment]
But I don't have the new versions. After 3 days I have only the "SubReddit (3d Comments)" but nor the "SubReddit (2d Comments)" or "SubReddit (1d Comments)".
If I can have all of them that would be great :)

**Comment by ccrama** [comment]
They are all there, you switch between them in the toolbar

**Comment by Zykino** [comment]
Not in my phone, that's the point :s

I have a OnePlus2 with the stock Oxygen OS

**Comment by ccrama** [comment]
Please screenshot it for me

**Comment by Zykino** [comment]
I just thought of an educated guess before waiting 3 days.
Since I mostly use my phone out of home I don't always think to bring back each app on online mode. Most of them either:
* try to sync while offline (not suitable for slide)
* auto switch online / offline mode based on if I'm connected to internet (checking if I'm on WiFi is even better) [You may look at [k-9 Mail](https://github.com/k9mail/k-9) or [Synchting-Android](https://github.com/syncthing/syncthing-android) for examples]

Also I'm not a big user of reddit yet so I don't check the app every evenings.

Maybe my problem is in fact more a feature request: do the switch online/offline by yourself and don't ask the user to do it.
If possible give the option to only be in online mode over WiFi and not over 3G/4G.
(Do you want an issue for it? Do you wanna do it?)

If it's that there is still a bug relevant here: I see the download notification the morning even if no download were processed.
