### ISSUE TITLE
Clear all saved subreddits make the app blank

### ISSUE THREAD

**Issue by Zykino** [ccrama/Slide#1822]
Whenever I want use the option "Clear all saved subreddits" in "Manage offline content" while offline the application is impossible to use. I mean I can't even go to the settings. The left menu is blank and apparently I'm on /r/Android (even if it wasn't cached).
I need to connect to internet to be able to view my settings again.

To make the app usable again I have to go online.

Then when I go back to the "Manage offline content" menu the settings are reset.
(While I'm here talking about this sub-menu: the time-picker is forced to be AM/PM while I'm more used to 24h format)
This part is particularly annoying since I use the option quite often (related to #1821)

Slide version: 5.3.8
Android version: 5.1.1

**Comment by ccrama** [comment]
That is by design, there is nothing for you to do in the app if you remove the only content the app can display

**Comment by Zykino** [comment]
Ok but it's so empty I felt like I totally removed the app.

Because the menu is empty if I dimiss the popup asking me to reconnect I cannot go back online without restart.
And I think you may want to update your subscriptions to offline content or see / update some settings (for instance post layout or Font don't need any data to be changed).

It break the flow I use to have in other app.

**Comment by Zykino** [comment]
Oh you were talking about the middle panel? Yes Normal to be empty. Maybe to be more user friendly you can print a message saying "You are in offline mode and no subreddits are in cache" but that's a bonus.

**Comment by ccrama** [comment]
I don't really understand why the user should still be able to access the app, if they change settings there is nothing they are changing, because there is no content to display. I think the popup is fine and tells the user exactly why there is nothing available. Also you cannot change your offline settings while offline, it won't autocache if you are not connected to the internet.
