### ISSUE TITLE
Cant Sort Posts In Certain Cases 

### ISSUE THREAD

**Issue by slamanna212** [ccrama/Slide#1823]
If i follow a link to a subreddit in a post, it opens that subreddit but i can not sort. It will refresh the posts but they will be in the same order

Video of issue: https://www.youtube.com/watch?v=Tvj4bDHzQ7g (unlisted youtube video, you need the link to see it)

Slide Version: 5.3.9.2
Android Version: 6.0.1 on a Sprint LG G5

**Comment by ccrama** [comment]
Has been fixed for the next update, had to do with caps in the sub name
