### ISSUE TITLE
Padding for settings switches are too small

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#1824]
Slide version 5.3.9.2
CyanogenMod 13

![00001](https://cloud.githubusercontent.com/assets/12200557/15694947/fe7a2388-2767-11e6-887c-52722191b863.png)

![00002](https://cloud.githubusercontent.com/assets/12200557/15694953/07b65ab6-2768-11e6-8645-d60289a57f66.png)

It appears as if there's some kind of padding coming from the left and right edges, and not a problem with the switches themselves.

This happens no matter what settings page you are on.

**Comment by Nxt3** [comment]
I can only replicate this on the right side (the switch is set to enabled)
