### ISSUE TITLE
Image Save indicator and Album not loading.

### ISSUE THREAD

**Issue by slio** [ccrama/Slide#1826]
Slide version: 5.3.8.1
Android version: CM 11S

1) Image save is not showing the loading activator at all. It stopped working since 2 days (I know doesn't help you in finding the root cause.
1a) Bonus Issue : Albums in imgur never open, always says album not found open in external browser.
(Album issue is not present in Sync and Relay)

Will attaching screen-shots help or are you aware of these issues?

**Comment by ccrama** [comment]
The only reason images cannot load and albums would do that is if A) your network is blocking Imgur or B) imgur is rate limiting you. Because I have had no other reports of this, I believe the issue is limited to you, and because the issue just cropped up, it is most likely an Imgur API issue and is not a Slide issue

**Comment by slio** [comment]
What about image save indicator? Do we have a notification telling us image is saved or since it copied from cache there is no notification present?

To clarify: images do load correctly, in albums it shows not found open in external browser and opens correctly when selected yes.

**Comment by ccrama** [comment]
It doesn't copy from the cache, it initiates a download if the image isn't in cache or recreates it from the cache if it's there. Because you aren't seeing anything in the albums and saving isn't working, I'm 99% sure it's a network issue as it cannot download either image

**Comment by slio** [comment]
Hi,
Did some texting on the weekend. Now on latest version. 
1. Album issue is resolved it loads correctly.
2. Image downloading indicator/notification still not working. 
2.a image does get saved to the specified folder but it's name is too many random characters due to which android gallery does not show it when i open "gallery" app.
I manually renamed the downloaded file and it started showing.

Question: any way we may achieve to give small random names or original namea instead of cache names?
Tried topis on frontpage right now, dentist and quiet street in kyoto

**Comment by slio** [comment]
Hi,
thought about editing my comment but will leave it as it is and posting this new update.
The pic is still not viewed in gallery however opening it in a messenger app, the messenger app window shows date of the saved file in Unix time Jan 1 1970. could this be an issue?

**Comment by ccrama** [comment]
The name too long issue is specific to your device, isn't really a Slide issue. Next version has a new download notification and should fix your other issues, and no the date shouldn't affect this (although it's strange your device made the time of creation 0)
