### ISSUE TITLE
Backup to file not working without google play account

### ISSUE THREAD

**Issue by slio** [ccrama/Slide#1828]
Slide version: 3.8.1
Android version: CM11S

Hi,
Trying to backup my settings in the settings menu -> backup and restore.
I don't have a google account onmy mobile os, each time i click backup and restore it takes me to a default action of creating or adding an existing account.

Question: Any provision I may use backup to file without adding a gmail account or creating a new one?

**Comment by l3d00m** [comment]
What happens when you tap the back button after that Googe-Play dialog comes up? It closes the dialog for me and I can backup to file as usual.

I agree though, the google dialog should only pop up after you clicked backup or restore, not beforehand.

**Comment by slio** [comment]
It just keeps coming back to add account/use existing account. I have to close app and then open it. 
Approach ahould be asking for account/signin when using anything apart from save to file

**Comment by slio** [comment]
Hi,
I know this us on "priority: low" but it is turning to be a major annoyance, would really appreciate if i could backup to file or my phone my settings without having to enter any google account.
Thanks

**Comment by l3d00m** [comment]
As a workaround, try to tap outside of the dialog! Does it work for you?

**Comment by ccrama** [comment]
Also you can get the version from F-Droid and skip using the Google account all together

**Comment by slio** [comment]
Hi,
As per your advice I have done the same and using F-Droid version now. You may close this ticket.
