### ISSUE TITLE
Weird Formatting of Subreddit Title in Subreddit Theme Settings

### ISSUE THREAD

**Issue by fangorntheent** [ccrama/Slide#183]
The subreddit title shows up fine then immediately switches to a weird format were the subreddit name splits onto separate lines as soon as I scroll on the page. I can detect no rhyme nor reason to the title splitting.

**Comment by fangorntheent** [comment]
![screenshot_2015-10-19-23-40-45](https://cloud.githubusercontent.com/assets/7517882/10597304/78573352-76bb-11e5-9d72-851c3b1072b6.png)
Post scroll shenanigans.

**Comment by fangorntheent** [comment]
It's also not consistent in which titles are split or how they're split.

**Comment by ccrama** [comment]
Fixed c85abcb25dd12bc2566ee00e75c359de3c6602ac. Was a simple width issue!
