### ISSUE TITLE
New FAB hide behavior

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1830]
Saw this and thought it might be a cool idea for hiding the FABs. https://lambdasoup.com/post/fab_behavior_sync_appbarlayout/

Thoughts?

**Comment by Nxt3** [comment]
https://github.com/strooooke/appbarsyncedfab

Now it's a small lib

**Comment by ccrama** [comment]
Personally, I think that is a bit too much. I like it more subtle as it is now

**Comment by Nxt3** [comment]
Fair enough.
