### ISSUE TITLE
Color "load more comments" bars

### ISSUE THREAD

**Issue by DW1045** [ccrama/Slide#1834]
Comment indentation colours are greyed out and not the colour relative to the others at the same level of indentations. 

It's easier to remember what colour the comment replies are rather than scroll up (especially after long comments) and remember which grey indentation is on the same level.

E.g., Slide's: http://imgur.com/IMtEsYB
Sync's: http://imgur.com/jgWJx0E

Slide version: 5.3.9.3
Android version: 6.0

**Comment by ccrama** [comment]
This is on purpose, I don't think it looks good and it is confusing because the user can't tell if it's a load more bar or a comment bar. I dislike how Sync does it
