### ISSUE TITLE
Copy partial text from a comment

### ISSUE THREAD

**Issue by snowtyler** [ccrama/Slide#1837]
As suggested by this Reddit thread:

https://reddit.com/r/slideforreddit/comments/4m7zw2/copying_comment_text/

Allow the user to copy certain parts of a comment.

**Comment by ccrama** [comment]
This is now done for the next update! 

![image](https://cloud.githubusercontent.com/assets/3819844/16922686/443a5980-4cdc-11e6-80ca-bf6cf6d3a008.png)
