### ISSUE TITLE
Request: Direct reply to Comments from the Inbox.

### ISSUE THREAD

**Issue by turdbogls** [ccrama/Slide#1840]
Slide version:5.3.9.3
Android version: N

Wondering if we can get direct reply to comments from the inbox.  I would say half the time or more I know the referenced thread and what I said to get the reply.  there would be no need to load the comment thread.

a longpress action could be used to trigger the "reply" box from right within the inbox.

and while we are on replies, is it even possible to direct reply from a notification with Android N...I'm assuming no, but just curious.

thanks!

**Comment by anowlcalledjosh** [comment]
Direct Reply from a notification is a new feature in Android N ([source](https://developer.android.com/preview/features/notification-updates.html#direct)) - it looks like this:

![image](https://cloud.githubusercontent.com/assets/9433472/16003717/f84c379c-3155-11e6-9a9e-0ca8caadae60.png)

**Comment by ccrama** [comment]
Done! Now if you long press and click "Reply", you can reply directly in that screen. I will also look into implementing it from notifs once N hits
