### ISSUE TITLE
Sorting doesn't work on profiles

### ISSUE THREAD

**Issue by snowtyler** [ccrama/Slide#1841]
Slide version: 5.3.9.3
Android version: 6.0.1

**Comment by Nxt3** [comment]
I can confirm this.

**Comment by ccrama** [comment]
That is intended, you need to see everything a user's posted

**Comment by snowtyler** [comment]
How do I see my top comments and posts, in that case?

**Comment by ccrama** [comment]
What do you mean?

**Comment by snowtyler** [comment]
Comment/submission sorting, stuff like new/hot/top.

**Comment by ccrama** [comment]
How is this related to filters? And tap the sort icon to change the sorting type

**Comment by Nxt3** [comment]
He means the sorting is broken. I can't sort stuff on the profile page

**Comment by ccrama** [comment]
Had to do with caps in the profile name, has been fixed!
