### ISSUE TITLE
crash in /r/diy scrolling to 4th post

### ISSUE THREAD

**Issue by c727** [ccrama/Slide#1843]
Slide version: 5.3.9.3
Android version:  5.1.1

happens everytime. here is a list of the posts http://abload.de/image.php?img=rsdiy9baoz.png

**Comment by c727** [comment]
/r/earthporn instant crashes

**Comment by l3d00m** [comment]
Do you use an S7 edge?

**Comment by c727** [comment]
htc one x+

**Comment by l3d00m** [comment]
Have you reported the crash? I can't find your device in the recent reported crashes.

**Comment by c727** [comment]
I sent few minutes ago.
now post 4 is on 3rd position an it crashes earlier. see here https://youtu.be/FavSw3f7iUQ

**Comment by l3d00m** [comment]
Thanks. Here's the crash report, it's the same crash when you [rotate your device](https://www.reddit.com/r/slideforreddit/comments/4n95hb/slide_crashes_everytime_my_phone_goes_into/). I have absolutely no idea why this is happening, but it was reported pretty often.

```
java.lang.IllegalStateException: Unable to create layer for CardView
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:122)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
```

**Comment by c727** [comment]
Clearing data fixed it...
Well I had slide installed for 1 day. Let's see when it happens again

**Comment by c727** [comment]
@l3d00m

Setting postlayout to big picture causes this

**Comment by l3d00m** [comment]
I cannot reproduce, even with big picture enabled. Maybe it's happening because it's such a big picture and your device is older, I have no idea.

**Comment by c727** [comment]
Can you test if switching between big and cropped picture effects your rotation issue?

**Comment by l3d00m** [comment]
I don't have them any longer unfortunately, but I'll do as soon as the issue reappears.

**Comment by c727** [comment]
@l3d00m 

the 'calculation' for the big (uncropped) picture seems to be wrong and causing this bug...

here is a screenhot of now-for-reddit and slide: https://abload.de/img/nowslide0ka2b.png
in nfr the pic is resized correctly.
in slide we have this extrem high picture with missing left/right parts of the picture
