### ISSUE TITLE
Darker non-AMOLED theme?

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#1844]
Dunno whether it should replace Dark or be yet another theme, but I'd like to see something that's basically a reversed contrastAMOLED.

**Comment by Nxt3** [comment]
If I'm being honest, I'm not sure what you mean. :p

**Comment by The0x539** [comment]
True black background, near-black foreground.

**Comment by Nxt3** [comment]
Ah. Any particular reason the other themes aren't cutting it?

**Comment by The0x539** [comment]
Lack of darkness, looking weird, or lack of background contrast. Not
looking for an abyss theme until I get an AMOLED phone.

**Comment by ccrama** [comment]
Is this still necessary with the new Red Shift theme? We might be adding too many themes

**Comment by Nxt3** [comment]
I agree. Too many especially considering this would be close to an existing theme. Too much overlap.

**Comment by The0x539** [comment]
What about simply darkening Dark?

**Comment by ccrama** [comment]
Dark uses the Material Design dark theme

**Comment by The0x539** [comment]
I remember it got darkened before, what happened then?

**Comment by ccrama** [comment]
It didn't, it's the colors specified in the material spec. If it did change, then it changed to match better with the colors in the spec

**Comment by The0x539** [comment]
#1035

![Screenshot_20160919-154849.png](http://i.imgur.com/yPc93Pi.png)

**Comment by ccrama** [comment]
I swapped the "activity background" and "toolbar color" colors, they are still the same as the spec

**Comment by ccrama** [comment]
Added with the new 'Pixel' theme
