### ISSUE TITLE
Submit post does not auto fill subreddit field

### ISSUE THREAD

**Issue by kudiaborm** [ccrama/Slide#1847]
Slide version:5.3.9.3
Android version: NPD35K

This might be a feature request but I'll call it a bug.

I go to a sub and press the menu button to submit and the subreddit field is not auto filled.

My fab is set to hide seen since I lurk moar. I use the menu button to post but I have to manually enter the sub even though I'm on the tab.

**Comment by Nxt3** [comment]
What subreddit? I can't reproduce this.

**Comment by Nxt3** [comment]
Never mind, go it. Will fix in a bit. Thanks. :D
