### ISSUE TITLE
gfycat opens in external chrome browser

### ISSUE THREAD

**Issue by KaliK0t** [ccrama/Slide#185]
I have opengur set as the default image, gif and album viewer but gfycat opens in an external chrome browser.

shouldnt it open in the internal chrome browser?

**Comment by Alexendoo** [comment]
If you choose to handle links externally it will handle all links of that type externally, which means android gets to decide where it should go -- In this case since opengur isn't able to deal with gfycat links it passes onto the preset for that, which in your case is chrome
