### ISSUE TITLE
Opening wiki freezes app

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#1853]
I'm trying to open the wiki on /r/Vive

**Comment by Georgiel** [comment]
is it just upon pressing the wiki button?

is it in every case?

A longer description will help us pinpoint the exact reason.

**Comment by l3d00m** [comment]
/r/vive has a huge wiki (lots of tables & links). Waiting a few seconds does load the wiki for me, Slide stucks while loading though.

**Comment by ccrama** [comment]
Really no way to fix this, the processing has to happen on the main thread because they are views
