### ISSUE TITLE
Disable swipe setting

### ISSUE THREAD

**Issue by vinicius97g** [ccrama/Slide#1854]
Slide version: 5.3.9.3
Android version: 6.0.2

Is it possible to disable the swiping from the left motion (both on settings and when reading comments) I find that the sensitivity is way too high and end up either exiting one of these or almost at least pretty close to always. It's really the only thing that keeps me from using Slide since it's a pretty big deal.

I'm pretty sure I was able to do it in the past but right now I can't so i guess the option was removed?

Thanks for the great app.

**Comment by Nxt3** [comment]
This won't be considered. At one point, there was an option--but it has since been removed. The point of Slide is to "slide". :p

If it bothers you, don't swipe from so far over; it isn't that sensitive, but swiping from the edge will absolutely trigger it.

**Comment by l3d00m** [comment]
See #1335 as well.

**Comment by Nxt3** [comment]
@l3d00m I'm pretty sure the comment pages use the new swipe method. I don't think it's used in Settings, though--as I agree--it tends to be sensitive there.
