### ISSUE TITLE
Use images for thumbnails regardless of quality

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1855]
As per this subreddit post: https://www.reddit.com/r/slideforreddit/comments/4o2yqz/some_images_are_small_grey_boxes_with_a_white/d4a4huv?context=3

Instead of showing the "web" icon when a HQ thumbnail can't be used--use whatever we can get instead.

**Comment by c727** [comment]
+1

**Comment by ccrama** [comment]
What if we can't get any thumbnail?

**Comment by Nxt3** [comment]
Then I guess we'd have to use the web icon

**Comment by ccrama** [comment]
I believe I did this a week ago already
