### ISSUE TITLE
reply to comment crash when accessed from context link 

### ISSUE THREAD

**Issue by Georgiel** [ccrama/Slide#1860]
Prerequisites:
- **Fully collapse comments** needs to be disabled

Once that setting is disabled, going from _Inbox > Comment context > Reply to comment higher up in hierarchy_, crashes the app.

[Gfycat of issue](https://gfycat.com/AmpleHastyFrog)

**Comment by Georgiel** [comment]
My best guess is it fails out when connection is bad?

**Comment by Georgiel** [comment]
Finally managed to get it to happen intentionality, still can't actually tell why it only sometimes happens.

 In the video I clicked a reply, then responded to a comment higher in hierarchy. 

Slide crashed and then immediately reloaded to the frontpage. 

Comment still posted though.

 This is a repeat of the behaviour that caused it to crash seconds before. 

Android M 

Slide version 5.3.9.3

[gfycat gif](https://gfycat.com/AmpleHastyFrog)

**Comment by Georgiel** [comment]
:+1: it's consistently happening when I repeat the behaviour stated.

**Comment by Georgiel** [comment]
:+1:

**Comment by Nxt3** [comment]
There is no need to keep commenting. We are aware of the issue.

Having said that, I was able to replicate your issue given one extra requirement.
- **Fully collapse comments** needs to be disabled

Once that setting is disabled, going from _Inbox > Comment context > Reply to comment higher up in hierarchy_, crashes the app.

**Comment by Georgiel** [comment]
@nxt3 ah sorry,  still not used to github yet

**Comment by ccrama** [comment]
I can no longer reproduce on the latest alpha, is this done?

**Comment by ccrama** [comment]
Assuming this is now fixed

**Comment by Georgiel** [comment]
yeah it's fixed
