### ISSUE TITLE
Adding subreddit witout subscribing, marks it as subscribed

### ISSUE THREAD

**Issue by prashantkhurana** [ccrama/Slide#1861]
Using latest version with MM. 

Steps to reproduce : 
1) Add a sub from the "manage your subscriptions" page but don't subscribe to it i.e use the add option and not the "add and subscribe option"
2) Now go to the sub.
3) Open sidebar
4) You will be marked as subscribed i.e the checkbox is ticked.

We are though not subscribed in real. But the sidebar shows us that we are. 

Looking into the code, I can see the reason why this happens. As of now, we have a list of subs. This list is all the subs in the sidebar. Their is no distinction between a subscribed sub and a normal(unsubscribed) sub.

**Comment by ccrama** [comment]
Now it will only show based on whether the subreddit is subscribed, and if you are logged out it will have the same behavior as before

**Comment by prashantkhurana** [comment]
Wasn't it yesterday that you came back?! 😄
