### ISSUE TITLE
Creating and modifying Multis is awkard

### ISSUE THREAD

**Issue by kudiaborm** [ccrama/Slide#1862]
Slide version:5.3.9.3
Android version: N Preview 4 NPD56N

- [x] The back button (app not the nav bar back button) does nothing in this menu either.
- [x] No confirmation from the "save" icon in the CreateMulti-Activity
- [x] I load a multi, then select the "edit" icon to add threads and it defaults to the first multi alphabetically. At times attempting to type the name of my preferred multi to edit. Edit: The "create multireddit" from the menu seems to work properly,
- [x] The automatically checked subreddits in this menu when trying to modify subs by selecting "plus" fab button do match any actual multi I have created

**Comment by l3d00m** [comment]
> I load a multi, then select the "edit" icon to add threads and it defaults to the first multi alphabetically. At times attempting to type the name of my preferred multi to edit. 

Sorry, I don't get what you mean by this. Can you explain this futher?

**Comment by kudiaborm** [comment]
No longer occurs after wiping data and cache.
Apologies

**Comment by ccrama** [comment]
First one should be fixed as well
