### ISSUE TITLE
Deleting a multi deletes the first multi alphabetically

### ISSUE THREAD

**Issue by kudiaborm** [ccrama/Slide#1863]
Slide version:5.3.9.3
Android version: N Preview 4 NPD56N

Related to   #1862 

Upon attempting to delete a multi, the first multi alphabetically gets deleted instead. This seems related to the other referenced issue that affects multi modification and creation from the "edit" multi menu (pencil icon)

**Comment by l3d00m** [comment]
Is this still happening after clearing data? I can delete multis just fine.

**Comment by kudiaborm** [comment]
Clearing data did indeed resolve the issue

**Comment by l3d00m** [comment]
Great, feel free to reopen if it ever occurs again.
