### ISSUE TITLE
Remove and Unsubscribe from Manage Subscriptions causes error

### ISSUE THREAD

**Issue by kudiaborm** [ccrama/Slide#1864]
Slide version:5.3.9.3
Android version: N Preview 4 NPD56N

Causes "Uh oh something went wrong" every time

**Comment by l3d00m** [comment]
It does not happen for me, is there any chance that you could get us the logcat output of that too?

**Comment by kudiaborm** [comment]
I'll grab one later today

**Comment by kudiaborm** [comment]
No longer occurs after wiping data and cache.
Apologies

**Comment by Nxt3** [comment]
Should we close this then?

**Comment by kudiaborm** [comment]
Please close
