### ISSUE TITLE
Title bar re-appears after scrolling down. 

### ISSUE THREAD

**Issue by mezerr** [ccrama/Slide#1865]
Slide version: Newest as of June 20, 2016
Android version:6.0.1 (newest as on June 20, 2016
Nexus 6

When scrolling down, the title bar re-appears after you stop scrolling.  But only sometimes.  See video.

https://youtu.be/r1jwZAY9_GE

**Comment by ccrama** [comment]
I cannot reproduce this, what are the steps to reproduction?

**Comment by mezerr** [comment]
It's very intermittent.  Sometimes it does it, sometimes it doesn't.  No real steps to reproduce it, just start browsing a subreddit, and scroll down.  You can see in the Video that it in fact does do this, not really sure what else to say.

**Comment by ccrama** [comment]
Alright, I browse 3-4 hours a day when working on slide and I haven't run into this, so there has to be something else causing this issue. If you find any more variables that could affect this, please let me know

**Comment by ccrama** [comment]
Is this still an issue? If so, feel free to re-open it! I have not run into it since this post or received other reports of it
