### ISSUE TITLE
Images without an extension cannot be saved

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#1866]
Slide version: v5.3.9.3
Android version: 5.0.1, 5.1

Images wihout an extension (imgur links without an "jpg" or "png" ending, like `imgur.com/vwPNvtT`) cannot be saved, as reported [here](https://www.reddit.com/r/slideforreddit/comments/4p1169/hello_i_seem_to_be_having_a_problem_with/). It fails with the following error: 

```
E/ImageLoader: Image can't be decoded [https://imgur.com/vwPNvtT_1080x1776]
```

**Comment by ccrama** [comment]
Set it to now use the already displayed URL
