### ISSUE TITLE
Option to upload images to reddit instead of imgur

### ISSUE THREAD

**Issue by piyush-rvc** [ccrama/Slide#1867]
Has reddit provided API for it?

**Comment by Nxt3** [comment]
Unfortunately, they haven't. This will be impossible unless they provide an API. Whether they choose to do that or not remains to be seen yet.

**Comment by 07416** [comment]
@Nxt3 Is it impossible to upload via wrapping the website, like you do with the login process?

Can be done by using the desktop website or old.reddit.com, only the mobile site hides image uploading option.
