### ISSUE TITLE
Slide video plugin causes Android OS to completely lock up

### ISSUE THREAD

**Issue by applesandsynths** [ccrama/Slide#1868]
Slide version: 5.3.9.3
Android version: Android N DP4

Slide video plugin causes Android OS to completely lock up on the latest Android N developer preview 4. The system totally locks up after you try opening a video. I've uninstalled the video plugin and slide works fine without it. I haven't been able to find any other apps which lock up the OS like this. The only way around the lock up is to force reboot the device. 

The device I'm using is a Google Pixel C. 

Thanks!

**Comment by Nxt3** [comment]
None of the contributors are running the Developer Preview. None of us will be able to replicate this issue. I'm going to chalk it up to an Android N bug and close this issue. If it comes back once Android N is released, you bet it will be fixed. :)
