### ISSUE TITLE
accepting a moderator invite doesn't work 

### ISSUE THREAD

**Issue by Georgiel** [ccrama/Slide#1869]
In the gif included I am clicking the "accept" link and then the error appears. [the gif](https://gfycat.com/IndolentSeparateCottontail)

**Comment by Georgiel** [comment]
anyone else had this behaviour yet?

**Comment by Nxt3** [comment]
No way for us to test this unless you send us a mod invite. :p

**Comment by Georgiel** [comment]
ha, true. or to make a test reddit and then send the invite.

reddit username so can quickly try it out?

**Comment by l3d00m** [comment]
You don't need to, as it links to `https://www.reddit.com/r/<SUB>/about/moderators` and this isn't supported by Slide (and the api?). Slide should open this externally though.

**Comment by Georgiel** [comment]
I'm not getting that behaviour, and it's consistently so.

**Comment by l3d00m** [comment]
Sorry, I don't understand what you mean

**Comment by Georgiel** [comment]
As in I've never seen it attempt to open externally in each attempt.

**Comment by l3d00m** [comment]
Yeah, what I meant was that we should code that links to that always open externally.

**Comment by Georgiel** [comment]
Aha, now I understand, thought you were saying that you weren't getting the
same behaviour.

Are we sure there's no api hooks for the about/moderators section?
 I thought the reddit api was quite good in letting anything be hooked into?

If not, I think if we moan about it on
https://github.com/reddit/reddit/issues/new , there's an outside chance we
might get it added in the next major release.

On Fri, Jun 24, 2016 at 11:51 AM, Thomas Lu <notifications@github.com>
wrote:

> Yeah, what I meant was that we should code that links to that always open
> externally.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ccrama/Slide/issues/1869#issuecomment-228315712>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFqA8CGtTLa2DQw_hDND2mquWSK0TAjCks5qO7avgaJpZM4I8OkL>
> .
>



-- 
Regards,

George William Langham

**Comment by l3d00m** [comment]
I haven't really checked that, it was more like a assumption. I don't think that feature is needed though.

**Comment by Alexendoo** [comment]
Fixed with 025e7d4e864851f2cf3affec0b5527b3834de3d3, coming to an update near you at some point in the future
