### ISSUE TITLE
Slide does not support captchas in private messages

### ISSUE THREAD

**Issue by xshane** [ccrama/Slide#1870]
Slide version: 5.3.9.3
Android version: 6.0.1

http://i.imgur.com/ZTtt3OF.png

**Comment by Nxt3** [comment]
Can't seem to reproduce this.

**Comment by xshane** [comment]
I've cleared the system data, uninstalled and reinstalled but I still can't send a message out.

**Comment by Nxt3** [comment]
Try sending one to me? (_inate71_)

**Comment by xshane** [comment]
Just tried, still doesn't work. I tried using a different app to send a message earlier and it worked, so I don't think it's my account at least.

**Comment by Nxt3** [comment]
Could you by chance get a log when you try to send a message?

**Comment by xshane** [comment]
Sorry, I'm not sure how to do that. I'm not rooted either.

**Comment by l3d00m** [comment]
Can you try to send a message over the website? Do you get a captcha there?

**Comment by l3d00m** [comment]
Yeah, I think so. I think Slide doesn't support it atm.

**Comment by xshane** [comment]
I see, it's weird though I used to be able to send messages through slide. I guess it's something on my account side I need to check out. Thanks guys.

**Comment by l3d00m** [comment]
I have no idea what causes the sudden captcha prompts for you, but I think it's a good idea for Slide to support them, as new accounts are required to enter captchas.

**Comment by ccrama** [comment]
Added Captchas to private messages
