### ISSUE TITLE
Message replies should only be indented in the MESSAGES tab

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1874]
Slide version: bd47a034cc3a098ca3301e6547013c6398dd5702
Android version: 6.0.1

Currently they're indented in other tabs such as inbox, which implies they're a reply to the above message when they're not.

Code in question from the very early ages of the project, first commit in most parts of the file. Couldn't work out a way to check the current tab without some horrific casting

https://github.com/ccrama/Slide/blob/4a67bf5637bdb416575265c0f7ca319d9d33d5b5/app/src/main/java/me/ccrama/redditslide/Adapters/InboxAdapter.java#L93-L94

**Comment by ccrama** [comment]
Good idea, done!
