### ISSUE TITLE
Blank lines after comment options

### ISSUE THREAD

**Issue by ente3000** [ccrama/Slide#1880]
Slide version: 5.3.9.3
Android version: 5.1.1

Screenshot: http://imgur.com/SRsqPKX

**Comment by l3d00m** [comment]
May you explain what the steps are to reproduce this problem?

**Comment by ente3000** [comment]
@l3d00m it happens sometimes when opening a permalink to a comment

**Comment by ccrama** [comment]
Should be fixed now!
