### ISSUE TITLE
Title gets cutoff randomly in MainActivity

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#1881]
Slide version: v5.3.9.3
Android version: v5.0.2

[Source](https://www.reddit.com/r/slideforreddit/comments/4pttyh/bug_title_gets_cutoff_randomly_in_the_posts_page/):

I still encounter this every now and again.  You will see the post page like [this](http://i.imgur.com/AidC2B2.jpg).  You go inside the post and see [the actual full title](http://i.imgur.com/RKNox6W.jpg).  

If you go back to posts page, you will see the title still cutoff.  But if you scroll down so the post is out of view, and go back up to see it again, it gets [fixed](http://i.imgur.com/yOSQsW4.jpg).

It does not seem to be related to the posts title length, as there are other longer titles that show up fine.

**Comment by ccrama** [comment]
Same as #1812, merging
