### ISSUE TITLE
AMA comment sorting option not working. 

### ISSUE THREAD

**Issue by Lochstock** [ccrama/Slide#1883]
Slide version:5.3.9.3
Android version:6.0.1
Whenever I try a load comments using the Q&A option the child comments won't load. Whenever I click on them they disappear leaving just the parent comment. I attached a picture of what it looks like before trying to load the comments.
![screenshot_20160630-074716](https://cloud.githubusercontent.com/assets/16820036/16490609/b9530cc4-3e97-11e6-9394-dc91c21dfcfb.png)

**Comment by l3d00m** [comment]
Do you have a link to the thread? I had no issues so far with the mode.

**Comment by ccrama** [comment]
That could have just been how the reddit algorithm sorted it, maybe the op didn't reply to any of them yet

**Comment by ccrama** [comment]
That is how the Reddit API returns the comments, the same behavior is visible on the actual website. Closing now
