### ISSUE TITLE
Sliding between posts loops

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#1884]
when you get to the end of a page it loops back to the first post instead of loading the next page. Can you make it load the next page instead?

**Comment by ccrama** [comment]
It does not do this for me

**Comment by kufii** [comment]
Here's a video of it happening:

https://goo.gl/photos/LXmyMPGmoKjWHxbZ6

**Comment by ccrama** [comment]
Should be fixed now, thanks for the report!
