### ISSUE TITLE
Highlight the current sub in navdrawer

### ISSUE THREAD

**Issue by Soberat** [ccrama/Slide#1885]
I think bolding the text would be enough, especially that the color is already next to the name.

**Comment by Georgiel** [comment]
:+1:

**Comment by ccrama** [comment]
Due to the complexity of this issue and the fact it doesn't add much to the general UI, I have decided not to include this (and have closed many similar issues in the past).

**Comment by Georgiel** [comment]
I can't see a single change as simple as bold text being that insane to do.

**Comment by Nxt3** [comment]
@georgiel So you'll do it for us then?

**Comment by l3d00m** [comment]
@georgiel So how do you find out which sub is the current one? How do you color it?

**Comment by Georgiel** [comment]
@l3d00m  @Nxt3 ooh, touché, it somehow looked more simple than it was.
