### ISSUE TITLE
Backing out of large link does not cancel link download

### ISSUE THREAD

**Issue by jseybold** [ccrama/Slide#1886]
Slide version: v5.3.9.3
Android version: 6.0.1

To reproduce: Select a large link (gfy, jpeg, etc) and back out before it finishes loading. It will continue to load in the background causing Slide to become unresponsive to further requests that require data while it continues to load the backed out link (wasting mobile data).

Exiting Slide also does not seem to rectify this issue. I have to force kill and re-open the app.

**Comment by ccrama** [comment]
Should be fixed now, thanks for the report!
