### ISSUE TITLE
long press doesn't work on very long comments

### ISSUE THREAD

**Issue by Georgiel** [ccrama/Slide#1887]
https://vid.me/e/WqGQ

Example above. 

It seems with very long walls of text comments, the long press action doesn't react, so one can't vote or reply etc to them. 

In the above short animation, I'm attempting to long press a very long comment to no avail. I then long press a not very long comment and those work.

Android M
Slide version 5.3.9.3 
Xperia Z5 (I love that it has a built-in screen recorder)

**Comment by Georgiel** [comment]
:+1:

**Comment by Nxt3** [comment]
No need to comment again. That spams our GitHub notifications.

**Comment by hitesh22** [comment]
@Nxt3 Link to comments shown in the video: https://www.reddit.com/r/videos/comments/4qpieg/it_sounds_like_louisapple_laptop_repair_tech_has/?st=iq9tw9gk&sh=0f242b36

This is the specific comment where the issue happens: https://www.reddit.com/r/videos/comments/4qpieg/it_sounds_like_louisapple_laptop_repair_tech_has/d4ux7f0?st=iq9tz6fa&sh=ee9b8fe7

It is intermittent when I tried to reproduce the issue.

**Comment by ccrama** [comment]
That is the same issue as #1049 believe it or not. Merging
