### ISSUE TITLE
Have an "Add to Multireddit" icon on sub sidebar

### ISSUE THREAD

**Issue by kauelima** [ccrama/Slide#1889]
As a user, I would like to be able to add a subreddit directly to a multireddit via it's sidebar. This issue was discussed on reddit at [this thread](https://www.reddit.com/r/slideforreddit/comments/4r6y6m/add_to_multireddit_on_sub_sidebar/).

[Mockup for the feature](http://i.imgur.com/dOUD2qQ.jpg?1)

**Comment by ccrama** [comment]
I like the idea, have added it in for the next update!
