### ISSUE TITLE
I don't get notification 

### ISSUE THREAD

**Issue by Eliaskh77** [ccrama/Slide#1890]
Slide version:5.3.9.3
Android version:5.1.1

I don't get notification for my message and when someone comment on my post, I don't get any notification

**Comment by ccrama** [comment]
Your post probably had "send notifications" set to off when you posted it

**Comment by Eliaskh77** [comment]
How can I check this ?

**Comment by ccrama** [comment]
You can only set it at the time of creation. Next time you make a post, make sure notifications are checked on not off

**Comment by Eliaskh77** [comment]
http://imgur.com/KxYGfnG

I'm sorry but I can't find any thing relate to notification

**Comment by Eliaskh77** [comment]
And I don't get notification when I receive message 

I don't get any notification after I install your app

**Comment by ccrama** [comment]
"Send replies to inbox" is it. Also make sure you have set notifications to show up in settings, and make sure you didn't block Slide notifications. This is a device issue, Slide is working properly

**Comment by Eliaskh77** [comment]
I check them 

Thank you by the way, I try to fix it

**Comment by ccrama** [comment]
Closing for now, you're welcome! Let me know if the issue comes back
