### ISSUE TITLE
Blur NSFW image thumbnails

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1892]
As per [this subreddit post](https://www.reddit.com/r/slideforreddit/comments/4rliab/blur_nsfw_thumbnail/).

I don't think it should be an option though; it should be the default way NSFW thumbnails are presented. Offers some more color to the app and keeps posts looking consistent.

~~[There is a library that makes this simple](https://github.com/kikoso/android-stackblur).~~
Edit: Apparently this is already possible via the Reddit API--however, JRAW doesn't appear to support it. Once JRAW support was present, I'd happily look into this.

Thoughts?

**Comment by Alexendoo** [comment]
The blurred icons are exposed via the reddit api, no plugin is needed

**Comment by Nxt3** [comment]
Oh nice! I had no idea.

**Comment by Nxt3** [comment]
Where is an example of this? Can't find anything in JRAW.

**Comment by Alexendoo** [comment]
It looks like it might no longer be present in the API responses? Perhaps needs some flag thrown at it

**Comment by Nxt3** [comment]
This apparently can be done with `Submission.getThumbnails()` in JRAW. That's according to the JRAW dev

**Comment by ccrama** [comment]
Unfortunately for us, this only shows up if the thumbnail is NOT NSFW, meaning we can only show the blurred thumb through Reddit on already visible NSFW posts. Don't think this is doable using the Reddit API

**Comment by Nxt3** [comment]
It isn't doable with the API--but I know it can be achieved with the following library quite easily:

https://github.com/wasabeef/Blurry

Thoughts? I could implement this no sweat.

**Comment by ccrama** [comment]
The issue is no image is returned from the api in the case that I show the NSFW thumbnail, so there is nothing to blur. It acts the same as the web icon, and only shows as a last resort

**Comment by ccrama** [comment]
This would only be useful if we included our own NSFW filter and ignore the Reddit one, that turns this into a bigger endeavor though, haha

**Comment by Nxt3** [comment]
Maybe I'm not understanding--but if we just disregard the user's Reddit setting for showing NSFW images--show them everywhere--but honor their setting after we have the thumbnail--wouldn't that work? Instead of honoring their setting while grabbing thumbnails, honor it after the fact. Wouldn't that work?

**Comment by Alexendoo** [comment]
Is there a flag for that? I know of obey_over18=false but I'm not sure if that affects thumbnails

**Comment by Nxt3** [comment]
oh not that; the other one "Show thumbnails: Always, Never, Per Subreddit".

**Comment by Alexendoo** [comment]
Ah, that would be separate, the NSFW thumbs preference is its own one. The issue is that when the preferences are set the thumbnails aren't even present in the API response, so we would want a parameter to be able to include in the request instead of overriding user preferences. But I don't believe there is one for that

**Comment by Nxt3** [comment]
yeah, this would take a lot more work than I thought. Oh well.
