### ISSUE TITLE
Better indication when downloading images

### ISSUE THREAD

**Issue by touzainanboku** [ccrama/Slide#1894]
Slide version: 5.3.9.5
Android version: 6.0.1

As of right now when you tap the download button of an image a notification appears _after_ it has finished downloading. Depending on image size and internet speed this means you have a few seconds where you're not really sure if you actually tapped the button or not. The effect on the download button itself is pretty easy to miss, especially since your finger is covering most of it.

Also, only one notification appears that only shows the most recent saved image, regardless of how many images you've saved. This means if you download multiple images in quick succession, the only way to be sure that all of them were downloaded successfully is to check actually check the files using a file manager or a gallery app. The alternative is waiting for every image to finish downloading before saving another, which takes too much time. 

My suggestions are:

1. Immediately show a notification when the download button is pressed, indicating that a download _is in progress_, using some kind of progress bar (indeterminate is fine IMO), and then change the notification to what the current version shows once it's done: a text that indicates the picture was saved, and a preview of said photo.

2. Have a separate notification for every image saved. This will allow you to quickly see the last few saved images. This means you don't have to use another app, or wait for every image to finish downloading before queuing the others, to make sure that every image you wanted was saved. Combined with my first suggestion, It also means you'll get a new icon in your status every time you hit the download button, which is a good indication that you did indeed press the download button. This might get out of hand if you save too many pictures without clearing your notifications, so perhaps a maximum number of notifications would be a good idea (although I personally think that's not necessary).

**Comment by Nxt3** [comment]
I agree with this.

**Comment by ccrama** [comment]
Done for the next update, cheers!

**Comment by touzainanboku** [comment]
@ccrama thanks for all the hard work! Could the separate notifications also show separate icons in the status bar while their download is still in progress? That would help with being sure the app actually started downloading. It could go back to only showing one icon for finished downloads to reduce clutter.
