### ISSUE TITLE
MediaView buttons refresh after an image is loaded

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1895]
When opening an image, the bottom row buttons are displayed (Go to Comments, Download, Menu); once the image/GIF is finished loading, those buttons "flash" because they refresh with the image/GIF. I think this has been like that for a while, but I can't test right now to confirm.

This doesn't appear to happen when viewing an Album; instead, the buttons aren't displayed until the first image of the album is loaded.

**Comment by ccrama** [comment]
They don't refresh, the size change listener on the SubsamplingScaleImageView is set to change the alpha of the images on zoom in, and is activated for a second while the image is loaded (for some reason). A fix to this would be adding the zoom changed listener after the image is displayed

**Comment by ccrama** [comment]
Added a 2 second delay to setting the listener, seems to work better now!
