### ISSUE TITLE
Text cut off (without ... or anything)

### ISSUE THREAD

**Issue by ente3000** [ccrama/Slide#1898]
Slide version: 5.3.9.5
Android version: 6.0.1

Screenshot: http://imgur.com/5AK3QCi
Post: https://reddit.com/r/SCP/comments/4rx4no/fuel_thermostat_that_wants_to_kill_you/

**Comment by Alexendoo** [comment]
Rel: #1618 #1812 #1881

**Comment by ccrama** [comment]
Same as those, closing
