### ISSUE TITLE
Text in tables is always aligned left

### ISSUE THREAD

**Issue by ente3000** [ccrama/Slide#1899]
Slide version: 5.3.9.5
Android version: 6.0.1

Slide doesn't align text inside tables correctly.
Screenshot: http://imgur.com/VXsxoeG
Post: https://www.reddit.com/r/test/comments/4ryfsa/test/

**Comment by ccrama** [comment]
This would be quite difficult to achieve, I think it's fine the way it is unless there is a specific reason to do this

**Comment by ente3000** [comment]
Yeah, I think you're right

**Comment by Alexendoo** [comment]
@ente3000 Although it may or may not be fixed, it's good to keep the issue open as it serves as documentation

**Comment by ccrama** [comment]
Actually the info about the position of the text is stripped away when we parse and format the HTML, I don't think this will be fixed in the future

**Comment by ccrama** [comment]
@Deadleg  fixed this in a recent PR!
