### ISSUE TITLE
Add gfycat as separate handler to gifs

### ISSUE THREAD

**Issue by KaliK0t** [ccrama/Slide#190]
images, albums and gifs open fine in opengur if I uncheck the handler in the settings but gfycats open an external chrome browser.

Is there any way around this? or can I just select gfy for the internal viewer and have the rest open in opengur

**Comment by ccrama** [comment]
Gfycats are treated as gifs in my app. I transform every gif to a gfycat before showing it anyway, but are you asking for a separate setting to open gfycats in a browser instead of the gif view?

**Comment by KaliK0t** [comment]
Yes if thats not too much work. If i set gifs to open in an external app
(opengur) gfycat just throws me to an external chrome browser which makes
me sad

**Comment by ccrama** [comment]
Ah gotcha. Will do!

**Comment by ccrama** [comment]
Now you can specify urls to open externally always! Should fix this issue
