### ISSUE TITLE
Make "Go to user" a text field

### ISSUE THREAD

**Issue by ente3000** [ccrama/Slide#1900]
Slide version: 5.0.9.3
Android version: 6.0.1

This one's not really an issue but rather a suggestion:
I'd remove the "Go to user" button/tab and instead make it a text field like "Go to subreddit".

Here's a concept I made (I'm designer, not programmer): 
![slide_concept](https://cloud.githubusercontent.com/assets/8181990/16707498/a644ac9c-45d0-11e6-93af-f5ee4d1e1fb6.png)

Also [the project file](https://drive.google.com/file/d/0B7ix-E7JPJ2iWWMwVW9tejFMQ2M/view?usp=sharing) in case anyone wants it although I don't think so.

**Comment by ccrama** [comment]
The main issue with this is the "Go to subreddit" field directly changes the subreddits shown below in the list, while the user is a different dialog with no suggestions that allows a user to go straight to a user. They complete different actions, and therefore look and behave differently

**Comment by Nxt3** [comment]
This only saves one click for an action that doesn't even happen that often. If you're accessing someone often, why not add them as a friend so you can get to them through the Profile drop down? If you wanted to get to a user you saw on a comment or post, that's what the overflow menu is for. Just my thoughts.
