### ISSUE TITLE
Reddit native image URLs not resolving

### ISSUE THREAD

**Issue by nielmistry** [ccrama/Slide#1904]
Slide version: 5.3.9.3
Android version: 6.0.1

When externally opening redditupload image links, the app replaces & with `&amp; `

Using the internal image viewer is fine. Problem only occurs when sharing the link or opening it in an external application. Possibly the sharing mechansim used to hand off the link to the external program (intents? not really familiar) is adding the &amp

Evident with this Reddit post:https://reddit.com/r/mildlyinteresting/comments/4s79wd/my_local_botanical_garden_is_letting_people_in/

Slide goes to this URL : https://i.reddituploads.com/e8679fb4499b452d817f908b8c88c952?fit=max&amp;h=1536&amp;w=1536&amp;s=8d780d5d21b6758ab34f78ea885b7d4d

Works when `&amp; ` is replaced with & : https://i.reddituploads.com/e8679fb4499b452d817f908b8c88c952?fit=max&h=1536&w=1536&s=8d780d5d21b6758ab34f78ea885b7d4d

**Comment by nielmistry** [comment]
Sorry I meant when &amp; is replaced with &

**Comment by nielmistry** [comment]
gdi markdown. Slide replaces & with &amp ;  (ignore the space)

**Comment by nielmistry** [comment]
Reverting to 5.1.3 and enabling the internal image viewer solves the problem!

**Comment by ccrama** [comment]
Actually, the issue is that Reddit returned the escaped link, and Slide didn't un-escape it. Has been fixed for the next version, thank you for the detailed report!
