### ISSUE TITLE
Subreddit search showing subreddits I'm subscribed to on another user

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#1907]
I have 2 accounts linked to slide, and when I search for subreddits, subreddits I'm subscribed to on the other account are showing up in the results. How can I remove them?

**Comment by ccrama** [comment]
When you visit a subreddit, it gets added to the list of subs to show. This is intended behavior, but you can delete them all in Settings > History

**Comment by kufii** [comment]
the history should really be per account though. Kinda ruins the entire point of using multiple accounts, I want to do stuff without it showing up in the history for my main account

**Comment by ccrama** [comment]
IMO, it should stretch between accounts and it is coded to be between accounts this way. Changing it would also require resetting everyone's history and I don't think the trade off is worth that.

Submissions and other data are on a per-account basis, but history logs everything you do in Slide

**Comment by kufii** [comment]
ok as a compromise, could you make the save history option a per user setting? that way I can just disable it for the second account
