### ISSUE TITLE
Switch between accounts 

### ISSUE THREAD

**Issue by Eliaskh77** [ccrama/Slide#1915]
Slide version:5.3.9.5
Android version:5.1.1

I use the last version ( beta) and I have problem when I want to switch between my accounts, I have 2 account and when I try to switch, I should try more than once and sometimes the front page is from my account but the subreddit that show behind them is from my other account

**Comment by ccrama** [comment]
That's caused by an old bug when you added the accounts. Remove them and re-add them, and that will fix this issue
