### ISSUE TITLE
Crash when using "go to subreddit" option

### ISSUE THREAD

**Issue by notnsane** [ccrama/Slide#1916]
Slide version: 5.3.9.5
Android version: 5.1

I use F-Droid version which it seems to be more up-to-date than Play Store version:

1. Do a clean Slide install
2. Use "go to subreddit" option in sidebar
3. App crashes.

Another way to get this crash:

1. Clean Slide install
2. Go to Settings
3. Go to About
4. Tap on '/r/'slideforreddit' item
5. App crashes.

Crash text is "Unfortunately, Slide has stopped" and gives me an "OK" option.

**Comment by ccrama** [comment]
I'm not noticing any crashing or getting reports of this. Is there any way you could get a stacktrace of the issue?

**Comment by notnsane** [comment]
Just googled it how to do it and no, I'm not a programmer so no idea how to do that.

Have you tried using the app from the F-Droid store?

I'll add new steps for another way to get this crash, might help. It's has a 100% reproduction rate.

**Comment by ccrama** [comment]
I'm currently on that, no issues here

**Comment by notnsane** [comment]
I just reproduced it on my tablet (a cheap chinese one) running Android 4.4. Exact same error. I _never_ had Slide installed on my tablet before.

I also installed 5.3.9.3 on both devices (from F-Droid) and got no crash with the repro steps I wrote before, so it's definitely something introduced in 5.3.9.5

What exactly happens, is that the loading circle appears for a second, then app crashes.

**Comment by ccrama** [comment]
What loading circle are you referring to? There are no loading circles in Slide at all. We might be looking at two different things

**Comment by notnsane** [comment]
this? http://www.wallpaperama.com/post-images/forums/200903/07p-6606-loading-photo.gif

**Comment by ccrama** [comment]
Yes, none of those exist in Slide

**Comment by notnsane** [comment]
That's weird. It's a white circle with a spinner, it appears also when you manually force reload the app by swiping down and you are at the beginning of the feed, it has a full animation and everything. I'll try taking a screenshot.

![screenshot_2016-07-13-20-05-44-01](https://cloud.githubusercontent.com/assets/7162375/16822866/160eb82a-4936-11e6-90f9-fc632c1713b8.jpeg)

You're saying this doesn't exist in Slide?

---

Just thinking loud here, may this be caused by a "slow" network? Maybe that's why you don't see the spinner (though you should see the reload feed icon...) I live in Argentina and have a way slower ping than you since I'm quite far away from the Reddit servers. Maybe you can simulate this? Are you testing this on a < 5.1 device?

**Comment by ccrama** [comment]
Oh that's quite different, yeah that's a pull to refresh. I thought you were talking about a loading circle in the sidebar. 

The network speed should have nothing to do with it, I was just in an area with 0.2 mb/s internet and got no crashes due to this. 

Also, out of the few thousand alpha testers using that same version of Slide, there are no crash reports dealing with this. Are there any other factors you can think of that would cause this? What sub are you trying to access?

**Comment by notnsane** [comment]
Argh, I have to agree, there's no way to pinpoint this issue unless I get a stacktrace of sorts. There could be a thousand variables on why Slide is crashing for me. I'll try testing this again in a new Slide version, but it's weird it started happening on two different devices.

It seems the app crashes when the search finds a subreddit and tries to load its feed (like /r/slideforreddit). The app does NOT crash if no subreddit was found - say, try searching for 'asdasdasdasd123', there will be a "not found" message, but no crash.

Feel free to close it... sadly I'd have to start using another app if this isn't automagically fixed in the next versions :cry:

**Comment by slio** [comment]
`
I/Timeline(28424): Timeline: Activity_launch_request id:me.ccrama.redditslide time:109515887
I/ActivityManager(  830): START u0 {cmp=me.ccrama.redditslide/.Activities.MainActivity} from pid 28424
I/dalvikvm(28424): Could not find method android.view.Window.setStatusBarColor, referenced from method me.ccrama.redditslide.Activities.MainActivity.onCreate
I/dalvikvm(28424): Could not find method android.view.Window.setStatusBarColor, referenced from method me.ccrama.redditslide.Activities.MainActivity.updateColor
E/dalvikvm(28424): Could not find class 'android.app.ActivityManager$TaskDescription', referenced from method me.ccrama.redditslide.Activities.BaseActivity.setRecentBar
W/dalvikvm(28424): VFY: unable to resolve new-instance 27 (Landroid/app/ActivityManager$TaskDescription;) in Lme/ccrama/redditslide/Activities/BaseActivity;
I/dalvikvm(28424): Could not find method android.view.Window.setStatusBarColor, referenced from method me.ccrama.redditslide.Activities.BaseActivity.themeSystemBars
D/dalvikvm(28424): DexOpt: unable to opt direct call 0x0074 at 0x2e in Lme/ccrama/redditslide/Activities/BaseActivity;.setRecentBar
I/ActivityManager(  830): Displayed me.ccrama.redditslide/.Activities.MainActivity: +528ms (total +962ms)
I/Timeline(  830): Timeline: Activity_windows_visible id: ActivityRecord{420f9250 u0 me.ccrama.redditslide/.Activities.MainActivity t495} time:109516699
I/dalvikvm(28424): Could not find method android.widget.ImageView.<init>, referenced from method me.ccrama.redditslide.Views.MaxHeightImageView.<init>
I/Timeline(28424): Timeline: Activity_launch_request id:me.ccrama.redditslide time:109534900
I/ActivityManager(  830): START u0 {cmp=me.ccrama.redditslide/.Activities.SubredditView (has extras)} from pid 28424
I/ActivityManager(  830): Displayed me.ccrama.redditslide/.Activities.SubredditView: +320ms
I/Timeline(  830): Timeline: Activity_windows_visible id: ActivityRecord{421067a0 u0 me.ccrama.redditslide/.Activities.SubredditView t495} time:109535468
E/AndroidRuntime(28424): Process: me.ccrama.redditslide, PID: 28424
E/AndroidRuntime(28424): 	at me.ccrama.redditslide.Activities.SubredditView.doSubOnlyStuff(SubredditView.java:370)
E/AndroidRuntime(28424): 	at me.ccrama.redditslide.Activities.SubredditView.access$500(SubredditView.java:96)
E/AndroidRuntime(28424): 	at me.ccrama.redditslide.Activities.SubredditView$AsyncGetSubreddit.onPostExecute(SubredditView.java:1223)
E/AndroidRuntime(28424): 	at me.ccrama.redditslide.Activities.SubredditView$AsyncGetSubreddit.onPostExecute(SubredditView.java:1214)
W/ActivityManager(  830):   Force finishing activity me.ccrama.redditslide/.Activities.SubredditView
W/ActivityManager(  830): Activity pause timeout for ActivityRecord{421067a0 u0 me.ccrama.redditslide/.Activities.SubredditView t495 f}
I/ActivityManager(  830): Process me.ccrama.redditslide (pid 28424) has died.
I/WindowState(  830): WIN DEATH: Window{421cfd90 u0 me.ccrama.redditslide/me.ccrama.redditslide.Activities.MainActivity}
I/WindowState(  830): WIN DEATH: Window{42207be0 u0 me.ccrama.redditslide/me.ccrama.redditslide.Activities.SubredditView}
I/ActivityManager(  830): Start proc me.ccrama.redditslide for activity me.ccrama.redditslide/.Activities.MainActivity: pid=28489 uid=10115 gids={50115, 3003, 1028, 1015}
D/ActivityThread(28489): handleBindApplication:me.ccrama.redditslide
I/MultiDex(28489): MultiDexExtractor.load(/data/app/me.ccrama.redditslide-2.apk, false)
I/dalvikvm(28489): Could not find method android.view.Window.setStatusBarColor, referenced from method me.ccrama.redditslide.Activities.MainActivity.onCreate
I/dalvikvm(28489): Could not find method android.view.Window.setStatusBarColor, referenced from method me.ccrama.redditslide.Activities.MainActivity.updateColor
E/dalvikvm(28489): Could not find class 'android.app.ActivityManager$TaskDescription', referenced from method me.ccrama.redditslide.Activities.BaseActivity.setRecentBar
W/dalvikvm(28489): VFY: unable to resolve new-instance 27 (Landroid/app/ActivityManager$TaskDescription;) in Lme/ccrama/redditslide/Activities/BaseActivity;
I/dalvikvm(28489): Could not find method android.view.Window.setStatusBarColor, referenced from method me.ccrama.redditslide.Activities.BaseActivity.themeSystemBars
D/dalvikvm(28489): DexOpt: unable to opt direct call 0x0074 at 0x2e in Lme/ccrama/redditslide/Activities/BaseActivity;.setRecentBar
I/ActivityManager(  830): Displayed me.ccrama.redditslide/.Activities.MainActivity: +971ms
I/Timeline(  830): Timeline: Activity_windows_visible id: ActivityRecord{420f9250 u0 me.ccrama.redditslide/.Activities.MainActivity t495} time:109542161
I/DrWeb   ( 1495): DrWeb_22 /storage/emulated/0/Android/data/me.ccrama.redditslide/cache/gifs/journal
I/DrWeb   ( 1495): DrWeb_22 /storage/emulated/0/Android/data/me.ccrama.redditslide/cache/journal
I/ActivityManager(  830): Killing 28489:me.ccrama.redditslide/u0a115 (adj 9): remove task
I/WindowState(  830): WIN DEATH: Window{42411bf8 u0 me.ccrama.redditslide/me.ccrama.redditslide.Activities.MainActivity}
I/DrWeb   ( 1495): DrWeb_22 /storage/emulated/0/Android/data/me.ccrama.redditslide/cache/gifs/journal
`
Hope this logcat helps. 
Slide version: 5.3.9.5
Android version: CM11S

To elaborate, starting this version I have been getting crash on Slide on searching for a subreddit, the crash does not happen once the same subreddit is added in "My Subscriptions"
PS: Do we need to login to reddit to enable NSFW content/subs? Currently searching for any NSFW sub shows a blank page, it is a separate issue and it's ok if we focus on one thing at a time.

**Comment by notnsane** [comment]
Thank you so much slio for not making me sound more crazy than I already am =P 

Hope the logcat helps to pintpoint the issue.

**Comment by ccrama** [comment]
Thanks for the report @silo, but unfortunately there is no crash stack trace in that light snippet. Should say some sort of error, a few lines, then "caused by". And no, you shouldn't have to log in

**Comment by ccrama** [comment]
Figured it out though, it was a single ! that was added to the logged in check, being logged out was the issue!
