### ISSUE TITLE
Subreddit individual 'keyword' filter

### ISSUE THREAD

**Issue by notnsane** [ccrama/Slide#1917]
Slide version: any
Android version: any

This is a suggestion/feature request.

Say that I want to filter the keyword 'pokemon go' in /r/all but not in /r/gaming, currently it's impossible to do this. Maybe /r/all it's a bad example since it's a _special_ subreddit, but I think you know what I mean.

Another example: say I want to filter 'oneplus' in /r/android because I don't have a One Plus device, but I want to read news about them in /r/rall if they do appear.

I think this feature could be on the right sidebar of the subreddit (where we have "Sort mode, Refresh, Search", etc.)

**Comment by ccrama** [comment]
I have instead implemented subreddit flair filters, and you should be able to filter the oneplus flair from r/android if you'd like :)
