### ISSUE TITLE
Slide Widget skips Slide subreddit filter

### ISSUE THREAD

**Issue by notnsane** [ccrama/Slide#1918]
Slide version: 5.3.9.5
Android version: 5.1

Not sure if this is a bug or a "feature", haha, but raising an issue anyways just in case.

1. Open /r/all
2. Filter any subreddit (top post would be good, remember the post title)
3. Add a Slide widget to your homescreen with /r/all as the subreddit chosen to be displayed
4. Observe that the top post appears, as if the subreddit hasn't been filtered

**Comment by ccrama** [comment]
Fixed, good find!
