### ISSUE TITLE
404 Gfycat URLs causes ShadowBox mode to close

### ISSUE THREAD

**Issue by fbis251** [ccrama/Slide#1921]
Slide version: 5.3.9.3 and latest git commit (b12927a962866d208d0621cf3da6f0916d5b4b45)
Android version: 5.1, 6.0

Steps to reproduce
1) Open shadowbox mode
2) Encounter a gfycat post where the API returns a 404 for the video URL (video URL has to be null)
3) "GIF not found" dialog comes up, if you tap OK Shadowbox Mode closes

You can test this on /r/slideshowtest with the post called [gfycat error non-existent](https://www.reddit.com/r/slideshowtest/comments/4izkiq)

**Comment by ccrama** [comment]
Fixed, just had to set closeIfNull to false in the MediaFragment GifUtils.AsyncLoadGif line
