### ISSUE TITLE
Load more in offline mode

### ISSUE THREAD

**Issue by prashantkhurana** [ccrama/Slide#1925]
In offline mode we should load more posts and with more depth. The current number of posts loaded is too less , and so when you read something, you wished for more children comments. 

If we agree, I can work on this, after deciding if we want this to be an option in the setting, or just make it default.

**Comment by ccrama** [comment]
Loading more comments would not work for offline mode, but we could make it load more submissions

**Comment by prashantkhurana** [comment]
I was playing with this and wouldn't changing 
`JsonNode n = getSubmission(new SubmissionRequest.Builder(s.getId()).sort(CommentSort.CONFIDENCE).build());`
in CommentCacheAsync to 
`JsonNode n = 
getSubmission(new SubmissionRequest.Builder(s.getId()).limit(100).depth(10).sort(sortType).build());`

get more comments and more depth? I can see that this works.

**Comment by ccrama** [comment]
That will require lots of extra requests, making caching take significantly longer (if the depth is more, for each MoreChild object, it sends a request to get more comments)

**Comment by prashantkhurana** [comment]
oh yaa, agreed. But when I am caching posts for offline sync, I do want more comments with more depth to cache as I would be in subway for a long time. For me that is the point of offline mode.

**Comment by ccrama** [comment]
Ah gotcha. If you would like to add an option for deeper comments, be my guest :)

If you need help, let me know

**Comment by prashantkhurana** [comment]
Awesome, I'll add an option

**Comment by ccrama** [comment]
I think this was done with your last PR. Thanks :)
