### ISSUE TITLE
Laggy scrolling and updating in some settings subwindows

### ISSUE THREAD

**Issue by zlsa** [ccrama/Slide#1926]
Slide version: 5.3.9.3
Android version: 5.1.1 (CM 12.1)
Hardware: Galaxy Nexus Verizon (toro)

Some settings subwindows are very, very slow to scroll and update. Here's a list of those which are slow:

* General
* Post layout
* Comments
* Link handling
* History
* Data saving

I don't think this is a result of displaying tons of information; they're much slower than even the main post view. I don't have any numbers to back this up, but I'd guess it updates 4-8 times per second. (I do have a very old Galaxy Nexus, too, but I suspect this is a Slide issue that's more apparent on slow hardware.)

"Main Theme" and "Filters" both feel a bit laggy, but not nearly as bad as the above.

**Comment by Nxt3** [comment]
This isn't an issue for my 6P or Pixel. I really think this is an old hardware issue.

**Comment by zlsa** [comment]
Yeah, it may be. @ccrama said it was possibly a checkbox/toggle issue.

**Comment by ccrama** [comment]
I have had a lot of reports of it being much smoother now, assuming it's now fixed!

**Comment by zlsa** [comment]
I now have Marshmallow on the same device, and it's much smoother now. I'm not sure if it was a Marshmallow change or a Slide change. Either way, it works for me now.

**Comment by ccrama** [comment]
Glad to hear that!
