### ISSUE TITLE
Subreddit refreshes after sliding out from image viewer

### ISSUE THREAD

**Issue by matty1086** [ccrama/Slide#1928]
I believe this just started in one of these past alpha releases, and seems to only occurs after subscribing to a subreddit.

Repro steps:
1) Open this comment in slide (as example for a linked sub to subscribe)

https://www.reddit.com/r/AskReddit/comments/4t4g2q/what_weird_misconception_did_you_have_as_a_kid/d5ejcfh?context=3

2) Tap link to open /r/alanon/
3) Open sidebar for /r/alanon/ and subscribe
4) slide back to post
5) slide back to list of posts
6) tap an image thumbnail or something that opens in the internal browser.
7) Slide back from image viewer / internal browser
8) Subreddit, will refresh all posts
9) Steps 6-8 can now be reproduced until closing the app from recents and reopening.

Result: Entire post list reloads
Expected: Not that. :)

Slide version: 5.3.9.5 Alpha 3
Android version: N Dev Preview 4

**Comment by ccrama** [comment]
Both of your issues were caused by one small thing, has been fixed as well!
