### ISSUE TITLE
Post lists refreshes and defaults to /r/all after subscribing to new sub

### ISSUE THREAD

**Issue by matty1086** [ccrama/Slide#1929]
Repro steps:
1) Browse frontpage. This is what the app defaults to opening to for me.
2) Open a post
3) Find a comment with a linked subreddit you're not subscribed to
4) Tap link to open subreddit
5) subscribe to subreddit
6) slide back to post
7) slide back to frontpage

Result: frontpage refreshes and defaults to /r/all
Expected: No refresh (which im not sure is possible), but at least reload frontpage, or whatever subreddit I was viewing instead of defaulting to /r/all.

Ideally, no refresh would occur either as it is very annoying losing place in my scrolling the post list.

Slide version: 5.3.9.5 Alpha 3
Android version: N Dev Preview 4

**Comment by ccrama** [comment]
Fixed that one, thanks for the report!
