### ISSUE TITLE
Incorrect paddings

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#193]
Using [this](http://i.imgur.com/purztmL.png) card layout settings, Slide has two incorrect paddings.
1. At top: The padding between the top of the first card and the bottom of the tabs is much bigger than the other paddings. 
2. At bottom before new posts are loaded: No padding between bottom and last card.

**Comment by The0x539** [comment]
Also, between the cards is bigger than between a card and the side.

**Comment by ccrama** [comment]
Fixed a few commits back

**Comment by The0x539** [comment]
still happening in the build you gave us just now

**Comment by ccrama** [comment]
I changed it and it's all the same. You can take a look at the resources file (submission_bigcard)

**Comment by Alexendoo** [comment]
Seems to be an issue with all card layouts, including list for `1.`, but the second isn't noticeable due to the nature of lists

**Comment by ccrama** [comment]
Fixed 2 commits ago!
