### ISSUE TITLE
When typing a subreddit name in the hamburger menu it creates a weird scrolling animation

### ISSUE THREAD

**Issue by Canaaduh** [ccrama/Slide#1930]
Slide version: 5.3.9.5 - alpha3
Android version: N - Beta 4 (June security patch)

This bug only occurs when typing a subreddit in the hamburger menu using a different keyboard other than the Google Keyboard. Currently I'm using Fleksy and the issue is that when you enter a letter in the "go to subreddit" it starts scrolling on its own.

**Comment by ccrama** [comment]
It scrolls to the top, this is intended

**Comment by Canaaduh** [comment]
Here's a video of the issue: 

https://streamable.com/wvwh

**Comment by ccrama** [comment]
Looks like it's an issue with your keyboard more than a Slide issue, especially if it doesn't happen with the stock keyboard

**Comment by Canaaduh** [comment]
Ah okay. This issue occurs with the following keyboards:

Fleksy
Chrooma
Swift key
Swype

Are you able to replicate this bug on your device with a keyboard other than stock?

**Comment by Alexendoo** [comment]
I'm using Fleksy and no issue here, it _could_ be an N issue

**Comment by ccrama** [comment]
Merging with #1984
