### ISSUE TITLE
Opening a gif occasionally pulls up only a black screen until the gif is re-opened

### ISSUE THREAD

**Issue by evanbishop** [ccrama/Slide#1931]
Slide version: 5.3.9.3
Android version: 6.0.1

After tapping on a gif to load it, Slide loads the gif completely but only pulls up a black screen and does not play the gif. I have to back out and re-open it, which causes it to begin playing immediately.

Here's a screen recording of this bug:
https://www.youtube.com/watch?v=KKBYe-wf2Es

**Comment by ccrama** [comment]
Is there any way to reproduce this? I haven't run into this

**Comment by evanbishop** [comment]
It pretty much seems to happen at random, I haven't found any correlation between when it happens and when it doesn't.

**Comment by slio** [comment]
Slide version : 5.3.9.5
OS: CM11S
You may want to try sub "reactiongifs" , sooner than later you should be able to reproduce this. Happens most of the times when cache is close to > 200-300 mb. Gifutils.Java doesn't start, first log is once the gif downloaded and did not play and second log  is the action of pressing back and then clicking gif link again.
Doesn't show much in logs and re-visiting the same gif link after clearing cache doesn't help either.


`I/Timeline(  842): Timeline: Activity_windows_visible id: ActivityRecord{42d09620 u0 me.ccrama.redditslide/.Activities.CommentsScreenSingle t336} time:54609556
I/Timeline(28682): Timeline: Activity_launch_request id:me.ccrama.redditslide time:54617286
I/ActivityManager(  842): START u0 {cmp=me.ccrama.redditslide/.Activities.MediaView (has extras)} from pid 28682
I/dalvikvm(28682): Could not find method android.view.SurfaceView.<init>, referenced from method me.ccrama.redditslide.Views.MediaVideoView.<init>
V/(GifUtils.java:139)(28682): Path is file:///storage/emulated/0/Android/data/me.ccrama.redditslide/cache/gifs/1ri93avuntfsl67tqq56ckupg.0
D/Utils   (18409): printFileName fd(23) -> /storage/emulated/0/Android/data/me.ccrama.redditslide/cache/gifs/1ri93avuntfsl67tqq56ckupg.0
E/FFmpegExtractor(18409): android-source:0xb787ba18|file:/storage/emulated/0/Android/data/me.ccrama.redditslide/cache/gifs/1ri93avuntfsl67tqq56ckupg.0: avformat_open_input failed, err:Invalid data found when processing input
W/VideoView(28682): Unable to open content: file:///storage/emulated/0/Android/data/me.ccrama.redditslide/cache/gifs/1ri93avuntfsl67tqq56ckupg.0
W/VideoView(28682): 	at me.ccrama.redditslide.Views.MediaVideoView.openVideo(MediaVideoView.java:441)
W/VideoView(28682): 	at me.ccrama.redditslide.Views.MediaVideoView.access$1900(MediaVideoView.java:31)
W/VideoView(28682): 	at me.ccrama.redditslide.Views.MediaVideoView$7.surfaceCreated(MediaVideoView.java:240)
I/ActivityManager(  842): Displayed me.ccrama.redditslide/.Activities.MediaView: +570ms
I/Timeline(  842): Timeline: Activity_windows_visible id: ActivityRecord{42d1a5c0 u0 me.ccrama.redditslide/.Activities.MediaView t336} time:54618145`

----------------------------------------------------------------------------------------------------------------------------------------------------------------
`I/Timeline(28682): Timeline: Activity_launch_request id:me.ccrama.redditslide time:55029315
I/ActivityManager(  842): START u0 {cmp=me.ccrama.redditslide/.Activities.MediaView (has extras)} from pid 28682
V/(GifUtils.java:139)(28682): Path is file:///storage/emulated/0/Android/data/me.ccrama.redditslide/cache/gifs/neb762041hnyvje1crsw3pvq.0
D/Utils   (18409): printFileName fd(23) -> /storage/emulated/0/Android/data/me.ccrama.redditslide/cache/gifs/neb762041hnyvje1crsw3pvq.0
I/ActivityManager(  842): Displayed me.ccrama.redditslide/.Activities.MediaView: +285ms
I/Timeline(  842): Timeline: Activity_windows_visible id: ActivityRecord{4265abc0 u0 me.ccrama.redditslide/.Activities.MediaView t336} time:55029887`

**Comment by ccrama** [comment]
That means the video format is not supported by your device's codek @silo. Unfortunately nothing I can do about it

**Comment by ccrama** [comment]
I made it try twice to show the video, hopefully fixes the issue for you guys
