### ISSUE TITLE
invite to modteam button? 

### ISSUE THREAD

**Issue by Georgiel** [ccrama/Slide#1934]
Can't seem to find it,  maybe, if it does exist,  it needs to be easier to find. 

If it doesn't, I'd say it's an essential piece of the mod toolkit that's missing.

**Comment by l3d00m** [comment]
A very small portion of our users are mods, a much smaller portion is actively using Slide for modding their subs and I can't imagine that more than a handful of people would be using this feature. 

As it would take some time to implement the feature, I don't think it would make sense to do it.

**Comment by Georgiel** [comment]
Apart from the fact that thanks to another unfixed bug,  it's not possible to open reddit in browser anymore once installed,  so it's a necessary feature.

**Comment by l3d00m** [comment]
I think fixing that bug would be the easier and better way.

**Comment by Alexendoo** [comment]
@Georgiel could you open an issue for that bug? Would definitely need to be fixed either way though I can't reproduce it myself

**Comment by Georgiel** [comment]
@alexandoo think it's still open.  I'll find it and link it.

**Comment by Georgiel** [comment]
https://github.com/ccrama/Slide/issues/810

aha, closed cause it seemed to fix for him, but for me it's still doing the exact same behaviour he's displayed.
