### ISSUE TITLE
Can't open this gif

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1936]
[Imgur gifv](https://reddit.com/r/funny/comments/4tfol1/fedex_thanks_for_getting_these_to_me_safe_and/d5gyt6h?context=3)

Not sure if this is a Slide issue. Might be related to #1931

**Comment by ccrama** [comment]
That gif isn't loading in browser either

**Comment by Nxt3** [comment]
Loaded for me externally. It's a rickroll.

**Comment by ccrama** [comment]
I can't load it in chrome

**Comment by ccrama** [comment]
Now it loads, probably has to do with the ? In the url

**Comment by Nxt3** [comment]
There isn't a "?" in the URL as far as I can tell. I can get it to open on Desktop in Chrome, externally in the Imgur app, and externally in Chrome on Android.

If you don't think this is anything wrong with Slide, close this issue. Not sure myself.

**Comment by slio** [comment]
Slide version: 5.3.9.5
OS: CM11S

Could it be the fact the link is m.imgur but opens in i.imgur ? My log, attached below, it is not saving the file as intended and shows size as 0 in the slide app.

`I/Timeline(  842): Timeline: Activity_windows_visible id: ActivityRecord{42d09620 u0 me.ccrama.redditslide/.Activities.CommentsScreenSingle t336} time:54609556
I/Timeline(28682): Timeline: Activity_launch_request id:me.ccrama.redditslide time:54617286
I/ActivityManager(  842): START u0 {cmp=me.ccrama.redditslide/.Activities.MediaView (has extras)} from pid 28682
I/dalvikvm(28682): Could not find method android.view.SurfaceView.<init>, referenced from method me.ccrama.redditslide.Views.MediaVideoView.<init>
V/(GifUtils.java:139)(28682): Path is file:///storage/emulated/0/Android/data/me.ccrama.redditslide/cache/gifs/1ri93avuntfsl67tqq56ckupg.0
D/Utils   (18409): printFileName fd(23) -> /storage/emulated/0/Android/data/me.ccrama.redditslide/cache/gifs/1ri93avuntfsl67tqq56ckupg.0
E/FFmpegExtractor(18409): android-source:0xb787ba18|file:/storage/emulated/0/Android/data/me.ccrama.redditslide/cache/gifs/1ri93avuntfsl67tqq56ckupg.0: avformat_open_input failed, err:Invalid data found when processing input
W/VideoView(28682): Unable to open content: file:///storage/emulated/0/Android/data/me.ccrama.redditslide/cache/gifs/1ri93avuntfsl67tqq56ckupg.0
W/VideoView(28682): 	at me.ccrama.redditslide.Views.MediaVideoView.openVideo(MediaVideoView.java:441)
W/VideoView(28682): 	at me.ccrama.redditslide.Views.MediaVideoView.access$1900(MediaVideoView.java:31)
W/VideoView(28682): 	at me.ccrama.redditslide.Views.MediaVideoView$7.surfaceCreated(MediaVideoView.java:240)
I/ActivityManager(  842): Displayed me.ccrama.redditslide/.Activities.MediaView: +570ms
I/Timeline(  842): Timeline: Activity_windows_visible id: ActivityRecord{42d1a5c0 u0 me.ccrama.redditslide/.Activities.MediaView t336} time:54618145`

**Comment by ccrama** [comment]
That means the gif was mis-linked, and there is really no way to get around this. The Imgur website knows if an m. link was supposed to be m. or i. and corrects accordingly, while there is really no way for Slide to know that. It is impossible to download the gif as linked if you try downloading through any other web service
