### ISSUE TITLE
Toolbar title not horizontally aligned

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1940]
No idea if it's always been like this, but I noticed it today.

http://imgur.com/BpupEBd

**Comment by ccrama** [comment]
Google changed up the paddings, is this now fixed?

**Comment by Nxt3** [comment]
Nope. :| Do you not experience it?

**Comment by ccrama** [comment]
I can't really tell :s

**Comment by Nxt3** [comment]
Hm. Not really sure what to do. It definitely was lined up at one point. It
must be Goog's fault, so don't worry about it. :P

**Comment by ccrama** [comment]
Is the issue present on any other view?

**Comment by Nxt3** [comment]
It's only noticeably to me if the hamburger menu is present. No other view has that.

**Comment by ccrama** [comment]
Ah alright. I'll blame it on Google, too
