### ISSUE TITLE
Notifications for image downloads in progress make notification shade laggy

### ISSUE THREAD

**Issue by touzainanboku** [ccrama/Slide#1943]
Slide version: 5.4-alpha1
Android version: 6.0.1

When an image is in the process of being downloaded the notification shade becomes extremely laggy. I'm guessing the progress bar is causing issues, since it's not laggy anymore once it finishes downloading. 
Since it currently seems to only shows progress in two states (0% and 100%), it might be a better idea to switch to an indeterminate progress bar (ones that only show that something is in progress without actually showing how much is done) until a better solution for this is found.

**Comment by ccrama** [comment]
I'm using standard android code to do the notification progressbar, don't know if there is any way to really remedy this

**Comment by touzainanboku** [comment]
I see. 
Not sure how it's supposed to be, but for me it only shows 0% and 100% progress right now, meaning it basically doesn't really show progress at all. If that's the case for everyone maybe an indeterminate progress bar would be a good idea, assuming it doesn't lag like the current one (although maybe what I'm experiencing is device specific).

**Comment by Nxt3** [comment]
Yeah mine goes from 0 -> 100% and makes my notification tray lag a bit too. Weird.

**Comment by ccrama** [comment]
Made it update once every 10 percent instead of every byte, should fix this issue

**Comment by touzainanboku** [comment]
Sorry for bumping this after so long, but it's still pretty laggy for me, although it does properly show progress. 

> update once every 10 percent

Unless I'm misunderstanding how this works, this means the progress bar in the notification should update roughly 10 times in total right? That makes sense to me considering the [code](https://github.com/ccrama/Slide/blob/2225384912d192fa4082d50f94d62afdb1811d43/app/src/main/java/me/ccrama/redditslide/Notifications/ImageDownloadNotificationService.java#L95), but it seems to update way more frequently than that, leading to lag when numerous large images are downloaded. Is it working as intended on your side?
