### ISSUE TITLE
Crash when searching for subreddit within hamburger menu

### ISSUE THREAD

**Issue by Abhishek-Mohan** [ccrama/Slide#1944]
Slide version: 5.4-alpha 1
Android version: 6.0.1

So there is a problem with opening a subreddit when you search from it within the hamburger menu. 
I have attached a video 
https://streamable.com/tfnb

Here is the logcat.  http://pastebin.com/G536bqih
The crash starts at line 102
If there is anything else i can submit let me know

**Comment by Alexendoo** [comment]
Hi, thanks for the report, this one is fixed in fe4936931bc3e8175dac998cb7a3d37cc2bab0e9 for the next release
