### ISSUE TITLE
Crashing when opening saved / Upvoted items

### ISSUE THREAD

**Issue by matty1086** [ccrama/Slide#1949]
App crashes when attempting to load saved / upvoted items.

Repro steps:

Open sidebar
Tap down arrow next to "You"
Tap saved
Crash while loading content

or

Open sidebar
Tap "You" (without expanding)
Slide across from Overview --> Comments --> Submitted --> Gilded -- Upvoted
Crash while loading content

or

Tap "You" (without expanding)
Slide the top bar so "Saved" comes into view
Tap saved
Crash while loading content

Slide version: 5.4 Alpha 2
Android version: N DP4

**Comment by Canaaduh** [comment]
Maybe force close the app and clear the cache. I'm running alpha 2 and dp4 and I'm not experiencing this issue anymore.

**Comment by matty1086** [comment]
Clearing cache didn't fix, but after taking a backup, clearing app data, resigning into Reddit then restoring the backup for settings seems to have done the trick. Saved items no longer crashes the app. Thanks! Closing this.
