### ISSUE TITLE
Downloading multiple images in quick succession causes FC

### ISSUE THREAD

**Issue by touzainanboku** [ccrama/Slide#1953]
Slide version: 5.4-alpha2
Android version: 6.0.1

If you try to download multiple images (say in an album) very quickly, the app will crash after a few images. Usually happens for me at 3~5 images. 
 I've reported the FC from my phone once, don't know if that helps. I've been trying to get a log for it, but so far I don't really know what I'm doing.

Note: by quickly I mean quickly tapping download and swiping to the next image, then tapping download again, and so on, without any pause.

**Comment by ccrama** [comment]
Your device is probably running out of memory, not much I can do on my end

**Comment by ccrama** [comment]
Was mistaken, has been fixed

**Comment by touzainanboku** [comment]
Thanks. While it doesn't seem to FC anymore according to my testing (the new 5.4 stable), downloading images in albums still seems unreliable in general. Issues I experience:
- even if not done in quick succession, when I download an image from an album, sometimes the app stops responding, and it doesn't allow me to swipe to the next or previous image for a few seconds. I even got a "app is not responding, would you like to force close?" popup. 
- if I quickly tap download on a few images and then close the album, it seems to stop downloading for some/all of them images, and they're nowhere to be found if I go to my directory in a file manager. This isn't always reproducible as far as I have seen. I'm guessing it only happens when you click download and then close the image/album before it even shows the image, in which case this is a very low priority issue, since you generally don't try to download an image before actually seeing it. Although I still don't think this is expected behavior. 
I doubt this is caused by some hardware bottleneck. While my device isn't the fastest thing anymore, a Snapdragon 801 and 3 gigs of RAM aren't low end specs either. 

Should I make separate issues for these?
