### ISSUE TITLE
"Share image" from lightbox crashes app

### ISSUE THREAD

**Issue by abraham** [ccrama/Slide#1955]
Slide version: v5.4
Android version: v6.0.1

This just started happening in the last couple of days. I think with the promotion of v5.4 from alpha to stable.

![screenshot_20160721-142139](https://cloud.githubusercontent.com/assets/3341/17035874/655cbab6-4f4f-11e6-8b5c-d7f1b679de43.png)

**Comment by Nxt3** [comment]
Yeah, I changed this last night. Can you get me a log? I can't reproduce this.

**Comment by abraham** [comment]
An ADB log?

**Comment by Nxt3** [comment]
Don't worry about it. I was able to reproduce it. I think I fixed it also. Thank you!
