### ISSUE TITLE
Crash when attempting to share an image (Potentially Android N) (Video Attached) 

### ISSUE THREAD

**Issue by Canaaduh** [ccrama/Slide#1956]
Slide version: 5.4
Android version: N DP5

After opening an image and selecting to share the image, slide immediately crashes. 

Video: https://streamable.com/kmlj

**Comment by Nxt3** [comment]
Pretty sure this is Android N; I just implemented changes to this last night and didn't run into any crashes on my 6P or Pixel--and I'm not on Nougat.

**Comment by Nxt3** [comment]
Actually, I don't think this is Android N related. There is another issue somewhere. I'll merge this with #1955
