### ISSUE TITLE
Overflow menu bug in profiles

### ISSUE THREAD

**Issue by miladmaz12** [ccrama/Slide#1957]
Why is there a overflow menu (Top, new, best, etc) in profiles? Is this a bug? 

http://imgur.com/a/R2kTK

Slide version: Latest 5.4
Android version: 6.0.1

**Comment by ccrama** [comment]
No, you can sort profiles by those parameters

**Comment by miladmaz12** [comment]
Ok, I see. By the way, I like this new update. Thank you dev.

**Comment by ccrama** [comment]
You're welcome, glad you're liking it!
