### ISSUE TITLE
Forece close after starting the app and picking accent colour

### ISSUE THREAD

**Issue by bastadur** [ccrama/Slide#1958]
Slide version: 5.4
Android version: 4.1.2

I always get a force close after picking the accent colour. The front page starts loading, the loading circle rolls for a second and poof...

**Comment by ccrama** [comment]
I cannot reproduce this, have you reported it?

**Comment by ccrama** [comment]
Fixed, it had to do with the layout and not the accent color pre-Jellybean

**Comment by bastadur** [comment]
Was it pushed with 5.4.1? It's crashing on that version too.

**Comment by ccrama** [comment]
Can't reproduce then, please report the issue

**Comment by bastadur** [comment]
I must admit you got me confused now. Report where/how?

**Comment by ccrama** [comment]
When it crashes, click the "Report" button that pops up

**Comment by bastadur** [comment]
It doesn't. Just a "Slide stopped" or something like that and an "ok" option.

Is there a crash log generated somewhere that I can submit?

**Comment by ccrama** [comment]
It should be in that dialog. If it's not there, really is nothing I can do about it. You can use adb on your PC to get a log if you know how to use that, though

**Comment by bastadur** [comment]
Ah well, let's hope someone else will be able to report it. That is, if the crash occurs on someone's device.

**Comment by Nxt3** [comment]
Could you try uninstalling and reinstalling the app? Make sure you make a backup of Slide before you do (Settings > Backup and Restore > Backup to File)

**Comment by bastadur** [comment]
I got some time today to install a new custom ROM on my phone, and now Slide works finally.

Great app btw I can see that now. :D

**Comment by Nxt3** [comment]
Glad you're enjoying it! I'm going to close this issue; if you have problems again, do what I said above and if that doesn't fix it, make sure you report it here (or reopen this issue).
