### ISSUE TITLE
separate status bar icon for each download in progress

### ISSUE THREAD

**Issue by touzainanboku** [ccrama/Slide#1959]
Slide version: 5.4
Android version: 6.0.1
While the new update added separate notifications for each download, it'd be great if each download _in progress_ also showed a separate icon in the status bar as well. Makes it easier to be sure that the download actually started.
Although IMHO it's fine for finished downloads to only show one status bar icon in total, in order to reduce clutter.

**Comment by ccrama** [comment]
Slide already does this, the notification always has the same ID while downloading and when showing final

**Comment by touzainanboku** [comment]
Well if that's the intended behavior then that means I'm facing a bug. I'll make a new issue as a bug this time.
