### ISSUE TITLE
Live threads header does not collapse

### ISSUE THREAD

**Issue by kudiaborm** [ccrama/Slide#1965]
Slide version: 5.4
Android version: N preview 4

The header for live threads does not collapse. This may be intended but screen real estate is decreased when using multi window on Nougat, I can watch a YouTube video and use a live thread. The header remaining static reduces the amount of information available on screen.

**Comment by Nxt3** [comment]
Do you mean the toolbar?

**Comment by ccrama** [comment]
This is intended, it shows the live status of the thread
