### ISSUE TITLE
Inconsistency in saving images

### ISSUE THREAD

**Issue by touzainanboku** [ccrama/Slide#1967]
Slide version: 4.5
Android version: 6.0.1
Sometimes the apps seems to fail at downloading images. There's no indication that this happened, apart from the fact that no notification is created, and the image doesn't appear in a file manager/gallery (by this I mean that it doesn't seem to be happening because the internet is disconnected). 
I've been able to reproduce this a few times by trying to save multiple images quickly. It seems like it's more likely to happen if the image/album viewer is closed before it starts downloading. [Here](https://streamable.com/4039)'s a video showing this. As you can see the second image doesn't get saved, until I go back and tap the download button again. 
I apologize if it seems like I'm making duplicate issues. It's genuinely not my intention to cause clutter here. I'm actually having these issues and they're all slightly different, even though they're about the same feature.

**Comment by ccrama** [comment]
Yes, this is impossible to fix as it has to have a reference to the activity to start the service. Not really a way to fix this, unfortuantely. A very small minority of users will close it before it starts downloading, though

**Comment by touzainanboku** [comment]
I see. That's unfortunate. Thanks for the response!

**Comment by ccrama** [comment]
Once the notif shows up, it should be fine
