### ISSUE TITLE
Add a subreddit button

### ISSUE THREAD

**Issue by prashantkhurana** [ccrama/Slide#1970]
It is really hard to add a subreddit as of now : 
1 ) there is no add button in the sub sidebar and if you subscribe and then unsubscribe then the sub is gone from the drawer. 
2) In manage your subscriptions you don't get suggestions, so adding a sub like slideforreddit is difficult (even more difficult with the keyboard auto correcting you, putting in spaces)

**Comment by Nxt3** [comment]
I think the current subscribe button should be replaced with a button that brings up a dialog asking you if you want to add the sub or subscribe/add. That would be best.

**Comment by ccrama** [comment]
Done, now it's a button that says "Subscribe" or "Unsubscribe", and will let you "Subscribe and Add" or "Add" and "Unsubscribe" or "Unsubscribe and remove". It also works when not logged in!
