### ISSUE TITLE
Pin subreddits to their current positions

### ISSUE THREAD

**Issue by willborum** [ccrama/Slide#1971]
I have a handful of subreddits I keep at the top of my list for easy browsing. The only bad part is that when I want to alphabetize my subreddits, I have to manually move those handful back. I would like an option to temporarily/indefinitely pin subreddits/multis to their current positions so I can alphabetize the rest of my list.

**Comment by ccrama** [comment]
IMHO, this would overcomplicate the already over-complicated subreddit management screen and I don't know how often this feature would be used.

**Comment by willborum** [comment]
Fair enough
