### ISSUE TITLE
/r/android isn't loading in offline mode, even if cached

### ISSUE THREAD

**Issue by Soberat** [ccrama/Slide#1972]
Slide version: https://github.com/ccrama/Slide/commit/46d0e3363838518de166f4a2b471197bd1be5410
Android version: 6.0.1

Discovered here: https://www.reddit.com/r/slideforreddit/comments/4ubsrl/offline_mode_error_loading_content_for_randroid/

**Comment by Nxt3** [comment]
Have you been able to reproduce this? I can't.

**Comment by Soberat** [comment]
Still happening, same build. I can provide a video later, or anything else in fact.

**Comment by Nxt3** [comment]
a log would be good.

Have you tried clearing cache? If that doesn't work, uninstall/reinstall Slide--just make sure you remember to backup the settings first.

**Comment by Soberat** [comment]
Well, didn't even have to clear cache, for some reason it started working again. Will report if it ever happens again.
