### ISSUE TITLE
No post shown after refreshing 

### ISSUE THREAD

**Issue by ImjuzCY** [ccrama/Slide#1977]
Slide version: 5.4.1
Android version: 5.1 MIUI8 

It's not the first time happening, but this time it's quite serious. In any subs, post aren't shown even after refreshing and no error message is shown. After refreshing it just show a blank page. Already confirmed that there isn't any connection problem as I can browse reddit with other clients. Only Slide is having this problem. Problem still exist after clearing cache, force stop, and clearing data

**Comment by c727** [comment]
same here. was working 5 hours ago

**Comment by c727** [comment]
here is a logcat http://nopaste.linux-dev.org/?1119583

**Comment by Canaaduh** [comment]
Can confirm here too. I cleared the cache and force closed the app and no post are showing. Must be an issue with the API.

Android N DP5
Slide 5.4.1

**Comment by Alexendoo** [comment]
Well, rather extreme circumstances on this one. But hey at least the code is fine

https://www.reddit.com/r/slideforreddit/comments/4uxb62/my_account_was_compromised/

**Comment by amhrangel** [comment]
Experiencing same thing, blank page

**Comment by Rbbro7** [comment]
I got the same problem, it seems the app can't connect to my reddit account. When I relog the site tels me it's a bad request

**Comment by ccrama** [comment]
My account was compromised and in the process, Slide was removed from my apps section. Sent a message to the Reddit Admins and hopefully they can restore access soon
