### ISSUE TITLE
Slide not loading content anymore

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#1978]
Slide version: 5.4.1
Android version: 6.0.1

I've tried clearing the app data and rebooting my phone but it still isn't working. Is it just me?

**Comment by Alexendoo** [comment]
It's everyone https://www.reddit.com/r/slideforreddit/comments/4uxb62/my_account_was_compromised/

**Comment by ccrama** [comment]
Should be fixed now! My account was compromised and someone deleted my apps on purpose, has been reverted though
