### ISSUE TITLE
Add a "don't show read posts" options

### ISSUE THREAD

**Issue by Tgo1014** [ccrama/Slide#1980]
Every time I open the app I need to hold the FAB to hide read posts, but it doesn't hide everyone: when I scroll down it keep showing older read posts.

Would be nice an option that allows to always hide read posts.

**Comment by Nxt3** [comment]
If you long press the FAB it hides everything--meaning, if you hide a post, it will be hidden on desktop and everywhere else. If that isn't working, this is a bug.

**Comment by ccrama** [comment]
Long pressing the FAB does this, closing
