### ISSUE TITLE
Title bar bug

### ISSUE THREAD

**Issue by Ashos** [ccrama/Slide#1982]
Slide version: v5.4.1
Android version: 7.0

Sometimes when the title bar is tapped to return to top, there's a bug where the title bar floats below where it should be.
![screenshot_20160731-155612](https://cloud.githubusercontent.com/assets/16817522/17274892/6d72c010-5738-11e6-9d98-5d137f3d95ec.png)

**Comment by ccrama** [comment]
I have not run into this before, any specifics on how to reproduce it?

**Comment by Ashos** [comment]
It occurs almost every time when hitting the title bar to return to top;
aside from that, there doesn't seem to be a reproducible pattern.
Refreshing the page doesn't fix it, but entering a post and returning to
the front page does temporarily.

**Comment by ccrama** [comment]
Is there any way you can test this on non-Android N? I want to know if it's N related or not

**Comment by Ashos** [comment]
I think I have an old Nexus 7 2012 around somewhere. I'll see if I can get
it running on that and let you know.

**Comment by Ashos** [comment]
Managed to get my old tablet up and running. Bug is not in reproducable on
Nexus 7 2012, Android 5.1.1.Still able to reproduce on Nexus 5x, Android
7.0.

**Comment by Alexendoo** [comment]
@prashantkhurana reports it's not N only

**Comment by ccrama** [comment]
Is this still an issue with v5.4.3?

**Comment by Ashos** [comment]
Not as far as I can tell, no. I've been testing it since yesterday, and so
far the issue hasn't been apparent.

**Comment by ccrama** [comment]
Awesome! Feel free to re-open if it occurs again
