### ISSUE TITLE
Twitter in internal browser in different language

### ISSUE THREAD

**Issue by jordanclock** [ccrama/Slide#1983]
![screenshot_20160801-000553](https://cloud.githubusercontent.com/assets/2343319/17283314/fa9c2f1e-577c-11e6-8b0f-c14360b9501c.png)
Slide version: 5.4.1
Android version: 6.0.1

Whenever I access Twitter link through the internal browser, they appear to be pulling up a completely different language. If I had to guess, it would be Swedish.

**Comment by l3d00m** [comment]
Do you have a link to that post? Is it happening for all Twitter links?

**Comment by ccrama** [comment]
This will only occur if A) the link was set to be in that language or B) your Android settings have been set to that language
