### ISSUE TITLE
Allow to vote on locked posts

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#1985]
Slide version: 5.4.1
Android version: CM12.1 (5.1)

It isn't currently possible to vote on locked posts, although it is on other reddit clients (and especially on the website). [Source](https://www.reddit.com/r/slideforreddit/comments/4vz0nz/cant_vote_on_locked_post_works_on_desktop_and/)

Edit: Whoops, I confused archived and locked

**Comment by ccrama** [comment]
I actually already did this :)
