### ISSUE TITLE
Inconsistent swiping behavior

### ISSUE THREAD

**Issue by snowtyler** [ccrama/Slide#1986]
Slide version: 5.4.1
Android version: 6.0.1

Video [here](https://youtu.be/I-VkjplqEl4).

As you can see, it is possible to swipe from the main page of a sub to the last post you opened. Normally, to get back to that post you would have to tap it; but I have discovered a bug that lets you slide instead of tap. But it only seems to work when you enter a subreddit from a front page post.

I actually kind of like this, even though it is clearly not intended... _or is it?_

**Comment by ccrama** [comment]
This is sort of intended with the single subreddit view, this is not possible in the main view as you would be swiping between subreddits if there was no content to the right. In the single sub view, we don't need to disable swiping as you can't go anywhere

**Comment by snowtyler** [comment]
So, why is it still disabled in single sub view?

**Comment by ccrama** [comment]
What do you mean? The video shows that it is not disabled

**Comment by snowtyler** [comment]
You say that you can swipe between a single sub and a post in said sub, correct? This functionality only seems to work when you enter a sub through a front-page post.

**Comment by ccrama** [comment]
Yes, the single sub view which I am talking about. This does not work from the main sub view

**Comment by snowtyler** [comment]
OK. It doesn't work when you enter a sub through, say, the drawer.

**Comment by ccrama** [comment]
The sub through the drawer is the main sub view, so no it will not work there, only when you open a sub you don't have on your main page

**Comment by snowtyler** [comment]
So it only works with subreddits you are not subscribed to? Sorry for being so difficult

**Comment by The0x539** [comment]
"Subreddits you're not subscribed to" are opened through an overlay popup thing, instead of switching to them. You can kinda see the difference in whether the top left button is a drawer or a 🔙.

**Comment by snowtyler** [comment]
That is true, I have noticed. However, this "overlay" also appears with subreddits that I _am_ subscribed to. But only if I enter a subreddit from a post on reddit's frontpage.

**Comment by The0x539** [comment]
That would be because a sub is opened in overlay form when:

* The subreddit isn't in the drawer's list (might be slightly inaccurate
info), or

* Some content is already open, and therefore the subreddit can't "replace"
the main usually-frontpage view.

**Comment by snowtyler** [comment]
What exactly is "some content?" Shouldn't it be possible to go directly from reddit's frontpage to a subreddit's frontpage with no overlay?

**Comment by The0x539** [comment]
Ah, yes. Now I comprehend the behavior you're talking about, I think. I'm in agreement there, opening a post via the bottom sheet when opened from frontpage ought to open the sub the same way the drawer would.

**Comment by ccrama** [comment]
No it shouldn't, you are opening the submission *on top of* the current view, you would lose your place in the current subreddit or submission if this was not the case
