### ISSUE TITLE
Mod background span screwy

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1988]
See this comment 
https://reddit.com/r/apocalympics2016/comments/4wfguu/the_water_in_rio_is_so_dirty_the_australian/d66s4cy?context=3

What it looks like to me
http://imgur.com/Kj7eYO3

The mod is tagged correctly for one post, and then none of the times he's tagged for other comments. In addition to that, his background span is larger than normal for the comment he's tagged in correctly.

**Comment by ccrama** [comment]
That is only the case if the view has not been recycled yet

**Comment by ccrama** [comment]
Fixed by adding "\u200B" (zero width space) to the front of each comment title line. This forces the correct height if it hasn't been recycled
