### ISSUE TITLE
Improve automatic dark mode

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#1991]
- [x] Select times for "sunrise" and "sunset"<br /><br />

- [x] Select theme to use during day (does current implementation already do this?)<br /><br />

- [x] Option to wait for user to close app or return to top of "frontpage" before automatically switching (does current implementation do some form of this?)<br /><br />

- [ ] Option to override the global color theme, (and subreddit color themes), at night (if not a color selector, a choice of blue/dark/black/do not override)

**Comment by ccrama** [comment]
#2 just uses your base theme, no need for another option

#4 would be extremely complicated, and I don't think it's in the scope for this feature

#3 will theme all new opening windows with the new theme (if opened during time change), and will automatically change the base theme of the mainactivity when returned to it

Will work on #1 soon!

**Comment by The0x539** [comment]
Maybe an even simpler than proposed version of #4 could fit the bill, I'm imagining AMOLED themes with nothing but text and images lit up. Your judgment though.

**Comment by ccrama** [comment]
Did #1! I am going to make the decision not to do #4 due to how complex that would be to implement and debug (and potential confusion to the user)
