### ISSUE TITLE
Settings font size comically large

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1997]
I understand you wanted to improve readability--but it's far too large. It looks like I used the System Accessibility settings to increase font size it's so large.

**Comment by ccrama** [comment]
It has already been fixed, I only changed it 2sp though, don't know why it made such a bug affect on your device

**Comment by Nxt3** [comment]
But why? No other app has the Settings font size correlated to a setting. This seems so backwards and counterintuitive. :| Not sure what was wrong with it before; never saw anyone complain about it.

**Comment by Alexendoo** [comment]
Agreed, I think it should track whatever the regular sizes are for consistency with other apps

**Comment by Nxt3** [comment]
Whatever it was before was fine.

**Comment by ccrama** [comment]
Its back to 14 now.... :(

**Comment by Nxt3** [comment]
Can I ask why you changed it? Maybe there is an alternate way to achieve what you were aiming for?

**Comment by ccrama** [comment]
I thought it looked better with bigger fonts, just a personal thing I guess
