### ISSUE TITLE
Refresh spinner doesn't load correctly

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#2]
The pull down to refresh spinner appears out of nowhere, and doesn't automatically disappear when let go (no fade in and out like the old releases).

**Comment by ccrama** [comment]
Can you attach a screenshot? I'm not seeing this sort of behavior.

**Comment by alexsmithfanning** [comment]
Here you go: https://goo.gl/GnN6RB

Notice how it appears from nowhere? It's supposed to slide from under the toolbar.

**Comment by ccrama** [comment]
It is acting correctly until you let it back up. Will take a look and see why it's doing that!

**Comment by tehkurt** [comment]
I am experiencing the same issue. Linked is a screen recording.

https://drive.google.com/file/d/0B5xLJuH-45YNUjFUU2pjcmNrODQ/view?usp=sharing

**Comment by l3d00m** [comment]
i can reproduce this as well

**Comment by alexsmithfanning** [comment]
Things seem to have really broken this time...

Link: https://goo.gl/7wOr6y

**Comment by ccrama** [comment]
Been fixed for a while! Forgot to close.
