### ISSUE TITLE
Issues with saving media

### ISSUE THREAD

**Issue by Revel1020** [ccrama/Slide#20]
1) Saving does not do anything. For a GIF, it only shows a notification but doesn't save. Neither do images. Images don't even show notifications.

**Comment by ccrama** [comment]
1) cannot reproduce. It saves to my gallery just fine.

2) Also cannot reproduce :(

**Comment by ccrama** [comment]
What is your phone/OS?

**Comment by Alexendoo** [comment]
I can reproduce on Nexus 4, 5.1.1 as described

**Comment by Revel1020** [comment]
HTC One M8 running CM12.1

**Comment by ccrama** [comment]
Fixed with 4a11cea2144a2e016eb28503aaa0cb31337ef935
