### ISSUE TITLE
Search gives 2 results for some subs

### ISSUE THREAD

**Issue by m4potofu** [ccrama/Slide#2004]
Slide version:5.4.2 alpha 1
Android version:5.0.2

A few subs that are on the subscribtion list will show up 2 times in the search results :  https://gfycat.com/WeeklyShorttermIriomotecat
The lower case result will go to its tab while the upper case one will open another window : https://gfycat.com/WanGlossyAbyssiniangroundhornbill
The majority of subs don't have this behavior, it also happens on a fresh instal, non logged slide.

**Comment by ccrama** [comment]
Should be fixed now, thank @Soberat !

**Comment by Soberat** [comment]
It is partially fixed, actually:
-If a wrong cased sub is in history, it will show up too
-It shows both if the wrong cased one is in subscribtions (fixing that would require converting all wrong cased subs)

**Comment by m4potofu** [comment]
This bug re-surfaced somehow.
