### ISSUE TITLE
Offline mode : comments get mixed up

### ISSUE THREAD

**Issue by prashantkhurana** [ccrama/Slide#2008]
related to #1933 . 

The cause of this happening : we don't display "load more comments" and related stuff in offline mode but all the calculations (example getChildNumber()) uses it, so it messes up everything.

**Comment by ccrama** [comment]
Fixed, now it checks for offline mode in the relevant  hideNumber and unhideNumber methods!

**Comment by prashantkhurana** [comment]
Thanks !
