### ISSUE TITLE
Give vertical album view full-width images

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#2009]
Until a proper solution is devised for imgur's new by-default one-image albums (if one ever is), this would help for people who swipe away from anywhere.

**Comment by ccrama** [comment]
Good idea, done for the next update! And I highly doubt there will be a solution for that, unfortunately. I don't know why they are moving to a more complicated system, except for the fact that it forces users to go to their website to view content

**Comment by The0x539** [comment]
Except the silly part where it doesn't for users of anything third-party

**Comment by ccrama** [comment]
Yeah, exactly :/

**Comment by prashantkhurana** [comment]
@The0x539 this is good. Recently I submitted a PR which allows you to swipe from anywhere from the first image. So those 1 pic albums should no longer be a concern and you get a 'got to comments' button too. Just wanted to let you know.

**Comment by The0x539** [comment]
🎉
