### ISSUE TITLE
Slide crashes when the widget tries to fetch data and there's no internet after a wake

### ISSUE THREAD

**Issue by notnsane** [ccrama/Slide#2010]
OK, this might be super specific but this is how I get this crash. It's also very minor, since it doesn't really matter that the app crashes while being on a launcher's home, but maybe some had a comment written or something.

1. Put a Slide widget on a launcher's page
2. Go to your phone's Settings > Wi-Fi > Advanced
3. In "Keep Wi-Fi on during sleep", leave it on "never"
4. Let the phone go to sleep by turning the screen off for several minutes (+5 I think?)
5. Wake the device and go to you launcher's home by pressing the Home button

Result: Slide will crash because of the widget (twice in my case) while there's no connection, since Wi-Fi takes some seconds to be enabled again.

Slide version: 5.4
Android version: 5.1

**Comment by ccrama** [comment]
Added a network available check, thanks for the report!
