### ISSUE TITLE
Android back button doesn't work on Subreddit theme menu

### ISSUE THREAD

**Issue by m4potofu** [ccrama/Slide#2015]
Slide version: 5.4.2alpha1
Android version: 5.0.2

but works on Base theme menu, also clicking outside the window quit the menu for Base theme, but not for Subreddit Theme.

**Comment by ccrama** [comment]
That is on purpose, as you have to click save

**Comment by tp0** [comment]
I think this is still very illogical. Back most often means cancel and does mean cancel elsewhere in Slide.

Even more confusing if the Cancel / Reset / Save bottom part [gets cut off like this](http://i.imgur.com/n9s6yKJ.png) (depends on display size, working as intended?).

**Comment by ccrama** [comment]
There are no setting menus that close by clicking back in Slide, I disable all of them on purpose. I'll add a scrollbar to that view, though!

**Comment by ccrama** [comment]
Actually, I just made the buttons always stick to the bottom

**Comment by tp0** [comment]
> There are no setting menus that close by clicking back in Slide, I disable all of them on purpose. I'll add a scrollbar to that view, though!

Back works e.g. [here](http://i.imgur.com/fcmVyqf.png) and [here](http://i.imgur.com/gGhE1du.png) (and for each of the edit main theme popups). Are these now technically same kind of menus? Point still is that they look similar and the expectation is that back = cancel.
