### ISSUE TITLE
Less transparent images

### ISSUE THREAD

**Issue by prashantkhurana** [ccrama/Slide#2016]
Can we make the images less transparent? 

![screenshot_2016_08_10_14_53_40](https://cloud.githubusercontent.com/assets/6133816/17566657/53b43f44-5f0a-11e6-87c5-e860760a0049.png)

**Comment by Nxt3** [comment]
The images are opaque

**Comment by prashantkhurana** [comment]
haha, yeah. my bad. can we make the background darker?

**Comment by Nxt3** [comment]
This used to be an option. It was removed because it wasn't widely used. If tap on the bar with the comments button and download button, it puts it in a focused type mode.

**Comment by prashantkhurana** [comment]
thanks.yeah, that is nice. But then I lose the comments button(plus extra click). It would be nice to have it on by default and still keep the comments button.

**Comment by touzainanboku** [comment]
I'd still prefer it to be optional if this were to be implemented. The transparency really helps with slow connections or large files since you can read the comments while waiting for the image to load.

**Comment by ccrama** [comment]
I kept the transparency but made it a little less opaque (6% less)!
