### ISSUE TITLE
Multiple Accounts: I switched to a new account, now it refuses to go back.

### ISSUE THREAD

**Issue by Revel1020** [ccrama/Slide#202]
So I added a new account then switched to it. Browsed a while then decided to go back but it didn't work. I closed the app and opened it again. Still nothing. I've tried this a couple of times, still no dice.

**Comment by Alexendoo** [comment]
Ah yes I would've warned about that one on your previous post had I remembered, question though for you, is it 'stuck' on the account at the top of the list?

Related: #173

**Comment by Revel1020** [comment]
No, It's stuck on the account on the bottom. Trying to tap on the account on the top isn't switching to it.

**Comment by ccrama** [comment]
Interesting. I'm looking into it! Sorry bout that

**Comment by ccrama** [comment]
Cannot reproduce :(. Works just fine for me

**Comment by ccrama** [comment]
Fixed 26ef1c0e40e5d2392c6daf7d5a376ba19323422a
