### ISSUE TITLE
This imgur album makes Slide freeze

### ISSUE THREAD

**Issue by m4potofu** [ccrama/Slide#2020]
Slide version: 5.4.2alpha1
Android version: 6.0.1

https://www.reddit.com/r/araragi/comments/4x7el4/does_anyone_have_a_clean_version_of_this/d6e1ssn

**Comment by m4potofu** [comment]
did some tests : https://www.reddit.com/r/test/comments/4xcwwo/test/

It's  /layout/grid at the end of the url

**Comment by ccrama** [comment]
Fixed, now it just cuts out anything after layout! Good find
