### ISSUE TITLE
Implement "Contest Mode" when the Reddit API supports it

### ISSUE THREAD

**Issue by GeorgeWL** [ccrama/Slide#2021]
![Screenshot_20160812-122510.png](http://i.imgur.com/hDLERnR.png)
I pressed sort by new a few times and the sort is incorrect in each case.

**Comment by Soberat** [comment]
For some reason it doesn't work in this thread and works fine in others. 
Link:
https://www.reddit.com/r/CompactCraft/comments/490cjy/introduction_thread_v2/

**Comment by l3d00m** [comment]
> this thread is in contest mode - contest mode randomizes comment sorting, hides scores, and collapses replies by default.

Indeed; we should probably indicate that.

**Comment by ccrama** [comment]
The API has no way to show competition mode though

**Comment by Georgiel** [comment]
Aha, that makes sense then.

I thought competition mode did allow sorting after a time period set by moderators though?

I assumed that's why the comment scores were showing at all.

Damn the reddit API.

**Comment by Soberat** [comment]
Can't find that claim anywhere, only that they would delete it after a year. (They wrote that 3 years ago)

**Comment by l3d00m** [comment]
See https://github.com/reddit/reddit/pull/1660

**Comment by ccrama** [comment]
Also need to implement setting contest mode on the submission mod menu once this is implemented

**Comment by 13steinj** [comment]
The contest mode state is now exposed in the API as of earlier today, btw

**Comment by ccrama** [comment]
That is awesome @13steinj ! Thanks for helping implement that :)

**Comment by ccrama** [comment]
Done with implementation, it will display as a tag along with "Locked" and "Archived" at the top of the comment screen. I decided *not* to add it as a mod action as the amount it would be used would not be very high, and it would overpopulate the menu in my opinion

**Comment by 13steinj** [comment]
Np

And assuming you mean the happening now stuff, I'd doubt it, the only reason this got through is they did a rewrite which made my addition invalid and added it manually :P

**Comment by ccrama** [comment]
Oh, ok. That's unfortunate @13steinj , but thank you either way!
