### ISSUE TITLE
Chrome custom tabs don't work when default browser is not chrome on android M

### ISSUE THREAD

**Issue by m4potofu** [ccrama/Slide#2022]
Slide version: 5.4.2alpha1
Android version: 6.0.1

Links are automatically opened externally with the default browser.
No issue on android L

**Comment by ccrama** [comment]
That is because of a limitation with the custom tabs library, nothing I can really do about it unfortunately

**Comment by m4potofu** [comment]
OK. Maybe put a message saying it wont work unless chrome is the défaut browser ?

**Comment by ccrama** [comment]
There isn't a way to tell, the CustomTabs library handles it by itself

**Comment by m4potofu** [comment]
Sync prevent using chrome custom tabs when chrome isn't the default browser, so I imagine there is a way, It's not really a issue for me, it's just that in Slide chrome custom tabs is the default browser, so when a new user who don't have chrome as default start using Slide, it open every links externally by default,
