### ISSUE TITLE
Domain adding bugs

### ISSUE THREAD

**Issue by Soberat** [ccrama/Slide#2024]
Slide version: https://github.com/ccrama/Slide/commit/070c2c6f1faf56bb486acb25fae1b9cc63c10702
Android version: 6.0.1

- [x] If you add a domain to subscribtions, long press on it, the dialog is same as the one for actual reddit subscribtions  ("Remove this subreddit?" title, Remove & Unsubscribe and Remove as options)
- [x] Domain adding dialog also takes anything domain/non-domain for input, as long as its 2 chars long, that means subreddit names too (those are handled corretly)

**Comment by ccrama** [comment]
Now it won't show "unsubscribe" if it isn't a single unsubscribable sub, and it will only show "add" once you have a period in the input (and there is no longer a limit)
