### ISSUE TITLE
Unable to filter subreddit when part of name already filtered

### ISSUE THREAD

**Issue by TheWorstNL** [ccrama/Slide#2027]
Slide version: 5.4.2-alpha2
Android version: 6.0.1

When the subreddit /r/food is filtered and you try to filter /r/foodporn the checkbox is already checked and I'm unable to filter this subreddit.

**Comment by m4potofu** [comment]
I noticed that too, and somehow a sub r/go was added to the filter list when I tried to add r/pokemongo after adding r/pokemon in the main view. But after removing everything I added them in the filter menu and then it worked.

**Comment by ccrama** [comment]
Should be fixed now! Good find
