### ISSUE TITLE
Cosmetic issue resizes dialog

### ISSUE THREAD

**Issue by hdmi** [ccrama/Slide#2028]
Slide version: Slide v5.4.2-alpha2
Android version: Marshmallow 6.0.1

Cosmetic bug that resizes dialog when sliding a slider
Reproduction: Slide for Reddit > Settings > General > Inbox > move the slider

Video: http://gph.is/2aU9fvk

**Comment by ccrama** [comment]
I don't really see a way to fix this, it will only occur on devices with small screens

**Comment by hdmi** [comment]
Sorry for writing in a closed Issue but I just want to inform you that I am actually running in a Nexus 6P 5.7' 2K resolution with stock dpi so it also happens to big-size screens.

Thanks for your feedback

**Comment by ccrama** [comment]
Ah thanks for the info! I am actually on an HTC 10 and the screen was small enough to always have it on 2 lines. I think always making it 2 lines would work best in every situation though
