### ISSUE TITLE
Top bar not minimizing properly 

### ISSUE THREAD

**Issue by m4potofu** [ccrama/Slide#2029]
Slide version:5.4.2
Android version:6.0.1

see this video : https://vid.me/Dqzc

At some point down the page it minimizes properly, I didn't find what trigger this, it's not very frequent and it seems random, on a sub it minimizes properly, on another it minimizes properly 2 posts down, on another 5 posts down... restarting the app changes subs on which this happens.

**Comment by ccrama** [comment]
Should now be fixed, thanks!

**Comment by m4potofu** [comment]
Issue still here in the alpha 3

**Comment by m4potofu** [comment]
It seems scrolling down to a new page makes the bar not minimize for the whole height of the 1st page + a bit. I'm not sure this was happening  before
