### ISSUE TITLE
'OK' and 'Reset' still overlap the colors in the 'Change Color' section

### ISSUE THREAD

**Issue by Revel1020** [ccrama/Slide#203]
This is in the 'Subreddit Theme Settings'. While they don't overlap the colors as before, there still isn't an even space between the colors and buttons.

**Comment by ccrama** [comment]
I don't see that on my end. Can you attach a screenshot please?

**Comment by Revel1020** [comment]
"Overlapping" might have been there wrong word. What I meant is the padding between the OK and the colors above it, is way too narrow.

![](http://i.imgur.com/nLcegJT.jpg)

**Comment by alexsmithfanning** [comment]
As requested by @Alexendoo here's screenshots of the bug.

Accent color chooser doesn't work at all because of button placement.

Link: https://goo.gl/7gWcJT

Color chooser works, but I can't select all colors because of buttons.

Link: https://goo.gl/lwmR6e

**Comment by ccrama** [comment]
Done ef64778
