### ISSUE TITLE
Ability to disable ads blocking on a page

### ISSUE THREAD

**Issue by m4potofu** [ccrama/Slide#2030]
Slide version: 5.4.2alpha2
Android version: 6.0.1

Aside some tweaks of the ads blocking functionality, a way to disable it on a page should be added for pages that don't load properly.
Exemple where non ads images are filtered : https://www.reddit.com/r/Android/comments/4xsy6j/xiaomi_mi_note_2_images_leaked_confirm_edge/

**Comment by ccrama** [comment]
There isn't really a way that it filters non-ad images unless the images are hosted from a known ad hosting domain. I don't think we will add an option

**Comment by ccrama** [comment]
The image doesn't show up with ad blocker off either, I think it's an issue with that specific site on mobile
