### ISSUE TITLE
Make Night Theme time picker use TimePickerDialog

### ISSUE THREAD

**Issue by Soberat** [ccrama/Slide#2031]
The current one isn't really visually appealing, and I think it should include all hours for the sake of different timezones and Sun uptimes.

**Comment by ccrama** [comment]
I purposely did not do this as the time picker in Android is very unintuitive to use, and I wanted to limit the options down

**Comment by l3d00m** [comment]
I agree that the material picker is unintuitive and confusing for new users

**Comment by l3d00m** [comment]
@ccrama Is there a concrete reason for limiting the options down?

**Comment by ccrama** [comment]
Yes, I want them to only choose night and morning times in this feature

**Comment by ccrama** [comment]
I think @Nxt3 's changes are a good compromise! See #2065
