### ISSUE TITLE
Freezing when download is tapped in albums

### ISSUE THREAD

**Issue by touzainanboku** [ccrama/Slide#2033]
Slide version: 5.4.2-alpha3
Android version: 6.0.1
As shown in the [video](https://streamable.com/jizu), sometimes when you tap download in an album, it freezes for a few seconds before it starts responding again. No "app is not responding" dialog is shown, the app doesn't FC, the OS itself doesn't freeze, and the image is downloaded correctly.

**Comment by ccrama** [comment]
All three of your issues are the same implementation, can you please remove them and make one issue? Thanks!

**Comment by ccrama** [comment]
Was pretty simple to implement all three, done!

**Comment by touzainanboku** [comment]
> Was pretty simple to implement all three, done!
Thanks for that! And sorry for making separate issues, I wasn't really sure what to do. I'll make sure to make a single issue for similar ones like this from now on. Thanks again!
