### ISSUE TITLE
Separate download notification for each image in an album

### ISSUE THREAD

**Issue by touzainanboku** [ccrama/Slide#2034]
Slide version: 5.4.2-alpha3
Android version: 6.0.1

Currently that app shows one download notification per album. So if you download 5 images from the same album. only one notification is created, which keeps getting overwritten. This means you have no idea if the app actually did register your input, after your first image, until it finishes downloading. My suggestion is to treat each image inside the same album individually, creating separate notifications for each of them. 

Also on a slightly related note, are the download notifications set to be dismissed after a few seconds? I've seen some of them disappear after I while, and I wanted to check if that's intended behavior or not before I create an issue for that.

**Comment by ccrama** [comment]
Done!
