### ISSUE TITLE
Whitelist/blacklist for subreddit content filter

### ISSUE THREAD

**Issue by touzainanboku** [ccrama/Slide#2036]
Slide version: 5.4.2-alpha3
Android version: 6.0.1
The current content filter (from the overflow button) works as a blacklist, allowing you to choose what content to _hide_. I think having the option to choose what to _show_ would be helpful as well. Technically this is partially doable right now. For example if you only want to see albums you tick everything else and you only get albums. However you can't do this for NSFW content. While you can hide it, you can't choose to only show NSFW content. Having a whitelist along with the currently available blacklist will fix this, and it'd also be easier because you don't have to tick 5 boxes when you only want to see one type of content.

**Comment by ccrama** [comment]
Personally I think that would unnecessarily overcomplicate the feature. The method of hiding all but what you want to see works fine and is easier for users to understand IMO

**Comment by touzainanboku** [comment]
Well then how about separating only NSFW content? All the other ones (album/image/gif/link/self) are mutually exclusive. A post can't be both an album and a gif. You can only get gifs by hiding everything else. But NSFW isn't a content type, it's a tag. Hiding everything but NSFW only shows videos from YouTube for. It doesn't work like other content types.

**Comment by ccrama** [comment]
The issue with that is that the majority of people filter out nsfw and don't filter it in (like turning off nsfw content on their frontpage). If it was turned into only show nsfw content, that could lead to unintended consequences such as no posts showing up in a subreddit

**Comment by touzainanboku** [comment]
Makes sense. Thanks for the reply. I'll be closing this.
