### ISSUE TITLE
backup to file sometimes hangs

### ISSUE THREAD

**Issue by m4potofu** [ccrama/Slide#2037]
Slide version: 5.4.2alpha3
Android version: 6.0.1

It apparently infinitely writes this in the backup file until the app is killed :

`<map>`
    `<string name="stacktrace">java.lang.StackOverflowError: stack size 8MB`
	`at java.util.LinkedHashMap.get(LinkedHashMap.java:250)`
	`at com.fasterxml.jackson.databind.node.ObjectNode.get(ObjectNode.java:96)`
	`at com.fasterxml.jackson.databind.JsonNode.has(JsonNode.java:680)`
	`at net.dean.jraw.models.JsonModel.data(JsonModel.java:73)`
	`at net.dean.jraw.models.JsonModel.data(JsonModel.java:44)`
	`at net.dean.jraw.models.Thing.getFullName(Thing.java:33)`
	`at me.ccrama.redditslide.Adapters.CommentItem.getName(CommentItem.java:17)`
	`at` `me.ccrama.redditslide.Adapters.CommentAdapter.getHiddenCountUpTo(CommentAdapter.java:1818)`
	`at me.ccrama.redditslide.Adapters.CommentAdapter.getRealPosition(CommentAdapter.java:1804)`
	`at me.ccrama.redditslide.Fragments.CommentPage.doGoDown(CommentPage.java:1331)`
	**`at me.ccrama.redditslide.Fragments.CommentPage.doGoDown(CommentPage.java:1373)`**
	**`at me.ccrama.redditslide.Fragments.CommentPage.doGoDown(CommentPage.java:1373)`**
	**`at me.ccrama.redditslide.Fragments.CommentPage.doGoDown(CommentPage.java:1373)`**
`[...]`
	**`at me.ccrama.redditslide.Fragments.CommentPage.doGoDown(CommentPage.java:1373)`**

It happened 2 times, out of maybe 15 backups, first I thought that it was because I upgraded android from 5.02 to 6.0.1 (Slide 5.4.2 at the time) , since it did that just after the upgrade, and that when I restarted the app the issue was still there, but disappeared after a reinstall from scratch. But today it did it again, and it worked fine after restart of the app, so...

**Comment by ccrama** [comment]
Told it to skip writing the stacktrace from now on
