### ISSUE TITLE
Long pressing on sent messages shows the wrong author

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#2039]
Slide version: v5.4.2-alpha2
Android version: 5.1
[Reported here](https://www.reddit.com/r/slideforreddit/comments/4xwxa3/wrong_user_on_long_press_sent/d6j3qek):

Long pressing on sent messages in the inbox shows the wrong author. It always shows my name.

**Comment by ccrama** [comment]
That is actually the correct user, that's who wrote the message

**Comment by ccrama** [comment]
Either way, I changed it to show the person other than you. I disagree with that action though, it is standard to show who sent it
