### ISSUE TITLE
README.md modifications

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#204]
One small change:
Instead of saying "Slide is an open sourced, ad free Reddit browser for Android" I would change it to "Slide is an **open source**, ad free **Reddit client** for Android".

"Open-sourced" doesn't sound like the projects' author cares.

"Reddit browser" for some odd reason doesn't sound right. I don't know of anybody that has referred to a third-party Twitter app as a "Twitter browser". Reddit client sounds so much better.

First impressions are everything. To me, this would make for an ever so slightly better first impression.

**Comment by SolarAquarion** [comment]
We can simply call it Free,  Libre,  Open Source reddit client
