### ISSUE TITLE
Moderator list subreddit title gets filled with JSON

### ISSUE THREAD

**Issue by timawesomeness** [ccrama/Slide#2040]
Only happens when the subreddit gets opened on top of something else (i.e. when going to a subreddit you aren't subscribed to, or going to a subreddit from the three dot menu on a post, or opening a subreddit URL from another app). See http://i.imgur.com/F6h6wPl.jpg

Slide version: 5.4.2-alpha3
Android version: N Dev Preview 5

**Comment by ccrama** [comment]
Good find! I was referencing an in correct variable. Has been fixed
