### ISSUE TITLE
Slide disconnects and then doesn't reconnect

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#2041]
Slide 5.4.2-alpha3
CyanogenMod 13

Slide used to pop up a dialog asking you to reconnect, but now the dialog just says that there was an error connecting with no option to do so.

**Comment by ccrama** [comment]
An error will only show if the API is down, and reconnecting is not possible. It will ask to reconnect if the error was with authentication

**Comment by alexsmithfanning** [comment]
This happens fairly often. Any time I leave my phone sit for more than about ten minutes.

**Comment by ccrama** [comment]
Do you have wifi set to not stay during lock? This would cause there to be no internet when you return to Slide

**Comment by alexsmithfanning** [comment]
I do have it set to stay on during lock. It happens even if I leave the screen on.

**Comment by ccrama** [comment]
This error only shows in Slide if connecting to Reddit failed meaning the host was unknown (likely a network issue) or the connection could not be established (your device is not connected to the internet). Not really anything on my end I can do to fix that. I'd recommend checking your network and making sure you have no settings enabled on your device that would interfere with your network connections
