### ISSUE TITLE
Suggestions about shadowbox modes

### ISSUE THREAD

**Issue by m4potofu** [ccrama/Slide#2043]
Slide version: 5.4.2alpha3
Android version: 6.0.1

Comment Shadowbox :

1) Make all links in a comment appear in Shadowbox, right now only the first link appears.

2) A way to see the level of the comment on screen (top level, reply, reply+1...), to be able to figure out if a link is an answer to another.

3) Toggle all comments links/top level comment links only (but that might make it too complicated for the user?).

both :

4) Youtube videos are not obvious, they just appear as a pixelated image. Maybe show a play icon on them or add a type of content/domain description to the title at the bottom (could be useful for other content too, but it probably would take too much space?).

5) Ability to swipe down the expanded bottom description from the whole screen.

6) Crash from time to time, I can't pinpoint any particular action/content that trigger them though.

**Comment by ccrama** [comment]
1) It's only images and gifs

2) is possible, but don't know how useful that info would be

3) would be a bit complicated

4) They don't even show up, it's only gifs and images

5) Same as regular shadowbox, it needs to show a bit to be able to pull up

6) Only thing you can do is report it

Thanks for the feedback

**Comment by m4potofu** [comment]
1) sorry I wasn't talking about the type of link. For example If a post has several images links, only the fist one shows in shadowbox, instead of all of them, which is very useful to see all images of a comment with like 10+ image/gif links.

4) In normal shadowbox ? they do

**Comment by ccrama** [comment]
1) Probably not possible, but I'll look into it

4) I understand that, but that's because we have an image to show. There is no image to show in comment shadowbox and therefore it's only images, gifs, and albums.

**Comment by m4potofu** [comment]
4) I didn't notice at first video weren't in comment shadowbox so just talking about videos in regular shadow box, I think there should be something on screen (like a play icon) that shows that the content is a video and not an image. It's easy to guess by looking at the title, but it would clearer, espacially when scrolling fast.

5)  see : https://vid.me/JPBi
Like the Android notification drawer, pull from the edge, pull back from the whole screen. I'm nitpicking  but I think it would make the action easier.

**Comment by ccrama** [comment]
I made it so when you tap on the content and it's expanded, it will collapse. It's a third party library so I can't really make it go down on swipe as that isn't built in.

And did #1 2 and 4, cheers
