### ISSUE TITLE
Can we have a better upvoting functionality for comments?

### ISSUE THREAD

**Issue by yashghelani** [ccrama/Slide#2044]
Slide version: 5.4.1
Android version: 6.0 on Moto E2 LTE

Currently, there is an option to have an always floating action bar below every post title. But, when I open any post, in order to upvote a comment  I have to click on that comment to let the action bar first appear and then click on the upvote button. This gets in the way a lot when you want to upvote a lot of comments in that post. What my suggestion is to implement a slide to upvote/downvote functionality. Like the one you have on the narwhal app on iOS. Thus, you can slide a post to the left to upvote and slide to the right to downvote. I feel this is a quicker and easier way to upvote a lot of comments in a single thread. Thanks :)

**Comment by Nxt3** [comment]
This is impossible to implement. The ability to slide between posts would be broken.

That, and ccrama has already said he has no interest in implementing such a feature. Sorry.

**Comment by Nxt3** [comment]
Read his thoughts in this comment chain: https://www.reddit.com/r/slideforreddit/comments/4xupoq/help_choose_our_default_settings/d6iqyob

**Comment by yashghelani** [comment]
What about having the functionality that I've mentioned as an option? For users who don't want swiping between posts can opt for the voting functionality. How about that?

**Comment by Nxt3** [comment]
Incredibly unlikely. The app's hallmark feature is "sliding". Ccrama has been uninterested in this implementation. If you want that option, use another Reddit client. Slide is trying to be different, not the same.

**Comment by yashghelani** [comment]
Alright. Fair enough :) But, I'm sticking with Slide. It's my favorite ;)
