### ISSUE TITLE
The circles besides the subs in the sidebar should match the accent color and not the primary color.

### ISSUE THREAD

**Issue by yashghelani** [ccrama/Slide#2045]
Slide version:
Android version:

**Comment by Nxt3** [comment]
They match the color you assign them. This is already how it functions.

**Comment by yashghelani** [comment]
Slide version: 5.4.1
Android version: 6.0 on Moto E2 LTE

![Uploading Screenshot_20160818-015550.png…]()
As you can see, I have chosen black as my primary color, AMOLED with contrast as my base theme and red as my accent color. This makes those circles besides subs black as well. Shouldn't it match the accent color?

**Comment by ccrama** [comment]
No, it matches the subreddit color you set. If the sub has not been colored, it's your main color. You can color suns in Settings > Subreddit Settings

**Comment by yashghelani** [comment]
Okay. Thanks :)

**Comment by ccrama** [comment]
No problem!
