### ISSUE TITLE
"Lock" message sending FAB while it's in progress to prevent double sending 

### ISSUE THREAD

**Issue by Soberat** [ccrama/Slide#2046]
I'm not sure if it's happening with comment and post adding but I guess they could use that behavior too.

**Comment by ccrama** [comment]
The menu hides automatically for posts and comments, does it not close the menu view when you click it?

**Comment by Soberat** [comment]
It closes once it's been sent, in that time you can still press the FAB to send again.

**Comment by ccrama** [comment]
Now it hides until sending fails, then it shows again!
