### ISSUE TITLE
Ampersand shows up oddly in inbox

### ISSUE THREAD

**Issue by Jupitorr** [ccrama/Slide#2049]
Slide version: Slide v5.4.2-alpha4
Android version:6.0.1
I rarely use github, so apologies if I've done it wrong. The ampersand in this title: https://i.imgur.com/IsBtHSH.jpg looks odd in inbox view: https://m.imgur.com/ILFTXyf

**Comment by ccrama** [comment]
Good fix, should be fixed now!
