### ISSUE TITLE
Emote improvements

### ISSUE THREAD

**Issue by bb010g** [ccrama/Slide#2050]
The major inconvenience with emotes currently is that they cause the rest of all of a paragraph's lines to be as tall as the largest emote in the paragraph. There are a couple of ways this could be handled. Emotes could continue to be inline, but other lines would have their own heights. Alternatively, emotes could be more floating and all be anchored to the left, in order of use, and the non-emote parts of the paragraph be wrapped around in the containing space, flowing around the emotes. Visual:
```
potato [](/emote) potato potato potato
potato potato potato
radish pie
       vvvvvv
+------------------+
| /-\ potato potato|
| |*| potato potato|
| \-/ potato potato|
| radish pie       |
+------------------+
```
and
```
foo [](/emote) bar [](/emote2) [](/emote3) biz
        vvvvvv
+--------------------+
| /-\ XXX ~~~ foo bar|
| |*| X X ~%~ biz    |
| \-/ XXX ~~~        |
+--------------------+
```
I'd expect the former would be a easier to implement, but I don't know Android HTML UI elements. The latter would be closer to how they actually render on Reddit.

It would be nice if you could view the name about the emote by tapping on it. I know there are ways to reveal the source of a post to pull the emote name from it, but a dialog / toast would be a lot more convenient.

**Comment by ccrama** [comment]
Thank you for the feedback! To be honest, text wrapping would not be easy to do at all using the standard Android TextView implementation. What if it always newlined between the images, so it would be like

```
+-----------------------+
| /-\                               |
| |*|                                |
| \-/                               |
| potato potato potato |
| potato potato potato |
| radish pie                    |
+-----------------------+
```

**Comment by ccrama** [comment]
Assuming newline will help fix this issue. Did that, closing now!
