### ISSUE TITLE
Page refreshes upon Project Fi network change

### ISSUE THREAD

**Issue by plebdev** [ccrama/Slide#2054]
I imagine this is a rather niche issue, but whenever my cell network changes on Project Fi, whatever page I'm on will repeatedly refresh, making the app unusable until the network change completes. This happens even on WiFi, where the cell network shouldn't affect internet access.

Slide version: 5.4.1
Android version: 6.0.1

**Comment by plebdev** [comment]
This issue still happens on the latest version of Slide, as well

**Comment by ccrama** [comment]
When you say repeatedly refresh, do you mean it never stops loading?

**Comment by plebdev** [comment]
What happens is that the app will refresh the page, bringing me to the top of whatever page I'm on. Then it will function as normal for maybe 5-10 seconds, before refreshing again. It does this a few times until the network change is complete.

**Comment by ccrama** [comment]
Is this still an issue with 5.4.3?

**Comment by plebdev** [comment]
Yes, but I have now noticed it in other apps, leading me to believe the problem is part of Android or on Fi's end. It's just more noticeable since Slide takes a while to refresh.

**Comment by ccrama** [comment]
That is annoying, I wonder why your device isn't handling the switch gracefully? Android has been able to switch networks and retain data stream since at least jellybean

**Comment by ccrama** [comment]
Should be improved now, there was a socket issue with network changes, and I added more graceful handling of this. Feel free to re-open if you notice the issue after v5.4.3.5!
