### ISSUE TITLE
Build issue with me.everything:overscroll-decor

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2056]
Slide version: 5a65be3eafde95b0627059a41ec9888420032aec

Anyone else having this build error?

![screen shot 2016-08-20 at 10 22 36 am](https://cloud.githubusercontent.com/assets/2940826/17831764/18075f18-66c0-11e6-8424-5e420b98d028.png)

Not sure how to fix it. Already done a few clean builds.

**Comment by ccrama** [comment]
Try making a clean build. A new dependency was added and it appears you do not have internet access available to download it

**Comment by l3d00m** [comment]
Have you enabled Offline something for Gradle? (It is recommended in some tutorials to make gradle faster)

**Comment by Nxt3** [comment]
Nevermind. Ccrama was correct--it was my internet acting up this morning.
