### ISSUE TITLE
Alternative Layouts Image modes: "Big Image, Big Image Cropped." Not properly working

### ISSUE THREAD

**Issue by Snagg57** [ccrama/Slide#206]
https://www.youtube.com/watch?v=ZzreT5P4XII

When setting Alternative Layout Image Mode to either, Big Image, or Big Image Cropped. The Images all show as the Chameleon/Iguana/Lizard.

However Thumbnail, and the other modes work properly in Alternative Layout.

**Comment by ccrama** [comment]
Cannot reproduce. What app version are you on?

**Comment by loskristianos** [comment]
I have the same issue in the latest build (4.2.1)

Default layout: card mode enabled, image type thumbnail, action bar visible.
Alternative layout: card mode enabled, image type big picture, action based visible.

All subreddits with default layout show correctly, any subreddits set to alternative layout show the chameleon image as the big picture on each card.

**Comment by ccrama** [comment]
Yay I found the bug! The alternative mode was the key there! Fixing now.

**Comment by ccrama** [comment]
Fixed! 413f0d0700b7326b2e88e04d24f97d58f82c77ed
