### ISSUE TITLE
can the background color for the inline reply NOT match the subreddit style color?

### ISSUE THREAD

**Issue by stevefye** [ccrama/Slide#2060]
Slide version:
Android version:

Text can be hard to read on light colored themes. It's not a big deal on the title bar, but it's annoying for the action buttons in the editor

**Comment by Nxt3** [comment]
Don't use the lighter theme colors then. :P I use light themes but it doesn't bother me since it's my own fault.

Not to sound rude, but this has been like this for forever. You are the only person I've seen to say something about it. I don't see this changing, but of course, it's up to ccrama.

**Comment by stevefye** [comment]
No worries. If no one else has mentioned it, it's not worth changing it
when i can just manually change the subreddit theme.

Thanks!

**Comment by ccrama** [comment]
You can actually get this to happen by setting your theme to light gray on light theme, black for AMOLED themes, or dark blue for the dark blue theme, and then change the accent color to be the sub color you'd like to have. It works pretty well and I think it looks cool :)
