### ISSUE TITLE
Hide user flair reflecting the reddit setting

### ISSUE THREAD

**Issue by Ikos9** [ccrama/Slide#2061]
Slide version: v5.4.2

Is there a possibility to add a feature to hide the users flair in the comments list to reflect the user settings in the Reddit preferences? I have it disabled it Reddit but in the app I see the flairs anyway.

Thank you,
Ikos.

**Comment by ccrama** [comment]
The issue is I would have to load the Reddit preferences every time the app started to see if Flair should be enabled. Sorry, I don't think that will be possible.

**Comment by Ikos9** [comment]
It's ok, wanna just point out that others reddit apps have this option. It's a shame cause I really liked this app.

**Comment by ccrama** [comment]
Just because another app has a feature doesn't mean mine has to have it, it
hasn't been brought up before in the last year so it doesn't sound like
there is enough interest in such a feature to make it a setting in Slide.

**Comment by Ikos9** [comment]
Yeah no worries mate, everything is ok, people have preferences and we can't do anything about it.

Cheers,
Ikos.
