### ISSUE TITLE
Disable auto load next page

### ISSUE THREAD

**Issue by RedDragonx** [ccrama/Slide#2067]
Slide version: 5.4.2.2
Android version: 6.0.1
Can you add this feature to Slide?

**Comment by ccrama** [comment]
What would be the use case for this feature? I think it would confuse the user if they enabled it and couldn't get to the next page of content

**Comment by RedDragonx** [comment]
I like to load next reddit page manually to organize them and to reduce data and RAM?

You can add it as an option like 'Tap to load next page'

**Comment by l3d00m** [comment]
@RedDragonx Options are always a hard choice to make, as we already have a lot. I don't see this implemented, as it's rather niche.

**Comment by Nxt3** [comment]
Instead of making this an option--maybe include it as part of the data saver for Android N?

**Comment by ccrama** [comment]
Or data saving in Slide

**Comment by Nxt3** [comment]
also yes. It makes sense.

**Comment by RedDragonx** [comment]
@l3d00m I don't think Slide has a lot of option. Like RES extension on desktop has tons of option but it still very easy to find what I am looking for.
@ccrama You can set default action is auto load next page and add an option "Disable auto load next page" and at the end of the page you add a line "Tap to load next page"

**Comment by ccrama** [comment]
Merging with #2260
