### ISSUE TITLE
Autoplay videos with sound continue playing in background in shadowbox

### ISSUE THREAD

**Issue by m4potofu** [ccrama/Slide#2069]
Slide version:5.4.2.2
Android version:6.0.1

Streamable videos for exemple, I don't know if there is other services with sound.
Same issue in comment shadowbox.

For testing purpose : r/soccer seems to use streamable a lot.

Edit: mixtape.moe, vid.me... so  probably all webm should autostop  when swiping to another post

**Comment by poutros** [comment]
I know that this happens with the youtube shadowbox if you use the youtube background playback xposed module (but only the version with notification visible all the time).

**Comment by ccrama** [comment]
Should be fixed now!
