### ISSUE TITLE
AvoidXfermode (deprecated since sdk 16) removed in Android N

### ISSUE THREAD

**Issue by freundTech** [ccrama/Slide#2074]
android.graphics.AvoidXfermode, which is used to generate colored icons for Subreddit shortcuts was removed in SDK level 24 (Android N), after it has been deprecated since SDK level 16.

https://developer.android.com/sdk/api_diff/24/changes/pkg_android.graphics.html

**Comment by l3d00m** [comment]
This explains the reports from some reddit users. Thanks for the heads-up!

**Comment by ccrama** [comment]
Yikes, looks like there is no replacement for it either. Looking at the docs, it's deprecated (and now removed) because it doesn't work on some hardware

**Comment by freundTech** [comment]
Will be fixed by WIP pull request #2079. If fix is needed now feel free to cherry-pick the commit.

**Comment by freundTech** [comment]
Was fixed by merging #2079
