### ISSUE TITLE
When searching comments if you type just the letter A, L or T in the search bar it serches the comments <p> </p> HTML code

### ISSUE THREAD

**Issue by yasmara** [ccrama/Slide#2077]
Slide version: V5.4.2.4
Android version: 7.0

**Comment by ccrama** [comment]
That is actually a feature, you can search for links to a specific domain that way

**Comment by yasmara** [comment]
Ah i see. so its supposed to look like this http://i.imgur.com/ZuyaAy6.jpg

**Comment by ccrama** [comment]
Hmm shouldn't, I'll look into it!

**Comment by ccrama** [comment]
Should be fixed now
