### ISSUE TITLE
Upvote/Downvote in shadowbox mode

### ISSUE THREAD

**Issue by xnaas** [ccrama/Slide#208]
This is just a request, feel free to mark "won't fix." It would be nice if you could upvote/downvote submissions when in Single View.

**Comment by ccrama** [comment]
Which single view? Do you mean shadowbox mode?

**Comment by xnaas** [comment]
It's called single mode in the app...when you click it, you get a fullscreen view of pictures 'n' shit and it's dope. But sure, probably Shadowbox. :D

**Comment by ccrama** [comment]
Decided not to implement this to keep with the simplicity of Shadowbox mode
