### ISSUE TITLE
This image opens in very low res.

### ISSUE THREAD

**Issue by m4potofu** [ccrama/Slide#2080]
Slide version: 5.4.2.3
Android version: 6.0.1
Data saving disabled.

https://reddit.com/r/comics/comments/4z8cdh/ark_oc/

I think this is because this is an album, (although a single image one).
As a workaround I can click on the image to load the full res if the image(album) viewer is in vertical scrolling mode, not possible in horizontal mode.

**Comment by ccrama** [comment]
Should be fixed now!
