### ISSUE TITLE
Syntax highlighting for code

### ISSUE THREAD

**Issue by nakamin** [ccrama/Slide#2081]
It would be nice if code in the comments and self text could be highlighted. 
Here's a good SO question about this: http://stackoverflow.com/q/11987660/6031775
And here's a sample implementation: https://github.com/hzsweers/android-codepad
Not great on documentation but basically just using [google code prettify](https://github.com/google/code-prettify) and then creating text views from the HTML
Hope that you can do this 😃😀🎉

**Comment by gferon** [comment]
Correct me if I'm wrong, but reddit doesn't support code highlighting in the way that you cannot specify the language you use when starting a line with 4 spaces. To perform proper syntax highlighting, we need to know which language the code block's made of. I guess we could add line numbering though?

**Comment by Nxt3** [comment]
@gferon is correct. There is no way to know what language it is.

**Comment by nakamin** [comment]
The library comes with a lexrer that can figure out the language. There's also [highlight js](https://github.com/isagalaev/highlight.js) which has support for more languages. Both libraries just find code in certain tags (like code or pre), recognize the grammar, and then add the actual highlighting to the code. This is resource intensive though and should obviously be run on a separate thread.

**Comment by nakamin** [comment]
Oh and yeah @gferon line numbering is also a great idea 🎉😃🎉 should I open another issue or do you wanna do it?

**Comment by l3d00m** [comment]
I'm not sure if this maybe is a little bit too much for a reddit app. The library is again a few more kbs we want to avoid if possible.

**Comment by gferon** [comment]
I also don't know the performance impact it could have on things like scrolling or comments loading... Maybe there is a nice(r) way to do it?

**Comment by nakamin** [comment]
Alright then
