### ISSUE TITLE
Don't clear the "Go to subreddit" field when opening a subreddit from the list

### ISSUE THREAD

**Issue by gferon** [ccrama/Slide#2083]
Slide version: 5.4.2.1
Android version: 6.0.1

I was wondering if you consider this a good idea, and I'd be happy to submit a PR myself. The issue is that when I'm looking for a subreddit I don't know, I type a name, click on a subreddit and when I go back I have to start typing again to see the list as it was before.

**Comment by Nxt3** [comment]
Eh. This seems like it would be annoying. Every single time you use the Go to Sub field, you'll have to delete text

**Comment by Alexendoo** [comment]
It could retain just for subreddit not found, as well as keeping the drawer open (currently it takes you back to the previous page)

**Comment by Nxt3** [comment]
If it's implemented how @Alexendoo stated, and it isn't too much trouble for you @gferon, feel free to submit a PR. :) Don't forget to do it for the drawer and the toolbar search methods.

**Comment by gferon** [comment]
Right. My use case is kind of corner case, I guess. I should start using multireddits more instead of browsing manually a bunch of subreddit that have the same prefix / suffix. Though like @Alexendoo mentioned, I think it's a good idea for subreddit not found.

**Comment by ccrama** [comment]
Now it will only clear if the subreddit was found, and will return you to the text field if it was not a valid subreddit
