### ISSUE TITLE
Upvoting the comment plays the downvoting animation

### ISSUE THREAD

**Issue by Soberat** [ccrama/Slide#2084]
Slide version: 4cbd7c6
Android version: 6.0.1

What I mean is that instead of the upvote arrow being colored orange, downvote arrow is colored purple instead. 

Discovered here:
https://www.reddit.com/r/slideforreddit/comments/4zj43k/bug_report_comment_downvoting_animation_seems_to/

**Comment by Nxt3** [comment]
I can't reproduce this. Maybe I'm doing something wrong though.

**Comment by Soberat** [comment]
I actually mixed it around, downvoting colors the upvote arrow while closing, after expanding it again it's correct. Can provide a video if needed.

**Comment by Nxt3** [comment]
A video would be great!

**Comment by Soberat** [comment]
I guess I should have turned on input marks but I forgot to :( Just entered a thread, downvoted a comment, then you can see the bug happening. And the quality is bad because it's still processing :(
https://drive.google.com/file/d/0BwivIOVNk_KjM0ZLc3dRelJmaHM/view?usp=sharing

**Comment by Nxt3** [comment]
Still can't reproduce this.  Try running a newer build and let me know if it's been fixed.

**Comment by Soberat** [comment]
Tried on v5.4.2.3 as well as on https://github.com/ccrama/Slide/commit/094dfb41513cf99c98e92262cbe48b1470196d71 and it's still happening :(

**Comment by Nxt3** [comment]
I dunno. I can't replicate; maybe someone else can?

**Comment by ccrama** [comment]
Should now be fixed!
