### ISSUE TITLE
Posts double on hide while loading new content

### ISSUE THREAD

**Issue by xxdmnxosxx** [ccrama/Slide#2086]
Slide version: All
Android version: 7.0 and I think 6.0/1
Devices: Nexus 6P and 9

Attached are all the videos that I have taken and shown on reddit to ccrama but since he doesn't have a 7.0 device I am posting it here for other contributors.

https://goo.gl/photos/o7JqtdNUm5Aio92W6
https://goo.gl/photos/7s2ikMyhvyGC23hh8

Preface: as pointed out subtly in the video the double _can_ go away if you scroll away and then go back to it but that is still really annoying.

To reproduce (more than one way):
Video 1) Just start hiding stuff, was kinda fixed a few updates ago when the comments were redone but might come up occasionally. Method 2 still works 99%+ of the time.
Video 2) Find a subreddit, scroll to the bottom as fast as you can, before it refreshes or as it's refreshing hit hide on one or more of the bottom most posts, it will duplicate the last post or the first post that's incoming, it may take one or two tries but it happens 99%+ of the time.

**Comment by ccrama** [comment]
Should be fixed (finally) now!
