### ISSUE TITLE
Force English has dropouts sometimes

### ISSUE THREAD

**Issue by c727** [ccrama/Slide#2088]
Slide version: 5.4.2.3
Android version: 5.1.1

Sometimes sub-view and post-view are in system language instead of english

**Comment by ccrama** [comment]
Do you have any specifics?

**Comment by c727** [comment]
It happens from time to time...
Only some views are in system language - the left menu for example is still english. I you refresh the sub/post you will get English language.

**Comment by m4potofu** [comment]
I'd say after returning to the app after some time, but i'm really not sure, afaik it affects the sorting menu, the 3dots menu, the "just now" text next to a comment. It revert to English loading a post comments, or when exiting a post comments i think too. switching between tabs don't revert to english.

**Comment by l3d00m** [comment]
Saw this happening on other apps as well. The "force english" thing is a rather hacky workaround, which may explain this troubles.

Pretty sure it's something that's not fixable from our side.

**Comment by ccrama** [comment]
@l3d00m  is correct, Android handles a lot of the view creation with its own contexts, and the override I use to try to force English gets ignored for some api-level views such as dropdown menus and dialogs. Really not much I can do to solve that

**Comment by ccrama** [comment]
I overrode it in more places, hopefully that should fix the majority of these issues. Otherwise, as @l3d00m  stated, it is a rather hacky method and won't work perfectly all the time
