### ISSUE TITLE
This image doesn't load

### ISSUE THREAD

**Issue by m4potofu** [ccrama/Slide#2089]
Slide version:5.4.2.3
Android version:6.0.1
https://reddit.com/r/gaming/comments/4zkwfc/controversy_surrounding_no_mans_sky_reminded_me/
Probably because it's a non animated gif and fail to open via gfycat.

This one gives an error message though : https://reddit.com/r/test/comments/4xft31/test/d6xhiwf?context=3
If not fixable, ideally there should always be an error message.

**Comment by ccrama** [comment]
Should be fixed now (at least for Imgur images that pretend to be gifs)!
