### ISSUE TITLE
When NSFW post is opened directly from link, its preview image doesn't show up

### ISSUE THREAD

**Issue by piyush-rvc** [ccrama/Slide#2090]
Other apps[Sync] are able to show it to non logged-in users as well.

**Comment by ccrama** [comment]
That is on purpose, you can disable this in Settings > Reddit > Show NSFW previews

**Comment by piyush-rvc** [comment]
but Reddit settings are not available to guest/non-logged-in users.

**Comment by ccrama** [comment]
That is still intended behavior, there is a reason that is disabled for
guests on desktop as well

**Comment by piyush-rvc** [comment]
@ccrama On desktop, once you confirm the 18+ dialog, then it shows the previews to guests. And "preview" image is available in the json feed as well.

There is obey_over_18[or some similar] flag, that needs to be overridden.

**Comment by ccrama** [comment]
Slide handles nsfw content in itself, it's not a flag that has to be
overridden. This is on purpose (partly because of rules on the Play Store),
and is not likely going to change.

**Comment by piyush-rvc** [comment]
> partly because of rules on the Play Store

which rule? also then how does Sync for reddit gets around those rules.

I can implement it, you just need to provide me pointer :)

**Comment by ccrama** [comment]
They ignore the rule I guess, I really don't want that implemented to be
honest. If you visit an NSFW sub directly and click accept, you will be
able to see the posts in Slide after you give consent. If you click a post
from the front page that happens to be gore or NSFW and you're new to
Reddit, that isn't good. Gonna have to say no to this one
