### ISSUE TITLE
Text selection not working properly

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2091]
Several users have reported this: https://reddit.com/r/slideforreddit/comments/4zseqo/text_selection_for_copying/d6yo9rg?context=3

Not sure it's an OS issue

**Comment by l3d00m** [comment]
Happens for me as well, Lollipop 5.1 on an LG g2. It worked several versions ago and stopped working.

**Comment by ccrama** [comment]
It is an OS issue, don't think there is really a solution

**Comment by ccrama** [comment]
I changed how it works, it should be better now but will also show the popup menu
