### ISSUE TITLE
Archived posts show voting icons on comments

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2092]
I think at one point this wouldn't show if a post was archived but now it does. https://imgur.com/NHCpKiw

If you vote on a comment, it says there was an error. So I'm pretty sure this wasn't intentional.

Post: https://reddit.com/r/showerbeer/comments/3f7gea/my_mom_gave_me_a_selfie_stick_as_a_joke_guess/

**Comment by ccrama** [comment]
Should be fixed now, thanks!
