### ISSUE TITLE
Top bar re-maximizing

### ISSUE THREAD

**Issue by m4potofu** [ccrama/Slide#2093]
Slide version: 5.4.2.3
Android version: 6.0.1

Sorry it's me again with this issue. there are still instances where this happens :

1) when following a reddit link, and scrolling down to a position above the comment that loaded.

2) when going back to a previously visited sub, and scrolling down to a position above where the sub reloaded (it needs to be a sub that reloads).

3) I think there are some other instances but I can't find specific ways to reproduce them
edit : the front page does it after launching the app, for a small height ~1card

**Comment by m4potofu** [comment]
videos : 
1) https://vid.me/6uLS
2) https://vid.me/2dJ1

**Comment by ccrama** [comment]
Should be fixed for real now!
