### ISSUE TITLE
xkcd opens in the internal image viewer without alt-text

### ISSUE THREAD

**Issue by mehrabrym** [ccrama/Slide#2101]
Not sure whether to call it a bug or a feature, but all xkcd links now opens in the internal image viewer instead of going to the webpage. The problem is, it opens the image without the alt-text associated with it. This means checking the alt-text becomes a longer task of force opening it in an external browser (or using the settings to force xkcd.com domain to open in external browser). But regardless, there's no option anymore to view xkcd comics in the internal browser or in chrome custom tabs like we were able to before. A toggle would perhaps be welcome. Another solution could be showing the xkcd image in image viewer with a caption for the alt-text.

Slide version: 5.4.2.3
Android version: 6.0.1

**Comment by ccrama** [comment]
Long pressing for alt text has actually already been added to the next update. Cheers :)

**Comment by mehrabrym** [comment]
Thanks!
