### ISSUE TITLE
Several issues with Backup functionality

### ISSUE THREAD

**Issue by notnsane** [ccrama/Slide#2118]
I have several issues with the Backup function:

- [ ]  1) It doesn't work because it doesn't create any files.
- [ ]  2) It mentions the Google Drive option even though I'm using the non-Google F-Droid version (help text should be platform agnostic).
- [ ]  3) Mentions "Backup complete!" though it doesn't create any backups. Should provide an error text, I guess.
- [ ]  4) When you tap on "View" it doesn't find my file explorer (MiXplorer)
- [ ]  5) The popup that mentions that I don't have a file explorer doesn't provide the full complete path to the (alleged) file location, it gets cut with "...", so it's tricky to even try and find it.

So yeah, mostly I kinda want my backup to be created, but I'm not even getting that 😞 

Slide version: 5.4.2.3 from F-Droid
Android version: 5.1

**Comment by l3d00m** [comment]
Have you checked in /downloads if there's any kind of "Slide*´.txt" file? How do you know it doesn't create backups? Thanks for your help!

**Comment by notnsane** [comment]
I've been trying to create a backup since 5.2 versions, and it never worked. It works for anyone else using F-Droid or it's just me?

I did a "slide" search of all my .txt files on my device (with MiXplorer search function) and there's nothing anywhere. It just doesn't generate any file.

**Comment by l3d00m** [comment]
I just tried it with the F-Droid version and had no problem. The file shows up in /downloads.

Which device are you using? Do you know how to get a stacktrace?

**Comment by notnsane** [comment]
Hm, then it's my install I guess, This is my device: http://www.phonearena.com/phones/BLU-Studio-Selfie_id9866
I normally would have no issues trying to reinstall and uninstall, but I have a ton of filters and I already re-did all of them when I went from Play to F-Droid version back and forth a couple of times.
No, no idea how to get a stacktrace, sadly.

I'll try installing Parallels and checking if it can generate backups correctly.

**Comment by ccrama** [comment]
I don't think any of those are actually occurring. It creates the file in your devices' download folder, Four of those would be just because you could not find the file and the other is just a mistaken string

**Comment by notnsane** [comment]
@ccrama I can try and figure out how to record a video to show you that the issue _happens_ and that there's no file generated at all, if you want. I already tried doing this with **Parallels** so I could test with a new install, but again, the issue persists _on my phone_.

Maybe there's some lingering files from an older install somewhere that might be disturbing the process. I've seen weirder thing. Can you tell me where or what files are generated, so I can do a completely clean install of Slide?

What's weird is that when I press the "Restore from file" button, it shows the "Downloads" folder correctly.

What's left for me to try if everything else fails, is to export the app+data and import it on an emulator, so I can generate an export file on a clean system.

**Comment by ccrama** [comment]
Are you using the downloads app to view it? If so that will not show it, as
downloads only shows what it downloaded. Try using a different file
manager, the "Success" screen would not show if there was no file there,
it's really not possible for it to have a false positive.

**Comment by notnsane** [comment]
It's a .txt file, right?
I tried using Amaze too, searched for all the .txt files on my device, etc. Still nothing.

Hm, one particular thing that happens to me (maybe it's only with my device), is that "sdcard0" is my external SD card (where the Downloads folder is and where app the apps generate "junk" files) and "sdcard1" is actually the internal storage of my device. Maybe Slide is confused on where to generate the file?
I also have noticed that, to delete files on "sdcard1" (the internal storage) with Amaze, I need to give the program some extra permissions. Here it's exactly what happens: https://metactrl.com/docs/sdcard-on-lollipop/

**Comment by ccrama** [comment]
It isn't actually a text document, can you try going to the actual
downloads folder on your device or from your computer? That is probably why
your app cannot find the backup file. Also make sure you've granted the
permissions for storage in your device's settings

**Comment by notnsane** [comment]
Thanks for bearing with me!

The downloads folder ("/storage/sdcard0/Download") is working fine. 
To test, I used the open source app **Nori**, loaded a random image and used the "download" option. Nori doesn't give any options to select a download folder, so it's saves to the default folder. I then used the "Download" option (just below "DCIM")in **Amaze**, also open source, and it correctly shows the file. I tapped on it, and it opened correctly.

There is no other file there. Also, I _just_ tried making a backup with Slide, and there is still only that one image at the default download folder.

**Comment by ccrama** [comment]
Can you confirm Slide has write permissions for storage? The code I'm using is this:

Environment.getExternalStoragePublicDirectory(
                            Environment.DIRECTORY_DOWNLOADS

which Android itself says to use to get downloads, so that is very likely not the issue (unless you somehow deleted/gave different permissions to your download folder).

**Comment by notnsane** [comment]
Well, I tested everything I could. The app has zero problems with saving Images or GIFs, I even moved my custom install location to "/storage/sdcard0/Download" and no issues. Of course, there are no issues saving other images or files to that directory with other apps. I even checked the directoy permissions with Amaze, it's "rwx".

I had two permissions on Settings > Security > App Permissions of Slide, "Send Email" and "Send MMS", I set them up to always allow and the issue still happened. I even disabled the App Permissions setting and gave permissions to all apps, issue still happened. I also checked for hidden files, and there was nothing there.

No idea what more to do =P And again thanks for the patience.

**Comment by ccrama** [comment]
Hmm are you sure Slide only has those two permissions? Slide doesn't even ask for those two, which is a bit strange for them to be showing up. 

And this is the line straight from Nori:

`Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
`
which is exactly what Slide uses :(

**Comment by ccrama** [comment]
Forced it to make a new directory, now the code is 100% identical to what the other app has (it was already pretty much identical), so should fix your issue
