### ISSUE TITLE
Issues with offline mode

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2120]
Slide version: 7b074ac10166578151ecd33c776e4b3fa09f4e0e

- [x] Text in dropdown is black instead of white

- [X] Seems to be no difference between selecting "Submission Only" and "Just now (comments)". Both allow me to see the comments of submissions I have cached

- [ ] If you have the toolbar title search method enabled, it gets pushed to the right of the dropdown (should be to the left always)

![screenshot_20160904-132632](https://cloud.githubusercontent.com/assets/2940826/18232694/7830cf48-72a3-11e6-8d17-3676fb5b8aa9.png)

![screenshot_20160904-132628](https://cloud.githubusercontent.com/assets/2940826/18232695/7832a6a6-72a3-11e6-897a-66998669e658.png)

![screenshot_20160904-132906](https://cloud.githubusercontent.com/assets/2940826/18232705/b96b3912-72a3-11e6-9454-0e5654db4d41.png)

**Comment by ccrama** [comment]
2 is not an issue, if the submission is cached in submission only, it will still let you open it

**Comment by Nxt3** [comment]
Fair enough

**Comment by ccrama** [comment]
Fixed the text

**Comment by ccrama** [comment]
And it is really not possible to make it align left, would it be ok to just disable that in offline mode? The sidebar has a list of submissions anyway

**Comment by Nxt3** [comment]
Disabling all search makes more sense anyways. No point since you aren't online

**Comment by ccrama** [comment]
Yep exactly. I'll look into it!

**Comment by Nxt3** [comment]
You could just have the drawer layout load as if the toolbar search method was enabled, but add a check in the toolbar search setup method for not setting it up if you're offline.

**Comment by ccrama** [comment]
Done! Good suggestion
