### ISSUE TITLE
issue with swiftpic.org: press back-button twice

### ISSUE THREAD

**Issue by c727** [ccrama/Slide#2122]
Slide version: 5.4.2.3
Android version: 5.1.1

First slide trys to load the picture in the image viewer which seems to fail and than slide is using the internal browser. After this I have to double-back to close both.

Example:
http://www.swiftpic.org/view-image/29ac4719467acc53a663f410e0ce7731.png

Comment:
https://reddit.com/r/Android/comments/50zpob/turns_out_installing_cyanogenmod_on_the_xiaomi/d78gzqe?context=3

**Comment by ccrama** [comment]
That is because the image could not be displayed in Slide. The next update closes the view underneath
