### ISSUE TITLE
When changing splitscreen window size, activity refreshes

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2124]
Let me prefix this with the following: not sure if this is even possible to fix; it seems Nougat restarts the activities when changing sizes--so there probably isn't much we can do to prevent this. Just wanted to document it.

If you have Slide open in splitscreen alongside another app and you change the size of the windows, Slide will restart it's activity and refresh the sub you're looking at. So, if I have scrolled over a few sub tabs, then change the window size, Slide will throw me back to the frontpage sub tab and reload--losing my place. Same thing occurs if you had a single subreddit open; Slide will reload and you'll lose your scroll position.

Edit: This might be fixed by doing something with [`onMultiWindowModeChanged(boolean)`](https://developer.android.com/reference/android/app/Activity.html#onMultiWindowModeChanged(boolean)); maybe restore the instance there? Not sure.

Edit 2: Maybe [this helps?](https://medium.com/google-developers/5-tips-for-preparing-for-multi-window-in-android-n-7bed803dda64#2)

**Comment by ccrama** [comment]
Yeah that does help, all that needs to be added is smallestScreenSize|screenLayout to all of the activities in the manifest under configChanges=

**Comment by Nxt3** [comment]
Then I just did that. Only had to add `smallestScreenSize`. Not sure if
thats going to fix it though.

**Comment by ccrama** [comment]
Ah, so did that not work?

**Comment by Nxt3** [comment]
Not sure yet; haven't had a moment to test.

**Comment by ccrama** [comment]
Ah alright, I'll look into doing that for you

**Comment by russjr08** [comment]
I'm pretty sure this was fixed in the latest update, at least, it doesn't happen to me anymore.

**Comment by Nxt3** [comment]
Yeah I think it was. If I encounter it again I'll reopen this issue
