### ISSUE TITLE
Donation issue

### ISSUE THREAD

**Issue by YusefOuda** [ccrama/Slide#2128]
Slide version: v5.4.2.3
Android version: Nexus 6 7.0 DP5

It appears that you can only donate a specific amount once. I donated $5 a little ways back and when I try and donate $5 again, it's throwing an error. Other amounts let me go through. Probably a configuration issue with the IAPs?

**Comment by septemus** [comment]
I believe you can only buy an IAP once. Just how Google's IAP system works. Probably to prevent duplicate purchases.

**Comment by ccrama** [comment]
Yes, you are correct @septemus. Not really a way to fix this, unfortunately, but thank you for supporting Slide with your donations!

**Comment by Alexendoo** [comment]
You can purchase the same thing several times if they're consumable IAPs https://developer.android.com/google/play/billing/api.html#consumetypes

**Comment by ccrama** [comment]
Changed to consumable. I can't test it with my dev account, but I believe it will work!
