### ISSUE TITLE
Requesting "other discussions" option for post links.

### ISSUE THREAD

**Issue by Vismund-Cygnus** [ccrama/Slide#2131]
Slide version: 4.5.2.3
Android version: 6.0

I made a [post about this on reddit](https://www.reddit.com/r/slideforreddit/comments/5167l2/request_option_for_other_discussions_when_viewing/) but basically the jist of it is: the reddit website on desktop has a tab on every comments page that's titled "other discussions."

Clicking on this tab shows you all the other posts on reddit that correspond to that exact link. It only works when the URLs are exactly the same, but there are apps (such as [Search For Reddit](https://play.google.com/store/apps/details?id=chaitanya.im.searchforreddit&hl=en)) that shows results as long as the core URL is the same. That app specifically seems to use a different method of searching than reddit does.

Either way, however it's implemented, it would be a really cool feature to add into the Slide app itself. When viewing the comments, you'll be able to click on that option and see all the other places on reddit that the link has been posted.

Please read my reddit thread for a more in-depth explanation of this feature.

**Comment by ccrama** [comment]
Done! You can access the button in the comment overflow menu, or you can share links directly to it from the Android share menu of any app
