### ISSUE TITLE
External xkcd shadowbox bug

### ISSUE THREAD

**Issue by TheWorstNL** [ccrama/Slide#2134]
Slide version: 5.4.3-alpha2
Android version: 6.0.1

When you open the xkcd link in this comment: https://reddit.com/r/mildlyinteresting/comments/51oh55/my_neighbors_mailbox_is_a_microwave/d7dmton?context=3 the link opens externally (normal behavior). 

When you press the back button, you'll return to slide with an empty shadowbox.

**Comment by ccrama** [comment]
Forgot to add .finish(), should be fixed now!
