### ISSUE TITLE
Add donation/Bitcoin link in F-Droid Metadata

### ISSUE THREAD

**Issue by laserstrike** [ccrama/Slide#2135]
Slide version: Latest 
Android version: Cm 13

For example: https://f-droid.org/repository/browse/?fdfilter=document+viewer&fdid=org.sufficientlysecure.viewer

has a link to Donate that leads to a paypal account.

And https://f-droid.org/wiki/page/org.schabi.newpipe

has a link to the dev's Bitcoin.

Please add this since there isn't/can't be a way to donate within the app in the F-Droid version.

**Comment by ccrama** [comment]
Done for the next update, now "Donate" and "Support" views open a PayPal donation page if the user is using an F-Droid version :)

Thank you!
