### ISSUE TITLE
Search in multireddits coming up blank

### ISSUE THREAD

**Issue by jonathanadams83** [ccrama/Slide#2138]
Slide version: v5.4.3
Android version: 7.0

**Comment by ccrama** [comment]
It's working for me, make sure there are actually results for what you're searching for

**Comment by jonathanadams83** [comment]
There are. Even the most basic words and phrases are coming up blank. An uninstall and reinstall still doesn't fix it for me.

**Comment by ccrama** [comment]
That wouldn't have an effect on it. What are you searching and on what subreddits? Reddit search is notoriously bad

**Comment by touzainanboku** [comment]
I'm able to reproduce this. Searched the same thing on desktop vs in Slide in the span of a couple of minutes in the same multi. No results in Slide, plenty on desktop.

**Comment by ccrama** [comment]
Can you provide specifics on what you searched and where

**Comment by touzainanboku** [comment]
Wait actually I found something interesting. When I initially search nothing loads (it's sorted by Relevance > All by default). Then if I pull to refresh it loads. It seems like it only fails initially, then works afterwards.

**Comment by ccrama** [comment]
Was a time period bug, should now be fixed!
