### ISSUE TITLE
Toast when Download Image button is tapped

### ISSUE THREAD

**Issue by real-mizuya** [ccrama/Slide#2139]
Slide version: 5.4.3 (beta)
Android version: 6.0.1

 It would be nice to have a small toast if tapped on the download icon (of pictures in your app) and it really downloads. Since there is no response, I really don't even now if I hit it correctly or maybe tapped next to it. It's not a big deal and just a nice-to-have :p

**Comment by ccrama** [comment]
It will now do this, thanks for the idea!

**Comment by touzainanboku** [comment]
Can this be added for gifs as well? Currently there's no indication for them. Cause If you save a gif after you've already saved another one, they don't get separate notifications.

**Comment by ccrama** [comment]
I'll look into it. Double notifs probably won't be possible, though

**Comment by touzainanboku** [comment]
> Double notifs probably won't be possible

That's fine. I'd just like to have the toast. And thanks!
