### ISSUE TITLE
Something like Relay's simultaneous link+comment loading/opening

### ISSUE THREAD

**Issue by KaliK0t** [ccrama/Slide#214]
So that the gif or image keeps loading and im not stuck looking at a loading screen and the app can keep me busy

**Comment by ccrama** [comment]
AFAIK he does the same thing I do. What is different?

**Comment by KaliK0t** [comment]
Yes but the difference is i cant read comments while waiting for video or
gifs to load then swipe up to play them after they have loaded. Its one of
the things which makes relay convenient while on data.

**Comment by ccrama** [comment]
That would totally break how slide's UX works, sorry. Gonna mark as wontfix
