### ISSUE TITLE
Gallery Mode scroll stop issue

### ISSUE THREAD

**Issue by real-mizuya** [ccrama/Slide#2140]
Slide version: 5.4.3 (beta)
Android version: 6.0.1

In Gallery Mode all pictures from a subreddit are shown next to each other, which is really awesome, but unfortunately it just goes to a point where the page and the pictures were loaded. 

There's a point where you can't scroll further. At this point I have to leave the Gallery Mode, scroll in the subreddit, go back to the Gallery Mode and then scroll down and find the point where it stop last time.

That's very cumbersome and destroys the workflow of checking stuff. Can you make the app load the next bunch of posts and their pictures when I scroll further than the last picture?

You already said: 

> No worries! It will probably change in the future soon to behave more like that.

It would be nice if you could add that :)

**Comment by ccrama** [comment]
That is no longer true, it actually loads forever now

**Comment by real-mizuya** [comment]
Indeed, I checked it and it works, BUT after some scrolling it gets really choppy and unusable :(
Not just a little bit, really choppy as hell :O 
I'm using your recent beta and I'm on Android 6.0.1

If you want to, I can record it for you.

**Comment by ccrama** [comment]
It might just be your device is having trouble handling that many images. You can send a but might not be much I can do

**Comment by real-mizuya** [comment]
I use a Note 7 with 4GB RAM and even if I close all apps (also background running apps) it still happens. After some seconds/swipes in gallery mode it gets very choppy and it's annoying to use it.
