### ISSUE TITLE
Timeframe search option doesn't work.

### ISSUE THREAD

**Issue by m4potofu** [ccrama/Slide#2141]
Slide version:4.5.3
Android version:6.0.1

**Comment by m4potofu** [comment]
It actually works after a refresh.

**Comment by m4potofu** [comment]
I just tested on another device which was still on 5.4.2.3 and the timeframe is directly applied, after upgrading slide a manual refresh is needed.

**Comment by ccrama** [comment]
What does that mean?

**Comment by ccrama** [comment]
Should be fixed, thanks!
