### ISSUE TITLE
Google Play Music paused with Gif viewer

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide#2143]

**Comment by ccrama** [comment]
Only affected by Google Play Music, don't know if anyone else is experiencing this. Spotify doesn't seem to be affected

**Comment by kufii** [comment]
Confirming that I'm experiencing it too

**Comment by ccrama** [comment]
Has it not always been like that?

**Comment by kufii** [comment]
That I'm not sure about, today is the first time I've noticed it though

**Comment by ccrama** [comment]
Fixed!
