### ISSUE TITLE
Input focus not working in comments

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2145]
Slide version: d43ce8a3346598520a6d29001df1bdcec893b54e
Android version: 7.0

I saw you made commits for requesting focus on the reply line for comments. I have yet to have it work. Might be a bug in Android 7.0. If you don't have access to a device with Nougat, let me know and tell me where I could investigate to fix this.

**Comment by ccrama** [comment]
Fixed! Good find
