### ISSUE TITLE
Reddit thumbnail prefs aren't working in multireddit

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2146]
Slide version: d43ce8a3346598520a6d29001df1bdcec893b54e
Android version: 7.0

I have a multireddit with /r/meirl. For some reason, that sub is showing thumbnails now. On Desktop, the thumbnails are hidden correctly--and when viewing that sub directly in Slide, the thumbnails are hidden correctly. Not sure what is going on.

**Comment by ccrama** [comment]
Reddit changed their thumbnail prefs site wide yesterday, now they always show in any collection listing (like all and multis)

**Comment by Nxt3** [comment]
weird. Thanks; didn't know that.

**Comment by Nxt3** [comment]
Wait--that isn't true. On Desktop in the same multi /r/meirl posts still have the thumbnail hidden.

**Comment by Nxt3** [comment]
Also, where did they announce said change?

**Comment by ccrama** [comment]
This is the thread discussing that

https://www.reddit.com/r/changelog/comments/51u5gj/reddit_change_new_thumbnail_art_expando_art_and/

**Comment by Nxt3** [comment]
Weird that I don't see this on Desktop but only in Slide.

**Comment by ccrama** [comment]
Do you have RES or something else affecting it?

**Comment by Nxt3** [comment]
Not on the computer I'm currently using.

**Comment by ccrama** [comment]
Don't know why that's the case. Either way, we rely on the Reddit api to
hide and show thumbnails instead of our own system, so that's how the api
intended to display it to you

**Comment by Nxt3** [comment]
I figured as much. Bummer
