### ISSUE TITLE
Links to Steam images don't work

### ISSUE THREAD

**Issue by m4potofu** [ccrama/Slide#2148]
Slide version:5.4.3.1
Android version:6.0.1

Exemple : https://reddit.com/r/civ/comments/51zt2h/look_at_this_totally_unexpected_cs_canal_city/
Clicking on it does nothing, before it opened them in the internal browser.

Related: could support in the image viewer be added for Steam images ?

**Comment by ccrama** [comment]
That is because there is an illegal uri character in the link. I have ignored that specific error, but it's an issue with the link
