### ISSUE TITLE
Subreddit not found

### ISSUE THREAD

**Issue by m4potofu** [ccrama/Slide#2150]
Slide version:5.4.3.1
Android version:6.0.1
When typing a sub already in the sub list, then hitting search/enter on the keyboard.
Issue not present in 5.4.3

**Comment by Nxt3** [comment]
What sub are you trying?

**Comment by Nxt3** [comment]
I can't reproduce this

**Comment by m4potofu** [comment]
Any already in the sub list, I reproduced on 2 devices (6.0.1)
[Video](https://vid.me/Ljq8)

**Comment by Nxt3** [comment]
Wait. You said the issue isn't present in a newer version. So, what's the problem then? This has been fixed :p

**Comment by ccrama** [comment]
The error message only shows up if Reddit gives a 404 or 500 error, really nothing can be done on my end. The API could have been down at that time

**Comment by m4potofu** [comment]
I tested on 5.4.3 and 5.3.3.1 at the same time, the issue appeared in the new version

**Comment by ccrama** [comment]
hmm seems to be opening subs twice. Have removed the ability to use the bottom button to go
