### ISSUE TITLE
Force close when trying to log in

### ISSUE THREAD

**Issue by shaunidiot** [ccrama/Slide#2154]
Slide version: 5.4.3.7
Android version: 4.4.4

I updated the application and realized that you've fixed something related to the profile and advised the users to clear data. At the same time, I realized that some features related to profile weren't working and thought that I was affected. I cleared the app data and tried to login but it kept crashing time and time again without fail. I'm pretty sure I'm on the latest version of the app as I'm a beta user. I'm unable to get a logcat as I have no access to any PC right now until weekend but I've taken a screenshot of the crash log on my phone. 

http://i.imgur.com/PPPZFOV.jpg

Feel free to get back to me if you need any more info. Thanks!

**Comment by ccrama** [comment]
That is because your device is too old to contain some base API methods. I'll look into it

**Comment by ccrama** [comment]
Added a try case in case the device does not contain those methods, thanks for the report!
