### ISSUE TITLE
imgur upload failure 

### ISSUE THREAD

**Issue by GeorgeWL** [ccrama/Slide#2160]
https://streamable.com/7kkq

<br /><br />Though I'm unsure how much this may be caused by a slightly slow connection.<br /><br />

**Comment by ccrama** [comment]
How large is the image you're uploading? There is a 10mb limit

**Comment by CommunistDouglas** [comment]
The app crashes for me even with just a 200 kb upload.

**Comment by GeorgeWL** [comment]
Only 140kb
![Screenshot_20160914-202128.png](http://i.imgur.com/IHplDbs.png)

![sketch-1473858245433.png](http://i.imgur.com/fTt6rEb.png)

**Comment by ccrama** [comment]
The issue with inserting into the text field and not with uploading
