### ISSUE TITLE
Support for unicode in search links

### ISSUE THREAD

**Issue by touzainanboku** [ccrama/Slide#2162]
Slide version: 5.4.3.7
Android version: 6.0.1

I happened to stumble upon the link below:

https://www.reddit.com/r/LearnJapanese/search?q=%E3%81%AF+%E3%81%8C&restrict_sr=on

If you open it on desktop, the string %E3%81%AF+%E3%81%8C correctly gets converted to the corresponding unicode characters -> は が

On Slide, the action bar shows the string %E3%81%AF+%E3%81%8C itself, and the search results don't match what you get on desktop. 

Searching は が yourself works fine. It's only in links like the one above that it doesn't work.

Is it possible to add support for such links? Though I do admit this is a small nitpick, since between the 5 Reddit apps I tried, Slide is the only one that even supports opening search links.

**Comment by ccrama** [comment]
Should be fixed now, good find!

**Comment by touzainanboku** [comment]
Thanks for the fast response!

Tapping the link in the OP still searches for %E3%81%AF+%E3%81%8C on my side. I'm on 6.0.1, using 5.5-alpha2-dirty.

**Comment by ccrama** [comment]
It displays that but actually searches the correct thing

**Comment by touzainanboku** [comment]
Searching %E3%81%AF+%E3%81%8C on desktop has 6 results, while は が has more than more than 4 pages. I'm only getting those 6 results on Slide.

**Comment by ccrama** [comment]
That doesn't appear to be Slide related, the fact it shows results at all for those characters means Reddit interpreted it correctly but only returned that

**Comment by touzainanboku** [comment]
Opening that same in a web browser (either on mobile or desktop) shows different results. To me it looks like Slide is searching something different that just happens to have results.
