### ISSUE TITLE
Animate color changes in toolbar (w/ tabs)

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2164]
Found this sweet code that looks like it will make the animations smooth (something I think I remember you saying you had trouble with)

https://kylewbanks.com/blog/animating-toolbar-tablayout-floatingactionbutton-and-statusbar-background-color-on-android

**Comment by ccrama** [comment]
Done! Doesn't look bad, just a little getting used to though

**Comment by Nxt3** [comment]
Ha, I was going to do this--was just waiting your feedback. :P I remember you saying there was some reason you didn't do it before--just couldn't remember why.

Thanks!

**Comment by ccrama** [comment]
Ah sorry, haha. I removed it because it just didn't look that great, but I wasn't using the ArgbEvaluator and caused some lag scrolling (but that was probably for other reasons :P)
