### ISSUE TITLE
Better support for /r/friends

### ISSUE THREAD

**Issue by touzainanboku** [ccrama/Slide#2165]
Slide version: 5.4.3.7

Slide already supports /r/friends, and I think it'd be great if it could also:
- support [/r/friends/comments](https://www.reddit.com/r/friends/comments/) (assuming the API allows this)
- have a custom sidebar (for example showing a list of your friends, similar to the one in multireddits), or disable it altogether, like on the frontpage. Currently the sidebar just shows that it's trying to load something, but it never actually loads anything.

**Comment by ccrama** [comment]
Done disabling the sidebar. Where do you think the comments section should go?

**Comment by touzainanboku** [comment]
What do you think about using the sort button? Since it's disabled in the friends sub.

**Comment by touzainanboku** [comment]
So I just recently learned that /r/subredditName/comments works for all subreddits, and not just /r/friends. Would be great if this could be implemented for all subs, and not just /r/friends.

**Comment by touzainanboku** [comment]
Closing this because /r/subredditName/comments isn't just for /r/friends.
