### ISSUE TITLE
Unable to scroll down on certain posts forcing the keyboard to cover the reply box

### ISSUE THREAD

**Issue by anonymous-user** [ccrama/Slide#2167]
Please pardon the confusing title; I will try to clarify. When attempting to reply to a post or comment, the comment box will appear below said post or comment like this:

http://i.imgur.com/Aksugel.png

However in certain cases I will be unable to scroll down, so the reply box will be covered by the keyboard like this:

http://i.imgur.com/b1g4YNp.png

There are a couple conditions to reproduce this:

1. The post content and any replies combined cannot be too short or too long. If it is too short, the comment box will be shown without any scrolling necessary (example 1). If it is too long then scrolling will work.

2. The post must be accessed from the front page (I haven't encountered this bug via other means). If accessed via another dialog like your saved posts or a link to a post, then the bug won't happen.

Slide version: 5.5-alpha
Android version: Android 6.0.1 (Dirty Unicorns 10.6 custom ROM)

Screen recording: http://d-h.st/71hg

**Comment by ccrama** [comment]
Is this with comment pager view type turned on?

**Comment by anonymous-user** [comment]
Do you mean the comment pane view then yes. Also since you mentioned it, I switched to no subreddit tabs view and the bug no longer happens.

**Comment by ccrama** [comment]
Yeah, don't really know how I'd be able to fix this. Undoing that will make the drawer jump when you type (on Nougat), re-doing it will cause you to not be able to scroll

**Comment by anonymous-user** [comment]
At least I have a workaround now. Even if you can't fix it, I want to thank you for at least taking a look at it.

**Comment by ccrama** [comment]
Should be fixed now, thanks!
