### ISSUE TITLE
Long gaps between some subs in Discover section

### ISSUE THREAD

**Issue by johnondr** [ccrama/Slide#2168]
Slide version: 5.4.3.7
Android version: 6.0

When I browse list of subreddits in the Discover section, there are few huge gaps between some entries (like PS4 and reactiongifs). It seems there is a problem with formatting with some subs that became so long that their "card" is long few screens, because when i tap the "empty space" (shown on last screen), i'm redirected to the sub.

Some screens:
http://i.imgur.com/2nO4N7B.png
http://i.imgur.com/lVLdHHz.png
http://i.imgur.com/cZyAnJP.png

You have to scroll few times through this empty space until next post is reached: http://i.imgur.com/oliTRf9.png

**Comment by ccrama** [comment]
That will occur if that sub has many newlines in the description field. Not much I can do about that

**Comment by timawesomeness** [comment]
This issue should be reopened - this is caused by having text after a horizontal line in a description, not by newlines. The length of the blank space seems to be affected by the amount of content that should be in the space.
