### ISSUE TITLE
Update app colors

### ISSUE THREAD

**Issue by jahirfiquitiva** [ccrama/Slide#2172]
Slide version: 5-5alpha
Android version: 6.0.1

Hi

Slide is an awesome app, I use it everyday, however, I find something that annoys me a bit, and would like to report.

Is just a minor thing, so I think it won't be hard to implement, neither will hurt anyone. ;)

1. Change light background color from #dedede to #fafafa, as [guidelines say](https://material.google.com/style/color.html#color-themes).

2. Update the colors in theme settings to match the [latest Material Design color palette](https://material.google.com/style/color.html#color-color-palette). I think it has the colors from the very first palette, which was changed a long time ago.

3. Add more options to accent color. Like for primary color. And update their colors to match the [latest Material Design color palette](https://material.google.com/style/color.html#color-color-palette) too.

4. You could avoid 2 and 3 if you add an option to set custom colors with the hex or rgb code.

5. I think texts are a bit too dark in light theme, so please make them [match the guidelines](https://material.google.com/style/color.html#color-text-background-colors) (if they don't already).

Thanks in advance and keep up the great work. :)

**Comment by Nxt3** [comment]
This is unlikely to happen.

See this https://github.com/ccrama/Slide/issues/506

**Comment by jahirfiquitiva** [comment]
I think issue shouldn't have been closed.

Ok, more color options won't happen.

But at least make 1, 2 and 5 happen, or let the developer reply.

**Comment by jahirfiquitiva** [comment]
@Nxt3  I just noticed you are a contributor to the project, which means you are involved in the development.

Again, please consider requests 1, 2 and 5.

Thanks for such an awesome app.

**Comment by Nxt3** [comment]
5) The text is light because the user has the ability to tint cards different colors. If we made the text darker--what would happen if a post was tinted gray? It's too difficult to support text colors on a base-by-base instance. This will probably not change either.

1 and 2 are up to ccrama. If he was okay with it, I could personally do both.

**Comment by jahirfiquitiva** [comment]
@Nxt3 

About 5, I meant (and wrote) that texts are **too dark** in light theme. Honestly, I haven't found options to change the cards colors, do they really exist?

Thanks for considering 1 and 2. I really hope @ccrama accepts the request.

**Comment by Nxt3** [comment]
Settings > Main Theme > Submission color tinting mode > Card background

The text on white could be changed. Not sure.

**Comment by jahirfiquitiva** [comment]
@Nxt3 

Thanks, just noticed it.

Well, what I would do if cards are colored, is find if card color is light enough and then use a proper color... Here's a code snippet that I use in one of my apps. Not sure if it's good enough for you to implement, but still...

```java
title.setTextColor(getMaterialPrimaryTextColor(!isLightColor(color)));
subtitle.setTextColor(getMaterialSecondaryTextColor(!isLightColor(color)));
```

```java
public static boolean isLightColor(@ColorInt int color) {
	return getColorDarkness(color) < 0.4;
}

public static double getColorDarkness(@ColorInt int color) {
	if (color == Color.BLACK) return 1.0;
	else if (color == Color.WHITE || color == Color.TRANSPARENT) return 0.0;
	return (1 - (0.299 * Color.red(color) + 0.587 * Color.green(color) + 0.114 * Color.blue(color)) / 255);
}

public static int getMaterialPrimaryTextColor(boolean dark) {
	if (dark) {
		// 100%
		return Color.parseColor("#ffffffff");
	} else {
		// 87%
		return Color.parseColor("#de000000");
	}
}

public static int getMaterialSecondaryTextColor(boolean dark) {
	if (dark) {
		// 70%
		return Color.parseColor("#b3ffffff");
	} else {
		// 54%
		return Color.parseColor("#8a000000");
	}
}

//This one for disabled texts, hint texts, and icons
public static int getMaterialDisabledColor(boolean dark) {
	if (dark) {
		// 50%
		return Color.parseColor("#80ffffff");
	} else {
		// 38%
		return Color.parseColor("#61000000");
	}
}
```


And yeah, what I expect to change is text on white, because in dark theme texts are ok.


Thanks again

**Comment by Nxt3** [comment]
Wait--so you have dev experience? Why not create a PR for all of these things? You seem like you know exactly what you had in mind.

This was obviously an option--but given all of the color combos, it becomes a hassle to style everything 100% correct. You should really try playing around with it and submit a PR!

**Comment by jahirfiquitiva** [comment]
@Nxt3 

Really small dev experience.
And even less experience with PR.

I think the hassle is just to find the exact double to check the lightness of the color. For me 0.4 works just fine.

**Comment by ccrama** [comment]
1 is not going to happen, there was little to no difference between the cards and background, so I darkened it on purpose. 

2 was not aware of, where does it say it was changed?

5 matches already

**Comment by jahirfiquitiva** [comment]
Just made a pull request. Please I beg you to merge it.

https://github.com/ccrama/Slide/pull/2173

**Comment by jahirfiquitiva** [comment]
As suggested by @ccrama ... I made [a new PR with just 2 commits](https://github.com/ccrama/Slide/pull/2184).

Hope they are good enough for him to merge it.

Thanks

**Comment by ccrama** [comment]
Your PR closes this

**Comment by jahirfiquitiva** [comment]
Thank you so much @ccrama
