### ISSUE TITLE
[Feature request] Option to swipe from right edge for main menu, left edge for subreddit info

### ISSUE THREAD

**Issue by alpha-k** [ccrama/Slide#2174]
Slide version: 5.4.3.7
Android version: 6.0.1

Love the app, but one thing I miss is to be able to quickly swipe to see the subreddits list without reaching the top or right edges of my screen.. In flow for reddit, the swipe gesture works from anywhere, not just left edge. In boost for reddit, there's an option to swap sides, so the subreddits info is swipable from the left, and the main menu and subreddits list is swipable from the right. 

Of course Slide is unique in its own way and that's awesome, but could you please implement either one of these solutions, would make life a lot easier in terms of ergonomics, reaching the left edge of the screen or the top edge to choose subreddits is a lot more difficult than reaching the right edge.. The swipe tabs does work up to an extent, but it's only one subreddit at a time, Hope this can be done.

Thanks and keep up the great work!

**Comment by Nxt3** [comment]
Can't do this because if you have subreddit tabs, you wouldn't be able to swipe across subs.

**Comment by ccrama** [comment]
Unfortunately, @Nxt3  is correct. This would interfere with many of the swipe actions already available in Slide, and would not be possible. I'm a big proponent for being different, and I don't see another app having something as a reason to add it into Slide. That's how feature bloat happens, and we're trying to steer clear of that

**Comment by alpha-k** [comment]
Ohhk that's fine, how about, if we are in the left most tab, and we swipe left, could that bring up the menu? Right now that doesn't do anything.. it's a lot easier to swipe from the center of the screen than to move to the edge and swipe is all..

**Comment by Nxt3** [comment]
I actually tried something like what you're suggesting @alpha-k. What happens is it is overly sensitive and leads to you pulling the drawer out when you meant to scroll down. Wasn't good UX.
