### ISSUE TITLE
[Request] sort subreddit alphabetically after a certain point

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#2175]
It would be really really great if in the manage subreddit screen I could select a subreddit and sort all the subreddit after that alphabetically. Is this something you can add?

**Comment by kufii** [comment]
Alternatively, select a range of subreddit and sort them

**Comment by ccrama** [comment]
I think this would be a little hard to use and out of the scope for what the feature is designed for. Alternatively, you can sort all alphabetically and then select the ones you want to go to the top, and then hit the "Move to top" option

**Comment by kufii** [comment]
That's not really an alternative, the point is I want to sort all my subreddit without messing up the order of the ones I already brought to the top. But fair enough if you don't think it should be implemented

**Comment by ccrama** [comment]
I know it isn't the same, but it gets to the same result. I don't think there should be two methods of doing it, especially with the complexity of that system already. Hope that's understandable
