### ISSUE TITLE
Use GitHub Projects for repo

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2178]
You should take advantage of the new "Projects" feature for repos. Would be a great way for everybody to see what's up next and what is on deck for releases. (Even though I know nothing major is coming up due to school for you).

**Comment by ccrama** [comment]
I agree! Just have to find some projects to add though, haha

**Comment by Nxt3** [comment]
Well--what's next for Slide? Maybe go through the issue tracker and choose some things you want to have fixed by next release.

**Comment by Nxt3** [comment]
Actually nevermind. Surprisingly--you can't do that. Super annoying. :p
