### ISSUE TITLE
Tagging/voting while offline

### ISSUE THREAD

**Issue by andree182** [ccrama/Slide#2180]
Slide version: 5.4.3.7
Android version: 6.0.1

It would be nice, if it was possible during offline bowsing to

1) somehow bookmark the content (usecase: youtube video links) to be viewed online later
2) vote, which would be later sent in batch, after online mode is activated

**Comment by ccrama** [comment]
This would go against Reddit's TOS, unfortunately this will not be possible. You can "Read later" a post in the 3 dot menu while offline, though!
