### ISSUE TITLE
Snackbar's text color black when using Light theme

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2181]
When adding a sub to a multireddit using the sidebar (folder icon in sidebar), the snackbar text is black in the light theme.

For future reference, where is this color coming from? You've fixed an issue like this before but I can't figure out where to fix it.

![screenshot_20160920-170616](https://cloud.githubusercontent.com/assets/2940826/18688983/c88e8422-7f54-11e6-8210-8635936804a7.png)

**Comment by ccrama** [comment]
The color is the primary font color of the theme. This has to be done to all snackbars to make it white:

 ```
 Snackbar s = Snackbar.make(...);
 View view = s.getView();
 TextView tv = (TextView) view.findViewById(android.support.design.R.id.snackbar_text);
 tv.setTextColor(Color.WHITE);
 s.show();
```
