### ISSUE TITLE
"Unauthorized" message when linked to Twitter using in-app browser 

### ISSUE THREAD

**Issue by sagev9000** [ccrama/Slide#2182]
Slide version: 5.4.3.7
Android version: 6.0

**Comment by ccrama** [comment]
Don't think there's anything I can do on my end to fix that, whatever they linked to was locked down and you were unauthorized to view it

**Comment by sagev9000** [comment]
It's happened with multiple links that work fine in any other browser for
me. I suppose I should have been more specific.

**Comment by ccrama** [comment]
Maybe the site you're linking to relies on cookies and you've disabled it? Either way, it isn't anything I can do in app, that's up to the website

**Comment by sagev9000** [comment]
Fair enough.
