### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2183]
I've had this build error since this commit 065f723b1bb0c86f2458a74fdc158cfdaee0b3ba

Error I get when building:

`/Users/nxt3/code/AndroidStudioProjects/Slide/app/src/main/res/values-af-rZA/strings.xml:14: Error: "submission_share" is translated here but not found in default locale [ExtraTranslation]
  <string name="submission_share">Deel artikel</string>`

The fix for me is to just add `<string name="submission_share"></string>` to the base `strings.xml` file.

Wasn't sure how you wanted me to go about fixing it.

**Comment by Alexendoo** [comment]
It'll get fixed automatically with the next translation update, which I'll do shortly

**Comment by Nxt3** [comment]
I knew that would fix it--just didn't know when the next merge would be. Thank you!
