### ISSUE TITLE
[Request/Cosmetic] Option for full width cards post layout (not list view)

### ISSUE THREAD

**Issue by DW1045** [ccrama/Slide#2186]
As Android N is coming to more devices, having full width cards options would unite the overall look of Slide and the Android OS by adopting the design guidelines of Android N 7.0

This would also enable more information being shown whilst maintaining the card view.

For example, in list view, there is no space in between each post and the image in "big picture" mode doesn't touch the edges of the list.

A full width cards mode would, ideally, have a big picture/big picture cropped mode where the image is filled to each ends of the screen and there would be a card-like space in between each post! :)

Example to help visualise: [Cards view now](http://i.imgur.com/sQbI2dE.jpg) and [Full width cards](http://i.imgur.com/DiYjcvc.jpg)

**Comment by ccrama** [comment]
I responded with the reasoning in your post, but basically it is too difficult to tell posts apart that way. Sorry, but I don't see that being implemented, but thank you for the suggestion!
