### ISSUE TITLE
big picture mode: image cropped

### ISSUE THREAD

**Issue by c727** [ccrama/Slide#2187]
Slide version: 5.5 alpha
Android version: 5.1.1

https://abload.de/img/unbenannt3vlpsx.png
https://www.reddit.com/r/IAmA/comments/53tg5x/im_ken_jeong_creator_writer_and_star_of_abcs_dr/

cropped picture mode looks ok

**Comment by ccrama** [comment]
That is just the image Reddit pulled for that post. Nothing I can really do about it unfortunately

**Comment by c727** [comment]
As I said: Big picture cropped looks OK, so why not big picture??

https://abload.de/img/screenshot_2016-09-24rlshz.png

**Comment by ccrama** [comment]
That is forcing the height of the view, the other is not. The image is extremely wide and not tall, and this is why that occurs

**Comment by c727** [comment]
Hmmm.... Ok
