### ISSUE TITLE
Progressbar never hides after load

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2188]
Slide version: 0baa3bbd5df0879f7c62678e191f377c0319879f
Android version: 7.0

When opening a post, it appears the progressbar animates; upon load completion--the progressbar is never hidden (but there is no animation).

**Comment by ccrama** [comment]
I can't reproduce this

**Comment by Nxt3** [comment]
Can you post a screenshot of what a post looks like? The comments view.

**Comment by ccrama** [comment]
Sure, 
![Screenshot_20160924-152204.png](http://i.imgur.com/RHBy8Q8.png)

**Comment by Nxt3** [comment]
Mine looks like this https://imgur.com/U9x5HkC

**Comment by ccrama** [comment]
That code hasn't changed in over 8 months, don't know why that started occurring for you. Wish I could reproduce :(

**Comment by Nxt3** [comment]
Have you tried on Nougat? I just uninstalled and reinstalled. No dice

**Comment by ccrama** [comment]
No issue on N for me. Also, the progressbar is an overlay on top of the first item, it doesn't collapse down

**Comment by Nxt3** [comment]
I think I figured out what's going on. Where is the code associated with drawing the submission in the comments page? Layout-wise

**Comment by Nxt3** [comment]
It had to do with content scaling in Nougat. If you changed the display size to "Small" that gap would appear. I added a `-4dp` to the top to close that gap. You shouldn't be able to tell a difference between this and how it was before with any display size.

**Comment by Nxt3** [comment]
This is the difference of this change. (Top is old version, bottom is new version)

![screenshot_20160928-160913](https://cloud.githubusercontent.com/assets/2940826/18930419/f72928b8-8595-11e6-8d02-97b3c5518d82.png)

**Comment by ccrama** [comment]
Is there a downside to this? What happens if you have full images enabled in the comment screen?

**Comment by Nxt3** [comment]
Same thing as above--just with a full height image.
