### ISSUE TITLE
[bug] dark bar using the comments navigation toolbar

### ISSUE THREAD

**Issue by aldomann** [ccrama/Slide#2189]
Slide version: 5.4.3.7
Android version: 6.0.1 (CM 13.0)

If you have slow Internet (or you are fast enough), when you tap on the Next Comment button in the comments navigation toolbar before the comments have loaded, a dark bar appears on top of the thumbnail (as depicted in the screenshot below).

![screenshot_20160924-101914](https://cloud.githubusercontent.com/assets/729732/18807357/03cda5ca-8245-11e6-9a18-9f44069f49f5.png)

**Comment by ccrama** [comment]
That is actually just the toolbar hiding, which happens on every down click. I'll make it not do that if there is no comments available to jump through, though!
