### ISSUE TITLE
Steam Community image link handling

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#2191]
Page is slow to load with bad zooming

**Comment by ccrama** [comment]
That's just because the website isn't optimized well, I'd recommend adding those links to the list of links to open externally. There is really not much I can do to improve that, I'm using the stock WebView provided by Android

**Comment by The0x539** [comment]
So they can't be supported like the likes of tumblr posts?

**Comment by ccrama** [comment]
They do not have an API for steam community images
