### ISSUE TITLE
Sliding between comments pages sometime a doesn't load the next page

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#2192]
Slide version: Slide v5.5-alpha2-dirty
Android version: 7.0

Doesn't always happen, but sometimes when you're sliding between posts and get to the last one on the page, the next page never loads so you can't keep sliding. You have to go back to the post list, scroll down to trigger the page load, and then go back to sliding. Let me know if this makes sense I was having a hard time putting it into words

**Comment by ccrama** [comment]
It can take a few seconds to do this, I don't think it's an issue but rather its doing it in the background and it hadn't updated yet

**Comment by kufii** [comment]
Yes for the most part it works fine, but sometimes it doesn't even after leaving it for a minute

**Comment by ccrama** [comment]
If you find more details on this let me know, currently can't find a way to reproduce this, though

**Comment by kufii** [comment]
Ok I'll try to debug myself when I get the time

**Comment by ccrama** [comment]
Thank you! If you find a way to reproduce it, please let me know

**Comment by ccrama** [comment]
Feel free to re-open this if you can reproduce/debug it!

**Comment by kufii** [comment]
Sorry I haven't had time yet, been pretty busy lately. I'm still experiencing the issue so is it alright if you keep it open for a bit? I'll try to get to it this weekend

**Comment by ccrama** [comment]
No worries, sure!

**Comment by kufii** [comment]
Just for sake of time, mind pointing me to the place in the code where it actually loads the next page when sliding through comments?

**Comment by ccrama** [comment]
Sure thing, the code can be found [here](https://github.com/ccrama/Slide/blob/master/app/src/main/java/me/ccrama/redditslide/Activities/CommentsScreen.java#L223)

**Comment by ccrama** [comment]
Looking at that, your issue might actually be that you passed the 5 minute load time frame and Reddit cannot load more submissions. In this case, this is unfixable

**Comment by kufii** [comment]
Well I haven't fixed it yet, not quite sure what the best way to go about it is, but I found what's causing it. Basically, when you open the first comment, the SubredditPosts creates a new Paginator. This means that regardless of how much content has been loaded, the paginator starts at page 1. 

So for example, if you have 3 pages of submissions loaded, and open up the comments, when it tries to load the next page, the SubredditPosts will load page 1 instead of page 4.

I notice the exact same issue occurs in the shadow box.

Let me know if this doesn't make sense and I'll try to clarify.

**Comment by kufii** [comment]
it seems to me the best way to get around this would somehow share a postloader object between the 3 views (subreddit view, comments view, shadowbox view)

**Comment by kufii** [comment]
I made a recording of the issue

https://goo.gl/photos/MXsQAQHj3dfwPh4B9

Here's what's happening. The first time I get to the end of the content, loadMore is called. It reloads page 1 instead of loading page 2, so no posts are added. Then, when I go back a page, loadMore is called again, this time loading page 2, and I'm able to continue sliding.
