### ISSUE TITLE
Opening a certain post in /r/askreddit crashes the app

### ISSUE THREAD

**Issue by matthieugrieger** [ccrama/Slide#2195]
Slide version: v5.5-alpha2-dirty
Android version: 6.0.1

The post in question: https://www.reddit.com/r/AskReddit/comments/54nora/us_presidential_debate_megathread/

Let me know if you'd like any more information. It is possible that this crash only occurs on my device as I am using a custom ROM.

**Comment by aaronpoweruser** [comment]
relevant log 

`09-27 15:18:38.733 10670 10670 E AndroidRuntime: Process: me.ccrama.redditslide, PID: 10670
09-27 15:18:38.733 10670 10670 E AndroidRuntime: java.lang.IllegalArgumentException: LIVE is not a constant in net.dean.jraw.models.CommentSort
09-27 15:18:38.733 10670 10670 E AndroidRuntime: 	at java.lang.Enum.valueOf(Enum.java:200)
09-27 15:18:38.733 10670 10670 E AndroidRuntime: 	at net.dean.jraw.models.CommentSort.valueOf(CommentSort.java:6)
09-27 15:18:38.733 10670 10670 E AndroidRuntime: 	at me.ccrama.redditslide.Fragments.CommentPage.doAdapter(CommentPage.java:1732)
09-27 15:18:38.733 10670 10670 E AndroidRuntime: 	at me.ccrama.redditslide.Fragments.CommentPage.onCreateView(CommentPage.java:1018)
09-27 15:18:38.733 10670 10670 E AndroidRuntime: 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
09-27 15:18:38.733 10670 10670 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
09-27 15:18:38.733 10670 10670 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
09-27 15:18:38.733 10670 10670 E AndroidRuntime: 	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
09-27 15:18:38.733 10670 10670 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1638)
09-27 15:18:38.733 10670 10670 E AndroidRuntime: 	at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:679)
09-27 15:18:38.733 10670 10670 E AndroidRuntime: 	at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:166)
09-27 15:18:38.733 10670 10670 E AndroidRuntime: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1240)
09-27 15:18:38.733 10670 10670 E AndroidRuntime: 	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:670)
09-27 15:18:38.733 10670 10670 E AndroidRuntime: 	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:632)
09-27 15:18:38.733 10670 10670 E AndroidRuntime: 	at android.support.v4.view.ViewPager.dataSetChanged(ViewPager.java:1082)
09-27 15:18:38.733 10670 10670 E AndroidRuntime: 	at android.support.v4.view.ViewPager$PagerObserver.onChanged(ViewPager.java:3082)
09-27 15:18:38.733 10670 10670 E AndroidRuntime: 	at android.support.v4.view.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:284)
09-27 15:18:38.733 10670 10670 E AndroidRuntime: 	at me.ccrama.redditslide.Adapters.SubmissionAdapter$4.onSingleClick(SubmissionAdapter.java:208)
09-27 15:18:38.733 10670 10670 E AndroidRuntime: 	at me.ccrama.redditslide.util.OnSingleClickListener.onClick(OnSingleClickListener.java:40)
09-27 15:18:38.733 10670 10670 E AndroidRuntime: 	at android.view.View.callOnClick(View.java:5261)
09-27 15:18:38.733 10670 10670 E AndroidRuntime: 	at me.ccrama.redditslide.SubmissionViews.PopulateSubmissionViewHolder$32.onClick(PopulateSubmissionViewHolder.java:2552)`

**Comment by l3d00m** [comment]
They are using a new sort method, LIVE, which isn't supported by Slide / JRAW.

**Comment by ccrama** [comment]
Should be fixed now
