### ISSUE TITLE
Italic text in comments cut off

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2205]
Android version: 7.0

https://imgur.com/oSFb1Zr

Link to comment
 https://reddit.com/r/youtubehaiku/comments/551jen/haiku_you_repooped_in_the_wrong_yard/d86vjed?context=3

**Comment by ccrama** [comment]
It is not cut off for me

**Comment by Nxt3** [comment]
Yeah it happens so sporadically. Maybe it's been fixed. Maybe it's another display size bug thing. I have my 6P size set to Small on Nougat. Try that

**Comment by ccrama** [comment]
It's probably an issue with the size, the only real way to "fix" it is to add even more padding to the sides of the SpoilerRobotoTextView, but I don't know if it's worth the design trade-off to do that (especially if enabling a setting on the device causes the issue and isn't something Slide does wrong)

**Comment by Nxt3** [comment]
Okay, so I switched back to the default display size and it's still cut off.

**Comment by ccrama** [comment]
Not able to reproduce that, what font are you using?

**Comment by Nxt3** [comment]
Condensed at size Medium.

**Comment by ccrama** [comment]
That's what I have it set to as well, wonder why the behavior is different on your device

**Comment by Nxt3** [comment]
It has to be a Nougat thing. Although, I have no way to test this without firing up an emulator. I'll try to do that soon.

**Comment by ccrama** [comment]
Ended up adding a hairline break (&#x200A;) to the end of every line in comments. Fixed the issue, although it is quite hacky

**Comment by Nxt3** [comment]
Doesn't fix it for me.

**Comment by ccrama** [comment]
Are you sure? It's working on my devices and this was the workaround many
people used on StackOverflow

**Comment by Nxt3** [comment]
http://i.imgur.com/j563LtG.jpg

**Comment by ccrama** [comment]
Could it be your dpi settings? What does it look like with stock dpi?

**Comment by Nxt3** [comment]
I tried all of them. Didn't make a difference.

**Comment by ccrama** [comment]
What device are you on? I can no longer reproduce this :/

**Comment by Nxt3** [comment]
Nexus 6P, 7.0.

**Comment by ccrama** [comment]
Is 7.1 going to come to your device any time soon? Might be a fixed Android bug that is not on my version of Android

**Comment by Nxt3** [comment]
Supposedly in December. I'll keep you updated

**Comment by ccrama** [comment]
Fixed for real this time by adding a space to the end of everything in the SpoilerRobotoTextView. Sort of hacky still, but seems to be the only real solution here

**Comment by Nxt3** [comment]
That is hacky, but it's not the worst solution. Thank you!
