### ISSUE TITLE
Text in App Bar remains white regardless of colour selected, rendering it unreadable for certain colours

### ISSUE THREAD

**Issue by loskristianos** [ccrama/Slide#221]
When certain lighter shades of grey are chosen as the Main Color in theme settings (or subreddit theme settings) the text remains white and can barely be seen. Cosmetically it would be useful to either switch to a darker text colour for these shades, or allow user-selectable text colours in theme settings.

Example screenshot:
https://drive.google.com/file/d/0BwOGr2xW93f_S1RJazItaXV4S28/view?usp=docslist_api

**Comment by ccrama** [comment]
How did you choose that white color?

**Comment by loskristianos** [comment]
The two lightest shades of grey in the colour picker:
https://drive.google.com/file/d/0BwOGr2xW93f_TEpfekxCVEdhV3c/view?usp=docslist_api

**Comment by Alexendoo** [comment]
Merge into #221 (similar w/ more discussion)

**Comment by okungnyo** [comment]
#221?

**Comment by Alexendoo** [comment]
My bad, #379
