### ISSUE TITLE
Bought pro a while ago, stuck in free version

### ISSUE THREAD

**Issue by ImpersonatingRooster** [ccrama/Slide#2210]
I broke my phone the other day and I'm using a replacement phone until my new one arrives.

I bought slide for Reddit pro on my other phone (with the same Google account, it is in my order history), but for some reason every time I go to the page to install it, I have to buy it. How do I fix this issue? Thanks.

PS: would it be possible to PM me on Reddit about this? I only made this GitHub account to post this. Reddit.com/u/impersonatingrooster

**Comment by ccrama** [comment]
That will only occur if you purchased it with a different Google account, unfortunately there is not much I can do about that. You can use the F-Droid version if you want the unlocked pro features if this Google issue persists, though!
