### ISSUE TITLE
Amp pages displaying search for "amp" instead of that

### ISSUE THREAD

**Issue by kudiaborm** [ccrama/Slide#2211]
Slide version: 5.5 alpha 2 dirty
Android version: NRD90U

Search for something on google
Find a Reddit thread that is an amp pages (has the word "AMP" under the link)
See that clicking the link shows an amp subreddit

Example search, first link at the time of searching

https://www.google.com/search?q=reddit+tiny+text&oq=reddit+tiny+&aqs=chrome.1.69i57j35i39j0l2.6322j0j4&sourceid=chrome-mobile&ie=UTF-8

**Comment by Nxt3** [comment]
This is already been fixed for the next alpha :D

**Comment by l3d00m** [comment]
#2208
