### ISSUE TITLE
Using the "Go To Subreddit" function is difficult to use in landscape

### ISSUE THREAD

**Issue by SurelyExploding** [ccrama/Slide#2213]
Slide version: v5.5-alpha2-dirty
Android version: 7.0

When using the side menu to use the "Go To Subreddit" text box in landscape it brings up an input that takes up the full screen, which hides the suggestions. Additionally, each time I type a letter it dismisses the keyboard, which means I have to tap the text input box again. 

Steps to recreate:
1. Use phone in landscape mode
2. Open up side menu
3. Tap the "Go To Subreddit" text input box to bring up the full screen keyboard
4. Type a letter, which will dismiss the keyboard

**Comment by ccrama** [comment]
That is baked into your OS and not really something I can control

**Comment by ccrama** [comment]
I think I disabled it, hope that fixes your issue in the next version!
