### ISSUE TITLE
When quickly peeking, media viewer opens

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2214]
If you peek long enough to see the activity, but super quickly let go, it will open the MediaView. See the below video for what I mean. 

https://www.dropbox.com/s/9e6vkdgnjx0l2xw/2016_10_04_21_49_32.mp4?dl=0

**Comment by ccrama** [comment]
I changed how pop works, should be fixed now in the next alpha!

**Comment by Nxt3** [comment]
Doesn't seem to be fixed :/

**Comment by ccrama** [comment]
Should actually be fixed now, thanks!
