### ISSUE TITLE
Useless error message: 2131230893 try again

### ISSUE THREAD

**Issue by GeorgeWL** [ccrama/Slide#2216]
This is with a new account and on a nsfw reddit  after attempting to upload image or link posts.

The issue isn't just with the error,  but the fact that the error message has zero context.

**Comment by ccrama** [comment]
That is because a string was not defined on your device, usually clearing your cache will fix this, and it appears @Nxt3  did something relating to that in a recent commit

**Comment by Nxt3** [comment]
I didn't do anything about this in a commit.

**Comment by ccrama** [comment]
@Nxt3  ah my mistake. A clear of cache or reinstall will fix this issue either way
