### ISSUE TITLE
Strange font on Non-Pro version for ChromeOS

### ISSUE THREAD

**Issue by vcantu** [ccrama/Slide#2219]
Slide version: v5.5-alpha2-dirty
Android version: ChromeOS 53??

On ChromeOS before installing the pro APK from google play the fonts for the Subreddit titles was a bit strange. Here is a screenshot: http://i.imgur.com/OR4Ggen.png

But after the pro APK was installed it was fine: http://i.imgur.com/kL2WOeN.jpg

**Comment by ccrama** [comment]
The pro is just a file, it contains no code. That is just an issue with Chrome OS, not much I can do about it unfortunately
