### ISSUE TITLE
0 coments in the post

### ISSUE THREAD

**Issue by Pacogens** [ccrama/Slide#222]
Since the last update I only see 1 point and 0 coments in every post...

**Comment by Alexendoo** [comment]
@Pacogens Is it definitely every post (ie check you aren't sorted by new), and if so do the comments stil load correctly?

**Comment by Pacogens** [comment]
Well... This is awkward... I was in new... 😂😂😂

**Comment by ccrama** [comment]
Hahaha no worries!
