### ISSUE TITLE
Youtube player on Chrome OS only displays in portrait

### ISSUE THREAD

**Issue by vcantu** [ccrama/Slide#2220]
Slide version: v5.5 alpha2-dirty
Android version: ChromeOS 53

When opening youtube links on slide it opens in portrait regardless of what layout I have:
Screenshots: http://i.imgur.com/t3qlKHb.jpg   http://i.imgur.com/uzh1Poe.jpg http://i.imgur.com/S78NeBH.jpg

**Comment by ccrama** [comment]
It is using the standard YouTube API and there is not much I can control about how it displays. Don't think there is anything that can be done here, sorry
