### ISSUE TITLE
Swipe to exit does not work on Chrome OS

### ISSUE THREAD

**Issue by vcantu** [ccrama/Slide#2222]
Slide version: v5.5 alpha2-dirty
Android version: Chrome OS 53

Slide to exit works with touch, mouse & trackpad gesture for all regular posts but not images or gifs.

**Comment by ccrama** [comment]
I don't know if there is anything that can be done about that, the code is identical for all of the activities so it should not make a difference what can be swiped or not. What Chrome OS device are you using?

**Comment by vcantu** [comment]
Here it is:
Version 55.0.2882.0 canary (64-bit)
Platform 8887.0.0 (Official Build) canary-channel lulu
ARC Version 3339606
Firmware Google_Lulu.6301.136.57

**Comment by ccrama** [comment]
That is because Chrome OS lets you scroll ViewPagers with the trackpad, but not dragging views. Really not a way to fix this, unfortunately
