### ISSUE TITLE
slide crashing when adding account

### ISSUE THREAD

**Issue by Acters** [ccrama/Slide#2229]
Slide version: 5.4.3.7
Android version:Moto E 1st gen Android 4.4.4
This is my first time using this app. I don't know what to provide but I sent a report via the report button. I paid for pro and installed it, too.(don't know if it will make a difference)

Steps:
1. Start app.
2. Go to left menu
3. Tap "add account"

**Comment by ccrama** [comment]
That is a 4.4 bug that has been fixed, thanks for the report though!

**Comment by Acters** [comment]
Thank you. Is it in the alpha? When can I expect to be able to add my account? Can you, please, mention the commit(s)?

**Comment by ccrama** [comment]
It is not currently, but will be in the next one. Don't remember what commit it was but I just had to tell it to not clear the web cache below lollipop
