### ISSUE TITLE
Issues with download notification 

### ISSUE THREAD

**Issue by touzainanboku** [ccrama/Slide#2237]
Slide version: 5.5-alpha3
Android version: 6.0.1

- The progress bar doesn't show progress. It stays at 0% during the download. Downloading still works. 

- The delete button closes the notification shade, but doesn't actually delete the file. Also doesn't dismiss the notification. 

- The share button doesn't seem to be sending the correct information. Sharing to Telegram says unsupported content . Sharing the same image from QuickPic works fine. Sharing to Slide just goes to selftext mode. 

If there's any more information you need, please let me know. Peek is really cool BTW :)

**Comment by ccrama** [comment]
1) if it's cached, that is expected

2) works for me, I'll look into that though

3) it executes the exact same code as hitting share in the image view

**Comment by touzainanboku** [comment]
> 1) if it's cached, that is expected

I have data saving enabled at all times, and I tested on a bunch of pictures I hadn't opened before, so it's happening for non-cached ones as well. 

> 2) works for me, I'll look into that though

Thank you.

> 3) it executes the exact same code as hitting share in the image viewer, really nothing I can do

I see. Sharing from the image viewer works for me though. Just an FYI.

**Comment by ccrama** [comment]
Have fixed the delete button, and changed the progress code for your issue #1. And the share code is now identical, hopefully that fixes the issue you were having with share

**Comment by touzainanboku** [comment]
Thank you so much.

**Comment by touzainanboku** [comment]
Got the alpha-4 update. Unfortunately all three are still happening on my device, after clearing Slide's cache. There's one difference and it's that delete now FC's Slide. I reported it a couple of times, so I hope that helps.

**Comment by ccrama** [comment]
It's all working for me, I really don't know why your device seems to have issues with every feature

**Comment by touzainanboku** [comment]
I think bugs just like me :)

I'll try a clean install later. Maybe that'll fix it.

**Comment by touzainanboku** [comment]
Got 5.5.

- The progress bar now jumps from 0% to 100% after a few seconds, then stays like that for a moment and then shows download complete. Tested on an image that wasn't cached.

- Share button still doesn't work. Sharing the saved file from another app works. So does sharing from Slide's built-in media viewer.

- Delete now just opens Slide. So if I save an image, go to my home screen, then tap the delete button in the notification, it switches to Slide. 

I'm not entirely sure if there were any changes regarding this between 5.5-alpha4 and 5.5, so sorry if there weren't.
