### ISSUE TITLE
The article title text in the textview did not wrap to a second line

### ISSUE THREAD

**Issue by ChrisGuzman** [ccrama/Slide#2238]
Slide version: 5.4.3.7
Android version: 6.0.1 (Nexus 6 2014)

The title of this article is cut off. ![screenshot_20161017-212342](https://cloud.githubusercontent.com/assets/1993855/19461330/cc9fcd74-94b1-11e6-8f2d-0370a6383841.png)

Compare that to the next article below it. ![screenshot_20161017-212348](https://cloud.githubusercontent.com/assets/1993855/19461344/ebb0adf0-94b1-11e6-8d4b-59c62c9c666c.png)

When you click on the article, you can see the full title of the article ![screenshot_20161017-212354](https://cloud.githubusercontent.com/assets/1993855/19461355/fecffe54-94b1-11e6-9e4f-0eb0b91b3c53.png)

I think it's a recyclerview issue because when I kept scrolling down then scrolled back up the full text of article title was shown on two lines.
![screenshot_20161017-212755](https://cloud.githubusercontent.com/assets/1993855/19461381/3a4a98d6-94b2-11e6-9381-5b7c5898bd75.png)

**Comment by ccrama** [comment]
This is the same as #1618, unfortunately this issue is shared between many apps and appears to be a bug with the OS itself
