### ISSUE TITLE
Use the original filename sent by servers when saving images

### ISSUE THREAD

**Issue by fbis251** [ccrama/Slide#2240]
https://github.com/ccrama/Slide/blob/c3357ce88630ff7c235af95bd2f1432ad17cc029/app/src/main/java/me/ccrama/redditslide/Activities/MediaView.java#L1223

The `doAlternativeImageSave` function can save the image with the original filename. You can get a filename from a URL with something like

    private String getFileName(URL url) {
        if (url == null) return null;
        String path = url.getPath();
        return path.substring(path.lastIndexOf("/") + 1);
    }

Also all the `FileOutputStream out` references can be deleted since the share intent is using the `File image` object

**Comment by ccrama** [comment]
Done! Thank you for the suggestion/code
