### ISSUE TITLE
Unable to send messages on 2nd account

### ISSUE THREAD

**Issue by jonathanadams83** [ccrama/Slide#2242]
Slide version: v5.4.3.7
Android version: 7.0

The first Reddit account I add to Slide sends private messages just fine, but a 2nd account will not send them. It looks like a captcha shows up very briefly but then it disappears along with the message you're trying to send.

**Comment by ccrama** [comment]
Your other account is probably not old enough to send messages without a captcha. What happens if you complete the captcha correctly?

**Comment by jonathanadams83** [comment]
I'm not able to complete the captcha. I can only see it for a split second and then it disappears before I can take any action with it.

I'm able to send messages from the 2nd Reddit account on a different Reddit app without issue.

**Comment by ccrama** [comment]
Are you sure you are not dismissing the popup? Nowhere in code does it hide the captcha, and that would only occur if you accidentally tap outside of it and close it

**Comment by ccrama** [comment]
I made it impossible to tap and exit the popup, should fix your issue

**Comment by jonathanadams83** [comment]
I haven't seen this fixed or an app update yet, but just as an fyi I was not dismissing the pop-up. I don't touch the screen at all in this process. And I realized now that when it does this I get a "message sent" toast but nothing is actually sent. I'll wait until the app update to see if this is fixed.

**Comment by jonathanadams83** [comment]
Just attempted with the new update, and the issue still remains.

**Comment by ccrama** [comment]
Should be fixed for real now (tested and it works), thanks again for the report!
