### ISSUE TITLE
App shortcuts support for Android Nougat 7.0/7.1?

### ISSUE THREAD

**Issue by miladmaz12** [ccrama/Slide#2244]
Slide version:
Android version:

**Comment by Nxt3** [comment]
Only available on 7.1--and it's still in a dev preview. To my knowledge, you'll have to wait until ccrama gets the update.

**Comment by miladmaz12** [comment]
Thought so. Thanks for the response!

**Comment by ccrama** [comment]
My Pixel comes in tomorrow, will add it soon ;D

**Comment by ccrama** [comment]
What would you guys like to see on it? I was thinking Inbox, Multis, and the first 4 subs of your sub list

**Comment by Nxt3** [comment]
That sounds good to me. :)

**Comment by ccrama** [comment]
Done! Also logged out users will just see their subs. What icon should I use for the subs, though?

**Comment by Nxt3** [comment]
Bookmark icon?

**Comment by ccrama** [comment]
Done! 

http://i.imgur.com/zTW5Yti.jpg
