### ISSUE TITLE
Image links makes Slide flickering 

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#2245]
Slide version: 5.5alpha4
Android version: 5.1

Link in question (link is the gif in this post) : WARNING, nsfw (black humor) and nothing for people with epilepsy! https://reddit.com/r/ImGoingToHellForThis/comments/3vcnxu/reich/

Opening the gif in the link makes the screen flicker because the image view activity is closing and opening up again at a very high rate. You have to force close Slide somehow to make it stop.

**Comment by ccrama** [comment]
Should be fixed now, thanks for the report!
