### ISSUE TITLE
Some images are downloaded without file extension

### ISSUE THREAD

**Issue by touzainanboku** [ccrama/Slide#2248]
Slide version: 5.5
Android version: 6.0.1

Some images are downloaded without a file extension. This means they don't appear in any gallery app. The downloaded file seems to have the correct data. The issue is just the file extension. 

Example links: [1](https://www.reddit.com/r/carporn/comments/58v2gi/2016_ford_fiesta_st_4896_x_3264oc/), [2](https://reddit.com/r/2meirl4meirl/comments/58q7wp/2meirl4meirl/), [3](https://reddit.com/r/2meirl4meirl/comments/58spe8/2meirl4meirl/)

So far I've only had this with i.reddituploads links. Not sure if there are any other links affected, but I haven't found any so far. 

[Here](https://www.reddit.com/r/slideforreddit/comments/58wa7k/slide_55_saving_images_without_an_extension/)'s a thread about the same issue on Reddit (not my thread).

Also slightly related, but [this](https://www.reddit.com/r/carporn/comments/58ugyi/the_mclaren_f1s_gauges_2048x1365/) image is a jpg on desktop, but the one Slide downloads is a PNG. Though the MIMEtype says jpeg, so it's just the file extension. Not a big issue.

**Comment by ccrama** [comment]
That is because Reddit links to i.reddituploads.com do not have filetypes attached to them. I'll just make the method assume a png if no filetype is specified at the end of the name
