### ISSUE TITLE
If the OP is [deleted], every comment by [deleted] is considered an OP comment

### ISSUE THREAD

**Issue by brunelli** [ccrama/Slide#2249]
Slide version: 5.4.3.7
Android version: 6.0

Images:

![tmp_1641-img_20161023_144500-1553695079](https://cloud.githubusercontent.com/assets/5755892/19627849/5c53d07e-992f-11e6-942e-165d7b343a9e.jpg)
![tmp_1641-img_20161023_144517-317613859](https://cloud.githubusercontent.com/assets/5755892/19627851/614ea4aa-992f-11e6-8ee2-0217ec93b25a.jpg)

**Comment by ccrama** [comment]
That was actually fixed in 5.5 aleead, make sure you're up to date!
