### ISSUE TITLE
Slide displays a wrong gif

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#2254]
Slide version: 5.5
Android version: 5.1

**HIGHLY NSFW!** Comment in question: https://reddit.com/r/de/comments/58yt6y/der_saubere_bildschirm/d94a75k?context=3

Instead of displaying a little girl flying from a swing (SFW) it shows a guy getting fingered. It displays the correct gif when opened externally. (judging form the comments, sync has the same problem)

**Comment by Alexendoo** [comment]
Seems to display (to much relief) the right image, probably was an issue with the site

**Comment by l3d00m** [comment]
Can confirm, that one was a little bit disturbing :D

**Comment by Alexendoo** [comment]
This looks like it's probably gfycat's issue actually, as per https://redd.it/59dusp
