### ISSUE TITLE
Random dot before comment

### ISSUE THREAD

**Issue by brunelli** [ccrama/Slide#2255]
Slide version: 5.5
Android version: 6.0

I've seen a dot that looks like a hyperlink some times and I have no idea what it means. If I try to click it, Slide freezes.

![tmp_19520-img_20161024_104605442478872](https://cloud.githubusercontent.com/assets/5755892/19646282/79123626-99d7-11e6-9ec8-1073b004b5ba.jpg)

The desktop version doesn't show this:

![tmp_19520-img_20161024_104539-340423312](https://cloud.githubusercontent.com/assets/5755892/19646302/8aca772a-99d7-11e6-8f68-ce24daefebf9.jpg)

[Link](https://reddit.com/r/rickandmorty/comments/593cd1/justin/d95hf1r?context=3) to the comment.

**Comment by ccrama** [comment]
That is a type of link some subs do to display images or do CSS tricks. If you view the comment source, the link is actually there, but the sub hides it. Slide adds a dot to all links that are not visible, so the PonyMotes app has something to attach to and the user knows that there was supposed to be a link there.

Inspecting the source of the comment on desktop, it's actually this:

`[](/doapinkieroll) cool to see you here `

**Comment by brunelli** [comment]
Any way you could make it an option? I've never heard of PonyMotes and I don't see why it'd be useful for me to have this displayed.

**Comment by ccrama** [comment]
Probably not, sorry. It's useful because you know there is a link there
that the op has included, and if you have content type next to link
enabled, it'll show where that link goes to.
