### ISSUE TITLE
Share and delete in download notification don't work

### ISSUE THREAD

**Issue by touzainanboku** [ccrama/Slide#2262]
Slide version: 5.5.1
Android version: 6.0.1
- Share doesn't seem to be passing on the correct content. Telegram says "Unsupported content", Google+ says "Operation failed", and Slide's new submission goes into selftext mode. 
- Delete doesn't actually delete the file. No error is shown. It just closes the notification shade. If I tap it while being in a different app, when I haven't exited Slide or removed it from the recents, it switches to Slide.

**Comment by ccrama** [comment]
Share should now work for you (the code is now 100% identical), I'll look into delete again though

**Comment by ccrama** [comment]
Should all work now for you!

**Comment by touzainanboku** [comment]
Got the update. Share works! Delete still behaves the same as before. 

And thanks for looking into it.
