### ISSUE TITLE
Can't share comment with Facebook messenger

### ISSUE THREAD

**Issue by LINK1733** [ccrama/Slide#2269]
Slide version: 5.5.1
Android version: 6.0.1

When I try and share a comment using the share comment option and sending it to someone via Facebook messenger it doesn't link to the comment and just sends them the reddit post with no comment linked.

**Comment by ccrama** [comment]
Where are you sharing the comment from, the comment menu? Facebook messenger might be stripping out the end of the URL, in that case there is no way to fix that

**Comment by LINK1733** [comment]
Yea I'm sharing it from the comment menu. Yea if you think it's Facebook messenger that's messing it up then I'll just deal with it.

**Comment by ccrama** [comment]
Does it work to any other app?

**Comment by ccrama** [comment]
Going to assume it's an issue with FB Messenger
