### ISSUE TITLE
[Request] Ability to mark submissions as NSFW

### ISSUE THREAD

**Issue by MustardCat** [ccrama/Slide#2271]
Slide version: 5.5.1
Android version: 7.0

Some subreddits (ex - /r/buildapcsales) use the NSFW tag for something not NSFW (ex - when a deal has expired).

"Mark NSFW" has already been added in the Moderation tools but it would be great for regular users as well.  This could be placed under the edit submission drop down (where edit post, edit submission flair, and delete submission are listed)

**Comment by ccrama** [comment]
Done! Thanks for the suggestion
