### ISSUE TITLE
Force English didn't work sometimes

### ISSUE THREAD

**Issue by RedDragonx** [ccrama/Slide#2272]
Slide version: 5.5.1
Android version: 6.0.1

Since 5.5.1 Slide language goes from English to system language. I tried to enable "Force English everywhere" and it worked, but sometimes Slide still change to system language. It changed pretty randomly, sometimes when I open the app, view other sub or open a thread. And the solution is pretty random too, sometimes I only need to refresh, sometimes I have to go to setting and disable and re-enable force English option.

I used Slide from version 5.4.3 and this is the first time I got this issue, can you fix it?

**Comment by ccrama** [comment]
See #2088, in some places it is not really possible to override this. This method already uses some hacky code, and there's really not a way to make it better, unfortunately
