### ISSUE TITLE
Switching to offline mode crashes the app, and makes it crash on restart.

### ISSUE THREAD

**Issue by krompus** [ccrama/Slide#2273]
Slide version: v5.5.1
Android version: 6.0.1

Persistent after reboot; I had to uninstall/reinstall the app. I tried offline caching and switching to offline mode after the reinstall, and it happened again.

I submitted a crash report just now.

**Comment by ccrama** [comment]
Has recently been fixed, thanks for the report though!

**Comment by krompus** [comment]
Oh, nice. Thanks!
