### ISSUE TITLE
Save text if not able to submit

### ISSUE THREAD

**Issue by real-mizuya** [ccrama/Slide#2274]
Slide version: 5.5.1
Android version: 6.0.1

Sometimes my internet connection is not stable and it's really annoying if I write a something and it can't be submitted. The whole text gets lost and I just get the pop-up with "Un oh, posting this comment failed!"

Can you somehow store the stuff until it's really posted? 
Thank you

**Comment by ccrama** [comment]
It actually automatically saves the text, click the folder icon in the text editor to view your drafts!

**Comment by real-mizuya** [comment]
this happened several times and the text was not saved as draft :(
