### ISSUE TITLE
Swiping to right in offline mode not useful

### ISSUE THREAD

**Issue by andree182** [ccrama/Slide#2275]
Slide version: 5.5.1
Android version: 6.0.1

Swiping to the right appears to switch the cached comments (I have "frontpage" there as first item) after each pixel (or whatever small unit) - so even slightly moving the finger to the right basically switches the current cache multiple times.

The same thing probably happens in "Read later" tab, just the opposite direction.

**Comment by ccrama** [comment]
I'm not quite understanding what you mean, can you include a video please?

**Comment by andree182** [comment]
Sorry... You can reproduce like this:

1) 2x cache the front page
2) start offline mode
3) Now it's possible to choose e.g. "1d (comments)", "2h (comments)", "submissions only" in the dropdown menu. At the same time, there are two tabs below - "FRONTPAGE" and "READ LATER".
4) select the FRONTPAGE tab...
5) swipe to right => The "1d", "2h", "submissions" are chosen rapidly...

**Comment by ccrama** [comment]
I cannot reproduce this, can you upload a video please?

**Comment by andree182** [comment]
here you go - http://github.andree.sk/slide.mp4

**Comment by ccrama** [comment]
Ah that is interesting. Have fixed it! Thanks
