### ISSUE TITLE
Big picture option for subreddit themes gets disabled when changing post layout

### ISSUE THREAD

**Issue by anonymous-user** [ccrama/Slide#2279]
Slide version: 5.5.1
Android version: 6.0.1

So I am using the desktop condensed view for defaults and then I use subreddit themes to enable big pictures for a couple subreddits. This works fine but if I ever decide to tweak any of the picture/thumnail options under Settings -> Post layout, then that will disable the "Always show big pictures in this subreddit" option in Subreddit themes.

**Comment by ccrama** [comment]
I believe at one point this was intended behavior because users could think the setting was not changed when returning to a sub. It was intended that this overrides all subs that were overridden already

**Comment by anonymous-user** [comment]
I would think one would prefer that subreddit themes override the global post layout options though. Anyways if it is intended behavior then I understand and I'll just live with it. Thanks.

**Comment by ccrama** [comment]
Just checked the code and it was indeed intended. Sorry about the confusion
