### ISSUE TITLE
Inconsistent Popup Item Tapping Behaviour (Save Post)

### ISSUE THREAD

**Issue by karlding** [ccrama/Slide#228]
I noticed that the locations I can tap on is slightly different for the option to **Save** the post. For all the other items, you can tap anywhere along the same horizontal plane, which will still trigger the option. However, it seems like the Save option only works when you tap on the Star icon.

I've turned on visual feedback for touches to illustrate what I'm tapping.

Here's a GIF of the **Go to Subreddit** option.
![Go to Subreddit](http://fat.gfycat.com/MisguidedEuphoricCatbird.gif)

And here's the attempt on the **Save** option.
![Save on horizontal](http://giant.gfycat.com/RevolvingSickChuckwalla.gif)

It works when you tap on the **Star icon**.
![Works on icon](http://giant.gfycat.com/KeenInsignificantBat.gif)

**Comment by Alexendoo** [comment]
Others I found with a similar/same issue:

###### When viewing a post:
* Overflow menu
  * /u/username
  * /r/subreddit
  * Save post
* App bar
  * Search button
  * Sort button
* Comment overflow menu
  * /u/username
  * Share comment

**Comment by ccrama** [comment]
Fixed all of them! 399a0d66da43bd3e62ed169e43559e078d5927ff
