### ISSUE TITLE
Offline Mode Issues

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide#2281]
- [x] The first page doesn't load while in Comment Pager mode (it actually didn't work at all, just fixed that though)
- [ ] Swiping between subs changes the time period for that sub

**Comment by that1communist** [comment]
Also, if you go offline while you're on your profile (overview or comments or submitted), and it tries to load the next group, it clears all already downloaded and sends you to the top.

**Comment by Tensounder54** [comment]
This issue is resolved in a later verstion of slide and needs to be closed.
