### ISSUE TITLE
Different colors on name tags for Reddit admins

### ISSUE THREAD

**Issue by Empty2k12** [ccrama/Slide#2282]
Slide is using two different shades of red for coloring admin names. Should probably only be one. (BTW, the whiter red looks better)

**Steps to reproduce**:

1. Open [this link](https://www.reddit.com/r/webdev/comments/5c2vie/were_reddits_frontend_engineering_team_ask_us/) with Slide
2. Compare the admin name under the title to any admin name in the comments

**Screenshot:**
[Here](https://imgur.com/a/Qq7l2)

**Slide version**: 5.5.1
**Android version**: 7.0
**Android patch version**: NBD90Z

**Comment by ccrama** [comment]
Fixed! Good eye
