### ISSUE TITLE
[Suggestion] Circle Icon

### ISSUE THREAD

**Issue by Lionirdeadman** [ccrama/Slide#2285]
Circle icons seems to be Google's design of choice from what we've seen on the Google Pixel. I think Slide should follow that standard.

**Comment by Nxt3** [comment]
Someone asked about this earlier. Not sure about the logistics, but the icon used in Slide was created by someone that ccrama had to pay for. Not sure if this is true or not, but he'd have to pay for another icon (which can be expensive). However, now that ccrama has a Pixel, I feel like he may be more inclined to have this happen! Don't take it from me though, wait to see what he says. :P

**Comment by Lionirdeadman** [comment]
Maybe, haha. I hope so.

**Comment by zlsa** [comment]
I believe circular icons won't work if you have color-changing icons enabled. That said, if ccrama wants to implement circular icons, I can make a circular version of the current icon (assuming it's licensed to ccrama and not owned by the artist).

**Comment by The0x539** [comment]
For what it's worth, I recall the icon designer presenting a selection of icon options, some of them round.

**Comment by ccrama** [comment]
I hired Michael Cook to design one, and this will be included in the next update!

<img src="app/src/main/res/mipmap-xxxhdpi/icon_round.png" align="left"
width="200"
    hspace="10" vspace="10">
