### ISSUE TITLE
Invalid URL when opening redditmedia posts externally or sharing link

### ISSUE THREAD

**Issue by fbis251** [ccrama/Slide#2289]
Slide version: 5.5.2-alpha2
Android version: 6.0.1

This is a post where this error happens, though all redditmedia posts have this error
https://reddit.com/r/funny/comments/5d40ah/easy_mistake/

Steps to reproduce:
1) Settings > Link Handling > Disable internal image view
2) Attempt to open the post image by tapping on the image
3) Invalid URL is opened in the external app

When trying to open externally or sharing a URL from slide, the URL becomes
`https://i.redditmedia.com/s2xVF5jlsfkdRaKu_iTAANJRioGtcTDLXzqEYj4zQrE.jpg?w=587&amp;amp;s=f2bcc2772a145ec8440ad41efa8ad3c0`

The valid URL for the image from that post should be
`https://i.redditmedia.com/s2xVF5jlsfkdRaKu_iTAANJRioGtcTDLXzqEYj4zQrE.jpg?w=587&s=f2bcc2772a145ec8440ad41efa8ad3c0`

The invalid post doesn't decode the `&amp;` parts in the URL

When using the internal image viewer, attempting to open the URL via the post menu > Open Externally loads the correct URL

When sharing, the URL is invalid regardless of whether the images are opened in the internal image viewer or using an external app

Steps to reproduce sharing invalid URL
1) Open a post to a redditmedia image post
2) Tap the post menu > Share link
3) Invalid URL is sent via the share intent

**Comment by ccrama** [comment]
That is a really good find, didn't realize the urls opened externally were not escaped. Added that into the method that opens externally (thankfully all of the settings in LinkHandling go through the same method), should be fixed now. Thank you for finding that!

**Comment by fbis251** [comment]
Hey, I just ran a build of 376d0d9435bd916bf31a1cf02ed98f762dc69d21 and opening externally works fine now, but sharing is still adding `&amp;` into the URL

**Comment by ccrama** [comment]
Whoops, added that to the share as well in my last commit @fbis251

**Comment by fbis251** [comment]
It's working great now! Thanks for the fix

**Comment by ccrama** [comment]
Awesome! You're welcome
