### ISSUE TITLE
[Feature Request] swipe left at the end of album to return to subreddit/comment

### ISSUE THREAD

**Issue by RedDragonx** [ccrama/Slide#2290]
Slide version: 5.5.1
Android version: 6.0.1

At the end of album, swipe left has no effect, I have to press "Back" button to return to what I'm viewing. Can you add a feature to go back by swiping left at the end of album?

**Comment by ccrama** [comment]
Swiping left will already exit the album if you're on the first item, and you can swipe from the very left edge of the screen to exit from any image in the album

**Comment by touzainanboku** [comment]
I think by swiping left they meant swiping to the left, not swiping from the left. The former currently doesn't do anything when you're at the end of an album.

**Comment by RedDragonx** [comment]
Yes, thank you @touzainanboku that's exactly what I mean.
I guess swiping from the left edge is alright but sometime it's hard to do that especially with one hand and on landscape mode, and many people (including me) didn't know about this.
