### ISSUE TITLE
App shortcuts not appearing in Nova Launcher on Android 6.0.1

### ISSUE THREAD

**Issue by gofirst2220** [ccrama/Slide#2291]
Slide version: 5.5.2-alpha3
Android version: 6.0.1
Device: Samsung Galaxy S6
Model: SM-G920A
Carrier: AT&T

I installed the alpha updates with the app shortcuts on my S6 with Nova Launcher beta. The latest Nova Launcher beta have back ported the app shortcuts to older Android versions. But when I pinned the Slide for Reddit app to home screen and took a peak at app shortcuts for it but they are not there. Is there a issue with this?

**Comment by Nxt3** [comment]
That is because Slide is using dynamic shortcuts which Nova Launcher doesn't support for older versions of Android--Nova can only backport static shortcuts.

**Comment by gofirst2220** [comment]
Oh I didn't know that. Maybe Nova Launcher devs could rewrite the app shortcuts thing to support dynamic shortcuts?

**Comment by touzainanboku** [comment]
It probably would've been done already if it were possible. Neither Action nor Nova launcher support dynamic shortcuts on pre-7.1.
