### ISSUE TITLE
Clicking on shared links opens in browser

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2295]
https://reddit.com/r/AskReddit/comments/5dqc4n/redditors_who_have_had_to_work_with_other_peoples/da6oje0?context=3

That link (and many others) load in an external browser when shared in Hangouts with me. The links are generated from Slide and shared to Hangouts. Not sure if this is something that can be fixed.

**Comment by Nxt3** [comment]
I think it is a bug in Hangouts...

**Comment by ccrama** [comment]
I think it may be a bug with Hangouts too, it's just standard share intent

**Comment by Nxt3** [comment]
GDI Hangouts.
