### ISSUE TITLE
Clicking on a comment in the search comments page no longer locates the comment

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#2296]
Slide version: 5.5.2-alpha3
Android version: 6.0.1

This page: http://i.imgur.com/SPyCwcy.png

**Comment by ccrama** [comment]
It's working for me, what does it do for you?

**Comment by Controless** [comment]
Ah, it works now. Wasn't working before, odd. I'll close the issue.

**Comment by touzainanboku** [comment]
@ccrama I think I found what happened. Here's how to reproduce:

- Set view type to comment pane.

- Open a subreddit you're not subscribed to. Alternatively, open a subreddit you're subscribed to by long pressing.

- Open a thread.

- Search something and tap on a comment. 

It doesn't happen with other view types, or if you open a sub you're subscribed to with a normal tap.

**Comment by ccrama** [comment]
Should be fixed now @touzainanboku , thanks
