### ISSUE TITLE
[Feature Request] LaTeX 

### ISSUE THREAD

**Issue by moshpirit** [ccrama/Slide#2297]
There's some subs like /r/Physics, /r/AskPhysics, /r/Math /r/LearnMath, /r/cheatatmathhomework and others where [it's recommended the usage of a LaTeX plugin](https://www.reddit.com/r/Physics/wiki/syntax) to visualize maths equations. It would be very cool to have this integrated in Slide too. Would it be difficult to do?

**Comment by dulleh** [comment]
There are a couple libraries available: 

[aJLaTeXMath](https://github.com/mksmbrtsh/jlatexmath-android)

[MathView](https://github.com/kexanie/MathView)

aJLaTeXMath renders a bitmap given some text whereas MathView uses a webview to render the formulas.

**Comment by ccrama** [comment]
Unfortunately this would add significant processing time to displaying code blocks and would cause a lot of lag for this feature. Although it would look awesome, I think this won't be pursued

**Comment by moshpirit** [comment]
What about some kind of option in the menu called "Activate LaTeX plugin" or something?

**Comment by ccrama** [comment]
I really don't think it would work in a recycling view type of layout, and the time to implement this would not be worth seeing if it is even possible or not. If you or someone else would like to take a stab at it, though, I'd be happy to point you in the right direction to implement it!

**Comment by moshpirit** [comment]
Ok, thanks a lot anyway! :)
