### ISSUE TITLE
Yellow tint colour using the light theme gives little contrast

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#23]
Particularly noticeable by the text cursor in the 'Search for a subreddit' field

**Comment by ccrama** [comment]
Yeah, the light options should only be used with dark themes. I don't really know how I could fix this.

**Comment by Alexendoo** [comment]
Is it possible to have the cursor fall back to black if sufficient contrast isn't available?

**Comment by ccrama** [comment]
Not really, it's just up to the user
