### ISSUE TITLE
Shadowbanned user comments should be labeled as "Removed" rather than "Removed by true"

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#2301]
Slide version: 5.2.2
Android version: 6.0.1

http://i.imgur.com/iHiOF48.png

**Comment by ccrama** [comment]
I don't think it's possible to tell if the user is shadowbanned, only if it is removed. For some reason the removed user is "true" if the user is banned, and that's what Slide displays

**Comment by bb010g** [comment]
I think it would be safe to special case it here, as the user [true](https://www.reddit.com/user/true) doesn't moderate anything. (In fact, it's been inactive for 8 years after having done nothing at all.)

**Comment by ccrama** [comment]
Fair enough, I changed it to "Removed by Reddit" if the removed user is "true"
