### ISSUE TITLE
Continue this thread behavior differs from desktop

### ISSUE THREAD

**Issue by touzainanboku** [ccrama/Slide#2304]
Slide version: 5.5.2
Android version: 6.0.1

If you go to [this](https://www.reddit.com/r/counting/comments/5el4be/1523k_counting_thread_d/) thread and tap "continue this thread" below 1,523,009:

- On desktop you can see until 1,523,018, with the top comment being 1,523,009.

- On Slide you can see until 1,523,013, with the top comment being 1,523,004.

Can this behavior be changed to mimic the desktop site, for consistency's sake?

**Comment by ccrama** [comment]
I don't think that is possible due to how Slide opens links (automatically puts two items ahead, which limits two below)

**Comment by touzainanboku** [comment]
So does it behave similarly to "share comment" where it adds "?context=x"? If so, I understand why it's done for sharing comments (even though I don't necessarily agree with it), but when tapping "continue this thread", the user has already read the thread up to that point. The only thing adding context does is increase the numbers of taps needed to read more comments.

**Comment by ccrama** [comment]
Yes, but that is built into the comment opening code that this method utilizes

**Comment by touzainanboku** [comment]
Can't an exception be added?

Also, in the case of the link I posted, I get 5 context comments. Is that normal?

**Comment by ccrama** [comment]
I added support for context parameters to the open reddit link code and added ?context=0 to continue threads

**Comment by touzainanboku** [comment]
Sweet! Thanks.
