### ISSUE TITLE
Overlapping onscreen navigation and gif controls in immersive mode

### ISSUE THREAD

**Issue by martin-fink** [ccrama/Slide#2306]
Slide version: 5.5.2
Android version: 6.0.1

When watching a gif in immersive mode and showing the gif controls, the onscreen buttons get shown and overlap with the controls

http://imgur.com/SbVPxne

**Comment by ccrama** [comment]
I don't think there is a way to fix this, other than waiting for the on screen buttons to hide again (usually happens within a few seconds while in immersive mode on Android)
