### ISSUE TITLE
DeviantArt image view not working in some cases

### ISSUE THREAD

**Issue by roschlau** [ccrama/Slide#2307]
Slide version: 5.5.2
Android version: Stock 7.0 on an unrooted Nexus 6P

This issue was created from this reddit thread: https://www.reddit.com/r/slideforreddit/comments/5ek41c/deviantart_links_not_working/

When seeing DeviantArt posts from /r/lifeisstrange (and possibly others) on the frontpage, the image viewer doesn't show the image. This happens from the link thumbnail on the frontpage and from individual posts, but not if I tap on the link thumbnail of the post in the subreddit post list. For example, [this post](https://reddit.com/r/lifeisstrange/comments/5efz5l/life_is_strange_run_away/) when opened in slide will not show the image.

Description of the exact steps I do from the frontpage:

1. I tap the post thumbnail (this is just the "link"-thumbnail, I don't actually see a thumbnail of the picture behind the post)
2. The image viewer opens, I now have a semitransparent black overlay with the download- and other buttons at the bottom, back-button at the top, I can still see the front-page through the overlay
3. The progress bar at the top appears and seems to go from 0 to 100 rather quickly, it disappears as it hits 100
4. I would expect the image to be shown anytime now, but nothing happens. With some bigger gifs I often have to wait for a second or two at this point, but the images in question here just never load. I keep staring at my half-overlayed frontpage.

When tapping on the download button in the empty image viewer, a toast says "Downloading image..." and I get the download notification saying "Download in progress", but the progress bar in the notification is stuck at around 50%. Could be exactly 50%, dunno. It's staying there for now, I'll watch if anything else happens.
Interestingly, when I open the image from the subreddit post list where it actually gets displayed, the same thing happens when I press download - the notification comes, the progress bar gets stuck. This time it's stuck at around 2/5 though.

**Comment by Tensounder54** [comment]
This issue is resolved in a later verstion of slide and needs to be closed.
