### ISSUE TITLE
I clicked "support slide" in settings 

### ISSUE THREAD

**Issue by JibbsIsMe** [ccrama/Slide#231]
## Info
see title, sorry I can't add more details! 
## Stacktrace
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{me.ccrama.redditslide/me.ccrama.redditslide.Activities.Don
ateView}: android.view.Infl
ateException: Binary XML file line

**Comment by Alexendoo** [comment]
What version of the app you ya running @JibbsIsMe?

**Comment by JibbsIsMe** [comment]
Actually I just realized I shouldn't have reported this, because I'm using
a GitHub build from a few days ago. If it's fixed already, sorry!!

**Comment by xnaas** [comment]
Are you logged in when you click the button? I know I had issues in the past with the button when not logged into Reddit.

**Comment by xnaas** [comment]
Already fixed.
