### ISSUE TITLE
Slide treats links to youtube channels the same as videos.

### ISSUE THREAD

**Issue by Devinean** [ccrama/Slide#2317]
Slide version: 5.5.2
Android version: 6.0
When attempting to open a link to a youtube channel through slide (with video plugin installed), it opens the embedded player and displays error 400, instead of defaulting to opening externally (which works fine)

Steps to reproduce:
1: View permalinked comment in slide : https://reddit.com/r/electronics/comments/5hl44w/hello_relectronics_im_mark_and_i_solder_tiny/db0zarj?context=3
2: click on YouTube link.

**Comment by ccrama** [comment]
We searched for /user/ but not /channel/, should be fixed now!
