### ISSUE TITLE
Suggestions for data saving mode

### ISSUE THREAD

**Issue by touzainanboku** [ccrama/Slide#2319]
Slide version: 5.5.2
Android version: 6.0.1

This is gonna be pretty long, since I tried to be as comprehensive as possible. Sorry about that. 

<h2>How the current data saving mode behaves</h2>

<h3>Testing method</h3>

Slide doesn't show what *exact* link it's loading, and I only have extremely basic programming knowledge, so my method isn't really ideal, but it's the best I could come up with:

- Set data saving mode in Slide, Clear its cache through Settings -> Apps, remove it from recents

- Send a message to myself in Telegram containing a link to a post, and links to different thumbnail/preview versions from reddit/Imgur ([example message](http://pastebin.com/mDUWKHWB))

- Copy the message, and open the post

- Open the image, wait for it to load and then close it

- Paste the message from Telegram in a comment, preview it

- Open every single thumbnail link and see which one loads from cache (and looks the same as the one from the post itself)

My internet is slow enough that I can actually see if it's loading anything from the internet or not. 

As I'm sure you know, reddit has a bunch of previews in the .json file of each post. According to [this](https://github.com/reddit/reddit/compare/2f7837e826cd0be34eabbb1975578545e5f5631c...df671653f2f6b781c08659372be27d765e7598f1#diff-6850f36502467acb3983f3a877321076R583) and the actual .json files, the width of these previews is 108, 216, 320, 640, 960, and 1080. Naturally, they won't be created if the image isn't large enough. As for Imgur, according to [this](https://api.imgur.com/models/image), each thumbnail has a suffix, and they're as following:

suffix | Resolution
-- | -- 
s | 90x90 square
b | 160x160 square
t | 160x160 thumbnail 
m | 320x320 thumbnail
l | 640x640 thumbnail
h | 1024x1024 thumbnail

There also seems to be "r", but I'm not entirely sure what it is, so I didn't include it in this test. 

<h3>Results</h3>

I tested using 5 different posts: an i.redd.it image, an Imgur image, an Imgur album, and two non-Imgur/i.redd.it images. Here are the results:

\# | Post | With reddit data saving | With Imgur data saving 
-- | -- | -- | -- 
1 | [i.redd.it](https://www.reddit.com/r/EarthPorn/comments/5hm3v6) | reddit 640 | reddit 640
2 | [Imgur](https://www.reddit.com/r/EarthPorn/comments/5hkz4y) | Imgur h (1024) | Imgur m (320)
3 | [Imgur album](https://www.reddit.com/r/araragi/comments/5009jn) | Imgur h (1024) | Imgur m (320)
4 | [non-Imgur/i.redd.it 1](https://www.reddit.com/r/HumanPorn/comments/37h28o) | reddit 320 | reddit 320
5 | [non-Imgur/i.redd.it 2](https://www.reddit.com/r/EarthPorn/comments/5hpwr0) | reddit 640 | reddit 640

Notes:

- When loading all the different Imgur previews with Imgur data saving mode, you have to tap HQ to actually load the image. You will still get the preview version, not the full version. You can make sure of this by testing the square thumbnail versions. They're extremely small and you can't mistake them for the full version. 

- For the Imgur album, I based my testing on the second image in the album. 

- The fifth post can't be opened with the built-in viewer, but the thumbnail loads, and that's what I based my testing on. 

To summarize the results: 

- For non-Imgur images:
  - the same thing is loaded regardless of which data saving mode is enabled.

  - the 640 version is loaded. However, for the fourth post, the 320 version was loaded, even though a 640 version is available (you can check the .json). 

- For Imgur images:
  - the h (1024) version is loaded with reddit data saving mode, and the m (320) version is loaded with Imgur data saving mode.

<h2>Requests/Suggestions</h2>

My main request is the following: 

The data saving option should be based on what resolution is loaded, not which host it uses. I think something like this will be nice: 

Option | Description
-- | --
Low resolution | Uses reddit 320 and Imgur m (320)
Medium resolution | Uses reddit 640 and Imgur l (640)
High resolution | Uses reddit 1080 and Imgur h (1024)

Naturally, each option will use the next highest resolution preview available as a fallback. IMHO, this is less confusing than the current options, while simultaneously giving more control to the user. 

<h3>Alternative</h3>

If you don't agree with my aforementioned request, I hope you at least consider the following as worth changing:

- The current description of data saving mode is reversed. For non-Imgur images, there is no difference, but for Imgur images, you get a higher resolution with reddit data saving. The opposite is stated in the app. 

- Regardless of which data saving mode is used, Imgur images are loaded from Imgur, and non-Imgur images are loaded from reddit. The current descriptions in the app don't match this.

- There is some inconsistency in which reddit preview is used (like the fourth post I tested). 

<h2></h2>

With all that said, IMO Slide still has the best data saving mode among the apps I've used, and it's one of the main reasons why it's my daily driver. 

Once again, sorry for the huge wall of text, and thank you very much for taking the time to read it.

**Comment by ccrama** [comment]
That is actually not quite the case. What I do in data saving mode is select the middle image of the request from Reddit. If three images are returned (full, medium, and low), it selects the middle image always. For Imgur images, it loads the "m" version always while data saving is enabled *through Imgur*. If it's through Reddit, it falls back to the Reddit previews instead of the Imgur data saving.

**Comment by touzainanboku** [comment]
Thanks for the reply!

> That is actually not quite the case. What I do in data saving mode is select the middle image of the request from Reddit. If three images are returned (full, medium, and low), it selects the middle image always. If five are returned, it selects #3, and so on.

I see. So: 

In my first example, there are 6 thumbnails, and it's selecting the fourth. 

In my fourth and fifth example, there are 5 thumbnails, and it's selecting the third. 

So for this part, my findings match what you say. What I didn't know is that it's intended. Sorry for implying it's a bug. 

> For Imgur images, it loads the "m" version always while data saving is enabled through Imgur.

Same for this. 

> If it's through Reddit, it falls back to the Reddit previews instead of the Imgur data saving.

Putting away single images for a moment, AFAIK reddit doesn't create previews for every single image in an album. If you check the .json from my third example (the Imgur album), all the previews are from the first image. I tested using the second image in the album specifically because of this. Am I right in thinking that while the app can/does use reddit for the thumbnail, once you actually open the album it has to rely on Imgur? Because my request is mainly based on what the app does *after* you open the content. 

As for single images, I tested my second example again (cleared cache and all), and the only preview link that the app didn't show a file size or a progress bar was Imgur h. All other previews, reddit or Imgur, were being loaded from the internet. I can upload a video if it matters.

Regardless, what do you think about my request itself? Everything else was an (admittedly) excessively long preface where I was trying to explain where my request comes from. 

Once again, thank you for taking the time to respond. I really appreciate it.

**Comment by touzainanboku** [comment]
OK so as promised, I took screenshots from what Slide displays when using reddit data saving mode, plus every thumbnail preview from reddit and Imgur. [Here](https://imgur.com/a/XhqjH)'s that album.

Then I overlaid all the previews on what Slide shows from the post, and set blend mode to difference, to see which one matches. [Here](https://imgur.com/a/f3qs4)'s that album. As you can see, only Imgur h shows no difference for the image itself (it's black). 

Of course, there's always the possibility that I made a mistake, so you check [this](http://pastebin.com/mDUWKHWB) to see the links I used. You can also use the screenshots I linked above and overlay them. 

Finally, I also recorded a video where I do what I explained in the OP. You can check that video [here](https://streamable.com/ntda). Obviously it's not reddit 108 or 216, and it's definitely not Imgur s, b, or t. They all have a very noticeably lower resolution. As for the remaining reddit 320, 640, 960, 1080, and Imgur m, l, and h, you can see that all of them except Imgur h are loading from the internet. You can see the progress bar, and the file size at the bottom left before they're displayed. 

I hope this is enough to explain why I think Slide is loading Imgur h for Imgur images when reddit data saving mode is used. 

Thanks for reading.

**Comment by ccrama** [comment]
Sorry, your reply must have slipped by. Either way, looks like your PR solved this. Thanks!
