### ISSUE TITLE
Can we turn off infinite scroll?

### ISSUE THREAD

**Issue by Lokesh-Krishna** [ccrama/Slide#2323]
Slide version: 5.5.3
Android version: 7.1.1

Will it be possible to have a toggle that let you turn off infinite scroll? 
I like to limit my time on Reddit but thanks to how amazing this app is and how I never realise how many pages I've browsed (something that I keep track of on the desktop and mobile site) and end up spending a lot more time intended.

**Comment by ccrama** [comment]
Seems to be the same as what #2260 is requesting

**Comment by Lokesh-Krishna** [comment]
@ccrama I'm so sorry. I should have searched harder. And I love Slide :)
By the by, how can I contact you if I want to discuss some other project with you?

**Comment by ccrama** [comment]
@Lokesh-Krishna sending a PM on Reddit is probably the best way to reach me :)

**Comment by Lokesh-Krishna** [comment]
@ccrama I did and you replied. Thank you so much :)

**Comment by ccrama** [comment]
@Lokesh-Krishna  you're welcome!
