### ISSUE TITLE
Bug with collapsing comments

### ISSUE THREAD

**Issue by grumpyfuzz** [ccrama/Slide#2327]
Slide version: 5.5.3
Android version: 7.1.1

This bug happens when 'fully collapse comments' is enabled. Sometimes collapsing a comment causes that comment's text to be replaced with another comment's text. This can be seen here: https://vid.me/1Zfw. [This](https://www.reddit.com/r/hockey/comments/57nt5t/connor_mcdavid_as_a_rookie_its_hard_to_come_into/) is the thread where the bug in the video occurs, and I can reproduce it every time.

**Comment by Tensounder54** [comment]
This issue is resolved in a later verstion of slide and needs to be closed.
