### ISSUE TITLE
Import preferences from RES

### ISSUE THREAD

**Issue by ghost** [ccrama/Slide#2329]
The ability to import (or better yet sync) my presences with Reddit Enhancement Suite would be really useful. Some things I would especially like to import or sync are user tags, filtered subreddits, and accounts, off the top of my head. Another useful feature would be the ability to export my Slide preferences in a format that I can then import on RES. I'm curious what the Slide community thinks about this though, I don't know if this is a niche market or not.

Thread regarding this suggestion:
https://www.reddit.com/r/slideforreddit/comments/5gfsiz/_/

**Comment by ccrama** [comment]
Although it would technically be possible, I think this might be a little out of the scope for a Reddit app, especially one that does not necessarily link to or have support from RES
