### ISSUE TITLE
[Bug] Dropdown menu options are white-on-white in Chrome custom tabs 

### ISSUE THREAD

**Issue by rakeshdas1** [ccrama/Slide#2331]
Slide version: 5.5.4
Android version: 7.1.1

When you go to a linked website, the website loads up in a Chrome Custom Tab. If there is a dropdown menu in the website and you go to click on it to select a menu option, the menu options of the dropdown menu are white. The background of the dialog is also white, as it should be, and hence makes it impossible for the user to read the menu options and chose one. This workaround for this issue is if you open the page externally, the text is readable because the text color is black again. This is what dropdown menus look like in the Chrome Custom Tab:
![screenshot_20161221-175156](https://cloud.githubusercontent.com/assets/6901641/21412207/24517eca-c7b4-11e6-97cb-821918f32499.png)

I have tested this in other apps that also make use of Chrome Custom Tabs and they do not have this issue.

**Comment by touzainanboku** [comment]
I'm pretty sure that's the internal browser, not a Chrome custom tab.

**Comment by rakeshdas1** [comment]
@touzainanboku Huh, I just assumed that it was CCT

**Comment by JukeboxRhino** [comment]
I can say that I have the same issue

**Comment by ccrama** [comment]
Unfortunately the fix for this causes more issues in the Website view, have to mark this as wontfix
