### ISSUE TITLE
Contest mode header unreadable with light theme

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2332]
I'll post a screenshot later. Here is an example thread. 

https://www.reddit.com/r/legaladvice/comments/5jq9ee/flmiamiupdatebeing_sued_for_having_topless_photos/

**Comment by ccrama** [comment]
Do you have any ideas on how to fix it? If it's just an issue with that one theme combo, might not be worth trying to fix

**Comment by Nxt3** [comment]
I think it's using hardcoded white. Might just need to use a different font color.

**Comment by Nxt3** [comment]
![Example of what I mean](https://i.imgur.com/50CxkpY.png)
