### ISSUE TITLE
Request: back button shows menu before an exit confirmation

### ISSUE THREAD

**Issue by ToNIX-** [ccrama/Slide#2333]
I've been using Slide for quite a while and I think it would be a nice addition to have the left menu show up before the exit confirmation when you press back multiple times. 

It could be added in the settings, just before "confirm exit dialog", something like "show menu before closing".

**Comment by ccrama** [comment]
Thank you for the suggestion, but I think that would lead to more confusion for users who have an expectation for the back button behavior in Android. I don't think we are going to pursue this
