### ISSUE TITLE
Log-in issues

### ISSUE THREAD

**Issue by inkcrypted** [ccrama/Slide#2336]
Slide version: 5.5.4
Android version: 7.0.0
Logging into Slide loops around 3 different login screens, the internal one, reddit Mobile version, and the desktop version.  The loop continues even when credentials are correct, with an exclamation point on "password". Logging in reddit on a browser works just fine with same credentials. Resetting Password/create new account does not work, and loops the same 3 sites.

**Comment by ccrama** [comment]
That is an issue with Reddit that is affecting all apps, hopefully the issue is resolved soon (but nothing I can do on my end)

**Comment by inkcrypted** [comment]
Inconsistently, Sync for Reddit, and Now for Reddit work with the login system, and they both seem to be using the same api for login as Slide. I figure the redirect is in place the api gets an invalid response from reddit, but that doesn't seem to be the issues on others. Hopefully, if it's a reddit issue, they fix it soon.

**Comment by ccrama** [comment]
It's a noted issue according to Reddit, if you open the login link in a
browser it won't let you log in either. Gonna have to wait for Reddit to
fix this one.

**Comment by inkcrypted** [comment]
Issue was fixed today morning by reddit.
