### ISSUE TITLE
Downloading images stuck at 100%

### ISSUE THREAD

**Issue by collectorgeneral** [ccrama/Slide#2337]
General Information:
App details:
Version: 5.5.4 ; Source: F-droid
OS: Cyanogen OS 13.1.2, Build: ZNH2KAS3P0 (Android 6.0.1)
Device: Oneplus One (aka A0001 aka Bacon)

Tried downloading some images off of r/spaceporn. I get a notification saying Downloading image... Download in progress. Fills up to 100% and then.. nothing. Seems to me like big images are causing issues, because when I tried for other image on r/pics, it saved just fine.

**Comment by sgango** [comment]
This happens for me as well. There's no option to cancel, so I usually have to force-stop Slide to get rid of the notification.

**Comment by touzainanboku** [comment]
Same here. Seems to happen primarily when I'm downloading numerous large images simultaneously. 

Slide 5.5.4, Android 6.0.1, Xperia Z2.

**Comment by ccrama** [comment]
I think this has been fixed in v5.5.5
