### ISSUE TITLE
[Bug] Mod Tools - Selecting "Ban User" and "Wiki Revise" crashes Slide

### ISSUE THREAD

**Issue by MustardCat** [ccrama/Slide#2338]
Slide version: 5.5.4
Android version: 7.1.1

Selecting either "Ban User" or "Wiki Revise" within Mod Tools' Mod Log crashes Slide.

As a side note - didn't want to make another issue about it but can if needed - could the Ban User entry list the banned user's username?

**Comment by l3d00m** [comment]
1)Clicking the mute user or unmute user action in mod log crashes Slide as well. 

2) Mute user would be more helpful with a username too.
