### ISSUE TITLE
Spoiler Tags confused?

### ISSUE THREAD

**Issue by roschlau** [ccrama/Slide#2339]
Slide version: 5.5.4
Android version: 7.0

So I just opened [this selftext post](https://www.reddit.com/r/Deusex/comments/5l726r/103_hours/) in slide, and as you can see it has quite some spoiler tags. They seemed a bit confused though, as the first one and one of the later ones were showing their content rather than hiding it when the post has loaded. I noticed that in both instances where the spoiler was already showing there seems to be a space missing between the spoiler and the word that comes immediately after it, so maybe that has to do with the bug?

**Comment by l3d00m** [comment]
I can't see any content in the spoiler, a screenshot may help to describe your problem.

**Comment by Hikaru755** [comment]
@l3d00m Yes of course! When I open the post it looks like this:
<img alt="screenshot_20161231-132443" src="https://cloud.githubusercontent.com/assets/16798225/21582459/9e48f6fc-d058-11e6-9efa-28c8f648218d.png" width="300"/>

And if I scroll down a bit:
<img alt="screenshot_20161231-132443" src="https://cloud.githubusercontent.com/assets/16798225/21582461/a4ac0836-d058-11e6-9e62-107d57679885.png" width="300"/>

Actually I just noticed there are three spoiler tags in there that are revealed by default.

(I scaled down the screenshots for embedding, you can view the full-size by right click and "show image in new tab")

**Comment by Tensounder54** [comment]
This issue is resolved in a later verstion of slide and needs to be closed.
