### ISSUE TITLE
FR: Option to show number of new comments/points since last used

### ISSUE THREAD

**Issue by boconnell** [ccrama/Slide#2343]
Similar to how res on the web allows you to see new comments since last viewed, I'd love the ability to toggle an option to highlight the number of new comments/points in a post since last viewed and a button to filter out posts in the feed that have less than a certain threshold of new points/comments since last visited.

**Comment by MustardCat** [comment]
> see new comments since last viewed

Settings > Post Layout > Show comment count since last visit

**Comment by ccrama** [comment]
There is already a setting for comments, don't think we are going to pursue adding this for points as well, though
