### ISSUE TITLE
Opening link causes crash

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#2344]
For whatever reason opening the link in this comment causes slide to crash 

https://reddit.com/r/Cubers/comments/5m8g7h/noob_cuber_here_just_started_breaking_into_the/dc1laz1?context=3

I'm using the built in web view with ad blocking, not chrome custom tab

**Comment by ioangogo** [comment]
What version is installed and what phone do you have

**Comment by ioangogo** [comment]
The page in the link is a WebGL app, This loads on my phone so it may be a few things. You phone does not have enough resources to support it or space oddly

Could you share this:
What phone do you have(Model number if you can get it):
Version:
Store:

**Comment by kufii** [comment]
I've got a Nexus 6P version 7.1.1

Slide version 5.5.4

**Comment by ioangogo** [comment]
Hmm, it seems odd that it crashed your phone with opening the page, Could
you try opening it again just in case it is just one of those 1 time crashes

**Comment by kufii** [comment]
Tried a few more times and it's still crashing. I submitted the crash report

**Comment by ccrama** [comment]
I cannot reproduce this, but it sounds like a memory issue on your device. Try enabling lower quality images in Settings > Data Saving if you are still having this issue
