### ISSUE TITLE
Slide doesn't load posts after a while

### ISSUE THREAD

**Issue by mathiascode** [ccrama/Slide#2348]
Slide version: 5.5.4
Android version: 7.1.1

After I've used Slide for about 15 minutes, or when I leave Slide open in the background for a while and open it again, it doesn't load posts or comments anymore. When I try to refresh a subreddit, all posts disappear. The only way to fix this is to stop the app and start it again.

(I'm not signed in to a Reddit account when using the app)

**Comment by ccrama** [comment]
Should be fixed in v5.6
