### ISSUE TITLE
In-app donation broken

### ISSUE THREAD

**Issue by hroyer** [ccrama/Slide#2354]
Slide version: 5.5.4
Android version: 7.1.1

I wanted to make a donation via the app (Settings > Donate), but it doesn't seem to work. I tried different amounts, but it doesn't work.
Usually, a Google Play payment window pop ups, but not now.

**Comment by ccrama** [comment]
Interesting, they may have updated the library and that may be causing the issue. Thank you for the report!

**Comment by CosmoJG** [comment]
I'm also having this issue on my Samsung Galaxy S6.

Slide Version: 5.5.5
Android Version: 6.0.1

**Comment by ccrama** [comment]
Should be fixed for v5.6, thank you guys for the report and supporting Slide!
