### ISSUE TITLE
Can't see and scroll to reply field, keyboard above it

### ISSUE THREAD

**Issue by real-mizuya** [ccrama/Slide#2355]
Hello, 
I have a very annoying bug, where I can't scroll when I want to reply, because the keyboard (GBoard) gets above the reply field. Since I can'T scroll I don't see what I type and it's really cumbersome. As you can see on the right side of the combined screenshot, you see that I can't sroll further. Am I the only one?

Slide version: 5.5.4 (recent version from Play Store and beta user)
Android version: 7.0

![jointpics_20170118_071026](https://cloud.githubusercontent.com/assets/22096591/22053468/20ec8ad8-dd51-11e6-90ea-36ba7775384c.PNG)

**Comment by touzainanboku** [comment]
Are you using immersive mode? If so, it should be fixed [https://reddit.com/r/slideforreddit/comments/5jc2eg/v554_released_bug_fixes_and_more/dby2fq6?context=3](in the next update).

**Comment by real-mizuya** [comment]
Yes, I use the immersive mode and it's exactly the same issue as the other person in reddit mentioned (from your link). Thanks a lot for fixing 👍

**Comment by ccrama** [comment]
Should be fixed now thanks to @jseybold!
