### ISSUE TITLE
REQ: Setting comment indent indicator depth

### ISSUE THREAD

**Issue by ZeGuitarist** [ccrama/Slide#2358]
Slide version: 5.5.4
Android version: 7.0

Requesting a setting that would allow us to set the depth of the indent for threaded comments - or in other words, the width of those "colored comment depth indicators".

The reason I'm suggesting this is because there are a number of phones with curved glass displays, for which screen protectors are made that cover up a small part of this sides of the screen. Because the screen protector can't adhere to the curved portion at the sides of the display, there's a black adhesive border there that covers up a tiny part of the display on all sides...

I have this issue with my OnePlus 3T, and because of the blacked-out 0.5mm of the right side of the screen, the blue "depth indicator" is obscured, so I can't tell the difference between the mother and first child comment.

A simple way to fix this would be if I were able to make these coloured indicators just a little bit wider. Hence I'm asking if such a feature is possible! I think it would help a lot of users with similar issues, since I believe this is pretty common with screen protectors for curved glass displays...

**Comment by ccrama** [comment]
The next update will have a setting for wider depth indicators in Settings > Comments!
