### ISSUE TITLE
Give a widget to go directly to a subreddit or search posts on reddit

### ISSUE THREAD

**Issue by uncertainquark** [ccrama/Slide#2359]
Slide version: 5.5.4
Android version: 6.0.1

It would be pretty fast and convenient to have a search widget.

It can either be used to go to a subreddit directly or initiate a search for posts.

**Comment by ccrama** [comment]
You can actually already do this by creating a "Shortcut" to Slide, and then choosing the subreddit you want to link to!

**Comment by uncertainquark** [comment]
Hey, you misunderstood I think. What you are suggesting involves me already
having subscribed to the subreddit and manually creating a shortcut to each
one I want.

What I am requesting is completely different. I am saying a search
subreddits widget like the one in the app. Say I can tap on the widget and
start searching for a sub, and it suggests me releavnt subs. I hit
enter/tap one of them and it directly does to that sub.

This would be beneficial because currently one has to open slide, swipe
right and than tap on search subreddits and do the further process.

Having a quick search widget would ease the process and allow fast access
to any subreddit.

**Comment by uncertainquark** [comment]
Hey, any update on this?
