### ISSUE TITLE
GIF last frame time

### ISSUE THREAD

**Issue by HexaCubist** [ccrama/Slide#2360]
Slide version: 5.5.4
Android version: 6.0.1

When a GIF uses frame timings to cycle slower between frames the last frame of the GIF in Slide doesn't respect the timing and immediately skips back to the first frame making it hard/impossible to view the last frame. For example: https://i.redd.it/7jemlsfr05by.gif from post https://reddit.com/r/gifs/comments/5pd6x6/trump_v_women/

**Comment by ccrama** [comment]
This behavior is changed with the addition of ExoPlayer in the next Slide alphas
