### ISSUE TITLE
Preview images not shown for https://www.reddit.com/r/BirdsBeingDicks/

### ISSUE THREAD

**Issue by piyush-rvc** [ccrama/Slide#2363]
Sync shows it. But slide doesn't

**Comment by piyush-rvc** [comment]
https://www.reddit.com/r/woahdude

This also.

**Comment by sgango** [comment]
I can see thumbnails in both /r/BirdsBeingDicks and /r/WoahDude just fine. Are you sure 'Thumbnail mode' (under Settings > Reddit preferences) is switched to 'Always show'?

**Comment by piyush-rvc** [comment]
@sgango no it was set to "per subrredit settings". After switching it to always show, not it shows.

But how was sync and even boost were able to show it, when the setting was set to  "per subrredit settings"?

**Comment by l3d00m** [comment]
I do think that they may not respect this setting and either show none at all oder everything @piyush-rvc

**Comment by ccrama** [comment]
Slide actually respects Reddit settings,  unlike other apps. Not a bug
