### ISSUE TITLE
Image redirects to porn for some reason

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#2365]
Slide 5.5.4
CyanogenMod 13

Link below redirects to porn. I checked it in a browser and it is indeed a cat GIF.

Tried clearing cache and data, didn't have any effect.

https://i.redd.it/z4fpqrrwh4dy.gif

**Comment by ccrama** [comment]
That is because Gfycat sometimes messes up while converting images and returns a url which already exists (and in this case is porn). Unfortunately there is nothing I can do about this except for report the link to the Gfycat developers

**Comment by alexsmithfanning** [comment]
Ah okay. I didn't know that.
