### ISSUE TITLE
Settings dialog some touches pass through to UI behind

### ISSUE THREAD

**Issue by HexaCubist** [ccrama/Slide#2366]
Slide version: v5.5.4
Android version: 6.0.1

(Excuse title gore)
When in the settings, and you open then close a sub page, clicking where the thumbnail is (behind the settings) will open up that thumbnail rather than the button that you clicked in the settings.

Demonstration: https://gfycat.com/PeskyCourteousDeer

**Comment by ccrama** [comment]
Thank you for the report! Unfortunately don't know if there is a way to fix this while still allowing for the settings page to update settings immediately (like base theme, for example), as it has to restart the Settings activity. This sometimes takes more than a few ms, and allows tap through to the bottom activity. If anyone has an idea of how to improve this, feel free to let me know!

**Comment by HexaCubist** [comment]
Perhaps whilst the settings app is open, you could disable
touches/interaction with the main page? Such as that unless the settings
app is explicitly closed you don't register touches?

No experience with Android coding but I guess that's how I'd tackle it if
it's possible to do so.

**Comment by Tensounder54** [comment]
This issue is resolved in a later verstion of slide and needs to be closed.
