### ISSUE TITLE
Bug: gilded icon appears twice

### ISSUE THREAD

**Issue by zeroxxx2** [ccrama/Slide#2368]
http://i.imgur.com/X2m7wgG.jpg

**Comment by ccrama** [comment]
Hmm I cannot seem to replicate this bug. Do you happen to have a link to that submission?

**Comment by zeroxxx2** [comment]
https://www.reddit.com/r/dataisbeautiful/comments/5tfcym/a_simulation_of_360000_1_pixel_pokemon_fighting/

**Comment by Nxt3** [comment]
Doesn't occur for me either.

**Comment by zeroxxx2** [comment]
https://www.reddit.com/r/slideforreddit/comments/5tiit9/bug_gilded_icon_appears_twice/

**Comment by zeroxxx2** [comment]
https://www.reddit.com/r/slideforreddit/comments/5tiit9/bug_gilded_icon_appears_twice/

**Comment by ccrama** [comment]
Sorry, I meant to the post you screen shotted.

**Comment by ccrama** [comment]
Still have not run across this, if you are able to reproduce it later feel free to re-open this with a link to that submission!
