### ISSUE TITLE
/r/Popular - Pop Menu includes Sidebar and Submit Options

### ISSUE THREAD

**Issue by MustardCat** [ccrama/Slide#2377]
Slide version: 5.5.5
Android version: 7.1.1

/r/Popular's menu includes "Sidebar" and "Submit"

![r-popular-menu](https://cloud.githubusercontent.com/assets/23003512/23089067/b1c564e2-f540-11e6-8717-823dbe1a572e.png)

**Comment by ccrama** [comment]
Good find! Should be fixed for the next update
