### ISSUE TITLE
RealPathUtil class is no longer used in the project

### ISSUE THREAD

**Issue by karlding** [ccrama/Slide#2378]
I don't think this class is currently being used. It seems like the import for this class was removed in the commit "[Improved image file from URI, Allow uploading images to album](https://github.com/ccrama/Slide/commit/cbd9ae518d11bf61a99fe1af6a8cd67ed7b1aad8)" 5 months ago, but the class itself was never deleted.

Is this class going to be used for something in the future? If not, should this class be removed to keep the repository clean?

**Comment by ccrama** [comment]
Good find, looks like something I forgot to delete. Will remove with my next commit!
