### ISSUE TITLE
[Feature Request] Picking primary and accent colour for Night Mode

### ISSUE THREAD

**Issue by hroyer** [ccrama/Slide#2379]
It would nice to be able to pick other app colours for Night Mode. For example, I use orange as the primary app colour, but when Night Mode turns on, I'd like the toolbar to be another colour (dark grey), as it would be easier on the eye.

Would this be a possible new option to add?

Thanks again for the great app and frequent updates!

--
Slide version: 5.5.5
Android version: 7.1.2

**Comment by ccrama** [comment]
Unfortunately I don't think something like this would be possible, it would make the UI for themes quite confusing and would not work with the theme system that I have developed for Slide. Thank you for the feedback, though!
