### ISSUE TITLE
When Slide is the bottom app in portrait multiwindow, it's impossible to select the go to Subreddit text field, as it gets immediately deselected.

### ISSUE THREAD

**Issue by lirannl** [ccrama/Slide#2380]
Slide version: 5.5.5
Android version: 7.1.1
Device: OnePlus One (bacon) (tested on several custom ROMs)

This issue only exists in portrait, and only on the secondary (bottom). I tried replicating the issue on landscape mode with Slide on the right (secondary app), and it worked fine, and same goes for when slide was the primary app in the split screen.

**Comment by ccrama** [comment]
I cannot reproduce this, works for me. Might be your keyboard?

**Comment by bb010g** [comment]
Works fine on my Osprey running LineageOS nightly. The screen just slides up.

**Comment by ccrama** [comment]
Will close for now. If you are able to reproduce, feel free to re-open the issue
