### ISSUE TITLE
Crash while scrolling post list after refreshing

### ISSUE THREAD

**Issue by matty1086** [ccrama/Slide#2382]
Slide version: 5.5.5
Android version: 7.1.1 Nexus 6P

I can reproduce this near 100% of the time and is the only source of crashing on Slide that I've found.

If I tap on 'refresh' when slide says no more posts then start scrolling though the list while more load, Slide crashes. Scroll speed seems to not matter.

Kind of difficult to describe so created a repro gif:

http://i.imgur.com/6pltx1d.jpg

Minor, obviously, but would be nice if this was handled a bit more gracefully.

Keep up the great work.

**Comment by ccrama** [comment]
Is this still an issue with the app?

**Comment by matty1086** [comment]
Nope, no longer an issue. Closing the issue. Thanks!
