### ISSUE TITLE
Title colors: unreadable

### ISSUE THREAD

**Issue by smarek** [ccrama/Slide#2386]
Color choice does not look right. If the background is not selected by app, it should probably calculate contrast color to match.

![screenshot_20170308-190732](https://cloud.githubusercontent.com/assets/384824/23717144/f5df6226-0432-11e7-907e-b4ff25531d6e.png)
Slide version: v5.5.4
Android veraion: 7.1.1

**Comment by ccrama** [comment]
Unfortunately the only solution is to remove the colors that aren't readable. We went through about a year ago and removed many of the hard to read colors, if there is a color that seems to be hard to read, you can edit the subreddit theme and lower the brightness a little bit.
