### ISSUE TITLE
Opening a sponsored post crashes Slide every time 

### ISSUE THREAD

**Issue by Empty2k12** [ccrama/Slide#2388]
Slide version: 5.5.5
Android version: 7.1.1

This link is a advertisement which users have bought to be shown on a sub reddit. It will crash reddit every time. 
https://www.reddit.com/comments/5ulva5/transaction_wont_confirm_fees_too_high_find_out/ddwc4cy/

**Comment by ccrama** [comment]
Hmm what are sponsored posts, and where do they show up? I can't say I've run across one so thanks for the report!

**Comment by Empty2k12** [comment]
Sponsored Posts are promoted posts that can be bought from Reddit as a means of advertisement. You can specify ads to target subreddits.

This is how they appear on web: http://imgur.com/a/Zmd2d

In the case of the Bitcoin subreddit it is being used to bring users to the uncensored second BTC subreddit.

Normally the user has no incentive to click any ads, most Adblocks block them.

This is not a request to show reddit ads on top of each subreddit in Slide but rather being able to view the comments a promoted post has.

**Comment by ccrama** [comment]
Thank you for the detailed report! It will now open promoted posts, and it will say "Promoted" in the subreddit text fields

**Comment by Empty2k12** [comment]
Thank you Carlos for this quick fix and making Slide the best Reddit Client out there.
