### ISSUE TITLE
Images, gifs, and thumbnails not loading after scrolling past many saved pictures and gifs quicklu

### ISSUE THREAD

**Issue by eodc** [ccrama/Slide#2390]
Slide version: 5.5.5
Android version: 7.1
Occurred on two of my devices, a Moto g 2015 & OnePlus 3. Force closing the app from recents fixes the issue temporarily, allowing for scrolling farther, but then the big occurs again after scrolling far enough.

**Comment by ccrama** [comment]
That is because it has not finished loading the previous images, and all available download threads are in use. Letting it sit for a minute will fix the issue
