### ISSUE TITLE
Saving large photos causes notifications bar to become unresponsive

### ISSUE THREAD

**Issue by tp0** [ccrama/Slide#2393]
Slide version: 5.5.5
Android version: 6.0.1
Device: Motorola Moto G 3rd Gen

Not sure if this is about the megapixels only, but here's one example:

https://upload.wikimedia.org/wikipedia/commons/4/4e/Macaca_nigra_self-portrait_large.jpg

    2912x4030, 11.7 MP

Repro:

1. Open in Slide: https://www.reddit.com/r/test/comments/5zz9xh/large_photo/

2. Tap the photo thumbnail & download/save the photo

3. Pull down Android's notifications

Result: the notifications bar is unresponsive for as long as the "Photo saved" notification is visible (can be swiped away, which is tricky because of the lag or Slide can be force stopped), .

**Comment by ccrama** [comment]
I made the image now scaled square to 400x400 pixels, and it seems to have improved performance and led to less Android system memory use. Thanks for the report!
