### ISSUE TITLE
Update the gfycat API

### ISSUE THREAD

**Issue by miladmaz12** [ccrama/Slide#2394]
Slide version:
Android version:

**Comment by ccrama** [comment]
What do you mean by this?

**Comment by miladmaz12** [comment]
Sometimes I get error/trouble opening up gfycat links. I kinda assume you are using an old version of gfycat's API.

**Comment by bb010g** [comment]
If you can just provide a description of the bug and steps to reproduce without a diagnosis, it should be easier to fix your issue.

**Comment by ccrama** [comment]
There is no new api, when it says it failed to convert, there was an internal server error on Github's side

**Comment by miladmaz12** [comment]
Oh I see, thanks. Closing this issue now
