### ISSUE TITLE
Subreddit list cut off in autocache settings if too many subreddits are set to cache

### ISSUE THREAD

**Issue by jglass071** [ccrama/Slide#2396]
Slide version: 5.5.5
Android version: 7.1.1

When there are too many subreddits set to automatically cache, the subreddit list is cut off and not all subreddits or the "will back up" text is displayed. For a screenshot see the post in r/slideforreddit by u/squarerootofnothing

I have a Moto G 2015 1GB running Lineage OS on 7.1.1.

**Comment by ccrama** [comment]
Should be fixed, thanks for the report
