### ISSUE TITLE
No search results returned after changing time period in search. 

### ISSUE THREAD

**Issue by eaglz05** [ccrama/Slide#2398]
Slide version: 5.5.5
Android version: 7.0

**Comment by ccrama** [comment]
There may not have been any results for that time period. Reddit search has been having many issues recently but hopefully they will resolve that soon

**Comment by eaglz05** [comment]
Hi, I'm still having issues with change the search results time frame. If I go from default all relevant results, then change to last year, or reverse, no results return.

**Comment by ccrama** [comment]
You will see the same behavior on desktop, it's just because Reddit's search engine is pretty terrible at remaining online or returning results
