### ISSUE TITLE
Rename "Use Chrome Custom Tabs" to "Use Custom Tabs"

### ISSUE THREAD

**Issue by TJFadness** [ccrama/Slide#2399]
Firefox Nightly now supports Custom Tabs. Firefox's implementation of Custom Tabs works as-is with Slide, so no work has to be done there.

**Comment by ccrama** [comment]
@Alexendoo  what would need to be done to do this through Crowdin?

**Comment by Alexendoo** [comment]
Just an upload + pulling down of updates files, stuck both in a PR
