### ISSUE TITLE
Subscribe/Add and Subscribe regression

### ISSUE THREAD

**Issue by robcore** [ccrama/Slide#2402]
Slide version:5.5.5
Android version:5.0

Hey there!
The latest version seems to have broken adding and subscribing for subs from the slide out panel. Choosing either option does nothing. I love the app though, but I figured you should know!
Take care,
Rob

**Comment by robcore** [comment]
Edit: upon downgrading to 5.5.4, it appears that the functions in question actually DO work in the background, they simply don't appear as such in the app.  So it is still broken, but less so :)

**Comment by ccrama** [comment]
It doesn't actually do it in the background, it just doesn't update the text until it is sure the subscribe went through. That is actually intended, as long as subscribing does work
