### ISSUE TITLE
Long Spoiler Tags have display issues.

### ISSUE THREAD

**Issue by GeorgeWL** [ccrama/Slide#2405]
Slide version: 5.5.5
Android version: N Latest Primary Release

Found with [this comment](https://www.reddit.com/r/MovieSuggestions/comments/63txbz/suggest_triangle_one_of_the_best_mystery_movies/dfxn3vl/) but I've seen it before.
 Long Spoiler Tags display as 

> **text in spoiler but visible** | _text in spoiler but only visible on tap, like it should be_

Doesn't affect spoiler tags shorter than two lines.

**Comment by ccrama** [comment]
No, that is actually correct. Looking at the raw formatting, he has the spoiler as the spoiler hint, and as the spoiler text. 

This is his raw comment:

`Not OP and I can say I liked it, but as others have said it has some pretty major plot holes that take away from the overall story\n\nSpoilers ahead\n\n[For me, the main issue with the plot is the motive of the 'protagonist'. So she's killing everybody, but they never reveal why other than a sense of urgency. I know she thinks it's the only way to save her son, but why? How does that make sense? She think she can break the loop and save her son? That she killed? And I guess she loses her memory when the storm comes each loop, but then how does she know she has to kill everybody to save her son? It's just riddled with stuff like that.](/spoiler \"For me, the main issue with the plot is the motive of the 'protagonist'. So she's killing everybody, but they never reveal why other than a sense of urgency. I know she thinks it's the only way to save her son, but why? How does that make sense? She think she can break the loop and save her son? That she killed? And I guess she loses her memory when the storm comes each loop, but then how does she know she has to kill everybody to save her son? It's just riddled with stuff like that.\"`

**Comment by GeorgeWL** [comment]
Ah okay,  the same comment appeared correctly formatted when I viewed it in the desktop browser though.
