### ISSUE TITLE
'Contest mode' banner illegible with 'light' base theme

### ISSUE THREAD

**Issue by sgango** [ccrama/Slide#2407]
Slide version: 5.5.5
Android version: 6.0

The 'contest mode' banner is white-against-white when using the 'light' base theme - it's not just a specific theme _combination_, it's any time the light base theme is used.
[Here's an example.](http://i.imgur.com/RM2Z6v3.png)

I'd suggest changing the font colour for banners to black or grey when the 'light' base theme is being used.

**Edit:** just found issue #2332, which is the same thing.

**Comment by Nxt3** [comment]
Closing since this is a duplicate
