### ISSUE TITLE
Related Submissions no longer works

### ISSUE THREAD

**Issue by uncertainquark** [ccrama/Slide#2410]
Slide version: 5.5.5
Android version: 7.1.1

Related Submissions is not working since some time now. It just shows the loading sign and then nothing happens.

Try it for this link for example: https://reddit.com/r/gnome/comments/64ocbi/return_home_to_gnome/

**Comment by touzainanboku** [comment]
Same here. Doesn't work no matter how many times I refresh.

**Comment by ccrama** [comment]
It is still working for me, I think the issue is there are no related submissions to that submission (there are none on desktop either)

**Comment by uncertainquark** [comment]
Nope, doesn't work, try this one -
https://reddit.com/r/linux/comments/65dm4e/that_sleek_ubuntu_desktop_mockup_is_now_a_real/

It has 2 related submissions.

- J
Typed on mobile, avoid typos.

**Comment by Nxt3** [comment]
Works for me

**Comment by touzainanboku** [comment]
I haven't seen it work for a while either. That's on links that did have other discussions (Sync disolayed them), including the /r/Linux link posted by uncertainquark.

**Comment by ccrama** [comment]
Slide uses Reddit search instead of the related API, because that usually leads to better results. That's why you guys might be seeing different results

**Comment by touzainanboku** [comment]
Is there a reason it's not using the API?

**Comment by ccrama** [comment]
9 times out of 10, it shows more results than the related submissions system does

**Comment by touzainanboku** [comment]
Considering how often reddit's search is broken I'd personally rather have fewer results than none at all.

**Comment by ccrama** [comment]
The issue, though, is Slide uses this system to allow you to share any URL to it and search for submissions that way. The related API takes a Reddit ID, which is not always available

**Comment by ccrama** [comment]
Also found a small bug with the system (restricting the subreddit to "all" returns no results), should be back to normal for the next update
