### ISSUE TITLE
Downloaded image notification crashes SystemUI

### ISSUE THREAD

**Issue by rushsteve1** [ccrama/Slide#2412]
Slide version: 5.5.4
Android version: 7.1.2 (Nexus 6p)

After pressing the download image button on a very large image the notification appeared like usual, but if I attempt to pull down the notification tray I get the "SystemUI has Crashed" popup.

This feature has worked fine until now so I am led to believe that it is the image itself that is crashing the SystemUI.

The image in question:
https://myswordisunbelievablydull.files.wordpress.com/2017/04/guide-to-cute-girls-going-cute-things.jpg

Considering the image is 10.77 MB I'm fairly sure that it is the size.

**Comment by ccrama** [comment]
Images have actually been downscaled for the next update already, thanks for the report!
