### ISSUE TITLE
Imgur links with a suffix won't load when data saving mode is enabled

### ISSUE THREAD

**Issue by touzainanboku** [ccrama/Slide#2413]
Slide version: 5.5.5 (Play Store), 5.5.7-alpha1 (Play Store), 5.5.2 (F-Droid) 
Android version: 6.0.1

**Steps to reproduce**
- Enable data saving mode (doesn't seem to matter which quality)
- Open an imgur link with a suffix (h, m, l, etc). You can test this [here](https://www.reddit.com/r/test/comments/65pv4g/slide_imgur_test/). 

**Result**
The image won't load, no matter how much you wait. If you then tap the HQ button, it'll display the version for the suffix that was in the URL. For example if you open the M version, it won't display anything, and when you tap the HQ button, it'll display the M version (eG3wRSH**m**.png), instead of the original (eG3wRSH.png). 

Here's what I think is happening: when data saving is enabled, Slide tries to add the appropriate suffix to Imgur links. This works fine if the link itself didn't have a suffix already, but if it does, it won't load anything, because the link now has two suffixes (https://i.imgur.com/eG3wRSHmm.png), and is therefore broken. 

I'm assuming fixing this would involve making Slide check for suffixes when trying to open Imgur links, and removing them, and then applying the appropriate suffix based on the settings. I'm not sure how consistent Imgur URLs are, but I'm assuming it's not impossible, since Sync seems to do exactly that. 

(I wanted to make sure I didn't cause this by breaking something when I [added more data saving options](https://github.com/ccrama/Slide/pull/2326), which is why I tested 5.5.2 from F-Droid. It was reproducible when data saving through Imgur was used).

**Comment by ccrama** [comment]
Does the link end in an m or l only if it is resized? What I mean is does the hash ever end in an l or an m. If not, we can easily just chop off the end of the link at the time we get the links and not worry about what happens after that. If not, though, that would make the issue a lot more complicated

**Comment by ccrama** [comment]
Didn't mean to close

**Comment by touzainanboku** [comment]
No, it looks like the original string can also end with an m or l or whatever. The example image I used ends in an m. I think they have a set length though (7 if I'm not mistaken). But I also remember reading somewhere that older Imgur links have a length of 5, so that's something to consider I guess.

**Comment by Tensounder54** [comment]
This issue is resolved in a later version of Slide and needs to be closed.
