### ISSUE TITLE
GIF link opens completely different link

### ISSUE THREAD

**Issue by nielmistry** [ccrama/Slide#2414]
Slide version: 5.5.5
Android version: 6.0.1

I was reading this post on the r/NHL subreddit: https://reddit.com/r/nhl/comments/65zp26/when_you_take_control_of_the_goalie_in_nhl_17/

When I tapped on the gif, instead of showing me a gif about hockey if showed me a gif of some gay pornography. I don't know if its a problem with slide or a problem with Reddit, but someone did comment that it happened to them on their Reddit mobile app as well.

**Comment by nielmistry** [comment]
It doesn't happen on the official Reddit app or the web

**Comment by touzainanboku** [comment]
Slide uses Gfycat to convert gifs that aren't from Imgur or Gfycat itself to mp4. In this case, Gfycat is returning the wrong file. 

Technically not Slide's fault. Although the chances of this happening would've been minimized if #2316 we're implemented.

**Comment by ccrama** [comment]
Unfortunately yes, it is an issue on Gfycat's end and not something I can fix
