### ISSUE TITLE
Changing of app icon color

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#242]
So the app is THOROUGHLY themeable, but the icon is just that same orange. It's fine if that's the default and kind of its identity, but it's possible to make it changeable. For an example of this, look at QKSMS. It's also GPLv3 so one SHOULD be able to take whatever they need directly from there.

**Comment by l3d00m** [comment]
I think it's pretty hard to implement, QKSMS had its problems with it too. It especially doesn't work with custom icon packs.

**Comment by ccrama** [comment]
This is done now thanks to @freundTech !
