### ISSUE TITLE
Lag while loading new post from multireddit

### ISSUE THREAD

**Issue by isiah-lloyd** [ccrama/Slide#2424]
Slide version: v5.6-alpha1
Android version: 7.0

I have a multireddit with about 15 subreddits in it. Everytime I scroll through the posts and the next "page" of posts starts to load, the app slows to a stall for up to thirty seconds.

**Comment by ccrama** [comment]
I am not able to reproduce this, mind uploading a video of that occurring?

**Comment by isiah-lloyd** [comment]
@ccrama https://gfycat.com/CharmingFairJumpingbean 

Notice my attempts to move the screen and the spinner stopping every time a new section of posts is loaded

**Comment by ccrama** [comment]
Can you try on the latest alpha? Alpha #2

**Comment by ccrama** [comment]
Should be fixed now
