### ISSUE TITLE
Slide doesn't show in application switcher

### ISSUE THREAD

**Issue by pcmaster160** [ccrama/Slide#2426]
Slide version: 5.6
Android version: 7.0

This occurs on my Galaxy S8. Not sure if there is a setting I missed or a issue with Android 7 support but when pressing the app switcher button from the app after opening it makes the app fly away into the top left and not show in the app switcher. Even though it is still open. 

I have seen it in the app switcher in a few instances but don't know how to reproduce this. The vast majority of the time it is missing.

**Comment by ccrama** [comment]
Is this issue still occurring?

**Comment by pcmaster160** [comment]
Yep, flies to the top left corner when pressing the application switcher.

To repro: Open Slide, hit application switcher.

**Comment by ccrama** [comment]
That is likely an issue with your rom as the app switcher is an OS level function

**Comment by pcmaster160** [comment]
I'm running stock Galaxy s8 ROM

**Comment by ccrama** [comment]
Can you take a video of what's happening?

**Comment by pcmaster160** [comment]
Just thought of something to try and I was right.

This only occurs when Color app icon is enabled. That should help a lot

**Comment by ccrama** [comment]
I still don't understand what you mean by flying to the top left

**Comment by pcmaster160** [comment]
![hi](https://media.giphy.com/media/xUNd9UYGbW0JAkgpS8/giphy.gif)

**Comment by ccrama** [comment]
That is definitely a system issue, unfortunately not much I can do unless I can get my hands on an S8 to test with. For what it's worth, this does not occur on my brother's S8

**Comment by Tensounder54** [comment]
If anyone (thats not @pcmaster160 ) can reproduce this issue on a Samsung Galaxy S8 in Slide version 5.9-alpha2 please reply here so that this issue can be looked at.

**Comment by Tensounder54** [comment]
As @ccrama said this is a system level issue and as such is not an issue that can be resolved by the Slide Dev Team. As such I'm closing this issue.
