### ISSUE TITLE
Notification buttons have gigantic icons

### ISSUE THREAD

**Issue by touzainanboku** [ccrama/Slide#2432]
Slide version: 5.6.1
Android version: 6.0.1, 5.1.1

When you save an image, the share and delete buttons have gigantic icons. 

[Screenshots](https://imgur.com/a/w4hf1)

Wanted to make sure it's not because I'm running a custom DPI, which is why i tested on my Z1 with stock DPI.

**Comment by ccrama** [comment]
I believe it has been fixed for a while now
