### ISSUE TITLE
Can't click on anything after opening any links, comments, etc. Once

### ISSUE THREAD

**Issue by gofirst2220** [ccrama/Slide#2435]
Slide version: 5.6.1
Android version: 7.0 Beta 3
Device: Samsung Galaxy S6

See title, after I click on gifs, links, posts, etc., The app freezes. I have to force close it to open anything else. But this bug still persists after force closing and opening it again to click on another post.

**Comment by ccrama** [comment]
Assuming this issue is fixed now
