### ISSUE TITLE
Sliding between comments pages sometime a doesn't load the next page

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#2441]
Just reopening #2192 because my PR didn't actually fix it. The problem with my PR is that the GC was disposing the PostLoader object, which was causing NullReferenceExceptions. I don't really think I know enough about android dev to fix it so I'll just reopen an issue

**Comment by Tensounder54** [comment]
This issue is resolved in a later version of slide and needs to be closed. As referenced by me in #2521.
