### ISSUE TITLE
Automatically mark posts as read on scrolling

### ISSUE THREAD

**Issue by Generator** [ccrama/Slide#2444]
**Slide version:** 5.6.1 (F-Droid)
**Android version:** 7.1.2

Automatically mark posts as read when posts go offscreen on vertical scroll.
Useful to use it with "hide read" button

Slide is a great app, but hide read posts is still a big missing feature, is really annoying to scroll all the way till new posts, some other apps (like Sync for Reddit) have that feature, when scrolling /r/all most of the users don't open all posts, the "hide read" button only hides posts that had been open, marking post as read would fix that issue.

**Comment by Nxt3** [comment]
Settings > History. Mark posts as seen when scrolling.
