### ISSUE TITLE
404 - Not found issue

### ISSUE THREAD

**Issue by memetg** [ccrama/Slide#2449]
Slide version: v5.6.1
Android version: Marshmallow on Zenfone2
Only in system language: Turkish

What happens: any subreddit that includes the letter capital "I" in its name is shown incorrectly, or not shown at all. Two examples I can give are IAmA and DIY subreddits. Slide tries to show me AmA and DY subreddits; a subreddit with the name AmA exists, so I am shown a different subreddit. DY does'n exist, so I am shown a 404 error instead. 

Possible reason: I-ı and İ-i are separate letters in Turkish and there is no pair like I-i. So, DIY would be dıy in lowercase. Slide omits "ı", which doesn't exist in English, and tries to find dy, and gives a 404 error as a result. Same with IAmA -> ıama -> ama. This is a slide-only problem, it doesn't exist on other reddit clients. 

What's supposed to happen: It should have shown DIY subreddit instead of looking for dıy. The solution would be to make sure that it uses the english language when making capital letters lowercase.

Steps to reproduce to issue: 
1. make the system language turkish.
2. clear application data or reinstall slide (it should be opened first time with a clean cache in turkish)
3. open the app.
4. visit "dıy" or "iama" subreddit from the list of subscribed subreddits that comes by default on the left menu, or any subscribed subreddit that includes the letter "I", or "ı". 

Temporary workaround: change the system language to english, open slide, login to your account/accounts and then revert back to turkish system language; correct links to subscribed subreddits persist in that case.

**Comment by ccrama** [comment]
Thank you for the report! You are correct that Slide sanitizes fields, and removes all non-english characters. Unfortunately if you tried to go to IAmA using the turkish I, it will also fail as the turkish I is not the same as the English I. I think Slide is behaving as intended, and the input you are trying has to change

**Comment by memetg** [comment]
no, i think you misunderstood; it's good when i type (and of course i am not typing an "ı", it's buggy when i try to visit pre-subscribed subreddits. this is clearly a bug. try the steps to reproduce the issue for getting clearly what i try to say.

to explain it further; slide comes with some list of default subreddits (on the left panel and on the top row), right? and that list already includes diy and iama, so you don't have to "type" anything. just make the system language turkish, uninstall-reinstall the app, and browse through the subreddits comes with slide by default (on the upper menu and the left menu); every single one works, diy does not work, iama redirects to ama. however, there's no problem with "askreddit". the official names of these three subreddits are DIY, IAmA, and AskReddit; apparently, slide experiences problems when trying to open DIY and IAmA, but not AskReddit, which has a lowercase "i" in its name, not a capital one.

again, i am not typing anything, just tapping the items in slide menus, either the subreddits comes with slide by default, or my subscribed subreddits, after i login. and again, i haven't experienced the same problem with any other reddit client, so, it's probably not a reddit related bug.

**Comment by memetg** [comment]
a gif and a vid (in a zip) representing the issue is uploaded, if you're interested:
![afrt6roukakc_a](https://user-images.githubusercontent.com/17992758/28231736-c75b5e82-68f5-11e7-8190-260d06e0038b.gif)
[slide.zip](https://github.com/ccrama/Slide/files/1149731/slide.zip)

**Comment by memetg** [comment]
i'll not follow the issue anymore, using another client. so: solved.

**Comment by ccrama** [comment]
For what it's worth, it's behaving as expected on Stock Android O and I have not had any other reports of anything similar. This is actually something that Reddit does on the server end (using international characters), and not something Slide can fix (the subreddit names are synced FROM Reddit)

**Comment by ccrama** [comment]
The next update forces the turkish I to turn into a regular I, but highly suspect it's related to your device specifically

**Comment by memetg** [comment]
thank you, just in case you are not forcing all characters to english: the problematic pair is "I -> ı", it must be "I -> i" (or just force "ı -> i"). No problem with the places where yo see "İ" although it's not an English character.

**Comment by ccrama** [comment]
Java automatically changes the american I to an i if you do .toLowerCase(), all I did was tell it to keep the encoding in English. I don't think it changes any other behavior if it is truly the english I to begin with

**Comment by memetg** [comment]
update: updated today and the issue is resolved with the new version. all subreddits work as expected after a clean install with turkish locale. 

thanks.

**Comment by ccrama** [comment]
Awesome! Glad to hear it
