### ISSUE TITLE
Be able to check what subs a redditor moderates (when viewing profiles)

### ISSUE THREAD

**Issue by KeronCyst** [ccrama/Slide#2450]
Slide version: 5.6.1
Android version: 6.0.1

Just an optional button for those who are interested in seeing what subs a given redditor moderates, if any.

**Comment by tryton-vanmeer** [comment]
Was looking into implementing this. Sadly the Reddit API only exposes if a user is a mod or not, and not a list of the subs they are mods of.

**Comment by bb010g** [comment]
https://www.reddit.com/r/redditdev/comments/5k9r5s/still_no_praw_ability_to_examine_a_redditor_and/ may be helpful.

**Comment by ccrama** [comment]
Unfortunately that workaround is not really a workaround, just trying to scrape html to find the moderated subs. That sucks, wonder why that is missing from the Reddit API? Will close for now, if Reddit implements an API for this I'd gladly implement it, though!

**Comment by bb010g** [comment]
@ccrama reddit/reddit#1414 is the relevant PR for the API.
