### ISSUE TITLE
Cannot press-hold on locked post's comments

### ISSUE THREAD

**Issue by KeronCyst** [ccrama/Slide#2452]
Slide version: 5.6.1
Android version: 6.0.1

I want to share the explanatory comment on https://reddit.com/r/pics/comments/6cqsn3/fake_homeless_woman_from_front_page_arrested_rva/

**Comment by KeronCyst** [comment]
Never mind, I was able to do it now that I've revisited the post. I don't know what happened. I expanded some comments (default settings are set to collapse all non-top-level), and then press-holding wouldn't do anything except expand/collapse child comments.

**Comment by KeronCyst** [comment]
Not a locked post, but I was able to duplicate this problem (apparently it had nothing to do with locked posts, I think – just massive ones):

https://reddit.com/r/GameDeals/comments/6colmw/steam_starpoint_gemini_2free100/

Going here, with all child comments collapsed by default (not sure if that is a factor), expanding some, and then trying to press-hold on /u/josh6499's comment to upvote/save the link would only alternate between expanding and collapsing its one child comment: the same effect as tapping the comment.

I was able to fix it by using the 3-dot option button to collapse all comments in the post, then press-hold again.

**Comment by Tensounder54** [comment]
This issue is resolved in a later version of slide and needs to be closed.
