### ISSUE TITLE
PM-sending problems

### ISSUE THREAD

**Issue by KeronCyst** [ccrama/Slide#2454]
Slide version: 5.6.1
Android version: 6.0.1

I just lost a *gigantic* PM to another redditor that didn't send for some reason. I think it may be because I accidentally hit the back button during the black screen that lingered shortly after I submitted the PM. It waited in black longer, and then returned me to my inbox with no record of the PM text.

I think a helpful failsafe to counter this would be to provide an optional checkbox that, when checked, auto-saves the text of your PM as a draft right before actually sending it.

**Comment by KeronCyst** [comment]
It failed to send a different PM again, and I didn't hit Back this time, but just waited. Thankfully I saved a draft before sending so I lost nothing, but now I know the failure was not because of user error. Are PMs working?

**Comment by ccrama** [comment]
That is because Reddit is having issues with their Captcha system, removed it for the next update and it appears to still allow posting, so hopefully that workaround will work

**Comment by KeronCyst** [comment]
Oh, I had no idea Reddit started putting in captchas for PMs.

**Comment by ccrama** [comment]
Actually they always have, but they recently removed that necessity and the API I used to check seems to have been removed as well
