### ISSUE TITLE
Wording of licensing addition

### ISSUE THREAD

**Issue by Calinou** [ccrama/Slide#2456]
[The end of the README](https://github.com/ccrama/Slide#licensing) says:

> In addition to the terms set by the GNU v3 Public License, I ask that if you use any code from this repository that you send me a message to let me know.

Even though this is not part of the [license file](https://github.com/ccrama/Slide/blob/master/license.txt), this may be perceived as a legal requirement – and, in order to be compliant with the [open source definition](https://opensource.org/osd) and the [Free Software definition](https://www.gnu.org/philosophy/free-sw.html), it should not be required to ask to be contacted in case code is reused in another project. (This is usually called the "desert island" test, because such a clause would be impossible to satisfy without Internet access, for example.)

Would you please reconsider the wording of that sentence so that there is no ambiguity about this part being optional? Thanks in advance.

**Comment by ccrama** [comment]
Meant to do this much earlier, just removed that line totally from the readme. Thanks for the information!
