### ISSUE TITLE
Problems with the layout

### ISSUE THREAD

**Issue by captainepoch** [ccrama/Slide#2460]
Slide version: 5.6.2.
Android version: 7.1.2 (LineageOS 20170525 build, LG Nexus 4 aka mako).

---

When I open the app (and a text post, but it happens with images as well), the top of the app 'cuts' with the title bar. Screenshots added as imgur links:

Screenshot 1: [http://imgur.com/Sm6H6lJ](http://imgur.com/Sm6H6lJ)
Screenshot 2: [http://imgur.com/QNi2SGX](http://imgur.com/QNi2SGX)
Screenshot 3: [http://imgur.com/uKoc3EB](http://imgur.com/uKoc3EB)

**Comment by ccrama** [comment]
Do you have any display zooming or changes to your display density enabled by chance?

**Comment by captainepoch** [comment]
As far as I know LineageOS comes with default dpi and I didn't touch it or any other config values.

**Comment by alexsmithfanning** [comment]
I'm on LineageOS 14 and mine does the exact opposite. I creates _more_ room, and leaves a gap.

**Comment by captainepoch** [comment]
I don't know then... A friend of mine doesn't have this problem with a Moto X and AOSP...

And I swear I have stock values of DPI and that kind of stuff.

On May 29, 2017 8:20:23 PM GMT+02:00, Alex Smith-Fanning <notifications@github.com> wrote:
>I'm on LineageOS 14 and mine does the exact opposite. I creates _more_
>room, and leaves a gap.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ccrama/Slide/issues/2460#issuecomment-304710683

- - - -
adolfo santiago
adol.pw
GPG Public Key:
  pgp.adol.pw/dolfism_gpg.txt
**
I'm on my mobile phone, sorry for the brevity of the message.

**Comment by captainepoch** [comment]
I'm going to close this issue. It seems to be random. It doesn't happen with an AOSP rom, but with LineageOS is completely random.
