### ISSUE TITLE
Link invocation is broken

### ISSUE THREAD

**Issue by KeronCyst** [ccrama/Slide#2461]
Slide version: 6.5.2
Android version: 6.0.1

The link at the very bottom of this screenshot:
http://imgur.com/tgNw6o7

... leads me to:

https://reddit.com//r/redditrequest/comments/67jhoy/requesting_rredditabuse/

... and whenever I keep pressing "Just Once," the same popup just momentarily leaves and comes back again. It never actually takes me to the link.

**Comment by KeronCyst** [comment]
Oops, Slide *5.6.2 lol.

**Comment by ccrama** [comment]
That appears to be an issue with the link you are clicking and not with Slide itself

**Comment by KeronCyst** [comment]
You're right! I didn't see the double /'s. That said, Chrome is still able to take me to the correct page. Could Slide be set to also handle two /'s after "/r?"

**Comment by KeronCyst** [comment]
It was on /r/redditrequest. I just PMed the admins and they fixed the double slash (/u/request_bot had faulty link-coding) so this should not happen again.

**Comment by ccrama** [comment]
That would be tough to parse if it was http://, and would require a more complex fix than just replacing "//" with "/". Gonna close this one for now
