### ISSUE TITLE
Copying error

### ISSUE THREAD

**Issue by KeronCyst** [ccrama/Slide#2462]
Slide version: 5.6.2
Android version: 7.1.2

When you go to "Copy Text," yet you don't highlight any text but just press "Copy," it says you copied text but actually it wipes your clipboard.

The proper fix for this is to pop up a toaster message that says, "You just wiped your clipboard, you dolt!"

Alternatively, maybe this means you could get rid of "Copy All" and just make the "Copy" button copy all if no text from the comment is highlighted. ¯\_(ツ)_/¯

**Comment by ccrama** [comment]
Fixed
