### ISSUE TITLE
When reporting posts or comments

### ISSUE THREAD

**Issue by KeronCyst** [ccrama/Slide#2463]
Slide version: 6.5.2
Android version: 7.1.2

When reporting posts or comments, it seems we must always type in a reason. Will there be incorporation of the provided drop-down boxes (spam, harassing, personal information, subreddit-specific settings)? This would be particularly helpful in a subreddit with customized reporting like, say, /r/freebies (try reporting content there to see all the specific buttons that they have).

**Comment by ccrama** [comment]
Unfortunately that is not part of the Reddit API and cannot be implemented
