### ISSUE TITLE
Flexible comment-press functions based on absence of children

### ISSUE THREAD

**Issue by KeronCyst** [ccrama/Slide#2465]
Slide version: 5.6.2
Android version: 7.1.2

In the default controls, you have to press and hold on a comment to reach the vote arrows, reply button, and more actions. Tapping expands child comments.

You *still* have to hold to reply, even if there are no child comments.

I propose the addition of an option that allows the vote/reply panel to be dynamically accessed, only needing a tap to open (even if you normally have to press-hold for it), if the comment in question has no child comments.

**Comment by ccrama** [comment]
Done for the next alpha
