### ISSUE TITLE
Account switching on Android O DP3

### ISSUE THREAD

**Issue by matty1086** [ccrama/Slide#2470]
Slide version: 5.6.2
Android version: O Developer Preview 3; Nexus 6P

Now that APIs are finalized for Android O, I wanted to send along the only issue I've run into on the O previews (2 and now 3 as well)

Steps to reproduce:
1) Have 2 accounts added to Slide prior to upgrading to O
2) Upgrade to O
3) Switch accounts to the 2nd account
4) Slide loads the second account with the following:
    i) Proper subreddits in the left slide out
    ii) Incorrect frontpage. The front page is from the 1st account

To get back to the first account:
1) Attempt to switch back to 1st account, but unable to tap it
2) Tap the 2nd account that is already "loaded"
3) While the account is loading, slide out the left drawer quickly before loading completes
4) Tap the 1st account. This will get you back to the first account as expected.

I have cleared app data with no luck. This actually gives a slightly different behavior adding both accounts on O:

1) Add account #1. All subreddits load as expected
2) Add the 2nd account.
3) Slide acts like its downloading subreddits and syncing colors, however, the list of subreddits stays the same as the first account that was just added. The front page is also for the 1st account.
4) Swapping accounts has the same behavior as in the 2nd example.

**Comment by ccrama** [comment]
Accounts aren't linked to Android in any way, sounds to me more like your save file became corrupted in some way. Does clearing data or reinstalling fix this issue for you?

**Comment by matty1086** [comment]
No, clearing data does not help when i setup both accounts from scratch. Please see the behavior I see then that I posted in the original issue above:

I have cleared app data with no luck. This actually gives a slightly different behavior adding both accounts on O:

Add account #1. All subreddits load as expected
Add the 2nd account.
Slide acts like its downloading subreddits and syncing colors, however, the list of subreddits stays the same as the first account that was just added. The front page is also for the 1st account.
Swapping accounts has the same behavior as in the 2nd example.

Let me know if there is anything else that I can provide.

**Comment by aaronpoweruser** [comment]
I can repo this on ODP3 as well

**Comment by ccrama** [comment]
Does killing the app after switching accounts fix the issue? Account switching code hasn't changed in over a year and a half, so I'm a little confused as to what could have changed

**Comment by matty1086** [comment]
Just tried switching accounts, force killing the app, and reopening.
The same thing occurs at that point - the proper subreddit list loads properly in the left slideout, but front page is for the first account.

I don't think it's anything that has changed in your app - this is an issue on O DP3. Something in Android must have changed that is no longer playing nice with that portion of code.

**Comment by ccrama** [comment]
Fixed in latest alphas, issue was Java 1.8 garbage collected the variable referenced later in the callback, which did not occur in Java 1.7
