### ISSUE TITLE
Allow choice of external browser

### ISSUE THREAD

**Issue by yaomtc** [ccrama/Slide#2472]
I have one browser ("Jelly" browser by LineageOS devs) set as the default browser in Android. However, I want to use Firefox for all links opened from Slide. Can you add an option to choose the external browser? Thanks.

Slide version: 5.6.2
Android version: 7.1.2

**Comment by ccrama** [comment]
That is actually an issue with links invocation in Android, you need to reset the default for the browser you don't want, and select the browser you want next time you click a link in Slide
