### ISSUE TITLE
Accidentally swiped down and refreshed while reading a post, lost comment I was typing

### ISSUE THREAD

**Issue by KeronCyst** [ccrama/Slide#2477]
Slide version: 5.6.2
Android version: 7.1.2

If you have begun commenting on a post, prevent swipe-downs from immediately refreshing all the content and losing your material.

1. Auto-draft the text, or

2. Pop up a warning, saying, "Are you sure you want to refresh? You will lose your comment in progress."

**Comment by Alexendoo** [comment]
Note: still applies when refreshing if you're replying to a comment that is hidden in the first comment response

**Comment by Tensounder54** [comment]
The issue seems to be resolved in Slide version 5.9-alpha2. This may need varification but I'm pretty certain this is the case. We may be able to close this issue.
