### ISSUE TITLE
Be able to browse through subreddit names

### ISSUE THREAD

**Issue by KeronCyst** [ccrama/Slide#2478]
Slide version: 5.6.2
Android version: 7.1.2

At the moment, Slide can only receive exact subreddit name searches in "Go to subreddit," or it can go nowhere. It would be nice to be able to browse through search results for subtitles with named that are close to the query!

**Comment by touzainanboku** [comment]
Tap discover in the navigation drawer, then tap the search button and enter your query there.

**Comment by KeronCyst** [comment]
Oh. Thanks. Man, the search engines in Slide are all over the place; the magnifying glass in the top bar, the subreddit filter-search, this subreddit name search...
