### ISSUE TITLE
[Feature Request] push notifications like Sync for Reddit

### ISSUE THREAD

**Issue by kiwiapple87** [ccrama/Slide#2480]
Slide version: 5.6.2 beta
Android version: 8.0.0

It requires the official Reddit app to be installed but when the official app receives a notification Sync will also receive it. It doesn't show the notification of the official app just a notification from Sync. This is also present in the twitter app Flamingo .

**Comment by ccrama** [comment]
I believe that goes against the Play Store TOS?

**Comment by kiwiapple87** [comment]
I have read through the TOS and the GP Business and Program Policies and nothing in them jumps out at me that this would violate. Also, Sync has had this for a month I know and Flamingo has had it for longer with no issues.

**Comment by ccrama** [comment]
Done
