### ISSUE TITLE
Long images aren't properly shown if they are hosted by Reddit (i.redd.it)

### ISSUE THREAD

**Issue by rakeshdas1** [ccrama/Slide#2490]
If there is a post with a super long image like [this one](https://reddit.com/r/TheSimpsons/comments/6ocn8v/the_best_simpson_faces/), Slide only shows a snippet of the image. You can't scroll up or down either, it's like Slide "cuts" the image and shows that image instead.

Expected behavior is to show the entire image but zoomed out.

Screenshot of what happens:

![Snippet of the image](http://i.imgur.com/xRm1beI.jpg)

**Comment by touzainanboku** [comment]
You can see the full image if you tap the HQ button.

**Comment by rakeshdas1** [comment]
@touzainanboku ah, that makes sense, thanks!
