### ISSUE TITLE
"Save GIF" option has extra string data added to file name and button

### ISSUE THREAD

**Issue by MustardCat** [ccrama/Slide#2491]
Slide version: 5.6.3
Android version: 7.1.2

After the latest update, the "Save GIF" button now includes extra string data.  I'm guessing this is from the change away from Gfycat. 

If you select the Save GIF option, it'll also include that extra data in the file name.

I'm not sure if this is new as I normally don't save GIFs, but the "GIF" also doesn't save in the subreddit's folder (the MP4 version does though); it saves into the root directory set in the General settings

http://imgur.com/a/6LLTW

**Comment by ccrama** [comment]
Just curious, what happens if you try to open that file?

**Comment by MustardCat** [comment]
Without changing the filename, Solid Explorer asks what app it should use to open it.

If I change the filename to .gif, no thumbnail is created and the gif does not load (Solid Explorer red X appears).

If I change the filename to .mp4, a thumbnail does appear but VLC and Solid Explorer both have problems playing the video.

VLC shows either a black or white screen.  If it's a white screen, VLC will come back a few seconds later with "VLC is not responding".  It never plays in VLC.

If I use Solid Explorer (SE View), the file plays at about 1 FPS

**Comment by Tensounder54** [comment]
This issue is resolved in a later version of slide and needs to be closed.
