### ISSUE TITLE
Change default search method to both "search in drawer" and "long press"

### ISSUE THREAD

**Issue by uncertainquark** [ccrama/Slide#2493]
Slide version: 5.6.2
Android version: 7.1.2

Both the search options are not in conflict with each other and hence it might be better to enable both as default instead of just "search in drawer."

![screenshot_20170718-232413](https://user-images.githubusercontent.com/22585732/28497405-ccee5f44-6f75-11e7-9429-ef794e27820a.png)

**Comment by Nxt3** [comment]
It's currently setup to be the drawer by default since it's visually accessible. If we had both enabled by default and a user didn't know about this setting, they might be confused if they accidentally long pressed on the toolbar.

**Comment by ccrama** [comment]
@Nxt3 's answer is correct
