### ISSUE TITLE
Save NSFW History shouldn't be enabled by default

### ISSUE THREAD

**Issue by uncertainquark** [ccrama/Slide#2494]
Slide version: 5.6.2
Android version: 7.1.2

Is there a reason NSFW history is enabled as default? How about a browser-like "Enter Private/Incognito" mode added instead?

![screenshot_20170718-232653](https://user-images.githubusercontent.com/22585732/28497447-d0425ad2-6f76-11e7-9a22-6fab2da00f28.png)

**Comment by Nxt3** [comment]
Just disable NSFW history. That's what you want.

**Comment by ccrama** [comment]
I do agree NSFW history should be disabled by default, though, but disabling all history is like going incognito

**Comment by uncertainquark** [comment]
Incognito is just an extra suggestion, you can ignore that. My primary issue was with NSFW history being enabled by default.

**Comment by ccrama** [comment]
Defaulted to false now in v5.6.5!

**Comment by aviwad** [comment]
Sorry to necrobump, but I wanted to add that I believe "incognito" option would come in handy, because it also makes the keyboard incognito (like how Telegram does it in Secret Chats, or Chrome in incognito).
