### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by antoniotorresm** [ccrama/Slide#2496]
The changelog that is linked in the [app and in F-Droid](https://github.com/ccrama/Slide/blob/master/CHANGELOG.md) is way outdated (last version registered is 5.4.2, current version is 5.6.5). Please update it so we can know what's new in Slide :)

**Comment by ccrama** [comment]
That was a mistake, the current version is 5.6.3 alpha and F-Droid decided to build a pre-release alpha version because I accidentally pushed the tag. There is nothing new in the F-Droid version yet, stay tuned until the alpha is done
