### ISSUE TITLE
Not able to access NSFW subreddits.

### ISSUE THREAD

**Issue by kiwiapple87** [ccrama/Slide#2497]
Slide version: 5.6.3
Android version: Android O DP3

[Screenshots](https://photos.app.goo.gl/7xPmUeEpsj5Mi05a2)

When I try to go to a NSFW subreddit in Slide it has a pop up that asks me if I am over 18 and willing to see adult content you can disable this permanently in Settings --> Reddit Preferences --> show nsfw content. With a button for 'Go Back' or 'Continue' if I hit continue it shows no posts in the sub. 

In the screenshots I have this message and when happens when I hit continue as well as my app settings for NSFW content.

**Comment by CyanJDroid** [comment]
Have this issue as well. Android 7.1.2, Slide 5.6.3

**Comment by cordage** [comment]
Same issue. Slide seems to ignore Reddit settings when you go to a sub from a post, discover, or entering the name; however you can subscribe and go to that sub from the subscription list with no problem.

**Comment by alexsmithfanning** [comment]
I'm facing the same issue.

**Comment by Chromelon** [comment]
Facing the same issue. Submitted a post talking about this on the subreddit.

**Comment by ccrama** [comment]
Should not be an issue with v5.6.5
