### ISSUE TITLE
Reply to comment crash

### ISSUE THREAD

**Issue by Jamessuperfun** [ccrama/Slide#2498]
Slide version: 5.6.2
Android version: 7.0 
Device: LG V20 

When attempting to select a specific comment in order to reply, Slide crashes. The comment is in this thread, written by "greenmachine9", in reply to Jamessuperfun.

**Comment by bb010g** [comment]
What thread?

**Comment by ccrama** [comment]
Please give more information on how to reproduce this crash, closing for now
