### ISSUE TITLE
Gyfcat.com gifs lag

### ISSUE THREAD

**Issue by dgyk** [ccrama/Slide#2500]
Slide version: 5.6.3
Android version: 7.0
Gifs and especially gyfcat gifs are lagging

**Comment by dgyk** [comment]
https://gfycat.com/DiscreteConfusedHawk - this gif is super laggy 

https://i.imgur.com/hdNcGYB.gifv - this gif is normal

**Comment by ccrama** [comment]
One is loaded from Imgur, while the Gfycat one is downloaded from Gfycat. If there is an issue encoding on their end, that may cause what you are seeing

**Comment by ccrama** [comment]
That is different @The0x539 , the latest alpha doesn't show the bottom bar anymore

**Comment by The0x539** [comment]
It seems like the g.redditmedia.com video is what's low-quality when this is an issue, since if memory serves it's like that in a browser.

**Comment by ccrama** [comment]
Yes, it’s the gif itself and not how Slide handles it

**Comment by ccrama** [comment]
Might change with the addition of ExoPlayer (now it's all done client-side instead of device-side), feel free to re-open if this continues to occur
