### ISSUE TITLE
App crashes after you type anything into the "Go to subreddit" field when it's hidden

### ISSUE THREAD

**Issue by guihkx** [ccrama/Slide#2501]
Slide version: 5.6.2
Android version: 6.0

Video: https://youtu.be/hgmofGkGARg

Steps to reproduce:

1. Set focus on the "Go to subreddit" field
2. Scroll down until it's hidden on your screen
3. Type anything
4. Slide will crash

**Comment by GUiHKX** [comment]
I guess this is fixed in 5.7.1, now after you scroll down the keyboard hides itself so you can't type anymore.

**Comment by bb010g** [comment]
If it's fixed, you should close the issue. However, I could see this still happening with external keyboards (haven't tested yet).

**Comment by guihkx** [comment]
The focus is now removed from the "Go to subreddit" typing field once it disappears from the phone screen. I've tested with a physical keyboard too. So I'm closing this.
