### ISSUE TITLE
Mod privileges not taken into account, causing crashes

### ISSUE THREAD

**Issue by KeronCyst** [ccrama/Slide#2503]
Slide version: 5.6.5
Android version: 7.1.2

I only have flair permissions for a given subreddit, but Slide still gives me all post-management mod options. So when I try to approve something (for example) in that sub, Slide crashes. It's not checking for which exact permissions I have available as a mod.

**Comment by ccrama** [comment]
Unfortunately, that is not possible to see from the app side. All I can do is catch the exception, what specifically causes a crash?

**Comment by KeronCyst** [comment]
I have flair-only moderator permissions on /r/efreebies. I forgot about this and tried pressing the armored checkmark icon (for approving content) on content in that sub, and after selecting "Approve," the app instantly crashed. This is replicable.

**Comment by ccrama** [comment]
Honestly don't know if there is an API endpoint for me to be able to check that, might just have to add catch statements to all of the actions in case it does crash

**Comment by Tensounder54** [comment]
@ccrama We could implement a system whereby each time the user visits a sub for the first time, that Slide knows that the user moderates, it does the following. As part of the loading process, Slide uses an `HTML` parser to check the `about/moderators/` page of that sub to see what moderator permissions the user has and set the items on the moderator shield context menu accordingly.

**Comment by Tensounder54** [comment]
This issue is resolved in a later version of Slide and so I'm closing it.
