### ISSUE TITLE
Opening gif links sometimes opens a different gif

### ISSUE THREAD

**Issue by cmoarbutts** [ccrama/Slide#2505]
Slide version: v5.6.2
Android version: 7.1.2

For example, this post: OP posted a gif of some simulation of metal falling but when I click on it, it's a woman grabbing her breast.

https://reddit.com/r/oddlysatisfying/comments/6rnm9z/this_animation/

I don't know if it's a coincidence but every time this has happened, it opens a NSFW gif instead. Not that I mind it, but it's made for some uncomfortable situations at work.

**Comment by ccrama** [comment]
That is a Gfycat issue, and unfortunately nothing can be done on our end about that. The latest alpha gets rid of Gfycat in favor of Reddit gif conversion
