### ISSUE TITLE
Message/comment notification will not clear

### ISSUE THREAD

**Issue by cartszn** [ccrama/Slide#2508]
Slide version:5.6.3
Android version:7.0
If you get a message or a responding comment notification, you can't clear it from the notification tray. If you tap "mark as read", another notification pops up without the msg content but also won't clear from reddit if you tap mark as read. The only way to prevent getting these reoccurring msg/comment notifications is to open the app and view the actual message or comment. It would be great to use the notification button as it was intended.

**Comment by ccrama** [comment]
That is the intended behavior, only tapping on the inbox message to mark it as read will stop it from re-appearing, or tapping the mark all as read button

**Comment by cartszn** [comment]
That would be great if it didn't appear again hours later

**Comment by ccrama** [comment]
Sorry, that's the only way I can check for notifications. The next update will allow you to only check when the official app checks
