### ISSUE TITLE
Keyboard autocorrect pane doesn't appear when typing in PMs to a whole subreddit's mods

### ISSUE THREAD

**Issue by KeronCyst** [ccrama/Slide#2511]
Slide version: 5.6.5
Android version: 7.1.2

It seems that whenever I'm PMing an entire subreddit's mods, the autocorrect pane above my Android keyboard didn't seem to appear. I'm not sure if it even capitalized the first letter of each new sentence.

**Comment by ccrama** [comment]
Seems to be working now on my Pixel on Oreo, so let me know if the next alpha fixes this issue for you. If it doesn't, feel free to re-open this issue!
