### ISSUE TITLE
NSFW thumbnail settings be ignored

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#2512]
Slide version: 5.6.3
Android version: Android N

In reddit I have the "Hide images for NSFW/18+ content (Don't show thumbnails or media previews for anything labeled NSFW)" setting enabled, but Slide is still showing NSFW thumbnails. Also when going to the comments, the big image is being auto loaded. On older versions of slide, it seemed like this setting was being respected. It wouldn't show the image and I'd have to actually tap it to load it.

**Comment by ccrama** [comment]
Are you on the alpha? If so, make sure you're fully up to date

**Comment by kufii** [comment]
I am on alpha but I don't see any updates in the play store

**Comment by ccrama** [comment]
This was fixed in the latest alpha released last week!
