### ISSUE TITLE
Loading failed, 401

### ISSUE THREAD

**Issue by CelloDE** [ccrama/Slide#2514]
Slide version: 5.6.2
Android version: 7.1.1

Every few hours I get the error and have to delete all the data to make it work again.
Only happens on my tablet (HTC Nexus 9)

**Comment by CheeseFrog** [comment]
+1 for this. I'm forced to use the mobile site due to this.
This is a massive issue on my S4 and other devices running Lineage OS.
Other times content also fails to load, needing a restart to get working again.
5.6.5a4, LOS 7.1.2

**Comment by Tensounder54** [comment]
This issue is resolved in a later version of Slide and needs to be closed.
