### ISSUE TITLE
Uploaded Imgur file without title should only add link to the post

### ISSUE THREAD

**Issue by MustardCat** [ccrama/Slide#2524]
Slide version: 5.6.5.1-alpha 4
Android version: 8.0.0

When uploading an Imgur file in a post, the user is given the option to enter a title (to use as text for the embedded link).  If the title field is empty, only the link should be added to the body of the post.

Currently, what happens is the skeleton for a "prettified" link is added anyways.  If the user leaves the skeleton alone, the link won't be visible in the post, so the user has to manually delete the skeleton

Ex - `[](http://imgur.com/xxyyzz)`

Expected behavior - `http://imgur.com/xxyyzz`

EDIT: If I didn't format the example as code, Github wouldn't actually display the link either :)

**Comment by ccrama** [comment]
Good idea! Will do that before the final 5.6.5 alpha

**Comment by ccrama** [comment]
Done!
