### ISSUE TITLE
Titles no longer showing up on light theme in latest beta

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#2532]
On the latest beta version, the titles seem to be the same color as the background for the light theme and thus aren't showing up

**Comment by kufii** [comment]
Actually noticing other theming issues with light theme too (flairs hard to read, fob text color incorrect), but this is the major one

**Comment by dgyk** [comment]
Same here. Had to change base theme color to something else (Pixel color) for now

**Comment by ccrama** [comment]
Should be fixed now!
