### ISSUE TITLE
Tables not being displayed

### ISSUE THREAD

**Issue by MustardCat** [ccrama/Slide#2533]
Slide version: v5.6.5-alpha5
Android version: 8.0.0

In the latest alpha, tables aren't not being displayed anymore.  Not sure if it's related to #2532 or not as I tried with both AMOLED and white themes.

Example post: https://www.reddit.com/r/slideforreddit/comments/71fv4t/v565alpha5_released/dnaq5xp/

**Comment by MustardCat** [comment]
Actually seems to be more related to [this issue](https://www.reddit.com/r/slideforreddit/comments/71fv4t/v565alpha5_released/dnapyyv/) that was referenced in the release post

**Comment by ccrama** [comment]
Should be fixed now!
