### ISSUE TITLE
Blocking 

### ISSUE THREAD

**Issue by EboniLM** [ccrama/Slide#2534]
Slide version: 5.6.5.1
Android version: 7.0

Any plans to implement in-app blocking? Ha ing to do it through the desktop website is tedious.

**Comment by l3d00m** [comment]
It's in the Settings and it's called "Filters", if by blocking you mean to filter based on keywords, title or subreddit.

**Comment by Nxt3** [comment]
I think he means blocking other users?

**Comment by EboniLM** [comment]
Yes, i do mean blocking other users.

**Comment by ccrama** [comment]
Added by @YusefOuda !
