### ISSUE TITLE
Opening a link within a comment crashes Slide

### ISSUE THREAD

**Issue by dgyk** [ccrama/Slide#2539]
Slide version: 5.6.5-alpha5
Android version: 7.1

Link to comment, then click wallpaper link: https://reddit.com/r/androidthemes/comments/71amkm/theme_tranquility/dn99rgc?context=3

**Comment by incIined** [comment]
Same issue here: https://github.com/ccrama/Slide/issues/2540

**Comment by freundTech** [comment]
It seems like in the newest alpha all links opening in the internal browser cause a crash.
For some reason chromium itself and therefor also the android webview is crashing. Here is a crash log

[webview_log.txt](https://github.com/ccrama/Slide/files/1323991/webview_log.txt)

**Comment by freundTech** [comment]
The problem has been introduced by commit 234d260b47aa9236cf5d0fbd9a96eeb03b5d6e2d. Note that neither that commit nor the previous one will build. You have to cherry-pick 2d81b9f0c43ed0cee79fd3d92d2e148ba2e7b9eb afterwards.

There are multiple changed in that commit that could cause the crash. I'm not yet sure what's responsible for it.

**Comment by ccrama** [comment]
Has been fixed, thanks for the reports!
