### ISSUE TITLE
Weird crash when opening specific link

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide#2540]
Slide version: 5.6.5-Alpha5
Android version: 7.1.1 (OxygenOS 4.5.10)

App goes all the way back to frontpage before exiting when attempting to open this link:

https://reddit.com/r/Android/comments/71jd68/google_to_make_its_dialer_app_more_useful_with/

Seems to happen when trying to open a link to XDA. 

Video of it happening: https://streamable.com/g4lz6

**Comment by incIined** [comment]
Happens on this link too: 

https://reddit.com/r/jailbreak/comments/71rcyq/giveaway_20_copies_of_photomanager/

(The Cydia link)

**Comment by ccrama** [comment]
It was actually all links, has been fixed
