### ISSUE TITLE
Comments view and subreddit view positioned incorrectly on pixel in landscape

### ISSUE THREAD

**Issue by ghost** [ccrama/Slide#2543]
Slide version: 5.6.5-alpha5
Android version: 8.0.0

When in landscape and navigating to a subreddit that I am not subscribed to, comments view, or video, the screen is not positioned correctly. 

The issue is explained perfectly in [this]( https://www.reddit.com/r/slideforreddit/comments/6bn6m4/bug_comments_window_is_positioned_wrong_on_pixel/) reddit post. There is a video in the post that shows what is happening.

**Comment by Tensounder54** [comment]
This doesn't seem to be an issue in 5.9-alpha2 but I'm using a Smasung Galaxy A300 to test which has a physical navbar. Could someone with a non-physical navbar please verify that this is no longer an issue so that it can be closed or fixed.

**Comment by Tensounder54** [comment]
This issue is resolved in a later version of Slide and as such it is being closed.
