### ISSUE TITLE
Black text with black background on Manage subreddits

### ISSUE THREAD

**Issue by isaactsg** [ccrama/Slide#2545]
Slide version: 5.6.5alpha5
Android version: 7.1.2
When using the AMOLED base theme I am unable to read the names on subreddits in the manage subreddits list, as the text is also black.
A workaround is to change the base theme to something other than black when managing subreddits, then change back when done.

**Comment by ccrama** [comment]
Make sure you're fully up to date, alpha 5 number 2 does not have this issue
