### ISSUE TITLE
Loading fails 403

### ISSUE THREAD

**Issue by isaactsg** [ccrama/Slide#2546]
Slide version: 5.6.5alpha5
Android version: 7.1.2
This issue has been happening at least since July.
Sometimes when I open the app it fails to load my frontpage (and all other subreddits), giving me an error 403.
The workaround I have found is to switch accounts, then switch back, or log out then log back in again.

**Comment by The0x539** [comment]
Dismissing the app from recents also makes it go away.

**Comment by ccrama** [comment]
I forced it to re-auth if it runs into that issue
