### ISSUE TITLE
'Open externally' causing crashes

### ISSUE THREAD

**Issue by TravisBickle76** [ccrama/Slide#2549]
Multiple crashes when using the 'open externally'  feature. Continues after app and device restart. 

Slide version: Slide v5.6.5-alpha5
Android version: 6.0.1

**Comment by TravisBickle76** [comment]
Updated to v5.6.5-alpha6

Trying open externally again.

**Comment by ccrama** [comment]
Not crashing on any of the alphas for me

**Comment by TravisBickle76** [comment]
Thanks for the reply. 'open externally'  had actually became unusable on alpha5 it was happening that often.
I've tried a few links on alpha6 with no problems. I'll keep trying and get back to you. Maybe a browser issue. 

Thanks again.
