### ISSUE TITLE
2FA not supported by crash reporter

### ISSUE THREAD

**Issue by GreyAsteroid** [ccrama/Slide#255]
Trying to log in to the crash reporter on an account that uses 2FA causes an error to be displayed.

**Comment by ccrama** [comment]
What is 2FA?

**Comment by GreyAsteroid** [comment]
2 Factor Authentication.

**Comment by l3d00m** [comment]
I have the problem too. I'm always using my self compiled build and they don't have the guest user and my account doesn't work because 2 factor. Means no longer crash reports from me.

**Comment by l3d00m** [comment]
https://github.com/PaoloRotolo/GittyReporter/issues/14  
I've reported it to the library that is used for crash reporter. I think this can be closed now because it's nothing ccramacan fix.

**Comment by ccrama** [comment]
Yep. Hope he updates it! Thank you for the report
