### ISSUE TITLE
NSFW image shown in comments even if the preview was hidden 

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2552]
For example, I'll see a post on /r/all that has the thumbnail preview hidden because it's NSFW. When you go to the comments view for that post, the lead image is not hidden anymore. 

If the preview is hidden, the lead image in the comments should be hidden as well.

**Comment by ccrama** [comment]
Is it possible you have nsfw images enabled, but set to hide on /r/all and you clicked on an /r/all post and saw the images? If that's the case, that is the intended behavior

**Comment by Nxt3** [comment]
that seems weird but okay :p

**Comment by ccrama** [comment]
There isn't a way for me to tell what subreddit you came out of, if you have NSFW images disabled everywhere it will hide, but if you open it and have told Slide to show NSFW images, that is the expected behavior imo

**Comment by Nxt3** [comment]
Ah that's a good point. It doesn't bother me honestly. I was thinking if I accidentally tapped on a NSFW post the image would be displayed. You're right though.
