### ISSUE TITLE
Installation crashes os, sends it into an infinite boot loop.

### ISSUE THREAD

**Issue by ian-kelling** [ccrama/Slide#2561]
Slide version: 5.6.5-alpha5.1
Android version: Replicant 6.0 0002 on galaxy s3.

I've reproduced it multiple times. It happens basically as the installation finishes.

**Comment by ian-kelling** [comment]
Also, slide version is from fdroid.

**Comment by bb010g** [comment]
This sounds more like a Replicant issue. Have you also reported it there?

**Comment by ccrama** [comment]
That is an issue with your OS, same as #2555
