### ISSUE TITLE
Comment menu with no children

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2566]
https://www.reddit.com/r/slideforreddit/comments/76m6c6/v57_released_push_notifications_android_o/dofwci1/

Only do this if you have `Fully collapse comments` disabled. https://github.com/ccrama/Slide/blob/a698550822616764b389111c8422b1418a39ea79/app/src/main/java/me/ccrama/redditslide/Adapters/CommentAdapter.java#L1805

**Comment by ccrama** [comment]
Also we could make a setting option for it!

**Comment by Nxt3** [comment]
You sure? I don't mind doing that too, but I feel like it's unnecessary. If the comments are fully collapsing, either long-pressing or tapping a comment w/ no child should open the menu. Another setting seems unnecessary.

**Comment by ccrama** [comment]
Honestly I'm not a big fan of it and want to disable it on my device. If you want I can implement the setting, just let me know!

**Comment by Nxt3** [comment]
Try it with the PR I made first. It's fine now.
