### ISSUE TITLE
V.reddit.com media has no sound

### ISSUE THREAD

**Issue by jordanclock** [ccrama/Slide#2567]
Slide version: 5.6.5 alpha5.1
Android version: Pixel 8.0

All v.reddit.com media is mute. All other sounds in the app work as expected. Sound for v.reddit.com has not work even in preview builds.

**Comment by ccrama** [comment]
That will be really hard to fix, as sound is a separate file stream that must somehow be merged with the video file. It's meant to stream in a web view and the Android media view doesn't really support DASH streaming

**Comment by jordanclock** [comment]
Then perhaps exclude v.reddit.com from gif view? Currently all the v.reddit.com links I see are labelled as gifs, which explains why the videos aren't opening in a browser for me.

**Comment by jordanclock** [comment]
Also, I tried adding v.reddit.com to the custom domains list and they are still being handled by the gif viewer.

**Comment by ccrama** [comment]
The only other alternative is opening it on the web browser only which I feel is a worse compromise

**Comment by jordanclock** [comment]
Could you possibly make the custom domains list supercede the internal viewer settings? At least then users could have the links open externally if we are okay with that trade off.

**Comment by ccrama** [comment]
It should (works for me)

**Comment by jordanclock** [comment]
I have added v.redd.it (mistakenly had v.reddit.com, derp) to the custom domains list. Unfortunately while the links open in Chrome, the tab goes away immediately. In Chrome Dev, Slide locks up but doesn't bring up a force close prompt.

**Comment by ccrama** [comment]
Fixed in next alpha!
