### ISSUE TITLE
Slide should hide Reddit app's notification when piggybacking off of push notification

### ISSUE THREAD

**Issue by MustardCat** [ccrama/Slide#2570]
Version: 5.7

When Slide is piggybacking off of the official reddit app's push notifications, Slide should hide/clear the reddit app's notification so only one notification is displayed

Ref: https://www.reddit.com/r/slideforreddit/comments/76m6c6/v57_released_push_notifications_android_o/dogyt1a/

**Comment by ccrama** [comment]
So actually this is not possible using the accessibility API, and it would have to be re-written to do this. While looking at the official app, it's also actually possible to get push notifications for subreddits, which is another feature Slide has to poll for in the background. DK if it would be worth merging the features

**Comment by Nxt3** [comment]
You'd need to use the Notification Access API. I don't use this feature at all, but this is something worth re-writing since Accessibility services run the risk of slowing down the device.

**Comment by ccrama** [comment]
Yeah I took me a few lines of code to convert between the two, and just decided to make the feature API 18 and above. I doubt it would lead to slowdowns using either method as I only use one of the possible permissions and get only one type of event returned to the services, but the NotificationListenerService is a bit cleaner and does only what I want it to do (and allows me to remove the Reddit notifs).

**Comment by ccrama** [comment]
Done!
