### ISSUE TITLE
Image Viewer Swipe Away Causes Status Bar Color Delay

### ISSUE THREAD

**Issue by reed501** [ccrama/Slide#2571]
Slide version: 5.7.1
Android version: 8.0
When viewing an image, the image slides in from the right and covers the status bar along with it replacing it to black. However, when swiping away the image slides to the right as expected but the status bar waits until the image is gone before sliding the color back.

**Comment by ccrama** [comment]
That actually happens everywhere in the app. Unfortunately there is not a way to fix it because the issue runs deep into how Slide activities are handled
