### ISSUE TITLE
Android Notifications - 2x notifications (alert sound and taps to mark as read)

### ISSUE THREAD

**Issue by MustardCat** [ccrama/Slide#2572]
Slide version: 5.7.1
Android version: 8.0

First saw this issue posted couple months ago: https://www.reddit.com/r/slideforreddit/comments/6rvn5o/notifications_always_reappearing_after_being/

When I get a notification, my notification alert sound occurs twice in quick succession.  I think it's related to below.

When marking the notification as read from the notification pull down, the first "mark as read" click removes the "child" notification that contains the actual reply text.  The "main" Slide notification (which all child notifications bundle into) still appears (the one that says "You have 1 unread message" without the actual reply's text).  To remove that notification, I have to click "mark as read" again.

It seems like the alert sound happens once for the "main" notification and then again for the "child" notification.

Extra Info: Since I'm using piggyback notifications, I do have the official app installed.  Within my notification settings, the official reddit app's notifications are set to *not* allow sound

**Comment by ccrama** [comment]
Does this only occur with sound/vibrate enabled?

**Comment by MustardCat** [comment]
Are you asking specifically about the double notification sound or having to select "mark as read" twice or both?

Using the new Oreo notifications, all my notifications for Reddit mail/Reddit modmail/Submission post checking are:

Importance: Urgent
Sound: Default
Vibrate: Off

**Comment by ccrama** [comment]
Is this still an issue with the latest alphas?

**Comment by MustardCat** [comment]
I haven't been around my phone when getting a notification lately but the issue of two notifications needing to be marked as read is still there

**Comment by MustardCat** [comment]
Finally got around to making a video of the issue where you can see the "double" notifications: https://streamable.com/vwhwg

I think this only happens on 8.0+ as my tablet (running M) doesn't have the double notification (and it only displays the "second" notification without the reply text in my notifications)

**Comment by ccrama** [comment]
Ah it is because of the notification "group" having its own tone in M and above. Will fix when I'm back in the country!

**Comment by ccrama** [comment]
Was all because of notification channels. Had to now make 2 channels, one being the quiet one and one being sound enabled for the setting

**Comment by ccrama** [comment]
Were some other issues but should now be fixed
