### ISSUE TITLE
Alarms set by AlarmManager.set() are treated as inexact

### ISSUE THREAD

**Issue by frankFic** [ccrama/Slide#2576]
Another thing I would like to mention, from API 19, the alarms set by`AlarmManager.set` will not be sent at the exact time specified but may be delayed. (Also refer to the [doc](https://developer.android.com/reference/android/app/AlarmManager.html#set(int,%20long,%20android.app.PendingIntent))).
I found it is used in [NotificationJobScheduler](https://github.com/ccrama/Slide/blob/98f5df0eb945fac7d5b8d2e7102cfacfaa754b4c/app/src/main/java/me/ccrama/redditslide/Notifications/NotificationJobScheduler.java#L32) and [NotificationPiggyback](https://github.com/ccrama/Slide/blob/490d0f26629d5c0c1ba9352e291d97a9a61eae5f/app/src/main/java/me/ccrama/redditslide/Notifications/NotificationPiggyback.java). I think the delay may be more obvious in NotificationPiggyback as it scheduled a very timely alarm. But I am not sure whether an exact time is desired. To achieve exact-time alarm, the alternative API is setExact for your reference.

Thanks and sorry for bothering. :)

**Comment by ccrama** [comment]
This is on purpose as it was causing extreme load on Reddit servers periodically as Android automatically batched notifications on many devices together at specific times. A strange issue to have but I risked losing API access unless I changed it
