### ISSUE TITLE
V.redd.it links crash App

### ISSUE THREAD

**Issue by orphanartist** [ccrama/Slide#2578]
Slide version: 5.7.1
Android version: 6.0.1

Previously reported in comment to u/ccrama. My user name: realandofficial 

Latest gif link is this post https://www.reddit.com/r/nonononoyes/comments/78zasi/riding_on_a_wall/

Note: all v.redd.it gifs have same effect.

**Comment by ccrama** [comment]
Have you reported this crash through the Play Store report? I need a stacktrace to be able to diagnose the issue

**Comment by orphanartist** [comment]
Apologies for my ignorance, I just did it via the Slide report button. How do I do a Play Store report? Just feedback on the Play Store?

**Comment by ccrama** [comment]
Is this still occuring? Play Report button showed me some crashes which I fixed a while back
