### ISSUE TITLE
"Hide NSFW previews in collections" not working

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2583]
I have a multi-reddit called "/m/humor" that still shows NSFW previews. I have the following settings enabled:

![Settings](https://i.imgur.com/11aMa7Q.png)

**Comment by ccrama** [comment]
Are you viewing this on its own or in the multireddit section of the app? If so that is the expected behavior

**Comment by Nxt3** [comment]
I imported the multi-reddit into the list of subs.

**Comment by Nxt3** [comment]
![Like this](https://i.imgur.com/PUAfDme.jpg)

**Comment by Nxt3** [comment]
Same with this person: https://reddit.com/r/slideforreddit/comments/7crdor/thumbnail_bug/

**Comment by ccrama** [comment]
Fixed!

**Comment by Nxt3** [comment]
Thanks man!
