### ISSUE TITLE
Can't play GIFs

### ISSUE THREAD

**Issue by silverAndroid** [ccrama/Slide#2585]
Slide version: 5.7.1
Android version: 6.0.1

I randomly opened Slide on my old Note 2 and it can't play GIFs, as in it shows a black screen where the GIF should be playing and when I try to fast forward, it stays in the same state. I know it's device specific because it works fine on my V20.

**Comment by ccrama** [comment]
Is the Note 2 on android 6.0?

**Comment by silverAndroid** [comment]
Note 2 on 6.0, V20 on 7.0

**Comment by ccrama** [comment]
Do you know if there are specific website's gifs that don't load? It might be an encoding issue, which in that case would not be possible to fix

**Comment by silverAndroid** [comment]
I think it might be a decoding issue on my device/ROM because nothing loads on r/gifs
