### ISSUE TITLE
After one link won't load, none will until restarting the app

### ISSUE THREAD

**Issue by kace91** [ccrama/Slide#2589]
Slide version: v5.7.1
Android version: 7.0 on a galaxy s8.

I'm having this frequent issue where, after a few minutes using the app, a link randomly won't load. This is consistent with usual behaviour (as reddit is sometimes overloaded) but what's changed is that from that point on, no link will load, including both links to pages outside reddit and comment sections, as well as switching subreddits. It just displays a blank page with the loading bar.

It's not related to my connection nor to reddit's state, since loading reddit on the browser will work fine and the problem is immediately resolved by closing Slide  in the multitasking menu and then opening it again.

I can't say for sure when the problem started, but it was somewhere in the last 2 weeks.

**Comment by ccrama** [comment]
When you say link, do you mean a website or some other type of content?

**Comment by kace91** [comment]
@ccrama  Comments, subreddits, anything that's opened inside the app. [Here's an example happening in a self post from askreddit.](https://imgur.com/P7wcrtX)

It just stays loading forever.

**Comment by Tensounder54** [comment]
This issue is resolved in a later version of Slide and needs to be closed.
