### ISSUE TITLE
Incorrect email linking 

### ISSUE THREAD

**Issue by GeorgeWL** [ccrama/Slide#2593]
Seems that it incorrectly links any emails which contain certain characters. 

Should be a quick fix of sanitising the strings so that it doesn't cut part of an email off.

The first instance I saw of it was a comment with `Mike.O'Reilly@fcc.gov` in which it only linked the `Reilly@fcc.gov` part of the email. 

Here's a link to the comment: https://reddit.com/r/mspaintbattles/comments/7er15g/looking_for_mspaintbattles_unless_we_fight_for/dq7fops?context=3

I've since tested it with other similar strings,  and it cuts short any email with characters valid for email which would usually have to be transformed into html-entities if used in URLs.

**Comment by ccrama** [comment]
Unfortunately links and emails are rendered as links through Reddit's servers, and nothing is done locally in Slide. That is something that can be fixed by Reddit in the future
