### ISSUE TITLE
Crashes when trying to quote

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [ccrama/Slide#2596]
Slide version: 5.7.1 (fdroid)
Android version: 7.1.2 (lineage os)

Hi, I couldn't find any similar issue on here so I post my own here : 

situation : replying to a comment, if I press the "quote button", I can select what part to quote, press "select" and then it crashes immediatly. It happens on every sub, 95% of the time. For some reason it worked sometimes without me figuring out why.

I don't know what other information I could bring.

Great app so far anyway, fantastic work :)

**Comment by Tensounder54** [comment]
This issue is resolved in a later version of Slide and needs to be closed.
