### ISSUE TITLE
Frontpage displays /r/all. Force restart, cache clean didn't fix it. 

### ISSUE THREAD

**Issue by sztkp** [ccrama/Slide#2598]
Slide version: v5.7.2-alpha1
Android version: 8.0.0

**Comment by BrainBlasted** [comment]
Could you try switching accounts or logging out then in again? I've seen something  like this and haven't had the chance to report it. Also, could you provide how the bug occurred for you?

**Comment by SorsaSampo** [comment]
I have the same problem with second account I added. The first one shows frontpage properly.

Removing the second account and adding it again did not help.

**Comment by Tensounder54** [comment]
This issue is resolved in a later version of Slide and needs to be closed.
