### ISSUE TITLE
Turn gear icon in appbar into Settings button in the top bit of drawer, which opens a dedicated Settings page.

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#26]
The current model isn't sustainable. The settings page could contain:

* Theme: Contains light/dark/black, as well as global color/accent.

* Global post options: Contains the "Edit CardView" dialog, to be overhauled in 4.1.

* Local post options: Contains a more batch-y and powerful way of editing per-subreddit card/color stuff.

* Multi-column: Contains an overhauled version of the "Grid layout" dialog.

* Donate: :moneybag::moneybag::moneybag:

* Other things, like if shadowbox is gonna be getting any customization.

**Comment by Alexendoo** [comment]
:+1: seems required to me, in addition will provide an area for an about page: version number, links to things relevent to slide

**Comment by The0x539** [comment]
Which in turn will allow for dev options if necessary.

**Comment by ccrama** [comment]
Halfway done with 7f3bae7e1f26aa7f2d17754a9d864bdf8266860f. Now it's a button in the sidebar
