### ISSUE TITLE
Gfycat api acting up, consider using V1 api

### ISSUE THREAD

**Issue by ioangogo** [ccrama/Slide#2600]
It looks like gfycat have stopped using https://gfycat.com/cajax/get/ as it now just leads to a not found, for example https://gfycat.com/cajax/get/EnviousUnrulyBullmastiff

[There is a new V1 api](https://developers.gfycat.com/api/), but it kind of behaves like twitch where you need a client ID for it to work

**Comment by ioangogo** [comment]
Nvm, it seems to be the API acting up, but I feel like the cajax api is a bit of a cliff edge in support as it is not the official documented api, I will leave the api open for this reason

**Comment by ccrama** [comment]
I started working on implementing the new Gfycat API but they were requesting analytics tracking and the new API requires authorization (more API calls to worry about), so I decided to drop support for the Gfycat api except for cajax to get gfycat links. I believe the API is working again but might rely on Reddit's conversion if Gfycat does axe cajax
