### ISSUE TITLE
Is there a way to view front page of local subs without an account?

### ISSUE THREAD

**Issue by laserstrike** [ccrama/Slide#2603]
Slide version: 5.7.2alpha1
Android version: 7.1.2

I just like to lurk, so I don't keep an account. But my front page view is the regular front page view and is not exclusive to the list of subs I've added.

If this can't be done, I hope it becomes a feature or option in settings. Thank you.

**Comment by ccrama** [comment]
Unfortunately that is not possible, as Reddit's frontpage is handled server-side and not on Slide. There is also a limit to the size of multireddits, so adding all of the subs together would not work either. Only option is to put the ones you really want to see in a multireddit and import that to your subs list
