### ISSUE TITLE
Setting a new default browser?

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide#2607]
Don't know if this would be worth implementing, but you could set your default Slide browser separate from the open links externally and the default system browser.

**Comment by Acters** [comment]
Would love to have a finer tuned controls for link handling.

**Comment by PiwwowPants** [comment]
Possible with this PR https://github.com/ccrama/Slide/pull/2740

Any browser on device can be selected now indepdendent of the link handling type.
