### ISSUE TITLE
Gif seek bar doesn't show in split-screen

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2612]
When Slide is split with a other app, and you view a gif or video that would normally show the seekbar--it is hidden until you exit split screen.

**Comment by ccrama** [comment]
Huh wonder if it has to do with the anchor view somehow?

**Comment by Nxt3** [comment]
I think it makes sense to hide it if Slide is the smallest it can be on the screen, but if Slide is the largest it doesn't show when there is clearly enough space. It's weird.

**Comment by ccrama** [comment]
This behavior will change with the new ExoPlayer addition, needs testing in next alpha

**Comment by Nxt3** [comment]
Yep it seems to be fixed since the controls are overlaid on the gif.
