### ISSUE TITLE
Freezing when there are several download notifications

### ISSUE THREAD

**Issue by WilhelmWeiIndie** [ccrama/Slide#2613]
Slide version: 5.7.2
Android version: 6.0.1
Device: Sony Xperia Z3 Dual D6633, Qualcomm Snapdragon 801, 3GB RAM

Whenever I download an image or video, the app shows a notification that says something like 'Photo Saved' with a small thumbnail to the left. 

But whenever I have downloaded several images and videos, with 3 or more notifications in the notification drawer, the phone will enter into a highly unresponsive condition: It will freeze whenever I pull the notification drawer and when I am at the lockscreen (pattern). 

I just avoid this by dismissing every notification but it's highly displeasing because I usually have to restart my device whenever this happens.

**Comment by ccrama** [comment]
Should be fixed now, images are scaled to 10% and should not waste the RAM. If this occurs in v5.8 feel free to re-open the issue
