### ISSUE TITLE
External website link gets modified when being opened

### ISSUE THREAD

**Issue by magnus-gross** [ccrama/Slide#2615]
When I visit [this reddit post](https://www.reddit.com/r/linux/comments/7nqhe8/initial_benchmarks_of_the_performance_impact/) with Slide, and try to open the link with the external browser (Chrome) or with inline view chrome, the link gets changed from `https://www.phoronix.com/scan.php?page=article&item=linux-415-x86pti&num=1` (correct) to `https://www.phoronix.com/scan.php?page=article&amp;item=linux-415-x86pti&amp;num=1` (not available). I noticed that this is like this with every phoronix link.

The expected behaviour is to not modify the URL so that I can view the website with the browser.

Slide version: 5.7.2
Android version: 6.0.1

**Comment by ccrama** [comment]
Slide actually does not modify the URL, it is just being HTML escaped through Reddit's JSON. Where are you tapping to open the link?

**Comment by magnus-gross** [comment]
Woah, that was a fast response :O

I tap on the thumbnail. I noticed that if I explicitly press on "Open Externally", it will open the correct URL. It will also share the correct URL, if I click on "Share Link"

**Comment by ccrama** [comment]
Haha we have a bot on the IRC channel that pings with new issues. That shouldn't be happening as Slide forces an un-escape, but I'll look into it!

**Comment by PiwwowPants** [comment]
Pressing "Open Externally" runs through a different code path than clicking the thumbnail and the app open externally based on default settings.
The former passes through `openExternally(String url, Context context, Boolean encoded)` which does not perform a `StringEscapeUtils.unescapeHtml4` on the url.
The latter passes through `defaultShare(String url, Context c)` which does.

You'd potentially want to consolidate this logic to avoid opening externally in two places.
