### ISSUE TITLE
Opening "Amp" reddit links in Slide

### ISSUE THREAD

**Issue by matty1086** [ccrama/Slide#2618]
Slide version: 5.8 alpha 1.5
Android version: 8.1.0 January 5th 2018 Security Patch Level

If you try to open Google's "amp" from search results or someone sending you one via chat, Slide is unable to open them in the application.

Example Google search (any of these with the little lightning bolt next to them):
https://imgur.com/a/BYESb

My only options for opening these are browsers or Sync for reddit:
https://imgur.com/a/mPbRD

It would be great if Slide was able to support these types or urls.

Thanks!

**Comment by ccrama** [comment]
Should this activate when you click on an amp.reddit.com link, or a reddit link that loads with AMP? I don't think I can handle the google link that has ?url=amp.reddit.com as Chrome loads this internally, but I could add support for amp.reddit.com links

**Comment by matty1086** [comment]
I was thinking about this some more then remembered that Android lets users see which urls an app is able to open. I looked at Syncs and compared to Slides and found they have a lot more, including amp.reddit.com, www.google.com, which is likely how the dev of Sync is able to get his app to open these urls from search results.

Looks like Sync has a longer list of reddit links than Slide does as well. 

Also has a couple of imgur links - which upon testing, loads the image viewer in Sync to view the image/album. Could also be useful to load Slides viewer for these as well?

Sync url settings:
https://imgur.com/a/DLtGz

Slide url settings:
https://imgur.com/a/0TA89

**Comment by ccrama** [comment]
I don't think it would get used very often to include all content links to open with Slide (may actually be annoying if it now asked the first time the user opens any type of link). Super easy to add amp.reddit.com support though

**Comment by ccrama** [comment]
Done for next alpha
