### ISSUE TITLE
V.redd.it links with USB-C headphones fail

### ISSUE THREAD

**Issue by jordanclock** [ccrama/Slide#2620]
Slide version: 5.8 alpha15
Android version: Pixel 2 XL 8.1

When using USB-C headphones, v.redd.it links fail to load. The media viewer will open, the thumbnail/first frame will load then after a few seconds the media viewer goes blank. Removing the headphones causes the media to play as expected.

This also only affects videos that have sound. V.redd.it videos without sound plays just fine with and without the headphones.

**Comment by Nxt3** [comment]
Just to make sure we've covered the bases--did you try it with normal headphones using an adapter? or is that what you mean?

**Comment by jordanclock** [comment]
I have not tried using the adapter, I have only used native USB-C headphones. I can try with the adapter later this evening.

**Comment by jordanclock** [comment]
I confirmed that using the USB-C-to-3.5mm adapter has the same results as native USB-C headphones.

**Comment by ccrama** [comment]
Does anyone have another pair of USB C headphones to confirm this bug?

**Comment by jordanclock** [comment]
I've found that the issue is kind of transient. Each time I reboot my device, there seems to be a chance of the issue occurring. Because of this I think this may actually be an Android bug that just happens to only show up in Slide for me.

**Comment by ccrama** [comment]
Should be fixed now, it streams as a MP4 instead
