### ISSUE TITLE
Child comment sometimes not marked purple

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2622]
![](https://i.imgur.com/pHsuMy8.png)

The seelxted comment should have been purple since it was the OP of the parent comment. If I loaded the comment permalink, it worked. 

https://reddit.com/r/TumblrInAction/comments/7pxkdu/better_take_a_xanax_every_time_i_snap/dsl1p0z?context=3

**Comment by ccrama** [comment]
Was an issue with indexes, has been fixed in my last commits
