### ISSUE TITLE
App crash when tapping before image download at the image viewer

### ISSUE THREAD

**Issue by Acters** [ccrama/Slide#2624]
Slide version: 5.8-alpha1.5
Android version: 7.0

I clicked on a GFYcat link. It takes forever to even start downloading; related but not the specific issue.
Right before it starts the download there is the phase in which the app sends a request to get the gif/file and start the downloading. 
Tapping anywhere(as far as I know I only tried inside the image viewer) **crashes** the app.
There is a possibility that an image would crash it too, but its significantly common for me to be waiting for the app to load a GFYcat.
https://photos.app.goo.gl/U6YIqZksqEetJcKs2 (I used "adb shell screenrecord [file location]" for the video)

**Comment by Tensounder54** [comment]
In terms of the download time of the 

> GFYcat link

there is not much we can do about that as that is a GFYcat thing that it pretty much out of our control. @ccrama can correct me if I'm wroung. Otherwise, I think that this issue is resolved in a later version of Slide and needs to be closed.

**Comment by Acters** [comment]
I cannot reproduce this issue and will mark it as CLOSED. If the author/collaborators would like to dig deeper in this and find that the issue is still hiding in there then please reopen. 
The Gfycat issue is between me and their servers. As of recently Gfycat has resolved my connection to them.

Thank You for the app and support!
Cheers, Acters

**Comment by Tensounder54** [comment]
NP! Glad you like it and happy to help.
