### ISSUE TITLE
LQ playback when playing Reddit videos  

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide#2629]
Slide version: 5.8_a1.5
Android version: 7.1.2, OnePlus 5 

https://reddit.com/r/StoppedWorking/comments/7sfa6j/my_crab_wants_to_say_hello_to_this_sub/

An example can be seen here. 

Thumbnail:
![https://i.imgur.com/14FlW7M.jpg](url)

When playing the video:
![https://i.imgur.com/0vvmchV.png](url)

**Comment by incIined** [comment]
Seems fixed with the new DASH rework in Alpha 2. Not sure though, need to test it more.

**Comment by ccrama** [comment]
It is fixed! Made it use the original quality
