### ISSUE TITLE
[REQUEST] option to hide already viewed posts by default

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [ccrama/Slide#2638]
( Version 5.8-alpha1.5 (293) )

Hi :)

I didn't find any way to hide by default posts that are already greyed out. I think it would be a great enhancement :)

Kind regards :)

**Comment by PiwwowPants** [comment]
Just for clarity to this request.
Would you expect 
- The post to hide automatically after returning to the posts list from the post 
or
- Hide all read posts when the subreddit is originally opened

**Comment by ccrama** [comment]
This is actually something we've looked into in the past, and it created situations where there would be no more loadable pages of content and the page would be blank, leading to bad UX. This is why we did not implement this, unfortunately
