### ISSUE TITLE
Unable to set YouTube links to open in external browser (to allow them to be opened in NewPipe)

### ISSUE THREAD

**Issue by Trademark97** [ccrama/Slide#2641]
When I try to set the youtu.be and youtube.com domains as entries under "Link handling->Force external browser", nothing seems to happen. The input works correctly, but it seems that no actual entries are either created nor do they show up as domains to be handled externally.
Steps to reproduce:
1. Go to Settings->Link handling
2. Under "Force external browser", try to create entries for youtu.be and youtube.com
Expected results:
Entries created for youtu.be and youtube.com
Actual results:
No entries apparently created, and YouTube videos will not play without the proprietary YouTube application installed.
EDIT: Screen recording of issue: https://u.teknik.io/zuJg0.mp4
Slide version: 5.8-alpha1.5
Android version: 7.1.2 (Resurrection Remix v5.8.5)
Edit: Problem solved by uninstalling Slide for Reddit Video Plugin

**Comment by bqv** [comment]
This is still a problem, no?

**Comment by Alexendoo** [comment]
It happens if you have the video plugin installed @bqv which loads videos using the youtube app library, if you don't want that you have to uninstall it
