### ISSUE TITLE
Videos get stuck at end once watched

### ISSUE THREAD

**Issue by applesandsynths** [ccrama/Slide#2642]
Slide version: 5.8-alpha 1.5
Android version: 7.1.1
Lately, videos have been getting stuck at the end once watched. If I try to watch the video again, I try to manually drag the slider to the start, yet the video refuses to play. Even if I try backing out of the video to the Frontpage and going back in, it won't play again. The only way to play it again is to close and reopen Slide or launch it externally.

**Comment by ccrama** [comment]
Should be fixed with alpha 2, feel free to re open if you still run into this issue
