### ISSUE TITLE
"Error sharing image"

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide#2645]
Slide version: 5.8-a2
Android version: 8.1 (Codename Phoenix - OnePlus 5)

This occurs whenever I try sharing an image (not a link, a direct image). Didn't occur til the latest update. 

I'll share a video of what I see later on. 

Here's a logcat: 
https://drive.google.com/file/d/1NPxksasYUiYUahOooEEAHuw4NTzlbFlr/view?usp=drivesdk

Idk if it'll be useful but here ya go.

**Comment by PiwwowPants** [comment]
I broke this. I fixed it in this PR https://github.com/ccrama/Slide/pull/2644

Not sure if it'll get accepted though since it was a pretty hefty refactor to avoid leaving any pieces broken.

**Comment by ccrama** [comment]
Thanks @PiwwowPants
