### ISSUE TITLE
Obstruction by navbar

### ISSUE THREAD

**Issue by lirannl** [ccrama/Slide#2646]
Slide version:5.8 alpha 2
Android version:8.0

On landscape, with a navbar, the content doesn't make way for the navbar always (only occasionally).

**Comment by Tensounder54** [comment]
This issue needs to be verified that this is still a issue in the latest vertion of Slide before it any further action can be taken.

**Comment by lirannl** [comment]
Yep. Still exists, only when rotated 90 degrees clockwise though. When rotated counterclockwise it works just fine.

I'm now on Android 9.0, though I doubt it matters.

**Comment by Tensounder54** [comment]
This issue is resolved in a later version of Slide and needs to be closed.
