### ISSUE TITLE
Video/Gif player problems

### ISSUE THREAD

**Issue by brentluna** [ccrama/Slide#2647]
Slide version: 5.8 alpha 2
Android version: 8.1

https://www.reddit.com/r/aww/comments/7wdykd/gilbert_is_showing_off_his_skills_in_his_favorite/?ref=share&ref_source=link

- It labels it as a GIF, yet it has audio. 
- When opened, The player has no audio toggle/mute button. 
- When opened it doesn't populate the "length of video" field towards the right of the progress bar, so the progress bar slider is always at the farthest right position, leaving you unsure of how long the video is.

**Comment by Nxt3** [comment]
Yeah, I think v.reddit links should be labeled "v.reddit" so the user can expect sound. I've been in a few scenarios where I go to watch a gif, but then it was a loud video.

**Comment by Nxt3** [comment]
I'm actually going to close this and make it separate issues.
