### ISSUE TITLE
Opened videos should have a toggle mute option

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2649]
There should be a "Mute" button when viewing `v.reddit`, or any other video/streamable links to quickly mute/unmute the volume.
(I would think this won't be possible for sources like `VID.ME` or `VIMEO` since I think that's just using the internal browser to load--plus, I think they have a mute toggle built-in).

Bonus points if this can be set to a default state in Settings.

Taken from #2647 (@brentluna)

**Comment by brentluna** [comment]
Yeah, there should be a settings option to have videos(streamable, vreddit, etc) to be muted as default, where when opened the videos audio toggle is set to off

**Comment by ccrama** [comment]
Done! Now it's a button that stays red between future opened videos if muted and stays unmuted if you unmute (default is unmute)
