### ISSUE TITLE
v.reddit streams don't display time remaining in progress bar

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2650]
When opened it doesn't populate the "length of video" on the right of the progress bar, so the progress bar slider is always at the farthest right position, leaving you unsure of how long the video is.

Taken from #2647 (@brentluna)

Has a timestamp: https://reddit.com/r/Unexpected/comments/7x033u/safety_first/

Doesn't have a timestamp: https://www.reddit.com/r/aww/comments/7wdykd/gilbert_is_showing_off_his_skills_in_his_favorite/?ref=share&ref_source=link

**Comment by ccrama** [comment]
Does this happen to all v.redd.it links? I remember seeing that once but not since

**Comment by Nxt3** [comment]
This one does have the timestamp: https://reddit.com/r/Unexpected/comments/7x033u/safety_first/

**Comment by ccrama** [comment]
Works for me :/

**Comment by ccrama** [comment]
Any other patterns to this behavior @Nxt3 ?

**Comment by Nxt3** [comment]
I've seen a few more instances of it occurring.

**Comment by ccrama** [comment]
Does this only occur with videos with sound?

**Comment by Nxt3** [comment]
I think so, yeah.

**Comment by incIined** [comment]
https://v.redd.it/ba208fuphfi01

Happens on this video.

**Comment by incIined** [comment]
Doesn't happen on this video with sound.

https://v.redd.it/p3449lguxki01

**Comment by incIined** [comment]
It seems to happen when a video isn't fully loaded or something, I don't know. 

https://streamable.com/ovcr2

**Comment by ccrama** [comment]
Fixed, the Reddit audio file was for some reason up to 4x longer than the video, so the length of the file was longer than the video and the player got confused. Just had to crop the audio down
