### ISSUE TITLE
Tapping on a comment collapses it (instead of showing menu)

### ISSUE THREAD

**Issue by smtchahal** [ccrama/Slide#2654]
Slide version: 5.7.3
Android version: 7.0

When you tap on a comment with replies, it collapses. In order to access the upvote/downvote/other stuff menu, you need to tap and hold. But when you tap on a comment with no replies, the upvote/downvote menu shows up.

I think tapping on a comment should show that menu no matter what, and tapping and holding on it should collapse it, because I upvote/downvote comments far more often than I collapse them. As a former Sync for Reddit user I'm obviously biased, but I wonder if anyone else agrees?

**Comment by Nxt3** [comment]
You can change this behavior. Settings - Comments - Swap long press and tap actions

**Comment by smtchahal** [comment]
Wasn't aware of that setting, I should've checked before &ndash; thanks!
