### ISSUE TITLE
Multireddit as default

### ISSUE THREAD

**Issue by synchr** [ccrama/Slide#2656]
It could be nice to have a way to make a multireddit the default displayed page when opening Slide.

**Comment by Nxt3** [comment]
You can do this already. Go to settings, manage subreddits. Move the multi-reddit you want to open by default up at the top of this list. Whatever item is at the top of the list, opens up first.

**Comment by synchr** [comment]
I already looked for the multireddit in "Manage subreddits" but didn't find it and just assumed multireddits didn't show up in that list. Just found out that i had to import the multireddit by pressing the "+" sign in the corner of "Manage subreddits" and press "Collection" where i was able to import my multireddit. Nice to see that this feature already exist, but I would say that it's too well hidden.

Thanks for the pointer, I'm closing the issue again.
