### ISSUE TITLE
Download notification sometimes doesn't finish

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide#2657]

**Comment by Isvvc** [comment]
It almost never finishes for me. Downloads are usually successful, but the download meter in the notification just freezes at a seemingly random point.

**Comment by PiwwowPants** [comment]
This seemed to be fixed for me with my change to clean up the sharing logic by putting it into a single class. In that, I modified some download behavior / notification download behavior. 

I assume you are, but are you running into this on the build with that recent change?

**Comment by ccrama** [comment]
@PiwwowPants  I also fixed a lot of logic in the ImageDownloadService class with my latest commit, I believe it never "finished" because the async task creating the notification was killed by the service stopping before it could totally display the notification
