### ISSUE TITLE
Crash when clicking GIF

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide#2667]
Slide version: 5.8a3
Android version: 8.1

https://redd.it/80f37v

The GIF linked in this post crashes Slide. There's a few other links it happens though. 

Logcat: https://pastebin.com/1J0P6dwH

**Comment by ccrama** [comment]
Has been fixed, only happens when Reddit doesn't include the media preview (might be an API bug?)

**Comment by ccrama** [comment]
Now it will forward you to the original post
