### ISSUE TITLE
"Hide read posts" inconvenient behaviour

### ISSUE THREAD

**Issue by alexandrulesi** [ccrama/Slide#2668]
Slide version: v5.8-alpha2
Android version: 8.0.0

I'm having issues with two behaviors:

1) When the method is run sometimes the first new post is not displayed at the top of the page, but is rather already half cut off. This prompts the user to swipe back to the top (on reflex), which is not far enough away, causing the user to swipe too far and prompt the refresh method instead. 

2) The method only clears read posts up to the first new post. Somehow though, at least in my case, single new posts appear in-between the old ones, making me have to run the method 3-4 times until I actually get to new material. You can imagine how annoying this scales with the first issue: I have to start over rather frequently and lose posts in the process, as they are being displayed and marked as "read" right before I accidentally refresh.

Now I saw a similar issue which got closed saying that when repeating the method in some cases no new pages may be found, I presume causing an endless loop. I'd suggest tackling this by simply setting a fixed maximum recursion depth (say 10-20?) after which the app could simply declare "No new posts" or something (although even a recursion depth of 3 would already be a game changer).

Hope this makes sense. I'd really appreciate giving this a second thought.

**Comment by Tensounder54** [comment]
This issue needs to be verified that this is still a issue before it any further action can be taken.

**Comment by Tensounder54** [comment]
This issue is resolved in a later version of Slide and needs to be closed.
