### ISSUE TITLE
Disable Comment Replies option

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide#2671]

**Comment by iknownothingaboutcomputers** [comment]
@ccrama You mean, the *disable inbox replies* option of the web client, right? Came here to post this issue but I'm glad that you already did. This is a much needed option!

**Comment by boggle247** [comment]
Is this for disabling comments for posts or disabling comments on comments you posted?

**Comment by Alexendoo** [comment]
Got added some time ago
