### ISSUE TITLE
Showing wrong comment level

### ISSUE THREAD

**Issue by silverAndroid** [ccrama/Slide#2672]
Slide version: 5.8
Android version: 7.0

[For this specific comment](https://reddit.com/r/androiddev/comments/81f2ns/unofficial_apis_will_be_blocked_in_android_p_but/dv396p1?context=3), the comment tree is messed up ![the comment tree is messed up](https://i.imgur.com/TppeeAs.png)

**Comment by PiwwowPants** [comment]
Can you explain what seems to be wrong here? I am on that thread right now and it looks fine. When you long press to open the reply menu, the thread level just gets pushed all the way to the left.
I suppose that could be seen as weird behavior.

**Comment by silverAndroid** [comment]
Sorry about that, this is what I meant to show. ![](https://i.imgur.com/qM1szST.png)

If you load the full thread, you'll see it

**Comment by PiwwowPants** [comment]
Are you referring to the purple line? The purple line indicates the commenter is OP of the chain, not that it's a new comment tree level. I believe that chain looks right to me (I loaded it in the browser to confirm).

**Comment by silverAndroid** [comment]
Ohh so it indicates a comment from OP? That could be confusing considering functionality regarding the colour changing in comment threads usually means new comment level in the thread. Thanks anyways!
