### ISSUE TITLE
Imgur Content renders based on URL extension

### ISSUE THREAD

**Issue by PiwwowPants** [ccrama/Slide#2676]
[Issue from Reddit](https://reddit.com/r/slideforreddit/comments/824cmf/this_post_is_supposed_to_be_a_gif_opened/)

Imgur Content renders based on the extension in the URL. Imgur allows you to put whatever extension you want on a URL and it'll still resolve it and display the image (since the extension doesn't matter to the server). In the scenario mentioned in the Reddit post, a Gif contains a .jpg extension, so Slide renders it as an image, not a Gif. 

A potential solution would be to strip the extension name before opening it, so it renders as generic "Imgur Content" and Imgur resolves the type. The listing will still say "Image" but that is possibly not solvable since the URL is "misinformed".

https://i.imgur.com/rxHkhoG.jpg
https://i.imgur.com/rxHkhoG.gif
https://i.imgur.com/rxHkhoG

Here are three links to test post with to verify behavior.

**Comment by ccrama** [comment]
At one point in time @Alexendoo  and I went through and tested many different link types and conflicts and got to a pretty good state of being able to catch mis-labeled links like this, but seems like there has been a degradation in this behavior for some reason...

I think the issue comes from this line which doesn't test .jpgs from Imgur specifically

https://github.com/ccrama/Slide/blob/master/app/src/main/java/me/ccrama/redditslide/Activities/MediaView.java#L973

**Comment by PiwwowPants** [comment]
I see. In there there is even a check for the content type and then the extension just gets modified. 

Is there a reason you wouldn't just dump the extension when loaded? They're useful for identifying the type of image from the list view, but Imgur doesn't really care about them  I don't know Imgur well, but does it do video types too that would cause problems?

**Comment by ccrama** [comment]
Honestly yeah we could just download the file and then do with it based on the extension, for gifs though we would have to download the MP4 separately as Imgur returns a .gif if you try to download that image (which is a 51 mb gif and a 1400k mp4). This is the main reason we try to handle this at a higher level before we start to download the content, and why we don't try with Imgur as it is usually correct

**Comment by PiwwowPants** [comment]
I decided I don't care in this case based on what you said. If we can't get the true metadata before loading, this is fine. If someone puts a jpg extension on a gif, it's the wild west since ain't no one paying for that Ingur API.

**Comment by ccrama** [comment]
Wouldn't that lead to a delay before displaying if it an image though @Alexendoo ? Seems like a high price to pay for what is usually a rare issue

**Comment by Alexendoo** [comment]
It shouldn't need to add a delay since the content type header arrives before the image itself

**Comment by PiwwowPants** [comment]
Isn't the current behavior just loading the image into the view, not using the API? Would we get the file type back in a response? If we load it without any extension maybe, but then to get the performance benefits mentioned on videos, we'd have to reload again with the extension, right?

**Comment by ccrama** [comment]
We do actually check already @PiwwowPants @Alexendoo https://github.com/ccrama/Slide/blob/b1abe06a465f807d99ea33970dfe84edb5b6db69/app/src/main/java/me/ccrama/redditslide/Activities/MediaView.java#L992
