### ISSUE TITLE
Redd.it videos not playing

### ISSUE THREAD

**Issue by skinnx86** [ccrama/Slide#2679]
Slide version: 5.8
Android version: 7.1.1

Since the new update [posts like this](https://redd.it/82q85d) download but do not play.

**Comment by Nxt3** [comment]
Could you link to the Reddit post where this exists? Slide doesn't open Reddit Video links directly

**Comment by skinnx86** [comment]
Apologies that link was supposed to be to the comments. Yes it's to a reddit video link.

So why does it load but not display? I believe in the old versions slide opened it in the built in browser, could that happen in the mean time. Is there any possibility of supporting them in the future?

**Comment by Nxt3** [comment]
Can you edit your link to link to the Reddit post where this video is used? We can't test it since you linked to just the Video, not the post.

**Comment by skinnx86** [comment]
@Nxt3 All fixed in the original post now.

**Comment by skinnx86** [comment]
Epicly quick re-release. Reddit video links work in their entirety. The link in my original comment works, as does others, with audio muting activated. :grinning:

**Comment by Nxt3** [comment]
Oh I just realized you were on an older version. Glad it's working now.
