### ISSUE TITLE
Removing post as a mod causes AppCrash

### ISSUE THREAD

**Issue by dylmye** [ccrama/Slide#2680]
Hi, 

Removing a post with a reason causes the app to crash. This is as a mod with full permissions. The action is still performed (the post is deleted) but the app force closes ~5 seconds after. 

I've just sent through the ANR report; if there are any more details I can add please let me know. 

OnePlus 3 / OOS Oreo Stock

**Comment by PiwwowPants** [comment]
This only occurs for you when removing a post with a reason, correct? I imagine removing without a reason doesn't cause the crash.

**Comment by dylmye** [comment]
That's correct.
