### ISSUE TITLE
Crash when open image -> click "comment" icon on bottom left

### ISSUE THREAD

**Issue by RandyTasajaya** [ccrama/Slide#2682]
Slide version: 5.8.2
Android version: 6.0.1 (OnePlus One using stock ROM)

Open image (with the app's image viewer) from an Image-Post ->

On the far bottom left side of the screen there's the "comment" icon, to open the comment section of the post ->

The app crashes.

**Comment by RandyTasajaya** [comment]
As far as I'm aware,

this doesn't happen with posts from subreddits I'm subscribed to,

in other words,

it only happens with posts from subreddits I'm not subscribed to.

**Comment by PiwwowPants** [comment]
Can you link a post where this has happened to you? I can't seem to reproduce it at all on 8.x or 6.x.

**Comment by RandyTasajaya** [comment]
Video: reproducing this bug on my phone

https://drive.google.com/file/d/1oVs5HJ1ajz7-CBiFoSROVWQSqNbCaaCP/view?usp=drivesdk

What happens in the video:1. Open Slide for Reddit.2. Showing I'm not subscribed to r/paint .3. Go to r/paint .4. Filter posts in this subreddit, so that I can open an image-post.5. Open an image post with the app's image viewer.6. Click the "comment" icon on bottom left.7. App crashes.
 
 
  On Sun, Mar 11, 2018 at 4:45 PM, James Downs<notifications@github.com> wrote:   
Can you link a post where this has happened to you? I can't seem to reproduce it at all on 8.x or 6.x.

**Comment by Tensounder54** [comment]
This issue is resolved in a later version of Slide and needs to be closed.
