### ISSUE TITLE
Navbar hiding on Samsung devices causes menus to freak out

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide#2694]

**Comment by Alexendoo** [comment]
Related to #2710 perhaps

**Comment by Tensounder54** [comment]
Totally agree this is related. It's only an issue in immersive mode like #2710 so it's up to @Alexendoo if they want to close or not.

**Comment by Tensounder54** [comment]
This issue isn't resolved but I think #2710 covers all of this areas that this issue covers so I'm closing it. Feel free to reopen if it needs to be reopened.

> ↳T*54*
