### ISSUE TITLE
Change Color dialog for Users allows touch through the view

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2698]
The change color dialog allows touches through the dialog. Any touch on a blank area of the dialog passes through to the dialog behind it, causing unexpected behavior.

**Comment by Tensounder54** [comment]
This issue needs to be verified that this is still a issue before it any further action can be taken.

**Comment by Tensounder54** [comment]
This issue is resolved in a later version of Slide and needs to be closed.
