### ISSUE TITLE
Minor overhaul to drawer layout

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#27]
* Remove saved and upvoted entries (not that they even do anything ATM), they should be tabs in profile

* Remove the two hard-to-reach entries at the bottom, they're addressed by #26 

* Add Settings entry (#26)

* Add "Go to subreddit" entry

* Move multireddits entry to bottom, next to the actual list of subscribed subs

**Comment by Alexendoo** [comment]
The fourth exists currently as 'search for a subreddit', wording could perhaps be tweaked

**Comment by The0x539** [comment]
TIL.

**Comment by ccrama** [comment]
Revamped with 7f3bae7e1f26aa7f2d17754a9d864bdf8266860f
