### ISSUE TITLE
Comments have wrong color

### ISSUE THREAD

**Issue by anonymous-user** [ccrama/Slide#2703]
Slide version: 5.8.5-alpha2
Android version: 8.1

In some comment chains, I noticed that sometimes two comments will be at the same level/indentation but have different color. I then checked what the same comments looked in another client and also the website.

This is the reddit post:

https://www.reddit.com/r/Android/comments/88i7al/frys_product_page_up_for_the_moto_g6_and_g6_play/

And here are the screenshots:

https://imgur.com/a/3fOpo

**Comment by PiwwowPants** [comment]
The purple line indicates the the OP of the comment chain. 

All other colors match indentation level but that one relays to the user (you!) that the commenter is the comment chain author. 

@ccrama this comes up enough that this may be a conveyance issue. I think I said this last time though too and I'm not sure if I have a better answer other than to possibly keep the indentation color as it should and add a text tag or a something else?

**Comment by anonymous-user** [comment]
Oh ok. In that case, can we have an option to disable that feature? It seems a bit confusing and I personally don't have a use for it.

**Comment by ccrama** [comment]
Settings > Comments > Comment OP indicator @anonymous-user

**Comment by ccrama** [comment]
I agree though @PiwwowPants , unfortunately I can't get that info at the time that I create the text line in an efficient way. I think one solution would be to maybe point it out when the user first goes to comments and runs into it with a snackbar or something? Or maybe have the feature disabled by default

**Comment by anonymous-user** [comment]
@ccrama Thank you for pointing that out to me.
