### ISSUE TITLE
Data Saving for Videos

### ISSUE THREAD

**Issue by pidus** [ccrama/Slide#2708]
Slide only offers data saving for pictures. It would be great if we could get a similar setting for Gifs/Videos. 

Slide version: 5.8.5
Android version: 7.1.1

**Comment by ccrama** [comment]
The issue is the site's I download videos from would have to host smaller versions of the same videos, which most don't

**Comment by Acters** [comment]
Can you please do it for Reddit's Video stream?(v.redd.it) back in the first implementations of Slide's support for v.redd.it, slide had given me a low res video with no sound(which I have disabled all the time). I was happy I was getting these 1 mb video streams but now I get up to 30 to 50 MB for each video stream. I believe reddit does support lower resolution video streams.

**Comment by ccrama** [comment]
They do support it, but there is no way for me to directly download it (with sound), which is why the system had to be changed. The lower urls are not exposed in the Reddit API, only if I look through the metadata of the dash stream and hope there is a lq url there @Acters

**Comment by Acters** [comment]
oh well that stops that. Reddit are sure pure geniuses. Thank you for calming my heart.

**Comment by ccrama** [comment]
They love to strip features from us third party devs

**Comment by Acters** [comment]
Why can't we get along and love each other as humans instead of considering each other as "they"? Why must we alienate each other?
