### ISSUE TITLE
Minor annoyance: it's impossible to view your own account if you're temporarily suspended

### ISSUE THREAD

**Issue by timawesomeness** [ccrama/Slide#2711]
It pops up with the "This account is suspended" dialog, and when you press OK it leaves your profile. It'd be nice if that didn't dismiss your profile when trying to view your own temporarily suspended account.

**Comment by ccrama** [comment]
Nothing is returned to display if you are suspended, though, so it would be unnecessary to show the profile behind it

**Comment by timawesomeness** [comment]
If you're temporarily suspended reddit will still return everything as if you weren't suspended. It's only on permanent suspensions where reddit doesn't return anything.

**Comment by ccrama** [comment]
I don't think it's actually possible to tell if it's a temporary suspension or a permanent one, the app just sees "suspension". Maybe don't show that if it's your account?
