### ISSUE TITLE
GIFs won't load correctly

### ISSUE THREAD

**Issue by NCXY** [ccrama/Slide#2716]
Slide version: v5.8.5
Android version: 8.1.0 (April 5 security patch)

I've had the same problem as the one located at this Reddit thread as well:

https://www.reddit.com/r/slideforreddit/comments/81wy1x/probably_not_a_slide_issue_but_i_cant_watch_gifs/

I've had it on the previous Slide version before too, not sure how it started or why it started happening as GIFs worked before. The fix is the same as the Reddit thread, turn off WiFi, and it loads on Data. It doesn't matter if I have a data saving feature on or off, it still doesn't load properly on WiFi.

**Comment by xnaas** [comment]
Does force-stopping and clearing cache help for an extended period of time? Whenever I was on the beta branch and the app got fucky, I'd just do that and it _usually_ cleared up any issues I was having.

**Comment by Tensounder54** [comment]
This issue is resolved in a later version of Slide and needs to be closed.
