### ISSUE TITLE
Clicking this link causes device to become frozen

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2718]
Clicking this link causes my phone to become unresponsive. https://reddit.com/r/ProgrammerHumor/comments/8b51ez/standing_room_only_for_the_duel_of_the_ages/dx43whc?context=3

Might have to do with setting Slide as the default handler of Reddit links?

**Comment by ccrama** [comment]
For me, it opens in a web view and says page could not be found. What are your link handling settings?

**Comment by Nxt3** [comment]
![Link Handling Settings](https://i.imgur.com/x16uapA.png)

**Comment by Nxt3** [comment]
![Slide Settings](https://i.imgur.com/paxDscq.png)

**Comment by Nxt3** [comment]
And the external browser I'm using is Lynket.

**Comment by ccrama** [comment]
I think @PiwwowPants 's latest PR fixes this! #2728

**Comment by PiwwowPants** [comment]
It doesn't! CCRAMA!!!
I only fixed it with the internal browser. I need to extend this to the external browser to fix the infinite unresponsive loop.

**Comment by ccrama** [comment]
Just kidding
