### ISSUE TITLE
Slide crashes when i open filtered content

### ISSUE THREAD

**Issue by nikgtasa** [ccrama/Slide#2720]
Slide version: 5.8.2
Android version: Miui 9, Android 7.0
Tried restarting the phone but didn't help. It happened when i accidentally filtered reddit pictures.

**Comment by nikgtasa** [comment]
Tried 5.8.5. Reinstalled and everything was okay before i had restored my backup.

**Comment by Tensounder54** [comment]
This issue is resolved in a later version of Slide and needs to be closed.
