### ISSUE TITLE
Suggestion: add comment account switcher to FAB reply pop-up

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide#2731]
When replying from the save/vote bar:
![](https://i.imgur.com/86bkRs1.jpg)

when replying from the FAB:
![](https://i.imgur.com/KbdOsTm.jpg) - notice you can't switch account from here. 

Would be pretty useful and more consistent imo. 

Slide v5.8.6

**Comment by ccrama** [comment]
Done by @PiwwowPants !
