### ISSUE TITLE
old.reddit.links don't work 

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide#2738]
Slide 5.8.6
Android 8.0 TouchWiz 2/1/18 security patch 

Link in question:
 https://old.reddit.com/r/videos/comments/8evwfu/my_dog_cant_stop_wagging_his_tail_while_playing/

Just gives me this error: 
![](https://i.imgur.com/TiLDb1G.jpg)

Works fine when opened in browser.

**Comment by Lionirdeadman** [comment]
This is an inconsistency with Reddit.

Instead of reddit.com/r/subreddit, you can also do subrrddit.reddit.com for the same thing.

I guess an exception should be made for old.reddit.com since it won't redirect you a subreddit but rather to the old site.

**Comment by Alexendoo** [comment]
Yeah it's one of the many reddit URL quirks they've built up over the years. Thanks for the report @incIined
