### ISSUE TITLE
Image not fully appearing in LQ mode, appears on HQ mode

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide#2743]
Slide 5.8.6
TouchWiz 9.0 Oreo, 2/1/18 patch level 

Link to post: 
https://redd.it/8g00md

LQ:
![](https://i.imgur.com/JoGzZcI.jpg)

HQ:
![](https://i.imgur.com/mg8193w.jpg)

**Comment by ccrama** [comment]
That is because the image hosting website does that for lower quality images. Unfortunately nothing Slide does on its end for this to happen
