### ISSUE TITLE
An option to keep posts unread

### ISSUE THREAD

**Issue by azumukupoe** [ccrama/Slide#2752]

**Comment by PiwwowPants** [comment]
You mean from the FAB? The FAB can be disabled in Settings (I believe in General, if not in Post Layout).

**Comment by azumukupoe** [comment]
@PiwwowPants Yes, I've already disabled the FAB.

**Comment by ccrama** [comment]
Settings > History and you can disable history or nsfw history separately

**Comment by azumukupoe** [comment]
@ccrama It doesn't work...

**Comment by ccrama** [comment]
What do you mean? This disables it from ever turning gray (unless you have already seen them before you enabled the setting)

**Comment by azumukupoe** [comment]
@ccrama I have history disabled but it's still turning gray

**Comment by ccrama** [comment]
Oh, that is because Reddit marks it as read when you vote. That's the intended behavior

**Comment by azumukupoe** [comment]
@ccrama Can you still add an option to show all posts in black letters? This is the only client I have ever seen with this feature.
