### ISSUE TITLE
Volume key comment navigation doesn't work in "secondary" subreddit view

### ISSUE THREAD

**Issue by tgkokk** [ccrama/Slide#2773]
Slide version: 5.8.6
Android version: 8.0

Steps to reproduce:

1. Enable comment navigation with volume keys.
2. Go to e.g. Settings > About > /r/slideforreddit.
3. Tap on any post with comments.
4. Press volume down.

Expected behaviour: Slide scrolls to the first comment.

Actual behaviour: Volume changes.

**Comment by stalker314314** [comment]
FYI - tried to repro and it does work for me (do not repro). Both master branch and 5.8.6. Also android 8.0 (lineageOS), Xiaomi 4x. Maybe add more of your settings here?

**Comment by tgkokk** [comment]
True, I think turning on Comment pane in General > View type should be enough to reproduce it.

**Comment by stalker314314** [comment]
Yap, with "Comment pane", it it reproing for me too!
