### ISSUE TITLE
Can't open in external app from internal browser

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide#2774]
Slide 5.8.6
TouchWiz 8.0 Oreo, 2/1/18 patch level

This might be a device issue unrelated to the app but...

This is what I see when I try opening in an external app from the internal browser. 
![](https://i.imgur.com/nLHkeCa.jpg)

This is what happens when I long press a link and click "open externally"

![](https://i.imgur.com/O4YV4dT.jpg)

Basically, my Twitter app and browser aren't showing up in the menu. 

Reddit post link: https://reddit.com/r/SuddenlyGay/comments/8kgq0f/a_kiss_on_the_cheek/dz85r5w?context=3

**Comment by ccrama** [comment]
What are your open externally settings in Settings > Link Handling?

**Comment by incIined** [comment]
@ccrama ![](https://i.imgur.com/tck6BEe.jpg)

**Comment by ccrama** [comment]
Hmm, calling @PiwwowPants, is this possibly related to your previous PRs?

**Comment by PiwwowPants** [comment]
I don't have confidence I caused this. The only PR I put in stopped the internal browser from opening in Reddit again. The change to fix the external browser wasn't released yet.
