### ISSUE TITLE
Auto-rotation setting ignored while viewing post comments or in subreddit

### ISSUE THREAD

**Issue by EthanArmbrust** [ccrama/Slide#2775]
Slide version: dbb58dc198ba5cc371a3f7057fbf96fa7d2d9b58
Android version: 8.1.0 and P beta

Happens on commit dbb58dc198ba5cc371a3f7057fbf96fa7d2d9b58 but not previous ones.  
When viewing a post's comments or while browsing a single subreddit, the screen will rotate into landscape view even when auto-rotate is disabled by the OS.

**Comment by ccrama** [comment]
I believe this one is actually a P beta issue, will wait for a future update to see if Google has fixed this one!

**Comment by EthanArmbrust** [comment]
This was also happening in 8.1.0 as well

**Comment by PiwwowPants** [comment]
Thanks for testing on multiple OSs. I had told @ccrama I thought this was an Android P issue when I first saw it so we brushed it off. Should be fixed in my PR.

**Comment by EthanArmbrust** [comment]
Awesome. Thanks!
