### ISSUE TITLE
Strange issue - audio gets warped when opening a Reddit video 

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide#2776]
Slide 5.8.6
Galaxy S9+ (SM-G965U) on TouchWiz 8.0 Oreo, 2/1/18 patch level

Video of the issue:
https://streamable.com/bkodr

I've never seen this before. And it only happens on this one particular video. 

Seems to only happen when using Spotify or YouTube, when using SoundCloud it just makes an audible "pop" when it loads, and SoundCloud's audio and the video plays normally.

Dolby Atmos on or off doesn't make a difference. 

Reddit post: https://redd.it/8kid4w

Let me know what other info you might need.

**Comment by ccrama** [comment]
If it happens with one specific video it might not be fixable as it's likely an issue with that videos encoding. But if you notice it again please update me!
