### ISSUE TITLE
Content Filters don't catch v.redd.it

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide#2783]

**Comment by PiwwowPants** [comment]
It is also not catching youtube links in any form for some reason.
Breakpointing in `PostMatch.doesMatch` is showing youtube get through.

**Comment by Tensounder54** [comment]
This issue is being closed as it is resolved in PR #2784.

**Comment by MetalNeo** [comment]
I am experiencing this issue with v.reddit and youtu.be links not being filtered properly.

Android: 11
Slide: v6.7
