### ISSUE TITLE
When making a new post, text fields are treated as login fields by Oreo autofill

### ISSUE THREAD

**Issue by najodleglejszy** [ccrama/Slide#2789]
Slide version: 5.8.6
Android version: 8.0

Whenever I create a new post in Slide, all text fields in all submission types (selftext/image/link) are detected by password manager. which shows autofill option on each of them. The only exception is the URL field in Link submission type. Here's a screenshot of Bitwarden offering filling credentials into Title field, but the same thing is happening with Subreddit name and Text. 

![screenshot_20180526-201209](https://user-images.githubusercontent.com/8598559/40579168-40c0e27e-6111-11e8-8fd2-237de5bf06f1.png)

Bitwarden uses Android Oreo's autofill service, so I suspect that other password managers that use it instead of Accessibility service are doing the same thing.
I'm experiencing the issue on Sony Xperia XZ2 Compact, but I've also had it on other phones running Android Oreo.

**Comment by ccrama** [comment]
@PiwwowPants  I believe we can fix it by adding this method to the base activity

`    @Override
    public void onCreate(Bundle savedInstanceState) {
       super.onCreate(savedInstanceState);
       disableAutoFill();
    }

    @TargetApi(Build.VERSION_CODES.O)
    private void disableAutoFill() { 
        getWindow().getDecorView().setImportantForAutofill(View.IMPORTANT_FOR_AUTOFILL_NO_EXCLUDE_DESCENDANTS);
    }
`

**Comment by PiwwowPants** [comment]
@ccrama is there no where in the app where we want to have autofill happening? Would this make autofill in the OAuth view break, assuming it opens internally in the app as a WebView?
Things I could probably just check instead of asking.

**Comment by ccrama** [comment]
We could just override the method in the login subclass, should be the only place we might want it!

**Comment by Tensounder54** [comment]
Issue resolved in PR #2792
