### ISSUE TITLE
Continous slide not working after searching for subreddit

### ISSUE THREAD

**Issue by candlej4ck** [ccrama/Slide#279]
After searching for a subreddit, posts won't continously keep loading after reaching the bottom. Seems to work fine for the default subreddits that are pinned.

**Comment by l3d00m** [comment]
Can repro

**Comment by ccrama** [comment]
Wow this is a very large issue actually. I have the same object in DataShare that is referenced from loading a sub and opening comments. Need to fix this soon

**Comment by ccrama** [comment]
I believe it's been fixed for a while
