### ISSUE TITLE
Suggest popular subreddits in lieu of subscribed ones when searching for a subreddit

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#28]
This will allow quicker matches of subreddits and highlight the fact that the field can be used to go to a subreddit the user is not subscribed to

**Comment by The0x539** [comment]
Should prioritize subscribed ones, though.

**Comment by ccrama** [comment]
Interesting. I'll look into this! I can also do a subreddit search and add those subreddits below while typing, which would be pretty neat I think

**Comment by ccrama** [comment]
Instead, made a "Go to ____" option in the sidebar!
