### ISSUE TITLE
Could we get a new build?

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2802]
@ccrama I know you're busy and all, but could you release a new beta? With old.reddit links becoming more prevalent, it would be beneficial to have this fix.

**Comment by ccrama** [comment]
Unfortunately this build currently contains a lot of untested changes and I am totally investing my time into the iOS app as of now (switching between swift and Java is tough....). I cannot offer a timeline as of right now, but may release a super alpha soon to test all of the recent changes (especially @PiwwowPants 's changes), or just release an update with changes to support the reddit link types

**Comment by Nxt3** [comment]
I can't imagine switching between Swift and Java hahaha. @PiwwowPants has been on 🔥with all these great changes so it's no surprise there's lots to test.

**Comment by Alexendoo** [comment]
Fix was released cherry picked and released as 5.8.7
