### ISSUE TITLE
The app crashes when trying to search for comments with a specific word on specific post

### ISSUE THREAD

**Issue by azumukupoe** [ccrama/Slide#2808]
The app crashes when trying to search "Gideon" on [this post](https://redd.it/8sz67b).
I have to force close the app to use it again.

**Comment by PiwwowPants** [comment]
Thanks for the easy report. 
I can only get the "g" in before the app locks up. 

I'll check this out.

**Comment by azumukupoe** [comment]
Oh, I forgot to tell you about it.
Yes, only "g."

**Comment by PiwwowPants** [comment]
I'm sorry to wait so long on this but I made it no where with this so if anyone else is looking please do investigate. This is still on my radar though.

**Comment by Tensounder54** [comment]
While there is no version number attached to this issue it is resolved in Slide version 5.9-alpha2. 
This issue has been resolved and needs to be closed.
