### ISSUE TITLE
Using Japanese input to type into "Go to subreddit" triggers a glitch

### ISSUE THREAD

**Issue by azumukupoe** [ccrama/Slide#2810]

**Comment by Nxt3** [comment]
What's the glitch? It worked for me

**Comment by Nxt3** [comment]
You should really put that kinda info in the description 😬

**Comment by incIined** [comment]
Should probably take a screenshot or screen recording of the issue. You don't go to your mechanic and say "when you go 88 miles an hour something weird happens", right?

**Comment by Alexendoo** [comment]
What is the "glitch" exactly @azumukupoe - what happens that should not?

**Comment by azumukupoe** [comment]
I took a screen rec.
http://www.sharedvid.com/da495de57c4badeb/

**Comment by Alexendoo** [comment]
More palatable link: https://streamable.com/qanfe

I think this is a bug with the keyboard in question reacting to the restricted chars. Google Japanese Input seems to handle it fine

We could potentially remove the in field character restriction and strip the incorrect characters just in code, which would potentially have better compatible with international keyboards (first applying NFKD could also help here)

**Comment by Tensounder54** [comment]
This issue needs to be verified that this is still a issue before it any further action can be taken.

**Comment by Tensounder54** [comment]
@Alexendoo Your Streamable link is broken FYI.
