### ISSUE TITLE
Sending Messages

### ISSUE THREAD

**Issue by GIVEMEARUNFORMYMONEY** [ccrama/Slide#2814]
Unsure if this issue has already been reported however: everytime I send a message I get an error message saying error 25. Yet the message is still sent to the receipient anyways. ![GitHawk Upload by GIVEMEARUNFORMYMONEY](https://i.imgur.com/dSAgJma.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by incIined** [comment]
If this is for the iOS version, I think it would be better if you submitted an issue in the Slide iOS GitHub page instead of this one, which seems to be just the Android version. 

https://github.com/ccrama/Slide-iOS

**Comment by incIined** [comment]
Anyways, I’m not getting this issue on mine. 

iPhone 6S 11.1.2
Slide 1.3 (21)
