### ISSUE TITLE
Embedded links that reference sub-page wikis do not work

### ISSUE THREAD

**Issue by PiwwowPants** [ccrama/Slide#2816]
With the new WebView-based Wiki implementation, if a link on the Will references a sub-page (e.g. "Recommended/Books") the new page will not be loaded. 

This is most likely due to how the WikiPage title is pulled from the URL, as I believe it doesn't care about anything after a forward slash. 

Can be tested with the /r/lifeisstrange Wiki and selecting "Books" from the recommended page. This action should open the "Recommended/Books" page.

**Comment by Tensounder54** [comment]
This issue is resolved in a later version of Slide and needs to be closed.
