### ISSUE TITLE
Viewing text posts crashes app

### ISSUE THREAD

**Issue by DarkZek** [ccrama/Slide#2821]
Slide version: 5.8.7
Android version: 8.1 (Los)
When I enter a text post the app crashes. I captured a log of the event for you.
https://pastebin.com/n3wLpTCN
I have tried restarting the app and my phone, it was working fine this morning and my phone has not updated since then (updates arent automatic on my ROM)

**Comment by Tensounder54** [comment]
This issue is resolved in a later version of Slide and needs to be closed.
