### ISSUE TITLE
Spoiler + Code Block rendering issue

### ISSUE THREAD

**Issue by xnaas** [ccrama/Slide#2825]
Slide version: 5.9-alpha1
Android version: 9 (DP5 on Pixel 2)

How it appears on Slide:

![img1](https://cdn.discordapp.com/attachments/436560603931213825/474929622568665098/Screenshot_20180803-082013.png)

How it appears on desktop (correct):

![img2](https://cdn.discordapp.com/attachments/436560603931213825/474929648044867586/unknown.png)

**Comment by xnaas** [comment]
God damnit github.

**Comment by Alexendoo** [comment]
When the HTML gets ran through

https://github.com/Alexendoo/Slide/blob/1b3f5950988f896b4c4b297dec67026cfa121aff/app/src/main/java/me/ccrama/redditslide/SpoilerRobotoTextView.java#L194

the value is `<div class="md"><div><code>[[&lt;[&gt;!this!&lt;]&gt;]]</code> turns into <span class="md-spoiler-text">this</span></div>`

so in https://github.com/Alexendoo/Slide/blob/1b3f5950988f896b4c4b297dec67026cfa121aff/app/src/main/java/me/ccrama/redditslide/SpoilerRobotoTextView.java#L198-L207

It matches as:

```html
<div class="md"><div><code>[[&lt;[&gt;!this!&lt;]&gt;]]</code> turns into <span class="md-spoiler-text">this</span></div>
                                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^~~~~~~~~~~~~~
                                                                          match                         group 1
```

so `text` is the string `"this"`

https://github.com/Alexendoo/Slide/blob/1b3f5950988f896b4c4b297dec67026cfa121aff/app/src/main/java/me/ccrama/redditslide/SpoilerRobotoTextView.java#L204

replaces then replaces **both** occurrences of it in the string with a spoiler tag.
