### ISSUE TITLE
Comment rendering incorrectly with spoilers and ponymotes

### ISSUE THREAD

**Issue by BytewaveMLP** [ccrama/Slide#2828]
**Slide version:** v5.9-alpha1  
**Android version:** 8.0.0

When viewing [this comment](https://np.reddit.com/r/mylittlepony/comments/94jcz9/lady_tirek_by_evehly/e3lec8r/) in Slide, it renders... well, horribly. It looks like a bunch of empty(?) spoiler tags and the comment in unparsed HTML form.

![Failed comment render - the comment appears to Slide as being composed of empty spoiler tags and unparsed HTML](https://i.imgur.com/mxl6Qdg.jpg)

I would imagine this is caused by the ponymote at the start of the comment. I do have the PonyMotes app installed, and I can uninstall it if necessary to test, but if I can avoid a database update that takes like an hour I'd like to do that. ;p

**Comment by bb010g** [comment]
Reproduces the same for me on 8.1.0.

**Comment by BytewaveMLP** [comment]
Appears to be fixed as of alpha 2. Much appreciated!

**Comment by Alexendoo** [comment]
Good to hear, thanks @BytewaveMLP
