### ISSUE TITLE
Links crashing slide

### ISSUE THREAD

**Issue by JmplJeff** [ccrama/Slide#2832]
Slide version: v5.9 alpha 1
Android version: 6.0.1

Whenever i click a link, slide crashes.

**Comment by Alexendoo** [comment]
Does it crash on every link @JmplJeff?

**Comment by JmplJeff** [comment]
Yes, every link.

**Comment by JmplJeff** [comment]
Even when click on "open externally" after a long press it also crashes.

**Comment by Alexendoo** [comment]
Could you send some screenshots of your link handling page? (In Settings)

**Comment by Alexendoo** [comment]
Thanks!

Might be related to link handling changes @PiwwowPants?

**Comment by Alexendoo** [comment]
Does the crash still occur for you in v5,9-alpha2 @JmplJeff?

**Comment by touzainanboku** [comment]
@Alexendoo I was having the same issue and it seems to be fixed for me now 👍

**Comment by Tensounder54** [comment]
> 
> 
> Does the crash still occur for you in v5,9-alpha2 @JmplJeff?

@Alexendoo I know this is resolved in `alpha2`.

**Comment by Tensounder54** [comment]
This issue has been resolved and needs to be closed.
