### ISSUE TITLE
Feature Request: "Favorite Subreddits" 

### ISSUE THREAD

**Issue by AdhocSyn** [ccrama/Slide#2836]
Slide version: 5.9-alpha1
Android version: 9

I think having the ability to mark favorite subs would be nice, keeping them at the top of the list even while the rest are alphabetized. Like how Relay does it, where you can star subs.

**Comment by Nxt3** [comment]
You can Pin subs already. Settings > Manage Subreddits. Then click a sub and select "Pin"
