### ISSUE TITLE
links in r/multihub (to reddit multis) are all displayed as u/_ links

### ISSUE THREAD

**Issue by travisfw** [ccrama/Slide#2844]
Slide version: 5.9-alpha2
Android version: 7.0

Go to r/multihub and try a few. Obviously all submissions are from the same user. Looks like the person who created the multi.

**Comment by Tensounder54** [comment]
Could you post a screenshot of where this is happening as when I load up the same verson on my phone, this bug does not occur.

**Comment by travisfw** [comment]
Here are a couple screen shots. One of the post in r/multihub, and the next, the screen shown when I click the link in the post. The posts are from the user who posted the r/multihub post.

https://imgur.com/goXWNmN

https://imgur.com/HFVbQj5
