### ISSUE TITLE
Draft Discarding Crash

### ISSUE THREAD

**Issue by Ipquarx** [ccrama/Slide#2847]
It appears that if you immediately discard an empty draft, Slide will crash.

Platform: Android 6.0, LG G4, Slide 5.8.7

Steps to reproduce:

1. Load comments section of any post
2. Click 'Reply'
3. Click to save draft
4. Immediately click the 'discard' text that appears at the bottom of the screen.
5. Slide should crash.

**Comment by Tensounder54** [comment]
The idssue is resolved in version 5.9-alpha2
