### ISSUE TITLE
File of exported settings is incorrect (no newline)

### ISSUE THREAD

**Issue by concatime** [ccrama/Slide#2870]
Slide version: 5.9-alpha2
Android version: LineageOS 7.1.2

Exporting will NOT generate a newline at end of file :  “A file that is not empty and does not end with a newline is therefore not a text file.” [[1](//unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file)]
And importing a file with a newline will generate an error:
```
W/System.err( 6344): java.lang.StringIndexOutOfBoundsException: length=1; regionStart=6; regionLength=-7                                
W/System.err( 6344):     at java.lang.String.substring(String.java:1931)                                                                
W/System.err( 6344):     at me.ccrama.redditslide.Activities.SettingsBackup.onActivityResult(SettingsBackup.java:93)                    
W/System.err( 6344):     at android.app.Activity.dispatchActivityResult(Activity.java:6937)
```

**Comment by Alexendoo** [comment]
To clarify you're adding a newline manually to the backup and it's breaking?

**Comment by Alexendoo** [comment]
I can see why this might happen actually, yeah it's worth fixing

**Comment by Tensounder54** [comment]
This issue has been resolved and needs to be closed.

**Comment by concatime** [comment]
Perfect.

**Comment by Tensounder54** [comment]
> EDIT: Also, exporting settings should generate a file with a \n at EOF.

I this is a probelem I'd suggest that you open another issue to raise this problem.
