### ISSUE TITLE
Display the Silver/Platinum gildings alongside Gold

### ISSUE THREAD

**Issue by Gotolei** [ccrama/Slide#2876]
https://www.reddit.com/coins

Quick example of what it looks like on desktop:
![image](https://user-images.githubusercontent.com/7553595/47275151-fc8a3b00-d569-11e8-8c8d-6ecdfbc3d627.png)

Currently, only gold is shown:
![image](https://user-images.githubusercontent.com/7553595/47275213-82a68180-d56a-11e8-870a-35d8d2147094.png)

Possible addition to this: an option to have gilding icon/text scaled down to the same size as the flair text, since with up to three different icons and counters it can get big quickly.

Slide version: 5.9 a2
Android version: 8.1.0

**Comment by timawesomeness** [comment]
Already made pull request #2874 to add it

Scaling it down is a good idea though, it's fine with the DPI I use but it might not by fine for people with higher DPIs
