### ISSUE TITLE
Annoying 403 and 401 errors

### ISSUE THREAD

**Issue by NoahJelen** [ccrama/Slide#2883]
Slide version: 5.9-alpha2
Android version: 8
 Every now and then when I go to open the app, instead of my frontage or any subs loading, I got an error toast saying "A server error occurred 401 (403)". What exactly is causing these errors and are there any workarounds apart from killing the app's process in Settings?

**Comment by smarek** [comment]
Related #2871

**Comment by elementh** [comment]
It's been happening to me for months

**Comment by Tensounder54** [comment]
You say that the only workaround that you have is to kill the app's process in settings, Will the app do the same thing if you close and reopen it. By this I mean, sliding away the app on the running apps screen.

**Comment by elementh** [comment]
@Tensounder54 in my case, sliding it away it's _sometimes_ enough, and sometimes I have to reopen and slide it 2 or 3 times for it to work.

Related to this issue, 1/3 of the times this happens, I'm using the app perfectly and after and interface change (that is, from wi-fi to 4G) or when I lose signal (4g) and recover it quickly (usually a tunnel or something in my commute) this error triggers and all posts dissapear and 401(403) happens until I restart the app from 0.

**Comment by Tensounder54** [comment]
OK I'll take a look at this.

**Comment by NoahJelen** [comment]
@Tensounder54, closing the app from the task list screen does not work at all. It still gives the annoying error after that.

**Comment by Tensounder54** [comment]
Humm? This one might be complex. I'll look into sorting this at some point.

**Comment by Tensounder54** [comment]
Please see #2604 for official answer and explanation.
