### ISSUE TITLE
GIF/Video compression when streaming

### ISSUE THREAD

**Issue by chandujr** [ccrama/Slide#2885]
Some gif/video files are greater than 50MB when streaming. Is it possible to compress them before streaming? Reddit videos are usually the culprits in my experience.

**Comment by chandujr** [comment]
Are we using any libraries for media playback?

**Comment by ccrama** [comment]
Unfortunately the videos are hosted by Reddit and Reddit does not let us know if there are lower quality URLs to stream. We have to assume the full quality URL
