### ISSUE TITLE
Overhaul post customization

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#29]
So you have the settings, from which you can get basically any possible hybrid of the three presets, or something else entirely.

So you also have the presets, which are just bundles of the settings. No preset is "set" as part of the stored settings, they're just applied, which changes all the settings defined in them.

# Settings

#### View type
* Card: Self-explanatory. Form over function, with cards on a background, and of course whitespace.
* List: Self-explanatory. Separated only by dividers, with no real between-padding or side-padding. However, some padding may be necessary for the Big Picture and Infobar modes, but not much.

#### Link Preview
* Big Picture: That thing that's big and a picture.
* Infobar: That thing with the thumbnail, link title, and URL, in its own little separate division of the post. This is also what Big Picture reverts to when there's no suitable image.
* Thumbnail only: Only the thumbnail, find some way to also say at least what the domain is if not the important bits of the URL.

#### Big Picture Maximum Aspect Ratio
* Numeric Slider: Ranges from something pretty low to two, as I doubt any Android phones have a 9:21 display. If the bigpic is over the aspect ratio, perform the action defined by the next setting.

#### Big Picture Too-Tall Behavior
* Do Nothing: Display the picture normally anyway. May cause frustration due to vertical comic strips.
* Crop From Top: Crops the picture, leaving the top bit intact.
* Crop From Center: Crops the picture, leaving the center intact.
* Crop From Bottom: You know the drill.
* Revert to Infobar: Same behavior as if there were no suitable image for use in a bigpic at all.

#### Big Picture Info Overlay
That transparent thing with text that gets overlaid over the bigpic.
* Always: Display as long as there's a bigpic.
* Titles Only: Display only if the content being bigpic'd has a title in its metadata.
* Never: Never display the info overlay.

#### Thumbnail Placement
* Left
* Right

#### Action Bar
* Compact: Basically what you have now. Inline with other post metadata info, and few buttons.
* Collapsible: Basically what's present in Sync's smaller-cards and list options. A collapsible bar that appears on a maximum of one post at a time, with more buttons like save and share. Score and comments should still be visible elsewhere.

#### Font Size
* font size selector thing(y|ies)

#### Font Face
* font face selector thing(y|ies)

# Presets

### Compact
* View Type: List
* Link Preview: Thumbnail Only
* Action Bar: Collapsible
* Font Sizes: Pretty Damn Small

### Cards
* View Type: Card
* Link Preview: Thumbnail Only
* Action Bar: Compact
* Font Sizes: Decidedly Medium

### Big Cards
* View Type: Card
* Link Preview: Big Picture
* Big Picture Maximum Aspect Ratio: 1.5
* Big Picture Too-Tall Behavior: Revert to Infobar
* Info Overlay: Titles Only
* Action Bar: Compact
* Font Sizes: Arguably Large

**Comment by ccrama** [comment]
Started with 02e0aad78e5cc42526e5a6126995124bbeceac34

**Comment by ccrama** [comment]
Has been done for a few versions!
