### ISSUE TITLE
Opening an image activates Night Mode

### ISSUE THREAD

**Issue by granpepito** [ccrama/Slide#2908]
Slide version: Slide v5.8.7
Android version: Android 9.0

When I open an image, if the night mode (where the screen has a yellow tint for better usage) is disabled, the image comes with the yellow tint (like the night mode). When the night mode itself is enabled, opening an image and then closing it, disables the night mode. It means that I have to turn it off and turn it on for it to be normal again.

**Comment by timawesomeness** [comment]
I'm gonna guess you're on a OnePlus device?

[It's a OnePlus issue](https://www.reddit.com/r/slideforreddit/comments/9uy1vi/clicking_on_images_turns_night_mode_on_help/e9j8xh9/). We may be able to work around it in Slide, but ideally OnePlus should fix their version of Android.

**Comment by granpepito** [comment]
Yes I own one. 

Thank you for the reply.

**Comment by Tensounder54** [comment]
I'm closing this issue until someone creates a workaround or OnePlus fixes their version of Android.
