### ISSUE TITLE
Opening Reddit API documentation causes Slide to freeze entire phone

### ISSUE THREAD

**Issue by Smashman** [ccrama/Slide#2913]
Slide version: Slide v5.8.7
Android version: 9
Hardware: Pixel 2 XL

I was interested in the Reddit API and proceeded to Google as such. The [first link](https://www.reddit.com/dev/api/) (Do not click if you have Slide set to open links by default!) causes Slide to hang my entire phone for a while. Eventually I can get back in and kill Slide. 

This is 100% reproducible. 

Thanks for the app and work that you've been doing!

I've also posted on Reddit here: https://redd.it/a0dv7t

**Comment by timawesomeness** [comment]
This is fixed in v5.9-alpha2.
