### ISSUE TITLE
Night theme no longer automatically turns on

### ISSUE THREAD

**Issue by KeesNijenhuis** [ccrama/Slide#2914]
Slide version: Slide v5.9-alpha2
Android version: 8.0.0

I use the automatic night mode and since last update it no longer turns on automatically.

**Comment by Tensounder54** [comment]
What device are you running Slide on?
Are you signed in at the time that this issue occurs?
Are you using the version of Slide from FDroid or the Google Play Store?

**Comment by KeesNijenhuis** [comment]
Hi,

I think it was actually an Android bug because my nigtlight also was not turning on. 
It didnt work for a couple of days but it started working again after I rebooted my phone.

What device are you running Slide on? Oneplus 3T
Are you signed in at the time that this issue occurs? yes
Are you using the version of Slide from FDroid or the Google Play Store? Google Play version

**Comment by Tensounder54** [comment]
If you think its an Android issue would you like me to close it for you?

**Comment by KeesNijenhuis** [comment]
Yes, thats fine
