### ISSUE TITLE
gfycat gifs don't open

### ISSUE THREAD

**Issue by bradii2** [ccrama/Slide#2915]
Slide version: 5.9-alpha2
Android version: 9

**Comment by the-eater** [comment]
Just about to open this :')

Example link: https://www.reddit.com/comments/a0y20n

Screenshot: 
![screenshot_20181128-085257_slide](https://user-images.githubusercontent.com/1922630/49136813-13e7e100-f2eb-11e8-89bd-3082c7e6ae44.png)

**Comment by bradii2** [comment]
Yeah, I think maybe gyfcat updated their website in a way that broke slide just earlier today. It's the only thing I can think of

**Comment by the-eater** [comment]
This happend before: #2600 may be fixed in a moment, may be the end of it working
