### ISSUE TITLE
Gfycat links fail to open with "gif not found" error

### ISSUE THREAD

**Issue by gargolito** [ccrama/Slide#2920]
Posts that have gfycat links fail to open with "gif not found"
Phone: 
Pixel XL, Android 9, Build PPR2 181005.003.A1

Here's a couple of examples post that works if you use "open external" in slide but doesn't work if you tap the image.

https://redd.it/a1r5di
https://redd.it/a1qkmu

**Comment by abqnm** [comment]
Something with the Giycat API changed. Imagus for the PC was having issues too, and had to make a very small change to accommodate. Hopefully it can be corrected here too.

**Comment by timawesomeness** [comment]
This is fixed now

**Comment by Scrumplex** [comment]
> This is fixed now

Which commit fixed that?
@timawesomeness

**Comment by abqnm** [comment]
@Scrumplex https://github.com/ccrama/Slide/commit/f9f3fde141ca0369ad11097429829d2c16ac88c4

**Comment by Scrumplex** [comment]
Thank you. Didn't expect it to be 5 days ago

**Comment by abqnm** [comment]
@Scrumplex I think gfycat killing their old API without notice is what prompted the push for the quick release of 6.0.1 without going to the alpha channel first (and then subsequently some quick bug fix releases in 6.0.2 & .3).

**Comment by ccrama** [comment]
Yep @abqnm, who needs testing when you have 30k testers in production :P

**Comment by abqnm** [comment]
@ccrama it was a fun one, that's for sure. Luckily @timawesomeness fixed the broken back button and search pretty quickly, so it didn't hurt too bad. 🤣
