### ISSUE TITLE
Unable to select Best as default post sorting in General→Sorting

### ISSUE THREAD

**Issue by fifty-50** [ccrama/Slide#2926]
Slide version: 6.0.1-3
Android version: 7.0

I can change it to any other option, but selecting Best does nothing.

**Comment by Tensounder54** [comment]
What device?
Are you signed in at the time that this issue occurs?
Are you using the version from FDroid or the Google Play Store?

**Comment by fifty-50** [comment]
Moto G4 Plus
Yes, I'm signed in
Play Store version

**Comment by Tensounder54** [comment]
OK thanks for the Bug report. @Alexendoo Could you mark this as a `bug` please?

**Comment by timawesomeness** [comment]
Best support wasn't properly finished - see #2867
