### ISSUE TITLE
Line breaks not showing properly

### ISSUE THREAD

**Issue by matty1086** [ccrama/Slide#2927]
Slide version: 6.0.1-3
Android version: 9 Pie - Pixel 3

Not sure if this is expected or not - it looks like line breaks in comments are not displayed properly in comment view but when I open the copy text dialog they are.

Possible to show the same line breaks in the comment threads?

Example comment:
https://reddit.com/r/mintsim/comments/6y0a46/data_not_working/dmjragx?context=3

Album:
https://imgur.com/a/oti8o0A

**Comment by timawesomeness** [comment]
That is working as intended. Line breaks in markdown have to be either two newlines, or two spaces and one newline, otherwise they are treated like a space. You can confirm that by visiting your link on the desktop site.
