### ISSUE TITLE
Slide's Inline YouTube Player not working

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide#2932]
Slide v6.0.1-3
Pixel 2 XL 9.0 (Nov security patch)

All videos are opening in the internal browser instead of opening inline. Reinstalling the Inline Player app doesn't affect anything. 

![](https://i.imgur.com/NVYKJVs.jpg)

**Comment by timawesomeness** [comment]
[It'll be fixed in the next update](https://github.com/ccrama/Slide/pull/2928)
