### ISSUE TITLE
Gold/Platinum/Silver on profile adds up when refreshed

### ISSUE THREAD

**Issue by y2kmurali** [ccrama/Slide#2933]
Slide version: 6.0.1-3
Android version: 9.0 on my Pixel 2 

Posting an issue from the [reddit ](https://www.reddit.com/r/slideforreddit/comments/a4m4ih/if_you_open_a_profile_to_view_a_comment_that_has/) for visibility. Basically, if there is only one gold/silver/platinum on a post, every time you refresh the user page another gold/silver/platinum gets added to the pile.

 I want to try to help fix the issue, I'm just having trouble locating the code where the golds are displayed.

**Comment by Tensounder54** [comment]
@timeawsomeness impemented that feature he should be able to help you.
