### ISSUE TITLE
Frontpage showing subs the user isn't subscribed to

### ISSUE THREAD

**Issue by reschandreas** [ccrama/Slide#2935]
Slide version: v6.0.1-3 
Android version: 8.1.0
Recently I noticed that I'm seeing subreddits on my frontpage where I'm not subscribed to and have never been subscribed to. 
Has anyone else noticed that or is it just me?

**Comment by timawesomeness** [comment]
Slide just shows the front page reddit sends it. If there's an issue like that it's probably on reddit's end.
