### ISSUE TITLE
V.reddit videos don't play in peek mode

### ISSUE THREAD

**Issue by canopeerus** [ccrama/Slide#2936]
Slide version:6.0.1-3
Android version:8.1.0

V.reddit links don't play in peek mode. Long pressing v.reddit links opens  the peak viewer but nothing plays on it  They play fine if you click on them normally.

**Comment by Tensounder54** [comment]
Could you answer the following questions for me as it will help us solve this issue faster. 
What device are you running Slide on?
Are you signed in at the time that this issue occurs?
Are you using the version of Slide from FDroid or the Google Play Store?

**Comment by Tensounder54** [comment]
Can confirm that this is a `bug`.
