### ISSUE TITLE
A better comment collapse

### ISSUE THREAD

**Issue by dessalines** [ccrama/Slide#2947]
When I want to collapse a comment tree, Im done not only reading its children, but the comment itself too. With slide, even though I collapse a comment, if it's a long one, I still have to scroll down a lot. 

Here's how comment collapse looks in boost, it's very compact. 

![](https://i.imgur.com/NyOYhmD.png)

**Comment by abqnm** [comment]
Go to Settings > Comments > Fully collapse comments (at the bottom) and enable it. Now comments will be very small just like that. Has been an option for as long as I can remember.

**Comment by dessalines** [comment]
Oh cool! This should probably be default behavior.

**Comment by abqnm** [comment]
It would be hard to switch the default, now. You would have equally as many people who dislike that change and want the original behavior. But that's why it's an option, in case you prefer the complete collapse.

**Comment by dessalines** [comment]
> You would have equally as many people who dislike that change and want the original behavior.

I found at least 10 defaults in slide were off the mark, it'd probably be good to have votes on these. Not knowing that these were configurable, when pretty much every other client had sensible defaults, was one of the things that kept me away from slide for a long time.

**Comment by timawesomeness** [comment]
> it'd probably be good to have votes on these

There actually was a poll on defaults a couple years ago, that's how some of the default settings came to be.
