### ISSUE TITLE
Notification still shows downloading image after download is complete

### ISSUE THREAD

**Issue by tnkrer** [ccrama/Slide#2957]
Slide version: 6.0.1-3
Android version: 9.0
Device: Galaxy Note 9

![screenshot](https://i.imgur.com/2EuUXSp.jpg)

**Comment by JuliusBrueggemann** [comment]
Hey, I know this issue is really old, but I want to try and track this bug down. I can't seem to reproduce this behavior though. Did you consistently experience this bug or did it only happen once?

**Comment by JuliusBrueggemann** [comment]
@ccrama 

```
latestPercentDone = (int) ((current / (float) total) * 100);
//Do every 30 percent
if (percentDone <= latestPercentDone + 30 || latestPercentDone == 100) {
    percentDone = latestPercentDone;
    mBuilder.setProgress(100, percentDone, false);
    mNotifyManager.notify(id, mBuilder.build());
}
```

This code seems wrong to me. If `latestPercentDone` is always the latest progress value, then shouldn't `percentDone <= latestPerdentDone` always return `true`?

I also suspect the call to `mNotifyManager.notify()` may run after the AsyncTask's `onPostExecute()` dismisses the notification, thereby sending a new notification that doesn't get dismissed.  
I'd have to take a deeper look at the code to confirm that suspicion though.
