### ISSUE TITLE
Upload app to F-droid

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#296]
Do you want to upload the app to f-droid?

Update (04/09): I'm working on some kind of different flavors for F-droid. A f-droid release is expected in the near future.

See: https://f-droid.org/forums/topic/slide-for-reddit/

**Comment by The0x539** [comment]
IIRC it's planned at some point, but undecided as to how Pro will work.

**Comment by ccrama** [comment]
^ yeah pretty much. I am still working it out

**Comment by skmlcd** [comment]
+1 for F-Droid.

**Comment by bishtawi** [comment]
+1. Would like to see this happen.

**Comment by l3d00m** [comment]
https://f-droid.org/forums/topic/slide-for-reddit/

**Comment by l3d00m** [comment]
Slide is now available on F-Droid! [Link](https://f-droid.org/app/me.ccrama.redditslide)
