### ISSUE TITLE
YouTube Plugin for slide does not work after update

### ISSUE THREAD

**Issue by sync-ware** [ccrama/Slide#2965]
Slide version: Slide v6.0.1-3
Android version: 9.0

After upgrading to One UI for the Samsung Galaxy S9, the plugin has appeared to stop working. Have tried reinstalling but that does not work. It just opens the YouTube page in the internal browser.

**Comment by incIined** [comment]
@timawesomeness any ETA when this update will be pushed? The same issue I had was closed awhile ago, but no update was present in the Play Store.

**Comment by retorquere** [comment]
Also curious about that update.

**Comment by Tensounder54** [comment]
It should be fixed and in the live build so I'm going to close this issue. If this is not the case then feel free to reopen it.

**Comment by retorquere** [comment]
It is not the case for me. Youtube videos do not open in the plugin (in fact I don't see the plugin handling anything at all)

**Comment by retorquere** [comment]
(I don't see an option to reopen, I might not have permission as I'm not the Op)

**Comment by retorquere** [comment]
It's still this right? https://play.google.com/store/apps/details?id=ccrama.me.slideyoutubeplugin for me that shows last updated in 2016

**Comment by timawesomeness** [comment]
An update containing the fix has not been released yet.

**Comment by retorquere** [comment]
So is there a time line for this being released?

**Comment by Tensounder54** [comment]
Not at the moment. I would have thought that we would have the changes out in the next 2 month or so, but I can't really say when that will be.
