### ISSUE TITLE
Videos cause slide to freeze

### ISSUE THREAD

**Issue by kuojo** [ccrama/Slide#2970]
Slide version: 6.0.1-3
Android version: 8.0

If I click on a video slide stops responding and I have to exit the app for it to start working again.

**Comment by timawesomeness** [comment]
Does this happen with every video, or just videos from a specific site? What device are you using?

**Comment by kuojo** [comment]
It did happen with every video. LG V30.  A restart on the device fixed this issue. I am going to close since it's related to my device and not the app.
