### ISSUE TITLE
Stopped working - 403 Error

### ISSUE THREAD

**Issue by bisam** [ccrama/Slide#2973]
Since today the app stopped working with only 403 errors. Did reddit change something?

**Comment by timawesomeness** [comment]
It happens occasionally. If the error persists (i.e. if reddit isn't having server issues), simply re-adding your account will fix it.

**Comment by bisam** [comment]
Weird. I changed to guest mode and switched back to my user. Started working again. Didnt need to readd it.

Should i leave this open as it seems to be a known bug?

**Comment by Tensounder54** [comment]
I'm going to close this issue as I think we have a number of issues in the tracker already that are covering 403 errors.
