### ISSUE TITLE
Unable to login with Javascript disabled in WebView

### ISSUE THREAD

**Issue by guixxx** [ccrama/Slide#2974]
Slide version: 6.0.1-3
Android version: 7.1.2

I've been trying to login into my account since yesterday but with no luck so far. So I tried to authenticate using my desktop's browser, with javascript disabled, and it didn't work either (Reddit doesn't ask for my 2FA code). This is the auth URL Slide uses, but it only works with javascript:

 https://www.reddit.com/login.compact?dest=https%3A%2F%2Fi.reddit.com%2Fapi%2Fv1%2Fauthorize.compact%3Fscope%3Didentity%2Bmodcontributors%2Bmodconfig%2Bmodothers%2Bmodwiki%2Bcreddits%2Blivemanage%2Baccount%2Bprivatemessages%2Bmodflair%2Bmodlog%2Breport%2Bmodposts%2Bmodwiki%2Bread%2Bvote%2Bedit%2Bsubmit%2Bsubscribe%2Bsave%2Bwikiread%2Bflair%2Bhistory%2Bmysubreddits%26response_type%3Dcode%26state%3D6tl3ecdgj0tjer5924pj6hn5h5%26redirect_uri%3Dhttp%253A%252F%252Fwww.ccrama.me%26client_id%3DKI2Nl9A_ouG9Qw%26duration%3Dpermanent

**Comment by Tensounder54** [comment]
Odd. Have you tried using this URL in a web browser?

**Comment by guixxx** [comment]
Yes, I did. Here are my findings:

First off, my Reddit account has 2FA authentication.

* After I click the "log in" button on the Reddit login page (using Slide + WebView), I'm redirected to the login page again (it was supposed to ask for my 2FA code).
* Using [this authentication URL](https://www.reddit.com/login.compact?dest=https%3A%2F%2Fi.reddit.com%2Fapi%2Fv1%2Fauthorize.compact%3Fscope%3Didentity%2Bmodcontributors%2Bmodconfig%2Bmodothers%2Bmodwiki%2Bcreddits%2Blivemanage%2Baccount%2Bprivatemessages%2Bmodflair%2Bmodlog%2Breport%2Bmodposts%2Bmodwiki%2Bread%2Bvote%2Bedit%2Bsubmit%2Bsubscribe%2Bsave%2Bwikiread%2Bflair%2Bhistory%2Bmysubreddits%26response_type%3Dcode%26state%3D6tl3ecdgj0tjer5924pj6hn5h5%26redirect_uri%3Dhttp%253A%252F%252Fwww.ccrama.me%26client_id%3DKI2Nl9A_ouG9Qw%26duration%3Dpermanent) on a desktop browser, **with javascript enabled**, works just fine, because Reddit (now?) uses [XHR](https://developer.mozilla.org/pt-BR/docs/Web/API/XMLHTTPRequest) in the login page, hence why it doesn't work properly when javascript is disabled.
* I am able to bypass this issue by appending `:my_2fa_code` in my password.

(Possible?) solution:

I'm not a Java programmer, nor did I test this, but wouldn't [enabling Javascript in WebView fix this](https://developer.android.com/guide/webapps/webview#EnablingJavaScript)?

**Comment by DidierLmn** [comment]
Slide version: 6.0.1-3
Android version: 9

I'm having this same issue, 2FA is also enabled on my Reddit account.

As described above,  through a web browser it's working, but through the webview it reloads the login page without asking for the 2FA code.

**Comment by MadFatVlad** [comment]
I found a solution described in Reddit Help! You should use 'password':'2fa code' instead of password

**Comment by ccrama** [comment]
2fa issue has been fixed for the next update, not sure there is a workaround for disabled JavaScript though because that is the only page for mobile auth through Reddit. I am planning on moving all login logic out of the app and letting the default browser handle this in a future update as well, which might change the constraints of this issue

**Comment by guixxx** [comment]
I've tried to login a few days ago using Slide, and now Reddit asks for 2FA code.

Closing :)
