### ISSUE TITLE
Having a very large filter list crashes the app when opening filter settings

### ISSUE THREAD

**Issue by Fredddi43** [ccrama/Slide#2975]
Slide version: 6.0.1-3 Fdroid
Android version: 8.1.0
 
I have a very large amount of subreddits filtered (300+) and while I previously could open the filter settings, it was just very slow, now it crashes completely. Which is very unfortunate, as I accidentally blocked imgur and would like to get it back. Issue occurs every time I try to access the filter settings.

**Comment by Tensounder54** [comment]
We can look into trying to speed up the loading time for this. If I'm honest, I don't know if the sub list is cached on Slide or if a request is made every time.

**Comment by Fredddi43** [comment]
Here's an export of my settings that might help reproduce the crash.

[Slide-2019-02-28-17-48-00.txt](https://github.com/ccrama/Slide/files/2915998/Slide-2019-02-28-17-48-00.txt)

**Comment by timawesomeness** [comment]
This was actually caused by one of the flairs you filtered containing a comma.
