### ISSUE TITLE
Unsubscribe subreddits still appearing on go to subreddit scroll list

### ISSUE THREAD

**Issue by Doomsdayrs** [ccrama/Slide#2976]
Slide version: 6.0.1-3
Android version: 9

As the title states, some subreddits appear even if I am unsubscribed to them.

**Comment by timawesomeness** [comment]
Are these subreddits you've unsubscribed to from Slide, or from the website? Slide has a "casual subscription" feature allowing you to have subreddits in your subreddit list that you aren't subscribed to, but might want quick access to. If you unsubscribe from a subreddit in Slide, it gives you the option to either unsubscribe, or both unsubscribe and remove it from the list; if you unsubscribe elsewhere it will remain in the list until removed manually or until subscriptions are synced in settings.

**Comment by Doomsdayrs** [comment]
That's the thing, when i readd it, then unsubscirbe and remove from list it stays there.
