### ISSUE TITLE
[Feature Request] PIN/Fingerprint security for Android client

### ISSUE THREAD

**Issue by PaxVobiscuit** [ccrama/Slide#2982]
Slide version: v6.0.1-3
Android version: 9

I came over from the IOS client where this is built in. Are there plans to put this on the Android client as well?

Specifically, requiring a PIN or Fingerprint when you open the app - either at first open, or when re-opening after backgrounding/closing. 

[Reddit thread](https://www.reddit.com/r/slideforreddit/comments/aw5i4x/resurfacing_pinfingerprint_security_for_android/)

**Comment by ShrutiRawal** [comment]
Hi @Tensounder54 @PaxVobiscuit is this issue still relevant? I would like to take this up. Maybe we can use the exiting device lock for opening the app.....

**Comment by PaxVobiscuit** [comment]
I'd still like to see it.

**Comment by TacoTheDank** [comment]
Closed in https://github.com/ccrama/Slide/pull/3411.
