### ISSUE TITLE
Clicking on post content freezes slide

### ISSUE THREAD

**Issue by netxecute** [ccrama/Slide#2989]
Slide version: 6.0.1-3
Android version: 8.0.0
Installed through FDroid

This only happened after my most recent Android update a few days ago.
Now when I click on gifs, videos, images - slide just hangs.
I can open a thread fine to see comments, it's just the content of the main post.

Please let me know any other details you need for troubleshooting.

**Comment by DarkLinkXXXX** [comment]
I can reproduce it. Haven't had an OS update recently.

**Comment by netxecute** [comment]
Can or can't?

What do you need from me to help figure it out? This is maybe not the best reddit app but I like fdroid + the 0 trackers listed on exodus 😉

**Comment by netxecute** [comment]
I don't think I'd rebooted my phone since the update. Rebooted last night and noticed the issue is gone.
