### ISSUE TITLE
[Question] Raddle support?

### ISSUE THREAD

**Issue by MegaArthur** [ccrama/Slide#2990]
With the fact that Reddit is becoming more and more like Facebook, a platform that takes subs down because of no reason/advertisers, would you be willing to support another Reddit-like platform, namely Raddle (raddle.me)? 

It has no android app as of yet so Slide could be the main one for that.

**Comment by Nxt3** [comment]
This issue is essentially asking the same thing as this issue: https://github.com/ccrama/Slide/issues/2823

It's incredibly unlikely since it would be a huge effort to support.
