### ISSUE TITLE
Slide for Saidit

### ISSUE THREAD

**Issue by exalented** [ccrama/Slide#2991]
This app is really amazing. Everything works exactly how one would expect. There's only one issue. Reddit is going downhill and I was wondering if you could make this client compatible with saidit.net?
Repo: https://github.com/libertysoft3/saidit

**Comment by Nxt3** [comment]
This issue is essentially asking the same thing as this issue: https://github.com/ccrama/Slide/issues/2823

It's incredibly unlikely since it would be a huge effort to support.
