### ISSUE TITLE
Give 'open externally' option when loading fails

### ISSUE THREAD

**Issue by TheWorstNL** [ccrama/Slide#2993]
Slide version: latest
Android version: pie

Gfycat seems to be having problems today and it returns a lot of 'GIF not found' errors. Instead of only having an 'OK' option add a 'Open externally' option because that usually still works. Now I have to open a submenu and choose open externally manually.

**Comment by Reixko** [comment]
Can I perhaps look into this and take this issue ?

**Comment by Alexendoo** [comment]
Sure thing @Reixko

**Comment by Reixko** [comment]
@ccrama can you please check my PR, or maybe @Alexendoo do you have permission for that too, please?
