### ISSUE TITLE
No visual touch overlay on buttons, navigation bar, or the toolbar


### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#3]
No visual touch overlay on any of the buttons or navigation menus. To enhance this, you could use this library for pre-Lollipop devices: https://github.com/balysv/material-ripple; it would add a nice ripple effect to touches.

**Comment by ccrama** [comment]
It's not as easy as just using that library for everything. I'm working on an implementation that works on both Lollipop and KitKat at the moment.

**Comment by alexsmithfanning** [comment]
Sorry. Didn't know it wasn't that easy.

Wait... Own implementation? Cool!

**Comment by ccrama** [comment]
Well I can't just wrap every view so I'm going to need to do something.

**Comment by ccrama** [comment]
Added with 0f227ac2ac9117b10fca4ec069a6395fcc777989!
