### ISSUE TITLE
Sorting multis is not possible

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#300]
1. Select multi   
2. Select sorting method other than hot  
3. Sorting method is still hot

**Comment by Alexendoo** [comment]
I have the same occurring, except it's for hot rather than top

**Comment by l3d00m** [comment]
That's what I meant too

**Comment by l3d00m** [comment]
Problem is still persisting with newest code

**Comment by ccrama** [comment]
Dupe of #303

**Comment by ccrama** [comment]
Whoops. Fixing now

**Comment by ccrama** [comment]
It's a bug with the API I'm using. Will be forking it and trying to fix it. Until then, marking as planned

**Comment by ccrama** [comment]
Raising the zombie! @thatJavaNerd , do you know if this is an issue with JRAW or my implementation of it?

**Comment by thatJavaNerd** [comment]
Where is the relevant code?

**Comment by l3d00m** [comment]
Sorry that I can't link directly, but the class name is 'CreateMulti.java' and the relevant code is near the bottom of that class.

**Comment by ccrama** [comment]
@thatJavaNerd Should all be here
https://github.com/ccrama/Slide/blob/master/app/src/main/java/me/ccrama/redditslide/Adapters/MultiredditPosts.java#L87

**Comment by ccrama** [comment]
Fixed! Was a small issue with JRAW @thatJavaNerd . I detailed the issue with a fix here https://github.com/thatJavaNerd/JRAW/issues/124

**Comment by ccrama** [comment]
Well that fixed sorting profiles, but not multis. Re-opening for now
