### ISSUE TITLE
401 errors

### ISSUE THREAD

**Issue by retorquere** [ccrama/Slide#3002]
Slide version: 6.2
Android version: pie

Since this morning I'm getting 401 errors in slide. Other reddit apps work without error.

**Comment by najodleglejszy** [comment]
I've been noticing the same thing. frequent 401 and 403 errors. force closing Slide and clearing its cache helps sometimes, but not always. I'm getting constant 401 errors right now and I'm unable to view any content, while Sync for Reddit displays everything fine.

**Comment by Tensounder54** [comment]
Please see #2604 for official answer and explanation.
