### ISSUE TITLE
Constant crashes when trying to check notifications 

### ISSUE THREAD

**Issue by 3drinks** [ccrama/Slide#3003]
Slide version: 6.1
Android version: pie, s8+

Notifications come to my device just fine but when I try to view profile or notification/messages I get a crash.

**Comment by 3drinks** [comment]
FWIW, I just signed out then signed back in on a hunch when I saw my feed wasn't my subscriptions. This worked to restore functionality. 

So it showed me logged in but it acted like I wasn't. I'd say this definitely isn't expected to behavior all the same.

**Comment by 3drinks** [comment]
FWIW, I just signed out then signed back in on a hunch when I saw my feed wasn't my subscriptions. This worked to restore functionality. 

So it showed me logged in but it acted like I wasn't. I'd say this definitely isn't expected to behavior all the same.

**Comment by Tensounder54** [comment]
Please ensure that you are using the latest version of Slide.

If you experience the issue again, could you get a bug report and/or a screen recording reproducing the issue?

**Comment by Tensounder54** [comment]
I'm going to close this issue as I think that it has been resolved by a later vertion of Slide. @3drinks If this is not the case then please let us know and it can be re-opened.
