### ISSUE TITLE
Night mode issues

### ISSUE THREAD

**Issue by derKief** [ccrama/Slide#3013]
Slide version: 6.0.1
Android version: 9.0 / MIUI 10

I'm not quite sure if its an app or ROM issue but Slide trigger ROM night mode to ON upon app start independent of app settings. It makes no difference if app night mode setting is ON or OFF.
This only happens with Slide so i assume its an app issue.

**Comment by timawesomeness** [comment]
It's a ROM issue, it affects any app that uses high color gamut mode. It was an issue with the Android 9 betas of both OnePlus' OxygenOS and Samsung's One UI.

**Comment by Tensounder54** [comment]
This issue has been resolved and needs to be closed.
