### ISSUE TITLE
getting error 403 everywhere

### ISSUE THREAD

**Issue by terminatorbs** [ccrama/Slide#3020]
Slide version: 6.2
Android version: 8.0.0 

Currently, reddit works in my browser, but the app does not load any posts and only gives error 403.

Feel free to ask me for any more details.

Update: It works again. Issue can be closed i guess

**Comment by Tensounder54** [comment]
What it means is that slide is having issues contacting reddit's servers. There isn't a whole lot we can do about it as its mainly a backend thing an we have no control over thatp

**Comment by Alexendoo** [comment]
403 means forbidden, generally meaning authentication failure. It's one case where it is in slide's court

**Comment by Tensounder54** [comment]
Sorry @terminatorbs I stand corrected.

**Comment by Tensounder54** [comment]
@alexendoo Aren't there already issues for this?

**Comment by Alexendoo** [comment]
Yeah I shouldn't have re-opened that, didn't see OP closed it. It's a longstanding issue (#2604) that seems to affect some more than others. Sadly I'd never been able to get into the state to debug it
