### ISSUE TITLE
Feed refreshes by itself after closing the content

### ISSUE THREAD

**Issue by haysebeyse** [ccrama/Slide#3022]
Slide version: v6.2
Android version: OxygenOS 9.0.5

Not always but quite frequently when I swipe away the content (e.g. image, gif etc.) to return where I was in the feed (e.g. front page), the feed automatically refreshes unintentionally and I lose where I left off.

**Comment by Tensounder54** [comment]
Could you give us a little more info on the make and model of your device? Also, are you using the F-Droid or Google Play Store release? I'm assuming it's F-Droid release judging by the OS.

**Comment by bisherbas** [comment]
Fdroid. OnePlus 5T stock but rooted with Magisk.

**Comment by Tensounder54** [comment]
So I've been unable to to reproduce this issue. I't could be to do with the fact that your not running stock android. Next time this happens could you take a bug report. Also, if it's at all possible could you capture a screen recording?

**Comment by haysebeyse** [comment]
Unable to reproduce. Switched device.
