### ISSUE TITLE
subreddit keyword filters not working? 

### ISSUE THREAD

**Issue by Zorks** [ccrama/Slide#3027]
Recently discovered Slide and was excited to find that you had implemented keyword filters for subreddits  but I can't seem to make it work.  Am I doing something incorrectly or misunderstanding how to use the filter system? 

![Screenshot_20190618-054018](https://user-images.githubusercontent.com/6314048/59683961-eb8fd900-918d-11e9-8176-eb8ff353802a.png)
![Screenshot_20190618-053921](https://user-images.githubusercontent.com/6314048/59683977-f34f7d80-918d-11e9-929e-48dce5b2937c.png)

Slide version: 6.2
Android version: 6.0.1

**Comment by timawesomeness** [comment]
It only uses an exact comparison; for it to filter /r/dankmemes, you'd have to type dankmemes into the filter.

**Comment by Zorks** [comment]
ah, [this reddit post](https://www.reddit.com/r/slideforreddit/comments/53uzn4/filter_syntax/d7whh9g/) by ccrama made it sound like partial matches were a thing.

**Comment by Tensounder54** [comment]
This issue has been resolved and needs to be closed.
