### ISSUE TITLE
Slide is crashing

### ISSUE THREAD

**Issue by dickyharper** [ccrama/Slide#3028]
Slide version:6.2
Android version:5.0.1

Slide is crashing all the time. Especially at discover and searching.

**Comment by expobar** [comment]
I seem to have triggered this bug as well.
To reproduce:
1. Head to r/amd
2. Search "RIP my FX-8150"...
3. I should end up to [this](https://www.reddit.com/r/Amd/comments/c5mzzk/rip_my_fx8150_you_will_be_missed_for_about_two/) but instead the app crashes.

 I've successfully replicated it in a different profile with fresh install of the app.

**Comment by MrJoshTheEpic** [comment]
having the same problem. also happens on [this post](https://redd.it/celw7y)
