### ISSUE TITLE
Make the Download button in image/video previews optional

### ISSUE THREAD

**Issue by nobodywasishere** [ccrama/Slide#3031]
Slide version: v6.2
Android version: 9.0

I constantly accidentally touch the download button in image previews and I think it would be a good idea to have this button be optional through a switch in the settings.

**Comment by Tensounder54** [comment]
This is something that we can look into but it is not a priority right now.

**Comment by Reixko** [comment]
Hello, can I perhaps work on this feature ?

**Comment by nobodywasishere** [comment]
Thank you @michaelPotter
