### ISSUE TITLE
CodeClimate code analysis results

### ISSUE THREAD

**Issue by Zhuinden** [ccrama/Slide#3033]
![Screenshot 2019-07-09 at 16 21 14](https://user-images.githubusercontent.com/11718392/60895955-c874b880-a265-11e9-8d38-d554342af05c.png)
![Screenshot 2019-07-09 at 16 21 41](https://user-images.githubusercontent.com/11718392/60895956-c874b880-a265-11e9-9ec8-42eae3472d59.png)
![Screenshot 2019-07-09 at 16 26 42](https://user-images.githubusercontent.com/11718392/60896780-38377300-a267-11e9-9f99-7d719e2f8892.png)
![Screenshot 2019-07-09 at 16 27 07](https://user-images.githubusercontent.com/11718392/60896781-38377300-a267-11e9-98a0-74a654ac8150.png)
![Screenshot 2019-07-09 at 16 34 58](https://user-images.githubusercontent.com/11718392/60896964-851b4980-a267-11e9-9481-b41d7cd615ac.png)

But code climate is free for all open-source repos, so you can try it yourself and see all issues rather than just the ones I took screenshots of.

I'm actually not affiliated with them, I just find the results interesting.

**Comment by Tensounder54** [comment]
What does it mean by:

> Method `doActions` has 430 lines of code (exceeds 25 allowed). Consider refactoring.

**Comment by Zhuinden** [comment]
It means that optimally, 1 method shouldn't be longer than 25 lines of code.

Although sometimes I violate that too, my repos seem to have some methods that are ~50 LOC (sometimes 80). Don't seem to have more than 100 in one method, though.

**Comment by Tensounder54** [comment]
We know about all this so I'm just going to close it.
