### ISSUE TITLE
[Feature Request] When saving pictures, automatically save the post title to the picture file name just like the RES extension.

### ISSUE THREAD

**Issue by xCapRx** [ccrama/Slide#3035]
Title pretty much says it all. I appreciate how this app automatically saves and organizes pictures into folders with the same names as the subreddits they're sourced from. However, it doesn't seem complete if the pictures aren't named after their parent submission titles. If a picture just has a random string of characters, a lot of **context** is lost. Also, it's a little more of a challenge to manually rename pictures on mobile than it is on desktop PC. 

Since this feature is already a reality in the [open source RES extension](https://github.com/honestbleeps/Reddit-Enhancement-Suite), could it be easily copied or adapted to the Slide app? 

Thanks for your consideration.

**Comment by Tensounder54** [comment]
I've been pushing for a certain amount of unification for a while now. Tis is something to add to the essay I'm writing on feature differences between Slide and RES. I'm hoping to have it done by Jan 2020 with a view to implement the majority of the features in 2020/Slide V2

**Comment by ccrama** [comment]
Fixed by #3297
