### ISSUE TITLE
Flickering when swiping back

### ISSUE THREAD

**Issue by nielmistry** [ccrama/Slide#3037]
Slide version: 6.2
Android version: 10 Beta 5 on Pixel 2
When I swipe back on a post, it flickers like this pretty much everytime. 

Repro steps:
1) open post from front page
2) swipe back
![Screenshot_20190716-103634](https://user-images.githubusercontent.com/10933146/61303502-99a29900-a7b5-11e9-86e3-f57de5b05d64.png)

**Comment by timawesomeness** [comment]
Hopefully it's just a developer preview bug that goes away by the time Q is released

**Comment by dpeukert** [comment]
Looks like this was fixed in Beta 6.

**Comment by Alexendoo** [comment]
That is relieving. Has it been fixed for you as well @nielmistry

**Comment by Alexendoo** [comment]
If it hasn't please re-open this issue (or create a new one). Thanks
