### ISSUE TITLE
Twitter links not opening

### ISSUE THREAD

**Issue by Gregaar** [ccrama/Slide#3043]
Slide version: 6.2.1
Android version: 8.0.0

When trying to open links to Twitter I get a wall of code like attached in the picture.
![Screenshot_20190729-204336_Slide](https://user-images.githubusercontent.com/26699321/62092021-a2797d00-b241-11e9-9728-b19130e99fd3.jpg)

**Comment by Tensounder54** [comment]
This issue has been resolved and needs to be closed.
