### ISSUE TITLE
fdroid version is outdated

### ISSUE THREAD

**Issue by DaleBCooper** [ccrama/Slide#3044]
The latest version on fdroid is 6.2
Looks like the meta data file does not get automatically updated.

https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/me.ccrama.redditslide.yml

AutoUpdateMode: Version %v
UpdateCheckMode: Tags
CurrentVersion: '6.2'
CurrentVersionCode: 319

**Comment by Alexendoo** [comment]
It should be handled when there's a new tag pushed (eventually), if it doesn't happen you can open an issue on the fdroiddata repo though

**Comment by DaleBCooper** [comment]
Thanks for the quick response.
I've opened an issue on fdroid data.
