### ISSUE TITLE
Opening subreddit link with query string and no trailing slash fails

### ISSUE THREAD

**Issue by ejhobbs** [ccrama/Slide#3047]
Slide version: 6.2
Android version: 9

**BUG**

When opening a subreddit URL, if the link contains any query string e.g. https://www.reddit.com/r/gifs?fakeQuery then the subreddit will load, but the app shows a failure message and does not allow you to view the subreddit. Suspiciously, this does _not_ happen when linking directly to a post, and appears to occur only when the URL does not have a final ```/```, e.g.:

https://reddit.com/r/gifs?queryString - FAIL
https://reddit.com/r/gifs/?queryString - PASS

**REPRODUCTION**

Allow Slide to open reddit URLs by default. Click a link to a subreddit (e.g. https://www.reddit.com/r/programming?utm_medium=android_app ). The subreddit will load but an error will show.

 **SCREENSHOT**

![Screenshot_20190807-130109_Slide](https://user-images.githubusercontent.com/24442248/62621307-7631c080-b913-11e9-82a5-f30686ce1b9e.png)

**Comment by Alexendoo** [comment]
I'll take a look at this
