### ISSUE TITLE
App crash when loading comments in post

### ISSUE THREAD

**Issue by z4rcher** [ccrama/Slide#3050]
Slide version: 6.2
Android version: 8.0

It appears some comments from this post causes app to crash and reload:

https://www.reddit.com/r/tennis/comments/cox4jm/match_thread_2_rafael_nadal_vs_8_daniil_medvedev/

**Comment by z4rcher** [comment]
Also crashes and resets base theme when loading some comments in this post:

https://www.reddit.com/r/tennis/comments/cp01iy/bianca_andreescu_wins_the_rogers_cup_after_serena/

**Comment by Trailhead-Jared** [comment]
https://www.reddit.com/r/mtgcube/comments/cpdzvz/my_deck_monday_8122019/

https://www.reddit.com/r/mtgcube/comments/codncc/versus_series_lightning_helix_vs_boros_charm/

For two more examples. It will load, and once you scroll to a problem comment, it will crash.

**Comment by Alexendoo** [comment]
Does it still crash on Slide 6.2.2 @z4rcher @Trailhead-Jared?

**Comment by Trailhead-Jared** [comment]
[Fix crash with weird redesign flairs #3038](https://github.com/ccrama/Slide/pull/3038) likely solved this problem. I am using the F-Droid repository, which does not seem to have 6.2.2 available yet.

**Comment by z4rcher** [comment]
Same here, can't test if the crash issues are fixed until F-Droid package gets updated.

**Comment by Alexendoo** [comment]
Ah I see, the metadata issue [got fixed recently](https://gitlab.com/fdroid/fdroiddata/issues/1718), so hopefully there will be a build available on f-droid soon

**Comment by Alexendoo** [comment]
https://www.reddit.com/r/slideforreddit/comments/ctx73d/the_latest_version_is_now_available_on_fdroid/
