### ISSUE TITLE
[EXTERN] When ist Media Gallery View coming to the iOS App?

### ISSUE THREAD

**Issue by superpower10** [ccrama/Slide#3055]
Slide version: 4.0 for iOS
Android version: 4.0 for iOS

The Original App has a Media Gallery View in Portrait Mode available which makes browsing through a subreddit extremly comfortable and fast.

When is this comming to the iOS App?

**Comment by Tensounder54** [comment]
Hi there @superpower10

This is the repository for the android version of Slide. Please direct issues associated with the iOS version of the app to the [Slide-iOS Issue Tracker](https://github.com/ccrama/Slide-iOS/issues).

Have an amazing day*!*

@Tensounder54
