### ISSUE TITLE
Flair filter force close

### ISSUE THREAD

**Issue by tynansdtm** [ccrama/Slide#3059]
Slide version: 6.2.2
Android version: 9

Setting flair filters causes the app to force close when pressing the enter key. Tried "2e" and "socks".

**Comment by Alexendoo** [comment]
Thanks for finding this @tynansdtm. I've PR'd a fix that would stop the crash

Flair filters wants the format to be `subreddit:flair`, e.g. `pics:socks`. When it didn't find that it crashed, whoops
