### ISSUE TITLE
Night mode turning off on opening a post

### ISSUE THREAD

**Issue by NijenhuisDevelopment** [ccrama/Slide#3065]
Slide version:Slide v6.2.2
Android version: 9.0.0

**Comment by Alexendoo** [comment]
Which night mode are you referring to @NijenhuisDevelopment, is it one set at the android level, or Slide's night mode?

**Comment by NijenhuisDevelopment** [comment]
It's on the Android level.
Oneplus 6 latest OTA

**Comment by Tensounder54** [comment]
@Alexendoo Would it be possible to wire Slides night mode into the Android night mode so when a user has nightmode enabled in android, it's enabled in slide by default?

**Comment by Alexendoo** [comment]
I'm sure it would be, though detecting versions of android where the setting is nonsense is a harder problem. (Like older stock androids)

If slide is disabling the system night mode however that's a much larger issue

**Comment by Valentin-N** [comment]
This seems to be related to https://github.com/ccrama/Slide/issues/2908 where [a potential fix](https://old.reddit.com/r/redditsync/comments/9ta7df/updated_my_oneplus_6_recently_opening_images/e8vxqyt/) was posted.
