### ISSUE TITLE
Search doesn't pick up nsfw posts

### ISSUE THREAD

**Issue by florensie** [ccrama/Slide#3072]
Slide version: 6.2.2
Android version: 9.0

When you search in slide it won't show any NSFW posts when it definitely should. My content settings allow NSFW posts and pictures.

**Comment by AWalton** [comment]
Yup I've found the same thing, just test the NSFW subreddit for example and nothing will load.

**Comment by Tensounder54** [comment]
If your not logged in and have you account set to allow NSFW content then you cannot view it through Slide. This is a deliberate choice in the Reddit API and there is no way around it. 

-------

I'm closing this issue as it has been resolved.

**Comment by florensie** [comment]
![Screenshot_20200211-091959_Fennec_F-Droid](https://user-images.githubusercontent.com/13403842/74220438-e862d380-4caf-11ea-950c-2f3acc9ce367.png)
It turned out to be the third option here.

**Comment by Tensounder54** [comment]
Yep, but the point remains that you have to be logged in to view NSFW content through the Reddit API.
