### ISSUE TITLE
Slide crashes when clicking image of certain post

### ISSUE THREAD

**Issue by Holzhaus** [ccrama/Slide#3076]
Slide version: 6.2.2
Android version: 9 (Huawei P30) 

Slide crashes when I click on the image of this post:
https://www.reddit.com/r/gaming/comments/ddzc08/uzevediah_knows_whats_up/

This does not happen for other posts.

**Comment by Tensounder54** [comment]
This issue is resolved in the latest version of Slide and as such has been closed.
