### ISSUE TITLE
"archived post" note is to big, reaches over the post

### ISSUE THREAD

**Issue by castilma** [ccrama/Slide#3079]
Slide version 6.2.2
Android version: 9

Title.

I cannot scroll further up. The post title is unreadable.

![Screenshot_20191013-131351_Slide](https://user-images.githubusercontent.com/17392981/66714869-ea716000-edab-11e9-8e6d-e77519cff58d.jpg)

**Comment by goforbg** [comment]
@Alexendoo has this been fixed? Unable to reproduce in latest build

**Comment by castilma** [comment]
I still have the problem on 9.3.

[test page](https://www.reddit.com/r/AmItheAsshole/comments/aw4ci0/aita_for_rejecting_a_girl_as_revenge/)
