### ISSUE TITLE
Videos in Shadowbox mode autoplay with audio when not the focus

### ISSUE THREAD

**Issue by Zak-Bahm** [ccrama/Slide#3083]
## Version Info
Slide v6.2.2

Android 9, 8

## Description
When viewing a subreddit that has multiple reddit videos in Shadowbox mode, videos play with audio as soon as they are loaded. This can result in audio from 2 videos; the active one on screen and the next one that has finished loading, playing at the same time.

## Steps to Replicate
1. Go to a subreddit with a lot of reddit video posts
1. Enter Shadowbox mode
1. Swipe left until you get a post with Reddit video
1. If it sounds like multiple videos are playing at the same time, pause the active one to verify

**Comment by rakshazi** [comment]
Hello!
Any update on this?

**Comment by timawesomeness** [comment]
If #3209 doesn't fix this, let me know
