### ISSUE TITLE
Add an option to select text directly

### ISSUE THREAD

**Issue by smnthermes** [ccrama/Slide#3090]
When a comment is too long, it's harder to find the part to select text with the "copy text" command.

**Comment by underlineGalaxy** [comment]
Cant you do this already? Choosing copy comment displays the whole comment and you can select what to copy.

**Comment by harshlele** [comment]
Can we do something like this - 
long pressing on the comment lets you select the text, while short press shows the upvote/downvote/menu buttons 

(I can make the PR)

**Comment by Tensounder54** [comment]
Hi there! As @RenatoLopes771 pointed out, this already exists in Slide. So I'm going to close this issue. Have a great day!
> ↳T*54*
