### ISSUE TITLE
In the comment section. The bar that shows points and comments. The word 'comments' is very weird

### ISSUE THREAD

**Issue by Revel1020** [ccrama/Slide#31]
It keeps aligning itself in weird ways. One post had a weird spacing between the image and the title of the post. (I'll post screenshots on Google+).

**Comment by Alexendoo** [comment]
For reference https://plus.google.com/+WaleedRostom/posts/3sXt8T7CcX1

**Comment by ccrama** [comment]
Fixed with 85fb67c73a8fb0d4d3aea2da27ddc44867924ca4. Now uses a FlowLayout instead of LinearLayout in submission_fullscreen.xml
