### ISSUE TITLE
Opening "Link handling" or trying to search Settings when multiple browsers with the same name are installed causes crash

### ISSUE THREAD

**Issue by BeeeWall** [ccrama/Slide#3124]
Slide version: 6.2.2
Android version: 10
Logcat (Link handling): https://pastebin.com/raw/DAfSypZc
Logcat (Search): https://pastebin.com/raw/vUYCChay

Steps to reproduce:
1. Install Slide
2. Open Slide and navigate to Link handling (or try to search anything in the Settings page) It should work fine. 
3. Install [Firefox Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fennec_aurora) 
4. Install [Firefox Preview Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix.nightly) (when installed, this is also named Firefox Nightly)
5. Open Slide and navigate to Link handling (or search settings) again. It should crash.
6. Uninstall either browser (or both, but only need to remove one)
7. Open Link handling or search one last time. It should work again. 

For settings search: the search bar can be opened, but typing anything crashes. For link handling, it crashes immediately when you open it.

**Comment by Alexendoo** [comment]
Thanks for the clear issue @BeeeWall, submitted a PR to fix it
