### ISSUE TITLE
Privacy question

### ISSUE THREAD

**Issue by omicron-b** [ccrama/Slide#3129]
Hello!
I am starting to get into "privacy" thing and, as part of that process, switched to an open source Reddit client - Slide.
This is where I thank you for a great app :)

I would like to understand why the app needs to communicate to www.ccrama.me and ccrama.me
For example here:
https://github.com/ccrama/Slide/blob/59036f64480a3b8ed8ccf611181d9fe3b1a7886b/app/src/main/java/me/ccrama/redditslide/Activities/Login.java#L50-L52

And here:
https://github.com/ccrama/Slide/blob/59036f64480a3b8ed8ccf611181d9fe3b1a7886b/app/src/main/java/me/ccrama/redditslide/Reddit.java#L160-L163

I tried blocking those URLs via my DNS resolver and it did not *seem* to break anything (while the requests did happen and failed) but I am probably missing something.

**Comment by Alexendoo** [comment]
Good question! For Login.java it's part of [the OAuth registration process](https://github.com/reddit-archive/reddit/wiki/oauth2).

To log in to the app it opens a webview to a reddit's login page. The callback is how Slide gets the resulting token back from the page - when finished it issues a redirect to `http://www.ccrama.me?code=something...`. Slide picks up on this redirect without actually making any requests

In Reddit.java it is being used as to find any apps that are able to handle the ACTION_VIEW intent (web browsers). Here it's a stand in for any arbitrary URL, it's querying Android to find which applications could open the intent without actually firing it. The result is used for the setting in link handling to set a specific browser

**Comment by Alexendoo** [comment]
Ah though I just read the question again and you mention the request is actually sent. Is that in the registration case? If so that should be fixable

**Comment by omicron-b** [comment]
Thanks a lot, now it is clear to me!
Sorry, by "requests did happen" I meant requests to DNS resolver. I did not check for an actual HTTP(S) request and have no reason to believe that was the case, so I am closing this issue.
