### ISSUE TITLE
Screen Rotate Deletes Comment In Progress

### ISSUE THREAD

**Issue by grravity** [ccrama/Slide#3133]
When typing a comment (I assume the issue might occur when making a post as well, haven't tested) and you tilt the device and the screen rotates, it basically deletes everything you just wrote if it wasn't submitted. Just lost so much text due to accidentally rotating my device. Tested it again by just typing test and intentionally rotating, and can confirm that rotating it removed the text. Seems to refresh that view or something.

Slide version: 6.2.2 (F-Droid)
Android version: Android 9, LGv40

**Comment by Archeidos** [comment]
Was this issue resolved? This issue is not present for me on API 28 / Nexus 5

**Comment by grravity** [comment]
> 
> 
> Was this issue resolved? This issue is not present for me on API 28 / Nexus 5

Seems like it might be working now.
