### ISSUE TITLE
Add visual hint that reply formatting bar is scrollable?

### ISSUE THREAD

**Issue by elfez** [ccrama/Slide#3140]
Slide version: 6.3
Android version: 9

After using Slide for a couple of years or so I only learnt yesterday that the formatting bar when replying to a post can be scrolled horizontally to reveal more icons. Another long time user also commented on this. So would it be worth adding some form of visual hint that the bar is scrollable? Perhaps a gradient with transparency at the end of the bar?

**Comment by goforbg** [comment]
This has been fixed I believe, there's now a grey bar that indicates there are more icons to the right.
