### ISSUE TITLE
Copycat on Google Play

### ISSUE THREAD

**Issue by Poussinou** [ccrama/Slide#3153]
Hi @ccrama 

I found this app: https://play.google.com/store/apps/details?id=reddit.isfun.reddit.app.reddit.video.downloader.earn.cash on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove this copy from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPL v3 license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your own app and a link to it.

**Comment by Alexendoo** [comment]
Good find @Poussinou

**Comment by ccrama** [comment]
Thank you for the heads up @Poussinou ! I've reported it to Google, I'll update this issue if I hear anything further

**Comment by Alexendoo** [comment]
It got taken down
