### ISSUE TITLE
Date in archived posts not readable

### ISSUE THREAD

**Issue by MaggiWuerze** [ccrama/Slide#3160]
In archived post the time indicator on posts and comments is replaced by an 'a' instead of the regular one for year, month and so on. This makes it impossible to know how old/relevant a post or comment is.
![](https://i.imgur.com/Al1l8d9.jpg)

**Comment by goforbg** [comment]
Yeah I think it's restricted to German.

 The time_year_short is mentioned as %da instead of %dy in a lot of these languages, if someone who knows German can back me up on this, it's pretty easy to fix.

Also if we used the time_year_long which reads something like "3 years ago" I think the UI wouldn't be nice and that's why it's written like this?

**Comment by Alexendoo** [comment]
Yeah they're intended to be short else they don't really fit on screen that well.

Good catch that it's because of translations, in that case the place to go to fix this would be our crowdin page - https://crowdin.com/project/slide-for-reddit if anybody knows what it ought to be in German

**Comment by MaggiWuerze** [comment]
> Yeah I think it's restricted to German.
> 
> The time_year_short is mentioned as %da instead of %dy in a lot of these languages, if someone who knows German can back me up on this, it's pretty easy to fix.
> 
> Also if we used the time_year_long which reads something like "3 years ago" I think the UI wouldn't be nice and that's why it's written like this?

If you tell me what you need i can surely help you. Native German speaker here, if you hadn't already guessed.

**Comment by MaggiWuerze** [comment]
seems to be this one:
https://crowdin.com/translate/slide-for-reddit/2/en-de#q=%25da
there is already one that seems correct and should be used instead (%dj)

**Comment by Alexendoo** [comment]
Great, the voting changed the accepted translation to be `%dj`, the updated translations now include that - e6cf6ceb0e0f32f9c87cf323ba50179bec00980d

Thanks for your help @MaggiWuerze
