### ISSUE TITLE
GIFs from redgifs.com are not recognized

### ISSUE THREAD

**Issue by rEnr3n** [ccrama/Slide#3165]
Slide version: 6.3
Android version: 6.0.1

Redgifs links should be recognized as GIF instead of a link.

Example: **NSFW** https://www.reddit.com/r/redgifs/comments/gfvw9v/redgifs_links_on_reddit_see_comment/

**Comment by paulpark03** [comment]
Duplicate of #3169 
Sorry. I didn't check this before I created a new pull request.

**Comment by MetalNeo** [comment]
After updating to 6.6, redgifs gifs are not being recognized again.

**Comment by MetalNeo** [comment]
False alarm. The WiFi network I normally use started blocking redgifs the same time I updated. Issue can be closed.
