### ISSUE TITLE
F-Droid still has v6.3

### ISSUE THREAD

**Issue by mark05e** [ccrama/Slide#3171]
Slide version: 6.3
Android version: 9

Just wanted to know if v6.4 has been pushed to [F-Droid](https://f-droid.org/packages/me.ccrama.redditslide/) also?

![image](https://user-images.githubusercontent.com/1783193/82893263-68f4c980-9f59-11ea-912f-c0067a2da1c6.png)

**Comment by Tensounder54** [comment]
Yeah, it takes a few days to come through when it gets sent off to them. Not sure if @ccrama has sent it off yet but if we assume that he has the it's likely that it would be there by Friday. No  guarantees though.

**Comment by rakshazi** [comment]
Hello, F-droid still has only 6.3
