### ISSUE TITLE
Gfycat links are not working

### ISSUE THREAD

**Issue by Salman7236** [ccrama/Slide#3172]
Slide version: 6.4
Android version: 10
![Screenshot_20200528_064143_me ccrama redditslide](https://user-images.githubusercontent.com/64946014/83088877-61930480-a0ae-11ea-85d6-0144cb044f0e.jpg)

**Comment by Lokawn** [comment]
Maybe because you have Airplane mode on, all sites are working for me with the latest update.

**Comment by Salman7236** [comment]
I tried it with airplane mode off. But it's still not working. I tried it with a bunch of gifs and looks like it only shows this error when playing gifs that were uploaded a few months ago. But the problem is that boost for reddit is still able to play them.

**Comment by soren121** [comment]
The missing piece of this puzzle is that the Gfycat links that don't work are the NSFW Gfycats which now redirect to Redgifs.

The Reddit Preview feature doesn't work with these links, so Slide doesn't either.

**Comment by felipe19930** [comment]
Can confirm what @soren121 said. Here's a gfycat.com link that redirects to gifdeliverynetwork.com (RedGifs):

[NSFW, but there's actually no nudity](https://gfycat.com/inexperienceddigitalarrowana)

**Comment by Salman7236** [comment]
Understood. Thanks for the help guys.

**Comment by soren121** [comment]
To be clear, this is still a bug that needs fixing! You should reopen this issue.
