### ISSUE TITLE
I can't log in with Slide

### ISSUE THREAD

**Issue by dickyharper** [ccrama/Slide#3173]
Slide version:6.4 (GP)
Android version:5.0.1
I delete the appdata. Now;

It says that my password is wrong when logging in with Slide.  I verified that my password is correct with two different browsers.

**Comment by moving48119** [comment]
If you have 2FA, you need to type this at the end of your password ":CODE".

Example:
MyPassword123:9718

Hope it helps!

**Comment by dickyharper** [comment]
> If you have 2FA, you need to type this at the end of your password ":CODE".
> 
> Example:
> MyPassword123:9718
> 
> Hope it helps!

So far I have never used the 2fa feature.  nowhere

**Comment by Lokawn** [comment]
> If you have 2FA, you need to type this at the end of your password ":CODE".
> 
> Example:
> MyPassword123:9718
> 
> Hope it helps!

I have 2FA enabled and while logging in reddit asks me to supply the code seperately.

**Comment by promi404** [comment]
Same here. It says my password is incorrect and i don't use 2FA.
First install, i just discovered the app.
Slide version: 6.3 from F-Droid app
Android version: 4.4.2

**Comment by aliPMPAINT** [comment]
Same here. It says my password is incorrect(though it did work on browsers) and I don't use 2FA.
First install.
Slide version: 6.5 from F-Droid app
Android version: 6.0.1
