### ISSUE TITLE
Offline mode of death

### ISSUE THREAD

**Issue by sknorr-prv** [ccrama/Slide#3199]
Slide version: 6.4
Android version: 9

0. Make a Slide backup, if your Slide data is important to you.
1. Delete all the offline-cached data (via the sidebar > manage offline content > click all the little X's next to sub names).
2. Go into offline mode.

Result: Slide will consistently crash when starting. I have had two delete all my Slide user data twice because of this bug now, so I'd say this is moderately annoying.

**Comment by timawesomeness** [comment]
It should just pop up with ![this](https://user-images.githubusercontent.com/1624152/86399431-7e4dc980-bc64-11ea-99b0-a41d60b23821.png)

**Comment by sknorr-prv** [comment]
You're right, with default settings, this message appears. This issue only appears when enabling a different subreddit search mode in the options, "Long-press on the toolbar title".

**Comment by sknorr-prv** [comment]
Haven't tested but thank you for the quick fix!
