### ISSUE TITLE
'Search for a subreddit' opens a new view despite being subscribed to a sub

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#32]
Pressing android's equivalent of 'enter' via the keyboard rather than tapping on the subreddit name (underneath the search field) will open a new view on top, rather than scrolling you to the subreddit in the main view.

**Comment by ccrama** [comment]
This is more of a non issue, I think. The user can click the relevant sub below instead of clicking the search button. I've added in a "Go to ____" option as well to make this system a little less confusing! I think this was added in 7f3bae7e1f26aa7f2d17754a9d864bdf8266860f
