### ISSUE TITLE
Various bugs 

### ISSUE THREAD

**Issue by Pacogens** [ccrama/Slide#320]
Pull to refresh make the app crash.
 
Infinte scroll doesn't work. 

When I try to sign in from the in-app GitHub report it crash.

**Comment by ccrama** [comment]
Fixed 1 & 2 with 69c0ef81c58fe5bd14530264604e9f9ec0e36bca

**Comment by ccrama** [comment]
Do you have 2 factor auth on Github by chance?

**Comment by Pacogens** [comment]
No, only username and password

**Comment by ccrama** [comment]
Hmm, strange. It is probably a bug with the library I'm using :(

**Comment by Alexendoo** [comment]
Should no longer matter due to the autoreporter being removed
