### ISSUE TITLE
All posts are cleared when scrolling with a bad connection

### ISSUE THREAD

**Issue by Isaacntk** [ccrama/Slide#3201]
Slide version: v6.4
Android version: 10

On poor cellular data connections or if the app loaded a bunch of posts on WiFi and you disconnect, the app doesn't transition into offline mode and scrolling for new posts causes a "Loading failed, please check your connection" error message while dropping all posts previously loaded.

Pretty annoying on spotty cellular coverage as you need to reload all posts and scroll all the way down again

I've had this issue for a while now, probably over a year, but finally took the time to find a reliable way of reproducing it:
1. Open app and load a few posts
2. Minimize app, return to home screen or another app
3. Disconnect your WiFi and/or mobile data
4. Return to app and scroll to the end for new posts

![Screen_Recording_20200613-143624_1](https://user-images.githubusercontent.com/1376191/86515646-a8f67880-be44-11ea-9ed5-15a688c2259f.gif)

**Comment by timawesomeness** [comment]
Fixed by #3183
