### ISSUE TITLE
Some v.redd.it videos open without sound

### ISSUE THREAD

**Issue by berkleycameron** [ccrama/Slide#3204]
Slide version: 6.4
Android version: 9

Some videos uploaded to v.redd.it are playing without sound. The affected videos are seemingly random. A large number of people are affected judging by this thread: https://www.reddit.com/r/slideforreddit/comments/hizr86/no_audio_for_some_vreddit_videos/

Two affected videos:
https://www.reddit.com/r/PublicFreakout/comments/hlqguz/drunk_florida_man_trumper_chasing_the_grim_reaper/

https://www.reddit.com/r/PublicFreakout/comments/hlsl2l/woman_gives_oral_sex_to_a_demon_in_church/

Two working videos:
https://www.reddit.com/r/PublicFreakout/comments/hlmusu/jacked_70_year_old_man_gets_roidroad_rage/

https://www.reddit.com/r/PublicFreakout/comments/hlpfyj/karen_goes_to_hospital_because_of_her_broken/

**Comment by Tensounder54** [comment]
Hmmm. I've not seen this one before. Could you give me a bug report next time it happens. That way one of us can look into it.

**Comment by jpstach** [comment]
I have the same issue. How do I create a bug report? The report bugs option in the settings takes you to GitHub. A bunch of people on the slide for reddit sub have the same issue. https://www.reddit.com/r/slideforreddit/comments/hizr86/no_audio_for_some_vreddit_videos/

**Comment by Ullas-Aithal** [comment]
I've attached the logcat I took before starting the video. 

Source: https://www.reddit.com/r/maybemaybemaybe/comments/hmpcni/maybe_maybe_maybe/

Let me know if you need any other details. 
[slide_video_no_audio_bug.txt](https://github.com/ccrama/Slide/files/4886192/slide_video_no_audio_bug.txt)

**Comment by LiquidZer0** [comment]
Same for me. Random videos have no sound. 

Android 9, Slide 6.4

I noticed that the Slide for Reddit Video plugin hasn't had an update since December 11, 2016... Perhaps we could start there. It's detailed as version 2.5 in the Play store.

**Comment by Queuecumbr** [comment]
I am also affected by this issue too so this issue may not be resolved still. I'm using a Pixel 3 XL on Android 10.

**Comment by Alexendoo** [comment]
On Slide 6.5 @Queuecumbr?

**Comment by Queuecumbr** [comment]
Looks like I'm still on 6.4 since that's the latest one available through F-Droid
