### ISSUE TITLE
Slide does not update on F-Droid automatically

### ISSUE THREAD

**Issue by obar** [ccrama/Slide#3205]
With [some more metadata](https://gitlab.com/snippets/1895688) in the repo, F-Droid will automatically build new releases. Pull request incoming.

Thanks for the best Android Reddit client!

**Comment by obar** [comment]
Looks like it mostly worked… the latest update was caught but a config change needs to happen in fdroid for the build to happen, in the end of [this file](https://gitlab.com/fdroid/fdroiddata/-/blob/3c447a86a4657303c9389ef6dbcb8608d38f9fd8/metadata/me.ccrama.redditslide.yml#L589):

``` diff
- AutoUpdateMode: None
+ AutoUpdateMode: Version %v
```

**Comment by ccrama** [comment]
@obar what steps do we need to take to fix the current build? It shows that it found the latest update, but the build process is not started yet

**Comment by obar** [comment]
I submitted [a fix for both points](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7114), I think it should do the trick. Just needs to be merged.
