### ISSUE TITLE
Server Error 403

### ISSUE THREAD

**Issue by FOSS4TW** [ccrama/Slide#3236]
Hey all, not sure if this is the best forum but for the past few days I keep getting a toast notification "A server error occurred, 403". Network settings don't seem to have any effect and I'm able to access reddit through the browser. I'm on version 6.4 and I saw on the subreddit 6.5 should be coming soon so this issue may already be fixed once I get the update.

**Comment by Tensounder54** [comment]
Hi there! This issue is a server issue on Reddit's end that we can't really do anything about. The work around for this is to `Force Stop` the app in your phone's settings.

**Comment by Tensounder54** [comment]
Closing as this issue has been resolved.
