### ISSUE TITLE
Unable to set youtube.com to open in external browser

### ISSUE THREAD

**Issue by Xaymar** [ccrama/Slide#3242]
Slide version: Version 6.5
Android version: 10

Attempting to click a youtube link opens it in the embedded player, which fails to play it. As i don't want this integration, and don't need it, i tried removing it with the "Open in external Browser" option, but that seems to disallow "youtube.com" from being added at all. Other domains work fine. 

As far as i can tell, there is no option to even disable this broken behavior in the first place. YouTube is not an image, a GIF, or an album, and yet it acts like one in Slide. 

##### Media
![IMG_20200728_132240](https://user-images.githubusercontent.com/437395/88659710-c92cf680-d0d5-11ea-8a81-4a48020b5926.jpg)
![Screenshot_20200728-132857_Slide](https://user-images.githubusercontent.com/437395/88660041-4e181000-d0d6-11ea-9a7e-e462882e7435.png)

**Comment by Alexendoo** [comment]
Do you have the [video plugin](https://play.google.com/store/apps/details?id=ccrama.me.slideyoutubeplugin) installed? It is a bug that the player fails to load, however in the meanwhile you could uninstall the video plugin if you want youtube to open externally

**Comment by Xaymar** [comment]
No, I do not. Should I install it?

**Comment by Alexendoo** [comment]
Oh odd, I didn't think youtube opened embedded unless it was installed. I'll take a look at this

**Comment by Alexendoo** [comment]
Do all youtube videos trigger this issue? e.g. the ones just on /r/videos or is it only for specific ones

**Comment by Xaymar** [comment]
For me it is all of them. I have not found a way to make it not do that yet. Even forcing Slide to run as root has made no difference. Here's some additional system information in case it helps:

- Lineage OS (2020-08-03T11-28-44)
- Dual SIM (both active)
- Rooted with Magisk & XPosed
- XPrivacy to prevent private-data-vacuums from doing their work.

**Comment by Alexendoo** [comment]
Aha, I think it might be due to XPrivacy. In your original screenshot the "Download the Slide Video plugin" link is hidden, it only gets hidden when Slide thinks the video player is installed, which it determines by querying for the package. If XPrivacy returned a fake response here saying it is installed that would explain the breakage (Slide always tries to open youtube internally if it thinks the video player is installed)

Could you test with slide exempted from anything like that?

**Comment by Xaymar** [comment]
Exempting Slide from that fixes it. Thanks for the help! :+1:
