### ISSUE TITLE
Send PM option shows up even when not logged in

### ISSUE THREAD

**Issue by karlding** [ccrama/Slide#327]
When a user isn't logged in, and taps on the information icon on a user's Profile, the option to send a Private Message shows up. Tapping this brings up the Private Message form (which they can fill out), but hitting send will not actually do anything.

Obviously, you can't send a Private Message when you aren't logged in, but in this case, in terms of UX, I don't think this form should even show up.

**Comment by ccrama** [comment]
Good find! Will remove

**Comment by ccrama** [comment]
Done d81fbcebad5a9111dab93be9c1285277fbc53d9d
