### ISSUE TITLE
Slide use clipboard in iOS14

### ISSUE THREAD

**Issue by jarekpelczynski** [ccrama/Slide#3278]
When I back from a post to a list, Slide use clipboard and iOS shows a notification. Is it normal behavior?

![image](https://user-images.githubusercontent.com/1881800/95691591-694be380-0c20-11eb-9808-236956964ba6.png)

**Comment by Alexendoo** [comment]
Yeah this is expected, you subscribe to this issue https://github.com/ccrama/Slide-iOS/issues/1063

Details about why it's happening here: https://www.reddit.com/r/slide_ios/comments/isjqfi/question_slide_automatically_pasting_from/g59kmkb/
