### ISSUE TITLE
Blank sidebar and subreddits

### ISSUE THREAD

**Issue by c727** [ccrama/Slide#331]
info: my device has only 1GB ram

How to force this bug:
-open slide
-press homebutton
-open ~5 'big' apps
-go back to slide

**Comment by c727** [comment]
http://abload.de/img/screenshot_2015-11-016vssg.png

**Comment by alexsmithfanning** [comment]
Possibly related to #239?

**Comment by ccrama** [comment]
Possibly, but it should be merged with #306 as it fits in with the general "connection" bugs

**Comment by l3d00m** [comment]
Dupe of #65, it happens too with my better specs g2.

**Comment by ccrama** [comment]
Happens on my 4gb RAM note 5 as well :c

**Comment by ccrama** [comment]
Merging with #67
