### ISSUE TITLE
Unable to locate 'Read Later'

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [ccrama/Slide#3314]
Hi first of all i just wanted to say that I'm using the App for a while now and i totally love it. 

Yesterday i saved a post because i wanted to read it later. I looked everywhere in the app but i don't see any sort of Read Later section.

I'm using the latest version of the app that is available in f-droid and i use the Quest profile within the app.

**Comment by eredrolo** [comment]
Press the arrow beside "You" in the sidebar.

<a href="https://user-images.githubusercontent.com/74611933/104344546-497bd280-5523-11eb-9b3c-e7fb0aee44a0.jpeg"><img src="https://user-images.githubusercontent.com/74611933/104344546-497bd280-5523-11eb-9b3c-e7fb0aee44a0.jpeg" height="640" width="360" ></a>

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I dont have that in my sidebar.

**Comment by eredrolo** [comment]
Looks like it is only accessible if you sign into Reddit. But I think Read Later is a Slide feature so you should edit this issue or create a new one asking for the feature to access Read Later for guest accounts.
