### ISSUE TITLE
Please consider using UnifiedPush for push notifications

### ISSUE THREAD

**Issue by emorrp1** [ccrama/Slide#3330]
Slide version: f-droid
Android version: oreo

I would like to be able to use android without google services and get native notifications for comment replies etc. Currently notifications must use FCM unless each app developer hosts a notification gateway which drains battery. I suggest using [UnifiedPush](https://unifiedpush.org/), the community successor to [OpenPush](https://bubu1.eu/openpush/). Although UnifiedPush is brand new, I'm not aware of any other app-independent implementation. 

I believe the technical approach would be to use the "FCM-added" form of the UnifiedPush [android-connector](https://unifiedpush.org/developers/android/) library so that users who don't care about the minimal FCM data can continue to use it as before and f-droid can just build with the no FCM version. The only currently available UnifiedPush app is FluffyChat, implemented in [lib/utils/firebase_controller.dart](https://gitlab.com/famedly/fluffychat/-/commit/124a5eedf84854f4dcbbf7b9dc2a4a5ea2387f5a?view=parallel).

**Comment by emorrp1** [comment]
I've thought about it a bit more and think that Slide isn't using push notifications, just ordinary notifications from polling the reddit API? Sorry for the noise, I'll close this on that assumption, though it would be an interesting side project to host a reddit push gateway that Slide could then use.

**Comment by Alexendoo** [comment]
Yeah they work by either polling the reddit API every so often, or there's also a feature to piggyback on the official reddit apps notifications if it's installed

Getting regular push notifications would be a good challenge, I don't know if there's any interface reddit exposes (public or not) that could be utilised to get them without requiring a server that has full access to the users reddit inbox
