### ISSUE TITLE
This specific reddit gallery link crashes Slide. Works on the mobile website

### ISSUE THREAD

**Issue by IceCloud76** [ccrama/Slide#3343]
Slide version: 6.6.1-3
Android version: 9

Link:  
https://www.reddit.com/gallery/lp48pp

Not sure why this crashes Slide. All other reddit galleries I've tried load just fine. I can load the post with comments, but clicking on the button to load the images crashes Slide

**Comment by Aimhere2k** [comment]
Slide 6.6.1-4
Android version 10

I occasionally see gallery links crash Slide as well. For example,

[https://www.reddit.com/gallery/m895u8](url)

**Comment by TacoTheDank** [comment]
Duplicate of https://github.com/ccrama/Slide/issues/3313. Thanks for reporting though!
