### ISSUE TITLE
Comment alignment issues

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#335]
It's too hard to explain so I'll just give you the link to the screenshot I took: https://goo.gl/vYEZzw

**Comment by ccrama** [comment]
Interesting. Might be a KK issue so looking into it!

**Comment by ccrama** [comment]
Do you still have this issue?

**Comment by alexsmithfanning** [comment]
I haven't seen it since the 4.5 update. I think the issue might be resolved.
