### ISSUE TITLE
Doesn't show in Recent Apps after icon color change

### ISSUE THREAD

**Issue by shadow0013** [ccrama/Slide#3357]
Slide version: 6.6.1-3
Android version: 9

After changing app icon color, Slide no longer appears in Recent Apps drawer even after device boot.

**Comment by TacoTheDank** [comment]
This seems like it would be more a Launcher issue than an issue with Slide itself. Does the app still appear in the general apps drawer? (not recent apps)

**Comment by shadow0013** [comment]
It appears in the apps drawer. I'm using default OneUI 2.0 launcher on Samsung S8 Plus. So is it a OneUI issue then?

**Comment by TacoTheDank** [comment]
@shadow0013 If it appears in the general drawer, then this issue would relate to how launcher icons populate the app drawer. I don't think it's really even a OneUI issue, but just a limitation of how launchers work. There are very few apps where one can actually change the app icon from within itself, so it would be safe to say that no launcher devs really have a case for dealing with this. How it works (I believe) is that the app icon is removed and then replaced within the launcher drawer, so it likely resets that usage statistic or whatever. I'm kinda rambling at this point, but yeah basically this is a Launcher issue (or limitation, depending on how you look at it), and not an issue with Slide.

**Comment by shadow0013** [comment]
Makes sense I guess. Thanks.
