### ISSUE TITLE
Front-page sidebar issue

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#336]
Or rather, that it exists at all. Sometimes when you start Slide and slide from the right

**Comment by ccrama** [comment]
Can you go into more detail. I don't really understand the issue.

**Comment by Alexendoo** [comment]
You can get to the sidebar on the front page by swiping in from the right, it has placeholder text which happens to be /r/android

**Comment by ccrama** [comment]
Ah, so the first time you open the app?

**Comment by l3d00m** [comment]
No, it works every time. You just have to be on the front page and then swipe from the right to show the default /r/android sidebar.  I think I already opened a issue for that, will look for it.

**Comment by l3d00m** [comment]
#95 is it.

**Comment by ccrama** [comment]
Really? I can't even open the drawer from frontpage. I disable the right hand drawer on frontpage and /r/all o_o

**Comment by l3d00m** [comment]
At least I'm not using the latest version yet (v2.2.2), it is possible fixed already.

**Comment by ccrama** [comment]
It has been disabled since I added the sidebar

**Comment by yasmara** [comment]
Im also experiencing this. Swiping in from the right on the front page on my phone and tablet shows the /r/android sidebar

**Comment by ccrama** [comment]
Fixed 056efca7308d7f65d27f41e4d3909e49142502e2

**Comment by l3d00m** [comment]
happening again

**Comment by okungnyo** [comment]
Happening for me too.

Slide 4.3.4 on Android 6.0.

Using single mode.

**Comment by Alexendoo** [comment]
Seems to be gone again
