### ISSUE TITLE
Read Later and History not loading or updating on 6.7.1

### ISSUE THREAD

**Issue by tp0** [ccrama/Slide#3390]
Slide version: 6.7.1 (Play Store)
Android version: Android 10

Repro:

1. Enable "Save history"

2. Visit some non-NSFW post and mark is as "Read Later"

3. Check if the post or any prior posts appear in Read Later or History

For me, both views are empty. There no existing entries either which should be there.

I can repro this on a completely clean installation too.

**Comment by TacoTheDank** [comment]
https://github.com/ccrama/Slide/pull/3366 seems to have broke this. I reverted the change and tested it on my device, and now seems to work fine.
