### ISSUE TITLE
Some messages in threads are displayed with a wrongly colored bar

### ISSUE THREAD

**Issue by sknorr-prv** [ccrama/Slide#3394]
Slide version: 6.7.1
Android version: 11

In some cases, Slide will show a bar with a color that does not match the comment depth to the left of comment. For example, in this case, the two purple comments and the red comment are at the same comment level. (From the thread in redd.it/oaxkox)

![https---redd-it-oaxkox](https://user-images.githubusercontent.com/47387444/124044137-f7fdcc00-da0c-11eb-99e5-e7d46cf88515.png)

**Comment by eredrolo** [comment]
Purple bar means that the reply is by the OP of the parent comment. In the screenshot **Fluxoteen** is the OP of the parent comment so their bar will be purple in that thread.

**Comment by TacoTheDank** [comment]
@sknorr-prv That is intended behavior, as eredrolo states above. There is a switch to turn this off in the settings.
