### ISSUE TITLE
Translucent status bar

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#34]

**Comment by russjr08** [comment]
Would love to see this too!

**Comment by The0x539** [comment]
uh, i'm a bit more conservative about navbar. Not that i'll have one until my next phone.

**Comment by russjr08** [comment]
Oh, well okay. I know Navbar is a bit harder to do anyways.

**Comment by ccrama** [comment]
I believe this is done already

**Comment by The0x539** [comment]
Sidebar, drawer, and posts, all don't go under the status bar. I don't believe the state of things has changed since this issue was made.

**Comment by ccrama** [comment]
This also includes bringing the drawer under the status bar. Still a very difficult issue to fix and might not happen anytime soon

**Comment by ccrama** [comment]
I think we can officially close this. There is now a setting for immersive mode and that is probably the closest we will get to this
