### ISSUE TITLE
Crash after tapping FAB when there aren't any pins

### ISSUE THREAD

**Issue by karlding** [ccrama/Slide#341]
If there aren't any pinned subreddits, tapping the + FAB causes a crash. I'm using version 4.2.5.5

1. Tap "Reorder your pins"
2. Ensure there isn't anything pinned
3. Tap the FAB to add

Seems to be similar to #245, except in this case, it's when there aren't any pinned subreddits.

**Comment by ccrama** [comment]
Fixed f7967e973606ad01ae1966e0eebd725fade59474

**Comment by karlding** [comment]
This is still happening on the latest release.

**Comment by l3d00m** [comment]
not any longer happening
