### ISSUE TITLE
Not all themes restore

### ISSUE THREAD

**Issue by fangorntheent** [ccrama/Slide#344]
Not all backed up Subreddit themes restore. Everything is right until subreddits that start with the letter T and later.

**Comment by ccrama** [comment]
Hmm. I copy the entire file and paste it into drive, so I don't know why this would occur. Can you A) Try clearing all data, restoring, and then edit some T subs and beyond and re-backup and restore? Also, could you try B) signing in with a different account and seeing if you can set T and beyond and restore from that Reddit account? 

Thank you!

**Comment by fangorntheent** [comment]
Tried restoring again and it did it right. Maybe the restore process was interrupted before?

**Comment by ccrama** [comment]
Possibly, or Android restored some values from the RAM if something was saving before. Since I can't reproduce I'll close it for now
