### ISSUE TITLE
alternative layout is buggy

### ISSUE THREAD

**Issue by c727** [ccrama/Slide#348]
Image mode big picture, cropped and info bar not working

**Comment by ccrama** [comment]
Can you confirm you set the alternative layout to the specific subreddit?

**Comment by c727** [comment]
Yes. In default layout it's working, in alternative it doesn't.

I would make a video again, but it won't play von your end again :p

**Comment by c727** [comment]
... Thumbnail and no-image are OK.
Big picture and so on show no-image.

**Comment by The0x539** [comment]
Yep, this is what I was experiencing.

**Comment by ccrama** [comment]
Very strange. Can't reproduce :(. Can you guy send me a few screenshots please?

**Comment by The0x539** [comment]
Already did on IRC. it's as if it doesn't load it.

**Comment by ccrama** [comment]
When on IRC, I'm on it rn and didn't see anything

**Comment by The0x539** [comment]
the other day

**Comment by c727** [comment]
see here
https://www.youtube.com/watch?v=4cU9Ay7ZvyU&feature=youtu.be

whats your irc channel/server?

**Comment by ccrama** [comment]
irc.snoonet.org and #slide. We're usually on there :). Checking out your bug as well!
