### ISSUE TITLE
Hamburger Menu bar shouldn't animate

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#350]
As per all other "material design" apps, the hamburger menu button shouldn't animate when pulling out the drawer.

**Comment by alexsmithfanning** [comment]
I think it's mostly preference.

**Comment by The0x539** [comment]
Not really. When the drawer covers the button, which it's supposed to in almost all cases, there's not supposed to be an arrowburger.

**Comment by Nxt3** [comment]
Why close these issues? They haven't been fixed.

**Comment by The0x539** [comment]
It's not closed?

**Comment by l3d00m** [comment]
duplicates are always closed

**Comment by Nxt3** [comment]
oh derp. I misread.

I thought you closed this issue. Nevermind, sorry.

**Comment by l3d00m** [comment]
No problem!

**Comment by alexsmithfanning** [comment]
Hangouts does it.

**Comment by l3d00m** [comment]
What?

**Comment by The0x539** [comment]
Hangouts is wrong.

**Comment by ccrama** [comment]
Fixed with the above PR
