### ISSUE TITLE
colour upvote/downvote arrows after vote

### ISSUE THREAD

**Issue by emacsomancer** [ccrama/Slide#352]
The post/comments score changes after an upvote/downvote and changes colour to red/orange=up and blue=down.  But it would be nice if the upvote arrow also became orange after an upvote, and likewise the down arrow blue after a downvote.

**Comment by l3d00m** [comment]
This is already implemented, the only thing that's missing is that the arrow isn't blue when the user voted before and then opens the action bar with the arrows.

**Comment by ccrama** [comment]
You can hook into the "up" and "down" arrays which are in CommentAdapter, those get full with whenever the content is voted up or down

**Comment by ccrama** [comment]
Ill look into it :)

**Comment by emacsomancer** [comment]
@l3d00m - I don't see any arrows changing colours myself.  Having the up- or down-arrow coloured as appropriate is really helpful for me to quickly tell if I've already voted on a post/comment.

**Comment by l3d00m** [comment]
added!
