### ISSUE TITLE
fast(er) navigation to specific subreddit action

### ISSUE THREAD

**Issue by emacsomancer** [ccrama/Slide#353]
"Sliding" from subreddit is very nice, but it would also be good to have some quick navigate-to-subreddit option.  The subreddit list scrolls left/right, but if there are a lot of subreddits in a list, it can be a bit frustratingly slow to get to a particular subreddit.  Relay for Reddit has a drop-down list which one can scroll through really fast.  I'm not suggesting this particular implementation necessarily, but some faster way to navigate to subreddits that are far apart (in a list) would be really nice.

**Comment by ccrama** [comment]
The sidebar has a list of all your subreddits which you can easily click and go to :)

**Comment by emacsomancer** [comment]
ccrama <notifications@github.com> writes:

> The sidebar has a list of all your subreddits which you can easily click and go to :)

Ah, I see. That works - just a different flow than I was used to.
