### ISSUE TITLE
Comments disappear when tapped during loading

### ISSUE THREAD

**Issue by karlding** [ccrama/Slide#357]
After tapping the "Load more comments" text, if you happen to tap the newly loaded comment before the animation fully finishes, the newly loaded comments disappear and leave a gap, where the comments should have been displayed.

However, it seems like certain portions of the hidden comments are still clickable. For example, I was able to visit a user's Profile.

![Screenshot](http://i.imgur.com/pUwHamX.png)

**Comment by l3d00m** [comment]
i can't reproduce it

**Comment by karlding** [comment]
I can consistently reproduce this. I've included a video, with Visual feedback for touches enabled to make it obvious what's being tapped.

![Gfycat video](http://giant.gfycat.com/HarmfulZealousArmadillo.gif)

**Comment by l3d00m** [comment]
Thanks for the video, that made it easier to understand.

I can reproduce it sometimes, but you need to hit the right moment, so I don't think it's priority right now. Thanks for the report though.

**Comment by ccrama** [comment]
It's really difficult to reproduce but I got it once. This is a bug with the RecyclerView and I don't know how I could fix that (at least anytime soon). Thanks for the report, putting a future milestone on it

**Comment by ccrama** [comment]
I don't think this is an issue anymore
