### ISSUE TITLE
Wrong check box position in sidebar

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#359]
The subscribed and pinned check boxes in the sidebar should be on the right of the label, not the left.

**Comment by ccrama** [comment]
It is symmetric with the other icons, keeping it the way it is

**Comment by alexsmithfanning** [comment]
Those are settings, shouldn't they be placed on the right?

**Comment by ccrama** [comment]
No.

**Comment by alexsmithfanning** [comment]
You're right. But there still needs to be padding between the checkbox and the label.

See here: https://www.google.com/design/spec/components/lists-controls.html#lists-controls-usage
