### ISSUE TITLE
Smooth color transitions

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#360]
Color transitions could be smoothened out a bit when switching between subreddits.

**Comment by ccrama** [comment]
Can't really do that, sorry (unless you want a super laggy phone)

**Comment by alexsmithfanning** [comment]
Could you use the code from QKSMS to apply themes? Is you're not familiar with QKSMS, the intro screen gives you an option to try out Night Mode. It changes the entire screen and is extremely smooth. It don't know what implementation of this would entail, but it'd be really cool if you could get it to work.

**Comment by The0x539** [comment]
OctoDroid does do a smooth color transition, though admittedly it's between two tabs with everything predefined.
