### ISSUE TITLE
Possible dialog bug

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#369]
When changing the subreddits colors via the sidebar, its possible to press buttons underneath the dialog.

**Comment by alexsmithfanning** [comment]
Also, the 'OK' and 'Reset' buttons cover up the color chooser.

**Comment by l3d00m** [comment]
the second one is already in #203, thanks for the reports though.

**Comment by alexsmithfanning** [comment]
On mine it actually overlaps. Like get in the way unable to select some colors type of overlap.

**Comment by Alexendoo** [comment]
@alexsmithfanning could you post a screenshot in #203 please

**Comment by alexsmithfanning** [comment]
This might be resolved because @ccrama fixed #203 earlier. But I'm not sure.
