### ISSUE TITLE
Settings naming/positioning cleanup

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#372]
My preliminary suggestions would be:

* [x] New section: Info
 * [x] Move version number into this section in line with other apps
 * [x] Link to github
 * [x]  Can add a credits section for all the libs used perhaps, this could also go in a file on github
* [x] "Mail notification settings" → "Mail notifications", settings is already implied
* [x] "Default Theme" → "Theme" or "Base Theme", alternative implies it ties in with the alternative layouts
* [x] All layout & theme settings could go under an Appearance section
* [x] Default sorting could go under General rather than being its own item in the top level settings, with a small description
* [x] "Backup" → "Backup & Restore"
* [x] link to reddit.com preferences
* [ ] 'reset layout' button has no function

**Comment by Alexendoo** [comment]
Additionally:
* "Support slide" → "Go pro" in drawer
* Move multicolumn to settings menu from drawer, in appearance section if added or under layout/theme if not

**Comment by l3d00m** [comment]
https://www.google.com/design/spec/patterns/settings.htm

**Comment by alexsmithfanning** [comment]
@I3d00m I think you meant: http://www.google.com/design/spec/patterns/settings.html

**Comment by Alexendoo** [comment]
+ reddit.com preferences

**Comment by l3d00m** [comment]
Currently missing:
* reddit.com preferences
* 'reset layout' button has no function

**Comment by ccrama** [comment]
Believe this is done with the settings rewrite :)

**Comment by Alexendoo** [comment]
Reset layout still seems not to work

**Comment by Alexendoo** [comment]
Reset layout no longer exists
