### ISSUE TITLE
Concept for drawer

### ISSUE THREAD

**Issue by c727** [ccrama/Slide#378]
I already posted this on g+ in text-form.
In my opinion this more intuitiv than the current drawer.

![slide sidebar](https://cloud.githubusercontent.com/assets/11984118/11002043/bff29a9c-84aa-11e5-9b89-1e7407ea435c.png)

*account switcher-button should be placed right from "Hello <<user>>"

**Comment by ccrama** [comment]
Interesting. I will look into something like this

**Comment by l3d00m** [comment]
The account switcher is integrated now as well as the "Go To " if no 100% match.

Multis in the sub list is another issue already.

We won't move anything below the sub list though, so it makes no sense to make it collapseable.
