### ISSUE TITLE
Turn subreddit info into a right-side drawer, that, like desktop, contains both sidebar text and other stuff.

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#38]
This drawer is accessible via either an edge swipe or the existing info button, or only via the swipe if you think you can train users to know that.
![grilledcheese](https://cloud.githubusercontent.com/assets/7350294/10413676/9d0ec79a-6f78-11e5-906f-c55407d7ca9a.png)

**Comment by ccrama** [comment]
Done with a5f55db411cbcc0448d58519abe9bc6fd40908ac and after
