### ISSUE TITLE
Ability to change back swipe function 

### ISSUE THREAD

**Issue by 530farm** [ccrama/Slide#385]
Hoping you may consider adding a toggle to change the back swipe function to mimic the back button. I know you can do this by swiping from the screen edge, but on large phones it's hard to reach the opposite screen edge for right handers, and I don't really see using swipe to go to the previous post that often. 

Thanks for your consideration.

**Comment by Alexendoo** [comment]
Added with 887760a219f4b12d3828005490b4d1ca3ead4bc7! :tada:
