### ISSUE TITLE
App dies when WiFi/Mobile Data is turned off while in app

### ISSUE THREAD

**Issue by fangorntheent** [ccrama/Slide#389]
Slide Version: 4.3

If mobile data or wifi is turned off while in app, the app will crash and produce the "restart app" screen. When "restart" is clicked, the app will restart but will not go passed the initial splash screen that says, "connecting to reddit," even when connected to internet. This also happens when the app is opened from the app drawer or by other means besides the "restart" button. 
Once the app is stuck on the "connecting to reddit" and internet access is removed, the app will not produce the "slide has crashed" screen until the device's native "back" button is pressed.
If the "restart" button is pressed while there is no internet access, the "uh oh, you are not connected" dialog will appear as normal, however, the app will still not progress past the "connecting to reddit" screen when internet access is recovered.
The only way to restore functionality to the app is to either wipe app data or uninstall and reinstall the app.

EDIT: Upon further testing I have learned that this problem is fixed by uninstalling and reinstalling the app. It must be noted, however, that the app still crashes when an internet connection is removed while in app.

**Comment by l3d00m** [comment]
this is important

>When "restart" is clicked, the app will restart but will not go passed the initial splash screen that says, "connecting to reddit," even when connected to internet.

**Comment by l3d00m** [comment]
merge into #306
