### ISSUE TITLE
Collapsing comments - fold actual comment?

### ISSUE THREAD

**Issue by SZE2** [ccrama/Slide#39]
enhancement request:

Please make it that when you collapse a comment, it collapsed the actual comment along with that comment's children.

When collapsed, a comment can show just it's regular header, containing the OP, Vote count, time, and children count. tapping on this header will reopen the comment body and its children.

This will be very useful for Reddits with long top-level comments, like r/writing prompts.

link to a rough mockup:

TIA!!

![](https://imgur.com/a/PCrX1)

**Comment by szeichorn** [comment]
sorry, link here: https://imgur.com/a/PCrX1

**Comment by l3d00m** [comment]
+1 for this

**Comment by The0x539** [comment]
Agreed.

**Comment by ccrama** [comment]
Done, will add in next commit!

**Comment by ccrama** [comment]
Prelim code added in 85fb67c73a8fb0d4d3aea2da27ddc44867924ca4. Looks a bit strange, working on a smooth animation to make it more clean :)

**Comment by szeichorn** [comment]
thank you!

**Comment by l3d00m** [comment]
Awesome thanks!

**Comment by ccrama** [comment]
Ends up looking really bad and not working with the default recyclerview animations. I'll put this one on the books, but will mark as wontfix for now

**Comment by The0x539** [comment]
To be honest I'd rather no animation than current behavior, but...

**Comment by Alexendoo** [comment]
I'd agree with no animation, function has to trump form in some places and this is definitely one

**Comment by l3d00m** [comment]
I'd agree with @the0x539 too.

**Comment by frederickfogerty** [comment]
I'm not so fussed with the comments still being shown, but I would agree that animations slow down navigating through comments, maybe there could be a toggle in the settings somewhere to turn off animations?

**Comment by okungnyo** [comment]
I don't understand, is this a "show top-level comments only" feature?

**Comment by l3d00m** [comment]
No, this is about hiding the content of the top level comment too if you hide its children.

**Comment by okungnyo** [comment]
I don't understand...

**Comment by The0x539** [comment]
So right now, if you longpress/tap a comment depending on setting, it hides all child comments. The idea, and the way most other access methods do it, the parent comment is, on top of that, collapsed to a single line of text in height.

**Comment by okungnyo** [comment]
I still don't understand.

So hide the top-level comments too?

**Comment by l3d00m** [comment]
yes

**Comment by okungnyo** [comment]
yes

**Comment by szeichorn** [comment]
Can this please be Revisited? 
I see that the Milestone of 4.1.0 has passed...
Don't mind me if this sounds pushy... thanks!

**Comment by 2fst4u** [comment]
I second this also. It's mostly important/an annoyance when a parent comment is quite large. When you tap and hold, you can see anything change and still have to scroll passed it to get to the next one.

**Comment by tejassharma96** [comment]
I personally really like it the way it currently is, if implemented it would be really nice if there was a toggle in the settings to still show the top comment. Similar to how it is with horizontal/vertical album view in the settings.

**Comment by raazman** [comment]
Yes, please collapse parent comment too. There is a reason to collapsing the comment, because you're done with it.

**Comment by l3d00m** [comment]
Added as a setting in c85e3211e735c436c5bb5485fb18b6c491ce83ac
