### ISSUE TITLE
Pinned posts on every post

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#391]
Basically the title. Every card has the pinned status.

**Comment by ccrama** [comment]
What? What is pinned status

**Comment by alexsmithfanning** [comment]
The post is pinned at the top of the subreddit. All cards have that label.

**Comment by ccrama** [comment]
I still don't know what you mean

**Comment by alexsmithfanning** [comment]
The green "pinned" text that are on posts that have been posted to the top of the stream.

Like an NSFW tag, but green.

**Comment by ccrama** [comment]
Cannot reproduce

**Comment by alexsmithfanning** [comment]
Here's a screenshot: https://goo.gl/o8K6HL

The first post is pinned. It says pinned twice. The second one isn't, if says pinned once.

**Comment by alexsmithfanning** [comment]
It's either KitKat related or device specific. I can't reproduce this on my friends Nexus 5X.

**Comment by alexsmithfanning** [comment]
Fixed.
