### ISSUE TITLE
Posts no longer work

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#392]
Slide crashes when tapping on a post.

Problem, yeah.

**Comment by ccrama** [comment]
Cannot reproduce at all

**Comment by ccrama** [comment]
You gotta give me more info man

**Comment by alexsmithfanning** [comment]
I've tried. Now I can't get it to open at all. I've tried reinstalling, clearing cache, and clearing data but I can't get it to start.

**Comment by ccrama** [comment]
Click the report button please. I can't help you without a log

**Comment by alexsmithfanning** [comment]
I can't even do that. It crashes as soon as anything appears. Could I get a stack trace from ADB or something?

It doesn't have a report button anymore. Does it?

**Comment by ccrama** [comment]
The system ui says Slide crashed and it has close and report. Click report and it'll send over the Play Store

**Comment by alexsmithfanning** [comment]
Minor problem: there's no report button.

Link: https://goo.gl/sV8URU

**Comment by fangorntheent** [comment]
He means the Android generated crash dialog. It says "close" and "report" when any app crashes unexpectedly.

**Comment by ccrama** [comment]
That means you are not on a play store build

**Comment by alexsmithfanning** [comment]
I installed it from the Play Store.

Correction: updated from Play Store.

**Comment by ccrama** [comment]
That's pretty strange. I'll look into it

**Comment by ccrama** [comment]
But it looks like an OS issue, not an app issue

**Comment by alexsmithfanning** [comment]
It's fixed.
