### ISSUE TITLE
Your profile -> comments, gilded not working

### ISSUE THREAD

**Issue by c727** [ccrama/Slide#395]
It's never loading for me
https://youtu.be/-IYwg5HH1Q0

@team: newest version is much better :)

**Comment by ccrama** [comment]
Maybe you've never been gilded? And the team is me :)

**Comment by c727** [comment]
Gold job ccrama ;)
True, but why is the spinner there for ever? Same for cemments

**Comment by l3d00m** [comment]
So it should just show a message that there are no gilded posts @c727 ?

**Comment by c727** [comment]
@l3d00m 
thats a good idea, too.

But this report was about that the loading indicators not disappear after loading overview/comments/submitted/gilded

**Comment by l3d00m** [comment]
merge into #612
