### ISSUE TITLE
Some cosmetic bugs

### ISSUE THREAD

**Issue by c727** [ccrama/Slide#397]
* [x] translation missing: 'your profile' page
* [x] translation missing: 'frontpage', 'all'
* [x] innercontent-thumbnails also need fixed width
* [x] `i` button has no function  in 'frontpage' and 'all' -> hide button or make them  also themable
* [x] donation view:
- `$` is cut off
- wrong exchange rate to €
- 'support slide ...'-text in header and text  -> change one text
* [x] check message every  xxx-view needs a default value (ATM the text changes(gets much longer) when choosing a value)
* [ ] current value of a list-chosen-value is not translated (for example at fontsize)

**Comment by l3d00m** [comment]
1/2 i don't think frontpage and all should be translated

5. i think there is no exchange rate currently? it should be displayed only in $

6. what do you mean excactly by this?

**Comment by c727** [comment]
If you choose to donate 10$ and click donate it says 10,61€ instead of 9,31€

**Comment by ccrama** [comment]
Should all be fixed now (except for the locale). The issue with that is I don't know what the conversion rates for the amount are in different countries, US price is the only one I can rely on
