### ISSUE TITLE
Images over 4096px appear not to display a preview

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#40]
I have a few test images available on [/r/alexendoo](https://www.reddit.com/r/alexendoo), would be good for some others to confirm

**Comment by ccrama** [comment]
Seems to load fine for me!
![screenshot_2015-10-11-19-27-52](https://cloud.githubusercontent.com/assets/3819844/10420043/44ebe828-704e-11e5-85a1-1f38959a303c.png)

**Comment by Alexendoo** [comment]
Fixed with 0f227ac2ac9117b10fca4ec069a6395fcc777989
