### ISSUE TITLE
Improvements for Shadowbox Mode

### ISSUE THREAD

**Issue by KaliK0t** [ccrama/Slide#409]
* [x] Would be very helpful if the  slideshow view showed the subreddit and the number of comments in the information text below.

* [x] And would be great if it jumps  straight to where you left of in the Feed view

**Comment by Alexendoo** [comment]
Yeah second one would be very nice, same with swiping right through comment threads (But I assume also hard). First one would add more UI though it's meant to be relatively distraction free so I'm not sure about that

**Comment by KaliK0t** [comment]
it would just be added to the post title beside or below the text

**Comment by ccrama** [comment]
Done!
