### ISSUE TITLE
Text formatting buttons and double-tapping bugs

### ISSUE THREAD

**Issue by stevefye** [ccrama/Slide#41]
Formatting text buttons don't seem to do anything when replying to comment. Also, double-tapping text in the content reply box causes view to scroll and loses any text that you already typed. 

https://youtu.be/J4YV1

Note 3 with 4.4.2, rooted, stock TouchWiz

**Comment by Alexendoo** [comment]
@stevefye There appears to be an issue with your video

**Comment by Alexendoo** [comment]
Checking it though I have the same thing occur for both, the double tapping is particularly strange

**Comment by stevefye** [comment]
Huh.  Try this video.

https://youtu.be/J4YV1Yjlijk

**Comment by ccrama** [comment]
The double clicking does this because the first click exits the menu and the second click hides all child comments. This is working as intended.

As for the formatting, will work on fixing that!

**Comment by Alexendoo** [comment]
@ccrama Double tapping a word is an android action to highlight it, it's a default behaviour that shouldn't be overridden. That also doesn't explain the random velocity the app seems to gain

**Comment by ccrama** [comment]
Merge with #66
