### ISSUE TITLE
Problems with the username in comments

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#415]
examples: 
https://www.reddit.com/r/Android/comments/3rw8l6/slide_for_reddit_v4_beta_complete_rewrite_stable/cws1be3;  
https://plus.google.com/+GusLipkin-FangornTheEnt/posts/LJ1bBbp8bE7  
http://abload.de/img/screenshot_2015-11-16nrq76.png  

Only noticied it whit [SCORE HIDDEN]

**Comment by l3d00m** [comment]
![screenshot_2015-11-14-10-42-27](https://cloud.githubusercontent.com/assets/12055376/11167968/2a21cbd2-8b7b-11e5-928a-fb48c2bb84e5.png)

![screenshot_2015-11-14-10-42-21](https://cloud.githubusercontent.com/assets/12055376/11167969/36b08550-8b7b-11e5-8160-2b3b41ace218.png)

Happens with other names too sometimes.

**Comment by l3d00m** [comment]
http://abload.de/img/screenshot_2015-11-16nrq76.png

**Comment by Controless** [comment]
Can confirm, happening to me too.
![screenshot_2015-11-17-23-30-15](https://cloud.githubusercontent.com/assets/13410769/11235157/be538200-8d83-11e5-9750-90683e741521.png)

**Comment by l3d00m** [comment]
Happens especially for users with the /r/android developer flair.

**Comment by ccrama** [comment]
Has this been fixed?

**Comment by l3d00m** [comment]
No, it still happens.

**Comment by Plastix** [comment]
I'm experiencing a similar issue on a Nexus 5 running 6.0.1 with the latest Slide Pro. 
![screenshot_20160208-065324](https://cloud.githubusercontent.com/assets/1526881/12886947/1251e86e-ce3f-11e5-833a-a9fc97b12f17.png)

Comment in question: https://www.reddit.com/r/Android/comments/44opi3/reddit_sync_temporarily_blocked_for_bad_api_usage/czrpfk9

**Comment by stokholm** [comment]
Slide: 4.6.1-8
Android: 6.0.1

Happens still, and further more there's two different expressions of this bug, depending on whether the comment is collapsed or not.

![comment header](https://cloud.githubusercontent.com/assets/1306752/13218948/58eb362a-d96d-11e5-8185-7f05627325d5.png)

**Comment by Alexendoo** [comment]
If I'm stating the obvious here whoops, but it looks like it occurs every time the content wraps to the next line due to flair or really long names

**Comment by ccrama** [comment]
Fixed
