### ISSUE TITLE
App crash when changing Image mode.

### ISSUE THREAD

**Issue by clank201** [ccrama/Slide#416]
Whenever I try to change the image mode to whataver different than "None" inside Settings->Default Layout or Settings->Alternative Layout, the app crashes. 

Release 4.3 downloaded from Play Store.
Using Samsung Galaxy S6 (SM-G920F) on Android 5.1.1

EDIT: Using Catalan locale (cat, ca_ES) btw.

Thanks for the workaround and keep up the good work =D

**Comment by l3d00m** [comment]
Current workaround is to set your system language to english. Sorry for that, it'll be fixed with the next release.

**Comment by ccrama** [comment]
Fixed 75076a9
