### ISSUE TITLE
Option to remove dead space between each comment tree

### ISSUE THREAD

**Issue by ObsoletePixel** [ccrama/Slide#419]

**Comment by l3d00m** [comment]
Can you explain what you mean by dead space?

**Comment by ObsoletePixel** [comment]
there's space between each comment tree that I'd like to be able to remove, in subreddits where I see only one child comment per parent comment or something similar it's a huge waste of space. Also, it just doesn't look that nice to me :p

**Comment by l3d00m** [comment]
Now i know which space you mean. +1 for that!

**Comment by l3d00m** [comment]
[This](https://i.imgur.com/D83ovfW.jpg) is how it would look like with only 2dp instead of 8dp. Is it ok @ccrama?

**Comment by Alexendoo** [comment]
Personally I think that's too little
