### ISSUE TITLE
[Request] Move thumbnails to left-hand side of post titles

### ISSUE THREAD

**Issue by crwood** [ccrama/Slide#420]
Because a) images typically convey more information than text and b) most redditors read from left to right, it would improve readability to move (or at least add an option to move) the thumbnails to the left-hand side of the post title when the image mode is set to "thumbnail". This change would bring Slide's interface more in-line with the traditional reddit layout and, more importantly, would serve to greatly reduce eye-strain/fatigue on wider displays (assuming, of course, that most users look at images before they read text).

If this is unclear or unconvincing, consider the eye-movement/distance required to go a) from a thumbnail on the far right side of the screen to the beginning of the post title to the end of the post title vs. b) from a thumbnail on the left side of the screen to the beginning of the post title to the end of the post title. In the latter case (with the thumbnail on the left) the user need only scan from left to right (effectively moving in a straight line), whereas in the former case (with the thumbnail on the right, as it currently stands) the user's eyes need to scan from right to left to right again, effectively doubling the amount of eye-movement required. 

This may seem very nitpicky to some, but small usability-improvements go a long way in improving user-experience in extended-use scenarios (with which I'm sure most redditors are familiar with!).

**Comment by Alexendoo** [comment]
It's a preference, tapping the thumbnail provides a way to go straight to the link so moving that away from the hand wouldn't be appreciated for some, a left handed thumbnail option could be added if feasible though

**Comment by l3d00m** [comment]
Added in 6458ec8f670ecd845c279dd61dc5aa01b4f6970c
