### ISSUE TITLE
Suggestion to move "Sumbit a post"

### ISSUE THREAD

**Issue by Soberat** [ccrama/Slide#421]
Right now, if you want to sumbit a post, you need to go to the Navigation Menu, expand the "Profile" menu and click "Sumbit a post". In my opinion, that's kinda unintuitive. Since app is fully Material Design, a Floating Action Button in lower right corner would make sense. I'd advise to keep it lower that Google says, because by default they are way too high. It would hide when scrolling down, and show up when scrolling up. But it would be great if current layout would be still an option.
I'm attaching a mockup, sorry for the quality but I forgot to disable compression in Photoshop.
Cheers,
Soberat
![feature request mockup](https://cloud.githubusercontent.com/assets/15708186/11017171/70dbfb22-8597-11e5-913f-18e63dc946b1.png)

**Comment by l3d00m** [comment]
this is a really good idea. i don't know if it should have it's own fab because it isn't used that often and fabs are for often used actions, but it shouldn't be that hidden

**Comment by frederickfogerty** [comment]
Maybe the user could decide what they wanted in the FAB? Some users might like to have a create post button, whereas others might like a button to hide viewed posts (my preference), others might like a button to search.

**Comment by plumbe0** [comment]
+1 on the FAB to post a new submission (and maybe expand the FAB so you can choose text/link/image post)

**Comment by okungnyo** [comment]
Also, maybe have the FAB hide itself when scrolling down?

Because I don't think submitting a post/link is a frequent enough action to warrant a FAB for most users.

**Comment by plumbe0** [comment]
Yeah, much like it is implemented in G+ app.

**Comment by ccrama** [comment]
Thank @TomerRosenfeld  for the PR!
