### ISSUE TITLE
Gesture to close video/gif previews

### ISSUE THREAD

**Issue by frederickfogerty** [ccrama/Slide#425]
I love being able to tap anywhere on image previews to close them, but for video previews I have to either use the back button or the close button at the top-right of the screen. This is a stretch for my thumb, would love if there was a way to tap the video, or maybe slide up/slide down like Facebook Groups/Paper, and Telegram.

Loving the app otherwise! I'd love to help write it, but I don't know Android development that well unfortunately

**Comment by Alexendoo** [comment]
You can swipe from the left edge to exit most things in the app (notable exception currently is the browser), unless I'm mistaken which bit you mean

**Comment by frederickfogerty** [comment]
I did not know that, but it's still a bit of a stretch. I imagine it'd be hard to do what I'm suggesting for videos, as you'd have to overlay the actual player. Still, it'd be nice to have consistent behaviour with image previews.

**Comment by kauelima** [comment]
Swiping down is the most recognizable *exit* gesture on photos or previews. Facebook does that, Twitter does that, etc. Maybe down is better that left to right in this ocasions.

**Comment by ccrama** [comment]
Unfortunately, I can't do down, but I can do up, right, and left. Are any of these gestures better?

**Comment by okungnyo** [comment]
Why's that? (Just curious.)

**Comment by kauelima** [comment]
Possibly because of pull down to refresh that is implemented everywhere else? If so, i'd rather close with pull down since media is not changing all the time as timelines are.

If not possible, the next best option is the current one, I'd only try to make the gesture work even when swiping on top of the media itself (now it only works outside of the picture on the black area)

**Comment by Alexendoo** [comment]
Added with 887760a, there's now an option to swipe back from anywhere to close the post/image/video, it's pretty nice. :+1:
