### ISSUE TITLE
Strange cardview shadow cropping

### ISSUE THREAD

**Issue by vemacs** [ccrama/Slide#428]
This issue is especially apparent with the light theme. The bottom shadow of the card is cropped out, making it look weird.

![](http://i.imgur.com/l8h02Kl.png)

**Comment by ccrama** [comment]
Fixed with redo of all views  a few commits back

**Comment by vemacs** [comment]
This is still an issue with 4.5.

**Comment by l3d00m** [comment]
True, exactly the same as described in op is happening with 4.5.0

**Comment by ccrama** [comment]
Fixed in my new branch
