### ISSUE TITLE
New posts do not load after you reach the bottom of any sub

### ISSUE THREAD

**Issue by kelvinalfaro** [ccrama/Slide#43]
/all
/frontpage
any any other sub is affected. 
No autoloading of posts beyond what is initially loaded on start up.

**Comment by Alexendoo** [comment]
I couldn't manage to reproduce this exactly however I did experience some similar behaviour to #13 and shall re-open it

**Comment by ccrama** [comment]
Fixed with 85fb67c73a8fb0d4d3aea2da27ddc44867924ca4 for good this time!
