### ISSUE TITLE
Inconsistent padding for thumbnail view

### ISSUE THREAD

**Issue by vemacs** [ccrama/Slide#430]
![](http://i.imgur.com/joBc14Q.png)

* Top margin is way too large
* Right margin for the image (not the buttons) is way too small
* Vertical space between post title/thumbnail and buttons could be cut down

Also, note that #428 is visible here as well.

**Comment by brudin** [comment]
Yeah, toggling action bar to off also makes it worse.

**Comment by ccrama** [comment]
Not applicable anymore after complete rewrite of card views.
