### ISSUE TITLE
gfycat thumbnail?

### ISSUE THREAD

**Issue by JayXon** [ccrama/Slide#431]
I set image mode to big picture, even random webpage has thumbnail, but not gfycat?
![screenshot_20151107-160603](https://cloud.githubusercontent.com/assets/1552641/11018021/d470aac6-8569-11e5-95c8-6373e7fffd48.png)

**Comment by l3d00m** [comment]
I think the thumbnails are fetched directly from reddit so it's something we can't fixed. I wait for @ccrama  statement before closing this.

**Comment by JayXon** [comment]
Now for Reddit was able to display at least a small thumbnail.

![screenshot_20151108-001102](https://cloud.githubusercontent.com/assets/1552641/11019421/54b619a8-85ad-11e5-98e4-592017208a80.png)

**Comment by l3d00m** [comment]
"All the thumbs I get are from Reddit. If they are too low resolution, I hide them from being shown because it looks bad honestly :(﻿" "I'm adding a blurry switch soon so you can always show them﻿
" Quoted from ccrama on g+

**Comment by ccrama** [comment]
Not applicable anymore, now it shows them all.
