### ISSUE TITLE
Request for hide button in action bar on comment view too

### ISSUE THREAD

**Issue by 2fst4u** [ccrama/Slide#434]
As above. Simple button to action bar instead of having to open the menu to hide a post.

**Comment by l3d00m** [comment]
added as an option

**Comment by okungnyo** [comment]
What does "Simple button to action bar" mean??

**Comment by 2fst4u** [comment]
A button added to the action bar. Which I imagine would have been simple to implement.

Therefore Simple button to action bar

**Comment by okungnyo** [comment]
I'm still confused.

**Comment by l3d00m** [comment]
![screenshot_2015-11-10-20-32-22](https://cloud.githubusercontent.com/assets/12055376/11073301/4dc7024e-87ea-11e5-9f54-f4920d46e9f1.png)

This is how it will look like.

**Comment by 2fst4u** [comment]
About what? The action bar part?

**Comment by l3d00m** [comment]
It's optional anyway

**Comment by okungnyo** [comment]
Oh, I get it now! Thanks for the screenshot, helped me to finally understand

**Comment by l3d00m** [comment]
the bar with the arrows and the hide button is called 'action bar'.

**Comment by okungnyo** [comment]
Thanks.

**Comment by 2fst4u** [comment]
The hide button only shows when viewing an entire sub. When inside a post it would be good to see it too.

**Comment by l3d00m** [comment]
That is intentional. Why would you like to have it in post view too?

**Comment by 2fst4u** [comment]
My flow of events when browsing is to open, read, hide, exit. Now that your
app provides the functionality to swipe through posts, removing the need to
"exit", my flow would be better if it was open, read, hide, swipe. Instead
I'm forced to open, read, exit, hide, completely ruining the swipe
experience.

**Comment by okungnyo** [comment]
That seems logical.

**Comment by Nxt3** [comment]
@2fst4u Why not just use the hide FAB? That way, you could view multiple posts, then press the button once to hide them all?

**Comment by 2fst4u** [comment]
I don't think that was around when I made this request

**Comment by Nxt3** [comment]
Can I close this issue? I have to agree in that you're an outlier in terms of hiding the post while you're still viewing it. While I could make an option for this--I really feel like options concerning the comments section are starting to get cluttered. :\ 

However, the "Hide FAB" sounds like exactly what you want. You'd view multiple posts, then long press on that FAB to hide the 'seen' posts.

**Comment by 2fst4u** [comment]
Yea probably if I'm the only person that wanted it. Go ahead
