### ISSUE TITLE
Shadowbox mode includes text posts

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#44]
![screenshot_2015-10-11-23-32-03](https://cloud.githubusercontent.com/assets/1830331/10419453/78b1ad56-7070-11e5-96d7-2ae7c876290d.png)

**Comment by ccrama** [comment]
Should it just not include selftext, or should I have a little reddit icon in the image view?

**Comment by Alexendoo** [comment]
I think since it's a mode for just browsing through images/gifs as far as I see it, it would be best to exclude them

**Comment by ccrama** [comment]
This would not work with the way I handle the data, unfortunately. Not a breaking issue, just might be annoying on non picture-heavy subs
