### ISSUE TITLE
Markdown: Ordered Lists

### ISSUE THREAD

**Issue by karlding** [ccrama/Slide#440]
Ordered lists are being treated as unordered lists.

```
1. Item 1
2. Item 2
3. Item 3
```

Should display as

1. Item 1
2. Item 2
3. Item 3

Not

* Item 1
* Item 2
* Item 3

**Comment by TomerRosenfeld** [comment]
Can you please provide a screenshot example?

**Comment by karlding** [comment]
This is because of the replacements that ``ParseTextWithLinksTextViewComment`` does on line 116 in [MakeTextviewClickable.java](https://github.com/ccrama/Slide/blob/06dec494eb9a2f7c6199805498209c72601108d8/app/src/main/java/me/ccrama/redditslide/Views/MakeTextviewClickable.java#L116). An ordered list is preceded by ``<ol>`` and then each list ``<li>`` element, but currently, the code blindly replaces any ``<li><p>`` with ``<p>• ``, assuming that the only lists are unordered lists.

The problem is that it's being treated exactly the same way as an unordered list.
