### ISSUE TITLE
Rename "fast scroll" option in settings

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#441]
For posts with lots of comments, it takes a long time to manually scroll to the next top comment.

With [prev/next] arrow buttons, it would be possible to skip to the next top comment.

**Comment by l3d00m** [comment]
Settings -  General - fast scroll through comments

**Comment by okungnyo** [comment]
Thank you.

Perhaps it should be renamed?

Because to me, personally, "fast scroll" implies a draggable scrollbar, not top comment navigation.

"Show button to fast navigate top comments" maybe?

**Comment by l3d00m** [comment]
That makes more sense, yes. I reopened it.

**Comment by l3d00m** [comment]
fixed with 5662c8b

**Comment by okungnyo** [comment]
What sentence did you change it to?

And how soon will we get to see it in a release?

I'm just excited!

**Comment by l3d00m** [comment]
wrong commit linked, this is the right one: 5af36a4

```
-    <string name="settings_fastscroll">Fast scroll through comments</string>
+    <string name="settings_fastscroll">Navigate between parent comments</string>
```

This is what i've changed @okungnyo. I'm pretty excited too!

**Comment by l3d00m** [comment]
Forget to answer your question: I think it should be a few days max. Only Alpha channel will get the next update iirc.

**Comment by okungnyo** [comment]
Thanks.

**Comment by okungnyo** [comment]
Should this be closed now?

**Comment by okungnyo** [comment]
Oh it is closed lol
