### ISSUE TITLE
Slide takes an insane amount of time to load posts and comments

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#442]
I'm running Android 6.0 Marshmallow, and am using Slide v4.3.1.

Relay and Sync will take 1-2 seconds to load my frontpage, while Slide takes 10 seconds.

I am not exaggerating, I literally counted it out and it was 10 seconds.

Relay will take 3 seconds to load comments, while Slide takes 15 seconds.

Again, I am not exaggerating. And the thread I tested had only 500 comments; I can only imagine how much longer Slide will take to load the average AskReddit thread with 3,000+ comments.

(I think you should look at how Relay loads comments. Instead of loading them all at once as Slide appears to be doing, Relay just loads the topmost one, and then sequentially loads the rest from there.)

It can't just be me that is seeing this slowness, can it?

**Comment by simmac** [comment]
Same here (Nexus 5, Android 6.0)

**Comment by l3d00m** [comment]
I assume this is because slide loads the subreddits simultanely because of the tab layout.

**Comment by okungnyo** [comment]
Is that true?

Is that intentional? Because that sounds like a huge mistake??

So if for example a user has 100 subs, Slide will load all 100 of them at once??

**Comment by SolarAquarion** [comment]
Not really, i have more than 100 subs and it takes around the same time as everyone else

**Comment by l3d00m** [comment]
no, but it always loads 3 at the same time iirc

**Comment by ccrama** [comment]
I removed that functionality in 75076a9 . I also found out Slide was reauthenticating on every activity open, and that has been fixed. This will be much faster now!
