### ISSUE TITLE
Imgur GIFs with JPG file extension don't work

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#443]
Was reported on reddit and I can reproduce it too. Example post: http://reddit.com/r/trees/comments/3rybkw/mrw_im_high_as_shit_and_try_to_get_some_munchies/

The important part to notice is that it's still gif, it just has the *.jpg ending also it's one.

Only the first frame is displayed as a static image. 

I'm adding this to 4.4 because it makes some "science" subs really boring.

**Comment by Spittie** [comment]
Yeah, the extension on imgur is mostly useless.

http://i.imgur.com/NfnL8zL.gif
http://i.imgur.com/NfnL8zL.png
http://i.imgur.com/NfnL8zL.jpg
http://i.imgur.com/NfnL8zL.jpeg
All show the same animated .gif.

I guess the solution would be to use the imgur api (I don't know if Slide would qualify for the free api - https://api.imgur.com/#commercial) to get the "animated" field (https://api.imgur.com/models/image) or to do an HEAD of the url to get the Content-Type header before displaying the image.

**Comment by l3d00m** [comment]
the imgur api shows which content type it is

**Comment by l3d00m** [comment]
Fixed!

**Comment by ccrama** [comment]
Why would gifs have a jpg link?

**Comment by l3d00m** [comment]
Because people are idiots. I have no idea to be serious, but it happened a few times already :/

**Comment by ccrama** [comment]
Fixed, it now works! Checks for the content type of the link if it's a jpg and does the appropriate action after that
