### ISSUE TITLE
Comment actionbar color shouldn't be dark main theme color

### ISSUE THREAD

**Issue by simmac** [ccrama/Slide#446]
It just doesn't look good and the contrast is very bad (dark grey/black on a dark color is never a good idea). It should be a lighter shade of the theme color, or the accent color.
Here you can see why: 
![comment_menu](https://cloud.githubusercontent.com/assets/7317069/11020049/57cfba66-8613-11e5-816e-54079e1cea6d.png)

**Comment by The0x539** [comment]
I think a lot of the problem is the foreground colors, not the background colors. White/lightgray on that orange would be just fine for me.

**Comment by simmac** [comment]
@The0x539 Yeah, that's what I meant with "dark grey/black on a dark color is never a good idea". I would be happy with lightgrey/white.

**Comment by ccrama** [comment]
Done with v4.5.1, now it's all white!
