### ISSUE TITLE
Allow users to set app language

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#448]
Help: http://stackoverflow.com/a/9173571/4026792

Some users complained on reddit because they don't like the translation / the translation isn't finished and they want to change the language (to default).

**Comment by kauelima** [comment]
This is a big issue for users with languages other than english set on their devices. There should be at least an option to use english instead of the device language while translation keys are not set

**Comment by l3d00m** [comment]
Just ut of curiosity: Why do you think it's such a big issue?

**Comment by kauelima** [comment]
Some strings are half in one language and half on another. Since sentences are not always built with the same rules in different languages some things just don't make any sense. As a fluent bilingual I can, with little observation, figure out what the sentence suposed to mean but it's not ideal.

**Comment by ccrama** [comment]
Done with 5.0.1!
