### ISSUE TITLE
Changing subreddit color theme issue

### ISSUE THREAD

**Issue by Soberat** [ccrama/Slide#455]
When you're choosing colors for particular subreddit, go into "Change color", "Accent color" or . Once you're in one of those, tapping on the place where they are will bring them up instead or again. It's a weird issue and it's hard to describe so I'm attaching a video. (Sorry it lags so much, my old device can't handle recording and doing something at one time).
https://dl.pushbulletusercontent.com/sCkqaSt7D2QNTLi7kBK9kDsweCyNVY6r/SCR_20151108_203628.mp4

**Comment by Alexendoo** [comment]
Ah this is similar to #369, it's apparently not a link underneath after all, as this thread is more informative I shell close the other

**Comment by l3d00m** [comment]
this is fixed a while ago too, because the dialog was reworked
