### ISSUE TITLE
Scrolling resets if you go into landscape mode and switch back

### ISSUE THREAD

**Issue by Unspec7** [ccrama/Slide#458]
This doesn't always happen, but if you're viewing a submission and go into landscape mode, then back to portrait, when you return to the frontpage or the subreddit in general, the scrolling sometimes resets all the way back at the top

**Comment by joshery420** [comment]
I've noticed this exact thing often and it drives me nuts haha.

**Comment by l3d00m** [comment]
this should be fixed with b58b69dda5d4e5baa696ce5bf3ec9d159ad1e3c8

**Comment by joshery420** [comment]
Awesome! Slide is getting more and more awesome with each update. It might well surpass Relay soon! :D

**Comment by l3d00m** [comment]
Thanks for the kind words! The newest update should come very soon, which will contain much big fixes and new Features like editing content.
