### ISSUE TITLE
Not showing newly subscribed subreddits

### ISSUE THREAD

**Issue by fangorntheent** [ccrama/Slide#459]
Latest version of slide.
Newly subscribed subreddits aren't showing as being subscribed in app (not in sidebar or tabs). I subbed to it a day ago and have opened and closed slide at least ten times since then.

**Comment by l3d00m** [comment]
Marking this high priority because it confuses users. Even if I'm subscribing through the website, it's not showing up after a day in Slide.

**Comment by fangorntheent** [comment]
It's a problem with needing permission to join said subreddit.  /r/ravenclaw
You can't just subscribe. Normal Subreddits show up fairly reasonably quickly.

**Comment by l3d00m** [comment]
No, it's not. This is an issue too, but normal Subreddits aren't showing up sometimes too.

**Comment by fangorntheent** [comment]
Oh. My bad. /r/ravenclaw still doesn't show in my subs, by the way.

**Comment by l3d00m** [comment]
No problem! Yeah, #498 is the issue you meant.

**Comment by ccrama** [comment]
Wait, you have to go into the sidebar, profile, and click "Sync Subreddits". Not a bug :P

**Comment by l3d00m** [comment]
Doesn't work, even when I restarted after it. It will show up after a few days only.

**Comment by ccrama** [comment]
Works for me every time :(. If you are closing the app right afterwards, Android won't let the .apply() on the SharedPreferences save as it's scheduled for the future

**Comment by okungnyo** [comment]
The user shouldn't HAVE to go into the sidebar, profile, and click "Sync Subreddits" though, right?

Shouldn't it be automatic?

**Comment by ccrama** [comment]
Every other app does it this way, and that allowed me to shave 5 seconds off the loading time

**Comment by okungnyo** [comment]
OK if it results in faster load times, then I'm all for it.

**Comment by fangorntheent** [comment]
Doesn't work for /r/ravenclaw

**Comment by l3d00m** [comment]
That's because it's private, there's another issue for that.
