### ISSUE TITLE
Request to pin multireddits to top bar

### ISSUE THREAD

**Issue by adamundercover** [ccrama/Slide#461]
Would be a useful feature that doesn't require swiping to the multireddit section

**Comment by ccrama** [comment]
Done with the new Collections feature in my last commits

**Comment by Alexendoo** [comment]
I wouldn't say this is done, collections are fundamentally less powerful than multireddit, for example in the big ones of not being able to add subreddits you aren't subscribed to, and not being able to share them across devices

**Comment by ccrama** [comment]
Added an option to import multireddits into collections, that's the best compromise I can do

**Comment by l3d00m** [comment]
#1439 should make this possible in the future.

**Comment by ccrama** [comment]
You can now by going to Reorder > + > Import multi!
