### ISSUE TITLE
Synccit support

### ISSUE THREAD

**Issue by FISHunderscore** [ccrama/Slide#464]
Support for syncing history via [synccit](http://synccit.com/) or reddit gold would be a nice addition.

**Comment by FISHunderscore** [comment]
Also it appears that the synccit dev has a [guide on implementing it](https://github.com/drakeapps/synccit).

**Comment by l3d00m** [comment]
Can you give me a short explanation of what this is and what advantages it has?

**Comment by Alexendoo** [comment]
It syncs visited, often called purple, links across clients, meaning you don't for instance read the same post twice on two different devices by accident. For instance /r/me_irl and derivatives would be irritating without it

**Comment by FISHunderscore** [comment]
Actually, I may have found a flaw in this. I'm pretty sure that Slide doesn't currently have any way of showing whether a post is read or not.

**Comment by l3d00m** [comment]
https://github.com/talklittle/synccit-android

**Comment by okungnyo** [comment]
Last commit "3 years ago"

It seems the project is abandoned?

Shame, it seems like it could be useful.

**Comment by FISHunderscore** [comment]
I believe the dev isn't working on it anymore, but the servers are still up and it works.

[TalkLittle's reddit is fun](https://play.google.com/store/apps/details?id=com.andrewshu.android.reddit) supports it and it works between my PC, phone, and tablet. Maybe see if they'd be willing to lend a helping hand?

**Comment by FISHunderscore** [comment]
Hey! Thanks for adding this!

However, it does not appear to work properly in the new update. Trying with one of my old keys and a new one, I always get "Could not authenticate. Make sure your username and authentication key are correct!" The exact same combination of username and keys works fine using the Chrome extension, and Talklittle's reddit is fun.

**Comment by ccrama** [comment]
You can only use the auth keys for one account at a time, also make sure there are no extra spaces and your internet connection is working. Synccit is working fine for me and can authenticate

**Comment by FISHunderscore** [comment]
The sign in works now! My best guess is that I was trying to use a newly generated auth code before it had been properly put everywhere it should have been on synccit's servers.

Thanks!

**Comment by ccrama** [comment]
Ah, glad it's working now :D
