### ISSUE TITLE
Gilding Posts/Comments

### ISSUE THREAD

**Issue by karlding** [ccrama/Slide#468]
Tapping **Gild Post** opens the URL that the submission is pointing to (if it's a Link submission, or the actual post if it's a self post), regardless of whether it is tapped on the Original Post or a comment.

Not sure if this is an API limitation, but regardless, I don't think the submission URL (ie. an Imgur link) should be opened in the browser, if you're prompting the user to use their browser to gild the comment/post. It'd make more sense to open the URL to the actual post/comment.

**Comment by l3d00m** [comment]
fixed with #493. it was not an api limitiation, but simply a bug
