### ISSUE TITLE
Post not saved should have empty star icon

### ISSUE THREAD

**Issue by plumbe0** [ccrama/Slide#471]
When the action dialog comes up upon tapping the three dots in a post, you have the option to save a post. As of now, saving/unsaving posts only has text feedback. It should have also visual feedback: by default the unsaved posts should show the `star border` icon (available in the MD icon library) and the saved posts should have the full star (like they do now).

**Comment by Alexendoo** [comment]
As an alternate/addition, colour the star gold when saved

**Comment by plumbe0** [comment]
I don't think that would follow MD specs

**Comment by Alexendoo** [comment]
See inbox for an example of colouring icons, of course it would be fine.

**Comment by okungnyo** [comment]
Is this being considered or implemented?

I just would like to be able to tell at a glance whether the post/comment is one that I have saved, or not.

I'm just so used to this feature from using Relay for Reddit that I just can't get used to a Reddit app without it.

Star icon filled = post/comment has been saved
Empty star icon = post/comment that haven't been saved

**Comment by ccrama** [comment]
Now it's colored!
