### ISSUE TITLE
HTML entities are not correctly decoded

### ISSUE THREAD

**Issue by plumbe0** [ccrama/Slide#472]
Some HTML entities are not correctly decoded (and therefore displayed). i.e `&` is rendered as `&amp;`. I caught this issue in post titles and comments flairs, but i don't know if it happens elsewhere.

![img_20151109_133929](https://cloud.githubusercontent.com/assets/15671077/11033910/802788ac-86e7-11e5-87fe-56f7240c69ed.jpg)
![img_20151109_134406](https://cloud.githubusercontent.com/assets/15671077/11033975/0858c9de-86e8-11e5-815f-fdec31b6e7c5.jpg)

![img_20151109_133538](https://cloud.githubusercontent.com/assets/15671077/11033920/9209cf26-86e7-11e5-8255-1d6fdd651ed9.jpg)

**Comment by l3d00m** [comment]
This is a bug with JRAW

**Comment by plumbe0** [comment]
![_20151114_092042](https://cloud.githubusercontent.com/assets/15671077/11162793/aeacea78-8ab1-11e5-8cf4-69a9631a0943.JPG)
Found also when sharing a link.

**Comment by l3d00m** [comment]
Happening again on  70b39bf.

**Comment by ccrama** [comment]
Fixed for real this time!
