### ISSUE TITLE
Collapsed comments should remember their state

### ISSUE THREAD

**Issue by mAbubakr** [ccrama/Slide#473]
If a comment is collapsed, it should remain collapsed until it is tapped again by the user. Sometimes the comment's state is not stored and can result in some odd and not so user friendly behaviour. For example, say I am reading some long comment thread and I collapse some children to make it easier to navigate. Once I am done, I collapse the parent and move on to the next comment. Later on maybe I come back to this comment thread to reread something (such as when things get meta and you want to understand the reference **or** if you just did not read the comment carefully and forgot), once I open the parent, all it's children automatically open too resulting in a really long thread.

It may be easier if the previously collapsed children remain that way until the user manually opens them again. I don't think opening a parent should automatically open all children.

**Steps to reproduce:**
1. Collapse a child comment
2. Collapse the child's parent comment
3. Tap to open the parent comment
4. Previously collapsed child comment is now also opened

**Comment by ccrama** [comment]
Although it is annoying, it is not possible to do this with the way we have implemented the CommentAdapter. This might be something we do in the future, but is not something that will be possible before 4.5

**Comment by ccrama** [comment]
Well after some debate among the contributors, I have implemented this for v5.3!
