### ISSUE TITLE
Add a way to quickly return to the top of a comment thread

### ISSUE THREAD

**Issue by yngwi** [ccrama/Slide#474]
Sometimes it is necessary to return to the top of a long comment thread to check out the original post again or to refresh the contents of the thread for new answers. Either an icon in the top bar or in between the previous-next comment arrows (or something else) would be great.

**Comment by l3d00m** [comment]
How about long pressing the comment nav arrow? Just a showerthought I just had.

**Comment by yngwi** [comment]
Yes, that sounds reasonable...

**Comment by okungnyo** [comment]
That sounds like a great idea.

**Comment by l3d00m** [comment]
implemented it. Long clicking on the 'up' comment arrow brings you to the top of the page with the next release!

**Comment by okungnyo** [comment]
Will long-pressing the down arrow bring you to the bottom too?

**Comment by l3d00m** [comment]
nope, not currently. That one was a bit harder to implement and useless in my opinion

**Comment by okungnyo** [comment]
OK, thanks.

**Comment by yngwi** [comment]
Great, thanks!
