### ISSUE TITLE
Button to revisit the link while viewing comments

### ISSUE THREAD

**Issue by isiah-lloyd** [ccrama/Slide#481]
Often I see a comment far down in a thread and want to look at the link again. I'd have to scroll all the way up and lose my place. It would be awesome if this could work with self posts too

**Comment by l3d00m** [comment]
Somehow related to #474

**Comment by Alexendoo** [comment]
Long pressing the down arrow could restore the user to the place where they came up from

**Comment by ccrama** [comment]
Done, now hit the 3 dot menu and click "Open content"
