### ISSUE TITLE
3 things

### ISSUE THREAD

**Issue by silverAndroid** [ccrama/Slide#485]
1. There's a bug I noticed while surfing through r/Android 
http://imgur.com/YIXDnCC

2. How do I submit a post? I've been looking for the longest time and I still can't find it and I'm using version 4.3.1 
http://imgur.com/aq5RhSo
http://imgur.com/IVNeLug
http://imgur.com/R1MFYqS

3. Unsubscribing and subscribing to subreddits is really annoying because of the fact that most of the time, the settings don't save

**Comment by l3d00m** [comment]
1. We aware of it, thanks for your report. 
2. Sidebar > Profile > Submit a Post

**Comment by Alexendoo** [comment]
3. is likely due to #459
