### ISSUE TITLE
Night mode

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#49]
Well, daytime-based automatic theme switching. Could be a pro feature, like it was in QKSMS back when it was proprietary. Here's how I envision it working.

Settings category, titled Night Mode
* Nighttime start time selector
* Nighttime end time selector
* Nighttime light/dark/black selector
* Nighttime Default Theme selector
* Option to override Subreddit Themes with Nighttime Default

**Comment by ccrama** [comment]
Would night use the dark or amoled theme? I like this idea

**Comment by The0x539** [comment]
>nighttime light/dark/black selector

**Comment by l3d00m** [comment]
Added.
