### ISSUE TITLE
Add activity transition when coming from a post to the comment menu

### ISSUE THREAD

**Issue by rosenpin** [ccrama/Slide#490]
Here is what I mean
![Example](http://i.imgur.com/Vpacw79.gif)
Think of the contact list as the submissions overview and the contact clicked as a single submission.

**Comment by l3d00m** [comment]
image not available :(

**Comment by rosenpin** [comment]
Fixed

**Comment by ccrama** [comment]
This won't work with our options and how comments slide, sorry!
