### ISSUE TITLE
Add long press support to posts

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#50]
It would be good to have access to a few features without entering comments, for instance the ones provided without entering a post on the desktop version, which are

* votes
* share
* save
* **hide**
* **report**

Additionally, as it stands there does not appear to be any way within the app to hide or report posts

**Comment by ccrama** [comment]
Really great idea. Adding this now.

**Comment by The0x539** [comment]
This is basically part of the "Collapsible" actionbar option that's in The Great Customization Overhaul, though.

**Comment by ccrama** [comment]
Done with 4a11cea2144a2e016eb28503aaa0cb31337ef935. Hiding done with e9420a1c25eaa797cb3235a25eb865f5d9b96987.

Report will be coming later!
