### ISSUE TITLE
Inconsistent upvote / downvote buttons position 

### ISSUE THREAD

**Issue by TomerRosenfeld** [ccrama/Slide#501]
While scrolling in the main activity the upvote button is on the left as it should but in the comment view of a post its on the right. 

![example](http://i.imgur.com/xPzJOSQ.png)

**Comment by SolarAquarion** [comment]
Have you ever joined IRC?

**Comment by TomerRosenfeld** [comment]
I'm not sure what you mean.

**Comment by l3d00m** [comment]
This is fixed with one of my last pro. I think it was #492. 
@TomerRosenfeld: IRC is a 'chatroom', where we coordinate this project.
