### ISSUE TITLE
More accent color options

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#506]
Accent color choices are lacking and make it so you have to use the same color multiple times for different subreddits. The accent choices should have just as many color choices as main color.

It should also prevent you from choosing the same color for main and accent color. Like give an error or just switch it back to default. Something like that.

**Comment by plumbe0** [comment]
I second this, main color and accent color should have the same choices available. Why is it hard if it has already been done for the main colors?

**Comment by The0x539** [comment]
It's done differently, somehow.

**Comment by ccrama** [comment]
I have added more since this issue was created, now has pretty much all the accent color options in Material design (one per color swatch)
