### ISSUE TITLE
Use more MaterialDialogs

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#507]
Color choosers use some hybrid semi-material dialog, right? These and other non-materialized dialogs should be converted to MaterialDialogs.

This should also fix the weird padding issue found in KitKat.

**Comment by alexsmithfanning** [comment]
If I'm not mistaken, I think @afollestad has his own implementation of a color picker in his library. I think it looks really good.

**Comment by ccrama** [comment]
They are all using material dialogs. I am not going to change my slider system

**Comment by afollestad** [comment]
Just gonna put this here 😉

![affix_20151115_212844](https://cloud.githubusercontent.com/assets/1820165/11173756/f2ccddd8-8bdf-11e5-843b-8015784a6858.png)

**Comment by alexsmithfanning** [comment]
Still not enough?

Here's another. **On KitKat**: https://goo.gl/1gRteh

Tempting, isn't it @ccrama?

**Comment by Alexendoo** [comment]
The restricted set of colours were chosen intentionally

**Comment by alexsmithfanning** [comment]
I don't like it as far a vertical space goes. There's a ton of space on screen being wasted with the current implementation.

I'd like it more if the two choosers were vertical instead of horizontal.

**Comment by afollestad** [comment]
My color chooser is customizable, as is everything else in my library.

**Comment by Alexendoo** [comment]
The colour picker takes on the form of a modified slider, sliders are typically horizontal for a reason and I'm not sure breaking that makes much sense here

**Comment by ccrama** [comment]
@afollestad It's not that I don't like the color chooser dialog, it looks great! I just prefer the slider as it lets me preview the look of the different colors without actually choosing one and having to go back and forth

**Comment by alexsmithfanning** [comment]
The solution to everything: make it a setting!

Or do a poll.

**Comment by ccrama** [comment]
No, I'm keeping it the way it is. Sorry :(
