### ISSUE TITLE
Most actions without an internet connection causes a crash

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#51]
Very similar to #33, open the app with an internet connection, then activate aeroplane mode and swipe through to a sub

**Comment by Alexendoo** [comment]
Also appears to crash without an internet connection when you try and load anything new. Profiles, posts, submitting a post

**Comment by ccrama** [comment]
Fixed with 85fb67c73a8fb0d4d3aea2da27ddc44867924ca4
