### ISSUE TITLE
Slide is erroneously counting votes

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#510]
I have no idea how to explain what's happening. I just know that it only happens when viewing a users profile and I can very easily reproduce it.

If you look at the number of upvotes and downvotes the user has on each post, it fluctuates. I tested this on the desktop by refreshing the page and the count wasn't changing like that.

Video: https://goo.gl/vaqwe2

**Comment by Alexendoo** [comment]
Reddits vote fuzzing can cause situations such as this though it's strange that it would reload the score simply by moving off screen.

Go to your frontpage and hit ctrl r a bunch you can often see a post fluctuating

**Comment by ccrama** [comment]
Yep, what Alexendoo said.

**Comment by okungnyo** [comment]
Slide updates the votes/scores in realtime?!

**Comment by Alexendoo** [comment]
I didn't see any requests happening when doing the same thing on my end, it's possible it's a KitKat bug but I have no KitKat device to test this with

**Comment by alexsmithfanning** [comment]
It's not just KitKat. I can reproduce this on my friends Nexus 5X (rooted, stock Android, no Xposed).
