### ISSUE TITLE
Settings Save Automatically (Save button is misleading)

### ISSUE THREAD

**Issue by karlding** [ccrama/Slide#511]
For example, if a user goes to **Settings** > **Notification Settings**, and unticks **Check for new messages every 15 minutes**, and then presses the back button on their device without tapping **Save**, the user would expect that their changes weren't updated, since that is what the **Save** button is for.

However, this is not the case, and the settings are updated immediately, regardless of whether the **Save** button is pressed or not.

**Comment by okungnyo** [comment]
Was it fixed?

**Comment by l3d00m** [comment]
Yes, the button is now renamed to done.

**Comment by okungnyo** [comment]
??

I thought the issue was about the Save/Done button being misleading?

"the settings are updated immediately, regardless of whether the Save button is pressed or not."

**Comment by l3d00m** [comment]
The issue was that 'save' indicates that the settings are only saved when this button is clicked and therefore when it's canceled that this won't happen. 'Done' is more neutral and doesn't indicate that.

**Comment by okungnyo** [comment]
Oh OK.
