### ISSUE TITLE
Highlight selected subreddit in the drawer

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#512]
* [x] WONTIFX The subreddits portion of the navigation drawer should have a separator and a subheader (e.g. "Subreddits").

* [ ] When an item is selected, it should change color to the accent color of Slide.

**Comment by l3d00m** [comment]
I don't the first one would be so useful because it would take much more space, and you already need to scroll down to reach them

**Comment by alexsmithfanning** [comment]
Its just a subheader. Its also part of the design guidelines.

**Comment by l3d00m** [comment]
Yeah, I know, but material design doesn't they you should add a subheader for everything. IMO it would be a waste of space.

**Comment by ccrama** [comment]
Yeah, it's pretty obvious what the content below it is

**Comment by alexsmithfanning** [comment]
The text is also bold. It shouldn't be bold.

**Comment by Alexendoo** [comment]
Which text is bold?

**Comment by ccrama** [comment]
I don't think this will be implemented in the future, I'll close it for now
