### ISSUE TITLE
App doesn't display images inline when logged in

### ISSUE THREAD

**Issue by kindall** [ccrama/Slide#516]
I'm looking to get the sweet Reddit experience I see in the screen shots. And I got that the first time I started it up. But as soon as I log in, it turns plain and boring. Instead of seeing nice big beautiful images, I see text that says "Image" which I then have to touch to see the image. Joined the alpha community to see if there was a newer version that fixed that, but looks like not.

I don't see any way to log out of my account or I'd try that. However, if I clear the app's data, it works fine again until I log in.

Here's what I see... looks a little plain:

![screenshot](https://cloud.githubusercontent.com/assets/4211579/11136455/73ee1442-8963-11e5-8fd9-b358e1bdc468.png)

**Comment by l3d00m** [comment]
Check on reddit.com > preferences if you have thumbnails disabled.

**Comment by l3d00m** [comment]
Merging into #519
