### ISSUE TITLE
Quarantined subreddits incorrectly reported as non-existing

### ISSUE THREAD

**Issue by karlding** [ccrama/Slide#518]
Trying to visit a [quarantined subreddit](https://reddit.zendesk.com/hc/en-us/articles/205701245) returns the message saying that the subreddit doesn't exist (for example, /r/ferguson).

On the website, trying to visit a **quarantined subreddit** will display the message "Communities that are dedicated to shocking or highly offensive content are quarantined. Content in this community may be upsetting. Are you certain you want to continue?"

**Comment by l3d00m** [comment]
Merging into #498
