### ISSUE TITLE
Edit reddit.com preferences 

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#519]
This enhancement would be a very low priority, but I thought it would be good to have it on the issue tracker.

Even if it's just a WebView of https://www.reddit.com/prefs/, it would be useful.

It would also prevent confusion like this: https://github.com/ccrama/Slide/issues/516

**Comment by Alexendoo** [comment]
Merging into #372, thanks forgot about that one.

**Comment by okungnyo** [comment]
Cool, how will it be done? A WebView link to reddit.com/prefs?

Or actually incorporating reddit.com prefs with a UI?

**Comment by l3d00m** [comment]
it'll will only be a link now, incorporating reddits prefs with a ui would be a little bit too much at the moment.

**Comment by okungnyo** [comment]
Yeah, I agree.

But when that does happen, then no Reddit app will compare to Slide, and it will become THE Reddit app.

**Comment by alexsmithfanning** [comment]
It already is THE Reddit app.

**Comment by okungnyo** [comment]
Yeah, but I mean like have a feature that no Reddit app has EVER had.

No Reddit app has EVER tried to incorporate reddit.com/prefs as a UI.

**Comment by l3d00m** [comment]
That is true. I don't know if it is possible through the API though.

**Comment by Alexendoo** [comment]
It seems pretty easy to do through the API. https://www.reddit.com/dev/api#GET_api_v1_me_prefs

Reddit is fun has this implemented, at least the ones that affect the app IIRC

**Comment by l3d00m** [comment]
Then we should implement that in the future. At the moment a link in the settings should be enough though.

**Comment by okungnyo** [comment]
I look forward to it!

**Comment by l3d00m** [comment]
Thanks for the suggestion!

**Comment by okungnyo** [comment]
Thank you for considering it!

**Comment by ccrama** [comment]
There is a setting screen for this in 4.5.1!
