### ISSUE TITLE
Tapping on a "POST" opens the "below" one instead.

### ISSUE THREAD

**Issue by Snagg57** [ccrama/Slide#520]
Slide Version 4.3.2 (#slide APK)

The latest alpha has an issue with the incorrect post being open when tapping on a post.

For example: If I tap on the FIRST post in a subreddit. The SECOND post will be opened instead. If I tap on the SECOND post in a subreddit. The THIRD post will be opened instead. etc....

EXAMPLE VIDEO:
https://drive.google.com/open?id=0B0_-DHdOSWufY2tQdFBYSEhtSFE

**Comment by l3d00m** [comment]
closed because snagg57 opened it

**Comment by l3d00m** [comment]
and snagg is really bad!

**Comment by ccrama** [comment]
That was a pre-alpha apk heh

**Comment by l3d00m** [comment]
kill it with fire
