### ISSUE TITLE
Account selector/switcher in comment window

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#521]
Scenario:
- You are deep in a comment thread and see a comment about cheese.
- You think "this is a perfect opportunity to make a funny joke about cheese with my novelty account /u/ILOVECHEESE111111!"
- Now imagine: you tap the reply button, and above the text field is a "Comment as..." dropdown menu that allows you to switch to a secondary account JUST for that comment. So you don't have to go back to the main menu, you don't have to switch to your novelty account, and you don't have to spend five minutes finding that specific comment in that specific thread..

I think it would be useful.

**Comment by ccrama** [comment]
I really like this idea!

**Comment by okungnyo** [comment]
Awesome!

**Comment by bb010g** [comment]
I think Relay is landing this now.

**Comment by ccrama** [comment]
Added for the next update
