### ISSUE TITLE
Flairs and tags improvement

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#522]
User flairs and comment tags should use "chips" instead. 

You can see the spec on chips here: http://www.google.com/design/spec/components/chips.html

**Comment by Alexendoo** [comment]
Chips are a fair bit larger than the current implementation, they're able to be tapped after all. The rounding could be tweaked to match though.

**Comment by alexsmithfanning** [comment]
I think it'll be fine. We just have to be strategic about how we place them, that's all.

**Comment by ccrama** [comment]
Chips are way too big, I experimented with it at one point. The point of chips is a selection dialog, which would not fit flairs and tags

**Comment by alexsmithfanning** [comment]
Oh. Okay!
