### ISSUE TITLE
Subreddits tabs improvement

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#524]
Tabs should be offset as seen in the "default app and scrollable tab bar" section in the guidelines for tabs.

If I understand the spec correctly, I think the selected tab should be the same color as the accent color. But I'm not sure.

**Comment by The0x539** [comment]
Yeah, I do think you're right on the first point.

However, isn't the selected tab already the accent color?

**Comment by alexsmithfanning** [comment]
I don't think so. Not on KitKat at least.

**Comment by ccrama** [comment]
What does it look like on KK?

**Comment by ccrama** [comment]
I believe this has been fixed for a while (on KK too)
