### ISSUE TITLE
Web-browser-like tabs

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#525]
This is an idea for when Slide is so feature-complete that the developer doesn't know what features to add anymore.

Scenario:

* you are browsing an AskReddit thread

* suddenly, you want to visit /r/Android. But currently, this means that you will lose your 'progress' in the AskReddit thread, and if you ever want to continue reading that thread, you will have to manually find your place again, which is basically impossible for mortals. This forces us to have multiple Reddit clients installed at once.

* But no more. Imagine: web-browser-like 'tabs', but for subreddits.

* You would simply tap the '+' button (in the FAB or elsewhere), then [New tab], and this would open a new 'tab' that would allow you to leave the AskReddit thread open, and at the same time allow you to visit /r/Android or any other subreddit that you wish.

* Repeat until you have 100 'tabs' open.

It would be nice.

**Comment by ccrama** [comment]
This is rather niche and will not work with the way Slide's views now behave (as of v5)
