### ISSUE TITLE
Hide pro features

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#529]
There should be an option in settings that hides any trace of Slide Pro. Like the Shadowbox Mode button on the toolbar would disappear, and the Multi-Column Mode button from the sidebar would disapear. Some users might find this nice so they can remove some of the clutter. Like me.

**Comment by l3d00m** [comment]
Multi column button is moved to settings with the next version. If you buy pro, the pro button in the drawer and the pro in the settings will dissappear too.

**Comment by alexsmithfanning** [comment]
Yeah but I want it to be so when you tick the setting, no traces of pro are there. Not even "Get Pro" in the settings.

**Comment by Alexendoo** [comment]
Doesn't make economic sense

**Comment by ccrama** [comment]
That defeats the purpose of "Pro" anything
