### ISSUE TITLE
Ability to turn off auto-hide action bar

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#534]
A minor quibble I have is that scrolling up and down even just a little bit makes the action bar jump in and out like a madman.

An option to disable this--and have the action bar always in view--would be much appreciated.

**Comment by Alexendoo** [comment]
@okungnyo with the latest update(s) the action bar doesn't move everything else around when it jumps in/out, do you still wish for the option to have it fixed?

**Comment by ccrama** [comment]
This jumpy scrolling has been fixed in the v4.6.1 update, I don't think this is applicable anymore
