### ISSUE TITLE
A method to download .gifv/gfycat links as .gif files

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#536]
For now, the first [Floppy save] button is broken: #260 

But when that gets fixed, I would also like to suggest the ability to download .gifv/gfycat links as .gif files.

This is because .gif files are easier to share and view in chat messengers.

**Comment by Nxt3** [comment]
So this might actually be pretty easy. Turns out the raw gif form of any gfycat image follows the same URL pattern:

The gfycat https://gfycat.com/IncompleteSatisfiedCanine

would become

https://giant.gfycat.com/IncompleteSatisfiedCanine.gif

We would just have to alter the URL. :)

**Comment by tryton-vanmeer** [comment]
Would love this option since I like to share the gifs on hangouts and its a pain to open in browser, add gif for gfycat links, or in the case of imgur change gifv/mp4 to gif

**Comment by ccrama** [comment]
Done, now there's an option to download the base content (whether it's a gif, gifv, or animated PNG or JPG)

**Comment by okungnyo** [comment]
So after we click the download button, we get a pop-up with those choices?

**Comment by ccrama** [comment]
No, the bottom sheet has 2 options for download mp4 or download gif
