### ISSUE TITLE
Show a preview of multi-column mode/other premium features when the relevant button is tapped.

### ISSUE THREAD

**Issue by GermainZ** [ccrama/Slide#54]
Currently, only a text message is shown with a link to the Play Store. A small image preview (similar to the tutorials) would make it clearer without requiring the user to leave the app.

**Comment by The0x539** [comment]
Been discussed in IRC, where there's just a "Go Pro" drawer entry that contains a pro promo thingy.

**Comment by ccrama** [comment]
Merged with #491, basically the same concept

**Comment by ccrama** [comment]
Now you have 10 previews for shadowbox and gallery modes :)
