### ISSUE TITLE
[Question] no in-app browser?

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#546]
According to Settings, there is an internal browser.

But whenever I tap on a link, it opens in an external browser.

What am I doing wrong??

**Comment by l3d00m** [comment]
You have to open links in Chrome, otherwise custom tabs won't work. If you already set another browser as default, you have to 'clear default' for that app in android system settings.

**Comment by okungnyo** [comment]
Could Slide have a WebView internal browser like Sync or Relay?

I don't use Chrome custom tabs because I don't want Reddit links to spam my Google History.

**Comment by l3d00m** [comment]
Mhh, I don't think so. @ccrama pls

I don't think it would add the links to your history.
