### ISSUE TITLE
Thread selection sometimes broken

### ISSUE THREAD

**Issue by 2fst4u** [ccrama/Slide#547]
When selecting a thread I will be dropped into an unrelated thread maybe 1,2,3 or even more threads down the page. Backing out and trying again gives the same results. The only way to get where I want is to swipe along until I find the one I wanted.

Recently has happened in a private multi.

**Comment by Snagg57** [comment]
Ah yes this bug. I had this bug using a alpha APK. If this is similar to issue 520 it should be fixed soon™.

https://github.com/ccrama/Slide/issues/520

**Comment by 2fst4u** [comment]
Ah yes I didn't see that one. To add though: it isn't always the next one down. Sometimes I don't even know where I am and give up

**Comment by Alexendoo** [comment]
I believe this is fixed now
