### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#550]
Crash on startup for I'm assuming KitKat devices.

**Comment by rosenpin** [comment]
Can you please provide the event log?

**Comment by ihatetothink** [comment]
Yes, that happened to me aswell, then decided to contribute a fix, but current master branch doesn't crash. or maybe was some kind of old setting. To me happened today only and I think it had updated recently

**Comment by ccrama** [comment]
Fixed in latest commit

**Comment by ccrama** [comment]
And pushed to the play store
