### ISSUE TITLE
Remove "SecretConstants" file, or dynamically enter developer mode if it isn't found.

### ISSUE THREAD

**Issue by ColinChartier** [ccrama/Slide#558]
Please remove this file and put the public key in directly, or add some other mechanism for collaborators to easily compile your project.

The google developer guidelines say "To keep your public key safe from malicious users and hackers, do not embed it in any code as a literal string. Instead, construct the string at runtime from pieces or use bit manipulation (for example, XOR with some other string) to hide the actual key. The key itself is not secret information, but you do not want to make it easy for a hacker or malicious user to replace the public key with another key." [http://developer.android.com/google/play/billing/billing_best_practices.html]

However, this is to stop people from putting their own public keys and unlocking features without paying for them.  In your case, it is trivial to simply extract the dex file and get the constant from the file.  It's even easier to just compile the app with all IAPs purchased, since this project can be compiled by anyone.

I can understand if you want to keep it private, but if you do go that route, you should add a case in the code where no key was found so that the project can still compile.

**Comment by l3d00m** [comment]
Those guidelines are for closed source apps. Imo it's wrong to publish the billing key to github.

**Comment by ColinChartier** [comment]
My point was that the only reason you want to obfuscate your public key is to make it difficult for others to  replace it directly in the dex with their own, as to control the IAPs easily.  Assuming you must do the same in an open source app is silly, because you can trivially just unlock the features and compile the app yourself, no need to touch the public key at all.

There is no danger in others having the app specific public key. They can't use it in their own apps, and they can already trivially do what hiding the key protects you from.

**Comment by rosenpin** [comment]
It's as easy as creating a "Secret Constants" class yourself and adding the keys there, git will ignore it automatically.
