### ISSUE TITLE
Tabbed interface improvements.

### ISSUE THREAD

**Issue by GermainZ** [ccrama/Slide#56]
- Provide an option to disable the tabbed interface entirely, for those who prefer to use the navigation pane instead.
- Make it possible to only show pinned subs in the tabbed interface, as it gets too busy to be useful otherwise.

**Comment by szeichorn** [comment]
1+

**Comment by l3d00m** [comment]
+1

**Comment by ccrama** [comment]
Done with 086f82c63486cd7aa92100e6ba8bf7fcde066790
