### ISSUE TITLE
Gilded posts do not have any indication of being guilded (missing gilded icon)

### ISSUE THREAD

**Issue by karlding** [ccrama/Slide#561]
Gilded comments (Picture 3) will show the gilded star icon, but if the Original Post gets gilded, no indication is shown (Pictures 1 and 2).

This is the [post](https://www.reddit.com/r/gaming/comments/3t0bz1/mrw_skyrim_says_you_cant_fast_travel_when_enemies/) in the screenshots

![Skyrim](http://i.imgur.com/X5aWauN.png)

![Skyrim 2](http://i.imgur.com/NOmTPci.png)

![Skyrim Comment](http://i.imgur.com/LnD6uuM.png)

**Comment by l3d00m** [comment]
fixed in #562
