### ISSUE TITLE
Add option to grab lower resolution preview images.

### ISSUE THREAD

**Issue by GermainZ** [ccrama/Slide#57]
Such an option would be useful for users with slower connections or bandwidth caps.

**Comment by l3d00m** [comment]
Jraw supports this too now: https://github.com/thatJavaNerd/JRAW/commit/55fd284c815324aadbbdda4bf64a171d00408136#diff-de1f7f60345237c58473717fdb286e8bR1

**Comment by ccrama** [comment]
There is now a low-data mode in General Settings!
