### ISSUE TITLE
More stuff in the [i] section when viewing profiles

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#571]
* [ ] [A] - next to username for admins

* [ ] [...]'s snoovatar

* [X] *WONTADD* give reddit gold to [...]

* [X] redditor for [...]

* [ ] gifts on behalf of /u/[...] have helped pay for [...] hours of reddit server time.

* [x] MODERATOR OF

* [ ] PUBLIC MULTIREDDITS

* [X] TROPHY CASE

* [X] Is friend or not

Sample profile (of a Reddit admin account) where all this can be seen: https://www.reddit.com/user/acidtwist

Edit: also "[A] next to username for admins"

Edit 2: also added snoovatar and gifts on behalf ...

**Comment by ccrama** [comment]
Now it shows public multis! The other items might be a bit overkill, closing for now. If you think any of the non-completed ones are really worth it, feel free to re-open

**Comment by Controless** [comment]
I think the MODERATOR OF is pretty important but I may be biased because I'm a power mod. ¯\_(ツ)_/¯

**Comment by okungnyo** [comment]
I think the " [A] - next to username for admins" would be pretty handy.
