### ISSUE TITLE
Add a text to notify about empty pages

### ISSUE THREAD

**Issue by Soberat** [ccrama/Slide#576]
Adding some kind of string to pages that are empty would clarify if something is there but it didn't load. Maybe add separate strings for empty, closed or banned subs?

**Comment by l3d00m** [comment]
This is a good idea. Add also an information if a sub isn't loading because NSFW posts are deactivated.

**Comment by ccrama** [comment]
I believe Slide does this right now with "No more posts" or "Error loading content" titles.

**Comment by Alexendoo** [comment]
No more posts appears to show when posts run out, but not when subreddits are empty (see [/r/empty](https://www.reddit.com/r/empty)), there the spinner shows indefinitely still

**Comment by ccrama** [comment]
Now it won't perpetually load on submission views!
