### ISSUE TITLE
image slideshow: GIFs don't start from the beginning

### ISSUE THREAD

**Issue by c727** [ccrama/Slide#577]
https://www.youtube.com/watch?v=ScXwXhBdpcI&feature=player_detailpage#t=12

**Comment by l3d00m** [comment]
i don't get it, sorry. Can you explain that?

**Comment by SZE2** [comment]
This happens to me consistently.

What info can I give you to pin this bug down?

Screencaps, logs etc?

**Comment by ccrama** [comment]
This is because the ViewPager loads the side fragments at the same time as the main fragment, and it plays after loading the fragment. Easy fix would be to restart the MediaVideoView on the page change listener

**Comment by ccrama** [comment]
Fixed!
