### ISSUE TITLE
Can't scroll in [Choose a sorting type]

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#579]
I can't scroll down past [Controversial Today].

Is it just me?

**Comment by l3d00m** [comment]
There isn't anything below Controversial Today

**Comment by okungnyo** [comment]
But there is on reddit.com:

https://www.reddit.com/controversial/

**Comment by c727** [comment]
He means last hour/week/month/year/all is missing for controversial

**Comment by l3d00m** [comment]
Yeah I know. He created a new issue for that so I won't reopen this.

**Comment by okungnyo** [comment]
??

**Comment by l3d00m** [comment]
My fault, I haven't read the description of that issue
