### ISSUE TITLE
A [Tips] section for hidden features that aren't easy to discover

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#580]
As mentioned in https://github.com/ccrama/Slide/issues/536

**Comment by okungnyo** [comment]
"can't see NSFW posts" seems to be the #1 mistakenly-considered-a-bug issue, it would be nice if it was included in this future [Tips] section.

**Comment by l3d00m** [comment]
I think it's a better idea to fix the underlying issues instead of doing a tips section. It's usually a bad ux if we would need something like this.
