### ISSUE TITLE
Follow order of reddit.com's sorting types

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#581]
In Slide, the order is: Best, Top, Q&A, New, Controversial, Old

But on reddit.com, the order is: Best, Top, New, Controversial, Old, Q&A

It is a cosmetic change, but I thought I would put it on the issue tracker.

**Comment by l3d00m** [comment]
Also #579

Add more controversial sorting options.

**Comment by okungnyo** [comment]
And [Gilded], [Wiki], and [Promoted], too.

Is that possible?

**Comment by l3d00m** [comment]
What do you mean by this?

**Comment by okungnyo** [comment]
The tabs on reddit.com, next to [hot], [new], [controversial], and [top].

**Comment by l3d00m** [comment]
Wiki is already in the sidebar and promoted is probably something the user isn't interested in.

**Comment by okungnyo** [comment]
OK, just [gilded] then?

(And also to follow reddit.com's sorting order, [top] and [controversial] should be switched.)

So to recap:

* More controversial sorting options
* Switch order of [Top] and [Controversial] to match reddit.com's sorting order
* [Gilded] sorting option
