### ISSUE TITLE
Remove redundant "Settings" label in Settings (there are several)

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#585]
As mentioned here: https://github.com/ccrama/Slide/issues/573

Because the user is already in [Settings], it seems redundant to have "Settings" in the names of the sub-menus.

* If you go into the [General] sub-menu, the titlebar still says "General Settings", instead of "General".

* If you go into the [Base Theme] sub-menu, the titlebar says "Edit Theme", instead of "Base Theme".

* [Default Layout] and [Alternative Layout] do not have titlebars. I think it would be more consistent if they did.

* Subreddit Theme Settings

* Floating Action Button Settings

**Comment by l3d00m** [comment]
It doesn't need a new issue if it's already mentioned in #573

**Comment by okungnyo** [comment]
Isn't it better to have every separate issue in its own entry, so that each one can be closed as each is fixed?

I only ask because that's the way it's been for every other issue tracker I've contributed to.

**Comment by l3d00m** [comment]
Normally yes, but those issues are so small that it is much easier to keep track of them when they are all in one.

**Comment by okungnyo** [comment]
Ok, are they easy fixes?

**Comment by l3d00m** [comment]
Yes, I just have to rename one line of code for the most of them. 
The other ones needs probably avery small amount of changed lines too.

**Comment by okungnyo** [comment]
That's great to hear!

If it's that simple, then I have a couple more suggestions I will add to #573

**Comment by l3d00m** [comment]
Feel free to add them. I will probably take care of them because they are relatively small.

**Comment by okungnyo** [comment]
Thanks.
