### ISSUE TITLE
Clean up "sort by" dialog

### ISSUE THREAD

**Issue by szeichorn** [ccrama/Slide#59]
as of now, the list is longer than the screen!

Maybe make top and controversial one item each, and if they are picked, it changes to let you choose timeframe.

(BTW, this is how another app handles it:

![](http://i.imgur.com/2oXY8Wi.jpg)

![](http://i.imgur.com/iJqUn59.jpg)

I hope you don't mind me adding this)

**Comment by ccrama** [comment]
Changed to use the radio button system!
