### ISSUE TITLE
Dialogs don't follow button and text placement specifications

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#591]
The accent colored banner in dialogs aren't part of the spec and make it harder to make text viewable in the title. The title should just be black (I'm pretty sure its black) for white dialogs or white for black dialogs.

There should also be explanation changes. Instead of the dialog for Slide Pro saying what it does now, it should just say "This is a Slide Pro feature. Would you like to purchase Slide?" with the two possible choices being "Yes" and "No", with yes being on the right and no being just to the left of the yes button.

Buttons on dialogs are also not formatted correctly. The color chooser dialog (maybe?) should have an "Apply Changes" and a "Discard" button with the accent color of the current subreddit being the button text color.

Google explains it better than I ever could. Here's the guidelines for dialogs: http://www.google.com/design/spec/components/dialogs.html#

**Comment by ccrama** [comment]
I believe this is all fixed, Slide has been using a library to handle dialogs for some time now which fixed this
