### ISSUE TITLE
Scheduled backups

### ISSUE THREAD

**Issue by Soberat** [ccrama/Slide#596]
As backup feature is really nice, doing them manually kinda defeats the purpose of storing them in cloud, so having them being made on a set basis (every x hours or days,  after changes are made) would make it even better

**Comment by Alexendoo** [comment]
Another possibility, having it backup automatically whenever the user changes a setting

**Comment by ccrama** [comment]
The issue with this is it uses a lot of data and each backuo/restore counts against my monthly quota from Google

**Comment by okungnyo** [comment]
How about when the user changes a setting and then tries to back out of Settings, a pop-up dialogue shows up and says:

* You have made changes to some settings. Would you like to backup to the cloud now? [YES / NO]

And if the user changes a setting, but Slide is force-closed before it can show that dialogue, (i.e. the user opens [Recents] and closes Slide from there, or Slide crashes, etc.), then the next time Slide opens, a pop-up dialogue can say:

* Slide has crashed or was closed before the changed settings were backed up to the cloud. Would you like to backup to the cloud now? [YES / NO]

**Comment by Soberat** [comment]
Since we're making it complicated too much, my idea is this:
After changes aren't changed for, let's say, 48 hours, a backup would be uploaded. This would keep it not-so-data-hungry, wouldnt't be as intrusive as @okungnyo idea (a constant popup dialog would be really annoying for devs and end users) and does it's job. So what are your opinions? I'm definitely open.

**Comment by l3d00m** [comment]
I like your idea @soberat. To add something something to it, we should do it only when the user is connected to WiFi to save data.

**Comment by ccrama** [comment]
It's a thing now! You can mange it in the sidebar > top area dropdown > manage offline content!

**Comment by Soberat** [comment]
It was actually about settings backup, but since it's not really necessary I think it can remain closed ;)

**Comment by ccrama** [comment]
Oh. Oh well
