### ISSUE TITLE
No card Mode isn't scaled correctly

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#597]
What the title says. With card mode disabled, text is small and other text is really small.

At least on KitKat it is.

**Comment by rosenpin** [comment]
Can you please provide a screenshot?

**Comment by Alexendoo** [comment]
Becomes pretty difficult to read on a nexus 4

![](http://i.imgur.com/OW0Wza1.png)

**Comment by alexsmithfanning** [comment]
I don't think that's what I'm talking about. Look at my screenshot.

**Comment by Alexendoo** [comment]
What did you think I was referring too?

**Comment by alexsmithfanning** [comment]
Sorry, never mind. I was looking at your screenshot through my phone, I couldn't see it very well.

**Comment by l3d00m** [comment]
That is fixed with the redo of cards and list layout!
