### ISSUE TITLE
More text size settings

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#601]
* [ ] **Separation of text size options for posts and comments**. The text size for posts is big enough, and disproportionately larger than the text size for comments. It would be nice to change the size for one without the other.

* [x] **Larger text size options**. When you are Redditing while you are walking, it helps to have HUGE text size because your hand is wildly swinging up and down. But even with the largest text size in Slide, the comments are still quite small.

**Comment by l3d00m** [comment]
The second one is added with 33b10c5cc95bda037b3b226fd5b8237e65927b3b, I'm not sure if we will add the first one

**Comment by okungnyo** [comment]
Was my comment edited to add the checkboxes? I don't remember writing checkboxes lol.

Well, does increasing text size for comments still make the text size for posts insanely large? Because that's my main gripe. Otherwise, there doesn't need to be separation.

**Comment by l3d00m** [comment]
Yes, @Alexendoo  added checkboxes to all comments with multiple requests. I don't think so, try it out in the next alpha/beta that is coming in a few days

**Comment by okungnyo** [comment]
Yes

**Comment by okungnyo** [comment]
Problem still exists in 4.5.

As I said in the main post, I like to set text size to [Large] so I can read comments while walking.

The problem is, that makes the card text absurdly large. Like, twice as large. The level of disparity is quite jarring.

Why are you not sure you will add it?

**Comment by l3d00m** [comment]
I understand what you mean. We will add this one for sure now! Probably coming with the next update

**Comment by okungnyo** [comment]
Thank

**Comment by 530farm** [comment]
I'm working on this at the moment. I hope to have something today.

**Comment by The0x539** [comment]
Yeah, that text size for post titles is suuper big.

**Comment by 530farm** [comment]
I got independent font sizing working on my fork in the testing branch. The one issue I need help resolving is the default value listed on a cleaninstall is "MediumComment" instead of "Medium".

**Comment by 530farm** [comment]
The independent font sizing is done.

**Comment by ccrama** [comment]
Done in @530farm 's latest commit
