### ISSUE TITLE
Comment cosmetic changes

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#603]
* [x] Show comment edit dates. If a comment has been edited, Relay will show **47 min (edited 20 min)**, whereas Slide will just show **47 minutes ago**

* [x] Show dagger for controversial comments

* [x] Make the separation of the commenter's username and comment karma more obvious. The two are so close together it's confusing at a glance if the number is part of the username or not. Possible solutions: (1) Have the word "points" follow the karma number. (2) Give the comment karma a slightly grey color. (3) Add a separator between the username and the comment karma.

* [x] Add separator-lines between each comment. It's a usability issue, because logically, you should be able to tell where one comment ends and another begins by looking at the color indentations to the left, but realistically, it's confusing without line-separators.

* [x] Bring <user> <points> <timestamp> for posts and comments in same order/format (#652)

**Comment by okungnyo** [comment]
I just checked these in 4.5.

The first one has ot been fixed.

The second one has not been fixed.

The third one has not been fixed.

The fourth one has been fixed. Yay!

The fifth one has not been fixed.

Posts use: [username X hours ago * X points] format
Comments use: [username X points X hours ago] format

It's all horribly inconsistent.

**Comment by ccrama** [comment]
Done and done!
