### ISSUE TITLE
Crash in multicolumn mode after hold-tapping on a comment to upvote/downvote/etc

### ISSUE THREAD

**Issue by ViKomprenas** [ccrama/Slide#604]
Nexus 9, Android 6.0, Slide 4.3.4.

I quite like Slide and bought Pro for multi-column mode (and also to support it of course). It works well, but unfortunately it just crashes if you hold-tap on a comment (to bring up the menu).

**Comment by Snagg57** [comment]
Reproduced Successfully on Slide 4.3.4 Playstore APK

Nexus 6, Android 5.1.1
Landscape Mode with 2 Columns

**Comment by russjr08** [comment]
Here's a bit of logcat output. http://pastebin.com/Z8eMP2Kr

**Comment by l3d00m** [comment]
and heres a [stacktrace](http://pastebin.com/C5Uk4PTB)

**Comment by l3d00m** [comment]
This is fixed now. Thanks for the report!
