### ISSUE TITLE
Syncing subreddits doesn't immediately take effect

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#605]
For example, I removed a sub in https://www.reddit.com/subreddits/, then I opened Slide and tapped [Sync your Subreddits], but the sub didn't get removed. So I figured I had to manually restart the app, and when the app restarted I saw that the sub had been removed.

Maybe restart the app automatically after syncing subreddits? Or tell the user that the app must be restarted for changes to take effect.

**Comment by l3d00m** [comment]
merge into #459
