### ISSUE TITLE
Wiki overhaul

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#611]
The current state of wikis leaves a lot to be desired so I'm sure this can be appreciated as necessary. Let's start with the big one.

#### Load only one page at a time
On the opening of a wiki, load only the index page initially: currently the first page sorted alphabetically is loaded first, but to actually display any page in the current implementation **all** wiki pages must first be downloaded, which takes a fair amount of time longer than it should for small wikis, and an unbearable amount of time for large ones.

The index page has all the links to other pages that the subreddit intends to be accessed normally

#### Remove the tabbed interface
It's nice but not appropriate, wikis on reddit tend to be full of old/unused pages and the navigation in the index page will point to the relevant ones, no need to put effort into creating a UI to navigate them manually. In addition as the pages are often dependant on one another unlike subreddits, being able to slide between them isn't always appropriate

#### Fix or remove the table of contents
On reddit.com in a browser it's just a list of html anchors for quick navigation, however in the app implementation it has a few issues.
* It doesn't do anything, pretty self explanatory clicking them doesn't take you to the heading
* An extra level of indentation is only applied to the first child
* Third (and presumably higher) level indentation doesn't display, the first child shows as second level and the next shows as back to first level indentation
* The styling doesn't look very polished, they're displayed as bulleted items with indented options having two bullets, doesn't 'feel' like a table of contents

A few of these can be seen in http://i.imgur.com/U3WdApm.png and https://i.imgur.com/vQdaVcX.png

#### Wikis currently don't take on theme settings
They currently only use the dark theme regardless of the users selection

**Comment by Alexendoo** [comment]
It seems also that no internal links work for ie other pages when inside a wiki in the app

**Comment by Alexendoo** [comment]
I'm going to tag high priority as the current system does generate negativity towards the app, it doesn't mean all of it is high priority but some certainly is

**Comment by ccrama** [comment]
Done a few commits ago :)
