### ISSUE TITLE
Links to posts open subreddits instead of the post

### ISSUE THREAD

**Issue by c727** [ccrama/Slide#619]
Google for 'best subreddits'
->
What are the best text-based subreddits to kill time reading ...
->
https://www.google.de/url?sa=t&source=web&rct=j&url=https://m.reddit.com/r/AskReddit/comments/3pc6rf/what_are_the_best_textbased_subreddits_to_kill/&ved=0CCYQFjACahUKEwiewPnE7Z3JAhVBlQ8KHQPKCAQ&usg=AFQjCNHZj8ThwXYfzmWYQbeJ5boHeHIFJw&sig2=rP-AbnrwVf1Zq0dTPaPzEw

**Comment by Alexendoo** [comment]
Narrowed it down a little, links in the form 
https://reddit.com/r/AskReddit/comments/3pc6rf/what_are_the_best_textbased_subreddits_to_kill
do not work correctly, however others including 
https://reddit.com/r/AskReddit/comments/3pc6rf/
seem to function fine
