### ISSUE TITLE
Tapping the image/link preview should open the image/link instead of comments

### ISSUE THREAD

**Issue by augenleet** [ccrama/Slide#62]
When not having the large image preview enabled, there's no way to open the link/image with one tap.

The regular link/image preview should behave the same as the large one.

**Comment by ccrama** [comment]
Interesting, that isn't how it should be working. What card settings do you have enabled?

**Comment by augenleet** [comment]
It seems to be reproducible with "Small Card"  and "List" setting.

**Comment by ccrama** [comment]
Fixed with 855ce830323d9c5584003ad77b81a5df1f6bec93
