### ISSUE TITLE
crash when type '-' in drawer's search for sub

### ISSUE THREAD

**Issue by c727** [ccrama/Slide#620]
Try to type 'a-'

**Comment by Controless** [comment]
I can't seem to replicate this. It doesn't even allow me to input any special characters.

**Comment by c727** [comment]
Type as 2nd/3rd/... character.
I'm using aosp keyboard

**Comment by Controless** [comment]
Ah okay, I'm using Google Keyboard so that's why the crash is not occurring for me.

**Comment by c727** [comment]
Ok , first char has to be a-z.
'@' also crashes
'Space' deletes characters and sometimes adds an '_'

Seems if the Text as a special length it doesn't crash on '-'

**Comment by karlding** [comment]
This has already been reported multiple times (#143)
