### ISSUE TITLE
Drafts

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#629]
1. Slide will automatically save posts/comments when a user exits without submitting.

This will a lifesaver for when you accidentally press the back button, or you accidentally close the app without submitting the post/comment.

2. Slide will collect these saved posts & comments into a [Drafts] section of the app, where the user can view them.

3. (optionally) make it a Pro-only feature.

**Comment by ccrama** [comment]
It now has a popup that says "Do you really want to discard this?". 
Is this a viable alternative?

**Comment by ccrama** [comment]
Done! Now you can click on the save icon in the editor to save a draft or the file icon to load a draft. It also saves a draft when replying gives an error and when leaving the view before sending.
