### ISSUE TITLE
Add support for Reddit's report links & comments feature

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#630]

**Comment by Alexendoo** [comment]
For when it gets worked on, a new feature has arrived https://www.reddit.com/r/changelog/comments/3w4rsf/upcoming_reddit_change_subreddit_rules_report/

**Comment by ccrama** [comment]
Merging #936  with this

**Comment by rmenessec** [comment]
+1

I can't find any Reddit clients with the ability to report posts. Have to continue using Reddit site until this is available...

**Comment by ccrama** [comment]
Done, now you can report comment and posts with a custom reason!
