### ISSUE TITLE
Severe formatting issues regarding inline code

### ISSUE THREAD

**Issue by recalculated** [ccrama/Slide#636]
Reference post: https://www.reddit.com/r/archlinux/comments/3tmmcx/makepkg_illegal_instructions_on_everything/cx7khmn

This is the actual post text:

>2 things:
>
>Can you post your `/etc/makepkg.conf`/`~/.makepkg.conf`/`~/.config/pacman/makepkg.conf`?
>
>When you run makepkg, scroll up from where the error occurs, and look for a line containing `cc` or `gcc`. Your PKGBUILD likely calls `make`, and `make` prints the commands as it runs them. Let's see the exact gcc command that it is running.

And this is what Slide displays:

![screenshot_2015-11-21-20-33-28](https://cloud.githubusercontent.com/assets/13721872/11321918/33b8856e-908f-11e5-8b85-6426d5bba735.png)

**Comment by l3d00m** [comment]
fixed with #638
