### ISSUE TITLE
Sanitize the "search subreddit' input field

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#64]
Entering a whitespace in the search subreddit field crashes the app

**Comment by ccrama** [comment]
It shouldn't. Adding a space should be ignored

**Comment by l3d00m** [comment]
How can I verify it?

**Comment by Alexendoo** [comment]
It appears not to be sanitized, you can include any characters that would break the request https://gist.github.com/Alexendoo/7a95cccff1b65ed3abf0 (example with a space)

Another interesting one is that the subreddit '?' can load before crashing, whereas the crashes occur immediately: https://gist.github.com/Alexendoo/7549900a117d8cb60519

**Comment by l3d00m** [comment]
Looks like the ? gets sanitized and then the request gets send although it is empty.

**Comment by Alexendoo** [comment]
Indeed, there are some interesting ones that don't cause crashes including a completely blank entry.

A valid sub not including /r/ matches `/^[A-Za-z0-9][A-Za-z0-9_]{2,20}$/`

**Comment by l3d00m** [comment]
/[A-z0-9][A-z0-9_]{2,20}/     this would grab the subreddit even if there are wrong characters in front or end of it (removed the ^ &)

**Comment by Alexendoo** [comment]
Working with incorrect characters defeats the point of validation, no?

**Comment by l3d00m** [comment]
Yeah that's true. I have no idea which of those the better way is. Validation is probably better because it doesnt include characters we don't want (\d are arabic number too iirc), but it doesn't allow incorrect characters between the input (which shouldn't happen normally). eg /r/leagueofle.gends would become /r/leagueofle

**Comment by GermainZ** [comment]
Allowing spaces then stripping them out would be neat, as it would make it easier to search for English named subreddits by swiping/gesture typing.

**Comment by l3d00m** [comment]
Then we should go the "stripping all incorrect characters out" way.

**Comment by ccrama** [comment]
Yep working on that right now. Thanks for the find!

**Comment by ccrama** [comment]
Done with 824b092117ae42d3759f65f86ab984530f3d0965
