### ISSUE TITLE
album not found, missing thumbnails

### ISSUE THREAD

**Issue by c727** [ccrama/Slide#642]
album not found:
http://reddit.com/r/Minecraft/comments/3tqog9/while_looking_through_old_minecraft_screenshots_i/

Thumbnail missing:
http://reddit.com/r/gifs/comments/3tqssl/how_to_clean_a_window/

http://reddit.com/r/gifs/comments/3tpgn0/beautiful_passing_sequence_leading_to_a_goal/

http://reddit.com/r/gifs/comments/3tpymo/time_to_flip_the_mattress/

http://reddit.com/r/gifs/comments/3trwx5/they_see_me_rollin/

**Comment by okungnyo** [comment]
Great find!

I wonder why pic/album support is so finicky.

It's not just Slide, every other Reddit app in existence has these problems. Try visiting /r/RelayforReddit or /r/redditsync and 90% of the posts are about Imgur or Gfycat not loading.

**Comment by ccrama** [comment]
It's definitely the api. Sometimes the json call fails and Imgur force opens the link in a new tab. As a fix I just made it open in browser if it fails in the album viewer.

**Comment by okungnyo** [comment]
Do you mean Chrome custom tab? Or just a standard "open in browser" pop-up?

**Comment by l3d00m** [comment]
In a Web view. That's new and looks similar to custom tabs.

**Comment by okungnyo** [comment]
So an in-app browser?

What do you mean, isn't Chrome custom tabs newer than WebView?

Or do you mean "new" as in "new in Slide"?

**Comment by l3d00m** [comment]
New in Slide. Some people don't want to use chrome or in some cases we can use custom tabs.

**Comment by okungnyo** [comment]
Will all links be open-able in WebView?

**Comment by l3d00m** [comment]
Yes, it's an option in settings now

**Comment by okungnyo** [comment]
I believe I requested a WebView option a few months ago, but you shot down.

What changed y'all's mind?

**Comment by l3d00m** [comment]
I cannot remember something like this, but it's possible. 

When we thing a feature is niche, but is requested from multiple persons anyway, it's possible that we integrate it then.

**Comment by okungnyo** [comment]
So why did those people request WebView? What functionality do they need from WebView that Chrome Custom Tabs doesn't have?

**Comment by l3d00m** [comment]
I think it has different reason, but the main thing is that they don't want to use chrome. Why? It shows in their chrome history if they visit "science" subs /they want privacy and don't want their data send to Google. No idea, but that's what I'm assuming.

**Comment by okungnyo** [comment]
lol "science"

But Chrome custom tabs visits are recorded in your history?

Is this documented somewhere?

**Comment by l3d00m** [comment]
I'm pretty sure that I read this on reddit. I can try it out for myself at the moment, and the documentation about custom tabs is still a bit small because it's new.

**Comment by okungnyo** [comment]
Please do, that would be much appreciated.

Local history *and* history.google.com, if you can.

**Comment by l3d00m** [comment]
I will try it out when I'm back home later.

**Comment by okungnyo** [comment]
OK, in the meantime can you answer these two questions?

1. Does every link you open in WebView have its own cache/cookies/etc. folder? Or do all links opened in WebView in a single app share a single cache/cookies/etc. folder?

2. Are the cache/cookies/etc. cleared automatically when the WebView page is closed? Or when the app is closed?
