### ISSUE TITLE
Shortened youtube links freeze the app (youtu.be)

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#65]
Example post with a youtu.be link [here](http://www.reddit.com/r/pietsmiet/comments/3okpit/_/). When opening the link, the app switches to a black background and freezes.

**Comment by Alexendoo** [comment]
Can't replicate, which version of the app are you running @l3d00m, the play store version?

**Comment by l3d00m** [comment]
I can't replicate it any longer too, sorry for the confusion. (v4.0.5)
