### ISSUE TITLE
Problems with replying to post 

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#66]
First of all, I don't understand why the both reply fields are different (reply to a comment and reply to a post).  
The reply to comment works as it should but the reply to post doesn't show the formatting options (bold, italics,...). The discard button also doesn't work.  
Tapping the reply button in a post again should close the reply to post field.  

Sorry for "spamming" github with issues, I just found a few.

**Comment by Alexendoo** [comment]
@l3d00m Don't be sorry! The more issues that get reported the easier they're fixed.

**Comment by l3d00m** [comment]
Sounds good. If I have more time in future I will fix easier issues like that by myself and I'll  directly submit a pr.

**Comment by ccrama** [comment]
All done! 8abba701ce1a07125d179733f83a0467d1efcf43
