### ISSUE TITLE
How does Slide currently handle GIFs/GIFVs/Gfycats?

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#661]
Does it (1) stream them while downloading, or (2) wait until the entire GIF/GIFV/Gfycat is downloaded before commencing playback?

**Comment by l3d00m** [comment]
I'm pretty sure that it uses the first way, because it sometimes buffers while playing a gif.

**Comment by l3d00m** [comment]
it streams them while downloading. Now it uses a lighter version of gfys (every gif is converted to gfy too), which makes loading faster. Can i close this now?

**Comment by okungnyo** [comment]
1. By "a lighter version of gfys", you mean Gfycat mobile?

1. So, just to be clear, every Imgur GIF link is converted to a Gfycat mobile link?

2. What if an equivalent Gfycat does not exist? Is the GIF then converted to a GIFV?

**Comment by l3d00m** [comment]
1. Yeah, I've implemented that a few commits ago
2. That is correct 
3. Then we convert it to gfycat and get the mobile gfycat version of it too iirc.

**Comment by okungnyo** [comment]
3. What do you mean? Conversion happens on-the-fly?

**Comment by l3d00m** [comment]
Yep, it first checks if it's already a gfycat ([here](https://github.com/ccrama/Slide/blob/master/app/src/main/java/me/ccrama/redditslide/Activities/GifView.java#L123-L126)) and if not, it converts it to one [here](https://github.com/ccrama/Slide/blob/master/app/src/main/java/me/ccrama/redditslide/Activities/GifView.java#L201-L224)

**Comment by okungnyo** [comment]
Sorry if this sounds dumb, but how does that work?

It converts it, then uploads it? And how is that faster than just loading the GIF?

**Comment by l3d00m** [comment]
[Here](https://gfycat.com/api) is the api documentation. 

Slide takes the gif link (most times it's something like i.imgur.com/lKi99vn.gif) and only uploads the link to gfycat.com (not the whole gif) and gfycat converts it and then they gives back a url to a gfy (which slide downloads).

**Comment by Twixes** [comment]
Why so complicated? Aren't Imgur GIFVs enough?

**Comment by l3d00m** [comment]
that is a good question, i think gfycat is a bit lighter. We aren't currently using the imgur api, so we still fetch imgur GIFs iirc. @ccrama pls

**Comment by l3d00m** [comment]
Now it does that using the second way you described in your inital post @okungnyo

**Comment by okungnyo** [comment]
That sounds like a step backwards???

**Comment by l3d00m** [comment]
No, because it loads much faster that way. It also displays a progress bar instead of a black screen.

**Comment by okungnyo** [comment]
What about large Gfys?

I'm talking ones that are like a minute long and several tens of MB.
