### ISSUE TITLE
Double auth on app start

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#669]
(Not about the failed auths)

From playing with the debugger a little I believe I've narrowed down the cause, it auths twice on startup first [onCreate, line 383](https://github.com/ccrama/Slide/blob/e2a725cd7366a78cb7c2a332e9735adf0d297475/app/src/main/java/me/ccrama/redditslide/Reddit.java#L383), followed by updating again [onActivityResumed, line 198](https://github.com/ccrama/Slide/blob/e2a725cd7366a78cb7c2a332e9735adf0d297475/app/src/main/java/me/ccrama/redditslide/Reddit.java#L198)

**Comment by l3d00m** [comment]
Can confirm this

**Comment by l3d00m** [comment]
this is fixed now
