### ISSUE TITLE
Slide doesn't restore from background correctly

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#67]
If Slide crashes and then restarts or if I let Slide stay for a long time in background, so that android kills it to free memory, then it just shows a default screen like [this](http://imgur.com/a/ymtMf).  
Slide won't load any content even after one minute or so. Some buttons will crash the app again in this state (eg settings, info button in the action bar at the top) 

LG g2, Android 5.0.2, v4.0.5 (this should be the newest)

**Comment by ccrama** [comment]
Most likely fixed with d66b7ca

**Comment by l3d00m** [comment]
It's completely fixed now.
