### ISSUE TITLE
Use a bottom sheet for sharing options

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#672]
Basically the title. KitKat and below users should have this too. Although something like this is pretty far out.

**Comment by Alexendoo** [comment]
What's the current method doing wrongly?

**Comment by alexsmithfanning** [comment]
Nothing really. Just something that'd be cool to have.

**Comment by l3d00m** [comment]
wrong reference, sorry

**Comment by Alexendoo** [comment]
To replace this thing? http://i.imgur.com/VtGxdia.png &ndash; If so yeah that seems like a good one to me

**Comment by alexsmithfanning** [comment]
Yes. To replace that thing.
