### ISSUE TITLE
[Question] why is [Search for a subreddit] called that

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#674]
Since by the dev's own words, it "doesn't search for subs, you have to type the full sub name and click "Go to _____"".

https://www.reddit.com/r/Android/comments/3rw8l6/slide_for_reddit_v4_beta_complete_rewrite_stable/cxcm5kg?context=3

So why not rename it to [Go to subreddit].

Also, another capitalization inconsistency: in some places, "S/subreddit" is capitalized to 'Subreddit' and in other places, it's uncapitalized to 'subreddit'.

**Comment by ccrama** [comment]
It is "Go to android" if you typed android in the box. And most of the app functions are lowercase, some slip through though, can you find any specific examples I could fix?

**Comment by okungnyo** [comment]
I'm confused.

Has it been changed from [Search for a subreddit] to [Go to a subreddit] in the latest builds?

And do you prefer 'Subreddit' or 'subreddit'?
