### ISSUE TITLE
Crash when sharing images

### ISSUE THREAD

**Issue by christensen5** [ccrama/Slide#675]
I have so far been unable to share any media by tapping on the share icon while viewing them in the internal viewer. Every attempt to do this results in the usual "Slide has stopped working" page. 

For reference, I'm viewing on a Nexus 6 running stock rooted 6.0 with BenzoCore kernel. 

Hope this is helpful :)

**Comment by l3d00m** [comment]
I can share images without any crashes.

**Comment by l3d00m** [comment]
Fixed with the next release!
