### ISSUE TITLE
Slide reopens itself from background

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#678]
Sometimes Slide opens itself from background, probably everytime when checked for notifications.

When that happened once, you have to wait til data is loaded, otherwise it will reopen itself every minute

Probably introduced with the offline mode update

**Comment by l3d00m** [comment]
High priority removed because it occurs very rarely

**Comment by The0x539** [comment]
Can happen while the phone's locked, too >_>

Always unlocking to Slide until I force kill the thing

**Comment by c727** [comment]
Slide also reopens after 1-2 seconds when force-closed (developer options) while loading a subreddit

**Comment by ccrama** [comment]
That is because the Reddit class force opens the activity when slide is first booted, so on a cold boot (like for notifs), it will do this. Really don't know how I could work around that :(

**Comment by l3d00m** [comment]
Mh, it worked before the offline mode update. Isn't it somehow possible, because it's *really* annoying?

**Comment by ccrama** [comment]
I can't reproduce anymore, even with notif checks on and having it in the background all the time

**Comment by c727** [comment]
[21:23:32] <ccrama> https://www.filepicker.io/api/file/Y7jxihH1Q5GZvcDdGoHU try that

still reopens

**Comment by The0x539** [comment]
Just happened to me with today's build thing. Muh netflixes

**Comment by l3d00m** [comment]
easiest to repro is when you set the notification check to 15, still occurs for me

**Comment by l3d00m** [comment]
Fixed with 558e3b6ea9b2b491e4a6b1880de53767476223bf

**Comment by ccrama** [comment]
Woo
