### ISSUE TITLE
Don't reload the subreddit list at each start

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#68]
If I kill Slide and then start it, it'll now show a splash screen. (this looks pretty nice). 

Anyway, it would be nice if you could just use the latest cached version of the subreddit list and to reload it in background after the app is started completely. This would shorten the time Slide needs to start.

**Comment by Alexendoo** [comment]
I believe @ccrama considers this one as wontfix, but will let him confirm

**Comment by ccrama** [comment]
It should stay in memory long enough for you to re-open it. Can't really do this currently with the API I'm using. Sorry!

**Comment by l3d00m** [comment]
It unfortunately doesn't last very long in the memory for me, and I have to kill the app every few hours after I didn't use for more than half a hour.   
Isn't it possible to check if the app gets in this state and then to reload it? This happens really often and is annoying.
