### ISSUE TITLE
Markdown: Nested Lists

### ISSUE THREAD

**Issue by karlding** [ccrama/Slide#682]
Nested lists fail to display the proper nesting levels.

**Comment by l3d00m** [comment]
this is kinda related to #40

**Comment by youri--** [comment]
I've just tried nested lists in a comment and neither the preview or the comment rendered the nested list properly.

Nested unordered lists need 2 or more spaces at the start of a line, ordered lists 3 or more spaces, according to https://www.reddit.com/wiki/markdown#wiki_lists

Can this issue be reopened please?

**Comment by l3d00m** [comment]
@youri-- I'd just recommend to open a new one, it'll probably get more visibility than an old issue like this.
