### ISSUE TITLE
Post page doesn't properly reflect vote status

### ISSUE THREAD

**Issue by karlding** [ccrama/Slide#685]
If you vote on a post on the subreddit view, and then tap on a submission to go view the comments, the OP card does not reflect the vote that you just cast. I think it'd make sense for the submission view to also reflect your vote status.

When you vote inside the submission, the colours of the arrows in the submission card are properly updated, and if you then press back to go back the subreddit view, the new status is also properly reflected when the subreddit is reloaded.

**Comment by Alexendoo** [comment]
Fixed with 4232042c71f5f271fbe5c712a66d508d7b4004e0
