### ISSUE TITLE
Flickering after post viewed

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#686]
Subs such as /r/mildlyinteresting and /r/pics have a weird bug that causes text not to be visible until after you scroll down the page.

I might be able to a a screencap of this in action, but it happens very rarely, so maybe not.

**Comment by alexsmithfanning** [comment]
I caught it. Here's a screenshot: https://goo.gl/XxEsoZ

**Comment by plumbe0** [comment]
Can confirm, also happens in frontpage.

**Comment by l3d00m** [comment]
I never experienced it, android 5.0.2

**Comment by l3d00m** [comment]
I can reproduce it more often in last time, not sure why it happens though

**Comment by ccrama** [comment]
I believe this is fixed with hardware acceleration

**Comment by alexsmithfanning** [comment]
Yeah, sorry about that. I forgot to close it.
