### ISSUE TITLE
Image gallery does not include image title/description

### ISSUE THREAD

**Issue by abraham** [ccrama/Slide#690]
http://reddit.com/r/pics/comments/3uxw5f/this_is_freyja/

![screenshot_20151201-053917](https://cloud.githubusercontent.com/assets/3341/11498546/18621ed6-97ee-11e5-91a9-250ac75bdc84.png)
![screenshot_20151201-053925](https://cloud.githubusercontent.com/assets/3341/11498560/3168d4b0-97ee-11e5-8f7b-4107d9ba3837.png)

**Comment by ccrama** [comment]
Done with 7aa691aa76547aa036560b220494b8c972db6708! Thank you for the report
