### ISSUE TITLE
Crash when spoiler link opened

### ISSUE THREAD

**Issue by silentkun** [ccrama/Slide#691]
Subreddits that use spoiler tags creates a link to a nonexistent page in reddit. This causes the app to crash when opened. 

[Example] (http://reddit.com/r/anime/comments/3uybmz/what_are_some_issues_in_an_anime_that_could_have/cxircne?context=3)

**Comment by Alexendoo** [comment]
Related #692

**Comment by l3d00m** [comment]
This is fixed now,  it no longer crashes
