### ISSUE TITLE
Multiple font style options

### ISSUE THREAD

**Issue by silentkun** [ccrama/Slide#693]
Like a serif font for comments and medium/strong for post titles. Users should be able to customise.

**Comment by Alexendoo** [comment]
Seems a little out of scope

**Comment by l3d00m** [comment]
It's ugly code to override fonts and not recommended

**Comment by l3d00m** [comment]
added with next release

**Comment by okungnyo** [comment]
Huh?

So you guys *did* add it after all?

**Comment by l3d00m** [comment]
Yeah, @ccrama did it.
