### ISSUE TITLE
[Feature Request] Hide all read posts (or at least all LOADED read posts) until next refresh

### ISSUE THREAD

**Issue by joshery420** [ccrama/Slide#698]
Is there any possibility of a system like Relay has, where we can refresh to see all posts (including read posts) but then quickly and easily hide those read posts if we only want to see new content? That's the only thing keeping me from really switching to Slide full time anymore.

**Comment by l3d00m** [comment]
Yes, it is already implemented! Settings - > Floating action button - > activate fab - > activate the second option. Tipp: Long pressing the fab hides posts forever.

**Comment by joshery420** [comment]
Hot damn, that's it! haha, thanks so much, I had no idea that was in there.
So one last thing then. Is there any way to unhide posts if I accidentally long press?
I'm all for hiding posts, but forever is a long time, especially if it's by accident. ;)

**Comment by l3d00m** [comment]
Not currently, sorry. There is an issue for it and is has priority, so it should be coming soon, as well as an undo button on the Snackbar.

**Comment by joshery420** [comment]
Just awesome. yep, Relay uninstalled. Totally committing to Slide now haha.
Thanks so much for the quick responses. :+1:

**Comment by l3d00m** [comment]
Awesome to hear. No problem!
