### ISSUE TITLE
Random crash when tapping on comments

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#7]
When tapping on a comment sometimes for no reason Slide will crash. I can't find a pattern.﻿

**Comment by xnaas** [comment]
This is a know issue that seems to come back and go away as newer versions of the APK come out. In the latest ones (not available yet) this seems to be mostly resolved. @ccrama can probably provide better feedback on this though.

**Comment by ccrama** [comment]
I honestly have no idea why it's happening. I haven't experienced it so I can't confirm the bug. If someone could get me a stack-trace, that would be amazing!

**Comment by ccrama** [comment]
I think I may have found the issue, which is not what we think it is. I believe you might be clicking on "Load more comments", which then results in a crash. I have removed it from the latest version and will check back to see if anyone else still has this issue!

**Comment by alexsmithfanning** [comment]
Load more comments does this every time. But occasionally when tapping the comment itself Slide will crash.

**Comment by ccrama** [comment]
Fixed with 0f227ac2ac9117b10fca4ec069a6395fcc777989
