### ISSUE TITLE
Use native transparency

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#701]
Icons that need to be 54% black are instead colored gray/grey. This should use some type of transparency value, right?

Doesn't Android provide a method for doing this?

**Comment by recalculated** [comment]
Using true transparency would look strange on colored backgrounds. The color tinting method works, so why change it?

**Comment by ccrama** [comment]
Slide already does this

**Comment by okungnyo** [comment]
Lol, got shut down pretty hard there.

**Comment by ccrama** [comment]
Lol sorry, didn't mean to be mean
