### ISSUE TITLE
Gfycat mobile support

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#707]
https://www.reddit.com/r/RelayForReddit/comments/3vhuse/gfycat_now_have_a_smaller_mobile_version_of_hd/

https://www.reddit.com/r/RelayForReddit/comments/3vhuse/gfycat_now_have_a_smaller_mobile_version_of_hd/cxo2tod

**Comment by okungnyo** [comment]
Also: https://www.reddit.com/r/gfycat/comments/3vmgky/api_feature_request_return_the_mobile_version_url/

(DRady is the developer of Relay for Reddit)

**Comment by ccrama** [comment]
Wouldn't be difficult at all. Will do this!
