### ISSUE TITLE
Comment navigation arrows bug

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#708]
When trying to use the up and down comment navigation arrows and the post has no comments it crashes Slide.

**Comment by c727** [comment]
https://github.com/ccrama/Slide/issues/654

**Comment by okungnyo** [comment]
Shut down again lol.

**Comment by l3d00m** [comment]
I didn't mean to be rude, I'm really thankful that there are people who report issues and therefore help with the app.

It's just faster for me to close it and not writing a comment with an explanation. We also try to hold the tracker very clean of dupes and fixed issues.

**Comment by alexsmithfanning** [comment]
Oh crap! I'm sorry. I didn't see #654. I deserved that.

There's getting to be so many issues its becoming unmanageable.

**Comment by l3d00m** [comment]
No problem. That's the reason why we manage the tracker with some more people, it's just hard to get a overview.
