### ISSUE TITLE
Add [Search this subreddit] shortcut to the sidebar

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#709]
Submit and subscribe are there, so it makes sense that search is there too, it's there on reddit.com sidebars too.

**Comment by l3d00m** [comment]
I prefer to have it in the toolbar, as it is currently. I think it's mostly personal preference

**Comment by okungnyo** [comment]
Submit and subscribe are in the sidebar. So is search. Logically, they belong together.

**Comment by l3d00m** [comment]
IMO it doesn't always make sense to transfer concepts from websites 1:1 into apps.

I'm too inexperienced with ui though, that's why @Alexendoo or @ccrama should decide this.

**Comment by okungnyo** [comment]
Both sides are right.

On one hand, search can either be subreddit-specific, or it can be site-wide and not subreddit specific.

On the other hand, search IS on the sidebar on reddit.com.

But it doesn't have to be either or. It can be both.

Aren't submit and subscribe in two places too? So why not search too?

For those who want site-wide search, they can use action bar.

For those who want to search a specific subreddit and don't want to have to type it out, they can use one in the sidebar.

Again, the two are not mutually exclusive. You can have both.

You can have [Search] in the action bar, AND [Search this subreddit] both.

I urge you to reconsider. Thank you.

**Comment by The0x539** [comment]
I personally don't think it makes *sense* to have it there when the sidebar's a pop-out expanding one and there's a toolbar available to use. On the desktop site, search is a secondary function of the site, so a search bar doesn't deserve the width of a post, but at the same time it should at least be an input box *somewhere* on the desktop, so it's more of a fit to go in the column of the UI that has some width, but not a lot. Dunno.
