### ISSUE TITLE
Display "This is an archived post. You won't be able to vote or comment." message above archived posts.

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#710]
You can see it in action in any old post.

Example 1 (self post): https://www.reddit.com/r/montageparodies/comments/2i1ys5/when_you_upvotedownvote_you_now_get_a_hitmarker/

Example 2 (link post): https://www.reddit.com/r/funny/comments/202wd3/i_participated_in_one_of_the_biggest_magic_the/

**Comment by brudin** [comment]
Something similar for np.reddit posts would be cool too!

**Comment by okungnyo** [comment]
Sure, but there's not a reddit.com equivalent, so Slide would have to come up with its own message for np.reddit.com links.

**Comment by l3d00m** [comment]
The np-info is already implemented, [this](http://imgur.com/myzCnSj.jpg) is how it looks like.

**Comment by okungnyo** [comment]
LOL

**Comment by brudin** [comment]
Ah, cool!  What a great post to show it off with too, haha.

**Comment by l3d00m** [comment]
It's added now!

**Comment by okungnyo** [comment]
Boss.
