### ISSUE TITLE
Subscribing to a subreddit doesn't work

### ISSUE THREAD

**Issue by Revel1020** [ccrama/Slide#711]
If I tap on the 'subscribe' button, go back a place and then back again to the same page. I'll find that the 'subscribed' tick box is not ticked.

**Comment by l3d00m** [comment]
It works, you have to sync them via drawer - > profile - > sync. If you check it on reddit.com in your browser, you are subscribed.

**Comment by Revel1020** [comment]
Shouldn't it automatically resync after subscribing.

**Comment by okungnyo** [comment]
^ this.
