### ISSUE TITLE
Cannot access own profile section 

### ISSUE THREAD

**Issue by s0m3guy** [ccrama/Slide#712]
Whenever I try to go to my own profile using the drawer it says something like (German version) "error while loading content". This happens every time and on each profile section.

**Comment by l3d00m** [comment]
IIRC this is already fixed and will be included in the next update. Temporary workaround is to set you system language to English.

**Comment by s0m3guy** [comment]
Alright will look forward. If I might add then I would like to be able to
change language in the app too :)

Thomas Lu <notifications@github.com> schrieb am Mo., 7. Dez. 2015, 12:00:

**Comment by l3d00m** [comment]
Yeah, this is requested by some more people. We have an issue for that. Thanks for the report!
