### ISSUE TITLE
Changing to white theme causes a crash

### ISSUE THREAD

**Issue by Pacogens** [ccrama/Slide#715]
I use the black theme but now I change to white theme vut it make the app crash and it is imposiible to use it now. Every time I try to launch the app it crash.

**Comment by l3d00m** [comment]
Do you use lime green as a color by any chance?

**Comment by Pacogens** [comment]
Lime green in some subreddits yes... 

Android 6.0 on a Nexus 6

**Comment by l3d00m** [comment]
that causes the crash, should be fixed with the next version.
