### ISSUE TITLE
Loading mini spinner misplacement

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#721]
The pull to refresh mini spinner should start appearing at the very top of the screen, instead it starts right where the menu bar ends, which causes an ugly animation when first pulling. Am I making any sense?

**Comment by Alexendoo** [comment]
Yes, well noticed

**Comment by alexsmithfanning** [comment]
This has been bugging the crap out of me forever.

**Comment by ccrama** [comment]
That is actually not fixable. Slide has to do this because it shows the slider before the view is fully instantiated, so if I did not do this it would be invisible.
