### ISSUE TITLE
Hide or grey out certain settings when irrelevant

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#727]
For instance, the NSFW image previews option when NSFW posts as a whole are hidden.

**Comment by okungnyo** [comment]
Good catch! It's an important papercut.

**Comment by ccrama** [comment]
That's already in the latest commits (I think @rosenpin  did it a few weeks ago)

**Comment by rosenpin** [comment]
Yeah.
I did in a00fdfc .

**Comment by okungnyo** [comment]
In which sections does this apply?
