### ISSUE TITLE
Stuck on spinner. Nothing loading

### ISSUE THREAD

**Issue by akorchemniy** [ccrama/Slide#730]
Restarting app doesn't help. V4.3.4

**Comment by take-a-CHANCE** [comment]
Same here. Occasionally loads but then crashes quickly thereafter

**Comment by l3d00m** [comment]
Are you logged out by any chance?

**Comment by akorchemniy** [comment]
I was logged in. Problem is intermittent. Most of the time it works, once in a while I cannot get it to work.

**Comment by okungnyo** [comment]
Sync is having issues as well: https://github.com/laurencedawson/reddit-sync-development/issues/1102

So is reddit.com: https://www.reddit.com/r/AskReddit/comments/3wwpli/guys_reddit_is_broken_we_know_we_are_mods_we_cant/

**Comment by l3d00m** [comment]
I can repro it now, but it's a reddit issue, nothing we can fix on our side.
