### ISSUE TITLE
Locked posts

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#733]
I cannot find an example locked post to test, so forgive me if Slide already supports it.

But basically:

https://www.reddit.com/r/changelog/comments/3qgydw/reddit_change_lock_a_post/

https://www.reddit.com/r/modnews/comments/3qguqv/moderators_lock_a_post/

https://www.reddit.com/r/redditdev/comments/3qgwvu/api_support_for_lock_a_post/

**Comment by l3d00m** [comment]
Supported by JRAW now: https://github.com/thatJavaNerd/JRAW/commit/55fd284c815324aadbbdda4bf64a171d00408136#diff-1d641e31a08a4e07349a778f25c8ec66R288

**Comment by ccrama** [comment]
Done! Now Slide supports it too
