### ISSUE TITLE
Account suspensions

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#734]
Again, I cannot find an example suspended account to test, so forgive me if Slide already supports it.

But basically:

https://www.reddit.com/r/changelog/comments/3sc7nn/reddit_change_account_suspensions/

https://www.reddit.com/r/redditdev/comments/3sbs31/api_support_for_account_suspensions/

**Comment by ccrama** [comment]
What exactly would we be supporting though?

**Comment by ccrama** [comment]
Now it will notify you if suspended!
