### ISSUE TITLE
Small icons/pics in comments

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#735]
Once again, I cannot find an example to test, so forgive me if Slide already supports it.

Sometimes I've seen comments containing small icons/pics. Right-clicking the pic does not give the usual web browser for-images-context-menu, so I have no idea how the commenter inserted a pic into a Reddit comment.

That being said, it would be great if Slide supported it. (And if anyone can tell me what that feature is called, that would be great as well.)

**Comment by l3d00m** [comment]
Do you have RES installed? I think it has a feature like that.

**Comment by okungnyo** [comment]
1. No, I don't have RES.

2. They weren't normal pics. They weren't links to Imgur, for example.

No, they were these tiny icons. And all of them are the same size, like 50x50 (total conjecture) big or something.

Actually, now I remember hovering over one with my mouse and I got a little tooltip that said "kappa" or something like that.

**Comment by l3d00m** [comment]
Then i'm pretty sure it has something to do with that subreddit's CSS and that's something we won't integrate because it's nearly impossible.

**Comment by okungnyo** [comment]
I think what I saw was in the body of the comments themselves, but my memory is hazy and I am not sure...

**Comment by l3d00m** [comment]
it's pretty sure the subreddit CSS, so it's a wontifx unfortunately

**Comment by Alexendoo** [comment]
To add to it, some subreddits (though naturally when you want to find an example you can't) use links for placeholders to be replaced by images using CSS, unfortunately this would mean the subreddit CSS would have to be downloaded and parsed for every comment thread, which may not have a massive effect as for as performance goes but it's not done in one uniform way so it wouldn't likely be easy.
