### ISSUE TITLE
The change in top bar color when sliding between subreddits should happen gradually

### ISSUE THREAD

**Issue by Twixes** [ccrama/Slide#737]

**Comment by Twixes** [comment]
Just a suggestion, but I don't think a difficult one. It surely would look great, though!

**Comment by l3d00m** [comment]
That would be really nice, but it would make the app to choppy (source #360).  
Sorry for blocking both requests, thank you for that the ideas anyway!

**Comment by Twixes** [comment]
Couldn't it be just an option, though? As I said, it sounds pretty simple to do and should work well on more powerful phones.
