### ISSUE TITLE
Make tapped/visited links purple in self posts and comments

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#739]
When you're viewing a self post/comment with a list of 100 GIFs,  it's easy to lose your position and get lost.

It would be great if Slide made visited links purple.

As far as I know, no other app does this.

**Comment by Alexendoo** [comment]
Sounds like it would be a good thing to have

**Comment by ccrama** [comment]
Will take a lot of work.

**Comment by okungnyo** [comment]
Thanks for considering it.

**Comment by ccrama** [comment]
This would take an unproportionate amount of work and storage space, sorry will have to mark this as won't pursue
