### ISSUE TITLE
Blocking google analytics

### ISSUE THREAD

**Issue by ElectricSlide** [ccrama/Slide#740]
Is there a way for google analytics and other third party data collector's to be blocked when accessing reddit through your app? If not, is it something that can be looked into being implemented?

**Comment by Alexendoo** [comment]
This seems beyond the scope of a reddit app, currently web pages are opened using chrome custom tabs (or falling back to your browser if not available/selected otherwise). The place to look at blocking such requests would be either using a browser that does it already, or through some external blocking method (likely requires root if the browser does not support it)

**Comment by ElectricSlide** [comment]
yeah you could use firefox for android + noscript, or modify your hosts using adaway i think. But i was wondering if it would be possible from within the app. Just to be clear, i dont mean blocking  google analytics and 3rd parties on sites that the Slide links me to. I am referring to the ganalytics on reddit itself accessed via Slide

And now I am confused, i remember noscript blocking g analytics on my browser, and an option to opt out of ganalytics on reddit is fun but currently on the browser i can't find it anymore. Did reddit stop using ganalytics?

**Comment by Alexendoo** [comment]
Reddit indeed still uses google analytics on reddit.com, however mobile clients only have to send requests to the reddit API there is no requirement to contact analytics, it would make stats a little strange if they did, as it's very much a serivce for browsers/HTTP. 

Ignoring any collection done by the play store Slide doesn't use an analytics service. The option in reddit is fun would most likely have been to enable/disable an analytics service for the client itself, not on reddit's behalf.

**Comment by ElectricSlide** [comment]
ahh thx for clearing that up!
