### ISSUE TITLE
Phone reboots randomly while saving images 

### ISSUE THREAD

**Issue by sud007** [ccrama/Slide#743]
This is happening for the first time on this device in last 4 months. But today is happening after almost every third of fourth image I try to download. I downloaded images to repeat  crashes and they happen!

Xiaomi Redmi Prime
Android 4.4.4
MiUi 7.1 stable not rooted. 
Every thing Stock
Internal memory available 4GB
RAM available 1.4GB

**Comment by ccrama** [comment]
Should be fixed with the revamped saving code in 4.5 update
