### ISSUE TITLE
More serious subreddit-specific thingies

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#744]
For instance, expired instead of NSFW on buildapcsales.

**Comment by ccrama** [comment]
I think Slide has matured to a point where this isn't really going to happen. Closing now! If you have any comments or other ideas, please do let me know

**Comment by bb010g** [comment]
Perhaps allowing customizable NSFW titles? E.g. setting "Spoiler" instead of "NSFW". Perhaps it could be set in Subreddit Theme?

**Comment by ccrama** [comment]
I don't know how useful that would be, and it would cause us to have to re-write all the methods to accept a subreddit name to pull the correct string.  Don't know if something like that would be worth implementing into the UI
