### ISSUE TITLE
Images on frontpage?

### ISSUE THREAD

**Issue by cjamesdesigner** [ccrama/Slide#745]
I cannot see images on frontpage tab like i can on all the sub tabs including the all tab. Also it would be nice to have the swipe thorough image option on saved posts (or may option to add it as a tab). And out of pure curiosity is there a way to view images as a gallery like 4x5 thumbnails. Otherwise this app is fantastic and you have earned my donation!

**Comment by Alexendoo** [comment]
Could you grab a picture of the images not loading, would help us to know what's going on, thanks!

For the grid, not currently though I believe it's requested/been discussed for the album view for larger albums

**Comment by ccrama** [comment]
I think it might have been residual from the alternative layouts. I think it's safe to close it now (fixed in v4.5)
