### ISSUE TITLE
Cra ashing when approving.  Also please show some sign that it was approved by "someone"

### ISSUE THREAD

**Issue by SolarAquarion** [ccrama/Slide#749]

**Comment by okungnyo** [comment]
What is "approving", if I may ask?

**Comment by SolarAquarion** [comment]
Approving as a mod a post.  I think it crashes when someone else approved a
post.

**Comment by ccrama** [comment]
Fixed! And now it shows you who approved the post and lets you go to the approved users' profile. This is included in the complete modtools revamp in v5
