### ISSUE TITLE
Cannot save pictures 

### ISSUE THREAD

**Issue by vaporSilver** [ccrama/Slide#752]
Trying to save something from the internal viewer and a dialogue box pops up with "oops something went wrong, try again?". Never works. 

I honestly have only had this app for 2 hours so pardon my ignorance if this is already know.

**Comment by l3d00m** [comment]
Which android version are you using? Are you using the normal play store version or alpha version? 

It's probably fixed with the next release if you're using the play store version.

**Comment by vaporSilver** [comment]
Verizon Galaxy S6 Android 5.1.1 with Play Store edition.

**Comment by l3d00m** [comment]
Then it should be fixed with next release!
