### ISSUE TITLE
Shadowbox viewer only loads however many posts have loaded

### ISSUE THREAD

**Issue by parkerlreed** [ccrama/Slide#753]
If I jump to a subreddit and hit the gallery view button (shadowbox I think it was called?) it loads and lets me swipe through images but only for the first page of results. I have to back out and scroll down to load more posts. Then when going back it's reset to the first image, so I have to swipe about 20 times just to get back to where I was.

I guess what might work here is load more posts when you hit the last image in the viewer and also remember position if you happen to go back in.

**Comment by Alexendoo** [comment]
Same occurs with swiping through posts - #478

**Comment by l3d00m** [comment]
Marking this high priority because it makes one pro feature nearly unusable. It was also multiple times reported in other locations.

**Comment by l3d00m** [comment]
fixed with bd7251d0c8712e1aba0a4b69f0b4a669df6e5ff4
