### ISSUE TITLE
After signing in, the app doesn't restart correctly

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#758]
I'm a few commits behind on this build so I'll test on latest later, however after signing in the app prompted for a restart, after which came back into a strange state.

![](http://i.imgur.com/4asTytu.png)

**Comment by ccrama** [comment]
That should have been fixed in the latest commits. Can you let me know if it was please?

**Comment by l3d00m** [comment]
No it isn't. It restarts but that needs about 10 second and then it displays default subs. After a combination of killing from recents and backing out, it worked for me and showed the right subs but that was pretty hard to get.  
The app also doesn't restart after clicking got it in tutorial activity

**Comment by ccrama** [comment]
Fixed with 1b5121565d22b3592db6f24bf38146cfae2d8557!
