### ISSUE TITLE
Improved comment actions

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#76]
Currently the comment action bar is located under the comment you're trying to edit. Could it be places at the top in a way similar to copy-pasting? Or at the bottom?

I can attach a concept screenshot to better explain this if needed.

**Comment by alexsmithfanning** [comment]
If this was implemented, where would be the more sane place to put it?

**Comment by ccrama** [comment]
I dont know if there is any other better place to put it honestly
