### ISSUE TITLE
Gifs not loading correctly

### ISSUE THREAD

**Issue by MrGreenTea** [ccrama/Slide#760]
Whenever I open a gif it loads for a while and then just looks like this:
http://i.imgur.com/hUxmx5L.png

I already tried deleting the cache and data. That didn't change anything. Is there anything else I can try?

**Comment by MrGreenTea** [comment]
I forgot to add this:
I am using Slide on my OnePlus One with Resurrection Remix M v5.6.0

**Comment by l3d00m** [comment]
Which slide version are you using? Alpha or the normal one from play store?

**Comment by MrGreenTea** [comment]
I am using v4.5 from the play store.

**Comment by ccrama** [comment]
I don't believe this is an issue anymore. Feel free to re-open if you get it again
