### ISSUE TITLE
Go to random subreddit

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#761]

**Comment by alexsmithfanning** [comment]
Would this include NSFW subreddits too?

There should be an option to toggle that if that's the case.

**Comment by Alexendoo** [comment]
`/r/random` takes you to non NSFW subreddits at least on reddit, I think there's a way to have the opposite effect, mixed I don't know (though Slide could select between the nsfw version and the sfw version randomly to achieve the same effect)

**Comment by Twixes** [comment]
I don't see a point in this feature, /r/random and /r/randnsfw seem to work perfectly
