### ISSUE TITLE
Sliding as going back from post to subreddit view

### ISSUE THREAD

**Issue by Twixes** [ccrama/Slide#763]
I'm coming from Sync for Reddit and one thing I really liked there was the option to swipe right to come back instead of using the back button. Sadly, in Slide I can only slide between posts and have to press the back button to once again find myself in the subreddit view. Would it be possible to add this Sync behavior as an option in settings?

**Comment by Twixes** [comment]
Am stupit. It's as easy as swiping from the edge. But still, an option to enable this behavior for the whole screen would be nice.

**Comment by ccrama** [comment]
There is an  option! Go to settings > general > swipe from anywhere to enable it on 4.5
