### ISSUE TITLE
Crash when not signed in and changing Notification checking frequency

### ISSUE THREAD

**Issue by trevorhalvorson** [ccrama/Slide#764]
When signed out go to Settings, open Notifications, check the "Check for new mail" checkbox, select Done

**Comment by Alexendoo** [comment]
What slide version are you running? I believe this is fixed in 4.5 if not sooner

**Comment by trevorhalvorson** [comment]
Sorry I was running v4.3.4. Can confirm fix in v4.5

**Comment by l3d00m** [comment]
No problem. The next version won't even show the notifications settings when you're not logged in.

**Comment by okungnyo** [comment]
Wouldn't it be better to grey it out?

**Comment by l3d00m** [comment]
I don't think so. Why should the logged out user even see it?

**Comment by Alexendoo** [comment]
Consistent setting placements may aid finding what you're looking for a bit

**Comment by okungnyo** [comment]
Yeah, what @Alexendoo said.

**Comment by l3d00m** [comment]
Mh, then I will readd that. You are the ux guys.
