### ISSUE TITLE
Settings tab closing when tapping outside of color picker

### ISSUE THREAD

**Issue by Soberat** [ccrama/Slide#766]
So, this issue is kinda specific and the title may say not much, because I can't explain that bug without explaining the whole process of reproducing:
If you go to Settings, then to Default Theme and choose Main Color/Accent Color, tapping outside the popup will kick you back to main settings page, instead of just Default Theme. Can provide video if needed.

**Comment by l3d00m** [comment]
I know what you mean and can reproduce it.
