### ISSUE TITLE
Slide kills the currently logged in user

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#767]
At random intervals Slide will crash and the current user will be logged out (and makes it hard to log back in because of issue #758). All user data is kept.

**Comment by l3d00m** [comment]
It's not really logging out, it's more coming in the default logged out state. A force kill and restart fixed it for me most times. It's definitely related to #758

**Comment by ccrama** [comment]
Both are fixed in the last few commits.
