### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#775]
I can't believe this isn't on the tracker yet.

* **Filter domains** (example scenario: filter imgur.com, discover a whole new sea of content)

* **Filter keywords** (example scenario: filter "comcast", stop seeing posts that make your blood pressure boil)

* **Filter subreddits** (from /r/all) (example scenario: browse /r/all without having to see /r/adviceanimals)

**Comment by okungnyo** [comment]
Source: https://plus.google.com/+NicolasJohnson/posts/GTct1TPrd9k

**Comment by ccrama** [comment]
Done with 313544f32de2489b6b1658d3ae987e8332503c4c

**Comment by okungnyo** [comment]
Wow, that was fast.

All three were added?

**Comment by okungnyo** [comment]
Just checked, subreddit filtering was not added.

Was this done on purpose not to conflict with Reddit Gold?

And what is the difference between "selftext" filtering and "title" filtering? I'm confused.

**Comment by s1390** [comment]
I've been waiting for this feature from day 1, so thank you! Please add subreddit filtering, so it's possible to filter subreddit from r/all, @ccrama.

@okungnyo All big reddit apps have this, so I'm very sure it's not gold related.

**Comment by okungnyo** [comment]
@s1390 but I know the Sync dev purposely held out on subreddit filtering for a looong time because he didn't want to step on Reddit Gold's toes.

**Comment by ccrama** [comment]
I didn't even know that was a Reddit gold feature. Tbh I just forgot about it, might add it in sometime soon

**Comment by okungnyo** [comment]
So then re-open the issue?

**Comment by s1390** [comment]
@ccrama please re-open this issue. Filtering subreddits from r/all is a very important part of filtering in a reddit app.

**Comment by ccrama** [comment]
It would break the Reddit TOS and I could possibly lose API access if I did this @s1390

**Comment by okungnyo** [comment]
That doesn't sound right, then why did Now, Relay, Sync etc. all add it?

**Comment by s1390** [comment]
@ccrama Could you please look in this more? Baconreader has this as well. Blue had this as well before they merged with Reddit (and still has).
Thanks.

**Comment by s1390** [comment]
I also took the time to look over https://github.com/reddit/reddit/wiki/API, but can't find anything.

**Comment by s1390** [comment]
@ccrama Any update on this?

**Comment by s1390** [comment]
Filtering subreddits in r/all has been added in 4.7.0.
