### ISSUE TITLE
Card action bar placed incorrectly

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#786]
If Slide is set to display images in the middle of a card, the card action bar will look incorrect.

**Comment by ccrama** [comment]
Can you provide a screenshot please

**Comment by alexsmithfanning** [comment]
![screenshot_2016-01-14-13-07-12](https://cloud.githubusercontent.com/assets/12200557/12334478/d509fd12-babf-11e5-9639-74a6f05d1e65.png)

**Comment by ccrama** [comment]
Fixed with v4.6
