### ISSUE TITLE
"Save post" is always the default string, even if the post is already saved

### ISSUE THREAD

**Issue by Soberat** [ccrama/Slide#788]
Also, to not make the issue tracker a trashcan, "Toggle dark theme" in 3 dot menu is similar, it's static no matter the theme.

**Comment by okungnyo** [comment]
Yes, when I saved a comment, exited the 3-dot menu, and then re-opened the 3-dot menu, it said [Save comment] when it should say [Un-save comment].

Is this what you are experiencing as well?

**Comment by Soberat** [comment]
Exactly what I meant.

**Comment by l3d00m** [comment]
#828
