### ISSUE TITLE
Color chooser "OK" button incorrect

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#79]
The personal profile color chooser dialog has the 'OK' button placed way too far up.

**Comment by Alexendoo** [comment]
@alexsmithfanning A screenshot would help, I'm not sure what you're referring too

**Comment by alexsmithfanning** [comment]
Here you go: https://goo.gl/hNMAJb

**Comment by ccrama** [comment]
Fixed with 98550c3f2bd280405d222f07ef293766925743de
