### ISSUE TITLE
Changing theme via 3 dot menu crashes the app

### ISSUE THREAD

**Issue by Soberat** [ccrama/Slide#790]
I guess it's known, but changing theme, no matter if theme is light or dark makes the app crash, without restarting it. After launching it again theme is indeed changed though.

**Comment by l3d00m** [comment]
It works for me

**Comment by Soberat** [comment]
Just tried it on my Xperia S running 5.1 - does work. May be a Marshmallow issue. I'll check with 5.1 emulator.

**Comment by ccrama** [comment]
I can't get it to crash either :(

**Comment by Soberat** [comment]
Reddit downtime helped a lot in this issue - it happens when posts still haven't loaded. Checks out 100% of time.

**Comment by l3d00m** [comment]
I still can't repro it, even while posts are loading. Maybe it's fixed with next release then.

**Comment by Soberat** [comment]
May be Marshmallow related. This week is quite busy for me so  I will test it on the weekend.

**Comment by Alexendoo** [comment]
@Soberat Is this still occurring for you on 4.6?

**Comment by Soberat** [comment]
@Alexendoo Just checked on my Nexus 5X, doesn't occur, even when loading posts. However the string is still static for both themes.

**Comment by Alexendoo** [comment]
Excellent, and yeah that is true well noticed, will look at that when we do the settings/UI bikeshedding for next release
