### ISSUE TITLE
Selecting OK in the reorder pins menu crashes the app.

### ISSUE THREAD

**Issue by beepFTW** [ccrama/Slide#791]
No subreddits are pinned when reopening the app.

**Comment by l3d00m** [comment]
Have you reported that via the Slide has crashed dialog? Otherwise we will not be able to fix that because I can't reproduce it.

**Comment by beepFTW** [comment]
Just sent it with information that can easily identify that it was from me.

**Comment by ccrama** [comment]
Not applicable anymore, no more pins
