### ISSUE TITLE
If you exit the viewer before the GIF fully loads, the GIF doesn't play

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#794]
Ideally, the user should be able to tap on it (which tells the app to load that GIF), then do something else while it loads.

The user should not be forced to stare at a black screen loading bar for ten seconds (I've seen some long GIFs).

**Comment by ccrama** [comment]
I can't think of a way to do this with the current slide UI, marking as wontfix for now

**Comment by ccrama** [comment]
Fixed for v5.0.4
