### ISSUE TITLE
[Edit link then... (normal link actions here)] feature

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#797]
For when a commenter makes a typo and misspells a link, as seen here:

https://www.reddit.com/r/funny/comments/40zi0x/my_flight_attendant_mom_got_this_napkin_from_an/cyyec5r

In such a case, in Slide 4.5 and every other Reddit app, you have to copy the link, open a browser, fix the link, and open it yourself.

Basically, torture.

In a future release, Slide could detect that it's a Reddit link that for some reason it can't open.

Then it should ask the user, "Did the poster/commenter misspell the link? Would you like a chance to fix it so that the link can be opened by Slide?" and then open it in Slide.

**Comment by l3d00m** [comment]
I think this is a bit overkill. It's a really nice idea, but that would create feature bloat in Slide if we create more niche features like this. Thank you anyway for the suggestion!

**Comment by okungnyo** [comment]
Aight.
