### ISSUE TITLE
MultiReddits Kick you to the top when refreshing at the bottom of the list

### ISSUE THREAD

**Issue by 530farm** [ccrama/Slide#798]
When you get to the bottom of a multireddit it tries to refresh and while doing so, kicks you to the top of the list.

**Comment by l3d00m** [comment]
Uh, this is definitely an ugly bug. No idea how this slipped through the alpha. Thanks for the report!

**Comment by ccrama** [comment]
Happens to every view that loads more at the bottom except for the main SubmissionView :(

**Comment by ccrama** [comment]
Fixed with my last commits

**Comment by okungnyo** [comment]
Wait, you fixed "every view that loads more at the bottom except for the main SubmissionView"?

**Comment by l3d00m** [comment]
yes, because it's all the same class

**Comment by okungnyo** [comment]
Cool, @ccrama made it sound like a huge problem that would be really hard to fix.

**Comment by l3d00m** [comment]
sometimes you don't know how big a problem is before you fixed it. and it was a huge issue, wasn't it?

**Comment by okungnyo** [comment]
I don't use multireddits, so this wasn't a huge issue for me lol.

Do you use multireddits? If so, I have a few questions.

**Comment by l3d00m** [comment]
Yes, I do. One 'science' multi, one tales from multi and one android multi

**Comment by okungnyo** [comment]
Ok then, here's my question. How does that affect your frontpage?

Like, which subs from which multi show up on your frontpage?

**Comment by l3d00m** [comment]
not at all i think, the "science" subs should not show up on my frontpage anyway, and i'm subscribed to all android multis, so i don't use that multi that often

**Comment by okungnyo** [comment]
So subreddits in a multireddit don't show up on the main frontpage?

**Comment by 530farm** [comment]
I believe they would show up on the Frontpage if they are subscribed to. However you can put subs in a multi without subscribing, in which case they wouldn't show on the Frontpage or a stand alone sub

**Comment by okungnyo** [comment]
That sounds like a great way to keep an eye on an interesting subreddit that you wouldn't necessarily want on your main frontpage.

So for subreddits like /r/me_irl that I want to browse when I'm in the mood, but don't want showing on my frontpage, I would put it in a multireddit called "Mood lifters".

Did I get that right?

**Comment by l3d00m** [comment]
Yep
