### ISSUE TITLE
Comment approval icon always appears 

### ISSUE THREAD

**Issue by Soberat** [ccrama/Slide#799]
No matter if you're a mod for a sub or not,  comment approval button is displayed in action bar. Tapping it doesn't give any messages and closes the action bar. Wiping app's data didn't help. 
Screenshot : http://imgur.com/BSoEhoG.png

**Comment by l3d00m** [comment]
I cannot reproduce this. No idea why this happens to you :/

**Comment by Soberat** [comment]
Got it. Will check it further later today.

**Comment by ccrama** [comment]
There is no more icon there, removed for now!
