### ISSUE TITLE
Some dialogs have incorrect title color

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#80]
A great example of this would be the settings dialog with the light theme enabled.

**Comment by ccrama** [comment]
Looks fine for me. Can you provide a screenshot please.

**Comment by alexsmithfanning** [comment]
Yes I can. Here you go: https://goo.gl/zZtKhn

**Comment by ccrama** [comment]
That is not an issue. It takes the current theme color not current subreddit color.

**Comment by Alexendoo** [comment]
Perhaps the text colour was being referred to rather than the background, namely it being black rather than white:

![](http://i.imgur.com/pOphhwM.png)

**Comment by Alexendoo** [comment]
Particularly noticeable with the new sidebars
![](http://i.imgur.com/BUNU0G2.png)

**Comment by ccrama** [comment]
Sorry, it's really just user preference. That would take a LOT of work to do and I don't know if its a big enough issue to do right now.
