### ISSUE TITLE
Loading posts without [Always show offline data first] still takes twice as long as other Reddit apps

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#800]
Of course, I turned off [Always show offline data first] for fairness.

I used Relay for Reddit for comparison:

https://play.google.com/store/apps/details?id=free.reddit.news
https://play.google.com/store/apps/details?id=reddit.news

And the difference in loading speed was like 1-2 seconds.

Although that doesn't sound like much, if you visit multiple subs, those seconds really do add up and make a huge difference.

I imagine speed is an important factor for many other users as well.

**Comment by Alexendoo** [comment]
I can't reproduce this on my end, if you're swiping through subreddits a lot at a time to get to the one you want you may be hitting some rate limiting by reddit is a possible explanation of what you're experiencing

**Comment by okungnyo** [comment]
Kill both apps, then load up Relay and see how long it takes to load your frontpage. Do the same with Slide. The difference is there, I assure you.

**Comment by ccrama** [comment]
I did testing and it was near identical in speed. What kind of network are you on? Slide also preloads images so that might contribute

**Comment by ccrama** [comment]
Also, Relay uses cookie authentication which is less secure (and might have to be changed due to Reddit's new usage TOS) but is faster.

**Comment by okungnyo** [comment]
Ah, so that's why Relay is faster.

Is there really other no way to improve speed without making Slide insecure? That's a bummer...

**Comment by ccrama** [comment]
Yep it is

**Comment by okungnyo** [comment]
Two related questions.

1. On a cold start, does Slide load just the frontpage? Or does it predict and preload other subs too?

2. And does Slide preload any pics or GIFs?

**Comment by ccrama** [comment]
1) Just loads the visible sub and the one(s) next to it.

2) Preloads pics
