### ISSUE TITLE
Settings sliders under Settings > Reddit settings do nothing/reset themselves

### ISSUE THREAD

**Issue by Anorion121** [ccrama/Slide#806]
The two settings toggles under Settings > Reddit settings seem to revert to default as soon as you navigate away from the settings page.

To replicate: Go to Settings > Reddit settings and toggle the Hide all NSFW photos toggle. Press back. Go back to Reddit settings. Notice that the toggle is still set to "on".

**Comment by dvanselow** [comment]
Same bug, galaxy note 4 verizon

**Comment by ccrama** [comment]
Not applicable anymore (it's all removed)
