### ISSUE TITLE
"gif not found" error when trying to view imgur link

### ISSUE THREAD

**Issue by abraham** [ccrama/Slide#809]
Happens when tapping on the post thumbnail or content link.

https://www.reddit.com/r/woahdude/comments/4138t9/three_way_joint/

![screenshot_20160115-152857](https://cloud.githubusercontent.com/assets/3341/12365895/61fb27f4-bb9d-11e5-962d-4829a5d3fa7e.png)

**Comment by ccrama** [comment]
Fixed with latest commit

**Comment by abraham** [comment]
Still an issue on the 4.5.1 release.

**Comment by ccrama** [comment]
Do you have an example? I haven't run into it yet

**Comment by abraham** [comment]
https://www.reddit.com/r/woahdude/comments/4138t9/three_way_joint/

**Comment by abraham** [comment]
Another example https://reddit.com/r/funny/comments/45rz7s/tactical_diversion/

**Comment by ccrama** [comment]
This has been fixed with my latest commits
