### ISSUE TITLE
Replace stopgap Settings popup with full-blown dialog

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#81]
In not much of a particular order:

* General: Contains stuff that doesn't fit anywhere else, like whether edgeswipes go back and sideswipes switch posts or vice versa, or whether comments are tap-to-collapse/hold-to-act or tap-to-act/hold-to-collapse, or single-subreddit mode.
* Notifications: Contains the various notification options, from LED color to ringtone to ringtone/vibration/light toggles to update check frequency.
* Default Theme: Small popup, changes global color scheme (light/dark/black, main, accent)
* Subreddit Themes: See #36. Might be able to wait.
* Default Layout: Full-screen, opens the postlist-customization thing to be eventually overhauled as detailed in #29.
* Subreddit Layouts: See #36. Might be able to wait.
* Pro: Contains the subcategories for customizing Multi-Column, Shadowbox, and Night Mode(when it happens, might actually be a good idea to hold off until 4.1 for it), as well as any future things. Might actually be a good idea to just split this up, though, especially considering the tentative F-Droid edition.
* Support Slide: Donate dialog. Simple enough.

**Comment by ccrama** [comment]
Done with 98550c3f2bd280405d222f07ef293766925743de. Still adding some items but it's mostly functional at this point!
