### ISSUE TITLE
Sidebar animation problems

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#813]
1. Its reveal animation is jerky. (Compare it to the reveal animation of the navigation drawer and you will see the difference.)

2. It does not follow your finger. Even moving your finger slowly just to open the sidebar a little bit makes the sidebar open completely.

3. When you first open the sidebar, it "scrolls" down by itself and hides the buttons at the top (submit, subscribe, wiki).

**Comment by ccrama** [comment]
All should be fixed now
