### ISSUE TITLE
Provide descriptions for settings where appropriate

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#814]
Some settings need more than two/three words to describe what exactly is they do, having a small tagline underneath would help in many cases. For example how some settings are described in android's settings app.

![](http://i.imgur.com/DNR4rRB.png)

**Comment by okungnyo** [comment]
I mentioned it in https://github.com/ccrama/Slide/issues/573

**Comment by ccrama** [comment]
Merging this with #1128
