### ISSUE TITLE
filters bug

### ISSUE THREAD

**Issue by perler** [ccrama/Slide#817]
I just tried the filters by putting three words in three lines into the filter dialog. this resulted in slide not displaying anything anymore. 

problem is, even after clearing out all terms, still no posts are displayed. 

let me specify,  nothing is shown after the floating button is pressed to hide seen posts. 

after clearing the cache, posts reappear.

**Comment by Alexendoo** [comment]
This one's covered in #601 - It's requested quite a lot to separate out titles/comments/etc

**Comment by Alexendoo** [comment]
Apologies wrong one, too many tabs open

**Comment by okungnyo** [comment]
How many tabs do you have open, man? lol

**Comment by Alexendoo** [comment]
I read the github notifications a few at a time, like around 5, then act upon them. Usually fine but I wasn't paying enough attention

**Comment by ccrama** [comment]
I have fixed this a while ago.
