### ISSUE TITLE
Move the entire comment box out of the way of the keyboard

### ISSUE THREAD

**Issue by anonymous-user** [ccrama/Slide#820]
When replying or posting a comment, my keyboard will cover everything below the reply line. I have to manually scroll up to see the formatting toolbar and discard/submit buttons. It would be nice if this could be changed so that the buttons and toolbar are moved out of the way automatically.﻿

**Comment by l3d00m** [comment]
Fixed

**Comment by ccrama** [comment]
Slide now does this AFAIK
