### ISSUE TITLE
Mark a Message as read from the notification

### ISSUE THREAD

**Issue by hary585** [ccrama/Slide#822]
This is something I'd like to see. Like if you expanded the notification, it would give you options to quick reply or mark as read because this is some quality of life stuff I'd like to see.

**Comment by 530farm** [comment]
I am going to try and implement this.

**Comment by l3d00m** [comment]
added with 42e131f61d056d41ff404a8ac8e6e721db2851b8, thanks to @530farm

**Comment by hary585** [comment]
perfect lets goooooo
