### ISSUE TITLE
Submission saving isn't working in mainactivity

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#828]
It is working in post view, but not in the mainactivity

The linked issues below are all caused through this.

**Comment by ccrama** [comment]
Works fine for me, can save with the little star icon and also in the menu

**Comment by l3d00m** [comment]
@ccrama also in the post menu in mainactivity? the star icon is working too for me

**Comment by ccrama** [comment]
Yeah it's working there for me

**Comment by okungnyo** [comment]
Saving with the star icon on the post card works for me too.

But saving with [overflow 3-dot icon > Save post] is not working. It says "Post saved", but it's not...

**Comment by ccrama** [comment]
Fixed!
