### ISSUE TITLE
Inconsistent card view

### ISSUE THREAD

**Issue by joytrekker** [ccrama/Slide#829]
There are two issues with the card layout.
1. The cards show the sub, author, points and comments # all on the same line. The points and comments get pushed to a newline depending on the the length of the preceding text. This makes it very hard to scan down the feed and see what post have a high/low amount of points and comments. 
I suggest the points and comments be move to a newline since the comments are always warped to a new line anyway. In the screenshot the middle card is a good example of what it should look like. 

2.The left and right margins are different when thumbnails are used. 
The screenshot shows the margin on the right between thumbnails is to small. 
![screenshot_20160118-123030](https://cloud.githubusercontent.com/assets/5538589/12402254/97224ada-bde0-11e5-9e8b-3e0d524d050c.png)

**Comment by okungnyo** [comment]
Good catch, I was meaning to post something like this.

**Comment by ccrama** [comment]
Done and done with v4.6

**Comment by joytrekker** [comment]
I just recompiled v4.6 alpha and issue #2 still remains.

**Comment by ccrama** [comment]
Fixed with my brand new redesigned card layouts
