### ISSUE TITLE
Show cake day icon for users who are celebrating cake day

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#831]

**Comment by l3d00m** [comment]
I don't think we will add such a feature because it's pretty unimportant. Sorry for that.

**Comment by okungnyo** [comment]
Have you no heart? Have you never seen that little cake icon next to usernames and said to them "happy cakeday!"?

**Comment by l3d00m** [comment]
No :p

**Comment by okungnyo** [comment]
I have to disagree, every issue related to a reddit.com feature should be kept open because you never know what will happen in the future.

You didn't want to add WebView and separate font sizes for posts and comments, and both were eventually added.

All I request is that minds be kept open.
