### ISSUE TITLE
Scrolling Lag on Front page 

### ISSUE THREAD

**Issue by mattlyons0** [ccrama/Slide#832]
I have a LGG4 which has a 2,560x1440 resolution. On the subreddit view (front-page or any other sub) I experience noticeable input Lag. Nothing crazy like 500ms but around 50-200ms. Enough to make scrolling down feel bad. Although I do have some frame drops when viewing comments (or maybe the smooth scrolling is jumpy), I do not have the very noticeable input Lag that I do in the front page. I would say there is around 2-4x worse input Lag on the front-page than in the comments. Also enabling show touches in dev options makes it even more apparent. If you want to send me a apk with some performance profiling I'd be more than willing to run that for you.

**Comment by ccrama** [comment]
Fixed with latest commits (changed from StaggeredGridLayoutManager to PrecachingLinearLayoutManager)

**Comment by mattlyons0** [comment]
I haven't noticed any change in latency on the front-page after updating. I'm not sure if you changed the manager on the comments as well but they are as laggy as the front-page now (if not worse, although it may seem worse due to the frame drops when scrolling).

**Comment by Deadleg** [comment]
This should be much better now with the latest release. Closable?

**Comment by Alexendoo** [comment]
Indeed, @mattlyons0 if it's still bad for you feel free to reopen, but the last update should help greatly

**Comment by mattlyons0** [comment]
Great work guys! Scrolling is very smooth (Feels like 60fps on the frontpage, maybe 40-50 in comments) and very responsive.
