### ISSUE TITLE
Go to quarantined/private sub causes crash

### ISSUE THREAD

**Issue by joytrekker** [ccrama/Slide#834]
In the newest build Slide crashes if you use the textbox in the drawer to go to a sub that is banned or requires an invite.

**Comment by l3d00m** [comment]
somehow related to #498

**Comment by l3d00m** [comment]
Also related to https://github.com/thatJavaNerd/JRAW/issues/93

**Comment by Alexendoo** [comment]
No longer should cause a crash, however related is #949
