### ISSUE TITLE
Keyboard covers results in drawer subreddit search

### ISSUE THREAD

**Issue by joytrekker** [ccrama/Slide#835]
Using the newest build...
When selecting the textbox in the drawer the keyboad covers the subs making autocomplete useless unless the user scrolls up. The solution would be to make the drawer and textbox scroll to the top of the screen when clicked.

**Comment by okungnyo** [comment]
It scrolls up automatically for me.

The [Go to subreddit] text field scrolls up by itself to just above the keyboard.

**Comment by Alexendoo** [comment]
The search field isn't the issue, the suggestions are, ideally it would scroll to the following position

![](http://i.imgur.com/hX4XrQT.png)

**Comment by okungnyo** [comment]
I didn't even know there *were* suggestions lol

**Comment by ccrama** [comment]
That's a really good idea @joytrekker! I'll do that asap

**Comment by ccrama** [comment]
Done with my latest commit
