### ISSUE TITLE
Use pngcrush?

### ISSUE THREAD

**Issue by GermainZ** [ccrama/Slide#84]
Running pngcrush on the PNGs in res/ roughly saves 0.7M.

- size of res/ before running pngcrush: 24836655 ≈ 23.69M
- size of res/ after running pngcrush: 24113615 ≈ 23.0M

I just ran `for i in **/*.png; do pngcrush -reduce -ow $i; done`, which does *lossless* compression, FYI.

**Comment by alexsmithfanning** [comment]
You could probably do better with OptiPNG.

**Comment by GermainZ** [comment]
optipng and pngcruh give similar results (`pngcrush -reduce` actually saved around 19 whole kilobytes over `optipng -o7`), but pngquant goes a bit further saving an extra 0.3M:

    $ for i in **/*.png; do pngquant --speed 1 --skip-if-larger --force -o $i $i; done
    $ du -bs
    23820871    .

≈ 22.72M

**Comment by alexsmithfanning** [comment]
OptiPNG with all functions separately. Not just -o7.

**Comment by ccrama** [comment]
Going to go to vector drawables here soon!
