### ISSUE TITLE
Some issues with Slide

### ISSUE THREAD

**Issue by SethDusek** [ccrama/Slide#843]
- Links should open using webview,  not browser 

- Youtube should open using youtube app,  not web browser 

- Option to use imgur app for imgur links (useful for galleries)

**Comment by l3d00m** [comment]
1. It's possible to open it in webview: Settings > Link Handling > Disable "Use Chrome Custom Tabs"
2. That is possible if you set youtube as your default app for that
3. Deactivate Settings > Link Handling > album view / image view
