### ISSUE TITLE
Go to comment permalink

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#844]
https://plus.google.com/u/0/+AdrienPyke/posts/JcFWQHuCidY

**Comment by l3d00m** [comment]
Isn't this the same as #819?

**Comment by okungnyo** [comment]
We'd have to ask the man himself what he exactly meant, but my interpretation was:

#819: Add a [Go to parent comment] in the overflow menu for comments. Use case: when you see a comment that's the third or fourth reply down, and you forgot what the comment is replying to, and want to see that parent comment again.

#844 (this): You know how underneath comments, there are two links, [permalink] and [context]? Well in Slide, when you tap on a comment in your profile, it automatically goes to the comment in [context] view mode. The man is requesting a [permalink] view mode as well, which would only show that comment and its children.

**Comment by l3d00m** [comment]
Then this is a good idea. I have no idea why we need the other one though.

**Comment by kufii** [comment]
@l3d00m I mentioned this in the google+ thread, but the use case is for when you're viewing a reply to a comment in context mode, you can only see the parent comment and the reply comment. Going to permalink lets you see the parent comment and _all_ the replies. So it's for when you want to see the rest of the replies to a comment, loading full thread would be really cumbersome and it would be hard to find your spot.

**Comment by ccrama** [comment]
When you load more replies, it actually scrolls back down to the position of the comment you last opened the menu of. Does this not work?

**Comment by kufii** [comment]
that would be a good, however it isn't working for me

**Comment by ccrama** [comment]
Added a "Go to permalink" button in the comment menu!
