### ISSUE TITLE
Show a [Showing results for "peanut butter"...] message above search results

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#845]

**Comment by l3d00m** [comment]
What is this and why?

**Comment by l3d00m** [comment]
What is this and why?

**Comment by okungnyo** [comment]
What do you mean?

Similar to the [This is an archived post. You won't be able to vote or comment.] message.

So if the user searches for 'peanut butter', a yellow bar under the action bar could say [Showing results for "peanut butter"...]

And when you tap on the bar, you can change what you want to search for without having to start from scratch (useful when your search term is looong).

**Comment by ccrama** [comment]
Done for v4.6!
