### ISSUE TITLE
[Go to top]

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#847]
https://plus.google.com/111048658411269639919/posts/SLSfK9QVSoT

> When I am scrolled down a subreddit a long way, to save time scrolling all the way back to the top, it would be nice to have a "go to top" feature. 
>
> I suggest that it be when you press on the subreddit's name at the top of the screen it takes you to the top of the page. ﻿

**Comment by Alexendoo** [comment]
Available with comment navigation on by long pressing the up arrow

**Comment by ccrama** [comment]
Done! Now you can tap on the toolbar or subreddit tab to go to top
