### ISSUE TITLE
On Settings>General>[Alphabetical sidebar]...

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#848]
1. [Alphabetical sidebar] is misleading. [Alphabetical subreddit list in navigation drawer] would be more apt.

2. Actually, this setting should just not exist at all. All it does is confuse users, like so: https://plus.google.com/113951066459473422927/posts/1yDba3c7QFB

The subreddit ordering in [Reorder your subs] should be universal and apply everywhere.

Less confusion and settings-bloat that way.

**Comment by Alexendoo** [comment]
I agree with this one, seems very niche

**Comment by ccrama** [comment]
Has been removed, good points @okungnyo  :)
