### ISSUE TITLE
Reordering subreddits does not change the order in the navigation drawer until Slide is restarted

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#849]
If this is a bug, then, umm, yeah, a fix would be appreciated. The subreddit ordering in the navigation drawer should update immediately.

But if this is by design, then there should be a prompt telling the user that Slide needs to be restarted for the changes to take effect.

(Settings>General>[Alphabetical sidebar] is disabled.)

**Comment by ccrama** [comment]
Not an issue anymore! Fixed in v4.6.1
