### ISSUE TITLE
Long Usernames Extend too Far in Navigation Drawer

### ISSUE THREAD

**Issue by karlding** [ccrama/Slide#85]
If you log in using an account name over 13 characters long, the text will extend behind the **Log Out** text. I've attached a screenshot below.

![Portrait Mode]
(http://i.imgur.com/yynwNJr.png)

Same thing for landscape mode.

![Landscape Mode](http://i.imgur.com/qYx7yXy.png)

I took a look through the [reddit source code](https://github.com/reddit/reddit/blob/master/r2/r2/lib/validator/validator.py#L1471-L1474), which seems to imply that usernames are expected to be between 3 and 20 characters long (lines 1471-1474). Perhaps the username should be moved onto its own line?

```py
MIN_USERNAME_LENGTH = 3
MAX_USERNAME_LENGTH = 20

user_rx = re.compile(r"\A[\w-]+\Z", re.UNICODE)
```

**Comment by ccrama** [comment]
Fixed a while ago with the addition of the account chooser! Forgot to close this.

**Comment by karlding** [comment]
I'm running version 4.2.0, and now the "Manage Accounts" is being blocked

![Manage Accounts](http://i.imgur.com/UxoLprl.png)

**Comment by ccrama** [comment]
Whelp crap. Ill put it under "profile" then!

**Comment by l3d00m** [comment]
it's fixed now
