### ISSUE TITLE
A [+]/[-] icon to hide the subreddit list in the navigation drawer

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#850]
For users who are either (1) subscribed to a ton of subreddits and/or (2) use Subreddit Tabs and don't need the navigation drawer to show the subreddits list all the time.

Source: https://plus.google.com/111935954636440596417/posts/NjznEHhYcAD

**Comment by l3d00m** [comment]
This was discussed before and we won't add this. Reason is that there isn't anything below the drawer which needs to be shown.

**Comment by okungnyo** [comment]
That makes sense.
