### ISSUE TITLE
Greater notification delay

### ISSUE THREAD

**Issue by codlike** [ccrama/Slide#852]
* [x] When you turn off or on notification settings, it doesn't change the message underneath until you exit out of the General tab and re enter the General tab.
So if you untick notifications it doesn't confirm that notifications are disabled, until you exit the General tab and re enter it. 

* [ ] On a separate thought is it possible to delay checking for messages greater than an hour, eg 2, 3 hours, even just daily. Keep up the good work your app looks lovely.

**Comment by okungnyo** [comment]
+1, I noticed this too and was going to report it, you beat me to the punch.

**Comment by l3d00m** [comment]
I fixed the first one with 55f0a9d0f8eebf8b5abbeda3f8aa5ee5f2625485

**Comment by ccrama** [comment]
You can set it to check up to 24 hours. Am I missing something?

**Comment by ccrama** [comment]
This is already possible, OP has not responded
