### ISSUE TITLE
Spinning load circle animation doesn't stop when bottom has been reached

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#856]
Test case: use any user profile with a few comments, and keep scrolling down.

**Comment by l3d00m** [comment]
Can you elaborate on that? I don't get it

**Comment by okungnyo** [comment]
In Slide, go to any profile, and keep scrolling down until you reach the bottom (preferably a profile with only a few comments, so you don't sit there all day scrolling down).

The spinning circle animation never stops spinning despite the fact that there are no more posts/comments to show.

**Comment by l3d00m** [comment]
This is fixed now
