### ISSUE TITLE
Chrome custom tab share shouldn't ask to be default

### ISSUE THREAD

**Issue by abraham** [ccrama/Slide#865]
"just once, always" doesn't make any sense here. It should be the standard share dialog that doesn't ask for you to set a default.

![screenshot_20160119-125238](https://cloud.githubusercontent.com/assets/3341/12510076/b7f2c5de-c0cc-11e5-8019-eedab8ac2636.png)

**Comment by okungnyo** [comment]
What kind of a share dialog is this??

**Comment by ccrama** [comment]
I don't handle this, it's all handled by the Chrome app and your OS. Sorry

**Comment by Alexendoo** [comment]
It's possible to get a list of apps supporting custom tabs, and then to launch it with a chosen package directly

https://github.com/GoogleChrome/custom-tabs-client/blob/master/demos/src/main/java/org/chromium/customtabsdemos/CustomTabActivityHelper.java#L40-L64
https://github.com/GoogleChrome/custom-tabs-client/blob/master/shared/src/main/java/org/chromium/customtabsclient/shared/CustomTabsHelper.java#L53-L107

This would be a good addition IMO, the only caveat being additional logic may be required to determine if there's a native app, however that may be a plus if #1116 is implemented? Not sure myself

**Comment by Alexendoo** [comment]
Fixed with 4a793aa8cf2156b4d803d80da9dc5688f6601301
