### ISSUE TITLE
Chrome custom tab share uses previous URL

### ISSUE THREAD

**Issue by abraham** [ccrama/Slide#866]
Open a link in Chrome custom tab

![screenshot_20160122-055744](https://cloud.githubusercontent.com/assets/3341/12510225/0bbc667e-c0ce-11e5-9efa-bbb152aaf15d.png)

Share it and everything works as expected

![screenshot_20160122-055804](https://cloud.githubusercontent.com/assets/3341/12510235/1e8b01a2-c0ce-11e5-9424-64aa14fc7b88.png)

Go view a different URL

![screenshot_20160122-060018](https://cloud.githubusercontent.com/assets/3341/12510251/2d9a86d6-c0ce-11e5-8b78-ebd6884aa136.png)

Try and  share it but instead the first URL is shared again.

![screenshot_20160122-060030](https://cloud.githubusercontent.com/assets/3341/12510260/3ea0fd3e-c0ce-11e5-999e-64dc5c7b6aa5.png)

The URL being shared will stay the same even after force closing the app.

**Comment by szeichorn** [comment]
IIRC Chrome custom tabs does not give the app any info regarding further pages that the user navigates to, so maybe this should be brought up with Google until they implement a solution.

Can a Dev chime in?

**Comment by ccrama** [comment]
Correct. This is all handled exclusively by Chrome and there isn't much I can do about it. Might want to make this an issue with Google :(

**Comment by Alexendoo** [comment]
This should be possible to do, I checked out the custom tab demos by Google and they added something similar, it's a toast that shows the current URL 

https://github.com/GoogleChrome/custom-tabs-client/blob/master/demos/src/main/java/org/chromium/customtabsdemos/CustomUIActivity.java#L165-L171

It would also be possible to replace the current custom share button with .addDefaultShareMenuItem() on the intent builder, this works like normal chrome, so no custom icon on the toolbar

**Comment by Alexendoo** [comment]
Fixed with 4a793aa8cf2156b4d803d80da9dc5688f6601301
