### ISSUE TITLE
Galleries do not load more than 10 images

### ISSUE THREAD

**Issue by SZE2** [ccrama/Slide#867]
How do I add the "BUG" label?

Attached is a link to a Reddit post containing a 63 image album.

Slide will only show the 1st 10 images both in shadowbox or in regular view, with no option to load the rest.

Latest beta.

Albums not completely loading

https://www.reddit.com/r/pics/comments/41aexc/this_guy_found_a_huge_underground_facility/

Google+ bug report: https://plus.google.com/+ZalmanEichorn/posts/LLKgaW1yMZ8

**Comment by Snagg57** [comment]
Confirmed, reproducible on the latest Slide Beta. Nexus 6 5.1.1

**Comment by Alexendoo** [comment]
This happens only on gallery links not just albums - ie `imgur.com/gallery/...` but not `imgur.com/a/...`

**Comment by l3d00m** [comment]
This is a bug with the old imgur api and will be fixed as soon as #977 gets merged.

**Comment by Alexendoo** [comment]
It seems this is fixed in horizontal albums, but not vertical

**Comment by ccrama** [comment]
Should be fixed now for both. Let me know if it's not

**Comment by ccrama** [comment]
Now using v3, no more issues hopefully
