### ISSUE TITLE
Don't treat image/album view background like a piece of paper now that it's translucent

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#868]
The background shouldn't cast a shadow. Perhaps it should fade out the further to the right the image is swiped.

**Comment by Nath5** [comment]
I like the idea of a fade out, not sure the shadow is wrong though, even a translucent sheet will cast some shadow.

**Comment by The0x539** [comment]
It definitely *looks* wrong as it is right now. If it's gonna cast a
shadow, it should be underneath it too.

**Comment by ccrama** [comment]
Better animation has been added (less paper-y)

**Comment by The0x539** [comment]
http://i.imgur.com/Y2tJAqs.png

**Comment by ccrama** [comment]
I am closing this issue as there is an option to disable the transparent background, and the enter animation has been adjusted accordingly (and the exit animation if you tap to exit)
