### ISSUE TITLE
It's possible to set main colour to none

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#87]
I haven't managed to figure out exactly what's causing this one but I've had it happen two times before (but forgot to take screenshots, but it definitely occurs within the new theme settings, I shall investigate more.

![screenshot_2015-10-15-22-25-04](https://cloud.githubusercontent.com/assets/1830331/10528124/3a4777fc-738c-11e5-8fe8-5a683e276a68.png)
![screenshot_2015-10-15-22-24-56](https://cloud.githubusercontent.com/assets/1830331/10528125/3a4e2d0e-738c-11e5-962c-88ebf3754102.png)
![screenshot_2015-10-15-22-24-53](https://cloud.githubusercontent.com/assets/1830331/10528126/3a4f09ae-738c-11e5-87ae-5c8dbb8f4abd.png)

**Comment by ccrama** [comment]
Caused by not selecting a color on the color choosing dialog in settings. Working on a fix atm!

**Comment by ccrama** [comment]
Fixed 2853f0cbc308d8779a52a6c31cf8212e06da189d. It now pre-selects the default color
