### ISSUE TITLE
Search sorting keeps reverting back to [Past 24 hours]

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#870]

**Comment by ccrama** [comment]
It is automatically set to the month, nowhere in the code is 24 hours even stated. Can't reproduce

**Comment by okungnyo** [comment]
Slide --> action bar --> overflow menu --> search --> action bar --> clock icon

You don't see the [Past Hour], [Past 24 Hours], [Past Week], [Past Month], [Past Year], and [All Time] sorting options?

**Comment by ccrama** [comment]
Yes, it is set to Past Month automatically for me

**Comment by okungnyo** [comment]
For me, if I select any other sorting option, it will keep changing back to [Past 24 Hours].

By that, I mean the radio button for [Past 24 Hours] will be filled.

I don't know if it actually does sort by past 24 hours (maybe this is a similar bug from a few months ago when the comment sort was changing to [Hot] when the user selected another.)

**Comment by ccrama** [comment]
Shouldn't be an issue anymore
