### ISSUE TITLE
Support for advanced search

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#872]
I was wondering why searching "self:yes" in /r/all was not working.

For example, the result for "self:yes" sorted by "top - past 24 hours" should be: https://www.reddit.com/r/SandersForPresident/comments/4235jg/clinton_superpac_offers_burlington_free_press_vt/

But Slide returns this: https://www.reddit.com/r/depression/comments/424841/2_days_ago_i_got_a_new_girlfriend_and_she_said/

(Note, I am subscribed to neither of those two subreddits; I was searching ALL.)

And I think the problem is that Slide doesn't support advanced search filters:

https://www.reddit.com/wiki/search

Some examples from the above page:

* title: The submission title.

For example, title:cats

* author: The user who submitted the post.

For example, author:PresidentObama

* selftext: For self-posts, the body of the post.

For example, selftext:cats

* subreddit: The submission's subreddit.

For example, subreddit:cats

* url: The submission's URL (the website's address).

For example, url:cats

* site: The domain of the submitted URL.

For example, site:example.com

* nsfw: Whether the post is NSFW.

Set to yes for NSFW submissions, no otherwise. 1 and 0 are also supported.
For example, nsfw:no or nsfw:0

* self: Whether nor not the submission is a text post.

Set to yes for text posts, no otherwise. 1 and 0 are also supported.
For example, self:yes or self:1

* flair: The text of the link flair on the post.

For example, flair:cats

* You can also search multiple fields at once.

For example, cats title:standing site:imgur.com

**Comment by ccrama** [comment]
Done, now Slide supports the advanced options and will open links with the advanced options.
