### ISSUE TITLE
Show a [This account is already added] when the user tries to log in with an account that has already been added

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#873]
I was testing for #853 with a secondary account, but I forgot to delete the account before adding it.

To my surprise, Slide didn't recognize that it had already been added.

**Comment by ccrama** [comment]
All I receive is the api key, not the account name or anything until after it's registered. Can't really fix this.

**Comment by okungnyo** [comment]
So basically, Reddit doesn't give out user info to clients for privacy reasons, and consequently you can't check whether an account has already been added?

Did I understand that correctly?

**Comment by ccrama** [comment]
Yes, that's exactly it. When the user boots up for the first time, I request the username and that's how I display it, but other than that I know nothing about the user.

**Comment by okungnyo** [comment]
OK, thanks.
