### ISSUE TITLE
Deleting an account doesn't automatically switch Slide to an undeleted account

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#874]
I logged into a secondary testing account, and then deleted it. But Slide continued to work as if I were in the second account (the message saying "Hello, secondary-account", tapping [Your profile] opening /u/secondary-account instead of /u/okungnyo, etc.)

Slide should automatically switch to an undeleted account when it detects that a particular account has been deleted.

**Comment by ccrama** [comment]
It does this for me on v4.5.1, it switches if you delete the current account

**Comment by okungnyo** [comment]
Not for me.

Try this:

1. Be on account #1.
2. Add account #2. Let Slide restart on its own, but don't restart manually.
3. Now delete account #2.

Post results.

**Comment by ccrama** [comment]
Did that, after I delete the other account it pops up with the previous account and lets me go back to it

**Comment by l3d00m** [comment]
Fixed with v4.6
