### ISSUE TITLE
[Create a new account] in the navigation drawer

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#876]

**Comment by okungnyo** [comment]
Maybe this should be included in #883, but this one would naturally go into the navigation drawer while those other ones wouldn't.

So I decided to make this one a separate issue.

**Comment by ccrama** [comment]
I don't think the workflow for Authentication will allow me to do that and get the new Auth token afterwards, but you can already create a new account from the "Add Account" screen.
