### ISSUE TITLE
Gifs become transparent when exiting and entering the app 

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#88]
![](http://i.imgur.com/BVyq5PZ.png)

**Comment by theRealPadster** [comment]
This seems like it might be the same bug I have encountered lately. It seems whenever I try to load a gif/gyf if takes a long time to load and then just displays fragments of what was behind it before I opened the image.

**Comment by ccrama** [comment]
I don't think this is still an issue. Can someone confirm?

**Comment by joytrekker** [comment]
I just recompiled and I can confirm this is still a bug. As theRealPadster said it happens when gif/gyf are loading. The previous layout/activity is visible in the space where the gif/gyf should be.

**Comment by theRealPadster** [comment]
Actually mine seems to work fine now.

**Comment by Alexendoo** [comment]
Still occurs on 8e7455f70d5d0e9096380317aca85b9297614798

**Comment by ccrama** [comment]
Has been fixed on my branch

**Comment by Alexendoo** [comment]
Seems to have cropped up again sometime, it's occuring on 2675a24cf9abd0b1d9fdc6c50ac72254ffb62c13 at least

**Comment by ccrama** [comment]
Fixed for real this time
