### ISSUE TITLE
Toggle in Settings to show top-level comments only, and hide all children comments by default

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#880]

**Comment by Alexendoo** [comment]
Seems very niche

**Comment by okungnyo** [comment]
Well, you know what they say, every niche feature is a butterfly waiting to bloom...

**Comment by l3d00m** [comment]
Where would this be useful? I can't think of any use cases for this.

**Comment by The0x539** [comment]
Who's "they", here, and in what context?

**Comment by ccrama** [comment]
Now there's a button in the comment screen overflow menu which lets you collapse all!
