### ISSUE TITLE
A section with important reddit.com links

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#883]
These are important Reddit pages that would be hard/impossible to replicate natively:

* [Create your own subreddit]: https://www.reddit.com/subreddits/create
* [Account activity]: https://www.reddit.com/account-activity

They would all open in the internal browser, of course.

More suggestions are welcome.

**Comment by ccrama** [comment]
These seem rather niche, I feel like this would overcomplicate the Slide menus

**Comment by okungnyo** [comment]
What I liked about Slide when I first discovered it was that you were open to suggestions, but now you seem to be against anything and everything I suggest.

Aren't you being a bit hasty and judgmental with the [wontfix] tag? What's wrong with leaving it open in case circumstances change and you become open to it.

Is it because I'm creating so many issues? If so, I will stop. I have no reason to be where I am unwanted.

There is a link to [Reddit preferences], right? All I'm asking for is something similar; just a link somewhere. It would not complicate the menus at all.

[Account activity] is pretty important, about as important as [Reddit preferences], I'd say.

**Comment by Alexendoo** [comment]
It helps developers to have a list of things that needs to be implemented/fixed, so that it stays useful it's important to close duplicates and things that are not intended to be implemented, so that it stays a nice reference. It's quite difficult to keep on top of but ensuring it stays useful means closing some suggestions

**Comment by ccrama** [comment]
Yeah, exactly what @Alexendoo  said. I have over 160 open requests with 80% of them suggestions. If I implemented everything, Slide would get major feature creep and I would spend my working days just adding new features in. Most of us are in IRC all the time and discuss the issues there, and collectively decide to close or open issues, and we choose which ones we're currently going to work on or wont fix.

**Comment by okungnyo** [comment]
Yes, I get what you are saying, that some issues need to be closed, etc. etc.

What I am saying is, but then what about all these issues here?:

https://github.com/ccrama/Slide/issues?page=7&q=is%3Aissue+is%3Aopen

They haven't been closed, despite the fact that they suggest things that would make Slide more bloated.

So what makes this suggestion different than all those ones?

**Comment by Alexendoo** [comment]
Some things slip through, we comb through them every so often making decisions but it's a bit of work. Doing it as they arrive is easier

**Comment by ccrama** [comment]
Most of the ones that are still open have:

A) Not been seen by me yet (there are over 800 issues so far and I'm one guy)

B) Are being planned on being implemented but haven't yet (see the ones labeled bug or help wanted, over 25% of them)

C) Are not applicable anymore and need to be closed

D) I look at the most recent issues first and haven't had time to go through to the very first issues on Github. 

It has nothing to do with you or your suggestions, but if you ever develop an app with this many users, suggestions, and features, you would understand that some suggestions, despite how good they may be, are gonna be closed for one reason or another.

**Comment by okungnyo** [comment]
All right, thanks for the explanations.

Sorry I made an e-fuss over nothing.
