### ISSUE TITLE
Would it be possible to have a [History] section that keeps a log of every post that the user taps on in Slide?

### ISSUE THREAD

**Issue by okungnyo** [ccrama/Slide#884]

**Comment by ccrama** [comment]
I already keep track of it, but it would take a TON of api requests to pull all those submissions and would probably get Slide kicked for rate limiting. Sorry :(

**Comment by okungnyo** [comment]
I don't understand.

I mean like a local-only version. Just track which "posts" the user taps on, and have a history page for it.

How would that be different from a web browser having a [History] page?

**Comment by ccrama** [comment]
a) Computers have lots more free storage space
b) To store the submission, I keep the submission ID. If you want to get anything about the submission (like display it in a history page), I'd have to request Reddit to return that submission object. If you have more than just a few of them, it would use quite a bit of requests

**Comment by okungnyo** [comment]
a) I was talking about Android browsers like Firefox and Lightning (both open source)/

b) I think I get it now, it's like with the account names? Reddit doesn't give you the full post titles, it just gives you an ID?

**Comment by ccrama** [comment]
Yes. And by A) I meant storing the post titles or information would take up a ton of storage and would be unfeasible, and that is why I store only the IDs which create issue B)

**Comment by okungnyo** [comment]
Understood.

**Comment by ccrama** [comment]
Actually I just added it into the profile section
