### ISSUE TITLE
Sidebar activation when browsing posts and easier subreddit selection.

### ISSUE THREAD

**Issue by beepFTW** [ccrama/Slide#885]
Can you add the option to make the left sidebar activate with a left swipe on any part of the screen? It's extremely hard to activate with my phone case and fat fingers.

And another feature id like is, if you tap the name of the subreddit on top of the screen, it opens a list of all subscribed subreddits (like Relay for Reddit). I like that way more than the current implementation.

Thanks for reading!

**Comment by ccrama** [comment]
The second request is done with @Nxt3 's latest PR, the first will not happen because it conflicts with other swipe gestures in the app.
