### ISSUE TITLE
Can't enable NSFW Thumbnails

### ISSUE THREAD

**Issue by odwk** [ccrama/Slide#886]
Is there a way to load nsfw thumbnails? They are enabled in reddit.com prefs and load on other clients, but they don't work on Slide. The only way to see nsfw posts is to load the full image

**Comment by beepFTW** [comment]
I had to log out, go onto desktop prefs enable then disable it again. Now when you relog into slide you should be able to see them. 

As long as you don't restore your backup. Also I have no idea if all of this is even needed to fix the thumbnails, but this worked for me.

**Comment by odwk** [comment]
Just tried that. It didn't work, thumbnails keep working on browsers and on other clients but not on Slide

**Comment by okungnyo** [comment]
It would be nice if NSFW content & thumbnails were a client setting separate from those of reddit.com.

That's how every other client seems to do it, and that's how people expect it to work.

It would certainly cut down the weekly can't-enable-NSFW help threads.

**Comment by ccrama** [comment]
It's not possible with the Reddit API @okungnyo . Sync and RIF (and the others) will follow what the Reddit prefs do, and Relay and a few others use a fake account with the stuff enabled inside to always show the content and handle it internally. Otherwise, the Reddit API won't even return nsfw content, nsfw thumbnails,or submission thumbnails if the user has disabled it. That being said, I'm looking into why some users are still having issues with it :(

**Comment by okungnyo** [comment]
Got it.

You should have an FAQ on the G+ page or somewhere that explains all this.

As I said above, that would cut down the weekly can't-enable-NSFW help threads.

**Comment by odwk** [comment]
This isn't exactly an help thread, though. As I said, NSFW thumbnails are enabled in reddit prefs (I can see them on desktop) but Slide isn't showing them. Not even after logging out and in again.

**Comment by ccrama** [comment]
@odwk  did you enable nsfw content and disable the checkbox to make it safe for work?

**Comment by odwk** [comment]
@ccrama Yes. NSFW content is enabled and the sfw checkbox is not checked. 
While using the website, nsfw thumbnails are visible on both sfw and nsfw subreddits (if that can make a difference). On Slide, nsfw thumbnails are never shown. Not even after revoking access to the app from preferences and logging in again.

**Comment by ccrama** [comment]
Fixed with my last commit @odwk ! Thanks for the report
