### ISSUE TITLE
"Last updated" shown twice

### ISSUE THREAD

**Issue by abraham** [ccrama/Slide#887]
I open the app after not using it in several hours and I immediately get two "last updated" toasts.

![screenshot_20160122-223611](https://cloud.githubusercontent.com/assets/3341/12528356/037f97de-c159-11e5-940e-0d090845300e.png)
![screenshot_20160122-223556](https://cloud.githubusercontent.com/assets/3341/12528357/0381010a-c159-11e5-9e66-cc5ba61740df.png)

**Comment by Nath5** [comment]
Pull request to fix:
https://github.com/ccrama/Slide/pull/898
