### ISSUE TITLE
"no more posts" not showing in Shadowbox mode

### ISSUE THREAD

**Issue by SZE2** [ccrama/Slide#890]
Latest beta version, Android 6.0

When viewing a small sub, you will often run into the "no more posts" message. But when in Shadowbox mode the message is missing, and there is no indication it animation that your are at the end of the list

**Comment by szeichorn** [comment]
Will someone please explain to me how to tag issues with the correct label on Android?
Or which app supports it?
Mine (gitskarios) doesn't let me...

**Comment by Alexendoo** [comment]
Labelling has to be done by contributors which is probably why you didn't see an option.

As for the issue, you get an overscroll animation when trying to swipe again if you've ran out of posts, is this not showing on your phone or insufficient?

**Comment by ccrama** [comment]
The fact you can't scroll anymore should be the default behavior that shows you there are no more items in the pager

**Comment by SZE2** [comment]
Now it is loading a overscroll effect. I guess it just wasn't showing for me last time.
Thanks!
