### ISSUE TITLE
Scrolling / switching side menu lags 

### ISSUE THREAD

**Issue by Dehcimal** [ccrama/Slide#893]
Hi, 

I do have a xiaomi redmi note 2 that has an octocore 2.2ghz, 2gb of ram and a 1920x1080 display.

Everytime I try to switch between sub menus or scroll down/up the scrolling is very laggy/choppy  my actual rom is miui 7 (6.1.21)

**Comment by l3d00m** [comment]
#832 

What do you mean with sub menus?

**Comment by Dehcimal** [comment]
Whenever I'm swiping if you prefer.

**Comment by Dehcimal** [comment]
If I switch submenus say : league of Legends channel, Diablo 3 channel
submenus = subreddit
