### ISSUE TITLE
Comment loading when swiping

### ISSUE THREAD

**Issue by anandroiduser** [ccrama/Slide#894]
When you swipe between posts in the comments view, every fifth one or so will not load the comments at all until you the comments view and click on the post directly.

**Comment by l3d00m** [comment]
This is not happening for me on the newest commit (791749c505292206b7c86a8ef62bc67226e4990c), no idea if that is fixed now or if it's just not happening for me

**Comment by anandroiduser** [comment]
Yep, it seems to have been fixed now.
