### ISSUE TITLE
Submitting Sublevel Comments takes you back to the Post Content

### ISSUE THREAD

**Issue by SZE2** [ccrama/Slide#896]
If I reply to a top-level comment lower down in the comments, after submitting Slide will refresh and take me to the top of the comment list, with the content preview. it's annoying to scroll back to where I was.

Ideally it should leave me exactly where I was before submitting, but with showing my comment as well if applicable.

Slide 4.5.1, Android 6.0

**Comment by ccrama** [comment]
Shouldn't be an issue anymore
