### ISSUE TITLE
Post swiping looping

### ISSUE THREAD

**Issue by anandroiduser** [ccrama/Slide#899]
When swiping between posts from the comments view in the latest version, when you get to the end, it loops back to the first post instead of ending the list or loading more.

**Comment by Alexendoo** [comment]
Can't reproduce on my end, what slide and android versions are you using?

**Comment by anandroiduser** [comment]
I'm on slide 4.5.1, Nexus 6P Android 6.0.1

**Comment by ccrama** [comment]
Can't reproduce this either

**Comment by l3d00m** [comment]
I can reproduce it, after waiting a moment at the end of the current loaded posts, it begins from start again

**Comment by anandroiduser** [comment]
Yep, exactly what happens to me

**Comment by ccrama** [comment]
Has been fixed for a while!
