### ISSUE TITLE
Shadowbox sets the wrong dimensions for gifs/gfy that are taller than the display.

### ISSUE THREAD

**Issue by joytrekker** [ccrama/Slide#901]
If you load a gif/gyf that has a height that is greater than the height of the portrait layout of your device  then the gif/gyf is squished down. The expected behavior would be for the gif/gyf to scale down and retain the original dimensions. This bug occurs landscape mode as well.

**Comment by Alexendoo** [comment]
Can't reproduce this on my end - with landscape at least, I didn't find any gifs that would meet the criteria in portrait

**Comment by joytrekker** [comment]
You need the right size gif/gfy to see the bug. It's dependent on the gif having a height greater than the longest dimension of your device. Then the gif is stretched/squished. Here is an example from landscape mode...  http://imgur.com/cUpOYxS

**Comment by Alexendoo** [comment]
Is this still an issue @joytrekker? Doesn't seem to be occurring for me when finding a sufficiently tall gif

**Comment by joytrekker** [comment]
I just took a look and Im happy to report that this is now fixed.

**Comment by Alexendoo** [comment]
Grand
