### ISSUE TITLE
Posts not loading...

### ISSUE THREAD

**Issue by anandroiduser** [ccrama/Slide#902]
When you clear read posts and there are less than 4 or so posts left on the screen, slide will stop loading posts or say no more posts.

**Comment by ccrama** [comment]
There probably isn't any more posts in that sorting mode. What do you have it set to (hot, new, etc)?

**Comment by anandroiduser** [comment]
I have it set to hot, but there absolutely are more posts. Just to be clear, this only happens when I *clear read posts* and there are 4 unread ones *left*. If I don't clear read posts and continue to scroll down, it loads properly

**Comment by Fnarley** [comment]
Slightly related, apologies if this should be a seperate thread in its own right - if so just say and I'll make one: 

I don't use clear read posts but still get 'no more posts' fairly regularly if I scroll down further than 50 posts or so. I use default sorting, so 'hot' I guess. Happens on all subs including frontpage. It reminds me of the banner you sometimes get on desktop when never ending reddit (RES feature) runs out of posts to display but without the 'scroll or click to load more posts' option.

**Comment by ccrama** [comment]
Both issues should be fixed already
