### ISSUE TITLE
Multi-reddits don't have FAB or Shadowbox functionality

### ISSUE THREAD

**Issue by mjwhitta** [ccrama/Slide#904]
I recently decided to start using multi-reddits for organization. I was saddened to see that, while browsing multi-reddits, I'm unable to hide read posts, as the FAB isn't there. It also appears the Shadowbox feature is not in the toolbar. This lack of consistency between "views", or lists of Reddit posts, interrupts the user experience.

I heard this was because the sidebar wasn't wanted in multi-reddits, but I feel it could be useful to create an on-the-fly sidebar and fill it with links to subreddits that the multi-reddit is composed of. This may mean that multi-reddits could be listed below subreddit subscriptions in the drawer, and may even allow for more code reuse.

Having only briefly looked at the source, I have no idea how big of challenge this may be.

**Comment by mjwhitta** [comment]
I recently decided to start using multi-reddits for organization. I was saddened to see that, while browsing multi-reddits, I'm unable to hide read posts, as the FAB isn't there. It also appears the Shadowbox feature is not in the toolbar. This lack of consistency between "views", or lists of Reddit posts, interrupts the user experience.

I heard this was because the sidebar wasn't wanted in multi-reddits, but I feel it could be useful to create an on-the-fly sidebar and fill it with links to subreddits that the multi-reddit is composed of. This may mean that multi-reddits could be listed below subreddit subscriptions in the drawer, and may even allow for more code reuse.

Having only briefly looked at the source, I have know idea how big of challenge this may be.

**Comment by Alexendoo** [comment]
Related #903

**Comment by ccrama** [comment]
Done with my new_offline_model PR
