### ISSUE TITLE
Crash after clicking a link

### ISSUE THREAD

**Issue by mortiz** [ccrama/Slide#905]
Slide unexpectedly stops under the following scenario:

* open a subredit 
* click on a post that has enough comments to require scrolling 
* click on a link and open it in any browser or app
* click the back button 

At that point I get the "slide stopped unexpectedly" dialog. This does not happen if there are not a sufficient number of comments to cause the page to scroll. 

I'm running android 5.0.1 on an LG-V489 (GPad 2, 8.0)

**Comment by l3d00m** [comment]
Interesting, which Web viewer are you using? Custom tabs, Web view or, our browser?

**Comment by mortiz** [comment]
Any and all. A couple of examples: (all with default settings in Slide)

* chrome
* atlas browser
* cm browser
* Firefox
* Google play store 

I tried with custom tabs and without, which produces the same behavior.

**Comment by mortiz** [comment]
I just tried using the internal browser and it doesn't crash upon returning to Slide, however the link never loads. (I tried a few)

**Comment by l3d00m** [comment]
I have no problems at all with link loading or crashes caused through that :(

**Comment by mortiz** [comment]
If it helps any, my device is a low-end one. It's only got 1GB of memory. I wonder if there is some sort of issue with whatever android uses as an OOM killer? I'll load it up on my phone (gs6) and a genymotion VM and see if I can replicate the issue.

**Comment by l3d00m** [comment]
The low memory could be related, yes. That would be very helpful, thanks!

**Comment by mortiz** [comment]
So I tried it in a genymotion VM running marshmallow with 2GB of memory and did not have the same issue. I then lowered the memory to 1GB. Still did not have the issue. The issue is also not present on my GS6 which has 3GB of memory and runs android 5.1.1. So it is either something specific to 5.0.1 or to something LG does.

I will try to throw together a 5.0.1 genymotion VM at some point if there is a gapps bundle for that version.

**Comment by mortiz** [comment]
It must be something related to LG's software or their OOM handling. The 5.0.1 VM works perfectly fine. If there is any debugging I can do please let me know. Otherwise this is probably just a tiny corner case that doesn't merit a fix

**Comment by l3d00m** [comment]
Have you reported it after it crashes? If we have a stacktrace, the chance is at least higher to fix it. Also thanks for the extended testing on your side, that made it a lot easier for us.

**Comment by mortiz** [comment]
I did report a couple of the crashes early on. I can do it under specific conditions if you think that would be helpful.

**Comment by ccrama** [comment]
Should not crash anymore. If it continues to occur, feel free to re-open the issue!
