### ISSUE TITLE
Subreddit order constantly getting reset

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#908]
Sorry if someone already reported this, I searched for it but I couldn't find it.

The order for subreddits gets reset just about every time I change settings, when I switch users, or when slide crashes. This is the one bug stopping me from using the app full time.

**Comment by l3d00m** [comment]
You can set the default order in settings > general

**Comment by kufii** [comment]
Sorry, I don't mean sorting. I mean the Reorder your Subs under your profile. The order never stays for more than an hour

**Comment by ccrama** [comment]
The order has never reset for me. What settings do you have enabled (alphabetical sidebar, etc)?

**Comment by kufii** [comment]
subreddit tabs enabled, swipe away from anywhere disabled, alphabetical sidebar disabled, 2 accounts linked both with their own order. They both get reset frequently.

for some reason now that I actually try to reproduce it it's not reseting. That's frustrating.

**Comment by ccrama** [comment]
That has been fixed in my new branch
