### ISSUE TITLE
Bug with the crash reporter

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#91]
If you have a custom client installed for GitHub (OctoDroid for example), the crash reporter crashes.

**Comment by ccrama** [comment]
Whelp that's awkward

**Comment by alexsmithfanning** [comment]
You could use CustomTabs to avoid the "open with" thing right?

**Comment by ccrama** [comment]
Eh sorta. That will open with default intent anyway so the same issue would occur. It's a bug with those respective apps, not much I can do about it

**Comment by alexsmithfanning** [comment]
You could give the option of copying the stacktrace to the clipboard?

**Comment by Alexendoo** [comment]
Reasonable workaround, submit that as an enhancement. As for memory usage it's only text, it'll be like a few KB
