### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by anandroiduser** [ccrama/Slide#913]
Compared to other reddit apps, slide seems to have much higher CPU utilization, causing the phone to get slightly warm and the battery to drain rapidly.

Nexus 6P, slide 4.5.1

**Comment by anandroiduser** [comment]
Possibly related: using slide for an extended period of time makes it have a very high "mobile radio active time". This may be due to bugs in Android, but other reddit apps do not seem to have this issue.

**Comment by l3d00m** [comment]
No problem for me, with anroid 5.0.2 and slide 4.5.1

**Comment by alexsmithfanning** [comment]
I can run it just fine too.

**Comment by anandroiduser** [comment]
I'm on 6.0.1, so perhaps that's the issue

**Comment by ccrama** [comment]
I'm on 6.0 and it runs fine, none of those issues are occurring for me. Slide also does batch requests to not keep the phone using mobile radio, so I don't know why you're having that issue either :(

**Comment by anandroiduser** [comment]
Weird. Here's an example of the mobile radio active issue: http://imgur.com/a/G1RBM

**Comment by ccrama** [comment]
Really can't help you there. If you are loading lots of content then yes, Slide has to use the mobile radio to contact Reddit, Imgur, and other servers. If you use cached data first and load comments mainly, the mobile radio active won't be an issue.
