### ISSUE TITLE
Spoilers not working in side bars, self post body, and with the light theme

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#914]
I know you guys know about this, but I didn't see it in the bug tracker so I thought I should add it.

Spoilers are not clickable in subreddit sidebar and in self post body text.

In light mode, the reveal colour is black, so it doesn't reveal properly

**Comment by Alexendoo** [comment]
Thanks, added the last point to #785

**Comment by ccrama** [comment]
THANK YOU for finding this. I have always had light theme on and could never figure out why spoilers never worked in my app. Can't believe this was the issue haha, will fix this asap

**Comment by ccrama** [comment]
Fixed with v4.6 and @Deadleg 's work

**Comment by kufii** [comment]
Has this been released yet? It's not working for me with the latest update

**Comment by l3d00m** [comment]
Only released for the alpha group. The link to join it can be found in the g+ group.

**Comment by kufii** [comment]
Sweet, it's working perfect. Thanks!
