### ISSUE TITLE
Clearing all read posts

### ISSUE THREAD

**Issue by anandroiduser** [ccrama/Slide#923]
When you clear read posts and there are none left, you are taken to a blank screen instead of more posts being loaded.

**Comment by SZE2** [comment]
Also, if you then reload, it will load posts that you read already, and will only load more unread posts if you scroll down past all the read posts until Slide leads
Loads more posts, and than you can clear all read posts with the FAB

**Comment by ccrama** [comment]
That is only if you have cached data set to always show. If you are not on cached data it loads more correctly. And that's the intended behavior @SZE2 , if you long press on the fab it will hide forever, though.

**Comment by SZE2** [comment]
I didn't know that, it's great! Thanks!
