### ISSUE TITLE
Comments overlay scrollbar

### ISSUE THREAD

**Issue by BitQuote** [ccrama/Slide#924]
The overlay scrollbar for comments doesn't have a smooth a transition like the sidebar one, which makes it look super jumpy.

**Comment by Alexendoo** [comment]
Very strange, it sort of shrinks and grows when scrolling down on my device

**Comment by anandroiduser** [comment]
Yes, but unlike the sidebar overlay scrollbar it doesn't smoothly transition between sizes.

**Comment by Alexendoo** [comment]
It shouldn't be changing size at all

**Comment by anandroiduser** [comment]
I'm talking about scrolling through comments

**Comment by Alexendoo** [comment]
(poor quality) video: https://vid.me/LaSM

The scrollbar changes size whilst just scrolling, which is rather strange

**Comment by anandroiduser** [comment]
Yep, that's what I was referring to

**Comment by ccrama** [comment]
The RecyclerView knows there are, let's say 300 items in the pager, including the top post and every body comment. It assumes the sizes are constant, that every item in the recycler will be the same size as the first loaded comments or the submission on top. When you scroll, some comments are larger than others and it realizes this, and changes the scrollbar size accordingly, which makes it look jumpy. There is no way for me to fix this, unfortunately.

**Comment by ccrama** [comment]
A fix is not really possible, sorry
