### ISSUE TITLE
Checkbox for subscribing

### ISSUE THREAD

**Issue by anandroiduser** [ccrama/Slide#926]
Currently, Slide uses a checkbox to subscribe/unsubscribe to subreddits. According to the material design spec, when there are fewer than two options, an on-off switch should be used instead.

Source: https://www.google.com/design/spec/components/selection-controls.html#selection-controls-checkbox

**Comment by Alexendoo** [comment]
Which is a shame, personally I think the switches are rather less nice looking.

One thing though I haven't looked to find it in the spec again but should the sidebar not be flat? ignoring the fact that there are currently some out of place buttons on it, sliders wouldn't be flat elements like checkboxes

**Comment by anandroiduser** [comment]
Ah, you're right. It should be a checkbox.
