### ISSUE TITLE
Preallocate space for big pictures

### ISSUE THREAD

**Issue by anandroiduser** [ccrama/Slide#932]
There should be a placeholder thumbnail while the real one is loading to prevent jumping while thumbnails are loading.

**Comment by Alexendoo** [comment]
I don't see any layout changes caused by thumbnails loading, the space is blank initially but text doesn't flow into it, what version are you running?

**Comment by anandroiduser** [comment]
I'm running the latest GitHub version.

On the main screen, the cards become larger when the thumbnails are loaded. Before that, the post looks like it doesn't have a link. Same for the comments view. I can share a video if needed.

**Comment by anandroiduser** [comment]
https://vid.me/y5CK

**Comment by ccrama** [comment]
I would have to know the image height before loading it, which wouldn't work unfortunately

**Comment by anandroiduser** [comment]
If "crop big picture" is enabled, wouldn't you know the height? Similarly, a placeholder link could also be used when big picture is disabled.

**Comment by ccrama** [comment]
In crop big picture, it does this already

**Comment by Alexendoo** [comment]
Doesn't for me - perhaps due to #933?

**Comment by ccrama** [comment]
Done with my latest commits
