### ISSUE TITLE
No more posts on reload

### ISSUE THREAD

**Issue by anandroiduser** [ccrama/Slide#937]
When you come back to a subreddit after a crash or after viewing another subreddit, Slide will say no more posts at the bottom instead of loading more. This happens if you have "show offline first" enabled.

**Comment by ccrama** [comment]
That is what it's supposed to do. If it is using cached data, it only shows what it has.

**Comment by anandroiduser** [comment]
Well the setting says "show offline posts *first*", implying that more will be loaded later

**Comment by ccrama** [comment]
More will be loaded if you pull to refresh, the post order has changed by the time the cached data is being displayed, meaning load more wouldn't function at all
