### ISSUE TITLE
New subscription while app is running

### ISSUE THREAD

**Issue by anandroiduser** [ccrama/Slide#939]
If you subscribe to a sub in the browser or anywhere else while Slide is running and then open it again, Slide crashes.

**Comment by ccrama** [comment]
Cannot reproduce, can someone else see if they can?

**Comment by anandroiduser** [comment]
The way I get it is:

1. Open Slide
2. Google search for something on reddit (with the Google App)
3. Open the reddit link with Slide
4. Subscribe to the subreddit from the Google search Slide
5. Go back to the running instance of Slide

Crash

**Comment by hary585** [comment]
Can confirm, reproduced.

**Comment by Alexendoo** [comment]
@anandroiduser @hary585 Can you still reproduce this on 4.6?

**Comment by ccrama** [comment]
Fixed!
