### ISSUE TITLE
The side pullout menu should remember it's position, and highlight the current sub.

### ISSUE THREAD

**Issue by SZE2** [ccrama/Slide#942]
<githubroot>[Enhancement] 
This would make going through all your subs much easier.

In case it's unclear, I'm referring to the view in this screenshot.

![screenshot](http://i.imgur.com/oFp0FDV.png)</githubroot>

**Comment by ccrama** [comment]
This would not work with searching because it removes items from the list and shrinks the size, losing both position and the highlighted value. Will have to mark this as wontfix, unfortunately

**Comment by ccrama** [comment]
Now it remembers the place, I will not be highlighting it, though

**Comment by SZE2** [comment]
Thank you!
