### ISSUE TITLE
Gify will start playback in middle, not the beginning.

### ISSUE THREAD

**Issue by SZE2** [ccrama/Slide#943]
I think this only occurs in Shadowbox mode. I most recently saw it on the post linked below, when it was the 3rd from top on r/funny, I started from the top in Shadowbox mode, when I got to this it started playing from the middle.

I cannot reproduce it in the same gif twice, so I think it may be a problem with the way they are loaded into memory the 1st time?

I do see it multiple times a session though.

Reply if you need more info to pin this down.

https://reddit.com/r/funny/comments/438bn4/the_immense_power_required_for_launching_a_rocket/

**Comment by SZE2** [comment]
Title messed up, I meant a gify, damn autocorrect

**Comment by l3d00m** [comment]
Probably the same as #577. It never happened for me.

**Comment by SZE2** [comment]
Correct, it is a duplicate.
What Android github app lets you search for issues?
My current one (gitskarios) didn't find that duplicate...

**Comment by l3d00m** [comment]
I'm using Forkhub, which let's you search issues.

**Comment by SZE2** [comment]
I'll try it
