### ISSUE TITLE
Comment scrolling stutters

### ISSUE THREAD

**Issue by anandroiduser** [ccrama/Slide#945]
Whenever you scroll down so that the action bar slides up, there is some stuttering in the comments section that is quite noticeable. There is similar stuttering when scrolling up to show the action bar. Just to be clear, the stuttering is only present when scrolling to show/hide the action bar in the comments section, not in general.

Nexus 6P, Android 6.0.1 stock rooted, latest github build

**Comment by ccrama** [comment]
Pretty much all fixed (20+ fps more than before) with v4.6
