### ISSUE TITLE
Opening r/redditslide crashes every time

### ISSUE THREAD

**Issue by comprocket** [ccrama/Slide#947]
I'm not subscribed, but instead just trying to go to the sub. Each time it caused the app to crash

**Comment by ccrama** [comment]
That subreddit doesn't exist, and if I type it in it has a popup that says "This subreddit doesn't exist". Do you not get a popup?

**Comment by comprocket** [comment]
No pop-up for that non existent sub. Others do have a pop-up though!  I tested with "bla111" and get the pop-up. I submitted two crash reports for this today.

**Comment by l3d00m** [comment]
Merging into #834
