### ISSUE TITLE
Private, banned and quarantined subreddits aren't indicated

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#949]
When you attempt to visit one the standard 'subreddit not found' dialog is displayed rather than showing a message indicating it's invite only.

Conveniently `/r/inviteonly` is invite only to test this.

Somewhat related is `/r/lounge` which, on reddit, has a unique message instead of just displaying invite only

**Comment by ccrama** [comment]
Not possible to get this information as the API always returns a 403 error. Instead, I added a sentence to the dialog saying you might not have permission to view this subreddit.
