### ISSUE TITLE
Info button provides no feedback on front/all

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#95]
title (using newest code)

**Comment by Alexendoo** [comment]
Are you currently looking in the frontpage or all? It now only works in subs

**Comment by l3d00m** [comment]
Ok, problem found. Can it be hidden from frontpage and all?

**Comment by l3d00m** [comment]
Or better, don't hide it because the theme settings but use a Placeholder for front and all that says "cannot show sidebar for frontpage/all"

**Comment by l3d00m** [comment]
merge with #336
