### ISSUE TITLE
very frequent crashes, OOM error

### ISSUE THREAD

**Issue by oatberry** [ccrama/Slide#950]
I get random crashes every 5-10 minutes while using slide. Since I can't copy-paste the strace, [here](http://imgur.com/a/nTC9X) it is in screenshot form from the bug report screen. Device, Nexus 6p. Android version, 6.0.1 stock rooted. Slide version, 4.5.1

Thanks!

**Comment by ccrama** [comment]
That is trying to allocate 0.1 megabytes of ram, so it looks like RAM might not be the culprit. Also, only 6% of total crashes on the 6P are out of memory errors, so that leads me to believe there is some other issue going on (There have only been 340 total crashes on the 6P out of 1,737 users, so the average 6P user has only crashed 5 times since installing Slide).

**Comment by oatberry** [comment]
I found that disabling XPosed fixed this issue, but I'm wondering if it's a specific module causing trouble. More investigation required, but I'll close this one.

**Comment by oatberry** [comment]
I found that disabling XPosed fixed this issue, but I'm wondering if it's a specific module causing trouble. More investigation required, but I'll close this one.

**Comment by oatberry** [comment]
I found that disabling XPosed fixed this issue, but I'm wondering if it's a specific module causing trouble. More investigation required, but I'll close this one.

**Comment by oatberry** [comment]
I found that disabling XPosed fixed this issue, but I'm wondering if it's a specific module causing trouble. More investigation required, but I'll close this one.

**Comment by oatberry** [comment]
I found that disabling XPosed fixed this issue, but I'm wondering if it's a specific module causing trouble. More investigation required, but I'll close this one.

**Comment by oatberry** [comment]
I found that disabling XPosed fixed this issue, but I'm wondering if it's a specific module causing trouble. More investigation required, but I'll close this one.
