### ISSUE TITLE
Slide crashes regularly 

### ISSUE THREAD

**Issue by varystargaryen** [ccrama/Slide#951]
It crashes constantly; I can't get three minutes of use without the message "Unfortunately, Slide has stopped, especially during scrolling and attempting to edit multireddits. 

 I'm running an AT&T Galaxy S5 on 5.0.2. ﻿

**Comment by ccrama** [comment]
Are you on a spotty network by chance? There has to be something causing Slide to crash.

**Comment by varystargaryen** [comment]
No, my network is solid. I've never had issues anywhere else.

**Comment by ccrama** [comment]
I haven't crashed in days (and neither have the majority of my users based on Google Play data), so there has to be something else causing stability issues. How much RAM does your device have?

**Comment by varystargaryen** [comment]
Approximately 2 GB. It's a Galaxy S5. Sync for Reddit Dev has never crashed and the rest of my apps, including RAM intensive games never lag or crash. That's what baffles me.

**Comment by ccrama** [comment]
Yeah my 2gb ram device has never crashed (nexus 5 2013). Have you tried resetting app data? Sounds like a device specific issue because the vast majority of my users are not experiencing this issue.

**Comment by varystargaryen** [comment]
I'll try that. I haven't cleared the data but I clear the cache every crash and force stop it, to no avail.

**Comment by ccrama** [comment]
Try clearing data and see if that fixes your issues.

**Comment by varystargaryen** [comment]
I simply reinstalled the app after clearing all temporary files, cache, etc. It seems to have worked. The speed and smoothness has been amplified. I'll let you know if anything major changes.

**Comment by ccrama** [comment]
Alright! That is interesting, but hopefully that fixes your issue

**Comment by l3d00m** [comment]
Probably related to #950?

**Comment by oatberry** [comment]
@l3d00m I've tried everything that @varystargaryen has and more, it didn't help.

**Comment by ccrama** [comment]
Almost all of these issues have been fixed in my new_offline_branch branch
