### ISSUE TITLE
Shadowbox mode not marking read on scroll

### ISSUE THREAD

**Issue by SZE2** [ccrama/Slide#956]
[BUG]
I think this may be a duplicate, but I couldn't find it...

Screencaps: www.vid.me/xNI7

**Comment by SZE2** [comment]
Still broken in 4.6 alpha

**Comment by ccrama** [comment]
I didn't say I fixed it yet

**Comment by SZE2** [comment]
Oops, sorry

**Comment by ccrama** [comment]
Fixed!
