### ISSUE TITLE
NSFW Thumbnails not yet fixed. All Reddit preferences allow all NSFW to be enabled. 

### ISSUE THREAD

**Issue by varystargaryen** [ccrama/Slide#958]
Google+ stated that it would be fixed in the 4.5 update, but I am running 4.5.1 and it is still not yet fixed. 

Thank you.

**Comment by l3d00m** [comment]
Settings > Reddit settings > NSFW photos maybe? Working for me.

**Comment by varystargaryen** [comment]
No effect. Reddit preferences are set correctly.

**Comment by ccrama** [comment]
It is working on the current new branch @l3d00m , not in production. It's fixed though for the next release

**Comment by varystargaryen** [comment]
In the Slide app, the "Hide all NSFW photos" under Reddit Preferences is disables and grated out.

**Comment by varystargaryen** [comment]
Grayed out*

**Comment by ccrama** [comment]
It's already fixed on github
