### ISSUE TITLE
Opening a post linked in a PM will not mark it as read.

### ISSUE THREAD

**Issue by SZE2** [ccrama/Slide#959]
If you are having a hard time reproducing this, I can post screencaps.

Latest beta from Google play, Android 6.0

**Comment by ccrama** [comment]
So if you click on a URL in a PM, it won't mark as read? That is the intended behavior if I understand you correctly.

**Comment by SZE2** [comment]
If you open a Reddit link (e.g. To a ask Reddit discussion), it will not show that discussion as read in the regular sub list view later.

I'll upload screencaps after the weekend hopefully.

**Comment by ccrama** [comment]
Oh, I understand. That's strange, it should definitely be marking as read. Will look into it

**Comment by ccrama** [comment]
Has been fixed for a while, actually!
