### ISSUE TITLE
Voting on comments is not possible

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#97]
I cannot vote on comments, it simply does nothing. Voting on posts is no problem. That happens using the latest alpha release or using the (newer) code directly from github (self compiled)

**Comment by Alexendoo** [comment]
additional: Attempting to tap up/downvote hides the bar

**Comment by l3d00m** [comment]
I think it should hide the bar and is intentional

**Comment by ccrama** [comment]
It is now! 53d04b62cd50a7ed30a7eb55abd286dc709de7b4
