### ISSUE TITLE
Alert the user if thumbnails are disabled via reddit preferences

### ISSUE THREAD

**Issue by aaroncraigongithub** [ccrama/Slide#970]
Slide v4.5.1
Android v6.0.01
Nexus 6

Settings > Post layout: Card mode on, Big picture enabled on, Crop big picture on, Image in middle of card off.

The layout in any column (Front page, all, etc) shows a grey globe placeholder thumbnail image in the right corner of the card.  Same when I click on a post.  To see any images I have to click on the placeholder thumbnail.  Once I do that the image opens using the internal viewer.

**Comment by Alexendoo** [comment]
Are your thumbnail preferences on reddit.com set to not display thumbnails? That would explain what you're experiencing

**Comment by aaroncraigongithub** [comment]
That was it, nearly.

I actually had link compression on, which implicitly disables thumbnails.

However, from a UX point of view, that's a lot of information about how reddit.com and Slide interact to expect an average user to know.

I suggest adding a note in the settings screen around the appropriate controls (as reddit.com does -- it says in red letters "to enable thumbnails, disable compressed link display" near the Media settings) to alert users that they need to enable thumbnails in their reddit.com preferences in order for them to also display in Slide.

**Comment by Alexendoo** [comment]
Settings are planned to be looked at pretty thoroughly, the reddit preferences affecting the app is a reasonably large part of that so should manage to get something good going, wasn't aware there was another such option that disabled thumbnails also, thanks for catching that.

**Comment by aaroncraigongithub** [comment]
My pleasure!  Thanks for helping out -- at least I can see images in all their glory now :)

**Comment by Alexendoo** [comment]
Merge into #1128
