### ISSUE TITLE
Memory leak in new_offline_model

### ISSUE THREAD

**Issue by Deadleg** [ccrama/Slide#972]
If you go to the comments page for a submission in a subreddit with lots of images, continue to swipe right. The memory usage goes up and up until it crashes. Memory usage goes up in text heavy subreddits too.

**Comment by ccrama** [comment]
Same thing with swiping horizontally on subreddits. I did a ton of memory profiling and it looks like just tons of bitmaps are being stored in memory, and tons of strings are being stored attributed to OKHTTP and JRAW. I have disabled just about everything I added in the new_offline_model (including all the OfflineSubreddit stuff) to no avail, will be working on more memory optimization soon, though!

**Comment by ccrama** [comment]
I think it's because Slide is generating a new OfflineSubreddit object every time it is called, I'm switching it to a static get method and returning a instantiated version of the OfflineSubreddit if it exists. Will report back

**Comment by ccrama** [comment]
Turns out it was the ViewTreeObserver in the HeaderLinkView. Have fixed and will push soon!
