### ISSUE TITLE
CommentPage crash when swiping right in new_offline_model

### ISSUE THREAD

**Issue by Deadleg** [ccrama/Slide#973]
Open the comments page for a submission and swipe right to the end. When you get to the last loaded submission you get an null pointer exception at [here](https://github.com/ccrama/Slide/blob/new_offline_model/app/src/main/java/me/ccrama/redditslide/Fragments/CommentPage.java#L330) where `o.submissions.get(page)` is null.

**Comment by Deadleg** [comment]
This has been fixed at some point.

**Comment by ccrama** [comment]
I believe I fixed it with 4.6 :)
