### ISSUE TITLE
Floating action button doesn't show in unsubscribed subs

### ISSUE THREAD

**Issue by 2fst4u** [ccrama/Slide#979]
Would be good for the floating action button to show in subs that you aren't already subscribed to.

**Comment by ccrama** [comment]
Which floating action button?

**Comment by 2fst4u** [comment]
None at all.  I particularly want the "hold to hide viewed" one to show.

**Comment by ccrama** [comment]
I don't understand what you are referring to. The hide viewed shows up on all subs including multis if you have it enabled

**Comment by 2fst4u** [comment]
Not for me.

Example of sub I subscribe to:
http://imgur.com/YCSbbaW


Example of sub I don't subscribe to:
http://imgur.com/2voJQ31

After scrolling up and down it doesn't show

**Comment by ccrama** [comment]
Oh, it doesnt show on the single subreddit view. I don't know if this would be worthwile to add, you shouldn't have history on that sub if you are visiting it as a single sub.

**Comment by 2fst4u** [comment]
Wink wink. There are reasons.

**Comment by ccrama** [comment]
Done!
