### ISSUE TITLE
When typing a comment reply, text typed is hidden.

### ISSUE THREAD

**Issue by 2fst4u** [ccrama/Slide#981]
Unsure where this issue lies, but when typing a comment reply the text is hidden by by keyboard so I can't see what I'm typing. This doesn't happen in any other apps and I'm using stock Google keyboard.

**Comment by l3d00m** [comment]
Could you take a Screenshot of it? That would make it a bit easier to understand!

**Comment by 2fst4u** [comment]
http://imgur.com/T7baMLI after hitting reply and starting to type, it looks like this.

For reference after scrolling down a small amount, here is the text I typed:
http://imgur.com/ZMuUvD4

**Comment by l3d00m** [comment]
Alright, can reproduce. This is easier to reproduce if a post has 0 comments, but happens on multiple comments too.

**Comment by ccrama** [comment]
Merging with #820
