### ISSUE TITLE
Cannot open Reddit links received via PM

### ISSUE THREAD

**Issue by SZE2** [ccrama/Slide#982]
<githubroot>4.6 Alpha

Www.vid.me/J7Tt

It only opens the reply box.</githubroot>

**Comment by SZE2** [comment]
vid.me/J7Tt

**Comment by ccrama** [comment]
Fixed with my last commit

**Comment by SZE2** [comment]
Was fixed, now I'm having the issue again.

https://vid.me/8sVk

**Comment by ccrama** [comment]
Has been fixed again with my other commits last night
