### ISSUE TITLE
Gallery view captions text improvements

### ISSUE THREAD

**Issue by SZE2** [ccrama/Slide#983]
<githubroot><githubroot>[Enhancement][4.6 alpha issue]

The image viewing experience is far better, but the captions are much less useful now...

Please make the text smaller (the same or similar size as user's set comment text), so you can see more of it.

Please make the text background opaque. It's quite hard to read the text when you see other text under it. (See screenshot)

Please let me scroll the caption text, there is a scroll bar, but you can't actually scroll(see screenshots) This is invaluable in subs like r/diy. (I know you said earlier that it would be hard to add, I'm asking regardless)

![screenshot](http://i.imgur.com/nWSrULs.jpg)</githubroot></githubroot>

**Comment by ccrama** [comment]
Done with my latest commit
