### ISSUE TITLE
Post action bar covers thumbnails

### ISSUE THREAD

**Issue by joytrekker** [ccrama/Slide#985]
Using v4.6 alpha
If you set the post font to small or smaller the post action bar covers the thumbnail.
http://i.imgur.com/oeMtBmg.png

Setting the font to large and larger can make the text wrap in a strange way. Example the text "hours ago" can get split and "ago" will wrap to a new line but it aligns with username instead of the left margin.

**Comment by ccrama** [comment]
Fixed with my last commits
