### ISSUE TITLE
Inline video player freezes

### ISSUE THREAD

**Issue by joytrekker** [ccrama/Slide#986]
Using v4.6 alpha
Opening a video within slide will cause the app to freeze.
Also if you open the comments to a video the preview image has the default placeholder text "imgur" & "imgur.com/a/duARTe". The correct text is actually displayed at bottom where the post description would be if it were a self post.

**Comment by ccrama** [comment]
Fixed the video issue with my last update, working on the other one right now!

**Comment by ccrama** [comment]
Fixed both
