### ISSUE TITLE
On first start, drawer items are duplicated

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#988]
Occurs after the first time set-up 

![screenshot_2016-02-14-10-17-52](https://cloud.githubusercontent.com/assets/1830331/13033237/2c0d0e38-d307-11e5-8ab4-5535d1e5566d.png)

**Comment by ccrama** [comment]
Cannot reproduce :(

**Comment by l3d00m** [comment]
Had this too

**Comment by l3d00m** [comment]
But looks like it's not happening on newest commit

**Comment by ccrama** [comment]
I fixed it way back in v4.4

**Comment by Alexendoo** [comment]
Additionally it appears it's not loading fully either, note this only happens on the very first startup - after clearing data/or installing for the first time

![image](https://cloud.githubusercontent.com/assets/1830331/13035244/b0ccf738-d342-11e5-9e2e-ce5c7a5c3b34.png)

**Comment by Alexendoo** [comment]
Fixed with cfbad2f1bd1e9dbae5777bd67f115c1876f60f88 :+1:
