### ISSUE TITLE
Hide Not working as expected

### ISSUE THREAD

**Issue by prashantkhurana** [ccrama/Slide#995]
Check this out : 
https://imgur.com/a/P8WiO

The last pic has first post from r/india and second from r/steam and then I hid the first post. So shows the second pic. Now I click on the steam post and the india post opens up as shown in the 1st pic. 

So even though india post was hidden, it opens up. 

This is fixed temporarily by refreshing the page.

**Comment by prashantkhurana** [comment]
Awesome. Thanks. Can you push out a release with this change?

**Comment by ccrama** [comment]
I will in a day or two
