### ISSUE TITLE
Attempt to open album causes freeze and crash

### ISSUE THREAD

**Issue by LordManhattan** [ccrama/Slide#999]
The app will freeze, then crash after about 10 seconds after trying to open an album. 

02-15 22:54:06.674 E/ActivityManager(1137): ANR in me.ccrama.redditslide (me.ccrama.redditslide/.Activities.AlbumPager)

Slide version: 4.6.0-38-a72df68-dirty

**Comment by ccrama** [comment]
Fixed with my latest commit
